(function(){/*
 http://pcjs.org/modules/devices/device.js (C) Jeff Parsons 2012-2017
 http://pcjs.org/modules/devices/input.js (C) Jeff Parsons 2012-2017
 http://pcjs.org/modules/devices/led.js (C) Jeff Parsons 2012-2017
 http://pcjs.org/modules/devices/rom.js (C) Jeff Parsons 2012-2017
 http://pcjs.org/modules/devices/time.js (C) Jeff Parsons 2012-2017
 http://pcjs.org/modules/devices/ledctrl.js (C) Jeff Parsons 2012-2017
 http://pcjs.org/modules/devices/machine.js (C) Jeff Parsons 2012-2017
*/
var t,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var ea={ua:!0},fa={};try{fa.__proto__=ea;ca=fa.ua;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ba;
function u(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ba=b.prototype}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},y="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ja(){ja=function(){};y.Symbol||(y.Symbol=ka)}var ka=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();function la(){ja();var a=y.Symbol.iterator;a||(a=y.Symbol.iterator=y.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ia(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(this)}});la=function(){}}function ma(a){var b=0;return na(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}
function na(a){la();a={next:a};a[y.Symbol.iterator]=function(){return this};return a}function oa(a){la();var b=a[Symbol.iterator];return b?b.call(a):ma(a)}function pa(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function B(a,b){if(b){var c=y;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}B("Number.parseInt",function(a){return a||parseInt});
B("Math.trunc",function(a){return a?a:function(a){a=Number(a);if(isNaN(a)||Infinity===a||-Infinity===a||0===a)return a;var b=Math.floor(Math.abs(a));return 0>a?-b:b}});B("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}});B("Math.log2",function(a){return a?a:function(a){return Math.log(a)/Math.LN2}});
B("String.prototype.startsWith",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var b=this+"";a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var k=0;k<f&&c<e;)if(b[c++]!=a[k++])return!1;return k>=f}});var qa="Machine";
function D(a,b,c,d){this.j=d||{};this.v=a;this.oa=b;this.version=c||0;this.o={};E[this.v]||(E[this.v]=[]);E[this.v].push(this);ra(this,this.j);sa(this,this.j);ta(this,this.j.bindings)}var ua;
D.prototype.ba=function(a,b){var c=this;switch(a){case va:b.onclick=function(){var a=wa(c);a&&(a.value="")};break;case xa:b.value="",b.addEventListener("keypress",function(a){a=a||window.event;var d=a.which||a.keyCode;if(d){var f=b.value;b.setSelectionRange(f.length,f.length);a.stopPropagation();if(13==d&&(d=ya,d=F[c.v]&&F[c.v][d]))for(a.preventDefault(),f=b.value+="\n",b.blur(),b.focus(),a=f.slice(f.lastIndexOf("\n",f.length-2)+1,-1),f=0;f<d.length&&!d[f](a);f++);}})}};
function ta(a,b){var c=Array.isArray(b),d;for(d in b){var e=b[d];c&&(d=e);var f=document.getElementById(e);f?(a.o[d]=f,a.ba(d,f)):c||G(a,"unable to find device ID: "+e)}}function za(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function Aa(a,b){var c=ya;F[a.v]||(F[a.v]={});F[a.v][c]||(F[a.v][c]=[]);F[a.v][c].push(b)}
function sa(a,b){if(b.overrides){var c=Ba(),d;for(d in c)if(0<=b.overrides.indexOf(d)){var e=c[d];if(e.match(/^[+-]?[0-9.]+$/))var f=Number.parseInt(e,10);else"true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"');b[d]=f;G(a,"overriding "+a.oa+" property '"+d+"' with "+e)}}}
function ra(a,b){if(a.version){var c="",d=E[a.v];if(d)for(var e in d)if(d[e].oa==a.v){var f=d[e];break}if(f.version!=a.version){c="Machine";var k=f.version}else b.version&&b.version>a.version&&(c="Config",k=b.version);c&&(b="Error: "+a.ha("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.za,a.version,c,k)+"\n\nClearing your browser's cache may resolve the issue.",(c=Ca)&&0>Da.indexOf(c)&&(alert(b),Da.push(c)),G(a,b))}}
function wa(a){var b=xa,c=a.o[b];if(void 0===c){var d=E[a.v],e;for(e in d)if(c=d[e].o[b])break;c||(c=null);a.o[b]=c}return c}function H(a,b){if(a=E[a.v])for(var c in a)if(a[c].j["class"]==b){var d=a[c];break}return d}function Ea(a,b){return a.j.bindings&&a.j.bindings[b]}function Fa(a){if(a=a.o[Ga])var b=a.textContent;return b}function Ha(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c){a=a.j[b];void 0===a?a=c:(b=typeof c,typeof a!=b&&("boolean"==b?a=!!a:"number"==typeof c&&(a=+a)));return a}function Ia(a){if(void 0===Ja){var b=!1;if(window)try{window.localStorage.setItem(J,J),b=window.localStorage.getItem(J)==J,window.localStorage.removeItem(J)}catch(c){G(a,c.message),b=!1}Ja=b}return!!Ja}
function Ka(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function La(a,b){if(K&&0<=K.indexOf(Ma))L+=b;else{if(a=wa(a))a.value+=b,8192<a.value.length&&(a.value=a.value.substr(a.value.length-4096)),a.scrollTop=a.scrollHeight;a||(a=b.lastIndexOf("\n"),0<=a&&(console.log(L+b.substr(0,a)),L="",b=b.substr(a+1)),L+=b)}}function G(a,b){La(a,b+"\n")}
D.prototype.ca=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];La(this,this.ha.apply(this,[].concat([a],c instanceof Array?c:pa(oa(c)))))};function M(a,b,c){if(a=a.o[b])a.textContent=c}function Na(a,b){b=void 0===b?"":b;var c=K,d=!b&&K&&0<=K.indexOf(Ma);K=b;d&&(b=L,L="",La(a,b));return c}
D.prototype.ha=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]?)([0-9]*)(\.?)([0-9]*)([hlL]?)([A-Za-z%])/),f=0,k;for(k=0;k<e.length-7;k+=7){d+=e[k];var l=c[f++],g=e[k+1],n=+e[k+2]||0,h=+e[k+4]||0,m=e[k+6],p=null;switch(m){case "d":l=Math.trunc(l);case "f":m=Math.trunc(l)+"";h&&(n-=h+1);m.length<n&&("0"==g?(0>l&&n--,m=("0000000000"+Math.abs(l)).slice(-n),0>l&&(m="-"+m)):m=("          "+m).slice(-n));h&&(l=Math.trunc((l-Math.trunc(l))*Math.pow(10,
h)),m+="."+("0000000000"+Math.abs(l)).slice(-h));d+=m;break;case "s":for(;l.length<n;)l="-"==g?l+" ":" "+l;d+=l;break;case "X":p=Oa;case "x":p||(p=Pa);m="";do m=p[l&15]+m,l>>>=4;while(0<--n||l);d+=m;break;default:d+="(unrecognized printf conversion %"+m+")"}}return d+=e[k]};
function Ba(){var a,b=ua;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}ua=b}return b}var va="clear",xa="print",Ma="buffer",ya="command",Da=[],Ca="version",Ja=void 0,J="PCjs.localStorage",F={},E={},K="",L="",Pa="0123456789abcdef",Oa="0123456789ABCDEF";
function N(a,b,c){D.call(this,a,b,Qa,c);this.time=H(this,O);this.R=this.N=this.c=this.M=null;this.X=I(this,"drag",!1);this.O=I(this,"scroll",!1);this.g=!1;if(a=this.o[Ra]){b=this.j.location;this.ma=b[0];this.pa=b[1];this.f=b[2];this.m=b[3];this.s=b[4]||1;this.K=b[5]||1;this.ia=b[6]||a.naturalWidth||this.f;this.ka=b[7]||a.naturalHeight||this.m;this.$=b[8]||0;this.aa=b[9]||0;this.fa=b[10]||0;this.ja=b[11]||0;(this.b=this.j.map)?(this.w=this.b.length,this.i=this.b[0].length):(this.i=this.s,this.w=this.K,
this.s=this.K=0);this.da=I(this,"hexagonal",!1);this.a=I(this,"buttonDelay",0);this.T=this.f/(this.i+this.i*this.s)|0;this.V=this.m/(this.w+this.w*this.K)|0;this.ea=this.T*this.s|0;this.W=this.V*this.K|0;this.l=this.L=-1;Sa(this,a);Ta(this,a);if(this.time){var d=this;this.a&&(this.Z=Ua(this.time,"timerInputRelease",function(){0>d.l&&0>d.L&&P(d,-1,-1)}));this.b&&(this.a&&(this.la=Ua(this.time,"timerKeyRelease",function(){Va(d)})),this.h=0,this.u=[],Wa(this))}this.S=this.Y=-1}}u(N,D);
N.prototype.ba=function(a,b){var c=this;switch(a){case Xa:b.onclick=function(){c.c&&c.c()};break;case Ya:b.onclick=function(){c.N&&c.N()}}D.prototype.ba.call(this,a,b)};function Za(a,b,c){a.c=b;a.N=c}function $a(a,b){a.R=b}function ab(a,b){a.M=b}function bb(a){a.a?Q(a.time,a.la,a.a):Va(a)}
function Wa(a){var b=document;b.addEventListener("keydown",function(b){b=b||window.event;if(document.activeElement==a.o[Xa]){var c=cb[b.which||b.keyCode];c&&db(a,c)&&b.preventDefault()}});b.addEventListener("keypress",function(b){b=b||window.event;var c=String.fromCharCode(b.which||b.charCode);c&&db(a,c)&&b.preventDefault()})}
function Sa(a,b){b.addEventListener("mousedown",function(c){if(!a.g){var d=a.o[Xa];if(d){var e=window.scrollX,f=window.scrollY;d.focus();window.scrollTo(e,f)}c.button||R(a,b,eb,c)}});b.addEventListener("mousemove",function(c){a.g||R(a,b,fb,c)});b.addEventListener("mouseup",function(c){a.g||c.button||R(a,b,S,c)});b.addEventListener("mouseout",function(c){a.g||(0>a.l?R(a,b,fb,c):R(a,b,S,c))})}
function Ta(a,b){b.addEventListener("touchstart",function(c){a.O&&(a.g=!0);R(a,b,eb,c)});b.addEventListener("touchmove",function(c){R(a,b,fb,c)});b.addEventListener("touchend",function(c){R(a,b,S,c)})}function db(a,b){for(var c=0;c<a.b.length;c++)for(var d=a.b[c],e=0;e<d.length;e++)if(0<=d[e].split("|").indexOf(b))return a.h?16>a.u.length&&a.u.push(b):(a.h=1,P(a,e,c),bb(a)),!0;a.ca("unrecognized key '%s' (0x%02x)\n",b,b.charCodeAt(0));return!1}
function Va(a){1==a.h?(a.h++,P(a,-1,-1),bb(a)):(a.h=0,a.u.length&&db(a,a.u.shift()))}
function R(a,b,c,d){var e=-1,f=-1,k=!1,l;if(c<S){d=d||window.event;if(d.targetTouches&&d.targetTouches.length){var g=d.targetTouches[0].pageX;var n=d.targetTouches[0].pageY;k=1<d.targetTouches.length}else g=d.pageX,n=d.pageY;var h=l=0;var m=b;do isNaN(m.offsetLeft)||(l+=m.offsetLeft,h+=m.offsetTop);while(m=m.offsetParent);g=a.ia/b.offsetWidth*(g-l)|0;n=a.ka/b.offsetHeight*(n-h)|0;b=g-a.ma;var p=n-a.pa;h=l=!1;m=g>=a.$&&g<a.$+a.fa&&n>=a.aa&&n<a.aa+a.ja;if(0<=b&&b<a.f&&0<=p+a.W||m)if(k||a.O||d.preventDefault(),
0<=b&&b<a.f&&0<=p&&p<a.m){h=!0;d=a.f/a.i|0;var r=a.m/a.w|0,q=b/d|0,v=p/r|0;!a.da||v&1||(b-=d>>1,q=b/d|0,q==a.i-1&&(b=-1));r=v*r+(a.W>>1);b-=q*d+(a.ea>>1);p-=r;0<=b&&b<a.T&&0<=p&&p<a.V&&(e=q,f=v,l=!0)}}if(!k)if(c==eb)a.l=g,a.L=n,h?(P(a,e,f),l&&a.a&&Q(a.time,a.Z,a.a,!0)):m&&a.c&&a.c();else if(c==fb)0<=a.l&&0<=a.L&&a.X?P(a,e,f):a.R&&a.R(e,f);else if(c==S){if(c=a.a)c=a.time,e=a.Z,c=c.a&&0<e&&e<=c.b.length?0<=c.b[e-1].U:!1;c||P(a,-1,-1);a.l=a.L=-1}else G(a,"unrecognized action: "+c)}
function P(a,b,c){if(b!=a.S||c!=a.Y)a.S=b,a.Y=c,a.M&&a.M(b,c)}var eb=1,fb=2,S=3,Xa="power",Ya="reset",Ra="surface",cb={8:"\b"},Qa=1.11;
function gb(a,b,c){D.call(this,a,b,hb,c);a=this.o[ib];if(!a)throw Error("LED binding for '"+ib+"' missing: '"+this.j.o[ib]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.X=a;this.type=Ha(this.j.type||jb,jb,kb);this.m=lb[this.type][0];this.u=lb[this.type][1];this.width=I(this,"width",this.m);this.height=I(this,"height",this.u);this.h=I(this,"cols",1);this.b=this.h+I(this,
"colsExtra",0);this.R=I(this,"rows",1);this.f=this.R+I(this,"rowsExtra",0);this.S=this.width*this.h;this.O=this.height*this.R;this.i=T("black",0);this.g=mb(this.j.color)||this.i;this.aa=T(this.g,1,.25);this.$=T(this.g,1,2);this.l=mb(this.j.backgroundColor);this.da=I(this,"fixed",!1);this.da||(b.style.width="100%",b.style.height="auto");this.W=I(this,"hexagonal",!1);this.ea=I(this,"highlight",!0);this.N=I(this,"persistent",this.type<kb);b.setAttribute("width",this.S.toString());b.setAttribute("height",
this.O.toString());b.style.backgroundColor=this.i;a.appendChild(b);this.Y=b.getContext("2d");if(this.L=document.createElement("canvas"))this.L.width=this.V=this.m*this.h,this.L.height=this.T=this.u*this.R,this.c=this.L.getContext("2d");this.Z=(this.f+1)*this.b*4;this.a=Array(this.Z);this.w=null;this.fa=this.h<this.b?4*(this.b-this.h):0;this.s=this.K=!1;this.M=-1;var d=this;(this.time=H(this,O))&&nb(this.time,function(){U(d)})}u(gb,D);function ob(a,b){pb(a,a.a);a.s=a.K=!0;b&&U(a,!0)}
function qb(a){a.l?(a.c.fillStyle=a.l,a.c.fillRect(0,0,a.V,a.T)):a.c.clearRect(0,0,a.V,a.T)}
function U(a,b){b=void 0===b?!1:b;if(a.s||b){if(a.type<kb){a.N&&!b||qb(a);for(var c=0,d=0;d<a.f;d++){for(var e=0;e<a.h;e++){var f=a.a[c],k=a.a[c+1]||a.i,l=a.ea&&c==a.M;if(a.a[c+3]&V||l||b){a:{var g=a;var n=k;var h=e;k=d;var m=l;h=void 0===h?0:h;k=void 0===k?0:k;m=void 0===m?!1:m;var p=0;if(g.W&&!(k&1)&&(p=g.m>>1,h==g.h-1))break a;if(g.N){var r=h*g.m+p;var q=k*g.u;g.l?(g.c.fillStyle=g.l,g.c.fillRect(r,q,g.m,g.u)):g.c.clearRect(r,q,g.m,g.u)}n&&n!=g.g?(r=m?T(n,1,2):n,n=T(n,1,.25)):(r=m?g.$:g.g,n=g.aa);
m=!1;n=f?r:n;r==g.i&&(n=g.l,m=!0);g.c.fillStyle=n;f=h*g.m+p;k*=g.u;h=rb[g.type];3==h.length?(g.c.beginPath(),g.c.arc(h[0]+f,h[1]+k,h[2],0,2*Math.PI),m?(g.c.globalCompositeOperation="destination-out",g.c.fill(),g.c.globalCompositeOperation="source-over"):g.c.fill()):g.c.fillRect(h[0]+f,h[1]+k,h[2],h[3])}a.a[c+3]&=~V;l&&(a.a[c+3]|=V)}c+=4}c+=a.fa}}else{b="";for(c=0;c<a.a.length;c+=4)b+=a.a[c]||" ",a.a[c+3]&sb&&(b+=".");qb(a);for(e=d=c=0;c<b.length;c++){k=b[c];"."==k&&d&&d--;l=a;g=d;f=e;g=void 0===g?
0:g;f=void 0===f?0:f;if(k=tb[k])for(h=0;h<k.length;h++)if(p=l,m=ub[k[h]]){n=(void 0===g?0:g)*p.m;r=(void 0===f?0:f)*p.u;p.c.fillStyle=p.g;p.c.beginPath();if(3==m.length)p.c.arc(m[0]+n,m[1]+r,m[2],0,2*Math.PI);else for(q=0;q<m.length;q+=2)q?p.c.lineTo(m[q]+n,m[q+1]+r):p.c.moveTo(m[q]+n,m[q+1]+r);p.c.closePath();p.c.fill()}if(++d==a.h&&(d=0,++e==a.f))break}}a.Y.globalCompositeOperation=a.l&&!a.N?"source-over":"copy";a.Y.drawImage(a.L,0,0,a.V,a.T,0,0,a.S,a.O);a.s=!1;a.M=-1}else a.N||a.K||ob(a,!0);a.K=
!1}function vb(a,b,c){b=4*(c*a.b+b);return b<=a.a.length-4?a.a[b+2]:0}function W(a,b,c){var d;b=4*(c*a.b+b);0<=b&&b<=a.a.length-4&&(d=a.a[b]);return d}function mb(a){return(a=a||void 0)&&wb[a]||a}function T(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=wb[a]||a;if(xb(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}
function pb(a,b){for(var c=0;c<b.length;c+=4)b[c]=a.type<kb?X:" ",b[c+1]=a.g==a.i?null:a.g,b[c+2]=0,b[c+3]=V}function xb(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
function yb(a,b,c,d){var e=null;0<=c&&c<a.f&&0<=b&&b<a.b&&(e=!1,d=d||a.g,d==a.i&&(d=null),b=4*(c*a.b+b),a.a[b+1]!==d&&((a.a[b+1]=d)||(a.a[b]=X),a.a[b+3]|=V,a.s=e=!0),a.M=b,a.K=!0);return e}function zb(a,b,c,d){if(0<=c&&c<a.f&&0<=b&&b<a.b){b=4*(c*a.b+b);c=0;if(a.a[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.a[b+2]!==c&&(a.a[b+2]=c,a.a[b+3]|=V,a.s=!0);a.M=b;a.K=!0}}
function Y(a,b,c,d){var e=void 0===e?0:e;var f=null;if(0<=c&&c<a.f&&0<=b&&b<a.b){f=!1;b=4*(c*a.b+b);if(a.a[b]!==d||(a.a[b+3]&Ab)!==e)a.a[b]=d,a.a[b+3]=a.a[b+3]&~Ab|e|V,a.s=f=!0;a.M=b;a.K=!0}return f}
var jb=1,kb=3,ib="container",wb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",
darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",
goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",
lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",
olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",
slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},X=0,Ab=129,sb=1,V=128,Bb={},rb=(Bb[jb]=[16,16,14],Bb[2]=[2,2,28,28],Bb),lb=[[],[32,32],[32,32],[96,128]],ub={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,
104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},tb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),"-":["G"],E:["A","D","E","F","G"],".":["P"]},hb=1.11;
function Cb(a,b,c){D.call(this,a,b,Db,c);this.data=c.values;if(this.o[Eb]){var d=this;c=Math.log2(this.data.length)/2;this.b=Math.pow(2,Math.ceil(c));this.c=Math.pow(2,Math.floor(c));this.a=new gb(a,b+"LEDs",{"class":"LED",bindings:{container:Ea(this,Eb)},type:jb,cols:this.b,rows:this.c,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),ob(this.a,!0);this.f=new N(a,b+"Input",{"class":"Input",location:[0,0,this.a.S,this.a.O,this.b,this.c],bindings:{surface:Ea(this,
Eb)}});this.h=Fa(this);$a(this.f,function(a,b){if(d.g){var c=d.h;0<=a&&0<=b&&(a=b*d.b+a,c=d.g.Aa(d.data[a],a));M(d,Ga,c)}})}}u(Cb,D);var Eb="array",Ga="cellDesc",Db=1.11;
function Z(a,b,c){D.call(this,a,b,Fb,c);this.aa=I(this,"cyclesMinimum",1E5);this.ja=I(this,"cyclesMaximum",3E6);this.T=Ha(I(this,"cyclesPerSecond",65E4),this.aa,this.ja);this.K=Ha(I(this,"yieldsPerSecond",Gb),30,120);this.ka=Ha(I(this,"yieldsPerUpdate",Hb),1,this.K);this.X=I(this,"requestAnimationFrame",!0);this.fa=this.ia=this.O=1;this.Z=this.T/1E4/100;this.g=this.m=this.Z*this.O;this.u=0;this.S=Math.round(1E3/this.K);this.V=[];this.R=[];this.b=[];this.W=[];this.a=this.Y=this.l=!1;this.w=this.f=
0;this.ma=this.xa.bind(this);this.la=this.ea.bind(this);this.da=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);var d=this;Ua(this,"timerYield",function(){d.Y=!0;var a=d.u,b=Ib(d);b>=d.K?d.u++:d.u+=Math.ceil(d.K/b);d.u>=d.ka&&a<d.ka&&Jb(d);d.u>=d.K&&(d.u=0)},this.S);this.M=this.L=this.i=0;Kb(this)||Lb(this,this.fa)}u(Z,D);function nb(a,b){a.V.push(b)}
Z.prototype.ba=function(a,b){var c=this;switch(a){case Mb:b.onclick=function(){c.a?Nb(c):c.start()};break;case Ob:b.onclick=function(){c.a?G(c,"already running"):c.f?Nb(c):Pb(c,void 0)};break;case Qb:b.addEventListener("mousedown",function(){c.l=!0}),b.addEventListener("mouseup",function(){Kb(c);c.l=!1}),b.addEventListener("mousemove",function(){c.l&&Kb(c)}),b.addEventListener("change",function(){c.l=!0;Kb(c);c.l=!1})}D.prototype.ba.call(this,a,b)};
function Ua(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,va:c,na:d,U:-1});0<=d&&Q(a,e,d);return e}Z.prototype.ea=function(){for(var a=0;a<this.V.length;a++)this.V[a]();this.a&&this.X&&this.da(this.la)};function Rb(a){var b=a.g/a.Z;if(!b||b>a.O)b=a.O;a.pa=a.T/a.K*b;a.ia=b}function Sb(a,b,c){a.L=a.i=b;if(!a.R.length)return a.i=0,a.L;for(var d=0;0<a.i;)d<a.R.length?b=a.R[d++](c?0:b)||1:d=b=0,a.i-=b;return a.L-a.i}
function Tb(a,b){b=void 0===b?a.L-a.i:b;a.L=a.i=0;a.N+=b;a.M+=b;a.a||(a.M=0);return b}function Ib(a,b){return Math.ceil(a.T*a.ia/1E3*(void 0===b?1E3:b))}function Ub(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}
Z.prototype.xa=function(){this.w=0;if(this.a){Rb(this);this.$=this.N=0;this.s=Date.now();this.c||(this.c=this.s);if(this.h){var a=this.s-this.h;a>this.S&&(this.c+=a,this.c>this.s&&(this.c=this.s))}try{this.Y=!1;do{for(var b=Ib(this,this.S),c=this.b.length;0<c;c--){var d=this.b[c-1];!(0>d.U)&&b>d.U&&(b=d.U)}Vb(this,Tb(this,Sb(this,b)))}while(this.a&&!this.Y)}catch(e){G(this,e.message);Nb(this);return}if(this.a){a=setTimeout;b=this.ma;this.h=Date.now();this.$&&(this.c+=this.$,this.s+=this.$);c=this.S;
this.N&&(c=Math.round(c*this.N/this.pa));c-=this.h-this.s;if(d=this.h-this.c)this.g=this.M/(10*d)/100;0>c?(-1E3>c&&(this.c-=c),c=0):this.g<this.m&&(c=0);this.h+=c;K&&0<=K.indexOf("time")&&this.ca("after running %d cycles, resting for %dms\n",this.N,c);this.w=a(b,c);this.X||this.ea()}}};function Kb(a){var b=a.o[Qb];return b?(Lb(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.ja-a.aa)+a.aa)/a.T),!0):!1}
function Lb(a,b){void 0!==b&&(!a.l&&0<a.g&&a.g<.9*a.m&&(b=a.fa),a.O=b,b=a.Z*a.O,a.m!=b&&(a.m=b,M(a,Wb,Ub(a.m))),a.g=a.m);a.M=0;a.c=a.h=0;Rb(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.na&&Q(a,b,c.na,!0)}}function Q(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.U)&&(c=Ib(a,c),a.a&&(c+=Tb(a)),b.U=c)}Z.prototype.start=function(){if(this.a||this.f)return!1;this.w&&(clearTimeout(this.w),this.w=0);this.a=!0;this.c=this.h=0;Jb(this,!0);this.w=setTimeout(this.ma,0);this.X&&this.da(this.la);return!0};
function Pb(a,b){b=void 0===b?1:b;a.a||(b&&!a.f&&(a.f=b),a.f&&(a.f--,Vb(a,Tb(a,Sb(a,1,!0))),Jb(a),a.f&&setTimeout(function(){Pb(a,0)},0)))}function Nb(a){a.f?(a.f=0,Jb(a,!0)):a.a&&(a.a=!1,Tb(a),Jb(a,!0))}function Jb(a,b){b&&(a.a?G(a,"starting (target speed: "+Ub(a.m)+")"):G(a,"stopping"));M(a,Mb,a.a?"Halt":"Run");M(a,Ob,a.f?"Stop":"Step");a.l||M(a,Wb,a.a&&a.g?Ub(a.g):"Stopped");for(var c=0;c<a.W.length;c++)a.W[c](b)}
function Vb(a,b){for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.U||(d.U-=b,0>=d.U&&(d.U=-1,d.va(),0<=d.na&&Q(a,c,d.na)))}}var Mb="run",Wb="speed",Ob="step",Qb="throttle",Gb=120,Hb=60,Fb=1.11;
function Xb(a,b,c){D.call(this,a,b,Yb,c);this.h=I(this,"wrap",!1);this.s=I(this,"rule","");this.i=I(this,"pattern","");this.m=I(this,"symbols","");this.N=I(this,"toggleColor",!1);this.M=Array(Zb(this).length);if(c=H(this,$b)){this.a=c;ac(this)||ob(c,!0);(this.f=H(this,bc))&&Za(this.f,this.ga.bind(this),this.qa.bind(this));var d=this;this.K=new N(a,b+"Input",{"class":"Input",location:[0,0,c.S,c.O,c.h,c.R],drag:!(!this.f||!this.f.X),scroll:!(!this.f||!this.f.O),hexagonal:c.W,bindings:{surface:Ea(c,
ib)}});ab(this.K,function(a,b){var c=d.a;0<=a&&0<=b&&(d.g?yb(c,a,b,d.g)?Y(c,a,b,1):d.N?yb(c,a,b):Y(c,a,b,1-W(c,a,b)):Y(c,a,b,1-W(c,a,b)),zb(c,a,b,Zb(d,!!W(c,a,b))),U(c))});this.c=[];this.L=c.g;cc(this,this.L);dc(this);ec(this,this.j[fc]);if(this.time=H(this,O))this.time.R.push(this.wa.bind(this)),this.time.W.push(this.ta.bind(this));this.w="";Aa(this,this.ya.bind(this));this.u=this.l=0}}u(Xb,D);t=Xb.prototype;
t.ba=function(a,b){var c=this;switch(a){case gc:case hc:b.onchange=function(){ic(c,a)};ic(this);break;case fc:b.onchange=function(){ec(c)};break;case jc:za(b,kc(this.j[jc]),!1,this.j.pattern);b.onchange=function(){var a=c.o[jc];a&&a.options.length&&((a=a.options[a.selectedIndex].value)?ac(c,a):c.qa())};break;case lc:b.onclick=function(){var a=mc(c,!0),b=c.o[nc];b&&(a='"'+b.value+'":"'+a+'",');G(c,a)};break;case oc:b.onclick=function(){var a=mc(c);G(c,a);var b=window.location.href;b=0<=b.indexOf("pattern\x3d")?
b.replace(/(pattern=)[^&]*/,"$1"+a.replace(/\$/g,"$$$$")):b+((0>b.indexOf("?")?"?":"\x26")+"pattern\x3d"+a);window.location=b};break;case nc:b.onkeypress=function(a){b.value=String.fromCharCode(a.charCode);var d=c.o[pc];d&&(d.textContent=b.value);a.preventDefault()};break;default:if(a.startsWith(qc))b.onclick=function(){dc(c,a)};else{var d=this.j[jc];d&&d[a]&&(b.onclick=function(){ac(c,a)})}}D.prototype.ba.call(this,a,b)};
function kc(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
t.wa=function(a){a=void 0===a?0:a;var b=0;if(0<=a){do{switch(this.s){case rc:var c=0;for(var d=this.a,e=d.b,f=d.f,k=this.M,l=0;l<f;l++)for(var g=0;g<e;g++){var n=k,h=!1,m=4*(l*d.b+g);if(m<=d.a.length-4&&d.a[m+1]){h=!0;m=d.a[m+2];for(var p=n.length-1;0<=p;p--)n[p]=m&15,m>>>=4}if(h){c++;if(k[0])k[0]--;else{h=(n=W(d,g,l))||0;switch(n){case 1:if(h=X,k[0]=k[2],k[0]){k[0]--;break}case X:if(k[3]&&(h=this.c.indexOf(d.a[4*(l*d.b+g)+1]||d.i),0<=h)){for(h+=k[3];h>=this.c.length;)h-=this.c.length;yb(d,g,l,this.c[h])}h=
1;k[0]=k[1];k[0]&&k[0]--}h!==n&&Y(d,g,l,h)}zb(d,g,l,k)}}break;case sc:c=1;c=void 0===c?1:c;d=0;e=this.a;f=e.b;k=e.f;!this.l&&this.m&&this.u<this.m.length&&(this.l=tc(this,e.h,0,uc[this.m[this.u++]],!0));for(l=0;l<k;l++)for(g=0;g<f-c;g++)(n=W(e,g,l)||X)&&d++,Y(e,g,l,W(e,g+1,l)||X),Y(e,g+1,l,n);this.l&&this.l--;c=d;break;case vc:c=0;d=this.a.a;e=this.a;e.w||(e.w=Array(e.Z),pb(e,e.w));e=e.w;f=this.a.b;k=this.a.f;l=4*f;g=k*l;n=0;h=n-l;m=h-4;p=h+4;for(var r=n-4,q=n+4,v=n+l,x=v-4,w=v+4,C=0;C<k;C++){C?C==
k-1&&(this.h?(v-=g,x-=g,w-=g):v=x=w=g):this.h?(h+=g,m+=g,p+=g):h=m=p=g;for(var z=0;z<f;z++){z?1==z?this.h?(r-=l,m-=l,x-=l):(r=n-4,m=h-4,x=v-4):z==f-1&&(this.h?(q-=l,p-=l,w-=l):q=p=w=g):this.h?(r+=l,m+=l,x+=l):r=m=x=g;var A=d[n],da=d[m]+d[h]+d[p]+d[q]+d[w]+d[v]+d[x]+d[r];3==da?A=1:2!=da&&(A=X);e[n]=A;e[n+1]=d[n+1];e[n+2]=d[n+2];e[n+3]=d[n+3]|(d[n]!==A?V:0);n+=4;m+=4;h+=4;p+=4;q+=4;w+=4;v+=4;x+=4;r+=4;1==A&&c++}this.h?(C||(h-=g,m-=g,p-=g),q+=l,p+=l,w+=l):(C||(h=n-l,m=h-4),q=n+4,p=h+4,w=v+4)}d=this.a;
e=d.a;d.a=d.w;d.w=e;d.s=!0}a||G(this,"living cells: "+c);b+=1}while(b<a)}return b};function wc(a,b){var c=0;(a=a.o[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}function Zb(a,b){var c=0;if(b&&(b=a.o[xc])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=wc(a,yc)+wc(a,zc),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<Ac.length;b++)c.push(wc(a,Ac[b]));return c}
function ac(a,b){var c=a.a,d=-1,e=-1,f="";b||a.i.match(/^[0-9]/)||(b=a.i);if(b){var k=a.j[jc];k=k&&k[b];if(!k)return G(a,"unknown pattern: "+b),!1;G(a,"loading pattern '"+b+"'");for(var l=b=0;b<k.length;b++){var g=k[b];if("#"==g[0])G(a,g);else if(l++){var n=g.indexOf("!");if(0<=n){f+=g.substr(0,n);break}f+=g}else{var h=g.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!h)return G(a,"unrecognized header line"),!1;var m=+h[1];var p=+h[2];h=h[3]}}}else{if(!a.i)return!1;
f=0;h=a.i.split("/");5==h.length&&(d=+h[f++],e=+h[f++]);if(3==h.length||5==h.length)m=+h[f++],p=+h[f++],f=h[f];else return G(a,"unrecognized pattern: "+a.i),!1;h=a.s}if(h!=a.s)return G(a,"unsupported rule: "+h),!1;0>d&&(d=c.b-m>>1);0>e&&(e=c.f-p>>1);return 0>d||d+m>c.b||0>e||e+p>c.f?(a.ca("pattern too large (%d,%d)\n",m,p),!1):0<tc(a,d,e,f)}
function tc(a,b,c,d,e){e=void 0===e?!1:e;var f=a.a,k=[0,0,0,1],l=0,g=!1,n=!1;d=d.split(/([a-z$])/i);e||ob(f);for(var h=0,m=b,p=0;h<d.length-1;){var r=d[h++],q=d[h++],v=+r;for(r=""===r?1:v;r--;){var x=0,w=!1;switch(q){case "$":g=n=!1;b=m;c++;break;case "C":l=v;n=!0;break;case "R":k[0]=v;g=!0;break;case "G":k[1]=v;g=!0;break;case "B":k[2]=v;g=!0;break;case "A":k[3]=v;g=!0;break;case "b":w=Y(f,b,c,X);x++;break;case "o":w=Y(f,b,c,1);x++;break;default:a.ca("unrecognized pattern token: %s\n",q)}null==w?
a.ca("invalid pattern position (%d,%d)\n",b,c):(g&&yb(f,b,c,4>k.length||1==k[3]?f.ha("#%02x%02x%02x",k[0],k[1],k[2]):f.ha("rgba(%d,%d,%d,%d)",k[0],k[1],k[2],k[3])),n&&(w=4*(c*f.b+b),w<=f.a.length-4&&f.a[w+2]!=l&&(f.a[w+2]=l)),p<b&&(p=b),b+=x)}}e||U(f,!0);return 0>(p-=m-1)?0:p}
t.ya=function(a){var b="";""==a&&(a=this.w);this.w="";a=a.trim();var c=a.split(" "),d=c[1];switch(c[0][0]){case "c":d?(G(this,"set category '"+d+"'"),Na(this,d)):(d=Na(this))?G(this,"cleared category '"+d+"'"):G(this,"no category set");break;case "?":b="available commands:";Bc.forEach(function(a){b+="\n"+a});break;default:a&&(b="unrecognized command '"+a+"' (try '?')")}b&&G(this,b.trim());return!0};t.ga=function(a){this.time&&(a?this.time.start():Nb(this.time))};
t.qa=function(){G(this,"reset");ob(this.a,!0)};
t.ra=function(){var a=null;if(Ia(this)){var b;if(window)try{(b=window.localStorage.getItem(this.v))&&(a=JSON.parse(b))}catch(e){G(this,e.message)}}if(a)if((b=a.stateChip||a[0])&&b.length)if(b=b.shift(),(b|0)!==(Yb|0))this.ca("Saved state version mismatch: %3.2f\n",b);else{if(!Ba().pattern&&!Ba()[fc]){var c=a.stateLEDs||a[1];if(c&&this.a&&!this.m){a=this.a;b=c.shift();var d=c.shift();c=c.shift();if(b==a.g&&d==a.l&&c&&c.length==a.a.length){a.a=c;for(b=0;b<=a.a.length-4;b+=4)a.a[b+1]==a.i&&(a.a[b+1]=
null);U(a,!0)}}}}else G(this,"Invalid saved state")};t.sa=function(){var a=[[],[]],b=a[1];a[0].push(Yb);if(this.a){var c=this.a;c.a&&(b.push(c.g),b.push(c.l),b.push(c.a))}if(Ia(this)){a=JSON.stringify(a);try{window.localStorage.setItem(this.v,a)}catch(d){G(this,d.message)}}};
function mc(a,b){function c(a){var b=!1;null==h[3]&&(h[3]=1);if(x){if(g){if(h[0]!==q[0]||h[1]!==q[1]||h[2]!==q[2]||h[3]!==q[3])b=!0;da!==v&&(b=!0)}n!==r&&(b=!0);if(b||a&&r)g&&(m[0]!==q[0]&&(m[0]=q[0],e+=(q[0]||"")+"R"),m[1]!==q[1]&&(m[1]=q[1],e+=(q[1]||"")+"G"),m[2]!==q[2]&&(m[2]=q[2],e+=(q[2]||"")+"B"),m[3]!==q[3]&&(m[3]=q[3],e+=(q[3]||"")+"A"),p!==v&&(p=v,e+=(v||"")+"C")),1<x&&(e+=x),e+=1===r?"o":"b",b=!0}a?(e+="$",x=0):(b?x=1:x++,r=n,q[0]=h[0],q[1]=h[1],q[2]=h[2],q[3]=h[3],v=da)}var d=a.a,e="",
f=0,k=a.a.b,l=a.a.f,g=!!a.c.length,n,h=[0,0,0],m=[0,0,0,1],p=0,r=0,q=[0,0,0,1],v=0,x=0;a=0;var w=d.b-1,C=d.f-1;if(b){b&&(a=w,w=0);for(k=0;k<d.f;k++)for(l=0;l<d.b;l++)(n=W(d,l,k))&&b&&(a>l&&(a=l),w<l&&(w=l));k=w-a+1;l=C-0+1;0>k&&(k=0);0>l&&(l=0)}for(var z=0;z<=C;z++){for(var A=a;A<=w;A++){n=W(d,A,z);xb(d.a[4*(z*d.b+A)+1]||d.i,h);var da=vb(d,A,z);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,l--,e=e.slice(1);for(;"$$"==e.slice(-2);)l--,e=e.slice(0,-1);"$"==e&&(l=0);e=(b?"":"0/"+f+"/")+k+"/"+l+"/"+e.slice(0,-1);
return e=e.replace(/\$+$/,"")}function ec(a,b){var c=a.o[fc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.a;a.X&&(a.X.style.backgroundImage=b?"url('"+b+"')":"none")}}
function ic(a,b){var c=a.o[gc],d=a.o[hc];b=b===gc;c&&!c.options.length&&(za(c,a.j.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.b=a.j.colors[c.options[c.selectedIndex].value];for(var e in a.b)if(b=a.j[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),G(a,"overriding color '"+e+"' with "+b+" (formerly "+a.b[e]+")"),a.b[e]=b;za(d,a.b,!0)}c&&d&&d.options.length&&(a.g=d.options[d.selectedIndex].value,dc(a))}
function cc(a,b){var c=a.o[hc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.g=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function dc(a,b){var c=1,d;!b&&a.g&&(d=a.o[Cc])&&(d.style.backgroundColor=a.g);if(a.b)for(var e in a.b){var f=a.b[e];a.c&&(a.c[c-1]=f);var k=qc+c++;d=a.o[k];if(!d)break;d.style.display="inline-block";k==b&&cc(a,f);if(b&&b!=k||f!=a.g)f=T(f,1,.5);d.style.backgroundColor=f}for(;;){b=qc+c++;b=a.o[b];if(!b)break;b.style.display="none"}}t.ta=function(){this.time.a||U(this.a)};
var gc="colorPalette",hc="colorSelection",qc="colorSwatch",Cc="colorSwatchSelected",xc="countInit",yc="countOn",zc="countOff",fc="backgroundImage",jc="patterns",nc="symbolInput",pc="symbolPreview",lc="save",oc="saveToURL",Ac=[null,yc,zc,"countCycle"],Bc=["c\tset category"],rc="A4",sc="L1",vc="B3/S23",uc={A:"10/14/$3b4o$2bo4bo$2bo4bo$bo6bo$bo6bo$o8bo$o8bo$o8bo$10o$o8bo$o8bo$o8bo$o8bo",B:"10/14/$7o$o6bo$o7bo$o7bo$o7bo$o6bo$8o$o7bo$o8bo$o8bo$o8bo$o8bo$9o",C:"8/14/$2b6o$bo$o$o$o$o$o$o$o$o$o$bo$2b6o",
D:"10/14/$8o$o7bo$o8bo$o8bo$o8bo$o8bo$o8bo$o8bo$o8bo$o8bo$o8bo$o7bo$8o",E:"8/14/$8o$o$o$o$o$o$7o$o$o$o$o$o$8o",F:"8/14/$8o$o$o$o$o$o$o$7o$o$o$o$o$o",G:"9/14/$2b6o$bo$o$o$o$o$o$o$o6b2o$o7bo$o7bo$bo6bo$2b7o",H:"10/14/$o8bo$o8bo$o8bo$o8bo$o8bo$o8bo$10o$o8bo$o8bo$o8bo$o8bo$o8bo$o8bo",I:"7/14/$7o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$7o",J:"9/14/$8bo$8bo$8bo$8bo$8bo$8bo$8bo$8bo$o7bo$o7bo$o7bo$bo5bo$2b5o"},Yb=1.11;qa="LEDs";
function Dc(a,b){D.call(this,a,a,Ec);try{this.j=JSON.parse(b);var c=this.j[a];ra(this,c);sa(this,c);ta(this,c.bindings);this.a=!1!==c.autoPower}catch(k){c=k.message;var d=c.match(/position ([0-9]+)/);d&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')");G(this,"machine '"+a+"' initialization error: "+c)}var e=this,f=null;window.addEventListener("load",function(){for(var a,b,c,d,h=0;h<Fc.length;h++)for(a in e.j)try{var m=e.j[a],p="";b=m["class"];if(b==Fc[h]){switch(b){case Gc:d=c=new Xb(e.v,
a,m);break;case bc:c=new N(e.v,a,m);break;case $b:c=new gb(e.v,a,m);break;case Hc:c=new Cb(e.v,a,m);c.j.revision&&(p="revision "+c.j.revision);break;case O:c=new Z(e.v,a,m);break;case Ic:e.ca("PCjs %s v%3.2f\n",m.name,Ec);G(e,Jc);G(e,Kc);continue;default:G(e,"unrecognized device class: "+b);continue}G(e,b+" device initialized"+(p?" ("+p+")":""))}}catch(v){G(e,"error initializing "+b+" device '"+a+"':\n"+v.message);p=void 0;var r=a,q=E[e.v];if(q)for(p in q)if(q[p].oa==r){q.splice(p,1);break}}if(f=
d)f.ra&&f.ra(),f.ga&&e.a&&f.ga(!0)});window.addEventListener((Ka("iOS")?"pagehide":Ka("Opera")?"unload":void 0)||"beforeunload",function(){f&&(f.sa&&f.sa(),f.ga&&f.ga(!1))})}u(Dc,D);var Gc="Chip",bc="Input",$b="LED",Ic="Machine",Hc="ROM",O="Time",Fc=[Ic,O,$b,bc,Hc,Gc],Jc="Copyright \u00a9 2012-2017 Jeff Parsons \x3cJeff@pcjs.org\x3e",Kc="License: GPL version 3 or later \x3chttp://gnu.org/licenses/gpl.html\x3e",Ec=1.11;window[qa]=Dc;})()
//# sourceMappingURL=leds.js.map
