(function(){/*
 https://www.pcjs.org/modules/shared/lib/dumpapi.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/reportapi.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/strlib.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/weblib.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/embed.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/defines.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/usrlib.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/shared/lib/component.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/defines.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/panel.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/cpu.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/rom.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/ram.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/keyboard.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/video.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/serial.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/disk.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/debugger.js (C) Jeff Parsons 2012-2018
 https://www.pcjs.org/modules/c1pjs/lib/computer.js (C) Jeff Parsons 2012-2018
*/
var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={Lb:!0},ea={};try{ea.__proto__=da;ca=ea.Lb;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function p(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ve=b.prototype}var ha="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ia="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ja(a){if(a){for(var b=ia,c=["Math","trunc"],d=0;d<c.length-1;d++){var e=c[d];e in b||(b[e]={});b=b[e]}c=c[c.length-1];d=b[c];a=a(d);a!=d&&null!=a&&ha(b,c,{configurable:!0,writable:!0,value:a})}}ja(function(a){return a?a:function(a){a=Number(a);if(isNaN(a)||Infinity===a||-Infinity===a||0===a)return a;var b=Math.floor(Math.abs(a));return 0>a?-b:b}});
function q(a,b,c){b?9<b&&(b=9):(b=Math.abs(a),b=65535>=b?4:4294967295>=b?8:9);c=c?"0x":"";var d=void 0===d?0:d;var e="";isNaN(a)||"number"!=typeof a?a=null:(0>a&&-1<a&&(a=-1),0>a&&(a+=Math.pow(16,b)),a>=Math.pow(16,b)&&(b=Math.ceil(Math.log(a)/Math.log(16))));for(var g=d||-1;0<b--;){g||(e=","+e,g=d);if(null==a)e="?"+e;else{var k=a%16;k+=0<=k&&9>=k?48:55;e=String.fromCharCode(k)+e;a=Math.trunc(a/16)}g--}return(void 0===c?"":c)+e}function t(a){return q(a,2,!0)}function u(a){return q(a,4,!0)}
function ka(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("\x26");0<c&&(b=b.substr(0,c));return b}function la(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase());return b}function ma(a){return a.replace(/[&<>"']/g,function(a){return na[a]})}var na={"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#039;"},oa=Date.now||function(){return+new Date};
function w(a,b){var c=null,d=!0;c=void 0===c?"text":c;d=void 0===d?!1:d;var e=0,g=null;if("object"==typeof resources&&(g=resources[a]))b&&b(a,g,e);else if(d&&"function"==typeof resources)resources(a,function(c,d){b&&b(a,c,d)});else{a=a.replace(/^\/(pcjs-disks|pcjs-games|private-disks)\//,"https://jeffpar.github.io/$1/");var k=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP"),l=!1,h="string"===typeof k.responseType,m=function(){if(4!==k.readyState)return null;
try{g=l?k.response:k.responseText}catch(r){}if(null==g||200!=k.status&&(k.status||!g.length||"file:"!=(window?window.location.protocol:"file:")))e=k.status||-1;b&&b(a,g,e);return[g,e]};d&&(k.onreadystatechange=m);if(c&&"object"==typeof c){h="";for(var n in c)c.hasOwnProperty(n)&&(h&&(h+="\x26"),h+=n+"\x3d"+encodeURIComponent(c[n]));h=h.replace(/%20/g,"+");k.open("POST",a,d);k.setRequestHeader("Content-type","application/x-www-form-urlencoded");k.send(h)}else k.open("GET",a,d),"arraybuffer"==c&&(h?
(l=!0,k.responseType=c):k.overrideMimeType("text/plain; charset\x3dx-user-defined")),k.send();d||(k.readyState=4,m())}}function x(a){if(window){var b=window?window.navigator.userAgent:"";return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function pa(){var a,b=qa("mobile");if(b)return"true"==b;if(x("Mobi")){if(!a)return!0;(b="!"==a[0])&&(a=a.substr(1));return x(a)!=b}return!1}
function qa(a){if(!ra){var b,c={};if(window){b||(b=window.location.search.substr(1));for(var d,e=/\+/g,g=/([^&=]+)=?([^&]*)/g;d=g.exec(b);)c[decodeURIComponent(d[1].replace(e," "))]=decodeURIComponent(d[2].replace(e," "))}ra=c}return ra[a]||ra[a.toLowerCase()]}function sa(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function ta(a,b){function c(){b(100===d)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,g=!1;a.onmousedown=function(){g||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);g=!0}}function ua(a,b){if(window){var c=window[a];window[a]="function"!==typeof c?b:function(){c&&c();b()}}}function y(a){z.init.push(a)}
function va(a){if(wa)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){A("An unexpected error occurred: "+c.message+"\n\nIf it happens again, please send the URL to support@pcjs.org. Thanks.")}}function B(a){!wa&&a?(wa=!0,xa&&ya("init"),za&&ya("show")):wa=a}function ya(a){z[a]&&va(z[a])}var ra=null,z={init:[],show:[],exit:[]},xa=!1,za=!1,wa=!0;ua("onload",function(){xa=!0;va(z.init)});ua("onpageshow",function(){za=!0;va(z.show)});ua(x("iOS")?"onpagehide":x("Opera")?"onunload":"onbeforeunload",function(){va(z.exit)});
function C(a,b,c){this.type=a;b||(b={id:"",name:""});this.id=b.id||"";this.name=b.name;this.exports={};this.H=this.bindings={};a=this.id.indexOf(".");0>a?this.cb="PCjs":this.cb=this.id.substr(0,a);this.D={ready:!1,Ja:!1,$a:!1,Ue:!1,N:!1,Ne:!1,error:!1};this.bb=null;this.D.error=!1;this.la=c||0;this.v=this.u=this.U=null;D.push(this)}function A(a){window&&window.alert(a)}function Aa(a,b){a.value+=b;b=a.value;8192<b.length&&(a.value=b.substr(b.length-4096));a.scrollTop=a.scrollHeight}
function F(a,b){b=G(b.parentNode,"c1pjs-control");for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var g=d[e];if(1===g.nodeType){var k=g.getAttribute("class");if(k)for(var l=k.split(" "),h=0;h<l.length;h++)switch(k=l[h],k){case "c1pjs-binding":(k=H(g))&&void 0!==k.binding&&a.T(k.type,k.binding,g,k.value),h=l.length}}}}function Ba(a,b){if(void 0!==a){var c;b&&0<(c=b.indexOf("."))&&(a=b.substr(0,c+1)+a);for(c=0;c<D.length;c++)if(D[c].id===a)return D[c]}return null}
function Ca(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<D.length;d++)if(c)c==D[d]&&(c=null);else if(!(a!=D[d].type||b&&D[d].id.indexOf(b)))return D[d]}return null}function H(a){var b=null;if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(c){A(c.message+" ("+a+")")}return b}
function G(a,b,c){c&&(b+="-"+c+"-object");if(a.getElementsByClassName)return a.getElementsByClassName(b);var d;c=[];a=a.getElementsByTagName("*");var e=new RegExp("(^| )"+b+"( |$)");b=0;for(d=a.length;b<d;b++)e.test(a[b].className)&&c.push(a[b]);return c}
function Da(a){for(var b=!0,c=I[a];c&&c.length;){var d=c.splice(0,1)[0],e=d[0],g=null;0<=Ea.indexOf(e)&&(g=function(){return function(){Da(a)}}());var k=Fa[e];if(k)if(!g)b=k(d[1],d[2],d[3]);else{if(!k(g,d[1],d[2],d[3]))break}else{b=!1;var l=Ca(d[1],a);if(l)if(k=Ga[e])b=k(l,d[2],d[3]);else{var h=l.exports;if(h&&(k=h[e]))if(b=!0,!g)b=k.call(l,d[2],d[3]);else if(!k.call(l,g,d[2],d[3]))break}}if(!b){A("Script error: '"+e+"' command "+(k?" failed":" not recognized"));break}}c&&!c.length&&delete I[a];return b}
f=C.prototype;f.toString=function(){return this.name?this.name:this.id||this.type};
f.T=function(a,b,c){switch(b){case "clear":return this.H[b]||(this.H[b]=c,c.onclick=function(a){return function(){a.H.print&&(a.H.print.value="")}}(this)),!0;case "print":return this.H[b]||(this.H[b]=c,this.Va=function(a){this.l(a,this.type);return!0},c.value="",this.print=function(a){return function(b){Aa(a,b)}}(c),this.l=function(a,b){return function(a,c){a||(a="");if(c!=Ha||"..."!=a.slice(-3))c&&(a=c+": "+a),Aa(b,a+"\n");else{c=b.value;var d=c.lastIndexOf(a);0>d?c+=a+"\n":c=c.substr(0,d)+(a+".")+
c.substr(d+a.length);8192<c.length&&(c=c.substr(c.length-4096));b.value=c;b.scrollTop=b.scrollHeight}}}(this,c)),!0;default:return!1}};f.log=function(){};f.print=function(){};f.l=function(){};f.status=function(a){this.l(this.type+": "+a)};f.Va=function(a,b,c){if(!b){var d=Ca("Computer",this.id);if(d&&d.D.Ne)return console.log("ignoring notice during unload: "+a),!1}c=c||this.type;b||A((c?c+": ":"")+a);return!0};function Ia(a,b){a.D.error=!0;a.Va(b)}
function J(a,b){b&&(a.D.ready?b():a.bb=b);return a.D.ready}f.X=function(){if(!this.D.error&&(this.D.ready=!0,this.D.ready)){var a=this.bb;this.bb=null;a&&a()}};function K(a,b){a.D.Ja&&(b?a.D.$a=!0:void 0===b&&a.l(a.toString()+" busy"));return a.D.Ja}function L(a,b){if(a.D.$a)return a.D.Ja=!1,a.D.$a=!1;if(a.D.error)return a.l(a.toString()+" error"),!1;a.D.Ja=b;return a.D.Ja}
function M(a,b){b=void 0===b?0:b;return a.v&&(a!==a.v&&(b=b||a.la),a=a.v.la&b,b&4026531840&&b&268435455&&(a&4026531840&&a&268435455||(a=0)),b&&a===b)?!0:!1}var Ha="progress";window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]),window.PCjs.Commands||(window.PCjs.Commands={}));
var N=window?window.PCjs.Machines:{},D=window?window.PCjs.Components:[],I=window?window.PCjs.Commands:{},Ea=["hold","sleep","wait"],Fa={alert:function(a){A(a);return!0},sleep:function(a,b){setTimeout(a,+b);return!1}},Ga={select:function(a,b,c){var d=!1;if(a=a.bindings[b])for(b=0;b<a.options.length;b++)if(a.options[b].textContent==c){a.selectedIndex!=b&&(a.selectedIndex=b);d=!0;break}return d}};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});function Ja(a){C.call(this,"C1PPanel",a);this.D.N=!1}p(Ja,C);
Ja.prototype.T=function(a,b,c,d){return this.U&&this.U.T(a,b,c,d)||this.u&&this.u.T(a,b,c,d)||this.b&&this.b.T(a,b,c,d)||this.v&&this.v.T(a,b,c,d)?!0:C.prototype.T.call(this,a,b,c,d)};Ja.prototype.ia=function(a,b){a&&!this.D.N&&(this.D.N=!0,this.U=b,this.u=O(b,"cpu"),this.b=O(b,"keyboard"),this.v=O(b,"debugger"),Ka())};function Ka(){for(var a=!1,b=G(document,"c1pjs","panel"),c=0;c<b.length;c++){var d=b[c],e=H(d),g=Ba(e.id);g||(a=!0,g=new Ja(e));F(g,d);a&&g.X()}}y(Ka);
function La(a){C.call(this,"C1PCPU",a);Ma(this);this.D.N=!1;this.D.na=!1;this.Ta=a.autoStart;this.Pa=0;this.Pe=1;this.Qe=2;this.speed=this.Pa;this.Da=30;this.Ca=5;this.Ha=8;this.La=["Slow","Fast","Max"];this.hb=["(1Mhz)","(up to "+this.Ha+"Mhz)","(unlimited)"];this.O=[];this.I=[];this.pa=65536;this.qa=0;this.ea=65536;this.fa=0;this.Oa=32;this.Za=2;this.Oe=1;this.m=[this.tc,this.Nd,this.Ee,this.o,this.o,this.Pd,this.jc,this.o,this.Sd,this.Md,this.ic,this.o,this.o,this.Jd,this.gc,this.o,this.sc,this.Od,
this.o,this.o,this.o,this.Qd,this.kc,this.o,this.wc,this.Ld,this.o,this.o,this.o,this.Kd,this.hc,this.o,this.kd,this.cc,this.o,this.o,this.pc,this.ec,this.Yd,this.o,this.Ud,this.bc,this.Xd,this.o,this.oc,this.Zb,this.Vd,this.o,this.qc,this.dc,this.o,this.o,this.o,this.fc,this.Zd,this.o,this.oe,this.ac,this.o,this.o,this.o,this.$b,this.Wd,this.o,this.ee,this.Yc,this.o,this.o,this.o,this.$c,this.Gd,this.o,this.Rd,this.Xc,this.Fd,this.o,this.jd,this.Uc,this.Dd,this.o,this.uc,this.Zc,this.o,this.o,this.o,
this.ad,this.Hd,this.o,this.yc,this.Wc,this.o,this.o,this.o,this.Vc,this.Ed,this.o,this.fe,this.rb,this.o,this.o,this.o,this.tb,this.ce,this.o,this.Td,this.qb,this.be,this.o,this.hd,this.nb,this.$d,this.o,this.vc,this.sb,this.o,this.o,this.o,this.ub,this.de,this.o,this.qe,this.pb,this.o,this.o,this.o,this.ob,this.ae,this.o,this.o,this.ue,this.o,this.o,this.Ce,this.we,this.ze,this.o,this.Tc,this.o,this.Ie,this.o,this.Be,this.re,this.ye,this.o,this.lc,this.ve,this.o,this.o,this.De,this.xe,this.Ae,this.o,
this.Ke,this.te,this.Je,this.o,this.o,this.se,this.o,this.o,this.Ad,this.pd,this.vd,this.o,this.Bd,this.rd,this.wd,this.o,this.Ge,this.od,this.Fe,this.o,this.yd,this.ld,this.td,this.o,this.mc,this.qd,this.o,this.o,this.Cd,this.sd,this.xd,this.o,this.zc,this.nd,this.He,this.o,this.zd,this.md,this.ud,this.o,this.Mc,this.Ec,this.o,this.o,this.Nc,this.Gc,this.Qc,this.o,this.gd,this.Dc,this.Sc,this.o,this.Lc,this.Ac,this.Oc,this.o,this.rc,this.Fc,this.o,this.o,this.o,this.Hc,this.Rc,this.o,this.xc,this.Cc,
this.o,this.o,this.o,this.Bc,this.Pc,this.o,this.Jc,this.zb,this.o,this.o,this.Kc,this.Bb,this.dd,this.o,this.fd,this.yb,this.Id,this.o,this.Ic,this.vb,this.bd,this.o,this.nc,this.Ab,this.o,this.o,this.o,this.Cb,this.ed,this.o,this.pe,this.xb,this.o,this.o,this.o,this.wb,this.cd,this.o];this.gb=[7,6,0,0,0,3,5,0,3,2,2,0,0,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,3,6,0,0,3,3,5,0,4,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,3,2,2,0,3,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,
5,0,4,2,2,0,5,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,0,6,0,0,3,3,3,0,2,0,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,0,4,0,0,2,6,2,0,3,3,3,0,2,2,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,4,4,4,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0]}p(La,C);f=La.prototype;
f.reset=function(a){this.D.na&&this.aa();Ma(this);this.f=this.a[65532]|this.a[65533]<<8;this.D.error=!1;this.v?this.v.reset():a&&(!0===this.Ta||null===this.Ta&&!this.v&&void 0===this.H.run)&&this.ua()};
f.T=function(a,b,c){a=!1;switch(b){case "run":this.H[b]=c;c.onclick=function(a){return function(){a.D.na?a.aa():a.ua()}}(this);a=!0;break;case "A":case "X":case "Y":case "S":case "PC":case "C":case "Z":case "I":case "D":case "B":case "V":case "N":case "speed":this.H[b]=c;a=!0;break;case "setSpeed":this.H[b]=c,c.onclick=function(a){return function(){P(a,2<=a.speed?a.Pa:a.speed+1,!0)}}(this),a=!0}return a};
f.ba=function(a,b,c){this.a=a;this.K=b;this.ra=c-b+1;this.Fa=this.K+this.ra;this.K?A("unsupported CPU address buffer offset ("+this.K+")"):this.X()};f.ia=function(a,b){if(a&&!this.D.N){this.U=b;(this.v=O(b,"debugger"))&&this.v.Pb();if(a=O(b,"video"))this.ab=function(a){return function(){Na(a)}}(a),this.ca=function(a){return function(){a.ca()}}(a);this.D.N=!0;this.reset(!0);this.update()}};function Oa(a,b,c,d,e){0>Pa(a.O,b,c,d,e)&&(a.pa>b&&(a.pa=b),a.qa<c&&(a.qa=c),a.O.push([b,c,d,e]))}
function Qa(a,b,c){for(var d=0;d<a.O.length;d++)b>=a.O[d][0]&&b<=a.O[d][1]&&a.O[d][3].call(a.O[d][2],b,c)}function Q(a,b,c,d,e){0>Pa(a.I,b,c,d,e)&&(a.ea>b&&(a.ea=b),a.fa<c&&(a.fa=c),a.I.push([b,c,d,e]))}function Ra(a,b,c){for(var d=0;d<a.I.length;d++)b>=a.I[d][0]&&b<=a.I[d][1]&&a.I[d][3].call(a.I[d][2],b,c)}function Pa(a,b,c,d,e){for(var g=0;g<a.length;g++)if(a[g][0]==b&&a[g][1]==c&&a[g][2]==d&&a[g][3]==e)return g;return-1}
function P(a,b,c){void 0!==b&&(a.speed=b,a.H.setSpeed&&(a.H.setSpeed.innerHTML=a.La[2<=b?0:b+1]),a.l("running at "+a.La[b].toLowerCase()+" speed "+a.hb[b]),c&&a.ca());a.V=0;a.Ua=oa();Sa(a)}f.ab=function(){};f.ca=function(){};function R(a,b,c,d){void 0!==a.H[b]&&(void 0===d&&(d=1),c="0000"+c.toString(16),a.H[b].innerHTML=c.slice(c.length-d).toUpperCase())}
function Ta(a){R(a,"A",a.h,2);R(a,"X",a.A,2);R(a,"Y",a.F,2);var b=Ua(a);R(a,"C",b&1?1:0);R(a,"Z",b&2?1:0);R(a,"I",b&4?1:0);R(a,"D",b&8?1:0);R(a,"B",b&16?1:0);R(a,"V",b&64?1:0);R(a,"N",b&128?1:0);R(a,"S",a.G,4);R(a,"PC",a.f,4);a.H.speed&&a.M&&(a.H.speed.innerHTML=a.M.toFixed(1)+"Mhz")}
function Sa(a,b){var c=30;c<a.Da&&(c=a.Da);c<a.Ca&&(c=a.Ca);var d=1;b&&a.speed>a.Pa&&a.M&&(d=a.M);d>a.Ha&&2>a.speed&&(d=a.Ha);a.ib=Math.round(1E3/30);a.ja=Math.floor(1E6/c*d);a.sa=Math.floor(1E6/30*d);a.Xa=Math.floor(1E6/a.Da*d);a.Wa=Math.floor(1E6/a.Ca*d);b||(a.R=a.sa,a.Y=a.Xa,a.W=a.Wa);a.Aa=0}
function Va(a){var b=oa(),c=a.ib;a.Z&&(c=Math.round(c*a.Z/a.sa));c-=b-a.jb;if(b-=a.Ua)a.M=Math.round(a.V/(100*b))/10,864E5<=b&&P(a);0>c?c=0:1==a.speed?a.M<=a.Ha&&(c=0):2==a.speed&&(c=0);a.Aa+=a.Z;return c}
f.ua=function(){if(L(this,!0)){this.D.na||(P(this),this.U&&this.U.start(),this.D.na=!0,this.H.run&&(this.H.run.innerHTML="Halt"),this.ca());1E6<=this.Aa&&Sa(this,!0);this.Z=0;this.jb=oa();try{do{this.step(this.ja);var a=this.L-this.C;this.V+=a;this.Z+=a;this.L=this.C=0;this.Y-=this.ja;0>=this.Y&&(this.Y+=this.Xa,this.ab());this.W-=this.ja;0>=this.W&&(this.W+=this.Wa,Ta(this));this.R-=this.ja;if(0>=this.R){this.R+=this.sa;break}}while(this.D.na)}catch(b){this.aa();this.update();L(this,!1);Ia(this,
b.stack||b.message);return}setTimeout(function(a){return function(){a.ua()}}(this),Va(this))}else this.update(),this.U&&this.U.stop(this.Ua,this.V)};
f.step=function(a){var b=!0;this.b=this.g=-1;var c;if(c=a&&this.v)c=this.v,c=0<c.oa.length||0<c.va.length||0<c.xa.length;this.L=this.C=a;do{a=this.a[this.f];var d;if(d=c){d=this.v;var e=a,g=!1;Wa(d,this.f,d.oa,"exec")?g=!0:(d.L++,d.B[e][1]++,d.wa[d.Ka++]=d.u.f,d.Ka>=d.wa.length&&(d.Ka=0));d=!!g}if(d){b=void 0;this.aa();break}this.f++;this.m[a].call(this);if(0<=this.b){this.b>=this.pa&&this.b<=this.qa&&Qa(this,this.b,this.f);if(d=c)d=this.v,e=!1,Wa(d,this.b,d.va,"read")&&(e=!0),d=!!e;if(d){b=!1;this.aa();
break}this.b=-1}else if(0<=this.g){this.g>=this.ea&&this.g<=this.fa&&Ra(this,this.g,this.f);if(d=c){d=this.v;e=this.g;g=this.a[this.g];var k=!1;(g&255)!=g&&(d.l("invalid value at "+u(e)+": "+g),k=!0);Wa(d,e,d.xa,"write")&&(k=!0);d=!!k}if(d){b=!1;this.aa();break}this.g=-1}this.C-=this.gb[a]}while(0<this.C);return b};function Xa(a){a.R=0;a.L-=a.C;a.C=0}f.aa=function(){K(this,!0);this.L-=this.C;this.C=0;this.D.na&&(this.D.na=!1,this.H.run&&(this.H.run.innerHTML="Run"))};
f.update=function(){this.ab();Ta(this)};function Ya(a){return a.D.na?a.V+a.L-a.C:0}f.S=function(a){return this.a[a]};function Ua(a){var b=a.c&256?1:0;b|=a.j&255?0:2;b|=(a.s&255^a.w^a.s>>1)&128?64:0;b|=a.i&128?128:0;return a.B&60|b}function Za(a){a.B|=8;a.m[97]=a.Vb;a.m[101]=a.Xb;a.m[105]=a.Ub;a.m[109]=a.Rb;a.m[113]=a.Wb;a.m[117]=a.Yb;a.m[121]=a.Tb;a.m[125]=a.Sb;a.m[225]=a.ke;a.m[229]=a.me;a.m[233]=a.je;a.m[237]=a.ge;a.m[241]=a.le;a.m[245]=a.ne;a.m[249]=a.ie;a.m[253]=a.he}
function $a(a){a.B&=-9;a.m[97]=a.rb;a.m[101]=a.tb;a.m[105]=a.qb;a.m[109]=a.nb;a.m[113]=a.sb;a.m[117]=a.ub;a.m[121]=a.pb;a.m[125]=a.ob;a.m[225]=a.zb;a.m[229]=a.Bb;a.m[233]=a.yb;a.m[237]=a.vb;a.m[241]=a.Ab;a.m[245]=a.Cb;a.m[249]=a.xb;a.m[253]=a.wb}function S(a,b,c){var d=a.c&256?1:0,e=(b&15)+(c&15)+d;10<=e&&(e=e+6&15|16);e+=(b&240)+(c&240);a.w=b^c;a.s=e;a.i=e&255;160<=e&&(e+=96);512<=e&&(e-=256);a.c=e;a.j=b+c+d&255;a.C--;return e&255}
function T(a,b,c){var d=a.c&256?0:1,e=(b&15)-(c&15)-d;0>e&&(e=(e-6&15)-16);e+=(b&240)-(c&240);0>e&&(e-=96);a.i=a.j=(a.c=b-c-d)&255;a.w=b^c;a.s=a.c;a.c^=256;a.C--;return e&255}function Ma(a){a.h=0;a.A=0;a.F=0;a.G=256;a.B=0;a.i=0;a.j=0;a.w=0;a.s=0;a.c=0;a.f=0;a.b=-1;a.g=-1;a.M=0;a.V=a.L=a.C=0}
f.tc=function(){this.f++;this.a[this.G--]=this.f>>8;this.G|=256;this.a[this.G--]=this.f&255;this.G|=256;this.B|=16;this.B=Ua(this);this.a[this.G--]=this.B;this.G|=256;this.B&=239;this.b=65534;this.f=this.a[this.b]|this.a[this.b+1]<<8};f.Nd=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h|=this.a[this.b]};f.Pd=function(){this.b=this.a[this.f++];this.i=this.j=this.h|=this.a[this.b]};
f.jc=function(){this.g=this.a[this.f++];this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};f.Sd=function(){this.B=Ua(this);this.a[this.G--]=this.B;this.G|=256};f.Md=function(){this.b=this.f++;this.i=this.j=this.h|=this.a[this.b]};f.ic=function(){this.c=this.h<<1;this.i=this.j=this.h=this.c&255};f.Jd=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h|=this.a[this.b]};
f.gc=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};f.sc=function(){this.f+=(this.i&128?0:(this.C--,this.a[this.f]<<24>>24))+1};f.Od=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h|=this.a[this.b]};f.Qd=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h|=this.a[this.b]};
f.kc=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};f.wc=function(){this.c=0};f.Ld=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h|=this.a[this.b]};f.Kd=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h|=this.a[this.b]};f.hc=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};
f.kd=function(){this.b=this.f++;this.a[this.G--]=this.f>>8;this.G|=256;this.a[this.G--]=this.f&255;this.G|=256;this.f=this.a[this.b]|this.a[this.b+1]<<8};f.cc=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h&=this.a[this.b]};f.pc=function(){this.b=this.a[this.f++];this.j=this.h&this.a[this.b];this.i=this.i&127|this.a[this.b]&128;this.s=0;this.w=this.a[this.b]&64?128:0};f.ec=function(){this.b=this.a[this.f++];this.i=this.j=this.h&=this.a[this.b]};
f.Yd=function(){this.g=this.a[this.f++];this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.Ud=function(){this.G=this.G+1&255|256;this.B=this.a[this.G];this.c=this.B&1?256:0;this.j=this.B&2?0:1;this.i=this.B&128;this.s=0;this.w=this.B&64?128:0};f.bc=function(){this.b=this.f++;this.i=this.j=this.h&=this.a[this.b]};
f.Xd=function(){this.c=this.c&65280|this.h;this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.h=this.c&255};f.oc=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.j=this.h&this.a[this.b];this.i=this.i&127|this.a[this.b]&128;this.s=0;this.w=this.a[this.b]&64?128:0};f.Zb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h&=this.a[this.b]};
f.Vd=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.qc=function(){this.f+=(this.i&128?(this.C--,this.a[this.f]<<24>>24):0)+1};f.dc=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h&=this.a[this.b]};f.fc=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h&=this.a[this.b]};
f.Zd=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.oe=function(){this.c=256};f.ac=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h&=this.a[this.b]};f.$b=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h&=this.a[this.b]};
f.Wd=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.ee=function(){this.G=this.G+1&255|256;this.B=this.a[this.G];this.c=this.B&1?256:0;this.j=this.B&2?0:1;this.i=this.B&128;this.s=0;this.w=this.B&64?128:0;this.G=this.G+2&255|256;this.f=this.a[this.G-1|256]|this.a[this.G]<<8};
f.Yc=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h^=this.a[this.b]};f.$c=function(){this.b=this.a[this.f++];this.i=this.j=this.h^=this.a[this.b]};f.Gd=function(){this.g=this.a[this.f++];this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};f.Rd=function(){this.a[this.G--]=this.h;this.G|=256};f.Xc=function(){this.b=this.f++;this.i=this.j=this.h^=this.a[this.b]};
f.Fd=function(){this.c=this.c&65279|(this.h&1?256:0);this.h=(this.c=this.c&65280|this.h>>1)&255;this.i=this.j=this.c&255};f.jd=function(){this.b=this.f;this.f=this.a[this.b]|this.a[this.b+1]<<8};f.Uc=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h^=this.a[this.b]};f.Dd=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};
f.uc=function(){this.f+=((this.s&255^this.w^this.s>>1)&128?0:(this.C--,this.a[this.f]<<24>>24))+1};f.Zc=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h^=this.a[this.b]};f.ad=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h^=this.a[this.b]};f.Hd=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};
f.yc=function(){this.B&=251};f.Wc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h^=this.a[this.b]};f.Vc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h^=this.a[this.b]};f.Ed=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};
f.fe=function(){this.G=this.G+2&255|256;this.f=(this.a[this.G-1|256]|this.a[this.G]<<8)+1};f.rb=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Vb=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.h=S(this,this.h,this.a[this.b])};
f.tb=function(){this.b=this.a[this.f++];this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Xb=function(){this.b=this.a[this.f++];this.h=S(this,this.h,this.a[this.b])};f.ce=function(){this.g=this.a[this.f++];this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};f.Td=function(){this.G=this.G+1&255|256;this.i=this.j=this.h=this.a[this.G]};
f.qb=function(){this.b=this.f++;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Ub=function(){this.b=this.f++;this.h=S(this,this.h,this.a[this.b])};f.be=function(){this.c=this.c&65280|this.h;this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.h=this.c&255};f.hd=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.f=this.a[this.b]|this.a[this.b+1]<<8};
f.nb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Rb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.h=S(this,this.h,this.a[this.b])};f.$d=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};
f.vc=function(){this.f+=((this.s&255^this.w^this.s>>1)&128?(this.C--,this.a[this.f]<<24>>24):0)+1};f.sb=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Wb=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.h=S(this,this.h,this.a[this.b])};
f.ub=function(){this.b=this.a[this.f++]+this.A&255;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Yb=function(){this.b=this.a[this.f++]+this.A&255;this.h=S(this,this.h,this.a[this.b])};f.de=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};f.qe=function(){this.B|=4};
f.pb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Tb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.h=S(this,this.h,this.a[this.b])};f.ob=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};
f.Sb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.h=S(this,this.h,this.a[this.b])};f.ae=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};f.ue=function(){this.g=this.a[this.f++]+this.A&255;this.g=this.a[this.g]|this.a[this.g+1]<<8;this.a[this.g]=this.h};f.Ce=function(){this.g=this.a[this.f++];this.a[this.g]=this.F};
f.we=function(){this.g=this.a[this.f++];this.a[this.g]=this.h};f.ze=function(){this.g=this.a[this.f++];this.a[this.g]=this.A};f.Tc=function(){this.i=this.j=this.F=this.F-1&255};f.Ie=function(){this.i=this.j=this.h=this.A};f.Be=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.a[this.g]=this.F};f.re=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.a[this.g]=this.h};f.ye=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.a[this.g]=this.A};
f.lc=function(){this.f+=(this.c&256?0:(this.C--,this.a[this.f]<<24>>24))+1};f.ve=function(){this.g=this.a[this.f++];this.g=(this.a[this.g]|this.a[this.g+1]<<8)+this.F;this.a[this.g]=this.h};f.De=function(){this.g=this.a[this.f++]+this.A&255;this.a[this.g]=this.F};f.xe=function(){this.g=this.a[this.f++]+this.A&255;this.a[this.g]=this.h};f.Ae=function(){this.g=this.a[this.f++]+this.F&255;this.a[this.g]=this.A};f.Ke=function(){this.i=this.j=this.h=this.F};
f.te=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.a[this.g]=this.h};f.Je=function(){this.G=this.A|256};f.se=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.a[this.g]=this.h};f.Ad=function(){this.b=this.f++;this.i=this.j=this.F=this.a[this.b]};f.pd=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h=this.a[this.b]};f.vd=function(){this.b=this.f++;this.i=this.j=this.A=this.a[this.b]};
f.Bd=function(){this.b=this.a[this.f++];this.i=this.j=this.F=this.a[this.b]};f.rd=function(){this.b=this.a[this.f++];this.i=this.j=this.h=this.a[this.b]};f.wd=function(){this.b=this.a[this.f++];this.i=this.j=this.A=this.a[this.b]};f.Ge=function(){this.i=this.j=this.F=this.h};f.od=function(){this.b=this.f++;this.i=this.j=this.h=this.a[this.b]};f.Fe=function(){this.i=this.j=this.A=this.h};f.yd=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.F=this.a[this.b]};
f.ld=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h=this.a[this.b]};f.td=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.A=this.a[this.b]};f.mc=function(){this.f+=(this.c&256?(this.C--,this.a[this.f]<<24>>24):0)+1};f.qd=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h=this.a[this.b]};f.Cd=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.F=this.a[this.b]};
f.sd=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h=this.a[this.b]};f.xd=function(){this.b=this.a[this.f++]+this.F&255;this.i=this.j=this.A=this.a[this.b]};f.zc=function(){this.w=this.s=0};f.nd=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h=this.a[this.b]};f.He=function(){this.i=this.j=this.A=this.G&255};f.zd=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.F=this.a[this.b]};
f.md=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h=this.a[this.b]};f.ud=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.A=this.a[this.b]};f.Mc=function(){this.b=this.f++;this.i=this.j=this.c=this.F-this.a[this.b];this.c^=256};f.Ec=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};
f.Nc=function(){this.b=this.a[this.f++];this.i=this.j=this.c=this.F-this.a[this.b];this.c^=256};f.Gc=function(){this.b=this.a[this.f++];this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Qc=function(){this.g=this.a[this.f++];this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.gd=function(){this.i=this.j=this.F=this.F+1&255};f.Dc=function(){this.b=this.f++;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Sc=function(){this.i=this.j=this.A=this.A-1&255};
f.Lc=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.c=this.F-this.a[this.b];this.c^=256};f.Ac=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Oc=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.rc=function(){this.f+=(this.j&255?(this.C--,this.a[this.f]<<24>>24):0)+1};
f.Fc=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Hc=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Rc=function(){this.g=this.a[this.f++]+this.A&255;this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.xc=function(){$a(this)};
f.Cc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Bc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Pc=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.Jc=function(){this.b=this.f++;this.i=this.j=this.c=this.A-this.a[this.b];this.c^=256};
f.zb=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ke=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.h=T(this,this.h,this.a[this.b])};f.Kc=function(){this.b=this.a[this.f++];this.i=this.j=this.c=this.A-this.a[this.b];this.c^=256};
f.Bb=function(){this.b=this.a[this.f++];this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.me=function(){this.b=this.a[this.f++];this.h=T(this,this.h,this.a[this.b])};f.dd=function(){this.g=this.a[this.f++];this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};f.fd=function(){this.i=this.j=this.A=this.A+1&255};
f.yb=function(){this.b=this.f++;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.je=function(){this.b=this.f++;this.h=T(this,this.h,this.a[this.b])};f.Id=function(){};f.Ic=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.c=this.A-this.a[this.b];this.c^=256};
f.vb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ge=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.h=T(this,this.h,this.a[this.b])};f.bd=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};f.nc=function(){this.f+=(this.j&255?0:(this.C--,this.a[this.f]<<24>>24))+1};
f.Ab=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.le=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.h=T(this,this.h,this.a[this.b])};
f.Cb=function(){this.b=this.a[this.f++]+this.A&255;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ne=function(){this.b=this.a[this.f++]+this.A&255;this.h=T(this,this.h,this.a[this.b])};f.ed=function(){this.g=this.a[this.f++]+this.A&255;this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};f.pe=function(){Za(this)};
f.xb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ie=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.h=T(this,this.h,this.a[this.b])};
f.wb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.he=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.h=T(this,this.h,this.a[this.b])};f.cd=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};
f.Ee=function(){var a=this.a[this.f++];switch(a){case 0:this.l("HALT");this.aa();break;case 1:a=this.f;for(var b="";a<this.a.length;){var c=this.a[a++];if(!c)break;b+=String.fromCharCode(c)}this.f=a;b=b.replace(/%A/g,q(this.h,2)).replace(/%X/g,q(this.A,2)).replace(/%Y/g,q(this.F,2));this.l(b);Xa(this);break;default:this.f-=2,this.l("undefined opSim: "+t(a)+" at "+u(this.f)),this.aa()}};f.o=function(){var a=this.a[--this.f];this.l("undefined opcode: "+t(a)+" at "+u(this.f));this.aa()};
y(function(){for(var a=G(document,"c1pjs","cpu"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new La(d);F(d,c)}});function ab(a){C.call(this,"C1PROM",a);this.b=this.a=null;this.g=a.size;if(this.m=a.image){a=this.m;var b=la(this.m);"json"!=b&&"hex"!=b&&(a=(window?window.location.protocol+"//"+window.location.host:"https://www.pcjs.org")+"/api/v1/dump?file\x3d"+this.m+"\x26format\x3dbytes");var c=this;w(a,function(a,b,g){bb(c,a,b,g)})}}p(ab,C);
ab.prototype.ba=function(a,b,c,d){this.a=a;this.s=b;a=c-b+1;this.g||(this.g=a);a!=this.g?Ia(this,"computer-specified ROM size ("+u(a)+") does not match component-specified size ("+u(this.g)+")"):(d&&(this.u=d,Q(d,b,c,this,this.w)),cb(this))};ab.prototype.ia=function(a,b){a&&!this.D.N&&(this.D.N=!0,this.v=O(b,"debugger"))};ab.prototype.w=function(a,b){void 0!==b&&(this.v&&U(this.v,this,a,b,this.v.lb,!0),a-=this.s,this.a[this.s+a]=this.b?this.b[a]:0)};
function bb(a,b,c,d){if(d)a.l('Error loading ROM "'+b+'" ('+d+")");else{if("["==c.charAt(0)||"{"==c.charAt(0))try{var e=eval("("+c+")"),g=e.bytes;g?a.b=g:a.b=e}catch(k){a.l('Error processing ROM "'+b+'": '+k.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.b=Array(b.length),c=0;c<b.length;c++)a.b[c]=parseInt(b[c],16);cb(a)}}
function cb(a){if(!J(a))if(!a.m)a.X();else if(a.b&&a.a){var b=a.b.length;if(b!=a.g)Ia(a,"ROM image size ("+u(b)+") does not match component-specified size ("+u(a.g)+")");else{for(var c=0;c<b;c++)a.a[a.s+c]=a.b[c];a.X()}}}y(function(){for(var a=G(document,"c1pjs","rom"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new ab(d);F(d,c)}});function db(a){C.call(this,"C1PRAM",a)}p(db,C);db.prototype.ba=function(a){this.a=a;this.X()};
y(function(){for(var a=G(document,"c1pjs","ram"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new db(d);F(d,c)}});
function eb(a){C.call(this,"C1PKeyboard",a);this.D.N=!1;this.Ta=a.model;this.pa=8;this.jb=10;this.ib=13;this.qa=27;this.gb=this.pa;this.hb=this.jb;this.Ua=this.ib;this.fa=this.qa;this.w=224;this.g=16+this.w;this.O=17+this.w;this.R=18+this.w;this.ja=20+this.w;this.ea=this.w;this.Wa=3;this.Xa=15;this.L=1;this.I={};this.I["break"]=this.ea;this.I.esc=this.fa;this.I["ctrl-c"]=this.Wa;this.I["ctrl-o"]=this.Xa;this.b=[];this.b[49]=30464;this.b[33]=30464+this.g;this.b[50]=30208;this.b[34]=30208+this.g;this.b[51]=
29952;this.b[35]=29952+this.g;this.b[52]=29696;this.b[36]=29696+this.g;this.b[53]=29440;this.b[37]=29440+this.g;this.b[54]=29184;this.b[38]=29184+this.g;this.b[55]=28928;this.b[39]=28928+this.g;this.b[56]=26368;this.b[40]=26368+this.g;this.b[57]=26112;this.b[41]=26112+this.g;this.b[48]=25856;this.b[58]=25600;this.b[42]=25600+this.g;this.b[45]=25344;this.b[61]=25344+this.g;this.b[46]=22272;this.b[62]=22272+this.g;this.b[108]=22016;this.b[76]=22016+this.g;this.b[92]=22016+this.g;this.b[111]=21760;this.b[79]=
21760+this.g;this.b[this.gb]=21760+this.g;this.b[this.hb]=21504;this.b[this.Ua]=21248;this.b[119]=18176;this.b[87]=18176+this.g;this.b[101]=17920;this.b[69]=17920+this.g;this.b[114]=17664;this.b[82]=17664+this.g;this.b[116]=17408;this.b[84]=17408+this.g;this.b[121]=17152;this.b[89]=17152+this.g;this.b[117]=16896;this.b[85]=16896+this.g;this.b[105]=16640;this.b[73]=16640+this.g;this.b[115]=14080;this.b[83]=14080+this.g;this.b[100]=13824;this.b[68]=13824+this.g;this.b[102]=13568;this.b[70]=13568+this.g;
this.b[103]=13312;this.b[71]=13312+this.g;this.b[104]=13056;this.b[72]=13056+this.g;this.b[106]=12800;this.b[74]=12800+this.g;this.b[107]=12544;this.b[75]=12544+this.g;this.b[91]=12544+this.g;this.b[120]=9984;this.b[88]=9984+this.g;this.b[99]=9728;this.b[67]=9728+this.g;this.b[118]=9472;this.b[86]=9472+this.g;this.b[98]=9216;this.b[66]=9216+this.g;this.b[110]=8960;this.b[78]=8960+this.g;this.b[94]=8960+this.g;this.b[109]=8704;this.b[77]=8704+this.g;this.b[93]=8704+this.g;this.b[44]=8448;this.b[60]=
8448+this.g;this.b[113]=5888;this.b[81]=5888+this.g;this.b[97]=5632;this.b[65]=5632+this.g;this.b[122]=5376;this.b[90]=5376+this.g;this.b[32]=5120;this.b[47]=4864;this.b[63]=4864+this.g;this.b[59]=4608;this.b[43]=4608+this.g;this.b[112]=4352;this.b[80]=4352+this.g;this.b[64]=4352+this.g;this.b[this.O]=1536;this.b[this.fa]=1280;this.b[this.g]=512;this.b[this.R]=256;this.b[this.ja]=0;this.reset()}p(eb,C);f=eb.prototype;
f.reset=function(){this.Ma(this.Ta);this.m=this.L;this.sa=0;this.s=[this.L,0,0,0,0,0,0,0];this.V=[];if(this.B)for(var a in this.B)isNaN(+a)||this.B[a]&&clearTimeout(this.B[a]);this.B=[];this.La=this.C=0;this.Aa=-1;this.ra=this.s;this.Ca=this.Z=0;this.K=""};
f.T=function(a,b,c){if(void 0===this.H[b])switch(b){case "keyDown":return this.H[b]=c,c.onkeydown=function(a){return function(b){return fb(a,b,!0)}}(this),!0;case "keyPress":return this.H[b]=c,c.onkeypress=function(a){return function(b){var c=!0;b=b||window.event;b=b.which||b.keyCode;a.K="";a.m&8?a.m&=-9:c=!gb(a,b);a.v&&M(a.v,a.v.ya)&&a.v.message("keyPress("+t(b)+"): "+(c?"pass":"consume"));return c}}(this),!0;case "keyUp":return this.H[b]=c,c.onkeyup=function(a){return function(b){return fb(a,b,
!1)}}(this),!0;case "break":return this.H[b]=c,c.onclick=function(a){return function(){a.U&&a.U.reset(!0)}}(this),!0;default:if(void 0!==this.I[b])return this.H[b]=c,c.onclick=function(a,b,c){return function(){a.u&&a.u.ca();return!gb(a,c)}}(this,b,this.I[b]),!0}return!1};f.ba=function(a,b,c,d){this.a=a;this.Da=b;this.Re=c-b+1;this.Gb=this.Da+this.Re;d&&(this.u=d,Q(d,b,c,this,this.Ib));this.X()};f.Ma=function(a){this.M=a;this.W=255;600!=this.M&&(this.W=0,this.l("updated keyboard model: "+this.M))};
f.ia=function(a,b){a&&!this.D.N&&(this.D.N=!0,this.U=b,this.v=O(b,"debugger"))};f.X=function(){this.Y=(this.Se=x("iOS"))||x("Android");this.v&&M(this.v,this.v.ya)&&this.v.message("mobile keyboard support: "+(this.Y?"true":"false")+" ("+window.navigator.userAgent+")");C.prototype.X.call(this)};function hb(a,b){b=b?100:250;a.u&&a.u.M&&(b/=a.u.M);return b}function ib(a,b){!a.C||void 0!==b&&b==a.C||(a.v&&M(a.v,a.v.ya)&&a.v.message("autoClear("+t(a.C)+")"),clearTimeout(a.B[a.C]),jb(a,a.C,!1,4))}
function kb(a,b,c){a.K=b;lb(a,c||300)}function lb(a,b){if(0<a.K.length){var c=a.K.charCodeAt(0);10==c&&(c=13);65<=c&&90>=c&&(c+=32);a.K=a.K.substr(1);gb(a,c)}0<a.K.length&&setTimeout(function(a){return function(){lb(a,b)}}(a),b)}
function fb(a,b,c){var d=!c;b=b.keyCode;c&&(a.La=b);if(b==a.g-a.w)a.m&=-5,c&&(a.m|=4),b+=a.w,d=!1;else if(b==a.R-a.w)a.m&=-3,c&&(a.m|=2),b+=a.w,d=!1;else if(b==a.O-a.w)a.m&=-65,c&&(a.m|=64),b+=a.w,d=!1;else if(b==a.ja-a.w)c=!c,a.m&=~a.L,c&&(a.m|=a.L),b+=a.w,d=!1;else if(91==b){a.m&=-9;c&&(a.m|=8);d=!1;var e=!0}else e=9==b?d=!1:b==a.qa||b==a.pa?c?!gb(a,b):!1:!0;d&&(a.m&=-9,a.Y||b!=a.La||ib(a));void 0===e&&(e=!jb(a,b,c,2));a.v&&M(a.v,a.v.ya)&&a.v.message("key"+(c?"Down":"Up")+"("+t(b)+"): "+(e?"pass":
"consume"));return e}function gb(a,b){var c=!1;b==a.ea?a.U&&(a.U.reset(!0),c=!0):(a.Y&&65<=b&&90>=b&&(b+=32),ib(a,b),jb(a,b,!0,0)&&(2==a.u.speed?jb(a,b,!1,1):(c=!1,a.B[b]&&(clearTimeout(a.B[b]),c=!0),c=hb(a,c),a.B[a.C=b]=setTimeout(function(a){return function(){jb(a,b,!1,3)}}(a),c),a.v&&M(a.v,a.v.ya)&&a.v.message("keyPressSimulate("+t(b)+"): setTimeout()")),c=!0));a.v&&M(a.v,a.v.ya)&&a.v.message("keyPressSimulate("+t(b)+"): "+(c?"true":"false"));return c}
function jb(a,b,c,d){var e=!1;c||(a.B[b]=null,a.C==b&&(a.C=0));var g=0,k=a.b[b];void 0===k&&(1<=b&&26>=b&&(b+=64,g=a.O),k=a.b[b]);void 0!==k&&(b=k>>12,e=k>>8&15,g||(g=k&255),c?(a.s[b]|=1<<e,a.s[0]=g==a.O?a.s[0]|64:g==a.g?a.s[0]|4:g==a.R?a.s[0]|2:a.s[0]&-71):(a.s[b]&=~(1<<e),a.s[0]&=-71,a.s[0]|=a.m&70),c=0==d&&!a.V.length,a.V.push(a.s.slice()),mb(a,c),e=!0);return e}f.S=function(){};f.Ib=function(a){this.sa=this.u.S(a)^this.W;this.Z++;mb(this,!1,a)};
function mb(a,b,c){var d=Ya(a.u);b||(2==a.u.speed?b=void 0!==c&&32<=a.Z:(b=d-a.Ca,b=0>b||8192<=b));b&&(b=a.V.shift(),void 0!==b&&(a.ra=b),a.Z=0,a.Ca=d);for(b=d=0;8>b;b++)a.sa&1<<b&&(d|=a.ra[b]);d^=a.W;if(void 0!==c)a.a[c]=d;else if(c=a.Da,d!=a.Aa)for(;c<a.Gb;c++)a.a[c]=d;a.Aa=d}y(function(){for(var a=G(document,"c1pjs","keyboard"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new eb(d);F(d,c)}});
function nb(a,b,c,d){C.call(this,"C1PVideo",a);this.ja=a.model;this.Z=a.charCols;this.ea=a.charRows;this.qa=a.screenWidth;this.ra=a.screenHeight;this.B=a.charWidth;this.C=a.charHeight;ob(this);this.w=b;this.O=c;this.m=d;b=["","moz","ms","webkit"];a=a.smoothing;(c=qa("smoothing"))&&(a="true"==c);if(null!=a)for(c=0;c<b.length;c++)if(d=(d=b[c])?d+"ImageSmoothingEnabled":"imageSmoothingEnabled",void 0!==this.O[d]){this.O[d]=a;break}}p(nb,C);f=nb.prototype;
f.reset=function(a){this.Ma(this.ja);if(this.a)for(var b=this.I;b<this.R;b++)this.a[b]=a?Math.floor(256*Math.random()):32};f.T=function(a,b,c){switch(b){case "refresh":return this.H[b]=c,c.onclick=function(a){return function(){pb(a);Na(a)}}(this),!0}return!1};f.ba=function(a,b,c,d){this.a=a;this.I=b;this.pa=c-b+1;this.R=this.I+this.pa;d&&(this.u=d,Oa(d,56832,56832,this,this.S),Q(d,56832,56832,this,this.Kb));this.reset(!0)};
function ob(a,b,c,d,e){a.K=void 0!==b?b:a.Z;a.sa=void 0!==c?c:a.ea;a.g=a.K*a.sa;a.R=a.I+a.g;a.Y=void 0!==d?d:0;a.fa=void 0!==e?e:c;a.V=Math.floor(a.qa/a.K);a.W=Math.floor(a.ra/a.fa)}f.ca=function(){this.w.focus()};f.Ma=function(a){this.M=a;600==this.M?(ob(this,this.Z,this.ea,3,25),1024==this.g&&this.u&&(this.s=this.R+this.g-1,Q(this.u,this.s,this.s,this,this.Fb))):(this.l("updated video model: "+this.M),ob(this,64,32));pb(this);Na(this)};
f.ia=function(a,b){if(a&&!this.D.N&&J(this)){if(this.D.N=!0,this.v=O(b,"debugger"),this.b=O(b,"keyboard"))this.b.T("canvas","keyDown",this.w),this.b.T("canvas","keyPress",this.w),this.b.T("canvas","keyUp",this.w)}else!a&&this.D.N&&(this.D.N=!1)};f.X=function(){this.B||(this.B=Math.floor(this.m.width/16));this.C||(this.C=Math.floor(this.m.height/16));C.prototype.X.call(this)};
f.S=function(a,b){var c=this.u.S(a);void 0!==b&&this.v&&U(this.v,this,a,b,this.v.Ya);this.u.a[a]=c&127|(Math.floor(Ya(this.u)/8333)&1?128:0)};f.Kb=function(a,b){void 0!==b&&this.v&&U(this.v,this,a,b,this.v.Ya)};
f.Fb=function(a,b){if(void 0!==b){this.v&&U(this.v,this,a,b,this.v.Ya,!0);this.Ma(540);this.b&&this.b.Ma(542);a=this.u;b=a.I;var c=[],d=Pa(b,this.s,this.s,this,this.Fb);if(0<=d){c.push(b[d][0]);c.push(b[d][1]);b.splice(d,1);var e=65536,g=0;for(d=0;d<b.length;d++)e>b[d][0]&&(e=b[d][0]),g<b[d][1]&&(g=b[d][1]);c.push(e);c.push(g)}4==c.length&&(a.ea=c[2],a.fa=c[3])}};function pb(a){a.L=Array(a.g);for(var b=0;b<=a.g;b++)a.L[b]=-1}
function Na(a){var b=0;if(a.D.N)for(;b<a.g;){var c=a.a[a.I+b];if(a.L[b]!=c){var d=Math.floor(b/a.K);if(d>=a.Y&&(d-=a.Y,d<a.fa)){var e=c*a.B;a.O.drawImage(a.m,e%a.m.width,Math.floor(e/a.m.width)*a.C,a.B,a.C,b%a.K*a.V,d*a.W,a.V,a.W)}a.L[b]=c}b++}}
y(function(){for(var a=G(document,"c1pjs","video"),b=0;b<a.length;b++){var c=a[b],d=H(c),e=document.createElement("canvas");if(void 0===e||!e.getContext){c.innerHTML="\x3cbr/\x3eMissing \x26lt;canvas\x26gt; support. Please try a newer web browser.";break}e.setAttribute("class","c1pjs-canvas");e.setAttribute("width",d.screenWidth);e.setAttribute("height",d.screenHeight);e.setAttribute("contenteditable","true");e.setAttribute("autocapitalize","off");e.setAttribute("autocorrect","off");e.style.backgroundColor=
d.screenColor;e.style.height="auto";0<=(window?window.navigator.userAgent:"").indexOf("MSIE")&&(e.style.height=(c.clientWidth*d.screenHeight/d.screenWidth|0)+"px",c.onresize=function(a,b,c,d){return function(){b.style.height=(a.clientWidth*d/c|0)+"px"}}(c,e,d.screenWidth,d.screenHeight));c.appendChild(e);var g=new Image,k=e.getContext("2d");e=new nb(d,e,k,g);g.onload=function(a){return function(){a.X()}}(e,d.charSet);g.src=d.charSet;F(e,c)}});
function qb(a){C.call(this,"C1PSerialPort",a);this.D.N=!1;this.C=a.demo;this.reset(!0)}p(qb,C);f=qb.prototype;f.reset=function(a){if(a||this.m!=rb){this.s=-1;this.w=0;this.g="";if(this.C){a=1;if(this.cb){var b=this.cb.match(/\d+/);null!==b&&(a=parseInt(b[0],10))}this.g='10 PRINT "HELLO OSI #'+a+'"\n'}this.B=!0;this.m=sb}};f.start=function(){this.b&&this.C&&(kb(this.b," C\n\n",3E3),setTimeout(function(a){return function(){a.m=tb;kb(a.b,"LOAD\n")}}(this),12E3));this.C=!1};
f.T=function(a,b,c){var d=this;switch(b){case "listSerial":return this.H[b]=c,!0;case "loadSerial":return this.H[b]=c,c.onclick=function(){d.H.listSerial&&w(d.H.listSerial.value,function(a,b,c){ub(d,a,b,c)})},!0;case "mountSerial":return!pa()&&window&&"FileReader"in window?(this.H[b]=c,c.onchange=function(){var a=c.children[0];a.children[1].disabled=!a.children[0].files.length},c.onsubmit=function(a){var b=a.currentTarget[1].files[0],c=new FileReader;c.onload=function(){ub(d,b.name,c.result.toString(),
0)};c.readAsText(b);return!1}):c.parentNode.removeChild(c),!0}return!1};f.ba=function(a,b,c,d){this.a=a;this.K=b;this.M=c-b+1;this.I=this.K+this.M;if(this.u=d)Oa(d,b,c,this,this.S),Q(d,b,c,this,this.Jb);this.X()};f.ia=function(a,b){a&&!this.D.N&&(this.D.N=!0,this.U=b,this.b=O(b,"keyboard"),this.v=O(b,"debugger"))};
function ub(a,b,c,d){if(c){a.w=0;a.g=c;a.B=!0;a.m=sb;if(-1!==b.indexOf(".json",b.length-5))try{d="";var e=eval("("+c+")").bytes;for(c=0;c<e.length;c++)d+=String.fromCharCode(e[c]);a.g=d;a.B=!1}catch(g){a.l('Error processing file "'+b+'": '+g.message);return}a.U&&a.b&&a.u.D.na?(a.l("auto-loading "+b),a.u.ca(),"."!=a.g.charAt(0)?(a.m=tb,kb(a.b,"NEW\nLOAD\n")):(a.m=rb,a.U.reset(!0),kb(a.b,"ML"))):a.l(b+" ready to load")}else a.l('Error loading file "'+b+'" ('+d+")")}
f.S=function(a,b){void 0!==b&&(a&1?vb(this):this.g&&!this.w&&vb(this))};f.Jb=function(a,b){void 0!==b&&this.v&&U(this.v,this,a,b,this.v.Me,!0)};function vb(a){if(void 0!==a.g){a.s=-1;if(a.w<a.g.length){var b=a.g.charCodeAt(a.w++)&255;a.B&&10==b&&(b=13);a.s=b}else a.g="",a.w=0,a.m==tb&&a.b&&kb(a.b," \nRUN\n"),a.m=sb;for(b=a.K+0;b<a.I;b+=2)a.a[b]=0<=a.s?wb:xb;for(b=a.K+1;b<a.I;b+=2)a.a[b]=0<=a.s?a.s:0}}var xb=0,wb=1,sb=0,tb=1,rb=2;
y(function(){for(var a=G(document,"c1pjs","serial"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new qb(d);F(d,c)}});function yb(a){C.call(this,"C1PDiskController",a);this.D.N=!1;this.reset(!0)}p(yb,C);f=yb.prototype;f.reset=function(a){zb(this);this.b=-1;a&&(this.g=[],this.g[0]={Te:0,mb:40,Ob:!0,Ea:20,ma:0,Ba:-1,Ra:[]})};
function zb(a){a.M={J:64,read:function(){},update:function(a){return function(b){void 0!==b&&(this.J=b);a.B.J&4||V(a,0,this)}}(a)};a.m={J:255,read:function(){this.update()},update:function(a){return function(b){void 0===b?b=a.m.J:Ab(a,b,a.w.J);b=(b|190)&-2;if(0<=a.b&&a.g[a.b].Ra.length){var c=a.g[a.b];c.Ob&&(b&=-33);c.ma||(b&=-3);10>=--c.Ea&&(0<c.Ea?(b&=-129,Bb(a)):(c.Ea=100,0<=a.b&&(a.g[a.b].Ba=0,Cb(a))))}this.J=b;a.B.J&4&&V(a,0,this)}}(a)};a.B={J:0,read:function(){},update:function(a){return function(b){void 0!==
b&&(this.J=b&-193);V(a,1,this);a.m.update();a.M.update()}}(a)};a.L={J:255,read:function(){},update:function(a){return function(b){void 0!==b&&(this.J=b);a.C.J&4||V(a,2,this)}}(a)};a.w={J:255,read:function(){},update:function(a){return function(b){void 0===b?b=a.w.J:Ab(a,a.m.J,b);if(0<=a.b&&a.b<a.g.length){var c=a.g[a.b];c.Ra.length&&a.w.J&8&&!(b&8)&&(b&4?c.ma--:c.ma++,a.v&&M(a.v,a.v.Ga)&&a.v.message("stepping "+(b&4?"down":"up")+" to track "+c.ma),c.ma>=c.mb&&(c.ma=c.mb),0>c.ma&&(c.ma=0),c.Ea=20,
a.m.update(a.m.J|128),Bb(a))}this.J=b;a.C.J&4&&V(a,2,this)}}(a)};a.C={J:0,read:function(){},update:function(a){return function(b){void 0!==b&&(this.J=b&-193);V(a,3,this);a.w.update();a.L.update()}}(a)};a.O={J:0,read:function(){},update:function(a){return function(b){void 0!==b&&(3==(b&3)&&(a.s.J=14),this.J=b);a.s.update()}}(a)};a.s={J:14,read:function(){},update:function(a){return function(b){void 0===b&&(b=a.s.J);b&=-2;0<=a.b&&0<=a.g[a.b].Ba&&(b|=1);this.J=b;V(a,16,this)}}(a)};a.I={J:0,read:function(a){return function(){Cb(a)}}(a),
update:function(a){return function(b){void 0!==b&&(this.J=b);V(a,17,this)}}(a)};a.R={J:0,read:function(){},update:function(){return function(){}}(a)}}
f.T=function(a,b,c){switch(b){case "listDisk":return this.H[b]=c,!0;case "loadDisk":return this.H[b]=c,c.onclick=function(a){return function(){if(a.H.listDisk){var b=a.H.listDisk.value,c=b;".json"!=b.substr(b.length-5)&&(c="http://"+window.location.host+"/api/v1/dump?disk\x3d"+b);a.l("loading  "+ka(b)+"...");w(c,function(b,c,d){Db(a,b,c,d)})}}}(this),!0}return!1};f.ba=function(a,b,c,d){this.a=a;this.K=b;if(this.u=d)Oa(d,b,c,this,this.S),Q(d,b,c,this,this.Hb);this.X()};
f.ia=function(a,b){a&&!this.D.N&&(this.D.N=!0,this.v=O(b,"debugger"))};
function Db(a,b,c,d){if(d)a.l("disk load error ("+d+")");else{d=[];a.l("mounting "+b+"...");try{if(d=eval("("+c+")"),d.length)if(d[0].length){var e=d[0];if(void 0===e[0].trackNum)a.l("data error: "+e[0]);else if(a.g[0]){for(c=0;c<e.length;c++){var g,k=e[c],l=k.sectors;if(void 0===(g=k.trackNum)||void 0===l)throw Error("track "+c+" missing data");g!=c&&A("track "+g+" out of order (expected "+c+")");d=[];var h;if(g){Eb(d,k,"trackSig");Fb(d,k);W(d,k,"trackType");for(var m=0;m<l.length;m++){var n=l[m];
var r=n.sectorData;W(d,n,"sectorSig");W(d,n,"sectorNum");W(d,n,"sectorPages");for(h=0;h<r.length;h++)d.push(r[h]);Eb(d,n,"sectorEndSig")}}else for(n=l[0],r=n.sectorData,W(d,k,"trackLoad",2),W(d,n,"sectorPages"),h=0;h<r.length;h++)d.push(r[h]);e[g].Eb=d;a.v&&M(a.v,a.v.Ga)&&a.v.message("track "+g+": "+d.length+" bytes")}a.g[0].Ra=e;a.l("mount of "+b+" complete")}else a.l("no available drives")}else a.l("no tracks: "+b);else a.l("no data: "+b)}catch(E){a.l("disk data error: "+E.message)}}}
function Fb(a,b){b=b.trackNum;if(void 0===b)throw Error("missing bcd value: trackNum");a.push(Math.floor(b/10)<<4|b%10)}function W(a,b,c,d){b=b[c];if(void 0===b)throw Error("missing binary value: "+c);2==d&&a.push(b>>8&255);a.push(b&255)}function Eb(a,b,c){b=b[c];if(void 0===b)throw Error("missing signature: "+c);for(c=0;c<b.length;c++)a.push(b.charCodeAt(c))}
function Gb(a,b,c){b&=63;16>b?b&=3:32>b&&(b&=17);switch(b){case 0:a=a.B.J&4?a.m:a.M;break;case 1:a=a.B;break;case 2:a=a.C.J&4?a.w:a.L;break;case 3:a=a.C;break;case 16:a=c?a.O:a.s;break;case 17:a=a.I;break;default:a=a.R}return a}f.S=function(a,b){if(void 0!==b){var c=Gb(this,a-this.K,!1);this.v&&U(this.v,this,a,b,this.v.Ga,!1,c.Db);c.read()}};
f.Hb=function(a,b){if(void 0!==b){var c=this.u.S(a),d=Gb(this,a-this.K,!0);if(this.v&&M(this.v,this.v.Ga|this.v.lb)&&(U(this.v,this,a,b,this.v.Ga,!0,d.Db),d.Mb))for(a=128,b=d.J^c;b&&a;)b&a&&this.v.message("  changed "+d.Db+"."+d.Mb[a]+" to "+(c&a?"1":"0")),a>>=1;d.update(c)}};function Ab(a,b,c){var d=-1;void 0!==b&&void 0!==c&&(d=0,c&32||(d|=2),a.m.J&64||(d|=1));a.b!=d&&(a.b=d,a.s.update())}function Bb(a){0<=a.b&&(a.g[a.b].Ba=-1,a.I.update(255),a.s.update())}
function Cb(a){if(0<=a.b){var b=a.g[a.b];var c=b.Ra[b.ma];void 0!==c&&(0<=b.Ba&&b.Ba<c.Eb.length?(b.Ea=100,b=c.Eb[b.Ba++],a.I.update(b),a.s.update()):(b.Ea=10,Bb(a)))}}function V(a,b,c){a.u.a[b+a.K]=c.J}y(function(){for(var a=G(document,"c1pjs","disk"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new yb(d);F(d,c)}});
function Hb(a){C.call(this,"C1PDebugger",a);this.v=this;this.L=-1;this.ta=0;this.fb=null;this.Sa=!1;this.ha=0;this.oa=[];this.va=[];this.xa=[];this.Ka=0;this.wa=[];this.B=[];this.lb=1;this.ya=16;this.Ya=32;this.Ga=64;this.Me=128;this.la=this.Y=0;this.Qa={port:1,kbd:16,video:32,disk:64,serial:128};this.Oa=28;this.Za=56;this.Ia="ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRK BVC BVS CLC CLD CLI CLV CMP CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP PLA PLP ROL ROR RTI RTS SBC SEC SED SEI STA STX STY TAX TAY TSX TXA TXS TYA SIM .DB".split(" ");
this.W=["HLT","MSG"];Ib(this,!0);this.ga=[[10],[34,1,this.C],[this.Za,1],[],[],[34,1,this.b],[2,1,this.b],[],[36],[34,1,this.s],[2,0,this.O],[],[],[34,2,this.P],[2,2,this.P],[],[9,1,this.da],[34,1,this.I],[],[],[],[34,1,this.g],[2,1,this.g],[],[13],[34,2,this.w],[],[],[],[34,2,this.m],[2,2,this.m],[],[this.Oa,2,this.Na],[1,1,this.C],[],[],[6,1,this.b],[1,1,this.b],[39,1,this.b],[],[38],[1,1,this.s],[39,0,this.O],[],[6,2,this.P],[1,2,this.P],[39,2,this.P],[],[7,1,this.da],[1,1,this.I],[],[],[],[1,
1,this.g],[39,1,this.g],[],[44],[1,2,this.w],[],[],[],[1,2,this.m],[39,2,this.m],[],[41],[23,1,this.C],[],[],[],[23,1,this.b],[32,1,this.b],[],[35],[23,1,this.s],[32,0,this.O],[],[27,2,this.Na],[23,2,this.P],[32,2,this.P],[],[11,1,this.da],[23,1,this.I],[],[],[],[23,1,this.g],[32,1,this.g],[],[15],[23,2,this.w],[],[],[],[23,2,this.m],[32,2,this.m],[],[42],[0,1,this.C],[],[],[],[0,1,this.b],[40,1,this.b],[],[37],[0,1,this.s],[40,0,this.O],[],[27,2,this.kb],[0,2,this.P],[40,2,this.P],[],[12,1,this.da],
[0,1,this.I],[],[],[],[0,1,this.g],[40,1,this.g],[],[46],[0,2,this.w],[],[],[],[0,2,this.m],[40,2,this.m],[],[],[47,1,this.C],[],[],[49,1,this.b],[47,1,this.b],[48,1,this.b],[],[22],[],[53],[],[49,2,this.P],[47,2,this.P],[48,2,this.P],[],[3,1,this.da],[47,1,this.I],[],[],[49,1,this.g],[47,1,this.g],[48,1,this.V],[],[55],[47,2,this.w],[54],[],[],[47,2,this.m],[],[],[31,1,this.s],[29,1,this.C],[30,1,this.s],[],[31,1,this.b],[29,1,this.b],[30,1,this.b],[],[51],[29,1,this.s],[50],[],[31,2,this.P],[29,
2,this.P],[30,2,this.P],[],[4,1,this.da],[29,1,this.I],[],[],[31,1,this.g],[29,1,this.g],[30,1,this.V],[],[16],[29,2,this.w],[52],[],[31,2,this.m],[29,2,this.m],[30,2,this.w],[],[19,1,this.s],[17,1,this.C],[],[],[19,1,this.b],[17,1,this.b],[20,1,this.b],[],[26],[17,1,this.s],[21],[],[19,2,this.P],[17,2,this.P],[20,2,this.P],[],[8,1,this.da],[17,1,this.I],[],[],[],[17,1,this.g],[20,1,this.g],[],[14],[17,2,this.w],[],[],[],[17,2,this.m],[20,2,this.m],[],[18,1,this.s],[43,1,this.C],[],[],[18,1,this.b],
[43,1,this.b],[24,1,this.b],[],[25],[43,1,this.s],[33],[],[18,2,this.P],[43,2,this.P],[24,2,this.P],[],[5,1,this.da],[43,1,this.I],[],[],[],[43,1,this.g],[24,1,this.g],[],[45],[43,2,this.w],[],[],[],[43,2,this.m],[24,2,this.m],[]]}p(Hb,C);f=Hb.prototype;
f.T=function(a,b,c){var d=this;switch(b){case "debugInput":return this.R=this.H[b]=c,this.R.focus(),c.onkeypress=function(a,c){return function(d){13==d.keyCode&&(b=c.value,c.value="",Jb(a,b))}}(this,c),!0;case "debugEnter":return this.H[b]=c,ta(c,function(){return d.R?(b=d.R.value,Jb(d,b),!0):!1}),!0;case "step":return this.H[b]=c,ta(c,function(a){var b=!1;K(d,!0)||(L(d,!0),b=d.step(a?1:0),L(d,!1));return b}),!0}return!1};
f.ba=function(a,b,c){this.a=a;this.K=b;this.ra=c-b+1;this.Fa=this.K+this.ra;this.X()};f.ia=function(a,b){a&&!this.D.N&&(this.D.N=!0,this.u=O(b,"cpu"))};f.ca=function(){this.R.focus()};
function Ib(a,b){a.O=0;a.s=1;a.m=2;a.w=3;a.Na=4;a.kb=5;a.g=6;a.V=7;a.C=8;a.I=9;a.P=10;a.b=11;a.da=a.Na;var c="";if(b)for(a.ka="A #$nn $nnnn,X $nnnn,Y $nnnn ($nnnn) $nn,X $nn,Y ($nn,X) ($nn),Y $nnnn $nn".split(" "),b=0;b<a.ka.length;b++){var d=a.ka[b];c+="("+d.replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\$/g,"\\$")+"|)"}else for(a.ka="A nn [nnnn+X] [nnnn+Y] nnnn [nnnn] [nn+X] [nn+Y] [[nn+X]] [[nn]+Y] [nnnn] [nn]".split(" "),
b=0;b<a.ka.length;b++)d=a.ka[b],c+="("+d.replace(/\[/g,"\\[").replace(/]/g,"\\]").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\+/g,"\\+")+"|)";a.Le=new RegExp(c);a.Nb=[27,a.Oa,9,7,11,12,3,4,8,5]}f.aa=function(){this.u.aa()};function U(a,b,c,d,e,g,k){(a.la&e)==e&&(e=a.u.S(c),a.message(b.id+"."+(g?"setByte":"getByte")+"("+u(c)+")"+(void 0!==d?" @"+u(d):"")+": "+(k?k+"\x3d":"")+t(e)))}f.message=function(a){this.l(a);Xa(this.u)};f.Pb=function(){this.l("Type ? for list of debugger commands\n")};
f.ua=function(){if(!Kb(this))return!1;this.u.ua();return!0};f.step=function(a){if(!Kb(this))return!1;try{var b=this.u.step(a)}catch(c){b=void 0,Ia(this.u,c.stack||c.message)}void 0!==b&&this.L++;this.u.update(!0);this.update(!0);return b};f.update=function(a){this.ta=this.u.f;a||this.za?Lb(this):Mb(this)};function Kb(a){a.u&&J(a.u)&&!K(a.u)?(a=a.u,a.D.error?(a.l(a.toString()+" error"),a=!0):a=!1,a=!a):a=!1;return a}
f.reset=function(){var a;this.wa.length||(this.wa=Array(1E3));for(a=0;a<this.wa.length;a++)this.wa[a]=-1;this.B.length||(this.B=Array(256));for(a=0;a<this.B.length;a++)this.B[a]=[a,0];this.L&&this.update();this.L=0};f.start=function(){this.za||this.l("running")};f.stop=function(a,b){if(!this.za&&(this.l("stopped"),b)){var c=oa();this.l(c-a+"ms ("+b+" cycles)")}this.update();this.ca();this.za||(this.L=0);Nb(this,this.u.f)};function Ob(a,b){return a+(b<<24>>24)}
f.S=function(a){if(a>=this.K&&a<this.Fa){Qa(this.u,a);var b=this.a[this.K+a];b&=255}return b};function Pb(a,b,c){b<a.K||b>=a.Fa?a.l("invalid address: "+u(b)):(a.a[a.K+b]=c&255,Ra(a.u,b),a.u.update())}function Qb(a,b){X(a.oa,b,void 0)||a.oa.push(b);return!0}function X(a,b,c){for(var d=!1,e=0;e<a.length;e++)if(a[e]==b){c&&a.splice(e,1);d=!0;break}return d}function Rb(a,b){void 0!==b&&(Nb(a,a.M),Qb(a,b)&&(a.M=b))}function Nb(a,b){void 0!==a.M&&b==a.M&&X(a.oa,a.M,!0)&&(a.M=void 0);a.za=!1}
function Wa(a,b,c,d){for(var e=!1,g=0;g<c.length;g++)if(c[g]==b){b!=a.M&&a.l("breakpoint hit: "+u(b)+" ("+d+")");e=!0;break}return e}
function Sb(a,b,c){var d=q(b,4),e=a.S(b++),g=void 0===e?0:e,k=a.ga[g],l=[],h=void 0===k[1]?0:k[1];do{d+=" "+q(g,2);if(!h--)break;g=a.S(b++);if(void 0===g)break;l.push(g)}while(1);void 0===k[0]&&(k=[57,1,a.s],l.push(e));d=(d+"        ").substr(0,15);d+=a.Ia[k[0]];var m=null;if(void 0!==k[2]){h=k[2];m=a.ka[h];if(1==k[1]&&h==a.da)m=m.replace(/nnnn/,q(Ob(b,g=l.pop()),4));else for(;l.length;)m=m.replace(/nn/,q(g=l.pop(),2));h==a.s&&1==k[1]&&32<=g&&128>g&&(m+=" ;'"+String.fromCharCode(g)+"'")}if(e==a.u.Za&&
(g<a.W.length&&(m=a.W[g]),g==a.u.Oe)){h=0;for(m='"';g=a.S(b++);)16>h?m+=String.fromCharCode(g):16==h&&(m+="\u2026"),h++;m+='"'}m&&(d+=" "+m);c&&(d=(d+"               ").substr(0,30),d+=";"+c.toString());a.Z=b;return d}
function Y(a,b){var c=a.ta;if(void 0!==b){var d=16;"$"==b.charAt(0)?b=b.substr(1):"0x"==b.substr(0,2)?b=b.substr(2):"."==b.charAt(b.length-1)&&(d=10,b=b.substr(0,b.length-1));c=parseInt(b,d);isNaN(c)&&(a.l("invalid base-"+d+" address: "+b),c=void 0)}void 0!==c&&(c<a.K||c>=a.Fa)&&(a.l("address out of range: "+q(c)),c=void 0);return c}
function Tb(a,b){if("?"==b)a.l("\nfrequency commands:"),a.l("clear\tclear all frequency counts");else{var c=0;if(a.B)if("clear"==b){for(b=0;b<a.B.length;b++)a.B[b]=[b,0];a.l("frequency data cleared");c++}else if(void 0!==b)a.l("unknown frequency command: "+b),c++;else{var d=a.B.slice();d.sort(function(a,b){return b[1]-a[1]});for(b=0;b<d.length;b++){var e=d[b][0],g=d[b][1];g&&(a.l(a.Ia[a.ga[e][0]]+" ("+t(e)+"): "+g+" times"),c++)}}c||a.l("no frequency data available")}}
function Lb(a,b,c,d){var e=Y(a,b);if(void 0!==e){void 0===d&&(d=1);b=a.Fa;if(void 0!==c){b=Y(a,c);if(void 0===b||b<e)return;if(256<b-e){a.l("range too large");return}b++;d=-1}for(e!=a.ta&&a.l();d--&&e<b;)c=Sb(a,e,K(a,!1)||a.za?a.L:0),a.l(c),a.ta=e=a.Z}}
function Mb(a,b){if(b&&"?"==b[1])a.l("\nregister commands:"),a.l("r to display all"),a.l("r [target\x3dvalue] to modify"),a.l("supported targets:"),a.l("A,X,Y,S,PC and flags C,Z,D,V,N");else{var c=!0;if(void 0!==b&&1<b.length){c=!1;var d=b[1],e=d.indexOf("\x3d");if(0<e)b=d.substr(e+1),d=d.substr(0,e);else if(2<b.length)b=b[2];else{a.l("missing value for "+b[1]);return}e=parseInt(b,16);if(isNaN(e)){a.l("invalid value: "+b);return}switch(d.toUpperCase()){case "A":a.u.h=e&255;break;case "X":a.u.A=e&
255;break;case "Y":a.u.F=e&255;break;case "C":a.u.c=e?256:0;break;case "Z":a.u.j=e?0:1;break;case "D":e?Za(a.u):$a(a.u);break;case "V":e?(d=a.u,d.s=0,d.w=128):(d=a.u,d.s=0,d.w=0);break;case "N":a.u.i=e?128:0;break;case "S":if(256!=(e&-256)){a.l("invalid stack pointer: "+b);return}a.u.G=e;break;case "PC":c=!0;a.u.f=e&65535;a.ta=a.u.f;break;default:a.l("unknown register: "+d);return}a.u.update()}a.l("A\x3d"+q(a.u.h,2)+" X\x3d"+q(a.u.A,2)+" Y\x3d"+q(a.u.F,2)+" P\x3d"+q(Ua(a.u),2)+" S\x3d"+q(a.u.G,4)+
" PC\x3d"+q(a.u.f,4));c&&Lb(a,q(a.ta=a.u.f,4))}}function Ub(a,b){b=void 0===b?1:parseInt(b,10);var c=1==b?0:1;sa(b,function(a){return function(){return L(a,!0)&&a.step(c)}}(a),function(a){return function(){L(a,!1)}}(a))}
function Jb(a,b){b.length||(a.Sa?(a.l("ended assemble @"+q(a.ha,4)),a.ta=a.ha,a.Sa=!1):a.fb&&(b=a.fb));if(J(a)&&!K(a,!0)&&0<b.length){a.Sa?b="a "+q(a.ha,4)+" "+b:1<b.length&&1!=b.indexOf(" ")&&(b=b.charAt(0).toLowerCase()+" "+b.substr(1));var c=b.split(" ");a.fb=c[0];switch(c[0].toLowerCase()){case "a":var d=Y(a,c[1]);if(void 0!==d)if(a.ha=d,void 0===c[2])a.l("begin assemble @"+u(a.ha)),a.Sa=!0,a.u.update();else{b=c[2];var e=c[3];c=a.ha;d=[];if(void 0!==b){var g;b=b.toUpperCase();"?"==b.charAt(b.length-
1)&&(e="?",b=b.substr(0,b.length-1));for(g=0;g<a.Ia.length&&b!=a.Ia[g];g++);g==a.Ia.length&&(a.l("unknown operation: "+b),g=-1);var k="",l;if(0<=g&&void 0!==e)if(k=e.toUpperCase(),"?"==k){for(e=l=0;e<a.ga.length;e++)a.ga[e][0]===g&&(l||a.l("supported opcodes:"),a.l("     "+q(e,2)+": "+b+(void 0!==a.ga[e][2]?" "+a.ka[a.ga[e][2]]:"")),l++);g=-1}else if(l=k.match(a.Le),null!==l&&l[0]==k){for(e=1;e<l.length;e++)if(l[e]==k)if(void 0===h)var h=e-1;else{a.l("too many operand matches (both "+a.ka[h]+" and "+
a.ka[e-1]+")");g=-1;break}h==a.Na&&0>a.Nb.indexOf(g)&&(h=a.P);h==a.kb&&27!=g&&(h=a.P)}else a.l("unknown operand: "+k),g=-1;if(0<=g){l=-1;for(e=0;e<a.ga.length;e++)if(a.ga[e][0]===g&&a.ga[e][2]===h)if(0>l)l=e;else{a.l("too many instruction matches (both "+t(l)+" and "+t(e)+")");l=-2;break}if(0<=l){if(d.push(l),void 0!==h)if(b=a.ga[l][1],k=k.match(/[0-9A-F]+/),null!==k)for(k=parseInt(k[0],16),1==b&&h==a.da&&(k-=c+2,-128>k||127<k)&&(a.l("branch out of range ("+k+")"),d=[],b=0),e=0;e<b;e++)d.push(k&255),
k>>>=8;else b&&a.l("instruction missing "+b+" bytes")}else a.l("unknown instruction: "+b+" "+k)}}h=d;if(h.length){for(c=0;c<h.length;c++)Pb(a,a.ha+c,h[c]);a.l(Sb(a,a.ha));a.ha+=h.length}}break;case "b":h=c[1];c=c[2];if(void 0===h||"?"==h)a.l("\nbreakpoint commands:"),a.l("bp [a]\tset exec breakpoint at [a]"),a.l("br [a]\tset read breakpoint at [a]"),a.l("bw [a]\tset write breakpoint at [a]"),a.l("bc [a]\tclear breakpoint at [a]"),a.l("bl\tlist all breakpoints");else if(void 0===c&&1<h.length&&(c=
h.substr(1),h=h.charAt(0)),"l"==h){h=0;d=a.oa;for(c=0;c<d.length;c++)a.l("breakpoint enabled: "+u(d[c])+" (exec)"),h++;d=a.va;for(c=0;c<d.length;c++)a.l("breakpoint enabled: "+u(d[c])+" (read)"),h++;d=a.xa;for(c=0;c<d.length;c++)a.l("breakpoint enabled: "+u(d[c])+" (write)"),h++;h||a.l("no breakpoints")}else void 0===c?a.l("missing breakpoint address"):"c"==h&&"*"==c?(a.oa=[],a.va=[],a.xa=[],a.l("all breakpoints cleared")):(c=Y(a,c),void 0!==c&&("p"==h?Qb(a,c)?a.l("breakpoint enabled: "+u(c)+" (exec)"):
a.l("breakpoint not set: "+u(c)):"c"==h?X(a.oa,c,!0)?a.l("breakpoint cleared: "+u(c)+" (exec)"):X(a.va,c,!0)?a.l("breakpoint cleared: "+u(c)+" (read)"):X(a.xa,c,!0)?a.l("breakpoint cleared: "+u(c)+" (write)"):a.l("breakpoint missing: "+u(c)):"r"==h?(X(a.va,c,void 0)||a.va.push(c),a.l("breakpoint enabled: "+u(c)+" (read)")):"w"==h?(X(a.xa,c,void 0)||a.xa.push(c),a.l("breakpoint enabled: "+u(c)+" (write)")):a.l("unknown breakpoint command: "+h)));break;case "d":h=c[1];d=c[2];if("?"==h)a.l("\ndump commands:"),
a.l("d [a] [#]    dump # lines of memory");else if(h=Y(a,h),void 0!==h){c=0;void 0!==d&&("l"==d.charAt(0)&&(d=d.substr(1)),c=parseInt(d,10));c||(c=1);for(d=0;d<c;d++){k=b="";e=h;for(g=0;8>g&&h<a.Fa;g++)l=a.S(h),void 0===l&&(l=0),b+=q(l,2)+" ",k+=32<=l&&127>l?String.fromCharCode(l):".",h++;a.l(q(e,4)+" "+b+k)}a.ta=h}break;case "e":h=c[1];if(void 0===h)a.l("missing address");else if(h=Y(a,h),void 0!==h)for(d=2;d<c.length;d++)b=parseInt(c[d],16),Pb(a,h++,b);break;case "f":Tb(a,c[1]);break;case "g":h=
c[1];void 0!==h&&Rb(a,Y(a,h));a.ua()||a.u.ca();break;case "h":a.aa();break;case "o":if(void 0===c[1]||"?"==c[1])a.l("\noption commands:"),a.l("max\trun at maximum speed"),a.l("fast\trun faster (up to "+a.u.Ha+"Mhz)"),a.l("slow\trun at normal speed (1Mhz)"),a.l("classic\tuse classic operand syntax"),a.l("modern\tuse modern operand syntax"),a.l("msg\tenable message categories");else switch(h=c[1],h){case "slow":P(a.u,a.u.Pa);break;case "fast":P(a.u,a.u.Pe);break;case "max":P(a.u,a.u.Qe);break;case "classic":Ib(a,
!0);a.l("classic syntax enabled");break;case "modern":Ib(a,!1);a.l("modern syntax enabled");break;case "msg":h=0;void 0!==c[2]&&("all"==c[2]?h=255:void 0!==a.Qa[c[2]]&&(h=a.Qa[c[2]]),h&&("on"==c[3]?a.la|=h:"off"==c[3]&&(a.la&=~h)));for(d in a.Qa)if(void 0===c[2]||"all"==c[2]||c[2]==d)h=a.Qa[d],a.l(d+" messages: "+(a.la&h?"on":"off"));break;default:a.l("unknown option: "+h)}break;case "p":k=c[1];h=10;c=a.Ka;d=a.wa;if(void 0!==d){b=void 0===k?a.Qb:parseInt(k,10);void 0===b&&(b=10);b>d.length&&(a.l("note: only "+
d.length+" available"),b=d.length);void 0!==k&&(a.eb=0,a.l(b+" instructions earlier:"));k=a.eb?a.eb:1;c-=b;for(0>c&&(c=d.length-1);h&&c!=a.Ka;){e=d[c];if(0>e)break;a.l(Sb(a,e,k++));++c==d.length&&(c=0);h--;b--}a.Qb=b;a.eb=k}10==h&&a.l("no history available");break;case "r":Mb(a,c);break;case "s":a.S(a.u.f)==a.u.Oa?(Rb(a,a.u.f+3),a.za=!0,a.ua()||a.u.ca()):Ub(a);break;case "t":Ub(a,c[1]);break;case "u":Lb(a,c[1],c[2],8);break;case "?":case "help":a.l("\ncommands:\n?\thelp\na [#]\tassemble\nb [#]\tbreakpoint\nd [#]\tdump memory\ne [#]\tedit memory\nf\tdump frequencies\ng [#]\trun to [#]\nh\thalt\no\toptions\np [#]\tdump history\nr\tdump/edit registers\ns\tstep over instruction\nt [#]\tstep instruction(s)\nu [#]\tunassemble");
a.l("note: frequency and history commands operate only when breakpoints are set");break;default:a.l("unknown command: "+b)}}}y(function(){for(var a=G(document,"c1pjs","debugger"),b=0;b<a.length;b++){var c=a[b],d=H(c);d=new Hb(d);F(d,c)}});function Z(a,b){C.call(this,"C1PComputer",a);this.$=b}p(Z,C);Z.prototype.reset=function(a){var b=null,c;for(c in this.$)for(var d=0;d<this.$[c].length;d++){var e=this.$[c][d];e&&e.reset&&(e.reset(),"cpu"==c&&(b=e))}b&&(b.update(),a&&b.ua())};
Z.prototype.start=function(){for(var a in this.$)if("cpu"!=a)for(var b=0;b<this.$[a].length;b++){var c=this.$[a][b];c&&c.start&&c.start()}};Z.prototype.stop=function(a,b){for(var c in this.$)if("cpu"!=c)for(var d=0;d<this.$[c].length;d++){var e=this.$[c][d];e&&e.stop&&e.stop(a,b)}};Z.prototype.T=function(a,b,c){switch(b){case "reset":return this.H[b]=c,c.onclick=function(a){return function(){a.reset()}}(this),!0}return!1};function O(a,b){return a.$[b]?a.$[b][0]:null}
function Vb(a){var b=null,c;for(c in a.$)for(var d=0;d<a.$[c].length;d++){var e=a.$[c][d];if(e){if(!J(e)){J(e,function(a){return function(){Vb(a)}}(a));return}"cpu"==c?b=e:e.ia&&e.ia(!0,a)}}a.X();a.l("C1Pjs v1.70.0\nCopyright \u00a9 2012-2018 Jeff Parsons \x3cJeff@pcjs.org\x3e");b&&b.ia(!0,a)}
y(function(){for(var a=G(document,"c1pjs","computer"),b=0;b<a.length;b++){for(var c=a[b],d=H(c),e,g={},k,l=0,h=0,m=0;m<d.modules.length;m++){var n=d.modules[m];if(!m){if("cpu"!=n.type)break;l=n.start;h=n.end;k=Array(h+1-l);for(e=l;e<k.length;e++)k[e]=0}if(e=Ba(n.refID,d.id)){var r=n.type;void 0===g[r]&&(g[r]=[]);g[r].push(e);e.ba&&void 0!==n.start&&e.ba(k,n.start,n.end,g.cpu[0])}else{A('no component for \x3cmodule refid\x3d"'+n.refID+'"\x3e');return}}if(void 0===k){A('\x3cmodule type\x3d"cpu"\x3e definition must appear first in the \x3ccomputer\x3e specification');
break}if(e=Ba("debugger",d.id))g["debugger"]=[e],e.ba&&e.ba(k,l,h,g.cpu[0]);l=new Z(d,g);if(h=Ba("panel",d.id))if(g.panel=[h],h.H.print){e=void 0;d=d.id;g=[];d&&(d=0<(e=d.indexOf("."))?d.substr(0,e+1):"");for(e=0;e<D.length;e++)m=D[e],d&&m.id.indexOf(d)||g.push(m);d=g;for(g=0;g<d.length;g++)e=d[g],e!=h&&(e.Va=h.Va,e.print=h.print,e.l=h.l)}F(l,c);Vb(l)}});var Wb=0;
function Xb(a,b,c,d,e,g){e("Loading "+a+"...");w(a,function(k,l,h){h?(l||(l="unable to load "+a+" ("+h+")"),g(l,null)):Yb(l,a,b,c,d,e,g)})}
function Yb(a,b,c,d,e,g,k){function l(a,g){if(g)k(g,null);else{if(c){N[c]&&b&&(N[c][b]=a);(g=b)&&0>g.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(g=window.location.pathname+g);h?"}"==h.slice(-1)?(h=h.slice(0,-1),1<h.length&&(h+=",")):h='{state:"'+h+'",':h="{";h+='url:"'+g+'"}';"object"==typeof resources&&(g=null);h=h.replace(/\$/g,"$$$$");if(d){var l=a.match(/(<machine[^>]*\sclass=)(['"])(.*?)(\2.*?>)/);l&&(a=a.replace(l[0],l[1]+l[2]+d+l[4]),d="")}a=a.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,
"$1$2"+c+"$2"+(d?' class\x3d"'+d+'"':"")+(h?" parms\x3d'"+h+"'":"")+(g?' url\x3d"'+g+'"':""))}e||(a=a.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1C1Pjs$2"),a=a.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1c1pjs$2"));g=null;if("\x3c"==a.charAt(0))try{e||(a=a.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(g=new window.ActiveXObject("Microsoft.XMLDOM"),g.async=!1,g.loadXML(a)):g=(new window.DOMParser).parseFromString(a,
"text/xml")}catch(E){g=null,a=E.message}else a="unrecognized XML: "+(255<a.length?a.substr(0,255)+"...":a);k(a,g)}}var h="";a?e?Zb(a,g,l):l(a,""):k("no data"+(b?" for file: "+b:""),null)}
function Zb(a,b,c){var d;if(d=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(a)){var e=d[2];b("Loading "+e+"...");w(e,function(g,k,l){if(l||!k)c(a,"unable to resolve XML reference: "+d[0]+" ("+l+")");else{if(g=d[3])if(l=k.match(new RegExp("\x3c"+d[1]+"[^\x3e]*\x3e"))){for(var h=l[0],m,n=/( [a-z]+=)(['"])(.*?)\2/gi;m=n.exec(g);)h=0>h.toLowerCase().indexOf(m[1].toLowerCase())?h.replace("\x3e",m[0]+"\x3e"):h.replace(new RegExp(m[1]+"(['\"])(.*?)\\1"),m[0]);l[0]!=h&&(k=k.replace(l[0],h))}else{c(a,"missing \x3c"+
d[1]+"\x3e in "+e);return}k=k.replace(/<\?xml[^>]*>[\r\n]*/,"");a=a.replace(d[0],k);Zb(a,b,c)}})}else c(a,"")}
function $b(a,b,c,d){function e(a){if(void 0===l){var b=k&&G(k,"machine-warning");l=b&&b[0]||k}l&&(l.innerHTML=ma(a))}function g(a){e("Error: "+a);h&&(--Wb||B(!0));h=!1}var k,l,h=!0;b||(b="machine.xml",c||(c="components.xsl"));Wb++;N[a]={};try{if(k=document.getElementById(a)){var m;if("object"==typeof resources&&(m=resources.css)){var n=document.head||document.getElementsByTagName("head")[0],r=document.createElement("style");r.type="text/css";r.styleSheet?r.styleSheet.cssText=m:r.appendChild(document.createTextNode(m));
n.appendChild(r)}c||(c="/versions/c1pjs/1.70.0/components.xsl");m=function(d,h){h?Xb(c||"","","",!1,e,function(d,l){if(l){var m=c||"";N[a]&&m&&(N[a][m]=d);e("Processing "+b+"...");window.ActiveXObject||"ActiveXObject"in window?(l=h.transformNode(l))?(k.outerHTML=l,--Wb||B(!0)):g("transformNodeToObject failed"):document.implementation&&document.implementation.createDocument?(d=new XSLTProcessor,d.importStylesheet(l),(l=d.transformToFragment(h,document))?k.parentNode?(k.parentNode.replaceChild(l,k),
--Wb||B(!0)):g("invalid machine element: "+a):g("transformToFragment failed")):g("unable to transform XML: unsupported browser")}else g(d)}):g(d)};"\x3c"!=b.charAt(0)?Xb(b,a,d||"",!0,e,m):Yb(b,"",a,d||"",!1,e,m)}else g("missing machine element: "+a)}catch(E){g(E.message)}return h}window.embedC1P=function(a,b,c,d,e){B(!1);return $b(a,b,c,e)};
window.commandMachine=function(a,b,c,d,e,g){if("script"==e){d=!1;c+=".machine";if(!g)delete I[c],d=!0;else if("string"==typeof g&&!I[c]){d=!0;e=I;for(var k=c,l=g.length,h=[],m=[],n="",r=null,E=0;E<l;E++){var v=g[E];if('"'==v||"'"==v)r&&v!=r?n+=v:(r?r=null:r=v,n&&(m.push(n),n=""));else{if(!r){if("\r"==v||"\n"==v)v=";";if(" "==v||"\t"==v||";"==v){n&&(m.push(n),n="");";"==v&&m.length&&(h.push(m),m=[]);continue}}n+=v}}n&&m.push(n);m.length&&h.push(m);e[k]=h;Da(c)||(d=!1)}return d?(b&&(a.disabled=!0),
!0):!1}if(d&&(k=Ca(d,c+".machine"))&&(l=k.exports)&&(l=l[e]))return l.call(k,g)?(b&&(a.disabled=!0),!0):!1;console.log("unimplemented: commandMachine('"+c+"','"+d+"','"+e+"','"+g+"')");return!1};window.enableEvents=B;window.sendEvent=ya;})()
//# sourceMappingURL=c1p.js.map
