(function(){var g;function da(a,b){var c;if(a){b||(b=16);if("$"==a.charAt(0))b=16,a=a.substr(1);else if("0x"==a.substr(0,2))b=16,a=a.substr(2);else{var d=a.charAt(a.length-1).toLowerCase();"h"==d?(b=16,d=null):"."==d&&(b=10,d=null);null==d&&(a=a.substr(0,a.length-1))}var e,d=a,f=b;(f&&10!=f?16==f?null!==d.match(/^[0-9a-f]+$/i):2==f&&null!==d.match(/^[01]+$/i):null!==d.match(/^[0-9]+$/))&&!isNaN(e=parseInt(a,b))&&(c=e|0)}return c}
function n(a,b){var c="";void 0===b?b=8:8<b&&(b=8);if(null==a||isNaN(a))for(;0<b--;)c="?"+c;else for(;0<b--;){var d=a&15,d=d+(0<=d&&9>=d?48:55),c=String.fromCharCode(d)+c;a>>=4}return c}function q(a){return"0x"+n(a,4)}function ea(a,b){var c=a,d=a.lastIndexOf("/");0<=d&&(c=a.substr(d+1));d=c.indexOf("&");0<d&&(c=c.substr(0,d));b&&(d=c.lastIndexOf("."),0<d&&(c=c.substring(0,d)));return c}function fa(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase());return b}
function ka(a,b){return-1!==a.indexOf(b,a.length-b.length)}var la={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"};function ma(a){return a.replace(/[&<>"']/g,function(a){return la[a]})}function ra(a,b){return(a+"                                        ").slice(0,b)}function sa(a){return String.prototype.trim?a.trim():a.replace(/^\s+|\s+$/g,"")}
function ta(a,b,c){var d=0,e=a.length,f=0;for(void 0===c&&(c=function(a,b){return a>b?1:a<b?-1:0});d<e;){var k=d+e>>1,h;h=c(b,a[k]);0<h?d=k+1:(e=k,f=!h)}return f?d:~d}var ua=Date.now||function(){return+new Date};function va(){function a(a){return(10>a?"0":"")+a}var b=new Date;return b.getFullYear()+"-"+a(b.getMonth()+1)+"-"+a(b.getDate())+" "+a(b.getHours())+":"+a(b.getMinutes())+":"+a(b.getSeconds())}
function wa(a,b){var c;if(Array.prototype.indexOf)return a.indexOf(b,c);c=c||0;0>c&&(c+=a.length);0>c&&(c=0);for(var d=a.length;c<d;c++)if(c in a&&a[c]===b)return c;return-1}
function u(a,b,c,d){var e=0,f=null,k=null;if("object"==typeof resources&&(f=resources[a]))return d&&d(a,f,e),[f,e];if(c&&"function"==typeof resources)return resources(a,function(b,c){d&&d(a,b,c)}),k;var h=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");c&&(h.onreadystatechange=function(){4===h.readyState&&(f=h.responseText,200==h.status||!h.status&&f.length&&"file:"==(window?window.location.protocol:"file:")||(e=h.status||-1),d&&d(a,f,e))});if(b&&"object"==
typeof b){var l="",m;for(m in b)b.hasOwnProperty(m)&&(l&&(l+="&"),l+=m+"="+encodeURIComponent(b[m]));l=l.replace(/%20/g,"+");h.open("POST",a,!!c);h.setRequestHeader("Content-type","application/x-www-form-urlencoded");h.send(l)}else h.open("GET",a,!!c),"bytes"==b&&h.overrideMimeType("text/plain; charset=x-user-defined"),h.send();c||(f=h.responseText,200!=h.status&&(e=h.status||-1),d&&d(a,f,e),k=[f,e]);return k}function xa(){return"http://"+(window?window.location.host:"www.pcjs.org")}
function ya(){return window?window.navigator.userAgent:""}function v(a){window&&window.alert(a)}function za(a){var b=!1;window&&(b=window.confirm(a));return b}var Aa=null;function Ea(){if(null==Aa){var a=!1;if(window)try{window.localStorage.setItem("PCjs.localStorage","PCjs.localStorage"),a="PCjs.localStorage"==window.localStorage.getItem("PCjs.localStorage"),window.localStorage.removeItem("PCjs.localStorage")}catch(b){a=!1}Aa=a}return Aa}
function Ha(a){var b;if(window)try{b=window.localStorage.getItem(a)}catch(c){}return b}function Ia(a,b){try{return window.localStorage.setItem(a,b),!0}catch(c){}return!1}function Ja(a){if(window){var b=ya();return"iOS"==a&&b.match(/(iPod|iPhone|iPad)/)&&b.match(/AppleWebKit/)||"MSIE"==a&&b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)?!0:!1}return!1}function Ka(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function La(a,b){function c(){b(100===d)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,f=!1;a.onmousedown=function(){f||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);f=!0}}var Ma={init:[],show:[],exit:[]},Na=!1,Oa=!0;function Pa(a,b){if(window){var c=window[a];window[a]="function"!==typeof c?b:function(){c&&c();b()}}}function Qa(a){Ma.init.push(a)}
function Ra(a){if(Oa)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){v("An unexpected exception occurred:\n\n"+c.message+"\n\nPlease send this information to support@pcjs.org. Thanks.")}}function Sa(a){!Oa&&a?(Oa=!0,Na&&Ta("init")):Oa=a}function Ta(a){Ma[a]&&Ra(Ma[a])}Pa("onload",function(){Na=!0;Ra(Ma.init)});Pa("onpageshow",function(){Ra(Ma.show)});Pa(Ja("Opera")||Ja("iOS")?"onunload":"onbeforeunload",function(){Ra(Ma.exit)});
function x(a,b,c,d){this.type=a;b||(b={id:"",name:""});this.id=b.id;this.name=b.name;this.vb=b.comment;this.Kb=b;void 0===this.id&&(this.id="");b=this.id.indexOf(".");0<b?(this.zb=this.id.substr(0,b),this.Wa=this.id.substr(b+1)):this.Wa=this.id;this[a]=c;this.j={Ka:!1,Ha:!1,ob:!1,W:!1,Ja:!1};this.kb=null;this.j.Ja=!1;this.G={};this.B=null;this.Y=d||0;y.push(this)}var Ua=void 0,Va={};
if(window){Ua||(Ua=window.location.search.substr(1));for(var Wa,Xa=/\+/g,Ya=/([^&=]+)=?([^&]*)/g;Wa=Ya.exec(Ua);)Va[decodeURIComponent(Wa[1].replace(Xa," "))]=decodeURIComponent(Wa[2].replace(Xa," "))}function ib(a){function b(){}if(window){if(!a)throw new TypeError;if(Object.create)return Object.create(a);var c=typeof a;if("object"!==c&&"function"!==c)throw new TypeError;}b.prototype=a;return new b}
function z(a,b){b||(b=x);a.prototype=ib(b.prototype);a.prototype.constructor=a;a.prototype.parent=b.prototype}var y=[],jb={};function kb(a,b,c){jb[a]&&b&&(jb[a][b]=c)}function C(a){var b,c=[];a&&(a=0<(b=a.indexOf("."))?a.substr(0,b+1):"");for(b=0;b<y.length;b++){var d=y[b];a&&d.id.indexOf(a)||c.push(d)}return c}
function lb(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<y.length;d++)if(c)c==y[d]&&(c=null);else if(!(a!=y[d].type||b&&y[d].id.indexOf(b)))return y[d]}return null}function E(a){var b=null;if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(c){v(c.message+" ("+a+")")}return b}
function mb(a,b){for(var c=F(b.parentNode,"pc8080-control"),d=0;d<c.length;d++)for(var e=c[d].childNodes,f=0;f<e.length;f++){var k=e[f];if(1===k.nodeType){var h=k.getAttribute("class");if(h)for(var l=h.split(" "),m=0;m<l.length;m++)switch(h=l[m],h){case "pc8080-binding":(h=E(k))&&h.binding&&a.ea(h.type,h.binding,k,h.value),m=l.length}}}}
function F(a,b,c){c&&(b+="-"+c+"-object");if(a.getElementsByClassName)return a.getElementsByClassName(b);var d;c=[];a=a.getElementsByTagName("*");var e=new RegExp("(^| )"+b+"( |$)");b=0;for(d=a.length;b<d;b++)e.test(a[b].className)&&c.push(a[b]);return c}
x.prototype={constructor:x,parent:null,toString:function(){return this.name?this.name:this.id||this.type},ea:function(a,b,c){switch(b){case "clear":return this.G[b]||(this.G[b]=c,c.onclick=function(a){return function(){a.G.print&&(a.G.print.value="")}}(this)),!0;case "print":return this.G[b]||(this.xa=this.G[b]=c,c.value="",this.g=function(a){return function(b,c){8192<a.value.length&&(a.value=a.value.substr(a.value.length-4096));a.value+=(void 0!==c?c+": ":"")+(b||"")+"\n";a.scrollTop=a.scrollHeight}}(c),
this.ba=function(a,b,c){this.g(a,"notice",c)}),!0;default:return!1}},log:function(){},g:function(){},status:function(a){this.g(this.Wa+": "+a)},ba:function(a,b){b||v(a)},pa:function(){return this.j.W=!0},oa:function(a,b){b&&(this.j.W=!1);return!0}};function nb(a,b,c){a.B&&(!0===c||ob(a,c|0))&&a.B.message(b,void 0)}function ob(a,b){if(a.B){a===a.B?b|=0:b=b||a.Y;var c=a.B.Y&b;return!!b&&c===b||!!(c&a.B.Rb)}return!1}
function pb(a,b){if(a.j.ob)return a.j.Ha&&(a.j.Ha=!1),a.j.ob=!1;if(a.j.Ja)return a.g(a.toString()+" error"),!1;a.j.Ha=b;return a.j.Ha}function qb(a,b){a.j.Ha&&(b?a.j.ob=!0:void 0===b&&a.g(a.toString()+" busy"));return a.j.Ha}function G(a){if(!a.j.Ja&&(a.j.Ka=!0,a.j.Ka)){var b=a.kb;a.kb=null;b&&b()}}function rb(a,b){b&&(a.j.Ka?b():a.kb=b);return a.j.Ka}function sb(a,b){a.j.Ja=!0;a.ba(b)}
var tb="undefined"!==typeof ArrayBuffer,ub=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,
0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1];function vb(a){x.call(this,"Panel",a,vb)}z(vb);g=vb.prototype;g.ea=function(a,b,c,d){return this.s&&this.s.ea(a,b,c,d)||this.b&&this.b.ea(a,b,c,d)||this.w&&this.w.ea(a,b,c,d)||this.B&&this.B.ea(a,b,c,d)?!0:this.parent.ea.call(this,a,b,c,d)};g.La=function(a,b,c,d){this.s=a;this.A=b;this.b=c;this.B=d;this.w=wb(a,"Keyboard")};g.pa=function(a,b){b||xb();return!0};g.oa=function(){return!0};g.fa=function(){};
function xb(){for(var a=!1,b=F(document,"pc8080","panel"),c=0;c<b.length;c++){var d=b[c],e=E(d),f;a:{f=e.id;if(void 0!==f)for(var k=void 0,k=0;k<y.length;k++)if(y[k].id===f){f=y[k];break a}f=null}f||(a=!0,f=new vb(e));mb(f,d);a&&G(f)}}Qa(xb);
function yb(a,b,c){x.call(this,"Bus",a,yb);this.b=b;this.B=c;this.J=a.buswidth||16;this.M=Math.pow(2,this.J);this.w=this.M-1|0;this.P=20>=this.J?12:24>=this.J?14:15;this.Z=1<<this.P;this.R=this.Z>>2;this.s=this.Z-1;this.I=this.M/this.Z|0;this.L=this.I-1;this.C=[];this.D=[];this.F=this.H=!1;this.S=[];this.V=[];a=new H;zb(a,this.B);this.A=Array(this.I);for(b=0;b<this.I;b++)this.A[b]=a;a=this.b;b=this.A;c=this.P;var d=this.w;a.ga=b;a.P=c;a.Z=1<<a.P;a.I=a.Z-1;a.S=b.length;a.R=a.S-1;a.L=d;G(this)}z(yb);
yb.prototype.reset=function(){};yb.prototype.pa=function(a,b){b||this.reset();return!0};function Ab(a,b,c,d){for(var e=b>>>a.P;0<c&&e<a.A.length;){var f=a.A[e],k=e*a.Z,h=c>a.Z?a.Z:c;if(f&&f.size){if(f.type==d){if(b+c<=f.u)return f.gb+=f.u-b,f.u=b,!0;if(b>=f.u+f.gb){h=f.size-(b-k);h>c&&(h=c);f.gb=b-f.u+h;c-=h;b=k+a.Z;continue}}return Bb(1,b,c)}f=a.A[e];b=new H(b,h,a.Z,d);zb(b,a.B,f);a.A[e++]=b;b=k+a.Z;c-=h}return 0>=c?!0:Bb(2,b,c)}function Cb(a,b){return a.A[(b&a.w)>>>a.P].eb(b&a.s,b)}
function Db(a,b){if(void 0===b)return a.F=!a.F,a.F;void 0===a.C[b]&&(a.C[b]=[null,!1]);a.C[b][1]=!a.C[b][1];return a.C[b][1]}function Qb(a,b){if(void 0===b)return a.H=!a.H,a.H;void 0===a.D[b]&&(a.D[b]=[null,!1]);a.D[b][1]=!a.D[b][1];return a.D[b][1]}function Bb(a,b,c){v("Memory block error ("+a+": "+n(b)+","+n(c)+")");return!1}var Rb;if(tb){var Sb=new ArrayBuffer(2);(new DataView(Sb)).setUint16(0,256,!0);Rb=256===(new Uint16Array(Sb))[0]}else Rb=!1;var Tb=Rb;
function H(a,b,c,d){this.id=Ub+=2;this.b=null;this.u=a;this.gb=b;this.size=c||0;this.type=d||Vb;this.F=d==Wb;zb(this);this.sa=this.Ub=!1;if(c)if(tb)this.C=new ArrayBuffer(c),this.D=new DataView(this.C,0,c),this.G=new Uint8Array(this.C,0,c),this.H=new Uint16Array(this.C,0,c>>1),this.b=new Int32Array(this.C,0,c>>2),Xb(this,Tb?Yb:Zb);else{this.b=Array(c>>2);for(a=0;a<this.b.length;a++)this.b[a]=0;Xb(this,$b)}else Xb(this)}var Vb=0,Wb=2,ac=["NONE","RAM","ROM","VIDEO","H/W"],Ub=0;
H.prototype={constructor:H,parent:null,save:function(){var a,b;if(tb)for(a=Array(this.size>>2),b=0;b<a.length;b++)a[b]=this.D.getInt32(b<<2,!0);else a=this.b;return a},restore:function(a){if(a&&this.size==a.length<<2){var b;if(tb)for(b=0;b<a.length;b++)this.D.setInt32(b<<2,a[b],!0);else this.b=a;return this.sa=!0}return!1},wa:function(a,b){b?0===this.s++&&bc(this,cc,!1):0===this.A++&&dc(this,cc,!1)},I:function(){this.B&&ob(this.B,129)&&this.B.message("attempt to read invalid block %"+n(this.u),!0);
return 255},w:function(a,b){this.B&&ob(this.B,129)&&this.B.message("attempt to write "+q(b)+" to invalid block %"+n(this.u),!0)},J:function(a,b){return this.Sa(a++,b++)|this.Sa(a,b)<<8},Wa:function(a,b,c){this.mb(a++,b&255,c++);this.mb(a,b>>8,c)},S:function(a){return this.b[a>>2]>>>((a&3)<<3)&255},ia:function(a){var b=a>>2;a=(a&3)<<3;var c=this.b[b]>>a;return 24>a?c&65535:c&255|(this.b[b+1]&255)<<8},va:function(a,b){var c=a>>2,d=(a&3)<<3;this.b[c]=this.b[c]&~(255<<d)|b<<d;this.sa=!0},ib:function(a,
b){var c=a>>2,d=(a&3)<<3;24>d?this.b[c]=this.b[c]&~(65535<<d)|b<<d:(this.b[c]=this.b[c]&16777215|b<<24,c++,this.b[c]=this.b[c]&-256|b>>8);this.sa=!0},M:function(a,b){if(this.B&&null!=this.u){var c=this.B;ec(c,this.u+a,1,c.R)&&c.U(!0)}return this.eb(a,b)},aa:function(a,b){if(this.B&&null!=this.u){var c=this.B;ec(c,this.u+a,2,c.R)&&c.U(!0)}return this.tb(a,b)},ma:function(a,b,c){if(this.B&&null!=this.u){var d=this.B;ec(d,this.u+a,1,d.F)&&d.U(!0)}this.F?this.w(a,b,c):this.Ua(a,b,c)},Va:function(a,b,
c){if(this.B&&null!=this.u){var d=this.B;ec(d,this.u+a,2,d.F)&&d.U(!0)}this.F?this.w(a,b,c):this.Ob(a,b,c)},L:function(a){return this.G[a]},R:function(a){return this.G[a]},V:function(a){return this.D.getUint16(a,!0)},ca:function(a){return a&1?this.G[a]|this.G[a+1]<<8:this.H[a>>1]},ja:function(a,b){this.G[a]=b;this.sa=!0},ua:function(a,b){this.G[a]=b;this.sa=!0},Ga:function(a,b){this.D.setUint16(a,b,!0);this.sa=!0},Xa:function(a,b){a&1?(this.G[a]=b,this.G[a+1]=b>>8):this.H[a>>1]=b;this.sa=!0}};
function zb(a,b,c){a.B=b;a.A=a.s=0;c&&((a.A=c.A)&&dc(a,cc,!1),(a.s=c.s)&&bc(a,cc,!1))}function fc(a,b){b?0===--a.s&&(a.mb=a.F?a.w:a.Ua):0===--a.A&&(a.Sa=a.eb,a.Lb=a.tb)}function bc(a,b,c){c&&a.s||(a.mb=!a.F&&b[2]||a.w);if(c||void 0===c)a.Ua=b[2]||a.w,a.Ob=b[3]||a.Wa}function dc(a,b,c){c&&a.A||(a.Sa=b[0]||a.I,a.Lb=b[1]||a.J);if(c||void 0===c)a.eb=b[0]||a.I,a.tb=b[1]||a.J}function Xb(a,b){b||(b=gc);dc(a,b,void 0);bc(a,b,void 0)}
var gc=[],$b=[H.prototype.S,H.prototype.ia,H.prototype.va,H.prototype.ib],cc=[H.prototype.M,H.prototype.aa,H.prototype.ma,H.prototype.Va];if(tb)var Zb=[H.prototype.L,H.prototype.V,H.prototype.ja,H.prototype.Ga],Yb=[H.prototype.R,H.prototype.ca,H.prototype.ua,H.prototype.Xa];
function hc(a,b){x.call(this,"CPU",a,hc,1);var c=a.cycles||b,d=a.multiplier||1;this.i={};this.i.Ra=c;this.i.Ba=d;this.i.qb=Math.round(this.i.Ra/1E4)/100;this.i.za=this.i.qb*this.i.Ba;this.j.X=!1;this.j.pb=!1;this.j.Db=a.autoStart;this.j.Eb=!1;this.j.Ia=!1;this.i.Ya=this.i.Oa=0;this.i.Za=a.csStart;this.i.Na=a.csInterval;this.i.Pa=a.csStop;this.ca=this.Fa.bind(this);G(this)}z(hc);var ic=["power","reset"];g=hc.prototype;
g.La=function(a,b,c,d){this.s=a;this.A=b;this.B=d;for(b=0;b<ic.length;b++)(c=this.G[ic[b]])&&this.s.ea(null,ic[b],c);wb(a,"FPU");this.w=wb(a,"ChipSet");a=jc(a,"autoStart");null!=a&&(this.j.Db="true"==a?!0:"false"==a?!1:!!a);G(this)};g.reset=function(){};g.save=function(){return null};g.restore=function(){return!1};
g.pa=function(a,b){if(!b){if(a&&this.restore){kc(this);if(!this.restore(a))return!1;lc(this)}else this.reset();if(this.B){var c=this.B;c.g("Type ? for help with PC8080 Debugger commands");c.fa();if(c.Xa){var d=c.Xa;c.Xa=null;mc(c,d)}}else this.g("No debugger detected")}I(this);return!0};g.oa=function(a){return a?this.save():!0};function nc(a){(a.j.Db||!a.B&&void 0===a.G.run)&&a.Fa(!0)}g.Fb=function(){return 0};
function lc(a){void 0===a.i.Za&&(a.i.Za=0);void 0===a.i.Na&&(a.i.Na=-1);void 0===a.i.Pa&&(a.i.Pa=-1);a.j.Ia=0<=a.i.Za&&0<a.i.Na;a.j.Ia&&(a.i.Ya=0,a.i.Oa=a.i.Za-a.H)}function oc(a,b){if(a.j.Ia){var c=!1;a.i.Ya=a.i.Ya+a.Fb()|0;a.i.Oa-=b;0>=a.i.Oa&&(a.i.Oa+=a.i.Na,c=!0);0<=a.i.Pa&&a.i.Pa<=pc(a)&&(a.i.Na=a.i.Pa=-1,lc(a),a.U(),c=!0);c&&a.g(pc(a)+" cycles: checksum="+n(a.i.Ya))}}
g.ea=function(a,b,c){var d=this;a=!1;switch(b){case "power":case "reset":this.G[b]=c;a=!0;break;case "run":this.G[b]=c;c.onclick=function(){var a;if(a=d.s)if(a=d.s,a.j.W)a=!0;else{var b=null,c,h=C(a.id);for(c=0;c<h.length&&(b=h[c],b===a||b.j.Ka);c++);if(c==h.length)for(c=0;c<h.length&&(b=h[c],b===a||b.j.W);c++);c==h.length&&(b=a);v("The "+b.type+" component ("+b.id+") is not "+(b.j.Ka?"powered yet":"ready yet"+(b.kb?" (waiting for notification)":""))+".");a=!1}a&&(d.j.X?d.U(!0):d.Fa(!0))};a=!0;break;
case "speed":this.G[b]=c;a=!0;break;case "setSpeed":this.G[b]=c,c.onclick=function(){qc(d,d.i.Ba<<1,!0)},c.textContent=this.i.za.toFixed(2)+"Mhz",a=!0}return a};function Qc(a,b,c){a.H+=b;c&&(a.D=a.b=0)}
function Rc(a,b){var c=30;60>c&&(c=60);2>c&&(c=2);var d=1;b&&1<a.i.Ba&&a.i.ya&&(d=a.i.ya/a.i.qb);a.i.Hb=Math.round(1E3/30);a.i.Yb=Math.floor(a.i.Ra/c*d);a.i.rb=Math.floor(a.i.Ra/30*d);a.i.Jb=Math.floor(a.i.Ra/60*d);a.i.Ib=Math.floor(a.i.Ra/2*d);b||(a.i.Qa=a.i.rb,a.i.ab=a.i.Jb,a.i.$a=a.i.Ib);a.i.sb=0}function pc(a){return a.H+a.F+a.D-a.b}function kc(a){a.i.ya=0;a.H=a.F=a.D=a.b=0;lc(a);qc(a,1)}
function qc(a,b,c){var d=!1;if(void 0!==b){.8>a.i.ya/a.i.za?b=1:d=!0;a.i.Ba=b;b=a.i.qb*a.i.Ba;if(a.i.za!=b){a.i.za=b;b=a.i.za.toFixed(2)+"Mhz";var e=a.G.setSpeed;e&&(e.textContent=b);a.g("target speed: "+b)}c&&a.s&&a.s.fb()}Qc(a,a.F);a.F=0;a.i.Ma=ua();a.i.Aa=0;Rc(a);return d}
g.Fa=function(a){if(pb(this,!0)){if(!this.j.X){qc(this);this.s&&this.s.start(this.i.Ma,pc(this));this.j.X=!0;this.j.pb=!0;this.w&&this.w.Zb();var b=this.G.run;b&&(b.textContent="Halt");this.s&&(this.s.fa(!0),a&&this.s.fb(!0))}this.i.sb>=this.i.Ra&&Rc(this,!0);this.i.bb=0;this.i.lb=ua();this.i.Aa&&(a=this.i.lb-this.i.Aa,a>this.i.Hb&&(this.i.Ma+=a,this.i.Ma>this.i.lb&&(this.i.Ma=this.i.lb)));try{do{var c=this.j.Ia?1:this.i.Yb;this.w&&(this.w.Nb(),c=this.w.ac(0,c),c=this.w.$b(c));try{this.Ta(c)}catch(e){if("number"!=
typeof e)throw e;}var d=this.D-this.b;this.F+=d;this.i.bb+=d;Qc(this,0,!0);oc(this,d);this.i.ab-=d;0>=this.i.ab&&(this.i.ab+=this.i.Jb);this.i.$a-=d;0>=this.i.$a&&(this.i.$a+=this.i.Ib,this.s&&this.s.fa());this.i.Qa-=d;if(0>=this.i.Qa){this.i.Qa+=this.i.rb;break}}while(this.j.X)}catch(e){this.U();I(this);this.s&&this.s.stop(ua(),pc(this));pb(this,!1);sb(this,e.stack||e.message);return}c=setTimeout;d=this.ca;this.i.Aa=ua();a=this.i.Hb;this.i.bb&&(a=Math.round(a*this.i.bb/this.i.rb));a-=this.i.Aa-this.i.lb;
if(b=this.i.Aa-this.i.Ma)this.i.ya=Math.round(this.F/(10*b))/100,864E5<=b&&(this.H=0,this.w&&this.w.Nb(!0),qc(this));if(0>a||this.i.ya<this.i.za)a=0;this.i.sb+=this.i.bb;this.i.Aa+=a;c(d,a)}else I(this),this.s&&this.s.stop(ua(),pc(this))};g.Ta=function(){return 0};g.U=function(a){qb(this,!0);this.D-=this.b;this.b=0;Qc(this,this.F);this.F=0;if(this.j.X){this.j.X=!1;this.w&&this.w.Zb();var b=this.G.run;b&&(b.textContent="Run")}this.j.jb=a};function I(a,b){a.s&&a.s.fa(b)}
function Sc(a){this.Gb=a.model||8080;hc.call(this,a,1E6);this.aa=Tc;kc(this);this.j.jb=this.j.Tb=!1;this.V=0;this.ga=[];this.P=this.Z=this.I=this.S=this.R=this.L=0;Uc(this)}z(Sc,hc);g=Sc.prototype;g.reset=function(){this.j.X&&this.U();Uc(this);kc(this);this.j.Ja=!1};function Uc(a){a.ha=0;a.T=0;a.da=0;a.ta=0;a.Ca=0;a.la=0;a.qa=0;a.Ea=0;a.N=0;Vc(a,0);a.M=0}g.Fb=function(){var a=this.ha+this.T+this.da+this.ta+this.Ca+this.la+this.qa|0;return a=a+this.Ea+this.N+Wc(this)|0};
g.save=function(){var a=new J(this);M(a,0,[this.ha,this.T,this.da,this.ta,this.Ca,this.la,this.qa,this.Ea,this.N,Wc(this)]);M(a,1,[this.J,this.M,this.H,this.i.Ba]);for(var b=this.A,c=0,d=[],e=0;e<b.I;e++){var f=b.A[e];if(f.sa||f.Ub){d[c++]=e;var k=c++;a:if(f=f.save()){for(var h=0,l=0,m=[];h<f.length;){for(var p=f[h],r=h+1;r<f.length&&f[r]===p;)r++;m[l++]=r-h;m[l++]=p;h=r}if(m.length<f.length){f=m;break a}}d[k]=f}}M(a,2,d);return a.data()};
g.restore=function(a){var b=a[0];this.ha=b[0];this.T=b[1];this.da=b[2];this.ta=b[3];this.Ca=b[4];this.la=b[5];this.qa=b[6];this.Ea=b[7]&65535;this.N=b[8]&65535;Vc(this,b[9]);b=a[1];this.J=b[0];this.M=b[1];this.H=b[2];qc(this,b[3]);a:{b=this.A;a=a[2];var c;for(c=0;c<a.length-1;c+=2){var d=a[c],e=a[c+1];if(e&&e.length<b.R){for(var f=0,k=Array(b.R),h=0;h<e.length-1;)for(var l=e[h++],m=e[h++];l--;)k[f++]=m;e=k}f=b.A[d];if(!f||!f.restore(e)){v("Unable to restore memory block "+d);b=!1;break a}}b=!0}return b};
g.ea=function(a,b,c){var d=!1;switch(b){case "A":case "B":case "C":case "D":case "E":case "H":case "L":case "SP":case "PC":case "F":case "CF":case "PF":case "AF":case "ZF":case "SF":case "VF":this.G[b]=c;this.V++;d=!0;break;default:d=this.parent.ea.call(this,a,b,c)}return d};function Wc(a){return a.Da&-214|(a.K&128?128:0)|(a.O&255?0:64)|((a.K^a.C)&16?16:0)|(ub[a.K&255]?4:0)|(a.O&256?1:0)}
function Vc(a,b){a.O=a.K=a.C=0;b&1&&(a.O|=256);b&4||(a.K|=1);b&16&&(a.C|=16);b&64||(a.O|=255);b&128&&(a.K^=192);a.Da=a.Da&-513|b&512|2}function Xc(a,b){return a.ga[(b&a.L)>>>a.P].Sa(b&a.I,b)}function Yc(a){var b=Xc(a,a.N);a.N=a.N+1&65535;return b}function N(a,b,c,d){d=d||2;a.G[b]&&(void 0===c&&(sb(a,"Value for "+b+" is invalid"),a.U()),c=!a.j.X||a.j.Eb?n(c,d):"--------".substr(0,d),a.G[b].textContent!=c&&(a.G[b].textContent=c))}
g.fa=function(a){this.V&&(a||!this.j.X||this.j.Eb)&&(N(this,"A",this.ha),N(this,"B",this.T),N(this,"C",this.da),N(this,"D",this.ta),N(this,"E",this.Ca),N(this,"H",this.la),N(this,"L",this.qa),N(this,"SP",this.Ea,4),N(this,"PC",this.N,4),a=Wc(this),N(this,"F",a,2),N(this,"S",a&128,1),N(this,"Z",a&64,1),N(this,"A",a&16,1),N(this,"P",a&4,1),N(this,"C",a&1,1));if(a=this.G.speed)a.textContent=this.j.X&&this.i.ya?this.i.ya.toFixed(2)+"Mhz":"Stopped"};
g.Ta=function(a){this.j.jb=!0;var b=this.j.Tb=this.B&&Zc(this.B),c=a?this.j.pb?0:1:-1;this.j.pb=!1;this.D=this.b=a;this.w&&!a&&this.w.Nb();a||(this.J|=4);do{if(this.M&&this.M&4){this.J=this.b=0;break}if(b){if($c(this.B,this.N,c)){this.U();break}c=1}this.J=0;this.aa[Yc(this)].call(this)}while(0<this.b);return this.j.jb?this.D-this.b:void 0===this.j.jb?0:-1};Qa(function(){for(var a=F(document,"pc8080","cpu"),b=0;b<a.length;b++){var c=a[b],d=E(c),d=new Sc(d);mb(d,c)}});function ad(){this.b-=4}
function O(){this.N=this.N-1&65535;nb(this,"unimplemented opcode",!0);this.U()}
var Tc=[ad,function(){var a;a=this.N;var b=a&this.I,c=(a&this.L)>>>this.P;b<this.I?a=this.ga[c].Lb(b,a):(b=this.ga[c].Sa(b,a),a=b|=this.ga[c+1&this.R].Sa(0,a+1)<<8);this.N=this.N+2&65535;this.T=a>>8&255;this.da=a&255;this.b-=10},function(){var a=this.T<<8|this.da;this.ga[(a&this.L)>>>this.P].mb(a&this.I,this.ha&255,a);this.b-=7},function(){var a=(this.T<<8|this.da)+1;this.T=a>>8&255;this.da=a&255;this.b-=5},function(){var a=this.T;this.C=a;a=(this.K=a+1)&255;this.O=this.O&-256|a;this.T=a;this.b-=
5},function(){var a=this.T;this.C=a;a=(this.K=a-1)&255;this.O=this.O&-256|a;this.T=a;this.b-=5},function(){this.T=Yc(this);this.b-=7},function(){var a=this.ha<<1;this.ha=a&255|a>>8;this.O=this.O&255|a&256;this.b-=4},ad,function(){var a,b=a=(this.la<<8|this.qa)+(this.T<<8|this.da);this.la=b>>8&255;this.qa=b&255;this.O=this.O&255|a>>8&256;this.b-=10},function(){this.ha=Xc(this,this.T<<8|this.da);this.b-=7},O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,
O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O,O];
function bd(a){x.call(this,"ROM",a,bd);this.s=null;this.F=a.addr;this.w=a.size;this.C=a.alias;this.D=a.file;this.H=ea(this.D);if(this.D){a=this.D;var b=fa(this.H);"json"!=b&&"hex"!=b&&(a=xa()+"/api/v1/dump?file="+this.D+"&format=bytes&decimal=true");var c=this;u(a,null,!0,function(a,b,f){cd(c,a,b,f)})}}z(bd);bd.prototype.La=function(a,b,c,d){this.A=b;this.b=c;this.B=d;dd(this)};
bd.prototype.pa=function(){if(this.na){if(this.B){var a=this.B,b=this.id,c=this.F,d=this.w,e=this.na,f=[],k;for(k in e){var h=e[k];"number"==typeof h&&(e[k]=h={o:h});var l=h.o,m=h.a;if(void 0!==l){var p=f,l=[l>>>0,k],r=ta(p,l,a.wb);0>r&&p.splice(-(r+1),0,l)}m&&(h.a=m.replace(/''/g,'"'))}a.H.push({bc:b,u:c,Xb:d,na:e,xb:f})}delete this.na}return!0};bd.prototype.oa=function(){return!0};
function cd(a,b,c,d){if(d)a.ba("Unable to load system ROM (error "+d+": "+b+")");else{kb(a.zb,b,c);if("["==c.charAt(0)||"{"==c.charAt(0))try{var e=eval("("+c+")"),f=e.bytes,k=e.data;if(f)a.s=f;else if(k)for(a.s=Array(4*k.length),d=c=0;c<k.length;c++)a.s[d++]=k[c]&255,a.s[d++]=k[c]>>8&255,a.s[d++]=k[c]>>16&255,a.s[d++]=k[c]>>24&255;else a.s=e;a.na=e.symbols;if(!a.s.length){v("Empty ROM: "+b);return}if(1==a.s.length){v(a.s[0]);return}}catch(h){a.ba("ROM data error: "+h.message);return}else for(b=c.replace(/\n/gm,
" ").replace(/ +$/,"").split(" "),a.s=Array(b.length),e=0;e<b.length;e++)a.s[e]=da(b[e],16);dd(a)}}
function dd(a){if(!rb(a))if(!a.D)G(a);else if(a.s&&a.A){if(a.s.length!=a.w)sb(a,"ROM size (0x"+n(a.s.length)+") does not match specified size ("+("0x"+n(a.w))+")");else{var b;b=a.F;if(Ab(a.A,b,a.w,Wb)){for(var c=0;c<a.s.length;c++){var d=a.A,e=b+c;d.A[(e&d.w)>>>d.P].Ua(e&d.s,a.s[c]&255,e)}b=!0}else b=!1;if(b){b=[];"number"==typeof a.C?b.push(a.C):null!=a.C&&a.C.length&&(b=a.C);for(c=0;c<b.length;c++){for(var f=a,d=b[c],e=f.A,k=f.w,h=[],l=f.F>>>e.P;0<k&&l<e.A.length;)h.push(e.A[l++]),k-=e.Z;e=f.A;
f=f.w;k=0;for(d>>>=e.P;0<f&&d<e.A.length;){l=h[k++];if(!l)break;e.A[d++]=l;f-=e.Z}}delete a.s}}G(a)}}Qa(function(){for(var a=F(document,"pc8080","rom"),b=0;b<a.length;b++){var c=a[b],d=E(c),d=new bd(d);mb(d,c)}});function ed(a){x.call(this,"RAM",a,ed);this.C=a.addr;this.w=a.size;this.s=!1}z(ed);g=ed.prototype;g.La=function(a,b,c,d){this.A=b;this.b=c;this.B=d;G(this)};g.pa=function(a,b){b||this.reset();return!0};g.oa=function(a){return a?this.save():!0};
g.reset=function(){!this.s&&this.w&&Ab(this.A,this.C,this.w,1)&&(this.s=!0,this.status(Math.floor(this.w/1024)+"Kb allocated"));this.s||v("No RAM allocated")};g.save=function(){return null};g.restore=function(){return!0};Qa(function(){for(var a=F(document,"pc8080","ram"),b=0;b<a.length;b++){var c=a[b],d=E(c),d=new ed(d);mb(d,c)}});function fd(a){x.call(this,"Keyboard",a,fd,65536);G(this)}z(fd);
Qa(function(){for(var a=F(document,"pc8080","keyboard"),b=0;b<a.length;b++){var c=a[b],d=E(c),d=new fd(d);mb(d,c)}});function gd(a){x.call(this,"Video",a,gd,262144);G(this)}z(gd);
Qa(function(){for(var a=F(document,"pc8080","video"),b=0;b<a.length;b++){var c=a[b],d=E(c),e=document.createElement("canvas");if(void 0===e||!e.getContext){c.innerHTML="<br/>Missing &lt;canvas&gt; support. Please try a newer web browser.";break}e.setAttribute("class","pcjs-canvas");e.setAttribute("width",d.screenWidth);e.setAttribute("height",d.screenHeight);e.style.backgroundColor=d.screenColor;e.style.height="auto";0<=ya().indexOf("MSIE")&&(c.onresize=function(a,b,c,d){return function(){b.style.height=
(a.clientWidth*d/c|0)+"px"}}(c,e,d.screenWidth,d.screenHeight),c.onresize());var f=+(d.aspect||Va.aspect);f&&.3<=f&&3.33>=f&&(Pa("onresize",function(a,b,c){return function(){b.style.height=(a.clientWidth/c|0)+"px"}}(c,e,f)),window.onresize());c.appendChild(e);f=document.createElement("textarea");Ja("iOS")&&(f.setAttribute("autocapitalize","off"),f.setAttribute("autocorrect","off"));c.appendChild(f);e.getContext("2d");d=new gd(d);mb(d,c)}});
function hd(a){x.call(this,"Debugger",a,hd);this.V=this.Ga=this.J=0;this.M=P();this.yb=P();this.D=-1;this.C=[];this.ia=!1;this.aa=P();this.H=[];this.ca={};this.w=this.R=this.F=[];id(this);this.ua=0;jd(this);this.Va=[];kd(this,a.messages);this.Xa=a.commands;var b=this;window?void 0===window.$&&(window.$=function(a){return mc(b,a)}):void 0===global.$&&(global.$=function(a){return mc(b,a)})}z(hd);
var ld={"?":"help/print","a [#]":"assemble","b [#]":"breakpoint",c:"clear output","d [#]":"dump memory","e [#]":"edit memory",f:"frequencies","g [#]":"go [to #]",h:"halt","i [#]":"input port #","if":"eval expression",k:"stack trace",ln:"list nearest symbol(s)",m:"messages","o [#]":"output port #",p:"step over",print:"print expression",r:"dump/set registers",reset:"reset machine","t [#]":"trace","u [#]":"unassemble",x:"execution options",v:"print version","var":"assign variable"},md="NONE ACI ADC ADD ADI ANA ANI CALL CC CM CNC CNZ CP CPE CPO CZ CMA CMC CMP CPI DAA DAD DCR DCX DI EI HLT IN INR INX JMP JC JM JNC JNZ JP JPE JPO JZ LDA LDAX LHLD LXI MOV MVI NOP ORA ORI OUT PCHL POP PUSH RAL RAR RET RC RM RNC RNZ RP RPE RPO RZ RLC RRC RST SBB SBI SHLD SPHL STA STAX STC SUB SUI XCHG XRA XRI XTHL".split(" "),
nd="B C D E H L M A F BC DE HL PSW SP PC".split(" "),od=[[45],[42,2323,32],[71,2387],[29,2323],[28,17],[22,17],[44,17,32],[63],[45,32768],[21,6419],[40,2387],[23,2323],[28,273],[22,273],[44,273,32],[64],[45,32768],[42,2579,32],[71,2643],[29,2579],[28,529],[22,529],[44,529,32],[52],[45,32768],[21,6675],[40,2643],[23,2579],[28,785],[22,785],[44,785,32],[53],[45,32768],[42,2835,32],[68,99],[29,2835],[28,1041],[22,1041],[44,1041,32],[20],[45,32768],[21,6931],[41,99],[23,2835],[28,1297],[22,1297],[44,
1297,32],[16],[45,32768],[42,3347,32],[70,97],[29,3347],[28,1553],[22,1553],[44,1553,32],[72],[45,32768],[21,7443],[39,97],[23,3347],[28,1809],[22,1809],[44,1809,32],[17],[43,17,17],[43,17,273],[43,17,529],[43,17,785],[43,17,1041],[43,17,1297],[43,17,1553],[43,17,1809],[43,273,17],[43,273,273],[43,273,529],[43,273,785],[43,273,1041],[43,273,1297],[43,273,1553],[43,273,1809],[43,529,17],[43,529,273],[43,529,529],[43,529,785],[43,529,1041],[43,529,1297],[43,529,1553],[43,529,1809],[43,785,17],[43,785,
273],[43,785,529],[43,785,785],[43,785,1041],[43,785,1297],[43,785,1553],[43,785,1809],[43,1041,17],[43,1041,273],[43,1041,529],[43,1041,785],[43,1041,1041],[43,1041,1297],[43,1041,1553],[43,1041,1809],[43,1297,17],[43,1297,273],[43,1297,529],[43,1297,785],[43,1297,1041],[43,1297,1297],[43,1297,1553],[43,1297,1809],[43,1553,17],[43,1553,273],[43,1553,529],[43,1553,785],[43,1553,1041],[43,1553,1297],[43,1553,1553],[43,1553,1809],[43,1809,17],[43,1809,273],[43,1809,529],[43,1809,785],[43,1809,1041],
[43,1809,1297],[43,1809,1553],[43,1809,1809],[3,17],[3,273],[3,529],[3,785],[3,1041],[3,1297],[3,1553],[3,1809],[2,17],[2,273],[2,529],[2,785],[2,1041],[2,1297],[2,1553],[2,1809],[73,17],[73,273],[73,529],[73,785],[73,1041],[73,1297],[73,1553],[73,1809],[66,17],[66,273],[66,529],[66,785],[66,1041],[66,1297],[66,1553],[66,1809],[5,17],[5,273],[5,529],[5,785],[5,1041],[5,1297],[5,1553],[5,1809],[76,17],[76,273],[76,529],[76,785],[76,1041],[76,1297],[76,1553],[76,1809],[46,17],[46,273],[46,529],[46,
785],[46,1041],[46,1297],[46,1553],[46,1809],[18,17],[18,273],[18,529],[18,785],[18,1041],[18,1297],[18,1553],[18,1809],[58],[50,2323],[34,35],[30,35],[11,35],[51,2323],[4,33],[65],[62],[54],[38,35],[30,32803],[15,35],[7,35],[1,33],[65],[57],[50,2579],[33,35],[48,33],[10,35],[51,2579],[74,33],[65],[55],[54,32768],[31,35],[27,33],[8,35],[7,32803],[67,33],[65],[61],[50,2835],[37,35],[78],[14,35],[51,2835],[6,33],[65],[60],[49],[36,35],[75],[13,35],[7,32803],[77,33],[65],[59],[50,3091],[35,35],[24],
[12,35],[51,3091],[47,33],[65],[56],[69],[32,35],[25],[9,35],[7,32803],[19,33],[65]],Q={cpu:1,bus:64,mem:128,port:256,timer:2048,keyboard:65536,key:131072,video:262144,fdc:524288,disk:2097152,serial:8388608,speaker:33554432,computer:67108864,log:536870912,warn:1073741824,halt:-2147483648};g=hd.prototype;
g.La=function(a,b,c,d){this.A=b;this.b=c;this.s=a;(a=jc(a,"messages"))&&kd(this,a);this.ib=od;pd(this,function(a){a:{var b=d.b.ga,c=a[0],h=a=0,l=b.length;if(c){a=T(U(d,c));if(-1===a){d.g("invalid address: "+c);break a}h=a>>>d.b.P;l=1}d.g("blockid   physical   blockaddr   used    size    type");d.g("--------  ---------  ----------  ------  ------  ----");for(var c=-1,m=0;l--;){var p=b[h];p.type==c?m++||d.g("..."):(c=p.type,m=ac[c],p&&d.g(n(p.id)+"  %"+n(h<<d.b.P)+"  %%"+n(p.u)+"  "+q(p.gb)+"  "+q(p.size)+
"  "+m),c!=Vb&&(c=-1),m=0);a+=d.b.Z;h++}}});G(this)};
g.ea=function(a,b,c){var d=this;switch(b){case "debugInput":return this.ma=this.G[b]=c,c.onkeydown=function(a){var b;if(13==a.keyCode)b=c.value,c.value="",mc(d,b,!0);else if(27==a.keyCode)c.value=b="";else if(38==a.keyCode?d.D<d.C.length-1&&(b=d.C[++d.D]):40==a.keyCode&&(0<d.D?b=d.C[--d.D]:(b="",d.D=-1)),null!=b){var k=b.length;c.value=b;c.setSelectionRange(k,k)}null!=b&&a.preventDefault&&a.preventDefault()},!0;case "debugEnter":return this.G[b]=c,La(c,function(){if(d.ma){var a=d.ma.value;d.ma.value=
"";mc(d,a,!0);return!0}return!1}),!0;case "step":return this.G[b]=c,La(c,function(a){var b=!1;qb(d,!0)||(pb(d,!0),b=d.Ta(a?1:0),pb(d,!1));return b}),!0}return!1};g.fb=function(){this.ma&&this.ma.focus()};function T(a){a=a&&a.u;null==a&&(a=-1);return a}g.ra=function(a,b){var c=255,d=T(a);-1!==d&&(c=Cb(this.A,d),b&&qd(a,b));return c};g.hb=function(a,b){var c=65535,d=T(a);if(-1!==d){var c=this.A,e=d&c.s,f=(d&c.w)>>>c.P,c=e!=c.s?c.A[f].tb(e,d):c.A[f++].eb(e,d)|c.A[f&c.L].eb(0,d+1)<<8;b&&qd(a,b)}return c};
g.ub=function(a,b,c){var d=T(a);if(-1!==d){var e=this.A;e.A[(d&e.w)>>>e.P].Ua(d&e.s,b&255,d);c&&qd(a,c);I(this.b,!0)}};g.Pb=function(a,b,c){var d=T(a);if(-1!==d){var e=this.A,f=d&e.s,k=(d&e.w)>>>e.P;f!=e.s?e.A[k].Ob(f,b&65535,d):(e.A[k++].Ua(f,b&255,d),e.A[k&e.L].Ua(0,b>>8&255,d+1));c&&qd(a,c);I(this.b,!0)}};function P(a){return{u:a||0,ka:!1}}function rd(a){return[a.u,a.ka]}function sd(a){return{u:a[0],ka:a[1]}}
function U(a,b,c){var d;c=(c?a.M:a.yb).u;if(void 0!==b){d=b=td(a,b);var e;if(d.match(/^[a-z_][a-z0-9_]*$/i))for(d=d.toUpperCase(),c=0;c<a.H.length;c++){var f=a.H[c].na[d];if(void 0!==f){d=f.o;void 0!==d&&(e=P(d));break}}if(d=e)return d;c=ud(a,b,void 0)}null!=c&&(d=P(c));return d}function vd(a,b,c){c&&(c=c.match(/(['"])(.*?)\1/))&&(b.Qb=wd(a,b.Mb=c[2]))}function qd(a,b){null!=a.u&&(a.u+=b||1)}
function xd(a,b,c){var d="";for(c=c||256;d.length<c;){var e=a.ra(b,1);if(!e||36==e||127<=e)break;d+=32<=e?String.fromCharCode(e):"."}return d}function kd(a,b){a.B=a;a.Y=a.Rb=1073741824;a.va=null;var c=wd(a,b.replace("keys","key").replace("kbd","keyboard"),!1,"|");if(c.length)for(var d in Q)0<=wa(c,d)&&(a.Y|=Q[d],a.g(d+" messages enabled"))}function pd(a,b){for(var c in Q)if(64==Q[c]){a.Va[c]=b;break}}
function yd(a,b){var c;a=a.toUpperCase();null==b?c=wa(nd,a):(c=wa(nd,a.substr(b,3)),0>c&&(c=wa(nd,a.substr(b,2))));return c}function zd(a,b){var c=0,d=Ad(a,b);if(void 0!==d)switch(b){case 7:case 0:case 1:case 2:case 3:case 4:case 5:case 8:c=2;break;case 9:case 10:case 11:case 12:case 13:case 14:c=4}return c?n(d,c):"??"}
function Ad(a,b){var c;if(0<=b){var d=a.b;switch(b){case 7:c=d.ha;break;case 8:c=Wc(d)&255;break;case 0:c=d.T;break;case 1:c=d.da;break;case 9:c=d.T<<8|d.da;break;case 2:c=d.ta;break;case 3:c=d.Ca;break;case 10:c=d.ta<<8|d.Ca;break;case 4:c=d.la;break;case 5:c=d.qa;break;case 11:c=d.la<<8|d.qa;break;case 12:c=d.ha<<8|Wc(d)&255;break;case 13:c=d.Ea;break;case 14:c=d.N}}return c}
function Bd(a,b){b=td(a,b);for(var c=0,d,e;0<=(c=b.indexOf("@",c));)e=yd(b,c+1),0<=e&&(b=b.substr(0,c)+zd(a,e)+b.substr(c+1+nd[e].length)),c++;for(c=0;0<=(c=b.indexOf("#",c));)e=b.substr(c+1,2),d=da(e,16),null!=d&&32<=d&&128>d?(d=e+" '"+String.fromCharCode(d)+"'",b=b.replace("#"+e,d),c+=d.length):c++;for(c=0;0<=(c=b.indexOf("$",c));)e=b.substr(c+1,9),(d=U(a,e))?(d=e+' "'+xd(a,d)+'"',b=b.replace("$"+e,d),c+=d.length):c++;for(c=0;0<=(c=b.indexOf("^",c));)e=b.substr(c+1,9),(d=U(a,e))?(qd(d),d=e+' "'+
xd(a,d,11)+'"',b=b.replace("^"+e,d),c+=d.length):c++;return b}g.message=function(a,b){b&&(a+=" at "+n(P(this.b.N).u,4));if(!this.va||a!=this.va)if(this.va=a,this.Y&-2147483648&&(this.U(),a+=" (cpu halted)"),this.g(a),this.b){var c=this.b;c.i.Qa=0;c.D-=c.b;c.b=0;I(c)}};function Cd(a,b,c,d){a.message(b.Wa+"."+(null!=d?"outPort":"inPort")+"("+q(c)+",unknown"+(null!=d?",0x"+n(d,2):"")+")")}
function jd(a){var b;if(Zc(a)){if(!a.L||!a.L.length){a.L=Array(1E3);for(b=0;b<a.L.length;b++)a.L[b]=P();a.ja=0;a.g("instruction history buffer allocated")}if(!a.I||!a.I.length)for(a.I=Array(256),b=0;b<a.I.length;b++)a.I[b]=[b,0]}else a.L&&a.L.length&&a.g("instruction history buffer freed"),a.ja=0,a.L=[],a.I=[]}g.Fa=function(a){if(!Dd(this))return!1;this.b.Fa(a);return!0};
g.Ta=function(a,b,c){if(!Dd(this))return!1;this.J=0;a||Zc(this)&&$c(this,this.b.N,0);try{var d=this.b.Ta(a);0<d&&(this.J+=d,Qc(this.b,d,!0),oc(this.b,d),this.V++)}catch(e){"number"!=typeof e&&(this.J=0,sb(this.b,e.stack||e.message))}!1!==c&&I(this.b);this.fa(b||!1);return 0<this.J};g.U=function(a){this.b&&this.b.U(a)};g.fa=function(a){void 0===a&&(a=!0);this.M=P(this.b.N);a&&1!=this.S?Ed(this):Fd(this)};
function Dd(a){var b;if(b=a.b&&rb(a.b))b=a.b,b.j.W?b=!0:(b.g(b.toString()+" not powered"),b=!1);b&&!qb(a.b)?(a=a.b,a.j.Ja?(a.g(a.toString()+" error"),a=!0):a=!1,a=!a):a=!1;return a}g.pa=function(a,b){return!b&&(this.reset(!0),a&&this.restore&&!this.restore(a))?!1:!0};g.oa=function(a,b){b&&this.g(a?"suspending":"shutting down");return a?this.save():!0};g.reset=function(a){jd(this);this.V=this.Ga=0;this.va=null;this.J=0;this.M=P(this.b.N);this.j.X=!1;Gd(this);a||this.fa()};
g.save=function(){var a=new J(this);M(a,0,rd(this.M));M(a,1,rd(this.aa));M(a,2,[this.C,this.ia,this.Y]);M(a,3,this.H);return a.data()};g.restore=function(a){var b=0;void 0!==a[2]&&(this.M=sd(a[b++]),this.aa=sd(a[b++]),this.C=a[b][0],"string"==typeof this.C&&(this.C=[this.C]),this.ia=a[b][1],this.Y|=a[b][2]);a[3]&&(this.H=a[3]);return!0};g.start=function(a,b){this.S||this.g("running");this.j.X=!0;this.Sb=a;this.Vb=b};
g.stop=function(a,b){if(this.j.X){this.j.X=!1;this.J=b-this.Vb;if(!this.S){var c="stopped";if(this.J){var d=a-this.Sb,e=0<d?Math.round(1E3*this.J/d):0,c=c+" (";Zc(this)&&(c+=this.V+" opcodes, ",this.Ga-=this.V,this.V=0);c+=this.J+" cycles, "+d+" ms, "+e+" hz)"}else ob(this,-2147483648)&&(c+=" (use the 't' command to execute blocked faults)");this.g(c)}this.fa(!0);this.fb();Gd(this,this.b.N)}};function Zc(a){return 1<a.w.length||!!a.ua}
function $c(a,b,c){var d=a.b;if(0<c&&(a.ua&&!--a.ua||ec(a,b,1,a.w)))return!0;0<=c&&a.I.length&&(a.V++,b=Cb(a.A,b),null!=b&&(a.I[b][1]++,b=a.L[a.ja],b.u=d.N,b.ka=!1,++a.ja==a.L.length&&(a.ja=0)));return!1}function Hd(a,b,c){a.g("break on input from port "+q(b)+": "+n(c));a.U(!0)}function Id(a,b,c){a.g("break on output to port "+q(b)+": "+n(c));a.U(!0)}
function id(a){var b,c;a.w=["bp"];if(void 0!==a.R)for(b=1;b<a.R.length;b++){c=a.R[b];var d=a.b;fc(d.ga[T(c)>>>d.P],!1)}a.R=["br"];if(void 0!==a.F)for(b=1;b<a.F.length;b++)c=a.F[b],d=a.b,fc(d.ga[T(c)>>>d.P],!0);a.F=["bw"];a.Ab=0}g.wa=function(a,b,c){var d=!0;c||Jd(this,a,b,!1,!0);if(a!=this.w){var e=T(b);if(-1===e)this.g("invalid address: "+n(b.u,4)),d=!1;else{var f=this.b;f.ga[e>>>f.P].wa(e&f.I,a==this.F)}}d&&(a.push(b),c?b.ka=!0:(Kd(this,a,a.length-1,"set"),jd(this)));return d};
function Jd(a,b,c,d,e){var f=!1;c=T(c);for(var k=1;k<b.length;k++){var h=b[k];if(c==T(h)&&(!d||h.ka)){f=!0;h.ka||e||Kd(a,b,k,"cleared");b.splice(k,1);b!=a.w&&(d=a.b,fc(d.ga[c>>>d.P],b==a.F));h.ka||jd(a);break}}return f}function Ld(a,b){for(var c=1;c<b.length;c++)Kd(a,b,c);return b.length-1}function Kd(a,b,c,d){c=b[c];a.g(b[0]+" "+n(c.u,4)+(d?" "+d:c.Mb?' "'+c.Mb+'"':""))}
function Gd(a,b){if(void 0!==b)ec(a,b,1,a.w,!0),a.S=0;else for(var c=1;c<a.w.length;c++){var d=a.w[c];if(d.ka){if(!Jd(a,a.w,d,!0))break;c=0}}}
function ec(a,b,c,d,e){var f=!1;if(!a.Ab++)for(var k=1;!f&&k<d.length;k++){var h=d[k];if(!e||h.ka)for(var l=T(h),m=0;m<c;m++)if(b+m==l){var p,f=!0;h.ka&&(Jd(a,d,h,!0),e=!0);if(p=h.Qb){for(var f=!1,r=0;r<p.length;r++)if(!Md(a,p[r],!0)){if(p[r].indexOf("if")){f=!0;break}for(var t=r+1;t<p.length&&p[t].indexOf("else");t++)r++;if(t==p.length){f=!0;break}}a.b.j.X||(f=!0)}if(f){e||Kd(a,d,k,"hit");break}}}a.Ab--;return f}
function Nd(a,b,c,d){for(var e=P(b.u),f=a.ra(b,1),k=a.ib[f],f="",h=null,l=md[k[0]],m=k.length-1,p=1;p<=m;p++){var r="",t=k[p];if(void 0!==t){var K=t&15;if(0==K){if(null==h)continue;K=h}h=K;K=t&240;if(32==K){var r=a,K=b,B=" ";switch(t&15){case 1:t&12288&&(B=n(r.ra(K,1),2));break;case 2:B=n(r.ra(K,1)<<24>>24,4);break;case 3:B=n(r.hb(K,2),4);break;default:B="imm("+q(t)+")"}r=B}else 16==K&&(r=nd[(t&3840)>>8]);if(!r||!r.length){f="INVALID";break}0<f.length&&(f+=",");f+=r||"???"}}k="";h=n(e.u,4)+" ";if(-1!==
e.u&&-1!==b.u){do if(k+=n(a.ra(e,1),2),null==e.u)break;while(e.u!=b.u)}h+=ra(k,11);h+=ra(l,7);f&&(h+=" "+f);c&&(h=ra(h,40)+";"+c,h=a.b.j.Ia?h+("cycles="+pc(a.b).toString()+" cs="+n(a.b.i.Ya)):h+(null!=d?"="+d.toString():""));return h}
function Od(a,b){var c;switch(b){case "I":c=a.b.Da&512;break;case "S":c=a.b.K&128?128:0;break;case "Z":c=a.b.O&255?0:64;break;case "A":c=a.b;c=(c.K^c.C)&16?16:0;break;case "P":c=ub[a.b.K&255]?4:0;break;case "C":c=a.b.O&256?1:0;break;default:c=0}return b+(c?"1":"0")+" "}function V(a,b){return nd[b]+"="+zd(a,b)+" "}var Pd={"||":0,"&&":1,"|":2,"^":3,"&":4,"!=":5,"==":5,">=":6,">":6,"<=":6,"<":6,">>>":7,">>":7,"<<":7,"-":8,"+":8,"%":9,"/":9,"*":9};
function Qd(a,b,c){for(c=c||-1;c--&&b.length;){var d=b.pop();if(2>a.length)return!1;var e=a.pop(),f=a.pop();switch(d){case "*":d=f*e;break;case "/":if(!e)return!1;d=f/e;break;case "%":if(!e)return!1;d=f%e;break;case "+":d=f+e;break;case "-":d=f-e;break;case "<<":d=f<<e;break;case ">>":d=f>>e;break;case ">>>":d=f>>>e;break;case "<":d=f<e?1:0;break;case "<=":d=f<=e?1:0;break;case ">":d=f>e?1:0;break;case ">=":d=f>=e?1:0;break;case "==":d=f==e?1:0;break;case "!=":d=f!=e?1:0;break;case "&":d=f&e;break;
case "^":d=f^e;break;case "|":d=f|e;break;case "&&":d=f&&e?1:0;break;case "||":d=f||e?1:0;break;default:return!1}a.push(d|0)}return!0}
function ud(a,b,c){var d;if(b){b=td(a,b);for(var e=0,f=!1,k=b,h=[],l=[],m=b.split(/(\|\||&&|\||^|&|!=|==|>=|>>>|>>|>|<=|<<|<|-|\+|%|\/|\*)/);e<m.length;){var p=m[e++],r=p.length,p=sa(p);if(!p){f=!0;break}p=Rd(a,p,null,!1===c);if(void 0===p){f=!0;c=!1;break}h.push(p);if(e==m.length)break;var p=m[e++],t=p.length;l.length&&Pd[p]<Pd[l[l.length-1]]&&Qd(h,l,1);l.push(p);b=b.substr(r+t)}Qd(h,l)&&1==h.length||(f=!0);f?c&&a.g("error parsing '"+k+"' at character "+(k.length-b.length)):(d=h.pop(),c&&re(a,null,
d))}return d}function td(a,b){for(var c;(c=b.match(/\{(.*?)}/))&&!(0<=c[1].indexOf("{"));){var d=ud(a,c[1]);b=b.replace("{"+c[1]+"}",null!=d?n(d):"undefined")}for(;(c=b.match(/\[(.*?)]/))&&!(0<=c[1].indexOf("["));)d=U(a,c[1]),b=b.replace("["+c[1]+"]",d?n(a.hb(d,0),4):"undefined");for(c=b;d=c.match(/\$([a-z]+)/i);){var e=null;switch(d[1].toLowerCase()){case "ops":e=a.V-a.Ga}if(null==e)break;c=c.replace(d[0],e.toString())}return c}
function Rd(a,b,c,d){var e;void 0!==b?(e=yd(b),0<=e?e=Ad(a,e):(e=a.ca[b],void 0===e&&(e=da(b))),void 0!==e||d||a.g("invalid "+(c?c:"value")+": "+b)):d||a.g("missing "+(c||"value"));return e}
function re(a,b,c){var d,e=!1;if(void 0!==c){e=!0;d=c;var f,k="";if(!f||4<f)f=4;for(var h=0;h<f;h++){k&&(k=","+k);var l=d&255,m=8,p="";void 0===m?m=32:32<m&&(m=32);if(null==l||isNaN(l))for(;0<m--;)p="?"+p;else for(;0<m--;)p=(l&1?"1":"0")+p,l>>=1;k=p+"b"+k;d>>=8}d="0x"+n(c)+" "+c+". ("+k+")"}a.g((null!=b?b+": ":"")+d);return e}function se(a,b){if(b)return re(a,b,a.ca[b]);var c=0;for(b in a.ca)re(a,b,a.ca[b]),c++;return 0<c}hd.prototype.wb=function(a,b){return a[0]>b[0]?1:a[0]<b[0]?-1:0};
function te(a,b,c){var d=[],e=T(b)>>>0;for(b=0;b<a.H.length;b++){var f=a.H[b],k=f.u>>>0,h=f.Xb;if(e>=k&&e<k+h){e=ta(f.xb,[e-k],a.wb);0<=e?ue(a,b,e,d):c&&(e=~e,ue(a,b,e-1,d),ue(a,b,e,d));break}}return d}function ue(a,b,c,d){var e={},f=a.H[b].xb,k=0,h=null;0<=c&&c<f.length&&(k=f[c][0],h=f[c][1]);h&&(e=a.H[b].na[h],h="."==h.charAt(0)?null:e.l||h);d.push(h);d.push(k);d.push(e.a);d.push(e.c)}
function ve(a,b){if("?"==b)a.g("frequency commands:"),a.g("\tclear\tclear all frequency counts");else{var c,d=0;if(a.I)if("clear"==b){for(c=0;c<a.I.length;c++)a.I[c]=[c,0];a.g("frequency data cleared");d++}else if(void 0!==b)a.g("unknown frequency command: "+b),d++;else{var e=a.I.slice();e.sort(function(a,b){return b[1]-a[1]});for(c=0;c<e.length;c++){var f=e[c][0],k=e[c][1];k&&(a.g((md[a.ib[f][0]]+"  ").substr(0,5)+" ("+("0x"+n(f,2))+"): "+k+" times"),d++)}}d||a.g("no frequency data available")}}
function we(a,b){var c=b.match(/^\s*([A-Z_]?[A-Z0-9_]*)\s*(=?)\s*(.*)$/i);if(c){if(!c[1])return se(a)||a.g("no variables"),!0;if(!c[2])return se(a,c[1]);if(!c[3])return delete a.ca[c[1]],!0;var d=ud(a,c[3]);return void 0!==d?(a.ca[c[1]]=d,!0):!1}a.g("invalid assignment:"+b);return!1}
function xe(a,b,c){var d=null;if(b=U(a,b,!0)){var e=te(a,b,!0);if(e.length){var f,k;e[0]&&(k="",(f=b.u-e[1])&&(k=" + "+q(f)),f=e[0]+" ("+n(e[1],4)+")"+k,c&&a.g(f),d=f);4<e.length&&e[4]&&(k="",(f=e[5]-b.u)&&(k=" - "+q(f)),f=e[4]+" ("+n(e[5],4)+")"+k,c&&a.g(f),d||(d=f))}else c&&a.g("no symbols")}return d}
function Ed(a,b){var c;if(b&&"?"==b[1])a.g("register commands:"),a.g("\tr\tdump registers"),a.g("\trx [#]\tset flag or register x to [#]");else{null==c&&(c=!0);if(null!=b&&1<b.length){var d=b[1],e=null,f=d.indexOf("=");if(0<f)e=d.substr(f+1),d=d.substr(0,f);else if(2<b.length)e=b[2];else{a.g("missing value for "+b[1]);return}var f=!1,k=ud(a,e);if(void 0!==k){var f=!0,h=d.toUpperCase();"E"==h.charAt(0)&&(h=null);switch(h){case "A":a.b.ha=k&255;break;case "B":a.b.T=k&255;break;case "BC":a.b.T=k<<8&
255;case "C":a.b.da=k&255;break;case "D":a.b.ta=k&255;break;case "DE":a.b.ta=k<<8&255;case "E":a.b.Ca=k&255;break;case "H":a.b.la=k&255;break;case "HL":a.b.la=k<<8&255;case "L":a.b.qa=k&255;break;case "SP":a.b.Ea=k&65535;break;case "PC":a.b.N=k&65535;a.M=P(a.b.N);break;case "PS":Vc(a.b,k);break;case "C":k?(d=a.b,d.O|=256):(d=a.b,d.O&=255);break;case "P":k?(d=a.b,ub[d.K&255]||(d.K^=1)):(d=a.b,ub[d.K&255]&&(d.K^=1));break;case "A":k?(d=a.b,d.C=~d.K&16|d.C&-17):(d=a.b,d.C=d.K&16|d.C&-17);break;case "Z":k?
(d=a.b,d.O&=-256):(d=a.b,d.O|=255);break;case "S":k?(d=a.b,d.K&128||(d.K^=192)):(d=a.b,d.K&128&&(d.K^=192));break;case "I":k?(d=a.b,d.Da|=512):(d=a.b,d.Da&=-513);break;default:a.g("unknown register: "+d);return}}if(!f){a.g("invalid value: "+e);return}I(a.b);a.g("updated registers:")}a.g(V(a,7)+V(a,8)+V(a,0)+V(a,1)+V(a,2)+V(a,3)+V(a,4)+V(a,5)+V(a,13)+Od(a,"I")+Od(a,"S")+Od(a,"Z")+Od(a,"A")+Od(a,"P")+Od(a,"C"));c&&(a.M=P(a.b.N),Fd(a,n(a.M.u,4)))}}
function ye(a,b){b=sa(b);var c=b.match(/^(['"])(.*?)\1$/);c?a.g(Bd(a,c[2])):ud(a,b,!0)}function ze(a,b,c){var d="t"!=b;c=Rd(a,c,null,!0)||1;var e=1==c?0:1;"tc"==b&&(e=c,c=1);Ka(c,function(){return pb(a,!0)&&a.Ta(e,d,!1)},function(){I(a.b);pb(a,!1)})}
function Fd(a,b,c,d){if(b=U(a,b,!0)){void 0===d&&(d=1);var e=256;if(void 0!==c){d=U(a,c,!0);if(!d||d.u<b.u)return;e=d.u-b.u;if(256<e){a.g("range too large");return}d=-1}c=0;for(var f;0<e&&d--;){f=qb(a,!1)||a.S?a.J:null;var k=null!=f?"cycles":null,h=te(a,b),l=b.u;if(h[0]&&d&&(!c&&d||0>h[0].indexOf("+"))){var m=h[0]+":";h[2]&&(m+=" "+h[2]);a.g(m)}h[3]&&(k=h[3],f=null);f=Nd(a,b,k,f);a.g(f);a.M=b;e-=b.u-l;c++}}}
function wd(a,b,c,d){if(c)if(b){0>a.D&&a.C.length&&(a.D=0);if(0>a.D||b!=a.C[a.D])a.C.splice(0,0,b),a.D=0;a.D--}else b=a.C[a.D+1];a=[];if(b){b=b.toLowerCase().replace(/""/g,"'");c=0;var e=null;d=d||";";for(var f=0;f<=b.length;f++){var k=b.charAt(f);if('"'==k||"'"==k)e?k==e&&(e=null):e=k;else if(k==d&&!e||!k)a.push(sa(b.substring(c,f))),c=f+1}}return a}
function Md(a,b,c){var d=!0;try{b.length&&"end"!=b?c||a.g(">> "+b):(a.ia&&(a.g("ended assemble at "+n(a.aa.u,4)),a.M=a.aa,a.ia=!1),b="");var e=b.charAt(0);if('"'==e||"'"==e)return!0;a.va=null;if(rb(a)&&0<b.length){a.ia&&(b="a "+n(a.aa.u,4)+" "+b);var f=b.replace(/ +/g," ").split(" ");if(f&&f.length)for(var k=f[0],h=k.charAt(0),l=1;l<k.length;l++){var m=k.charAt(l);if("?"==h||"r"==h||"a">m||"z"<m){f[0]=k.substr(l);f.unshift(k.substr(0,l));break}}switch(f[0].charAt(0)){case "a":var p=U(a,f[1],!0);if(p)if(a.aa=
p,void 0===f[2])a.g("begin assemble at "+n(p.u,4)),a.ia=!0,I(a.b);else{var r;a.g("not supported yet");r=[];if(r.length){for(var t=0;t<r.length;t++)a.ub(p,r[t],1);a.g(Nd(a,a.aa))}}break;case "b":a:{var K=f[0],B=f[1],Ue=b;if("?"==B)a.g("breakpoint commands:"),a.g("\tbi [p]\ttoggle break on input port [p]"),a.g("\tbo [p]\ttoggle break on output port [p]"),a.g("\tbp [a]\tset exec breakpoint at addr [a]"),a.g("\tbr [a]\tset read breakpoint at addr [a]"),a.g("\tbw [a]\tset write breakpoint at addr [a]"),
a.g("\tbc [a]\tclear breakpoint at addr [a]"),a.g("\tbl\tlist all breakpoints"),a.g("\tbn [n]\tbreak after [n] instruction(s)");else{var X=K.charAt(1);if("l"==X){var Ba=0,Ba=Ba+Ld(a,a.w),Ba=Ba+Ld(a,a.R);(Ba+=Ld(a,a.F))||a.g("no breakpoints")}else if("n"==X)a.ua=Rd(a,B),a.g("break after "+a.ua+" instruction(s)");else if(void 0===B)a.g("missing breakpoint address");else{var A=P();if("*"!=B&&(A=U(a,B,!0),!A))break a;B=q(A.u);"c"==X?null==A.u?(id(a),a.g("all breakpoints cleared")):Jd(a,a.w,A)||Jd(a,a.R,
A)||Jd(a,a.F,A)||a.g("breakpoint missing: "+n(A.u,4)):"i"==X?a.g("breakpoint "+(Db(a.A,A.u)?"enabled":"cleared")+": port "+B+" (input)"):"o"==X?a.g("breakpoint "+(Qb(a.A,A.u)?"enabled":"cleared")+": port "+B+" (output)"):null!=A.u&&(vd(a,A,Ue),"p"==X?a.wa(a.w,A):"r"==X?a.wa(a.R,A):"w"==X?a.wa(a.F,A):a.g("unknown breakpoint command: "+X))}}}break;case "c":a.xa&&(a.xa.value="");break;case "d":a:{var Ca,Da=f[0],Y=f[1],na=f[2],Ve=f[3];if("?"==Y){var Z="";for(Ca in Q)a.Va[Ca]&&(Z&&(Z+=","),Z+=Ca);Z+=",state,symbols";
a.g("dump memory commands:");a.g("\tdb [a] [#]    dump # bytes at address a");a.g("\tdw [a] [#]    dump # words at address a");a.g("\tdd [a] [#]    dump # dwords at address a");a.g("\tdh [#] [#]    dump # instructions from history");Z.length&&a.g("dump extension commands:\n\t"+Z)}else if("state"==Y){var Sd=Ae(a.s,!0);"console"==na?console.log(Sd):(a.xa&&(a.xa.value=""),a.g(Sd))}else if("symbols"==Y)for(var rc=0;rc<a.H.length;rc++){var sc=a.H[rc],Fa;for(Fa in sc.na)if("."!=Fa.charAt(0)){var Td=sc.na[Fa].o;
if(void 0!==Td){var Ud=sc.na[Fa].l;Ud&&(Fa=Ud);a.g(n(Td,4)+" "+Fa)}}}else{if("d"==Da){for(Ca in Q)if(f[1]==Ca){var Vd=a.Va[Ca];Vd?(f.shift(),f.shift(),Vd(f)):a.g("no dump registered for "+Y);break a}Y||(Da=a.Wb||"db")}else a.Wb=Da;if("dh"==Da){var Wd=Y,Xd=na,Yd="",Zd=0,D=a.ja,aa=a.L;if(aa.length){var L=+Wd||a.Bb,Ga=+Xd||10;isNaN(L)?L=Ga:Yd="more ";L>aa.length&&(a.g("note: only "+aa.length+" available"),L=aa.length);D-=L;0>D&&(null==aa[aa.length-1].u?(L=D+L,D=0):D+=aa.length);var tc=[];"call"==Xd&&
(Ga=1E5,tc=["CALL"]);for(void 0!==Wd&&a.g(L+" instructions earlier:");0<Ga&&D!=a.ja;){var $d=aa[D++];if(null==$d.u)break;var Za=P($d.u),We=L--,ae=Nd(a,Za,"history",We);(!tc.length||0<=ae.indexOf(tc[0]))&&a.g(ae);Za.nb&&(D+=Za.nb,Ga-=Za.nb,L-=Za.nb);D>=aa.length&&(D=0);a.Bb=L;Zd++;Ga--}}Zd||(a.g("no "+Yd+"history available"),a.Bb=void 0)}else{var Eb=U(a,Y);if(Eb){var Fb=0;na&&("l"==na.charAt(0)&&(na=na.substr(1)||Ve),Fb=Rd(a,na)>>>0,65536<Fb&&(Fb=65536));for(var oa="",Xe=(Fb||128)+15>>4||1,uc="dd"==
Da?4:"dw"==Da?2:1,be=0;be<Xe;be++){for(var Gb=0,vc=0,$a="",wc="",Y=n(Eb.u,4),xc=0;16>xc;xc++){var Hb=a.ra(Eb,1),Gb=Gb|Hb<<(vc++<<3);vc==uc&&($a+=n(Gb,2*uc),$a+=1==uc?7==xc?"-":" ":"  ",Gb=vc=0);wc+=32<=Hb&&128>Hb?String.fromCharCode(Hb):"."}oa&&(oa+="\n");oa+=Y+"  "+$a+" "+wc}oa&&a.g(oa);a.yb=Eb}}}}break;case "e":if("else"==f[0])break;var Ib=1,ce=255,de=a.ra,ee=a.ub;"ew"==f[0]&&(Ib=2,ce=65535,de=a.hb,ee=a.Pb);var fe=Ib<<1,ge=f[1];if(null==ge)a.g("edit memory commands:"),a.g("\teb [a] [...]  edit bytes at address a"),
a.g("\tew [a] [...]  edit words at address a");else{var Jb=U(a,ge);if(Jb)for(var Kb=2;Kb<f.length;Kb++){var ab=ud(a,f[Kb]);if(void 0===ab){a.g("unrecognized value: "+f[Kb]);break}ab&~ce&&a.g("warning: "+n(ab)+" exceeds "+Ib+"-byte value");var Ye=de.call(a,Jb);a.g("changing "+n(Jb.u,4)+" from 0x"+n(Ye,fe)+" to 0x"+n(ab,fe));ee.call(a,Jb,ab,Ib)}}break;case "f":ve(a,f[1]);break;case "g":a:{var he=f[1],Ze=b;if(void 0!==he){var yc=U(a,he,!0);if(!yc)break a;vd(a,yc,Ze);a.wa(a.w,yc,!0)}a.Fa(!0)||c||a.g("cpu busy or unavailable, run command ignored")}break;
case "h":var zc;a.j.X?(zc="halting",a.U()):zc="already halted";c||a.g(zc);break;case "i":if("if"==f[0]){var Ac;var bb=b.substr(2),bb=sa(bb);ud(a,bb)?(c||a.g("true: "+bb),Ac=!0):(c||a.g("false: "+bb),Ac=!1);Ac||(d=!1);break}var Bc=f[1];if(Bc&&"?"!=Bc){var Cc=Rd(a,Bc);if(void 0!==Cc){for(var R=a.A,ga=Cc,Dc=1,Ec=0,Fc=0;0<Dc;){var Lb=R.C[ga],cb=R.S[ga]||1,Gc=1==cb?255:2==cb?65535:-1,ha=Gc;void 0!==Lb?(Lb[0]&&(ha=Lb[0](ga,void 0),void 0===ha?ha=Gc:ha&=Gc),R.B&&R.F!=Lb[1]&&Hd(R.B,ga,ha)):R.B&&(Cd(R.B,R,
ga,null),R.F&&Hd(R.B,ga,ha));Ec|=ha<<Fc;Fc+=cb<<3;ga+=cb;Dc-=cb}a.g(q(Cc)+": "+("0x"+n(Ec,2)))}}else a.g("input commands:"),a.g("\ti [p]\tread port [p]"),a.g("warning: port accesses can affect hardware state");break;case "k":var $e=f[0];if("?"==f[1])a.g("stack trace commands:"),a.g("\tk\tshow frame addresses"),a.g("\tks\tshow symbol information");else{var Hc=0,ie=P(),db=P(a.b.Ea);for(a.g("stack trace for "+n(db.u,4));10>Hc;){for(var pa=null,af=256;65536>db.u>>>0;){ie.u=a.hb(db,2);if(null==db.u||!af--)break;
for(var bf=a,Mb=ie,je=null,eb=Mb.u,ke=eb,Ic=1;6>=Ic&&eb;Ic++){if(2<Ic){Mb.u=eb;var Nb=Nd(bf,Mb);if(0<Nb.indexOf("CALL")){var le=Nb.indexOf(" ");if(eb+(Nb.indexOf(" ",le+1)-le-1)/2==ke){je=Nb;break}}}eb--}Mb.u=ke;if(pa=je)break}if(!pa||null==pa)break;var me=null;if("ks"==$e){var ne=pa.match(/[0-9A-F]+$/);ne&&(me=xe(a,ne[0]))}pa=ra(pa,50)+"  ;"+(me||"stack="+n(db.u,4));a.g(pa);Hc++}Hc||a.g("no return addresses found")}break;case "l":if("ln"==f[0]){xe(a,f[1],!0);break}break;case "m":a:{var ba,ca=null,
w=f[1];"?"==w&&(w=void 0);if(void 0!==w){var qa=0;if("all"==w)qa=1610481663,w=null;else if("on"==w)ca=!0,w=null;else if("off"==w)ca=!1,w=null;else{"keys"==w&&(w="key");"kbd"==w&&(w="keyboard");for(ba in Q)if(w==ba){qa=Q[ba];ca=!!(a.Y&qa);break}if(!qa){a.g("unknown message category: "+w);break a}}qa&&("on"==f[2]?(a.Y|=qa,ca=!0):"off"==f[2]&&(a.Y&=~qa,ca=!1))}var cf=0,ia="";for(ba in Q)if(!w||w==ba){var df=!!(a.Y&Q[ba]);if(null===ca||ca==df)ia&&(ia+=","),++cf%10||(ia+="\n\t"),"key"==ba&&(ba="keys"),
ia+=ba}void 0===w&&a.g("message commands:\n\tm [category] [on|off]\tturn categories on/off");a.g((null!==ca?ca?"messages on:  ":"messages off: ":"message categories:\n\t")+(ia||"none"));jd(a)}break;case "o":var Jc=f[1],ef=f[2];if(Jc&&"?"!=Jc){var Kc=Rd(a,Jc,"port #"),Lc=Rd(a,ef);if(void 0!==Kc&&void 0!==Lc){for(var S=a.A,ja=Kc,oe=Lc,Mc=1,Nc=0;0<Mc;){var Ob=S.D[ja],fb=S.V[ja]||1,ff=1==fb?255:2==fb?65535:-1,Pb=(oe>>>=Nc)&ff;if(void 0!==Ob){if(Ob[0])Ob[0](ja,Pb,void 0);S.B&&S.H!=Ob[1]&&Id(S.B,ja,Pb)}else S.B&&
(Cd(S.B,S,ja,Pb),S.H&&Id(S.B,ja,Pb));Nc+=fb<<3;ja+=fb;Mc-=fb}a.g(q(Kc)+": "+("0x"+n(Lc,2)))}}else a.g("output commands:"),a.g("\to [p] [b]\twrite byte [b] to port [p]"),a.g("warning: port accesses can affect hardware state");break;case "p":if("print"==f[0]){ye(a,b.substr(5));break}var pe="pr"==f[0]?1:0,gf=1+pe;if(a.S)a.g("step in progress");else{var Oc=P(a.b.N);switch(a.ra(Oc)){case 205:a.S=gf,qd(Oc,3)}a.S?(a.wa(a.w,Oc,!0),a.Fa()||(a.s&&a.s.fb(),a.S=0)):ze(a,pe?"tr":"t")}break;case "r":if("reset"==
b){a.s&&a.s.reset();break}Ed(a,f);break;case "t":ze(a,f[0],f[1]);break;case "u":Fd(a,f[1],f[2],8);break;case "v":if("var"==f[0]){we(a,b.substr(3))||(d=!1);break}a.g("PC8080 version 1.21.7 ("+a.b.Gb+",RELEASE"+(tb?",TYPEDARRAYS":",LONGARRAYS")+")");a.g(ya());break;case "x":a:if(f[1]&&"?"!=f[1])switch(f[1]){case "cs":var gb;void 0!==f[3]&&(gb=+f[3]);switch(f[2]){case "int":a.b.i.Na=gb;break;case "start":a.b.i.Za=gb;break;case "stop":a.b.i.Pa=gb;break;default:a.g("unknown cs option");break a}void 0!==
gb&&lc(a.b);a.g("checksums "+(a.b.j.Ia?"enabled":"disabled"));break;case "sp":void 0!==f[2]&&(qc(a.b,+f[2])||a.g("warning: using 1x multiplier, previous target not reached"));a.g("target speed: "+(a.b.i.za.toFixed(2)+"Mhz")+" ("+a.b.i.Ba+"x)");break;default:a.g("unknown option: "+f[1])}else a.g("execution options:"),a.g("\tcs int #\tset checksum cycle interval to #"),a.g("\tcs start #\tset checksum cycle start count to #"),a.g("\tcs stop #\tset checksum cycle stop count to #"),a.g("\tsp #\t\tset speed multiplier to #");
break;case "?":if(f[1]){ye(a,b.substr(1));break}var hb="commands:",Pc;for(Pc in ld)hb+="\n"+ra(Pc,7)+ld[Pc];Zc(a)||(hb+="\nnote: frequency/history disabled if no exec breakpoints");a.g(hb);break;default:a.g("unknown command: "+b),d=!1}}}catch(qe){a.g("debugger error: "+(qe.stack||qe.message)),d=!1}return d}function mc(a,b,c){b=wd(a,b,c);for(var d in b)if(!Md(a,b[d]))return!1;return!0}Qa(function(){for(var a=F(document,"pc8080","debugger"),b=0;b<a.length;b++){var c=a[b],d=E(c),d=new hd(d);mb(d,c)}});
function J(a,b,c){this.id=a.id;this.key=Be(a,b,c);this.B=a.B;Ce(this,a.Kb)}function Be(a,b,c){a=a.id;if(b){var d=b.indexOf(".");0<d&&(a+=".v"+b.substr(0,d))}c&&(a+="."+c);return a}
J.prototype={constructor:J,value:function(){return this[this.id]},data:function(){return this[this.id]},toString:function(){var a=this[this.id];return"string"==typeof a?a:JSON.stringify(a)},clear:function(a){Ce(this);var b=[];try{for(var c=0,d=window.localStorage.length;c<d;c++)b.push(window.localStorage.key(c))}catch(e){}for(c=0;c<b.length;c++)if((d=b[c])&&(a||d.substr(0,this.key.length)==this.key)){try{window.localStorage.removeItem(d)}catch(e){}b.splice(c,1);c=0}}};
function Ce(a,b){a[a.id]={};b&&M(a,"parms",b);a.b=!1}function De(a){var b=!0;if(Ea()){var c=JSON.stringify(a[a.id]);Ia(a.key,c)||(v("Unable to store "+c.length+" bytes in browser local storage"),b=!1)}return b}function Ee(a){var b=!0;try{a[a.id]=JSON.parse(a[a.id])}catch(c){v(c.message||c),b=!1}return b}function Fe(a,b){return b?(a[a.id]=b,a.b=!0):a.b?!0:Ea()&&(b=Ha(a.key))?(a[a.id]=b,a.b=!0):!1}function Ge(a,b){return a[a.id][b]||null}function M(a,b,c){try{a[a.id][b]=c}catch(d){}}
function He(a,b,c){x.call(this,"Computer",a,He,67108864);this.j.W=!1;Ie(this,b);this.R=jc(this,"autoPower",a);this.C=0;this.ia=a.busWidth||a.buswidth;this.s=Je;this.L=null;this.H=this.ca=!1;this.ja=jc(this,"url")||"";(Math.random()+.1).toString(36);this.w=Ke(this);if(this.b=lb("CPU",this.id)){this.B=lb("Debugger",this.id);this.ma=[];for(b=null;b=wb(this,"Video",b);)this.ma.push(b);this.A=new yb({id:this.zb+".bus",buswidth:this.ia},this.b,this.B);var d,e=C(this.id);if((this.D=lb("Panel",this.id))&&
this.D.xa)for(b=0;b<e.length;b++)d=e[b],d.ba=this.D.ba,d.g=this.D.g,d.xa=this.D.xa;for(b=0;b<e.length;b++)d=e[b],d.La&&d.La(this,this.A,this.b,this.B);b=null;d=a.resume;void 0!==d&&(1<d.length?b=this.J=d:this.s=parseInt(d,10));var f;if(a=jc(this,"state")||(f=!0,a.state))b=this.S=a,f||(this.H=!0,this.s=Je),this.s&&(this.M=new J(this,W),Fe(this.M)?b=null:delete this.M);!b&&this.s&&(b=Le(this))&&(this.H=!0);if(b){var k=this;u(b,null,!0,function(a,b,c){c?(k.J=null,k.H=!1,k.ba("Unable to load machine state from server (error "+
c+(b?": "+sa(b):"")+")")):(k.L=b,k.ca=!0);G(k)})}else G(this);this.G.power||(this.R=!0);!c&&this.R&&Me(this,this.cb)}else v("Unable to find CPU component")}z(He);var W="1.21.7",Je=0;function Ie(a,b){if(!b){var c;if("object"==typeof resources&&(c=resources.parms))try{b=eval("("+c+")")}catch(d){v(d.message+" ("+c+")")}}a.I=b}
function jc(a,b,c){var d=b.toLowerCase(),d=Va[b]||Va[d];void 0===d&&a.I&&(d=a.I[b]);void 0===d&&c&&(d=c[b]);void 0===d&&"object"==typeof resources&&resources[b]&&(d=b);return d}function Me(a,b,c){for(var d=C(a.id),e=0;e<=d.length;e++){var f=e<d.length?d[e]:a;if(!rb(f)){rb(f,function(){Me(a,b,c)});return}}b.call(a,c)}
function Ne(a,b){var c=new J(a,W,"validate");if(Fe(c)&&Ee(c)){var d=Ge(c,"timestamp"),e=b?Ge(b,"timestamp"):"unknown";d!=e&&(a.ba("Machine state may be out-of-date\n("+d+" vs. "+e+")\nCheck your browser's local storage limits"),b||c.clear())}}g=He.prototype;
g.cb=function(a){void 0===a&&(a=this.s||(this.L?1:Je));if(!this.C){this.C++;var b=!1,c=!1;this.aa=!1;var d=this.M||new J(this,W);if(-1==a)b=!0;else if(a>Je){if(Fe(d,this.L)){this.F=new J(this,W,"failsafe");Fe(this.F)&&(Oe(this,d),a=2,Ce(this.F));M(this.F,"timestamp",va());De(this.F);var e=this.s&&!this.H;if(1==a||za("Click OK to restore the previous PC8080 machine state, or CANCEL to reset the machine.")){if(c=Ee(d)){var f=Ge(d,"code"),k=Ge(d,"data");f&&("ok"==f?Fe(d,k):("error"==f&&"no machine state"!=
k?(this.ba("Error: "+k),"unable to verify user"==k&&(Ia("user",""),this.w=null)):this.g(f+": "+k),Ce(d),Fe(d)?(c=Ee(d),e=!0):c=!1))}e&&Ne(this,c?d:null)}else 2==a&&d.clear()}else Ne(this);delete this.L;delete this.M}e=C(this.id);for(f=0;f<e.length;f++)k=e[f],k!==this&&k!=this.b&&(c=Pe(this,k,d,b,c));b=[d,a,c];-1!=a?Me(this,this.Cb,b):this.Cb(b)}};
function Pe(a,b,c,d,e){if(!b.j.W){b.j.W=!0;if(b.pa){var f=null;e&&((f=Ge(c,b.id))||(f=Ge(c,b.id.replace(/[a-z0-9]\./i,"."))));"string"===typeof f&&(f=null);!b.pa(f,d)&&f&&(v("Unable to restore state for "+b.type),a.S&&!a.ca?(c.clear(),a.s=Je,window&&window.location.reload()):a.aa=!0,b.pa(null),e=!1)}if(!d&&b.vb)for(a=b.vb.split("|"),c=0;c<a.length;c++)b.status(a[c])}return e}
g.Cb=function(a){var b=a[0],c=0>a[1];a=a[2];this.j.W=!0;var d=this.G.power;d&&(d.textContent="Shutdown");this.V||(this.g("PC8080 v"+W+"\nCopyright \u00a9 2012-2016 Jeff Parsons <Jeff@pcjs.org>\nLicense: GPL version 3 or later <http://gnu.org/licenses/gpl.html>"),this.V=!0);this.b&&(Pe(this,this.b,b,c,a),nc(this.b));this.aa&&(Oe(this,b),b.clear());!c&&this.F&&(this.F.clear(),delete this.F);this.C=0};
function Oe(a,b){if(za("There may be a problem with your PC8080 machine.\n\nTo help us diagnose it, click OK to send this PC8080 machine state to http://www.pcjs.org.")){var c=a.ja,d=a.w||"",e=b.toString(),f={app:"PC8080"};f.ver=W;f.url=c;f.user=d;f.type="bug";f.data=e;u("http://www.pcjs.org/api/v1/report",f,!0)}}
function Ae(a,b,c){var d,e="none";if(a.C)return null;a.C--;var f=new J(a,W),k=new J(a,W,"validate"),h=va();M(k,"timestamp",h);M(f,"timestamp",h);M(f,"version","1.21.7");M(f,"url",window?window.location.href:null);M(f,"browser",ya());a.b&&a.b.oa&&(c&&a.b.U(),d=a.b.oa(b,c),"object"===typeof d&&M(f,a.b.id,d),c&&(a.b.j.W=!1,!1===d&&(e=null)));for(var h=C(a.id),l=0;l<h.length;l++){var m=h[l];m.j.W&&(m.oa&&(d=m.oa(b,c),"object"===typeof d&&M(f,m.id,d)),c&&(m.j.W=!1,!1===d&&(e=null)))}e&&(c?(h=d=!1,b?(a.w&&
Qe(a,a.w,f.toString()),De(k)&&De(f)||(e=null,d=h=!0)):a.s&&(d=!0,h=3==a.s),d&&f.clear(h)):e=f.toString());c&&(a.j.W=!1,b=a.G.power)&&(b.textContent="Power");a.C=0;return e}g.reset=function(){this.A&&this.A.reset&&(nb(this,"Resetting "+this.A.type),this.A.reset());for(var a=C(this.id),b=0;b<a.length;b++){var c=a[b];c!==this&&c!==this.A&&c.reset&&(nb(this,"Resetting "+c.type),c.reset())}};
g.start=function(a,b){for(var c=C(this.id),d=0;d<c.length;d++){var e=c[d];"CPU"!=e.type&&e!==this&&e.start&&e.start(a,b)}};g.stop=function(a,b){for(var c=C(this.id),d=0;d<c.length;d++){var e=c[d];"CPU"!=e.type&&e!==this&&e.stop&&e.stop(a,b)}};
g.ea=function(a,b,c){var d=this;switch(b){case "power":return this.G[b]=c,c.onclick=function(){d.C||(d.j.W?Ae(d,!1,!0):Me(d,d.cb))},!0;case "reset":return this.G[b]=c,c.onclick=function(){if(d.j.W&&!d.C)if(d.s&&!d.J){var a=za("Click OK to save changes to this PC8080 machine.\n\nWARNING: If you CANCEL, all disk changes will be discarded.");Ae(d,a,!0);!a&&d.S?window&&window.location.reload():d.cb(Je)}else d.reset(),d.b&&nc(d.b)},!0;case "save":if(ka(xa(),"pcjs.org")){c.parentNode.removeChild(c);break}this.G[b]=
c;c.onclick=function(){var a=Ke(d,!0);if(a){var b=!!(d.s&&!d.J||d.S),c=Ae(d,b);b?Qe(d,a,c):d.ba("Resume disabled, machine state not saved")}};return!0}return!1};
function Ke(a,b){var c=a.w;c||(c=Ha("user"),void 0!==c?!c&&b&&(c=null,window&&(c=window.prompt("Saving machine states on the pcjs.org server is currently unsupported.\n\nIf you're running your own server, enter your user ID below.","")),c&&((c=Re(a,c))||a.ba("The user ID is invalid."))):b&&a.ba("Browser local storage is not available"));return c}
function Re(a,b){a.w=null;var c=u(xa()+"/api/v1/user?req=verify&user="+b),d=c[1];if(!c[0]&&d)try{c=eval("("+d+")"),c.code&&"ok"==c.code&&(Ia("user",c.data),a.w=c.data)}catch(e){v(e.message+" ("+d+")")}return a.w}function Le(a){var b=null;a.w&&(b=xa()+"/api/v1/user?req=load&user="+a.w+"&state="+Be(a,W));return b}
function Qe(a,b,c){if(c){var d={req:"store"};d.user=b;d.state=Be(a,W);d.data=c;b=u(xa()+"/api/v1/user",d);d=b[0];if(b[1]){if(d){var e=d.indexOf("\n");0<e&&(d=d.substr(0,e));d.indexOf("Error: ")||(d=d.substr(7))}d='{"code":'+b[1]+',"data":"'+d+'"}'}b=JSON.parse(d);b&&"ok"==b.code?a.ba("Machine state saved to server"):c&&(c=b&&b.data||"unable to save machine state",c="error"==b.code?"Error: "+c:"Error "+b.code+": "+c,a.ba(c),Ia("user",""),a.w=null)}}
function wb(a,b,c){a=C(a.id);for(var d=0;d<a.length;d++){var e=a[d];if(c)c==e&&(c=null);else if(e.type==b)return e}return null}g.fb=function(){};g.fa=function(a){this.b&&this.b.fa(a);this.D&&this.D.fa(a)};Qa(function(){for(var a=F(document,"pc8080-machine"),b=0;b<a.length;b++)for(var c=a[b],d=E(c),c=F(c,"pc8080","computer"),e=0;e<c.length;e++){var f=c[e],k=E(f),k=new He(k,d,!0);mb(k,f);k.R&&Me(k,k.cb)}});
Ma.show.push(function(){for(var a=F(document,"pc8080","computer"),b=0;b<a.length;b++){var c=E(a[b]);(c=lb("Computer",c.id))&&c.V&&!c.j.W&&c.cb(-1)}});Ma.exit.push(function(){for(var a=F(document,"pc8080","computer"),b=0;b<a.length;b++){var c=E(a[b]);(c=lb("Computer",c.id))&&c.j.W&&Ae(c,!(!c.s||c.J),!0)}});var Se=0;function Te(a,b,c,d,e,f){e("Loading "+a+"...");u(a,null,!0,function(k,h,l){l?(h||(h="unable to load "+a+" ("+l+")"),f(h,null)):hf(h,a,b,c,d,e,f)})}
function hf(a,b,c,d,e,f,k){function h(a,f){if(f)k(f,null);else{if(c){kb(c,b,a);var h=b;h&&0>h.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(h=window.location.pathname+h);d?"}"==d.slice(-1)?(d=d.slice(0,-1),1<d.length&&(d+=",")):d='{state:"'+d+'",':d="{";d+='url:"'+h+'"}';"object"==typeof resources&&(h=null);a=a.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(d?" parms='"+d+"'":"")+(h?' url="'+h+'"':""))}e||(a=a.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1pc8080$2"));
h=null;if("<"==a.charAt(0))try{e||(a=a.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(h=new window.ActiveXObject("Microsoft.XMLDOM"),h.async=!1,h.loadXML(a)):h=(new window.DOMParser).parseFromString(a,"text/xml")}catch(r){h=null,a=r.message}else a="unrecognized XML: "+(255<a.length?a.substr(0,255)+"...":a);k(a,h)}}a?e?jf(a,f,h):h(a,null):k("no data"+(b?" for file: "+b:""),null)}
function jf(a,b,c){var d;if(d=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(a)){var e=d[2];b("Loading "+e+"...");u(e,null,!0,function(f,k,h){if(h||!k)c(a,"unable to resolve XML reference: "+d[0]+" ("+h+")");else{if(f=d[3])if(h=k.match(new RegExp("<"+d[1]+"[^>]*>"))){for(var l=h[0],m,p=/( [a-z]+=)(['"])(.*?)\2/g;m=p.exec(f);)l=0>l.indexOf(m[1])?l.replace(">",m[0]+">"):l.replace(new RegExp(m[1]+"(['\"])(.*?)\\1"),m[0]);h[0]!=l&&(k=k.replace(h[0],l))}else{c(a,"missing <"+d[1]+"> in "+e);return}k=k.replace(/<\?xml[^>]*>[\r\n]*/,
"");a=a.replace(d[0],k);jf(a,b,c)}})}else c(a,null)}
function kf(a,b,c,d){function e(a){if(void 0===h){var b=k&&F(k,"machine-warning");h=b&&b[0]||k}h&&(h.innerHTML=ma(a))}function f(a){e("Error: "+a);l&&(--Se||Sa(!0));l=!1}var k,h,l=!0;Se++;jb[a]={};try{if(k=document.getElementById(a)){var m;if("object"==typeof resources&&(m=resources.css)){var p=document.head||document.getElementsByTagName("head")[0],r=document.createElement("style");r.type="text/css";r.styleSheet?r.styleSheet.cssText=m:r.appendChild(document.createTextNode(m));p.appendChild(r)}c||
(c="/versions/pc8080/1.21.7/components.xsl");m=function(d,h){h?Te(c,null,null,!1,e,function(d,m){if(m)if(kb(a,c,d),e("Processing "+b+"..."),window.ActiveXObject||"ActiveXObject"in window){var l=h.transformNode(m);l?(k.outerHTML=l,--Se||Sa(!0)):f("transformNodeToObject failed")}else document.implementation&&document.implementation.createDocument?(l=new XSLTProcessor,l.importStylesheet(m),(l=l.transformToFragment(h,document))?k.parentNode?(k.parentNode.replaceChild(l,k),--Se||Sa(!0)):f("invalid machine element: "+
a):f("transformToFragment failed")):f("unable to transform XML: unsupported browser");else f(d)}):f(d)};"<"!=b.charAt(0)?Te(b,a,d,!0,e,m):hf(b,null,a,d,!1,e,m)}else f("missing machine element: "+a)}catch(t){f(t.message)}return l}window.embedPC8080=function(a,b,c,d){Sa(!1);return kf(a,b,c,d)};window.enableEvents=Sa;window.sendEvent=Ta;
function lf(a,b,c,d){if(!c&&b){d.push(b);a=jb[d[0]];b=null;for(var e in a)if(ka(e,"components.xsl")){b=e.replace(".xsl",".css");break}b?u(b,null,!0,function(a,b){mf(b,d)}):mf(null,d)}else v("Error ("+c+") requesting "+a)}
function mf(a,b){var c,d,e,f=b[0],k=b[1];c=b[4];c=c.match(/^(\s*\(function\(\)\{)([\s\S]*)(}\)\(\);\s*)$/);var h=jb[f],l={},m;for(m in h){var p=h[m],r=fa(m);if("xml"==r){for(r=/[ \t]*<disk [^>]*path=(['"])(.*?)\1.*?<\/disk>\n?/g;d=r.exec(h[m]);){var t=d[2];t&&(h[t]||(p=p.replace(d[0],"")))}d=m=ea(m)}else"xsl"==r&&(e=m=ea(m));l[m]=p}a&&(l[m="css"]=a);b[2]&&(l[m="parms"]=b[2]);b[3]&&(l[m="state"]=b[3]);d&&e?(m=JSON.stringify(l),k+=".js",c=c[1]+"var resources="+m+";"+c[2]+c[3],c=c.replace(/\u00A9/g,
"&#xA9;"),m=k,h=null,l="data:application/javascript,",l=Ja("Firefox")?l+encodeURIComponent(c):l+encodeURI(c),m&&(h=document.createElement("a"),"string"!=typeof h.download&&(h=null)),h?(h.href=l,h.download=m,document.body.appendChild(h),h.click(),document.body.removeChild(h),c="Check your Downloads folder for "+m+"."):(window.open(l),c="Check your browser for a new window/tab containing the requested data"+(m?" ("+m+")":"")+"."),c+=', copy it to your web server as "'+k+'", and then add the following to your web page:\n\n',
c+='<div id="'+f+'"></div>\n',c+="...\n",c+='<script type="text/javascript" src="'+k+'">\x3c/script>\n',c+='<script type="text/javascript">embedPC("'+f+'","'+d+'","'+e+'");\x3c/script>\n\n',c+="The machine should appear where the <div> is located.",v(c)):v("Missing XML/XSL resources")}
window.savePC=function(a,b,c){var d=lb("Computer",a),e=lb("Debugger",a);if(d){var f=Ae(d,!0),k=d.I?JSON.stringify(d.I):null;b||(b="/versions/pcjs/1.21.7/pc"+(e?"-dbg":"")+".js");if(c&&c({state:f,Kb:k}))return!0;u(b,null,!0,function(c,d,e){lf(c,d,e,[a,ea(b,!0),k,f])});return!0}v("Unable to identify machine '"+a+"'");return!1};})();
