(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbgio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbg8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/port.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/ram.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/invaders/chip.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/invaders/video.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/machine.js (C) Jeff Parsons 2012-2019
*/
var f;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ca(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:ba(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={ub:!0},ja={};try{ja.__proto__=ia;ha=ja.ub;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function n(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Pg=b.prototype}var la="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ma="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function oa(a,b){if(b){var c=ma;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&la(c,a,{configurable:!0,writable:!0,value:b})}}oa("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});oa("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});oa("Number.parseInt",function(a){return a||parseInt});
oa("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function pa(){}function qa(){}n(qa,pa);
function ra(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var g;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)/))&&
(a=c[1],e=35-((c[2]||35)&255));c=a;if(((d=b)&&10!=d?16==d?null!==c.match(/^-?[0-9a-f]+$/i):8==d?null!==c.match(/^-?[0-7]+$/):2==d&&null!==c.match(/^-?[01]+$/):null!==c.match(/^-?[0-9]+$/))&&!isNaN(g=parseInt(a,b))){e&&(0>g&&(g+=Math.pow(2,36)),g=0<e?g*Math.pow(2,e):Math.trunc(g/Math.pow(2,-e)));var h=g}}return h}
function sa(a,b,c,d){var e;d=void 0===d?0:d;var g=void 0===g?0:g;var h="",m="",l=-1;void 0!=c&&void 0==e&&(e="");c||(c=a.X||10);d&&(l=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:m=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=m=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(l=Math.ceil(Math.log(b)/Math.log(c)))));for(a=g||-1;l--;){a||(h=","+h,a=g);if(void 0==b){if(h="?"+h,0>l)break}else{d=b%c;d+=0<=d&&9>=d?48:
55;h=String.fromCharCode(d)+h;if(!b&&0>l)break;b=Math.trunc(b/c)}a--}return e+h+m}function ta(a,b){var c=a/q|0,d=b/q|0;return(a&b)==(b|0)&&(c&d)==d}var q=Math.pow(2,32);function ua(){}n(ua,qa);f=ua.prototype;f.flush=function(){var a=va;va="";this.ta(a)};f.vg=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ca(b)))};
f.ta=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(va+a.substr(0,b)),va="",a=a.substr(b+1)));va+=a};f.M=function(a,b){this.ta(a+"\n",b)};f.J=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.ta(this.K.apply(this,[a].concat(ca(c))))};
f.K=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),g=0,h;for(h=0;h<e.length-6;h+=6){d+=e[h];var m=e[h+5],l="ACDFHIMNSTWYbdfjcsoXx%".indexOf(m);if(0>l)d+="%"+e[h+1]+e[h+2]+e[h+3]+e[h+4]+m;else{if(g<c.length){var k=c[g];"%"!=m&&g++}else k=c[c.length-1];var p=e[h+1],w=e[h+2];"*"==w?(w=k,k=g<c.length?c[g++]:c[c.length-1]):w=+w||0;var v=e[h+3];v=v?+v.substr(1):-1;var r=0<=p.indexOf("#"),t=0<=p.indexOf("0"),
u=null,y=0,C="";l=12>l&&"object"!=typeof k?this.vg(k):k;switch(m){case "C":k=r?"#":"";d+=isNaN(l.getTime())?void 0:this.K(this.K("%%%sW, %%%sF %%%sD, %%%sY",k),l);continue;case "D":k=r?l.getUTCDate():l.getDate();m="d";break;case "A":case "H":case "I":k=r?l.getUTCHours():l.getHours();"A"==m?(k=12>k?"am":"pm",m="s"):("I"==m&&(k=k?12<k?k-12:k:12),m="d");break;case "F":case "M":k=r?l.getUTCMonth():l.getMonth();"F"==m?(k=xa[k],m="s"):(k++,m="d");break;case "N":k=r?l.getUTCMinutes():l.getMinutes();m="d";
break;case "S":k=r?l.getUTCSeconds():l.getSeconds();m="d";break;case "T":k=r?"#":"";d+=isNaN(l.getTime())?void 0:this.K(this.K("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",k),l);continue;case "W":k=ya[r?l.getUTCDay():l.getDay()];m="s";break;case "Y":k=r?l.getUTCFullYear():l.getFullYear(),0<v&&(k%=Math.pow(10,v),v=-1),m="d"}switch(m){case "b":d+=k?"true":"false";break;case "d":k=Math.trunc(k);case "f":m=k+"";0<=v&&(m=k.toFixed(v));m.length<w&&(t?(0>k&&(w--,m=m.substr(1)),m=("0000000000"+m).slice(-w),
0>k&&(m="-"+m)):m=("          "+m).slice(-w));d+=m;break;case "j":d+=JSON.stringify(k,null,w||void 0);break;case "c":k="string"==typeof k?k[0]:String.fromCharCode(k);case "s":if(void 0!==k)for("string"!=typeof k&&(k=k.toString()),0<=v&&(k=k.substr(0,v));k.length<w;)k=0<=p.indexOf("-")?k+" ":" "+k;d+=k;break;case "o":y=8,r&&(C="0");case "X":u=za;case "x":m="";y||(y=16);!C&&r&&(C="0x");u||(u=Aa);"string"==typeof k&&(k=Number.parseInt(k,k.match(/(^0x|[a-f])/i)?16:10));t&&!w&&(w=Math.abs(k),w=65535>=
w?4:4294967295>=w?8:9);w-=C.length;do v=k&y-1,k>>>=16==y?4:3,t||!m||v||k?m=u[v]+m:(C&&(m=C+m,C=""),0<w&&(m=" "+m));while(0<--w||k);d+=C+m;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+m+")"}}}return d+=e[h]};
var va="",Aa="0123456789abcdef",za="0123456789ABCDEF",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" "),x={Ag:0xffffffffffff,NONE:0,Cg:0,Na:0x800000000000},Ba=x.NONE;function Ca(a,b,c,d){this.R=a;this.ua=b;this.W={};this.ya="";Da(this,c);this.version=d||2}var Ea;n(Ca,ua);
Ca.prototype.za=function(a,b){var c=this;switch(a){case Fa.lb:b.onclick=function(){var d=c.Da(Fa.Ra,!0);d&&(d.value="")};break;case Fa.Ra:b.value="",b.addEventListener("keypress",function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){var g=b.value;b.setSelectionRange(g.length,g.length);d.stopPropagation();13==e&&(d.preventDefault(),g=b.value+="\n",b.blur(),b.focus(),Ga(c,g))}})}};
function Da(a,b){b=void 0===b?{}:b;if(b.overrides){var c=Ha();for(h in c)if(0<=b.overrides.indexOf(h)){var d=c[h];if(d.match(/^[+-]?[0-9.]+$/))var e=Number.parseInt(d,10);else"true"==d?e=!0:"false"==d?e=!1:(e=d,d='"'+d+'"');b[h]=e;a.M("overriding "+a.ua+" property '"+h+"' with "+d)}}a.S||(a.S=b);b=b.bindings;c=Array.isArray(b);for(var g in b){e=b[g];if(c)g=e;else if(e.match(/^[0-9]+$/)){var h=+e;a.W[g]=[];do{e=g+h++;e=document.getElementById(e);if(!e)break;a.W[g].push(e)}while(1);continue}if(h=document.getElementById(e))a.W[g]=
h,a.za(g,h)}}Ca.prototype.Da=function(a){return this.W[a]};function Ia(a){var b=Ja.ab;return Ka[a.R]&&Ka[a.R][b]}function La(a,b,c){if(a)for(var d=0;d<Ma.length;d++){var e=Ma[d];if(c){if(e+=c,b+e in a)return e}else if(e=e?e+b[0].toUpperCase():b[0],e+=b.substr(1),e in a)return e}return null}function Na(a){var b=Oa;return a.S.bindings&&a.S.bindings[b]}function Pa(a){if(a=a.W[Qa])var b=a.textContent;return b}function Ra(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function z(a,b,c){a=a.S[b];void 0===a?a=c:(b=typeof c,typeof a!=b&&("boolean"==b?a=!!a:"number"==typeof c&&(a=+a)));return a}function Sa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Ha(){var a,b=Ea;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ea=b}return b}function Ta(a){if(void 0===Ua.Ma){var b=!1;if(window)try{window.localStorage.setItem(Ua.wa,Ua.wa),b=window.localStorage.getItem(Ua.wa)==Ua.wa,window.localStorage.removeItem(Ua.wa)}catch(c){a.M(c.message),b=!1}Ua.Ma=b}return!!Ua.Ma}
function Va(a){a=void 0===a?0:a;a%2&&a--;a=a||0;return-1==(a|1)||ta(Ba,a)?!0:!1}function Wa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Xa(a){if(window){var b=window.onresize;window.onresize="function"!==typeof b?a:function(){b&&b();a()}}}function Ya(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function Ga(a,b){try{var c=b.lastIndexOf("\n",b.length-2),d=b.slice(c+1,-1)||a.ya;a.ya="";d=d.trim();var e=d.split(" "),g=Ia(a);switch(e[0]){case "m":var h=1;var m=e[e.length-1].toLowerCase();var l=Ya(m);void 0!=l?e.pop():1>=e.length&&(e=Object.keys(x),h=3);for(c=h;c<e.length;c++){m=e[c].toUpperCase();var k=x[m];if(!k){ua.prototype.M.call(a,"unrecognized message group: "+m,!1);break}void 0!=l&&Za(a,k,l);ua.prototype.M.call(a,m+": "+Va(k),!1)}break;case "?":var p="";$a.forEach(function(w){p+="\n"+
w});p&&ua.prototype.M.call(a,"default commands:"+p,!1);default:if(e.unshift(d),g)for(c=0;c<g.length&&!g[c](e);c++);}}catch(w){ua.prototype.M.call(a,"error: "+w.message)}}Ca.prototype.ta=function(a,b){void 0==b&&(b=Va(x.Na));if(!b){var c=this.Da(Fa.Ra,!0);if(c){c.value+=a;8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096));c.scrollTop=c.scrollHeight;return}}ua.prototype.ta.call(this,a,b)};
Ca.prototype.J=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());Va(d)&&ua.prototype.J.call.apply(ua.prototype.J,[this,a].concat(ca(c)))};function ab(a,b,c){if(a=a.W[b])a.textContent=c}function Za(a,b,c){var d=!1;c?(c=Ba,Ba=(c|b)+(c/q|0|b/q|0)*q):(d=ta(Ba,x.Na)&&ta(b,x.Na),c=Ba,Ba=(c&~b)+((c/q|0)&~(b/q|0))*q);d&&a.flush()}
var Fa={lb:"clear",Ra:"print"},$a=["m\t\tenable messages"],Ja={ab:"command"},bb={list:[],tb:"version"},Ua={Ma:void 0,wa:"PCjs.localStorage"},Ma=["","moz","ms","webkit"],Ka={};x.zg=1;x.Bg=2;x.ja=4;x.Kg=8;x.sb=256;x.Pa=512;x.Qa=4096;x.Lg=8192;x.ob=16384;function D(a,b,c,d){Ca.call(this,a,b,c,d);this.status="OK";cb[this.R]||(cb[this.R]=[]);cb[this.R].push(this);this.xa={}}n(D,Ca);function db(a,b){if(a=cb[a.R])for(var c in a)b(a[c])}
D.prototype.Da=function(a,b){b=void 0===b?!1:b;var c=Ca.prototype.Da.call(this,a,b);if(void 0===c&&b){b=cb[this.R];for(var d in b)if(c=b[d].W[a])break;c||(c=null);this.W[a]=c}return c};function eb(a,b){if(a=cb[a.R])for(var c in a)if(a[c].ua==b){var d=a[c];break}return d}function fb(a,b){if(a=cb[a.R])for(var c in a)if(a[c].S["class"]==b){var d=a[c];break}return d}function gb(a,b){if(a=cb[a.R])for(var c in a)if(a[c].ua==b){a.splice(c,1);break}}D.prototype.jb=function(a,b){(a=this.xa[a])&&a.set(b)};
var cb={};function hb(a,b,c){D.call(this,a,b,c);this.g=c.addrWidth||16;this.h=c.dataWidth||8;this.f=Math.pow(2,this.g);this.i=this.f-1|0;this.a=c.blockSize||1024;this.a>this.f&&(this.a=this.f);this.l=this.f/this.a|0;this.c=Math.log2(this.a)|0;this.j=(1<<this.c)-1;this.b=Array(this.l);a=new E(a,b+".none",{size:this.a,width:this.h});for(b=0;b<this.f;b+=this.a)ib(this,b,this.a,jb.NONE,a)}n(hb,D);
function ib(a,b,c,d,e){for(var g=0,h=0,m=b>>>a.c;0<c&&m<a.b.length;){var l=m*a.a,k=a.a-(b-l);k>c&&(k=c);var p=a.b[m];if(b!=l||k!=a.a)throw Error(a.K("addBlocks(%#0x,%#0x): block boundary error",b,k));if(p&&p.type!=jb.NONE)throw Error(a.K("addBlocks(%#0x,%#0x): block (%d) already exists",b,k,p.type));if(e)if(e.size==a.a)b=e;else{p=void 0;if(e.values&&(p=e.values.slice(g,g+k),p.length!=k))throw Error(a.K("addBlocks(%#0x,%#0x): insufficient values (%d)",b,k,p.length));b=new E(a.R,e.ua+".block"+h,{type:d,
ia:b,size:k,width:a.h,values:p})}else b=new E(a.R,a.ua+".block"+h,{type:d,ia:b,size:k,width:a.h});a.b[m++]=b;b=l+a.a;c-=k;g+=k;h++}return!0}function kb(a,b){for(var c=jb.Sa|jb.va,d=0,e=0;e<a.b.length;e++){var g=a.b[e];g&&g.type&c&&(b(g),d++)}return d}hb.prototype.$=function(a){return this.b[(a&this.i)>>>this.c].$(a&this.j)};hb.prototype.ca=function(a,b){this.b[(a&this.i)>>>this.c].ca(a&this.j,b)};
function lb(a,b,c){var d=a.b[b>>>a.c];void 0!=d.ia&&(a=function(e){var g=d.Wa(e);d.Ja(d.ia+e,g);return g},d.Ga?d.Ja==c&&d.Ga++:(d.Ga=1,d.Ja=c,d.Wa=d.$,d.$=a))}function mb(a,b,c){var d=a.b[b>>>a.c];void 0!=d.ia&&(a=function(e,g){d.La(d.ia+e,g);d.$a(e,g)},d.Ha?d.La==c&&d.Ha++:(d.Ha=1,d.La=c,d.$a=d.ca,d.ca=a))}function nb(a,b,c){a=a.b[b>>>a.c];return a.Ga&&a.Ja==c?(--a.Ga||(a.$=a.Wa,a.Wa=a.Ja=void 0),!0):!1}
function ob(a,b,c){a=a.b[b>>>a.c];return a.Ha&&a.La==c?(--a.Ha||(a.ca=a.$a,a.$a=a.La=void 0),!0):!1}
function pb(a,b,c){D.call(this,a,b,c);this.X=16;this.H=1;this.o=["(",")"];this.l={};this.g=[];this.h=[];this.c=[];this.f=[];this.w=this.yb.bind(this);this.O=this.zb.bind(this);this.L=this.wb.bind(this);this.N=this.xb.bind(this);this.j=0;this.a=fb(this,qb);this.xa=this.a.xa;this.I=eb(this,this.a.S.busIO);this.b=eb(this,this.a.S.busMemory);this.u=this.b.g;this.time=fb(this,rb);this.s=sb();this.m=0;this.i=[];a=this.Kb.bind(this);b=Ja.ab;Ka[this.R]||(Ka[this.R]={});Ka[this.R][b]||(Ka[this.R][b]=[]);Ka[this.R][b].push(a)}
n(pb,D);function tb(a,b,c){b.T=b.T+c&a.b.i}function sb(a){a=void 0===a?0:a;var b=ub.qb;return"number"==typeof a?{T:a,Xa:-1,type:b}:{T:a.T,Xa:a.Xa,type:a.type}}function vb(a,b){if(b){var c=0,d=b.charAt(c);var e=sb();switch(d){case "&":c++;break;case "#":c++;e.type=ub.rb;break;case "%":c++,d=b.charAt(c),"%"==d?c++:e.type=ub.LINEAR}d=b.indexOf(":");0<=d&&(c=wb(a,b.substring(c,d)),void 0!=c&&(e.Xa=c),c=d+1);e.T=wb(a,b.substring(c))||0}return e}
function xb(a,b,c){a.j++;var d=a.b.$(b.T);c&&tb(a,b,c);a.j--;return d}function yb(a,b,c){a.j++;a.b.ca(b.T,c);a.j--}function zb(a,b,c){if(32>=a.u)return b&c;b=Ab(a,b,0,!0);c=Ab(a,c,0,!0);return((b/q|0)&(c/q|0))*q+((b&c)>>>0)}function Bb(a,b,c){if(32>=a.u)return b^c;b=Ab(a,b,0,!0);c=Ab(a,c,0,!0);return((b/q|0)^(c/q|0))*q+((b^c)>>>0)}
function Cb(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var g=b.pop();var h=b.pop();switch(e){case "*":h*=g;break;case "/":if(!g)return!1;h=Math.trunc(h/g);break;case "^/":if(!g)return!1;h%=g;break;case "+":h+=g;break;case "-":h-=g;break;case "<<":h<<=g;break;case ">>":h>>=g;break;case ">>>":h>>>=g;break;case "<":h=h<g?1:0;break;case "<=":h=h<=g?1:0;break;case ">":h=h>g?1:0;break;case ">=":h=h>=g?1:0;break;case "==":h=h==g?1:0;break;case "!=":h=h!=g?1:0;break;
case "&":h=zb(a,h,g);break;case "!":case "|":e=h;32>=a.u?h=e|g:(e=Ab(a,e,0,!0),g=Ab(a,g,0,!0),h=(e/q|0|g/q|0)*q+((e|g)>>>0));break;case "^!":h=Bb(a,h,g);break;case "&&":h=h&&g?1:0;break;case "||":h=h||g?1:0;break;case ",,":h=Ab(a,h,18,!0)*Math.pow(2,18)+Ab(a,g,18,!0);break;case "_":case "^_":"^_"==e&&(g=35-(g&255));g&&(h=Ab(a,h,0,!0),h=0<g?h*Math.pow(2,g):Math.trunc(h/Math.pow(2,-g)));break;default:return!1}b.push(Ab(a,h))}return!0}
function Db(a,b,c,d,e,g){var h,m=!1,l=0,k=[],p=[],w=a.X;for(a.X=e;c<d;){var v=b[c++].trim();var r=c<d?b[c++]:"";if(v){var t=void 0;var u=a;var y=v,C=g;l=void 0===l?0:l;if(void 0!=y){t=(t=u.xa[y.toUpperCase()])&&t.get();if(void 0==t)if(t=y,u.l[t]?t=u.l[t].value:(t=t.substr(0,6),t=u.l[t]&&u.l[t].value),void 0!=t){if(y=u.l[y]&&u.l[y].Og)C?C.push(y):(C=wb(u,y,C),void 0!==C?t+=C:t=void 0)}else t=ra(y,1<y.length||10<u.X?u.X:10);void 0!=t&&(t=Ab(u,Eb(u,t,l)))}u=t}else if("{"==r){v=1;for(u=c;c<d;)if(c++,
r=c<b.length?b[c++]:"","{"==r)v++;else if("}"==r&&!--v)break;u=Db(a,b,u,c-1,a.X,g);null!=u&&l&&(u=Eb(a,u,l));v=c<d?b[c++].trim():"";r=c<d?b[c++]:""}else{if(" "==r)continue;if("^B"==r){a.X=2;continue}if("^O"==r){a.X=8;continue}if("^D"==r){a.X=10;continue}if(!(l&-1073741824)){if("+"==r)continue;if("-"==r){l=l<<2|1;continue}if("~"==r||"^-"==r){l=l<<2|2;continue}if("^L"==r){l=l<<2|3;continue}}m=!0;break}if(void 0===u)if(g)g.push(v),u=0;else{m=!0;g=[];break}k.push(Ab(a,u));if(" "==r)if(c<b.length-1&&!b[c])c++,
r=b[c++];else{m=!0;break}if(!r)break;u="<"==a.o[0]?Fb:Gb;if(!u[r]){m=!0;break}p.length&&u[r]<=u[p[p.length-1]]&&Cb(a,k,p,1);p.push(r);a.X="^_"==r?10:e;l=0}if(m||!Cb(a,k,p)||1!=k.length)m=!0;m?g||a.M("parse error ("+(v||r)+")"):h=k.pop();a.X=w;return h}
function Hb(a,b,c,d,e){for(var g;0<=(g=b.indexOf(c));){for(var h=0,m=g+1,l=e;m<b.length;){var k=b[m++];if(k==c){l=-1;break}if(!l)break;l--;k=k.charCodeAt(0);7==d?k&=127:k=k-32&63;h=Ab(a,h*Math.pow(2,d)+k,d*e,!0)}if(0<=l){a.M("parse error ("+c+b+c+")");return}b=b.substr(0,g)+sa(a,h)+b.substr(m)}return b}
function wb(a,b,c){var d=void 0;if(b){"{"!=a.o[0]&&(b=b.split(a.o[0]).join("{").split(a.o[1]).join("}"));b=Hb(a,b,'"',7,5);if(!b)return d;b=Hb(a,b,"'",6,6);if(!b)return d;16!=a.X&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);d=Db(a,b,0,b.length,a.X,c)}return d}
function Eb(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-Ab(a,b);break;case 2:b=Bb(a,b,-1);break;case 3:for(d=35;0<=d&&!zb(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function Ab(a,b,c,d){var e=b;c=c||a.u;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}f=pb.prototype;
f.eb=function(a){if(-1>a)return Ib(this,this.eb);var b="",c=this.I,d=a,e="bi",g=!1,h=!1,m=this.c;d>=m.length&&(d-=m.length,e="bo",h=!0,m=this.f);d>=m.length&&(d-=m.length,c=this.b,e="br",g=!0,h=!1,m=this.g);d>=m.length&&(d-=m.length,e="bw",h=!0,m=this.h);if(0<=d){var l=m[d],k=function(p){for(var w=0;w<p.length;w++)if(void 0!=p[w])return!1;return!0};if(void 0!=l){if(!h&&nb(c,l,g?this.w:this.L)||h&&ob(c,l,g?this.O:this.N))m[d]=void 0,b+=this.K("%2d: %s %#0x cleared\n",a,e,l),k(this.h)&&(this.h=[],k(this.g)&&
(this.g=[],k(this.f)&&(this.f=[],k(this.c)&&(this.c=[],Kb(this,!1)))));b||(b=this.K("invalid break address: %#0x\n",l))}b||(b=this.K("invalid break index: %d\n",a))}b||(b="missing break index");return b};
f.Ua=function(a,b){b=void 0===b?!1:b;if(-1>a)return Ib(this,this.Ua,b);var c="";if(0<=a){var d=a,e="bi",g=this.c;d>=g.length&&(d-=g.length,e="bo",g=this.f);d>=g.length&&(d-=g.length,e="br",g=this.g);d>=g.length&&(d-=g.length,e="bw",g=this.h);if(0<=d){var h=!0,m=g[d],l=b?"enabled":"disabled";if(m<q){var k=m;b?h=!1:m=(m>>>0)+q}else k=m-q|0,b?m=k:h=!1;h?(g[d]=m,c+=this.K("%2d: %s %#0x %s\n",a,e,k,l)):c+=this.K("%2d: %s %#0x already %s\n",a,e,k,l)}}c||(c="missing break index");return c};
function Ib(a,b,c){function d(h,m){m=void 0===m?0:m;for(var l=0;l<h.length;l++)void 0!=h[l]&&(e+=b.call(a,l+m,c));return h.length}var e="",g=0;g+=d(a.c,g);g+=d(a.f,g);g+=d(a.g,g);g+=d(a.h,g);e||(e="no break addresses found");return e}
function Lb(a,b){function c(g,h,m){for(var l=0;l<g.length;l++){var k=g[l];if(void 0!=k&&(0>b||b==l+m)){var p="enabled";k>=q&&(p="disabled",k=k-q|0);d+=a.K("%2d: %s %#0x %s\n",l+m,h,k,p)}}return g.length}var d="",e=0;e+=c(a.c,"bi",e);e+=c(a.f,"bo",e);e+=c(a.g,"br",e);e+=c(a.h,"bw",e);d||(d="no break addresses found");return d}
function Mb(a,b,c,d){c=void 0===c?!0:c;d=void 0===d?!1:d;var e="";if(b){var g=a.b,h=d?"bw":"br",m=d?a.h:a.g;c||(g=a.I,h=d?"bo":"bi",m=d?a.f:a.c);var l=m.indexOf(b.T);0>l&&(l=m.indexOf((b.T>>>0)+q));if(0<=l)l=-(l+1);else{for(l=0;l<m.length&&void 0!=m[l];l++);m[l]=b.T}m=l;0<=m?(d?mb(g,b.T,c?a.O:a.N):lb(g,b.T,c?a.w:a.L),c?(m+=a.c.length+a.f.length,d&&(m+=a.g.length)):d&&(m+=a.c.length),e+=a.K("%2d: %s %#0x set\n",m,h,b.T)):e+=a.K("%s %#0x already set\n",h,b.T)}else e="missing break address";return e}
f.wb=function(a,b){this.j||0<=this.c.indexOf(a)&&Nb(this,this.K("break on input %#0x: %#0x",a,b))};f.xb=function(a,b){this.j||0<=this.f.indexOf(a)&&Nb(this,this.K("break on output %#0x: %#0x",a,b))};f.yb=function(a,b){this.j||(this.i.length&&0==(a-this.a.c&-4)&&(this.i[this.m++]=a,this.m==this.i.length&&(this.m=0)),0<=this.g.indexOf(a)&&Nb(this,this.K("break on read %#0x: %#0x",a,b)))};f.zb=function(a,b){this.j||0<=this.h.indexOf(a)&&Nb(this,this.K("break on write %#0x: %#0x",a,b))};
function Nb(a,b){a.M(b);Ob(a.time)}function Pb(a,b){var c=void 0===c?10:c;var d="";0>b&&(b=c);b=a.m-b;0>b&&(b+=a.i.length);for(var e,g=[];0<=b&&b<a.i.length&&0<c;){var h=a.i[b++];if(b==a.i.length){if(d)break;b=0}if(void 0!=h||g.length){e||(e=sb(h));if(h!=e.T||g.length==a.H)tb(a,e,-g.length),d+=a.Ya(e,g),c--;void 0!=h&&(e.T=h,g.push(xb(a,e,1)))}}return d||"no history"}
function Qb(a,b,c){var d=[],e="";for(b="number"==typeof b?sb(b):b;c--;){for(tb(a,b,d.length);d.length<a.H;)d.push(xb(a,b,1));tb(a,b,-d.length);e+=a.Ya(b,d)}return e}
function Rb(a,b,c,d,e){var g="";c||(c=a.b.h);var h=c>>3;d||(d=128);var m=0,l=d+15>>4||1,k=4==h?16:a.X;"y"==e&&(k=h,l=d,m=8*h);b||(b=a.s);for(;l--&&0<d;){var p=e=0,w,v="",r="",t=sa(a,b.T,a.X,a.b.g);for(w=k;0<w&&0<d;w--){var u=xb(a,b,1);e|=u<<(p++<<3);p==h&&(v+=sa(a,e,0,c),v+=1==h?9==w?"-":" ":" ",m&&(r+=sa(a,e,2,c)),e=p=0);m||(r+=32<=u&&127>u?String.fromCharCode(u):".");d--}g&&(g+="\n");g+=t+"  "+v+" "+r}a.s=b;return g}
function Kb(a,b){var c;if(void 0==b)return"unrecognized option";if(c=kb(a.b,function(d){for(var e=d.ia,g=0;g<d.size;e++,g++)b?lb(a.b,e,a.w):nb(a.b,e,a.w)}))a.m=0,a.i=b?Array(Sb):[];return a.K("history %s for %d blocks\n",b?"enabled":"disabled",c)}
f.Kb=function(a){var b="",c=0,d=[],e=a[1];if("*"==a[2])var g=-2;else{g=ra(a[2]);void 0==g&&(g=-1);var h=vb(this,a[2])}var m=0;a[3]&&(m=ra(a[3].substr("l"==a[3][0]?1:0))||8);for(var l=3;l<a.length;l++)d.push(ra(a[l],16));switch(e[0]){case "b":"c"==e[1]?b=this.eb(g):"d"==e[1]?b=this.Ua(g):"e"==e[1]?b=this.Ua(g,!0):"i"==e[1]?b=Mb(this,h,!1):"l"==e[1]?b=Lb(this,g):"o"==e[1]?b=Mb(this,h,!1,!0):"r"==e[1]?b=Mb(this,h,!0):"w"==e[1]?b=Mb(this,h,!0,!0):(b="break commands:",Tb.forEach(function(k){b+="\n"+k}));
break;case "d":if("b"!=e[1]&&e[1])if("w"==e[1])c=16;else if("d"==e[1])c=32;else{"h"==e[1]?b=Pb(this,g):(b="dump commands:",Ub.forEach(function(k){b+="\n"+k}));break}else c=8;b=Rb(this,h,c,m,e[2]);break;case "e":for(e=0;void 0!=h&&e<d.length;e++){m=xb(this,h);if(void 0==m)break;yb(this,h,d[e]);b+=this.K("%#06x: %#06x changed to %#06x\n",h.T,m,d[e]);tb(this,h,1);c++}b+=this.K("%d locations updated\n",c);break;case "g":this.time.start()?void 0!=h&&Mb(this,h):b="already started";break;case "h":Ob(this.time)||
(b="already stopped");break;case "p":a.shift();a.shift();h=a.join(" ");this.J("%s = %s\n",h,sa(this,wb(this,h)));break;case "r":void 0!=h&&this.a.jb(e.substr(1),h.T);b+=this.a.toString(e[1]);this.ya=a[0];break;case "s":h=Ya(a[2]);"h"==e[1]?b=Kb(this,h):(b="set commands:",Vb.forEach(function(k){b+="\n"+k}));break;case "t":m=ra(a[2],10)||1;Wb(this.time,m);this.ya=a[0];break;case "u":m||(m=8);h||(h=this.s);b+=Qb(this,h,m);this.s=h;this.ya=a[0];break;case "?":b="debugger commands:";Xb.forEach(function(k){b+=
"\n"+k});break;default:b=void 0}void 0==b&&a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')");b&&this.M(b.replace(/\s+$/,""));return b};f.Ya=function(a,b){var c=this;return this.K("%s %02x         unsupported\n",sa(this,a.T,this.X,this.b.g),function(){var d=b.shift();tb(c,a,1);return d}())};
var Xb="b?\t\tbreak commands;d?\t\tdump commands;e [addr] ...\tedit memory;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;s?\t\tset commands;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";"),Tb="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write".split(";"),Ub=["db  [addr]\tdump bytes (8 bits)",
"dw  [addr]\tdump words (16 bits)","dd  [addr]\tdump dwords (32 bits)","d*y [addr]\tdump values in binary"],Vb=["sh [on|off]\tset instruction history"],ub={qb:0,LINEAR:1,rb:2},Yb={pb:"PC"},Sb=1E5,Gb={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},Fb={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,
"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};function Zb(a,b,c){pb.call(this,a,b,c);this.style=$b;this.H=3}n(Zb,pb);
Zb.prototype.Ya=function(a,b){function c(A,B){var aa=ac[A];g.style==$b&&B&bc&&(A==cc&&(aa="HL"),aa="["+aa+"]");return aa}function d(A){switch(A&dc){case F:var B=sa(g,e(),16,8);break;case ec:B=sa(g,(e()|e()<<8)<<24>>24,16,16);break;case fc:B=sa(g,e()|e()<<8,16,16);break;default:return"imm("+sa(g,A,16,16)+")"}g.style==$b&&A&bc?B="["+B+"]":A&gc||(B=(g.style==jc?"$":"0x")+B);return B}function e(){var A=b.shift();m+=sa(g,A,16,8);tb(g,a,1);return A}for(var g=this,h=sa(this,a.T,this.X,this.b.g),m="",l=e(),
k=kc[l],p="",w=(this.style!=$b?lc:mc)[k[0]],v=k.length-1,r=nc,t,u=1;u<=v;u++){var y="";t=k[u];if(void 0!==t&&!(t&G&&this.style==jc)){var C=t&oc;if(C){var S=t&dc;S?r=S:t|=r;t&pc||(t|=1==u?qc:rc);C&H?y=d(t):C&gc?y=c((t&sc)>>8,t):C&tc&&(y=(l>>3&7).toString());if(!y||!y.length){p="INVALID";break}0<p.length&&(p+=",");p+=y||"???"}}}return this.K("%s %-9s%s %-7s %s\n",h,m,t&uc?"*":" ",w,p)};
var jc=8080,$b=8086,lc="NONE ACI ADC ADD ADI ANA ANI CALL CC CM CNC CNZ CP CPE CPO CZ CMA CMC CMP CPI DAA DAD DCR DCX DI EI HLT IN INR INX JMP JC JM JNC JNZ JP JPE JPO JZ LDA LDAX LHLD LXI MOV MVI NOP ORA ORI OUT PCHL POP PUSH RAL RAR RET RC RM RNC RNZ RP RPE RPO RZ RLC RRC RST SBB SBI SHLD SPHL STA STAX STC SUB SUI XCHG XRA XRI XTHL".split(" "),mc="NONE ADC ADC ADD ADD AND AND CALL CALLC CALLS CALLNC CALLNZ CALLNS CALLP CALLNP CALLZ NOT CMC CMP CMP DAA ADD DEC DEC CLI STI HLT IN INC INC JMP JC JS JNC JNZ JNS JP JNP JZ MOV MOV MOV MOV MOV MOV NOP OR OR OUT JMP POP PUSH RCL RCR RET RETC RETS RETNC RETNZ RETNS RETP RETNP RETZ ROL ROR RST SBB SBB MOV MOV MOV MOV STC SUB SUB XCHG XOR XOR XCHG".split(" "),
cc=6,ac="B C D E H L M A BC DE HL SP PC PS PSW".split(" "),dc=15,oc=240,sc=3840,pc=61440,nc=0,F=1,ec=2,fc=3,gc=16,H=32,bc=64,tc=128,I=1792|gc|F,J=0|gc|F,K=256|gc|F,L=512|gc|F,M=768|gc|F,N=1024|gc|F,O=1280|gc|F,P=cc<<8|gc|F|bc,vc=2048|gc|fc,wc=2304|gc|fc,Q=2560|gc|fc,xc=2816|gc|fc,yc=3584|gc|fc,rc=4096,qc=8192,G=16384,uc=32768,kc=[[45],[42,vc,H],[71,vc|bc,I|G],[29,vc],[28,J],[22,J],[44,J,H],[63],[45,uc],[21,Q|G,vc],[40,I|G,vc|bc],[23,vc],[28,K],[22,K],[44,K,H],[64],[45,uc],[42,wc,H],[71,wc|bc,I|G],
[29,wc],[28,L],[22,L],[44,L,H],[52],[45,uc],[21,Q|G,wc],[40,I|G,wc|bc],[23,wc],[28,M],[22,M],[44,M,H],[53],[45,uc],[42,Q,H],[68,51|bc,Q|G],[29,Q],[28,N],[22,N],[44,N,H],[20],[45,uc],[21,Q|G,Q],[41,Q|G,51|bc],[23,Q],[28,O],[22,O],[44,O,H],[16,I|G],[45,uc],[42,xc,H],[70,51|bc,I|G],[29,xc],[28,P],[22,P],[44,P,H],[72],[45,uc],[21,Q|G,xc],[39,I|G,51|bc],[23,xc],[28,I],[22,I],[44,I,H],[17],[43,J,J],[43,J,K],[43,J,L],[43,J,M],[43,J,N],[43,J,O],[43,J,P],[43,J,I],[43,K,J],[43,K,K],[43,K,L],[43,K,M],[43,K,
N],[43,K,O],[43,K,P],[43,K,I],[43,L,J],[43,L,K],[43,L,L],[43,L,M],[43,L,N],[43,L,O],[43,L,P],[43,L,I],[43,M,J],[43,M,K],[43,M,L],[43,M,M],[43,M,N],[43,M,O],[43,M,P],[43,M,I],[43,N,J],[43,N,K],[43,N,L],[43,N,M],[43,N,N],[43,N,O],[43,N,P],[43,N,I],[43,O,J],[43,O,K],[43,O,L],[43,O,M],[43,O,N],[43,O,O],[43,O,P],[43,O,I],[43,P,J],[43,P,K],[43,P,L],[43,P,M],[43,P,N],[43,P,O],[26],[43,P,I],[43,I,J],[43,I,K],[43,I,L],[43,I,M],[43,I,N],[43,I,O],[43,I,P],[43,I,I],[3,I|G,J],[3,I|G,K],[3,I|G,L],[3,I|G,M],[3,
I|G,N],[3,I|G,O],[3,I|G,P],[3,I|G,I],[2,I|G,J],[2,I|G,K],[2,I|G,L],[2,I|G,M],[2,I|G,N],[2,I|G,O],[2,I|G,P],[2,I|G,I],[73,I|G,J],[73,I|G,K],[73,I|G,L],[73,I|G,M],[73,I|G,N],[73,I|G,O],[73,I|G,P],[73,I|G,I],[66,I|G,J],[66,I|G,K],[66,I|G,L],[66,I|G,M],[66,I|G,N],[66,I|G,O],[66,I|G,P],[66,I|G,I],[5,I|G,J],[5,I|G,K],[5,I|G,L],[5,I|G,M],[5,I|G,N],[5,I|G,O],[5,I|G,P],[5,I|G,I],[76,I|G,J],[76,I|G,K],[76,I|G,L],[76,I|G,M],[76,I|G,N],[76,I|G,O],[76,I|G,P],[76,I|G,I],[46,I|G,J],[46,I|G,K],[46,I|G,L],[46,I|G,
M],[46,I|G,N],[46,I|G,O],[46,I|G,P],[46,I|G,I],[18,I|G,J],[18,I|G,K],[18,I|G,L],[18,I|G,M],[18,I|G,N],[18,I|G,O],[18,I|G,P],[18,I|G,I],[58],[50,vc],[34,51],[30,51],[11,51],[51,vc],[4,I|G,H|F],[65,tc],[62],[54],[38,51],[30,51|uc],[15,51],[7,51],[1,I|G,H|F],[65,tc],[57],[50,wc],[33,51],[48,H|F,I|G],[10,51],[51,wc],[74,I|G,H|F],[65,tc],[55],[54,uc],[31,51],[27,I|G,H|F],[8,51],[7,51|uc],[67,I|G,H|F],[65,tc],[61],[50,Q],[37,51],[78,xc|bc|G,Q|G],[14,51],[51,Q],[6,I|G,H|F],[65,tc],[60],[49,Q],[36,51],[75,
Q|G,wc|G],[13,51],[7,51|uc],[77,I|G,H|F],[65,tc],[59],[50,yc],[35,51],[24],[12,51],[51,yc],[47,I|G,H|F],[65,tc],[56],[69,xc|G,Q|G],[32,51],[25],[9,51],[7,51|uc],[19,I|G,H|F],[65,tc]];
function E(a,b,c){D.call(this,a,b,c);this.ia=c.addr;this.size=c.size;this.type=c.type||jb.NONE;this.width=c.width||8;this.values=c.values||Array(this.size);this.l=Math.pow(2,this.width)-1;this.f=!1;switch(this.type){case jb.NONE:this.$=this.m;this.ca=this.h;break;case jb.Sa:this.$=this.Ka;this.ca=this.h;break;case jb.va:this.$=this.Ka,this.ca=this.kb}}n(E,D);E.prototype.m=function(){return this.l};E.prototype.Ka=function(a){return this.values[a]};E.prototype.h=function(){};
E.prototype.kb=function(a,b){this.values[a]=b;this.f=!0};var jb={NONE:0,Sa:1,va:2};function zc(a,b,c){E.call(this,a,b,c)}n(zc,E);var Ac={NONE:0,Gg:1,bb:2};
function Bc(a,b,c){D.call(this,a,b,c);this.time=fb(this,rb);this.H=this.w=this.da=null;this.pa=z(this,"drag",!1);this.U=z(this,"scroll",!1);this.f=!1;if(a=this.W[Cc]){b=this.S.location;this.ra=b[0];this.sa=b[1];this.c=b[2];this.j=b[3];this.l=b[4]||1;this.s=b[5]||1;this.ka=b[6]||a.naturalWidth||this.c;this.oa=b[7]||a.naturalHeight||this.j;this.Z=b[8]||0;this.aa=b[9]||0;this.ga=b[10]||0;this.la=b[11]||0;(this.b=this.S.map)?(this.o=this.b.length,this.h=this.b[0].length):(this.h=this.l,this.o=this.s,
this.l=this.s=0);this.ea=z(this,"hexagonal",!1);this.a=z(this,"buttonDelay",0);this.L=this.c/(this.h+this.h*this.l)|0;this.N=this.j/(this.o+this.o*this.s)|0;this.ha=this.L*this.l|0;this.O=this.N*this.s|0;this.i=this.u=-1;Dc(this,a);Ec(this,a);if(this.time){var d=this;this.a&&(this.Y=Fc(this.time,"timerInputRelease",function(){0>d.i&&0>d.u&&Gc(d,-1,-1)}));this.b&&(this.a&&(this.qa=Fc(this.time,"timerKeyRelease",function(){Hc(d)})),this.g=0,this.m=[],Ic(this))}this.I=this.V=-1}}n(Bc,D);
Bc.prototype.za=function(a,b){var c=this;switch(a){case Jc:b.onclick=function(){c.da&&c.da()};break;case Kc:b.onclick=function(){c.w&&c.w()}}D.prototype.za.call(this,a,b)};function Lc(a,b){a.H=b}function Mc(a){a.a?Nc(a.time,a.qa,a.a):Hc(a)}
function Ic(a){var b=document;b.addEventListener("keydown",function(c){c=c||window.event;if(document.activeElement==a.W[Jc]){var d=c.which||c.keyCode,e=Oc[d],g=!1;e&&(g=Pc(a,e));a.J(x.Qa+x.Pa,"onKeyDown(keyCode=%#04x): %5.2f (%s)\n",d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()}});b.addEventListener("keypress",function(c){c=c||window.event;var d=c.which||c.charCode,e=String.fromCharCode(d),g=!1;e&&(g=Pc(a,e));a.J(x.Qa+x.Pa,"onKeyPress(charCode=%#04x): %5.2f (%s)\n",d,Date.now()/
1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()});b.addEventListener("keyup",function(c){c=c||window.event;document.activeElement==a.W[Jc]&&a.J(x.Qa+x.Pa,"onKeyUp(keyCode=%#04x): %5.2f (ignored)\n",c.which||c.keyCode,Date.now()/1E3%60)})}
function Dc(a,b){b.addEventListener("mousedown",function(c){if(!a.f){var d=a.W[Jc];if(d){var e=window.scrollX,g=window.scrollY;d.focus();window.scrollTo(e,g)}c.button||Qc(a,b,Rc,c)}});b.addEventListener("mousemove",function(c){a.f||Qc(a,b,Sc,c)});b.addEventListener("mouseup",function(c){a.f||c.button||Qc(a,b,Tc,c)});b.addEventListener("mouseout",function(c){a.f||(0>a.i?Qc(a,b,Sc,c):Qc(a,b,Tc,c))})}
function Ec(a,b){b.addEventListener("touchstart",function(c){a.U&&(a.f=!0);Qc(a,b,Rc,c)});b.addEventListener("touchmove",function(c){Qc(a,b,Sc,c)});b.addEventListener("touchend",function(c){Qc(a,b,Tc,c)})}function Pc(a,b){for(var c=0;c<a.b.length;c++)for(var d=a.b[c],e=0;e<d.length;e++)if(0<=d[e].split("|").indexOf(b))return a.g?16>a.m.length&&a.m.push(b):(a.g=1,Gc(a,e,c),Mc(a)),!0;a.J("unrecognized key '%s' (0x%02x)\n",b,b.charCodeAt(0));return!1}
function Hc(a){1==a.g?(a.g++,Gc(a,-1,-1),Mc(a)):(a.g=0,a.m.length&&Pc(a,a.m.shift()))}
function Qc(a,b,c,d){var e=-1,g=-1,h=!1,m;if(c<Tc){d=d||window.event;if(d.targetTouches&&d.targetTouches.length){var l=d.targetTouches[0].pageX;var k=d.targetTouches[0].pageY;h=1<d.targetTouches.length}else l=d.pageX,k=d.pageY;var p=m=0;var w=b;do isNaN(w.offsetLeft)||(m+=w.offsetLeft,p+=w.offsetTop);while(w=w.offsetParent);l=a.ka/b.offsetWidth*(l-m)|0;k=a.oa/b.offsetHeight*(k-p)|0;b=l-a.ra;var v=k-a.sa;p=m=!1;w=l>=a.Z&&l<a.Z+a.ga&&k>=a.aa&&k<a.aa+a.la;if(0<=b&&b<a.c&&0<=v+a.O||w)if(h||a.U||d.preventDefault(),
0<=b&&b<a.c&&0<=v&&v<a.j){p=!0;d=a.c/a.h|0;var r=a.j/a.o|0,t=b/d|0,u=v/r|0;!a.ea||u&1||(b-=d>>1,t=b/d|0,t==a.h-1&&(b=-1));r=u*r+(a.O>>1);b-=t*d+(a.ha>>1);v-=r;0<=b&&b<a.L&&0<=v&&v<a.N&&(e=t,g=u,m=!0)}}if(!h)if(c==Rc)a.i=l,a.u=k,p?(Gc(a,e,g),m&&a.a&&Nc(a.time,a.Y,a.a,!0)):w&&a.da&&a.da();else if(c==Sc)0<=a.i&&0<=a.u&&a.pa?Gc(a,e,g):a.H&&a.H(e,g);else if(c==Tc){if(c=a.a)c=a.time,e=a.Y,c=c.a&&0<e&&e<=c.b.length?0<=c.b[e-1].ba:!1;c||Gc(a,-1,-1);a.i=a.u=-1}else a.M("unrecognized action: "+c)}
function Gc(a,b,c){if(b!=a.I||c!=a.V)a.I=b,a.V=c}var Rc=1,Sc=2,Tc=3,Jc="power",Kc="reset",Cc="surface",Oc={8:"\b"};
function Uc(a,b,c){D.call(this,a,b,c);a=this.W[Vc];if(!a)throw Error("LED binding for '"+Vc+"' missing: '"+this.S.W[Vc]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.type=Ra(z(this,"type",Wc),Xc,Yc);this.b=Zc[this.type][0];this.g=Zc[this.type][1];this.width=z(this,"width",this.b);this.height=z(this,"height",this.g);this.c=z(this,"cols",1);this.o=this.c+z(this,"colsExtra",
0);this.N=z(this,"rows",1);this.w=this.N+z(this,"rowsExtra",0);this.Za=this.width*this.c;this.Va=this.height*this.N;this.j=$c("black",0);this.f=ad(this.S.color)||this.j;this.Z=$c(this.f,1,.25);this.Y=$c(this.f,1,2);this.i=ad(this.S.backgroundColor);this.aa=z(this,"fixed",!1);this.aa||(b.style.width="100%",b.style.height="auto");this.V=z(this,"hexagonal",!1);this.ea=z(this,"highlight",!0);this.H=z(this,"persistent",this.type<Yc);b.setAttribute("width",this.Za.toString());b.setAttribute("height",this.Va.toString());
b.style.backgroundColor=this.j;a.appendChild(b);this.U=b.getContext("2d");if(this.h=document.createElement("canvas"))this.h.width=this.O=this.b*this.c,this.h.height=this.l=this.g*this.N,this.a=this.h.getContext("2d");this.ha=(this.w+1)*this.o*4;this.buffer=Array(this.ha);this.ga=this.c<this.o?4*(this.o-this.c):0;this.s=this.u=!1;this.m=this.L=0;this.I=-1;var d=this;(this.time=fb(this,rb))&&bd(this.time,function(e){cd(d,!1,e)})}n(Uc,D);
function dd(a){for(var b=a.buffer,c=0;c<b.length;c+=4){var d=a,e=b,g=c;e[g]=d.type<Yc?ed:" ";e[g+1]=d.f==d.j?null:d.f;e[g+2]=0;e[g+3]=fd}a.s=a.u=!0;cd(a,!0)}function gd(a){a.i?(a.a.fillStyle=a.i,a.a.fillRect(0,0,a.O,a.l)):a.a.clearRect(0,0,a.O,a.l)}
function cd(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.s||b){if(a.type<Yc){var d=0;if(!a.H||b)gd(a);else if(a.m){d=a.c-a.m;var e=a.b*d;a.a.drawImage(a.h,a.b*a.m,0,e,a.l,0,0,e,a.l)}for(var g=e=0;g<a.w;g++){for(var h=0;h<a.c;h++){var m=a.buffer[e],l=a.buffer[e+1]||a.j,k=a.ea&&e==a.I;if(a.buffer[e+3]&fd||k||b){if(h>=d)a:{var p=a,w=m;m=l;var v=h;l=g;var r=k;v=void 0===v?0:v;l=void 0===l?0:l;r=void 0===r?!1:r;var t=0;if(p.V&&!(l&1)&&(t=p.b>>1,v==p.c-1))break a;if(m&&m!=p.f){r=r?$c(m,1,2):m;var u=$c(m,
1,.25)}else r=r?p.Y:p.f,u=p.Z;m=!1;w=w?r:u;r==p.j&&(w=p.i,m=!0);r=v*p.b+t;u=l*p.g;p.H&&(v=v*p.b+t,l*=p.g,p.i?(p.a.fillStyle=p.i,p.a.fillRect(v,l,p.b,p.g)):p.a.clearRect(v,l,p.b,p.g));p.a.fillStyle=w;l=hd[p.type];3==l.length?(p.a.beginPath(),p.a.arc(r+l[0],u+l[1],l[2],0,2*Math.PI),m?(p.a.globalCompositeOperation="destination-out",p.a.fill(),p.a.globalCompositeOperation="source-over"):p.a.fill()):p.a.fillRect(r+l[0],u+l[1],l[2],l[3])}a.buffer[e+3]=k?a.buffer[e+3]|fd:a.buffer[e+3]&~fd}e+=4}e+=a.ga}a.m=
0}else{b="";for(d=0;d<a.buffer.length;d+=4)b+=a.buffer[d]||" ",a.buffer[d+3]&id&&(b+=".");gd(a);for(g=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;h=a;k=e;p=g;k=void 0===k?0:k;p=void 0===p?0:p;if(l=jd[l])for(m=0;m<l.length;m++)if(v=h,t=kd[l[m]]){w=(void 0===k?0:k)*v.b;r=(void 0===p?0:p)*v.g;v.a.fillStyle=v.f;v.a.beginPath();if(3==t.length)v.a.arc(w+t[0],r+t[1],t[2],0,2*Math.PI);else for(u=0;u<t.length;u+=2)u?v.a.lineTo(w+t[u],r+t[u+1]):v.a.moveTo(w+t[u],r+t[u+1]);v.a.closePath();v.a.fill()}if(++e==
a.c&&(e=0,++g==a.w))break}}a.U.globalCompositeOperation=a.i&&a.f!=a.j?"source-over":"copy";a.U.drawImage(a.h,0,0,a.O,a.l,0,0,a.Za,a.Va);a.s=!1;a.I=-1}else a.H||a.u||(!c||!a.L||c-a.L>=(1E3/60|0))&&dd(a);a.u=!1;c&&(a.L=c)}function ad(a){return(a=a||void 0)&&ld[a]||a}
function $c(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=ld[a]||a;var e=a;var g=16;var h=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);h||(g=10,h=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(h){for(e=1;e<h.length;e++)d[e-1]=Number.parseInt(h[e],g);d.length=e-1;g=!0}else g=!1;if(g){a="rgba(";for(g=0;3>g;g++)h=Math.round(d[g]*c),h=0>h?0:255<h?255:h,a+=h+",";a+=(g<d.length?d[g]:b)+")"}}return a}
var Xc=0,Wc=1,Yc=3,Vc="container",ld={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",
darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",
goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",
lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",
olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",
slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},ed=0,id=1,fd=128,md={},hd=(md[Xc]=[4,4,4],md[Wc]=[16,16,14],md[2]=[2,2,28,28],md),Zc=[[8,8],[32,32],[32,32],[96,128]],kd={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,
91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},jd={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};
function nd(a,b,c){c.type=jb.va;E.call(this,a,b,c);a=this.S.bus;if(this.a=eb(this,this.S.bus))ib(this.a,c.addr,c.size,jb.va,this);else throw Error(this.K("unable to find bus '%s'",a));}n(nd,E);
function od(a,b,c){c.type=jb.Sa;E.call(this,a,b,c);c.revision&&(this.status="revision "+c.revision+" "+this.status);this.i=fb(this,pd);ib(this.i,c.addr,c.size,c.type,this);if(R[rd]&&this.W[Oa]){var d=this;c=R[rd];this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.g=this.values.length/this.b|0;this.c=new c(a,b+"LEDs",{"class":"LED",bindings:{container:Na(this)},type:c.Jg.Hg,cols:this.b,rows:this.g,color:z(this,"colorROM","green"),backgroundColor:z(this,"backgroundColorROM","black"),
persistent:!0}),dd(this.c);this.j=new Bc(a,b+"Input",{"class":"Input",location:[0,0,this.c.Za,this.c.Va,this.b,this.g],bindings:{surface:Na(this)}});this.o=Pa(this);Lc(this.j,function(e,g){if(d.a){var h=d.o;0<=e&&0<=g&&(e=g*d.b+e,h=d.a.Ng(d.values[e],d.ia+e));ab(d,Qa,h)}})}}n(od,E);od.prototype.da=function(){this.a||(this.a=fb(this,qb))};
od.prototype.Ka=function(a){if(this.c){var b=R[rd],c=this.c,d=b.Ig.Fg;b=b.Dg.Eg;b=(void 0===b?0:b)&129;var e=4*((a/this.b|0)*c.o+a%this.b);if(e<=c.buffer.length-4){if(c.buffer[e]!==d||(c.buffer[e+3]&129)!==b)c.buffer[e]=d,c.buffer[e+3]=c.buffer[e+3]&-130|b|fd,c.s=!0;c.I=e;c.u=!0;c.m=0}}return this.values[a]};var Oa="array",Qa="cellDesc";
function sd(a,b,c){D.call(this,a,b,c);this.la=z(this,"cyclesMinimum",1E5);this.sa=z(this,"cyclesMaximum",3E6);this.U=Ra(z(this,"cyclesPerSecond",65E4),this.la,this.sa);this.I=Ra(z(this,"yieldsPerSecond",td),30,120);this.Aa=Ra(z(this,"yieldsPerUpdate",ud),1,this.I);this.ga=(this.w=z(this,"clockByFrame",120>=this.U))||z(this,"requestAnimationFrame",!0);this.pa=this.qa=this.Z=1;this.ka=this.U/1E4/100;this.h=this.m=this.ka*this.Z;this.s=0;this.aa=Math.round(1E3/this.I);this.ea=[];this.u=[];this.b=[];
this.ha=[];this.a=this.L=this.l=!1;this.H=this.g=0;this.Ca=this.yg.bind(this);this.Ba=this.cb.bind(this);this.oa=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);if(this.w)this.f=this.ra=0;else{var d=this;Fc(this,"timerYield",function(){vd(d)},this.aa)}this.V=this.O=this.j=0;wd(this)||xd(this,this.pa)}n(sd,D);function bd(a,b){a.ea.push(b)}f=sd.prototype;
f.za=function(a,b){var c=this;switch(a){case yd:b.onclick=function(){c.a?Ob(c):c.start()};break;case zd:b.onclick=function(){Wb(c)};break;case Ad:b.addEventListener("mousedown",function(){c.l=!0}),b.addEventListener("mouseup",function(){wd(c);c.l=!1}),b.addEventListener("mousemove",function(){c.l&&wd(c)}),b.addEventListener("change",function(){c.l=!0;wd(c);c.l=!1})}D.prototype.za.call(this,a,b)};
function Fc(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,vb:c,Fa:d,ba:-1});0<=d&&Nc(a,e,d);return e}f.cb=function(a){if(this.w){if(!this.a)return;Bd(this);try{this.L=!1;do Cd(this,Dd(this,Ed(this,Fd(this))));while(this.a&&!this.L)}catch(c){this.M(c.message);Ob(this);return}Gd(this)}for(var b=0;b<this.ea.length;b++)this.ea[b](a);this.a&&this.ga&&this.oa(this.Ba)};function Hd(a){var b=a.h/a.ka;if(!b||b>a.Z)b=a.Z;a.Ea=a.U/a.I*b;a.qa=b}
function Ed(a,b){a.O=a.j=b;if(!a.u.length)return a.j=0,a.O;for(var c=0;0<a.j;)c<a.u.length?b=a.u[c++](b)||1:c=b=0,a.j-=b;return a.O-a.j}function Id(a,b){var c=Date.now();b()&&(a.N+=Date.now()-c)}function Dd(a,b){b=void 0===b?a.O-a.j:b;if(a.w){if(!a.a){if(a.f)for(var c=0;c<a.u.length;c++)a.u[c](-1);a.f=b}a.f-=b;1>a.f&&vd(a)}a.O=a.j=0;a.Y+=b;a.V+=b;a.a||(a.V=0);return b}function Jd(a,b){return Math.ceil(a.U*a.qa/1E3*(void 0===b?1E3:b))}
function Fd(a,b){b=void 0===b?0:b;if(b){var c=b;a.f+=b}else for(c=a.f,1>c&&(c=a.f+=a.ra),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.ba)&&c>d.ba&&(c=d.ba)}return c}function Kd(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}f.da=function(){Ld(this)};function Wb(a,b){a.a?a.M("already running"):a.g?Ob(a):Md(a,b)}function vd(a){a.L=!0;var b=a.s,c=Jd(a);c>=a.I?a.s++:a.s+=Math.ceil(a.I/c);a.s>=a.Aa&&b<a.Aa&&Ld(a);a.s>=a.I&&(a.s=0)}
f.yg=function(){this.H=0;if(this.a){Bd(this);try{this.L=!1;do{for(var a=Jd(this,this.aa),b=this.b.length;0<b;b--){var c=this.b[b-1];!(0>c.ba)&&a>c.ba&&(a=c.ba)}Cd(this,Dd(this,Ed(this,a)))}while(this.a&&!this.L)}catch(d){this.M(d.message);Ob(this);return}this.a&&(this.H=setTimeout(this.Ca,Gd(this)),this.ga||this.cb())}};function wd(a){var b=a.W[Ad];return b?(xd(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.sa-a.la)+a.la)/a.U),!0):!1}
function xd(a,b){void 0!==b&&(!a.l&&0<a.h&&a.h<.9*a.m&&(b=a.pa),a.Z=b,b=a.ka*a.Z,a.m!=b&&(a.m=b,ab(a,Nd,Kd(a.m))),a.h=a.m);a.w&&(a.ra=1E6*a.h/60+1E-8,a.f=0);a.V=0;a.c=a.i=0;Hd(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Fa&&Nc(a,b,c.Fa,!0)}}function Nc(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.ba)&&(c=Jd(a,c),a.a&&(c+=Dd(a)),b.ba=c)}function Bd(a){Hd(a);a.Y=0;a.N=0;a.o=Date.now();a.c||(a.c=a.o);if(a.i){var b=a.o-a.i;b>a.aa&&(a.c+=b,a.c>a.o&&(a.c=a.o))}}
function Gd(a){a.i=Date.now();a.N&&(a.c+=a.N,a.o+=a.N);var b=a.aa;a.Y&&(b=Math.round(b*a.Y/a.Ea));b-=a.i-a.o;var c=a.i-a.c;c&&(a.h=a.V/(10*c)/100);0>b?(-1E3>b&&(a.c-=b),b=0):a.h<a.m&&(b=0);a.i+=b;a.J(x.sb,"after running %d cycles, resting for %dms\n",a.Y,b);return b}f.start=function(){if(this.a||this.g)return!1;this.H&&(clearTimeout(this.H),this.H=0);this.a=!0;this.c=this.i=0;Ld(this,!0);this.w||(this.H=setTimeout(this.Ca,0));this.ga&&this.oa(this.Ba);return!0};
function Md(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,Cd(a,Dd(a,Ed(a,Fd(a,1)))),Ld(a),a.g&&setTimeout(function(){Md(a,0)},0)))}function Ob(a){return a.g?(a.g=0,Ld(a,!0),!0):a.a?(a.a=!1,Dd(a),Ld(a,!0),!0):!1}function Ld(a,b){b&&(a.a?(a.M("starting with "+Kd(a.m)+" target"),b=!1):a.M("stopping"));ab(a,yd,a.a?"Halt":"Run");ab(a,zd,a.g?"Stop":"Step");a.l||ab(a,Nd,a.a&&a.h?Kd(a.h):"Stopped");for(var c=0;c<a.ha.length;c++)a.ha[c](b)}
function Cd(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.ba||(d.ba-=b,0>=d.ba&&(d.ba=-1,d.vb(),0<=d.Fa&&Nc(a,c,d.Fa)))}}var yd="run",Nd="speed",zd="step",Ad="throttle",td=120,ud=60;function Od(a,b,c){c.type=Ac.bb;E.call(this,a,b,c);a=this.S.bus;if(this.a=eb(this,a))ib(this.a,c.addr,c.size,Ac.bb,this);else throw Error(this.K("unable to find bus '%s'",a));}n(Od,zc);f=Od.prototype;f.Db=function(a){this.J(x.ja,"inStatus0(%d): %#02x\n",a,0);return 0};
f.Eb=function(a){this.J(x.ja,"inStatus1(%d): %#02x\n",a,0);return 0};f.Fb=function(a){this.J(x.ja,"inStatus2(%d): %#02x\n",a,0);return 0};f.Cb=function(a){var b=this.b>>8-this.c&255;this.J(x.ja,"inShiftResult(%d): %#02x\n",a,b);return b};f.pg=function(a,b){this.J(x.ja,"outShiftCount(%d): %#02x\n",a,b);this.c=b};f.rg=function(a,b){this.J(x.ja,"outSound1(%d): %#02x\n",a,b)};f.qg=function(a,b){this.J(x.ja,"outShiftData(%d): %#02x\n",a,b);this.b=b<<8|this.b>>8};
f.sg=function(a,b){this.J(x.ja,"outSound2(%d): %#02x\n",a,b)};f.tg=function(a,b){this.J(x.ja,"outWatchDog(%d): %#02x\n",a,b)};f.Ka=function(a){var b=255;a=this.ia+a;var c=Pd[a];c&&(b=c.call(this,a));return b};f.kb=function(a,b){a=this.ia+a;var c=Qd[a];c&&c.call(this,a,b)};var Pd={0:Od.prototype.Db,1:Od.prototype.Eb,2:Od.prototype.Fb,3:Od.prototype.Cb},Qd={2:Od.prototype.pg,3:Od.prototype.rg,4:Od.prototype.qg,5:Od.prototype.sg,6:Od.prototype.tg};
function Rd(a,b,c){D.call(this,a,b,c);var d=this;this.ka=Wa("Gecko/");this.u=c.screenWidth;this.l=c.screenHeight;this.V=c.bufferAddr;this.ug=c.bufferRAM;this.Z=(a=c.bufferFormat)&&Sd[a.toUpperCase()]||Td;this.N=c.bufferCols;this.O=c.bufferRows;this.ma=c.cellWidth||1;this.fa=c.cellHeight||1;this.Y=c.bufferBits||1;this.wg=c.bufferLeft||0;if(this.b=c.bufferRotate)this.b=this.b%360,0<this.b&&(this.b-=360),-90!=this.b&&(this.J("unsupported buffer rotation: %d\n",this.b),this.b=0);this.aa=c.interruptRate;
this.Ba=c.refreshRate||60;b=document.createElement("canvas");b.setAttribute("class","pcjs-screen");b.setAttribute("width",c.screenWidth);b.setAttribute("height",c.screenHeight);b.style.backgroundColor=c.screenColor;var e=b.getContext("2d");(a=this.W[Ud.Oa])?a.appendChild(b):this.J("unable to find display element: %s\n",Ud.Oa);a&&Wa("MSIE")&&(a.onresize=function(l,k,p,w){return function(){k.style.height=(l.clientWidth*w/p|0)+"px"}}(a,b,c.screenWidth,c.screenHeight),a.onresize());var g=+(c.aspect||
Ha().aspect);a&&g&&.3<=g&&3.33>=g&&(Xa(function(l,k,p){return function(){k.style.height=(l.clientWidth/p|0)+"px"}}(a,b,g)),window.onresize());if(a){var h=document.createElement("textarea");h.setAttribute("class","pcjs-overlay");Wa("iOS")&&(h.setAttribute("autocorrect","off"),h.setAttribute("autocapitalize","off"),h.style.fontSize="16px");a.appendChild(h)}this.s=b;this.h=e;this.qa=h||b||null;this.Ib=this.u;this.Jb=this.l;this.ha=this.u/this.N|0;this.ga=this.l/this.O|0;1<this.fa&&(this.O++,this.Hb=
0,this.la=!1);h=c.smoothing;(b=Ha().smoothing)&&(h="true"==b);this.oa=h;this.Ca=La(this.h,"imageSmoothingEnabled");if(this.f=c.screenRotate)this.f=this.f%360,0<this.f&&(this.f-=360),-90!=this.f?(this.J("unsupported screen rotation: %d\n",this.f),this.f=0):(this.h.translate(0,this.l),this.h.rotate(this.f*Math.PI/180),this.h.scale(this.l/this.u,this.u/this.l));if(this.c=a)if(c=La(a,"requestFullscreen")||La(a,"requestFullScreen")){this.c.Ta=a[c];if(c=La(document,"on","fullscreenchange")){var m=La(document,
"fullscreenElement")||La(document,"fullScreenElement");document.addEventListener(c,function(){Vd(d,null!=document[m])},!1)}(c=La(document,"on","fullscreenerror"))&&document.addEventListener(c,function(){Vd(d)},!1)}this.o=fb(this,pd);this.a=fb(this,qb);Wd(this);this.time=fb(this,rb);this.Ea=Fc(this.time,this.ua,function(){var l=!0;d.aa&&(120==d.aa?d.Aa&1?(Xd(d.a,2),l=!1):Xd(d.a,1):Xd(d.a,4));if(l&&d.I&&d.m){var k=d.o,p=d.V,w=d.m,v=!0,r=p>>>k.c;for(p=k.a-(p&k.j);0<w&&r<k.b.length;){var t=k.b[r];t.f?
(t.f=!1,t=!0):t=!1;t&&(v=!1);w-=p;p=k.a;r++}v&&(l=!1)}Nc(d.time,d.Ea,1E3/Math.max(d.Ba,d.aa));d.Aa++;if(l)if(1<d.ma)switch(d.Z){case Yd:l=d.V;k=-1;w=0;v=60==d.xg?2:5;p=r=0;for(t=-1;w<d.O;){var u=0,y=l,C=k,S=d.N;for(C!=Zd&&(S>>=1);;){var A=d.o.$(y++);if((A&$d)==$d){var B=d.o.$(y++);k=B&ae;l=(B&be)<<8|d.o.$(y);l+=B&ce?de:ee;break}if(u<S)d.U[u++]=A;else break}if(v)v--;else{for(;u<d.U.length;)d.U[u++]=0;if(0<=C)for(y=d.I&&d.g[r]==S,d.g[r++]=S,S=0;S<u;S++){A=d.U[S];if(!y||A!==d.g[r]){d.g[t=r]=A;B=d;var aa=
d.ea;var da=A&127;if(A=B.Gb[C][A&128?1:0]){var Jb=(da&15)*A.ma,hc=(da>>4)*A.fa,qd=A.ma,ic=A.fa;if(aa){var wa=S*B.ma;var Z=w*B.fa;var na=B.ma;da=B.fa}else wa=S*B.ha,Z=w*B.ga,na=B.ha,da=B.ga;A.ma>B.ma&&(wa*=2,na*=2);A.fa>B.fa&&(C==fe&&(hc+=B.fa),ic=B.fa);aa?aa.drawImage(A.canvas,Jb,hc,qd,ic,wa,Z,na,da):B.h.drawImage(A.canvas,Jb,hc,qd,ic,wa,Z,na,da)}p++}r++}w++}}d.I=!0;d.la&&1==p&&(d.g[t]=-1,p=0);d.la=!1;p&&d.ea&&d.h.drawImage(d.j,0,d.Hb,d.i,d.w-d.fa,0,0,d.Ib,d.Jb)}else{v=d.V;r=v+d.m;u=t=p=0;l=d.i;C=
0;k=d.w;y=w=0;S=d.Y;B=(1<<S)-1;d.wg&&(S=-S,y=16+S);for(;v<r;){aa=d.o.$(v);if(d.I&&aa===d.g[p])t+=d.sa;else{d.g[p]=aa;(A=y)&&(aa=aa>>8|(aa&255)<<8);t<l&&(l=t);for(Jb=d.sa;Jb--;)na=aa>>A&B,da=d.pa,Z=t++,wa=na,na=d.b?(da.height-Z-1)*da.width+u:Z+u*da.width,wa&&d.Z==ge&&(208<=Z&&236>Z?wa=d.L+he:28<=Z&&72>Z&&(wa=d.L+ie)),Z=d.H[wa],na*=Z.length,da.data[na]=Z[0],da.data[na+1]=Z[1],da.data[na+2]=Z[2],da.data[na+3]=Z[3],A+=S;t>C&&(C=t);u<k&&(k=u);u>=w&&(w=u+1)}v+=2;p++;if(t>=d.i&&(t=0,u++,u>d.w))break}d.I=
!0;l<d.i&&(v=C-l,w-=k,d.b&&(r=l,p=v,l=k,v=w,k=d.i-(r+p),w=p),d.ea.putImageData(d.pa,0,0,l,k,v,w),d.h.drawImage(d.j,0,0,d.j.width,d.j.height,0,0,d.u,d.l))}});Nc(this.time,this.Ea,1E3/Math.max(this.Ba,this.aa));this.Aa=0}n(Rd,D);
function Wd(a){a.i=a.N*a.ma;a.w=a.O*a.fa;var b=a.i,c=a.w;a.b&&(b=a.w,c=a.i);a.m=0;if(!a.ug&&(a.m=(a.i*a.Y>>3)*a.w,!ib(a.o,a.V,a.m,jb.va)))return;a.m?(a.pa=a.h.createImageData(b,c),a.sa=16/a.Y|0,je(a,a.m>>1)):je(a,(a.N+1)*a.O);a.j=document.createElement("canvas");a.j.width=b;a.j.height=c;a.ea=a.j.getContext("2d");a.Gb={};a.L=1<<a.Y;a.H=Array(a.L+ke);a.H[0]=[0,0,0,255];a.H[1]=[255,255,255,255];a.Z==ge&&(a.H[a.L+he]=[255,255,0,255],a.H[a.L+ie]=[0,255,0,255]);a.Z==Yd&&(a.xg=60,a.U=Array(a.N));a.Ca&&(a.h[a.Ca]=
null==a.oa?!1:a.oa)}Rd.prototype.Ta=function(){var a=!1;if(this.c){if(this.c.Ta){a="100%";if(screen&&screen.width&&screen.height){var b=screen.width/screen.height,c=this.u/this.l;b>c&&(a=Math.round(c/b*100)+"%")}this.ka?(this.s.style.width=a,this.s.style.width=a,this.s.style.display="block",this.s.style.margin="auto"):(this.c.style.width=a,this.c.style.height="auto");this.c.style.backgroundColor="black";this.c.Ta();a=!0}this.qa&&this.qa.focus()}return a};
function Vd(a,b){!b&&a.c&&(a.ka?a.s.style.width=a.s.style.height="":a.c.style.width=a.c.style.height="");a.J("notifyFullScreen(%b)\n",b)}function je(a,b){a.ra=b;a.I=!1;if(void 0===a.g||a.g.length!=a.ra)a.g=Array(a.ra)}var Ud={Oa:"container"},he=0,ie=1,ke=2,Td=0,ge=1,Yd=2,Sd={SI1978:ge,VT100:Yd},Zd=96,fe=0,$d=127,be=15,ce=16,ae=96,de=8192,ee=16384;Ud={Oa:"container"};
function le(a,b,c){D.call(this,a,b,c);this.u=this.l=this.j=this.i=this.h=this.g=this.f=this.b=0;this.v(this.Y);me(this,0);this.H=ne;this.U=[this.na,this.xd,this.Tf,this.gd,this.$c,this.Kc,this.Me,this.qf,this.na,this.Fc,this.ud,this.Rc,this.ad,this.Lc,this.Ne,this.xf,this.na,this.yd,this.Uf,this.hd,this.bd,this.Mc,this.Oe,this.mf,this.na,this.Gc,this.vd,this.Sc,this.cd,this.Nc,this.Pe,this.nf,this.na,this.zd,this.Qf,this.jd,this.dd,this.Oc,this.Qe,this.Ec,this.na,this.Hc,this.wd,this.Tc,this.ed,this.Pc,
this.Re,this.nc,this.na,this.Ad,this.Sf,this.kd,this.fd,this.Qc,this.Se,this.Vf,this.na,this.Ic,this.td,this.Uc,this.Zc,this.Jc,this.Le,this.oc,this.Kd,this.Ld,this.Md,this.Nd,this.Od,this.Pd,this.Qd,this.Jd,this.Sd,this.Td,this.Ud,this.Vd,this.Wd,this.Xd,this.Yd,this.Rd,this.$d,this.ae,this.be,this.ce,this.de,this.ee,this.fe,this.Zd,this.he,this.ie,this.je,this.ke,this.le,this.me,this.ne,this.ge,this.pe,this.qe,this.re,this.se,this.te,this.ue,this.ve,this.oe,this.xe,this.ye,this.ze,this.Ae,this.Be,
this.Ce,this.De,this.we,this.Fe,this.Ge,this.He,this.Ie,this.Je,this.Ke,this.Xc,this.Ee,this.Cd,this.Dd,this.Ed,this.Fd,this.Gd,this.Hd,this.Id,this.Bd,this.Vb,this.Wb,this.Xb,this.Yb,this.Zb,this.$b,this.ac,this.Ub,this.Nb,this.Ob,this.Pb,this.Qb,this.Rb,this.Sb,this.Tb,this.Mb,this.Xf,this.Yf,this.Zf,this.$f,this.ag,this.bg,this.cg,this.Wf,this.If,this.Jf,this.Kf,this.Lf,this.Mf,this.Nf,this.Of,this.Hf,this.dc,this.ec,this.fc,this.gc,this.hc,this.ic,this.jc,this.cc,this.gg,this.hg,this.ig,this.jg,
this.kg,this.lg,this.mg,this.fg,this.Ue,this.Ve,this.We,this.Xe,this.Ye,this.Ze,this.$e,this.Te,this.qc,this.rc,this.sc,this.tc,this.uc,this.vc,this.wc,this.pc,this.tf,this.df,this.od,this.hb,this.yc,this.jf,this.bc,this.yf,this.Gf,this.ib,this.sd,this.hb,this.Dc,this.Ia,this.Lb,this.zf,this.sf,this.ef,this.nd,this.bf,this.xc,this.kf,this.dg,this.Af,this.pf,this.ib,this.ld,this.Yc,this.lc,this.Ia,this.Pf,this.Bf,this.wf,this.ff,this.rd,this.og,this.Cc,this.lf,this.kc,this.Cf,this.vf,this.cf,this.qd,
this.eg,this.Ac,this.Ia,this.ng,this.Df,this.uf,this.gf,this.pd,this.Vc,this.zc,this.hf,this.af,this.Ef,this.rf,this.Rf,this.md,this.Wc,this.mc,this.Ia,this.Bc,this.Ff];this.a=this.N=0;a=this.V=fb(this,oe);b=this.mb.bind(this);a.da=this.da.bind(this);a.w=b;this.O=eb(this,this.S.busIO);this.I=eb(this,this.S.busMemory);if(this.time=fb(this,rb))this.time.u.push(this.Ab.bind(this)),this.time.ha.push(this.nb.bind(this));this.L=void 0;this.xa[Yb.pb]={get:this.Bb.bind(this),set:this.v.bind(this)}}n(le,D);
f=le.prototype;f.Ab=function(a){a=void 0===a?0:a;if(0>a)return this.N=0;try{pe(this,a)}catch(c){this.M(c.message),Ob(this.time)}if(0>=a){var b=this;Id(this.time,function(){b.M(b.toString())})}return this.a};function pe(a,b){a.a=0;for(a.N=b;a.a<=a.N;)a.U[T(a)].call(a)}
f.fb=function(a){if(a){var b;a=null;if(Ta(this)&&window)try{(b=window.localStorage.getItem(this.R))&&(a=JSON.parse(b))}catch(c){this.M(c.message)}if(b=a)if((b=b.stateCPU||b[0])&&b.length)if(a=b.shift(),2!==(a|0))this.J("saved state version mismatch: %3.2f\n",a);else try{this.c=b.shift()}catch(c){this.M("CPU state error: "+c.message)}else this.M("invalid saved state")}};f.da=function(a){void 0==a&&(a=!this.time.a)&&(this.c=0);a?this.time.start():Ob(this.time)};
f.mb=function(){this.M("reset");this.c=0;this.time.a||this.M(this.toString())};f.gb=function(){var a=[[],[],[]],b=a[0];b.push(2);b.push(this.c);if(Ta(this)){a=JSON.stringify(a);try{window.localStorage.setItem(this.R,a)}catch(c){this.M(c.message)}}};f.na=function(){this.a+=4};f.xd=function(){qe(this,U(this));this.a+=10};f.Tf=function(){re(this,se(this),this.b);this.a+=7};f.gd=function(){qe(this,se(this)+1);this.a+=5};f.$c=function(){this.f=te(this,this.f);this.a+=5};
f.Kc=function(){this.f=ue(this,this.f);this.a+=5};f.Me=function(){this.f=T(this);this.a+=7};f.qf=function(){var a=this.b<<1;this.b=a&255|a>>8;ve(this,a&256);this.a+=4};f.Fc=function(){var a;we(this,a=V(this)+se(this));ve(this,a>>8&256);this.a+=10};f.ud=function(){this.b=W(this,se(this));this.a+=7};f.Rc=function(){qe(this,se(this)-1);this.a+=5};f.ad=function(){this.g=te(this,this.g);this.a+=5};f.Lc=function(){this.g=ue(this,this.g);this.a+=5};f.Ne=function(){this.g=T(this);this.a+=7};
f.xf=function(){var a=this.b<<8&256;this.b=(a|this.b)>>1;ve(this,a);this.a+=4};f.yd=function(){xe(this,U(this));this.a+=10};f.Uf=function(){re(this,ye(this),this.b);this.a+=7};f.hd=function(){xe(this,ye(this)+1);this.a+=5};f.bd=function(){this.h=te(this,this.h);this.a+=5};f.Mc=function(){this.h=ue(this,this.h);this.a+=5};f.Oe=function(){this.h=T(this);this.a+=7};f.mf=function(){var a=this.b<<1;this.b=a&255|ze(this);ve(this,a&256);this.a+=4};
f.Gc=function(){var a;we(this,a=V(this)+ye(this));ve(this,a>>8&256);this.a+=10};f.vd=function(){this.b=W(this,ye(this));this.a+=7};f.Sc=function(){xe(this,ye(this)-1);this.a+=5};f.cd=function(){this.i=te(this,this.i);this.a+=5};f.Nc=function(){this.i=ue(this,this.i);this.a+=5};f.Pe=function(){this.i=T(this);this.a+=7};f.nf=function(){var a=this.b<<8;this.b=(ze(this)<<8|this.b)>>1;ve(this,a&256);this.a+=4};f.zd=function(){we(this,U(this));this.a+=10};
f.Qf=function(){var a=U(this),b=V(this);this.I.ca(a,b&255);this.I.ca(a+1,b>>8&255);this.a+=16};f.jd=function(){we(this,V(this)+1);this.a+=5};f.dd=function(){this.j=te(this,this.j);this.a+=5};f.Oc=function(){this.j=ue(this,this.j);this.a+=5};f.Qe=function(){this.j=T(this);this.a+=7};f.Ec=function(){var a=0,b=ze(this);if((this.o^this.s)&16&&Ae||9<(this.b&15))a|=6;if(b||154<=this.b)a|=96,b=Be;this.b=Ce(this,a);ve(this,b?256:0);this.a+=4};
f.Hc=function(){var a;we(this,a=V(this)+V(this));ve(this,a>>8&256);this.a+=10};f.wd=function(){we(this,De(this,U(this)));this.a+=16};f.Tc=function(){we(this,V(this)-1);this.a+=5};f.ed=function(){this.l=te(this,this.l);this.a+=5};f.Pc=function(){this.l=ue(this,this.l);this.a+=5};f.Re=function(){this.l=T(this);this.a+=7};f.nc=function(){this.b=~this.b&255;this.a+=4};f.Ad=function(){this.u=U(this)&65535;this.a+=10};f.Sf=function(){re(this,U(this),this.b);this.a+=13};
f.kd=function(){this.u=this.u+1&65535;this.a+=5};f.fd=function(){var a=V(this);re(this,a,te(this,W(this,a)));this.a+=10};f.Qc=function(){var a=V(this);re(this,a,ue(this,W(this,a)));this.a+=10};f.Se=function(){re(this,V(this),T(this));this.a+=10};f.Vf=function(){this.m|=256;this.a+=4};f.Ic=function(){var a;we(this,a=V(this)+this.u);ve(this,a>>8&256);this.a+=10};f.td=function(){this.b=W(this,U(this));this.a+=13};f.Uc=function(){this.u=this.u-1&65535;this.a+=5};
f.Zc=function(){this.b=te(this,this.b);this.a+=5};f.Jc=function(){this.b=ue(this,this.b);this.a+=5};f.Le=function(){this.b=T(this);this.a+=7};f.oc=function(){ve(this,ze(this)?0:256);this.a+=4};f.Kd=function(){this.a+=5};f.Ld=function(){this.f=this.g;this.a+=5};f.Md=function(){this.f=this.h;this.a+=5};f.Nd=function(){this.f=this.i;this.a+=5};f.Od=function(){this.f=this.j;this.a+=5};f.Pd=function(){this.f=this.l;this.a+=5};f.Qd=function(){this.f=W(this,V(this));this.a+=7};
f.Jd=function(){this.f=this.b;this.a+=5};f.Sd=function(){this.g=this.f;this.a+=5};f.Td=function(){this.a+=5};f.Ud=function(){this.g=this.h;this.a+=5};f.Vd=function(){this.g=this.i;this.a+=5};f.Wd=function(){this.g=this.j;this.a+=5};f.Xd=function(){this.g=this.l;this.a+=5};f.Yd=function(){this.g=W(this,V(this));this.a+=7};f.Rd=function(){this.g=this.b;this.a+=5};f.$d=function(){this.h=this.f;this.a+=5};f.ae=function(){this.h=this.g;this.a+=5};f.be=function(){this.a+=5};
f.ce=function(){this.h=this.i;this.a+=5};f.de=function(){this.h=this.j;this.a+=5};f.ee=function(){this.h=this.l;this.a+=5};f.fe=function(){this.h=W(this,V(this));this.a+=7};f.Zd=function(){this.h=this.b;this.a+=5};f.he=function(){this.i=this.f;this.a+=5};f.ie=function(){this.i=this.g;this.a+=5};f.je=function(){this.i=this.h;this.a+=5};f.ke=function(){this.a+=5};f.le=function(){this.i=this.j;this.a+=5};f.me=function(){this.i=this.l;this.a+=5};f.ne=function(){this.i=W(this,V(this));this.a+=7};
f.ge=function(){this.i=this.b;this.a+=5};f.pe=function(){this.j=this.f;this.a+=5};f.qe=function(){this.j=this.g;this.a+=5};f.re=function(){this.j=this.h;this.a+=5};f.se=function(){this.j=this.i;this.a+=5};f.te=function(){this.a+=5};f.ue=function(){this.j=this.l;this.a+=5};f.ve=function(){this.j=W(this,V(this));this.a+=7};f.oe=function(){this.j=this.b;this.a+=5};f.xe=function(){this.l=this.f;this.a+=5};f.ye=function(){this.l=this.g;this.a+=5};f.ze=function(){this.l=this.h;this.a+=5};
f.Ae=function(){this.l=this.i;this.a+=5};f.Be=function(){this.l=this.j;this.a+=5};f.Ce=function(){this.a+=5};f.De=function(){this.l=W(this,V(this));this.a+=7};f.we=function(){this.l=this.b;this.a+=5};f.Fe=function(){re(this,V(this),this.f);this.a+=7};f.Ge=function(){re(this,V(this),this.g);this.a+=7};f.He=function(){re(this,V(this),this.h);this.a+=7};f.Ie=function(){re(this,V(this),this.i);this.a+=7};f.Je=function(){re(this,V(this),this.j);this.a+=7};
f.Ke=function(){re(this,V(this),this.l);this.a+=7};f.Xc=function(){var a=this.c-1;this.a+=7;this.H|=Ee;Dd(this.time);this.L&&Va(x.ob)?(this.v(a),Ob(this.time)):this.w&Fe||(this.L&&this.v(a),Ob(this.time))};f.Ee=function(){re(this,V(this),this.b);this.a+=7};f.Cd=function(){this.b=this.f;this.a+=5};f.Dd=function(){this.b=this.g;this.a+=5};f.Ed=function(){this.b=this.h;this.a+=5};f.Fd=function(){this.b=this.i;this.a+=5};f.Gd=function(){this.b=this.j;this.a+=5};f.Hd=function(){this.b=this.l;this.a+=5};
f.Id=function(){this.b=W(this,V(this));this.a+=7};f.Bd=function(){this.a+=5};f.Vb=function(){this.b=Ce(this,this.f);this.a+=4};f.Wb=function(){this.b=Ce(this,this.g);this.a+=4};f.Xb=function(){this.b=Ce(this,this.h);this.a+=4};f.Yb=function(){this.b=Ce(this,this.i);this.a+=4};f.Zb=function(){this.b=Ce(this,this.j);this.a+=4};f.$b=function(){this.b=Ce(this,this.l);this.a+=4};f.ac=function(){this.b=Ce(this,W(this,V(this)));this.a+=7};f.Ub=function(){this.b=Ce(this,this.b);this.a+=4};
f.Nb=function(){this.b=Ge(this,this.f);this.a+=4};f.Ob=function(){this.b=Ge(this,this.g);this.a+=4};f.Pb=function(){this.b=Ge(this,this.h);this.a+=4};f.Qb=function(){this.b=Ge(this,this.i);this.a+=4};f.Rb=function(){this.b=Ge(this,this.j);this.a+=4};f.Sb=function(){this.b=Ge(this,this.l);this.a+=4};f.Tb=function(){this.b=Ge(this,W(this,V(this)));this.a+=7};f.Mb=function(){this.b=Ge(this,this.b);this.a+=4};f.Xf=function(){this.b=X(this,this.f);this.a+=4};
f.Yf=function(){this.b=X(this,this.g);this.a+=4};f.Zf=function(){this.b=X(this,this.h);this.a+=4};f.$f=function(){this.b=X(this,this.i);this.a+=4};f.ag=function(){this.b=X(this,this.j);this.a+=4};f.bg=function(){this.b=X(this,this.l);this.a+=4};f.cg=function(){this.b=X(this,W(this,V(this)));this.a+=7};f.Wf=function(){this.b=X(this,this.b);this.a+=4};f.If=function(){this.b=He(this,this.f);this.a+=4};f.Jf=function(){this.b=He(this,this.g);this.a+=4};f.Kf=function(){this.b=He(this,this.h);this.a+=4};
f.Lf=function(){this.b=He(this,this.i);this.a+=4};f.Mf=function(){this.b=He(this,this.j);this.a+=4};f.Nf=function(){this.b=He(this,this.l);this.a+=4};f.Of=function(){this.b=He(this,W(this,V(this)));this.a+=7};f.Hf=function(){this.b=He(this,this.b);this.a+=4};f.dc=function(){this.b=Ie(this,this.f);this.a+=4};f.ec=function(){this.b=Ie(this,this.g);this.a+=4};f.fc=function(){this.b=Ie(this,this.h);this.a+=4};f.gc=function(){this.b=Ie(this,this.i);this.a+=4};
f.hc=function(){this.b=Ie(this,this.j);this.a+=4};f.ic=function(){this.b=Ie(this,this.l);this.a+=4};f.jc=function(){this.b=Ie(this,W(this,V(this)));this.a+=7};f.cc=function(){this.b=Ie(this,this.b);this.a+=4};f.gg=function(){this.b=Je(this,this.f);this.a+=4};f.hg=function(){this.b=Je(this,this.g);this.a+=4};f.ig=function(){this.b=Je(this,this.h);this.a+=4};f.jg=function(){this.b=Je(this,this.i);this.a+=4};f.kg=function(){this.b=Je(this,this.j);this.a+=4};
f.lg=function(){this.b=Je(this,this.l);this.a+=4};f.mg=function(){this.b=Je(this,W(this,V(this)));this.a+=7};f.fg=function(){this.b=Je(this,this.b);this.a+=4};f.Ue=function(){this.b=Ke(this,this.f);this.a+=4};f.Ve=function(){this.b=Ke(this,this.g);this.a+=4};f.We=function(){this.b=Ke(this,this.h);this.a+=4};f.Xe=function(){this.b=Ke(this,this.i);this.a+=4};f.Ye=function(){this.b=Ke(this,this.j);this.a+=4};f.Ze=function(){this.b=Ke(this,this.l);this.a+=4};
f.$e=function(){this.b=Ke(this,W(this,V(this)));this.a+=7};f.Te=function(){this.b=Ke(this,this.b);this.a+=4};f.qc=function(){X(this,this.f);this.a+=4};f.rc=function(){X(this,this.g);this.a+=4};f.sc=function(){X(this,this.h);this.a+=4};f.tc=function(){X(this,this.i);this.a+=4};f.uc=function(){X(this,this.j);this.a+=4};f.vc=function(){X(this,this.l);this.a+=4};f.wc=function(){X(this,W(this,V(this)));this.a+=7};f.pc=function(){X(this,this.b);this.a+=4};
f.tf=function(){Le(this)||(this.v(Me(this)),this.a+=6);this.a+=5};f.df=function(){qe(this,Me(this));this.a+=10};f.od=function(){var a=U(this);Le(this)||this.v(a);this.a+=10};f.hb=function(){this.v(U(this));this.a+=10};f.yc=function(){var a=U(this);Le(this)||(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.jf=function(){Y(this,se(this));this.a+=11};f.bc=function(){this.b=Ce(this,T(this));this.a+=7};f.yf=function(){Y(this,this.c);this.v(0);this.a+=11};
f.Gf=function(){Le(this)&&(this.v(Me(this)),this.a+=6);this.a+=5};f.ib=function(){this.v(Me(this));this.a+=10};f.sd=function(){var a=U(this);Le(this)&&this.v(a);this.a+=10};f.Dc=function(){var a=U(this);Le(this)&&(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.Ia=function(){var a=U(this);Y(this,this.c);this.v(a);this.a+=17};f.Lb=function(){this.b=Ge(this,T(this));this.a+=7};f.zf=function(){Y(this,this.c);this.v(8);this.a+=11};f.sf=function(){ze(this)||(this.v(Me(this)),this.a+=6);this.a+=5};
f.ef=function(){xe(this,Me(this));this.a+=10};f.nd=function(){var a=U(this);ze(this)||this.v(a);this.a+=10};f.bf=function(){var a=T(this);this.O.ca(a,this.b,this.c+-2&65535);this.a+=10};f.xc=function(){var a=U(this);ze(this)||(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.kf=function(){Y(this,ye(this));this.a+=11};f.dg=function(){this.b=X(this,T(this));this.a+=7};f.Af=function(){Y(this,this.c);this.v(16);this.a+=11};f.pf=function(){ze(this)&&(this.v(Me(this)),this.a+=6);this.a+=5};
f.ld=function(){var a=U(this);ze(this)&&this.v(a);this.a+=10};f.Yc=function(){var a=T(this);this.b=this.O.$(a,this.c+-2&65535)&255;this.a+=10};f.lc=function(){var a=U(this);ze(this)&&(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.Pf=function(){this.b=He(this,T(this));this.a+=7};f.Bf=function(){Y(this,this.c);this.v(24);this.a+=11};f.wf=function(){Ne(this)||(this.v(Me(this)),this.a+=6);this.a+=5};f.ff=function(){we(this,Me(this));this.a+=10};
f.rd=function(){var a=U(this);Ne(this)||this.v(a);this.a+=10};f.og=function(){var a=Me(this);Y(this,V(this));we(this,a);this.a+=18};f.Cc=function(){var a=U(this);Ne(this)||(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.lf=function(){Y(this,V(this));this.a+=11};f.kc=function(){this.b=Ie(this,T(this));this.a+=7};f.Cf=function(){Y(this,this.c);this.v(32);this.a+=11};f.vf=function(){Ne(this)&&(this.v(Me(this)),this.a+=6);this.a+=5};f.cf=function(){this.v(V(this));this.a+=5};
f.qd=function(){var a=U(this);Ne(this)&&this.v(a);this.a+=10};f.eg=function(){var a=V(this);we(this,ye(this));xe(this,a);this.a+=5};f.Ac=function(){var a=U(this);Ne(this)&&(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.ng=function(){this.b=Je(this,T(this));this.a+=7};f.Df=function(){Y(this,this.c);this.v(40);this.a+=11};f.uf=function(){Oe(this)||(this.v(Me(this)),this.a+=6);this.a+=5};f.gf=function(){var a=Me(this);me(this,a&Pe|this.w&~Pe);this.b=a>>8;this.a+=10};
f.pd=function(){var a=U(this);Oe(this)||this.v(a);this.a+=10};f.Vc=function(){this.w&=~Fe;this.a+=4};f.zc=function(){var a=U(this);Oe(this)||(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.hf=function(){Y(this,(this.w&~Qe|Oe(this)|Le(this)|((this.o^this.s)&16?Ae:0)|Ne(this)|ze(this))&Pe|this.b<<8);this.a+=11};f.af=function(){this.b=Ke(this,T(this));this.a+=7};f.Ef=function(){Y(this,this.c);this.v(48);this.a+=11};f.rf=function(){Oe(this)&&(this.v(Me(this)),this.a+=6);this.a+=5};
f.Rf=function(){this.u=V(this)&65535;this.a+=5};f.md=function(){var a=U(this);Oe(this)&&this.v(a);this.a+=10};f.Wc=function(){this.w|=Fe;this.a+=4;if(this.Z&&this.H&Re&&this.w&Fe){var a;for(a=0;8>a&&!(this.H&1<<a);a++);this.H&=~(0>a?255:1<<a);this.w&=~Fe;this.H&=~Ee;this.U[Se|a<<3].call(this)}this.H&Ee&&Dd(this.time)};f.mc=function(){var a=U(this);Oe(this)&&(Y(this,this.c),this.v(a),this.a+=6);this.a+=11};f.Bc=function(){X(this,T(this));this.a+=7};
f.Ff=function(){Y(this,this.c);this.v(56);this.a+=11};f.jb=function(a,b){if(a&&!(0>b))switch(a){case "pc":this.c=b;break;default:this.M("unrecognized register: "+a)}};function se(a){return a.f<<8|a.g}function qe(a,b){a.f=b>>8&255;a.g=b&255}function ye(a){return a.h<<8|a.i}function xe(a,b){a.h=b>>8&255;a.i=b&255}function V(a){return a.j<<8|a.l}function we(a,b){a.j=b>>8&255;a.l=b&255}f.Bb=function(){return this.c};f.v=function(a){this.c=a&65535};function ze(a){return a.m&256?Be:0}
function ve(a,b){a.m=a.m&255|b}function Ne(a){return Te[a.o&255]?Ue:0}function Le(a){return a.m&255?0:Ve}function Oe(a){return a.o&128?We:0}function me(a,b){a.m=a.o=a.s=0;b&Be&&(a.m|=256);b&Ue||(a.o|=1);b&Ae&&(a.s|=16);b&Ve||(a.m|=255);b&We&&(a.o^=192);a.w=a.w&~(Qe|Fe)|b&Fe|Xe}function Ce(a,b){a.s=a.b^b;return a.o=(a.m=a.b+b)&255}function Ge(a,b){a.s=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?1:0))&255}function Ie(a,b){a.m=a.o=a.s=a.b&b;(a.b|b)&8&&(a.s^=16);return a.m}
function ue(a,b){a.s=b^255;b=a.o=b+255&255;a.m=a.m&-256|b;return b}function te(a,b){a.s=b;b=a.o=b+1&255;a.m=a.m&-256|b;return b}function Ke(a,b){return a.o=a.m=a.s=a.b|b}function X(a,b){b^=255;a.s=a.b^b;return a.o=(a.m=a.b+b+1^256)&255}function He(a,b){b^=255;a.s=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?0:1)^256)&255}function Je(a,b){return a.o=a.m=a.s=a.b^b}function W(a,b){return a.I.$(b)|0}function De(a,b){return a.I.$(b)|a.I.$(b+1)<<8}function re(a,b,c){a.I.ca(b,c&255)}
function T(a){var b=W(a,a.c);a.v(a.c+1);return b}function U(a){var b=De(a,a.c);a.v(a.c+2);return b}function Me(a){var b=De(a,a.u);a.u=a.u+2&65535;return b}function Y(a,b){a.u=a.u-2&65535;var c=a.u;a.I.ca(c,b&255);a.I.ca(c+1,b>>8&255)}function Xd(a,b){a.H|=1<<b;a.w&Fe&&Dd(a.time)}
f.toString=function(){var a=this.K("A=%02X BC=%04X DE=%04X HL=%04X SP=%04X I%d S%d Z%d A%d P%d C%d\n",this.b,se(this),ye(this),V(this),this.u,this.w&Fe?1:0,Oe(this)?1:0,Le(this)?1:0,(this.o^this.s)&16&&Ae?1:0,Ne(this)?1:0,ze(this)?1:0);this.L&&(a+=Qb(this.L,this.c,1));return a};f.nb=function(a){this.L||(this.L=fb(this,Ye));!a&&this.time.a||this.ta(this.toString())};
var Be=1,Xe=2,Ue=4,Ae=16,Ve=64,We=128,Pe=255,Fe=512,Qe=Be|Ue|Ae|Ve|We,Te=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,
0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1],ne=0,Re=255,Ee=256,Se=199;
function Ze(a,b){D.call(this,a,a);var c=this;this.a=null;this.b="";this.c=this.f=!1;b=b.trim();"{"==b[0]?$e(this,b):(this.b=b,Sa(this.b,function(d,e,g,h){4==g&&(!h&&e?($e(c,e),af(c)):c.J("Error (%d) loading configuration: %s\n",h,d))}));window.addEventListener("load",function(){c.f=!0;af(c)});window.addEventListener((Wa("iOS")?"pagehide":Wa("Opera")?"unload":void 0)||"beforeunload",function(){var d;if(d=c.a)d.gb&&d.gb(),d.da&&d.da(!1)})}n(Ze,D);
function af(a){if(a.c&&a.f){for(var b in a.S){var c=void 0,d=void 0;try{var e=a.S[b];d=e["class"];if(R[d])if(d==bf)a.J("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,cf,df),a.b&&a.J("Configuration: %s\n",a.b);else{c=new R[d](a.R,b,e);if(d==qb)if(a.a){a.J("too many CPU devices: %s\n",b);continue}else a.a=c;a.J("%s device: %s\n",d,c.status)}else a.J("unrecognized %s device class: %s\n",b,d)}catch(g){a.J("error initializing %s device '%s': %s\n",d,b,g.message),gb(a,b)}}db(a,function(g){g.fb&&g.fb(a.g);g.da&&g.da(a.h)})}}
function $e(a,b){try{a.S=JSON.parse(b);var c=a.S[a.R];Da(a,c);if(a.version){var d="",e=eb(a,a.R);if(e.version!=a.version){d="Machine";var g=e.version}else c.version&&c.version>a.version&&(d="Config",g=c.version);if(d){var h="Error: "+a.K("%s Device version (%3.2f) incompatible with %s version (%3.2f)",c.Mg,a.version,d,g)+"\n\nClearing your browser's cache may resolve the issue.",m=bb.tb;m&&0>bb.list.indexOf(m)&&(alert(h),bb.list.push(m));a.M(h)}}a.h=!1!==c.autoStart;a.g=!1!==c.autoRestore;a.c=!0}catch(l){c=
l.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.M("machine '"+a.R+"' initialization error: "+c)}}var pd="Bus",qb="CPU",Ye="Debugger",oe="Input",rd="LED",bf="Machine",rb="Time",R={};"undefined"!=typeof hb&&(R[pd]=hb);"undefined"!=typeof le&&(R[qb]=le);"undefined"!=typeof Od&&(R.Chip=Od);"undefined"!=typeof Zb&&(R[Ye]=Zb);"undefined"!=typeof Bc&&(R[oe]=Bc);"undefined"!=typeof Uc&&(R[rd]=Uc);"undefined"!=typeof Ze&&(R[bf]=Ze);
"undefined"!=typeof E&&(R.Memory=E);"undefined"!=typeof nd&&(R.RAM=nd);"undefined"!=typeof od&&(R.ROM=od);"undefined"!=typeof sd&&(R[rb]=sd);"undefined"!=typeof Rd&&(R.Video=Rd);var cf="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",df="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";window.Invaders=function(a,b){return new Ze(a,b)};})()

//# sourceMappingURL=invaders.js.map
