(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbgio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/port.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/monitor.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/ram.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/invaders/chip.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/invaders/video.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbg8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/machine.js (C) Jeff Parsons 2012-2019
*/
var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var ha={mc:!0},ia={};try{ia.__proto__=ha;ea=ia.mc;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=da;
function n(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.bj=b.prototype}var ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},la="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ma(a,b){if(b){var c=la;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}ma("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ma("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});ma("Number.parseInt",function(a){return a||parseInt});
function na(){na=function(){};la.Symbol||(la.Symbol=oa)}function pa(a,b){this.a=a;ka(this,"description",{configurable:!0,writable:!0,value:b})}pa.prototype.toString=function(){return this.a};var oa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new pa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function ra(){na();var a=la.Symbol.iterator;a||(a=la.Symbol.iterator=la.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ka(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return sa(aa(this))}});ra=function(){}}function sa(a){ra();a={next:a};a[la.Symbol.iterator]=function(){return this};return a}
function ta(a,b){ra();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ma("Array.prototype.keys",function(a){return a?a:function(){return ta(this,function(b){return b})}});
ma("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function ua(){}function va(){}n(va,ua);
function wa(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var g;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)/))&&
(a=c[1],e=35-((c[2]||35)&255));c=a;if(((d=b)&&10!=d?16==d?null!==c.match(/^-?[0-9a-f]+$/i):8==d?null!==c.match(/^-?[0-7]+$/):2==d&&null!==c.match(/^-?[01]+$/):null!==c.match(/^-?[0-9]+$/))&&!isNaN(g=parseInt(a,b))){e&&(0>g&&(g+=Math.pow(2,36)),g=0<e?g*Math.pow(2,e):Math.trunc(g/Math.pow(2,-e)));var h=g}}return h}
function xa(a,b,c,d,e){d=void 0===d?0:d;var g=void 0===g?0:g;var h="",m="",k=-1;c||(c=a.Y||10);d&&(k=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:m=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=m=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(k=Math.ceil(Math.log(b)/Math.log(c)))));for(a=g||-1;k--;){a||(h=","+h,a=g);if(void 0==b){if(h="?"+h,0>k)break}else{d=b%c;d+=0<=d&&9>=d?48:55;h=String.fromCharCode(d)+h;if(!b&&
0>k)break;b=Math.trunc(b/c)}a--}return e+h+m}function ya(a,b){var c=a/p|0,d=b/p|0;return(a&b)==(b|0)&&(c&d)==d}var p=Math.pow(2,32);function za(){}n(za,va);f=za.prototype;f.flush=function(){var a=Aa;Aa="";this.ta(a)};f.nh=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};
f.ta=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(Aa+a.substr(0,b)),Aa="",a=a.substr(b+1)));Aa+=a};function x(a,b,c){a.ta(b+"\n",c)}f.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.ta(this.J.apply(this,[a].concat(ba(c))))};
f.J=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),g=0,h;for(h=0;h<e.length-6;h+=6){d+=e[h];var m=e[h+5],k="ACDFHIMNSTWYbdfjcsoXx%".indexOf(m);if(0>k)d+="%"+e[h+1]+e[h+2]+e[h+3]+e[h+4]+m;else{if(g<c.length){var l=c[g];"%"!=m&&g++}else l=c[c.length-1];var q=e[h+1],w=e[h+2];"*"==w?(w=l,l=g<c.length?c[g++]:c[c.length-1]):w=+w||0;var v=e[h+3];v=v?+v.substr(1):-1;var r=0<=q.indexOf("#"),t=0<=q.indexOf("0"),
u=null,A=0,B="";k=12>k&&"object"!=typeof l?this.nh(l):l;switch(m){case "C":l=r?"#":"";d+=isNaN(k.getTime())?void 0:this.J(this.J("%%%sW, %%%sF %%%sD, %%%sY",l),k);continue;case "D":l=r?k.getUTCDate():k.getDate();m="d";break;case "A":case "H":case "I":l=r?k.getUTCHours():k.getHours();"A"==m?(l=12>l?"am":"pm",m="s"):("I"==m&&(l=l?12<l?l-12:l:12),m="d");break;case "F":case "M":l=r?k.getUTCMonth():k.getMonth();"F"==m?(l=Ba[l],m="s"):(l++,m="d");break;case "N":l=r?k.getUTCMinutes():k.getMinutes();m="d";
break;case "S":l=r?k.getUTCSeconds():k.getSeconds();m="d";break;case "T":l=r?"#":"";d+=isNaN(k.getTime())?void 0:this.J(this.J("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",l),k);continue;case "W":l=Ca[r?k.getUTCDay():k.getDay()];m="s";break;case "Y":l=r?k.getUTCFullYear():k.getFullYear(),0<v&&(l%=Math.pow(10,v),v=-1),m="d"}switch(m){case "b":d+=l?"true":"false";break;case "d":l=Math.trunc(l);case "f":m=l+"";0<=v&&(m=l.toFixed(v));m.length<w&&(t?(0>l&&(w--,m=m.substr(1)),m=("0000000000"+m).slice(-w),
0>l&&(m="-"+m)):m=("          "+m).slice(-w));d+=m;break;case "j":d+=JSON.stringify(l,null,w||void 0);break;case "c":l="string"==typeof l?l[0]:String.fromCharCode(l);case "s":if(void 0!==l)for("string"!=typeof l&&(l=l.toString()),0<=v&&(l=l.substr(0,v));l.length<w;)l=0<=q.indexOf("-")?l+" ":" "+l;d+=l;break;case "o":A=8,r&&(B="0");case "X":u=Da;case "x":m="";A||(A=16);!B&&r&&(B="0x");u||(u=Ea);"string"==typeof l&&(l=Number.parseInt(l,l.match(/(^0x|[a-f])/i)?16:10));t&&!w&&(w=Math.abs(l),w=255>=w?
2:65535>=w?4:4294967295>=w?8:9,w+=B.length);w-=B.length;do v=l&A-1,l>>>=16==A?4:3,t||!m||v||l?m=u[v]+m:(B&&(m=B+m,B=""),0<w&&(m=" "+m));while(0<--w||l);d+=B+m;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+m+")"}}}return d+=e[h]};var Aa="",Ea="0123456789abcdef",Da="0123456789ABCDEF",Ca="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ba="January February March April May June July August September October November December".split(" "),Fa=0,y={all:0xffffffffffff};
function Ga(){this.V={};this.qa=[];this.ia=0;this.status="OK"}var Ha;n(Ga,za);
Ga.prototype.ua=function(a,b){var c=this;switch(a){case Ia.vb:b.onclick=function(){var d=c.Ca(Ia.Ma,!0);d&&(d.value="")};break;case Ia.Ma:b.value="",b.addEventListener("keydown",function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){var g=!1,h,m=b.value,k=m.lastIndexOf("\n");e==z.gb&&b.selectionStart<=k+1&&(g=!0);e==z.fc?(g=!0,0<c.ia&&(h=c.qa[--c.ia])):e==z.yb&&(g=!0,c.ia<c.qa.length&&(h=c.qa[++c.ia]||""));g&&d.preventDefault();void 0!=h&&(b.value=m.substr(0,k+1)+h)}}),b.addEventListener("keypress",
function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){e=String.fromCharCode(e);var g=b.value,h=g.lastIndexOf("\n");b.selectionStart<=h&&b.setSelectionRange(g.length,g.length);d.stopPropagation();"@"==e&&0<c.ia&&h+1==g.length&&(b.value+=c.qa[--c.ia],e="\r");"\r"==e&&(d.preventDefault(),g=b.value+="\n",b.blur(),b.focus(),(d=Ja(c,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&x(c,d.replace(/\n$/,""),!1))}})}};Ga.prototype.Ca=function(a){return this.V[a]};
function Ka(a){var b=La.hb;return Ma[a.O]&&Ma[a.O][b]}function Na(a,b,c){if(a){do{for(var d=0;d<Oa.length;d++){var e=Oa[d];if(c){if(e+=c,b+e in a)return e}else if(e=e?e+b[0].toUpperCase():b[0],e+=b.substr(1),e in a)return e}if(0>b.indexOf("screen"))break;b=b.replace("screen","Screen")}while(1)}return null}function Pa(a){var b=Qa;return a.T.bindings&&a.T.bindings[b]}function Ra(a){if(a=a.V[Sa])var b=a.textContent;return b}function Ta(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function C(a,b,c){a=a.T[b];void 0===a?a=c:(b=typeof c,typeof a!=b&&("boolean"==b?a=!!a:"number"==typeof c&&(a=+a)));return a}function Ua(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Va(){var a,b=Ha;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ha=b}return b}function Wa(a){if(void 0===Xa.Wa){var b=!1;if(window)try{window.localStorage.setItem(Xa.Ia,Xa.Ia),b=window.localStorage.getItem(Xa.Ia)==Xa.Ia,window.localStorage.removeItem(Xa.Ia)}catch(c){x(a,c.message),b=!1}Xa.Wa=b}return!!Xa.Wa}
function Ya(a){a=void 0===a?0:a;a%2&&a--;a=a||0;return-1==(a|1)||ya(Fa,a)?!0:!1}function Za(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function $a(a){var b=null;if(Wa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.O))&&(b=JSON.parse(c))}catch(d){x(a,d.message)}}return b}
function ab(a){if(window){var b=window.onresize;window.onresize="function"!==typeof b?a:function(){b&&b();a()}}}function bb(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function Ja(a,b){b=void 0===b?"?":b;try{if(b=b.trim())a.ia<a.qa.length&&b==a.qa[a.ia]?a.ia++:(a.qa.push(b),a.ia=a.qa.length);var c=b.split(" "),d=Ka(a);switch(c[0]){case "m":var e="";var g=c[c.length-1].toLowerCase();var h=bb(g);void 0!=h?c.pop():1>=c.length&&(c=Object.keys(y));for(d=1;d<c.length;d++){g=c[d];var m=y[g];if(!m){e+="unrecognized message group: "+g+"\n";break}void 0!=h&&cb(a,m,h);e+=g+": "+Ya(m)+"\n"}break;case "?":e="",db.forEach(function(l){e+=l+"\n"}),e&&(e="default commands:\n"+e);
default:if(c.unshift(b),d)for(a=0;a<d.length;a++){var k=d[a](c);if(void 0!=k){e=e?e+k:k;break}}}}catch(l){e="error: "+l.message+"\n"}return e}Ga.prototype.ta=function(a,b){void 0==b&&(b=Ya(0x800000000000));if(!b){var c=this.Ca(Ia.Ma,!0);if(c){c.value+=a;8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096));c.scrollTop=c.scrollHeight;c.setSelectionRange(c.value.length,c.value.length);return}}za.prototype.ta.call(this,a,b)};
Ga.prototype.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());Ya(d)&&za.prototype.I.call.apply(za.prototype.I,[this,a].concat(ba(c)))};function eb(a,b){if(Wa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.O,b)}catch(c){x(a,c.message)}}}function fb(a,b,c){if(a=a.V[b])a.textContent=c}
function cb(a,b,c){var d=!1;c?(c=Fa,Fa=(c|b)+(c/p|0|b/p|0)*p):(d=ya(Fa,0x800000000000)&&ya(b,0x800000000000),c=Fa,Fa=(c&~b)+((c/p|0)&~(b/p|0))*p);d&&a.flush()}
var Ia={vb:"clear",Ma:"print"},db=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m\t\tenable messages"],La={hb:"command"},gb={list:[],hc:"version"},Xa={Wa:void 0,Ia:"PCjs.localStorage"},z={gb:8,bc:9,Mb:10,wb:13,Wi:16,Ah:17,uh:18,Ki:19,xh:20,Fh:27,$b:32,Ni:33,Mi:34,Dh:35,ei:36,Lb:37,fc:38,Wb:39,$h:39,yb:40,Vh:44,Oi:44,fi:45,Ch:46,Zh:46,ci:47,ZERO:48,ONE:49,dc:50,cc:51,Cb:52,Bb:53,Zb:54,Yb:55,zb:56,Pb:57,bi:59,Xh:61,rb:65,sb:66,tb:67,xb:68,E:69,Ab:70,Db:71,Fb:72,Hb:73,Ib:74,Jb:75,Kb:76,
Nb:77,Ob:78,Qb:79,Rb:80,Q:81,Vb:82,Xb:83,ac:84,ec:85,gc:86,ic:87,jc:88,kc:89,lc:90,yh:91,Yh:91,Th:92,Ri:93,ai:93,ii:96,Ai:96,Sh:96,ji:97,yi:97,ki:98,xi:98,li:99,Ei:99,mi:100,Bi:100,ni:101,ui:101,oi:102,Gi:102,pi:103,zi:103,ri:104,Ii:104,si:105,Fi:105,Di:106,ti:107,Hi:109,vi:110,wi:111,Gh:112,Kh:113,Lh:114,Mh:115,Nh:116,Oh:117,Ph:118,Qh:119,Rh:120,Hh:121,Ih:122,Jh:123,Ci:144,Ui:145,Wh:173,Vi:186,Eh:187,zh:188,Bh:189,Li:190,Xi:191,vh:192,gi:219,wh:220,Qi:221,Pi:222,Uh:224},D={},hb=(D[z.gb]="\b",D[z.bc]=
"\t",D[z.Mb]="\n",D[z.wb]="\r",D[z.$b]=" ",D[z.ZERO]="0",D[z.ONE]="1",D[z.dc]="2",D[z.cc]="3",D[z.Cb]="4",D[z.Bb]="5",D[z.Zb]="6",D[z.Yb]="7",D[z.zb]="8",D[z.Pb]="9",D[z.rb]="A",D[z.sb]="B",D[z.tb]="C",D[z.xb]="D",D[z.E]="E",D[z.Ab]="F",D[z.Db]="G",D[z.Fb]="H",D[z.Hb]="I",D[z.Ib]="J",D[z.Jb]="K",D[z.Kb]="L",D[z.Nb]="M",D[z.Ob]="N",D[z.Qb]="O",D[z.Rb]="P",D[z.Q]="Q",D[z.Vb]="R",D[z.Xb]="S",D[z.ac]="T",D[z.ec]="U",D[z.gc]="V",D[z.ic]="W",D[z.jc]="X",D[z.kc]="Y",D[z.lc]="Z",D[z.Lb]="Left",D[z.Wb]="Right",
D),Oa=["","moz","ms","webkit"],Ma={};y.addr=1;y.bus=2;y.port=4;y.memory=8;y.cpu=16;y.video=32;y.monitor=64;y.screen=128;y.timer=256;y.event=512;y.key=1024;y.warn=2048;y.halt=4096;y.buffer=0x800000000000;function E(a,b,c,d){Ga.call(this);this.O=a;this.ca=b;ib(this,c);this.version=d||2;jb[this.O]||(jb[this.O]=[]);jb[this.O][this.ca]&&this.I("warning: machine configuration contains multiple '%s' devices\n",this.ca);jb[this.O][this.ca]=this;this.La={};this.M=void 0}n(E,Ga);
function ib(a,b){b=void 0===b?{}:b;if(b.overrides){var c=Va();for(g in c)if(0<=b.overrides.indexOf(g)){var d=c[g];if(d.match(/^[+-]?[0-9.]+$/))var e=Number.parseInt(d,10);else"true"==d?e=!0:"false"==d?e=!1:(e=d,d='"'+d+'"');b[g]=e;x(a,"overriding "+a.ca+" property '"+g+"' with "+d)}}a.T=b;c=b.bindings;var g=Array.isArray(c);for(var h in c){d=c[h];if(g)h=d;else if(d.match(/^[0-9]+$/)){e=+d;a.V[h]=[];do{d=h+e++;d=document.getElementById(d);if(!d)break;a.V[h].push(d)}while(1);continue}if(e=document.getElementById(d))a.V[h]=
e,a.ua(h,e)}if(a.version){h="";c=kb(a,a.O);if(c.version!=a.version){h="Machine";var m=c.version}else b.version&&b.version>a.version&&(h="Config",m=b.version);h&&(b="Error: "+a.J("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.$i,a.version,h,m)+"\n\nClearing your browser's cache may resolve the issue.",(m=gb.hc)&&0>gb.list.indexOf(m)&&(alert(b),gb.list.push(m)),x(a,b))}}
function lb(a,b){var c;try{var d=jb[a.O];if(d)for(c in d){var e=d[c];e.T["class"]!=mb&&b(e)}}catch(g){a.I("error while enumerating device '%s': %s\n",c,g.message)}}E.prototype.Ca=function(a,b){b=void 0===b?!1:b;var c=Ga.prototype.Ca.call(this,a,b);if(void 0===c&&b){b=jb[this.O];for(var d in b)if(c=b[d].V[a])break;c||(c=null);this.V[a]=c}return c};function kb(a,b){return(a=jb[a.O])&&a[b]||null}function F(a,b){var c=null;if(a=jb[a.O])for(var d in a)if(a[d].T["class"]==b){c=a[d];break}return c}
E.prototype.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if("number"==typeof a&&Fa&1&&Ya(a)&&(void 0===this.M&&(this.M=F(this,nb)),this.M)){a=c.shift();c=this.J.apply(this,[a].concat(ba(c))).trim();Ga.prototype.I.call(this,"%s at %#0x\n",c,this.M.R);return}Ga.prototype.I.call.apply(Ga.prototype.I,[this,a].concat(ba(c)))};function ob(a,b){(a=jb[a.O])&&delete a[b]}E.prototype.ob=function(a,b){(a=this.La[a])&&a.set(b)};var jb={};
function pb(a,b,c){E.call(this,a,b,c);this.h=c.addrWidth||16;this.f=c.dataWidth||8;this.g=Math.pow(2,this.h);this.i=this.g-1|0;this.b=c.blockSize||1024;this.b>this.g&&(this.b=this.g);this.l=this.g/this.b|0;this.c=Math.log2(this.b)|0;this.j=(1<<this.c)-1;this.a=Array(this.l);a=new qb(a,b+"[NONE]",{size:this.b,width:this.f});for(b=0;b<this.g;b+=this.b)rb(this,b,this.b,sb.NONE,a)}n(pb,E);
function rb(a,b,c,d,e){for(var g=0,h=b>>>a.c;0<c&&h<a.a.length;){var m=h*a.b,k=a.b-(b-m);k>c&&(k=c);var l=a.a[h];if(b!=m||k!=a.b)throw Error(a.J("addBlocks(%#0x,%#0x): block boundary error",b,k));if(l&&l.type!=sb.NONE)throw Error(a.J("addBlocks(%#0x,%#0x): block (%d) already exists",b,k,l.type));l=a.ca+"["+xa(a,b,16,a.h)+"]";if(e)if(e.size==a.b)b=e;else{var q=void 0;if(e.values&&(q=e.values.slice(g,g+k),q.length!=k))throw Error(a.J("addBlocks(%#0x,%#0x): insufficient values (%d)",b,k,q.length));b=
new qb(a.O,l,{type:d,ha:b,size:k,width:a.f,values:q})}else b=new qb(a.O,l,{type:d,ha:b,size:k,width:a.f});a.a[h++]=b;b=m+a.b;c-=k;g+=k}return!0}function tb(a,b){for(var c=sb.Ba|sb.ka,d=0,e=0;e<a.a.length;e++){var g=a.a[e];g&&g.type&c&&(b(g),d++)}return d}f=pb.prototype;f.ma=function(){};f.$a=function(a){return a&&this.la(a)?!0:!1};f.Ka=function(a){this.na(a)};f.la=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(!(c.type<=sb.Ba)&&c.la){var d=a.shift();if(!c.la(d))return!1}}return!0};
f.na=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(!(c.type<=sb.Ba)&&c.na){var d=[];c.na(d);a.push(d)}}};f.ba=function(a){return this.a[(a&this.i)>>>this.c].ba(a&this.j)};f.aa=function(a,b){this.a[(a&this.i)>>>this.c].aa(a&this.j,b)};function ub(a,b,c){function d(g){var h=e.ab(g);e.Ta(e.ha+g,h);return h}var e=a.a[b>>>a.c];if(void 0==e.ha)return!1;if(e.Qa)if(e.Ta==c)e.Qa++;else return!1;else e.Qa=1,e.Ta=c,e.ab=e.ba,e.ba=d;return!0}
function vb(a,b,c){function d(g,h){e.Va(e.ha+g,h);e.fb(g,h)}var e=a.a[b>>>a.c];if(void 0==e.ha)return!1;if(e.Ra)if(e.Va==c)e.Ra++;else return!1;else e.Ra=1,e.Va=c,e.fb=e.aa,e.aa=d;return!0}function wb(a,b,c){a=a.a[b>>>a.c];return a.Qa&&a.Ta==c?(--a.Qa||(a.ba=a.ab,a.ab=a.Ta=void 0),!0):!1}function xb(a,b,c){a=a.a[b>>>a.c];return a.Ra&&a.Va==c?(--a.Ra||(a.aa=a.fb,a.fb=a.Va=void 0),!0):!1}
function yb(a,b,c){E.call(this,a,b,c);this.Y=16;this.w=1;this.o=["(",")"];this.j={};this.M=F(this,nb);this.La=this.M.La;this.K=F(this,zb);this.H=kb(this,this.M.T.busIO);this.b=kb(this,this.M.T.busMemory);this.m=this.b.h;this.N=Math.pow(2,this.m)-1|0;this.L=0;this.c=[];for(var d in G)this.c[G[d]]=[];this.i=[];this.i[G.pa]=this.b;this.i[G.Ja]=this.b;this.i[G.Ga]=this.H;this.i[G.Ha]=this.H;this.f=[];this.f[G.pa]=this.qc.bind(this);this.f[G.Ja]=this.rc.bind(this);this.f[G.Ga]=this.oc.bind(this);this.f[G.Ha]=
this.pc.bind(this);this.a=[];this.h=0;this.time=F(this,Ab);this.time.L.push(this.rh.bind(this));this.s=Bb();this.l=0;this.g=[];this.u=!1;a=this.Cc.bind(this);b=La.hb;Ma[this.O]||(Ma[this.O]={});Ma[this.O][b]||(Ma[this.O][b]=[]);Ma[this.O][b].push(a)}n(yb,E);function Cb(a,b,c){b.S=b.S+c&a.b.i}function Bb(a){a=void 0===a?0:a;var b=Db.Tb;return"number"==typeof a?{S:a,bb:-1,type:b}:{S:a.S,bb:a.bb,type:a.type}}
function Eb(a,b){if(b){var c=0,d=b.charAt(c);var e=Bb();switch(d){case "&":c++;break;case "#":c++;e.type=Db.Ub;break;case "%":c++,d=b.charAt(c),"%"==d?c++:e.type=Db.LINEAR}d=b.indexOf(":");0<=d&&(c=Fb(a,b.substring(c,d)),void 0!=c&&(e.bb=c),c=d+1);e.S=Fb(a,b.substring(c))&a.N}return e}function Gb(a,b,c){a.h++;var d=a.b.ba(b.S);c&&Cb(a,b,c);a.h--;return d}function Hb(a,b,c){if(32>=a.m)return b&c;b=Ib(a,b,0,!0);c=Ib(a,c,0,!0);return((b/p|0)&(c/p|0))*p+((b&c)>>>0)}
function Jb(a,b,c){if(32>=a.m)return b^c;b=Ib(a,b,0,!0);c=Ib(a,c,0,!0);return((b/p|0)^(c/p|0))*p+((b^c)>>>0)}
function Kb(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var g=b.pop();var h=b.pop();switch(e){case "*":h*=g;break;case "/":if(!g)return!1;h=Math.trunc(h/g);break;case "^/":if(!g)return!1;h%=g;break;case "+":h+=g;break;case "-":h-=g;break;case "<<":h<<=g;break;case ">>":h>>=g;break;case ">>>":h>>>=g;break;case "<":h=h<g?1:0;break;case "<=":h=h<=g?1:0;break;case ">":h=h>g?1:0;break;case ">=":h=h>=g?1:0;break;case "==":h=h==g?1:0;break;case "!=":h=h!=g?1:0;break;
case "&":h=Hb(a,h,g);break;case "!":case "|":e=h;32>=a.m?h=e|g:(e=Ib(a,e,0,!0),g=Ib(a,g,0,!0),h=(e/p|0|g/p|0)*p+((e|g)>>>0));break;case "^!":h=Jb(a,h,g);break;case "&&":h=h&&g?1:0;break;case "||":h=h||g?1:0;break;case ",,":h=Ib(a,h,18,!0)*Math.pow(2,18)+Ib(a,g,18,!0);break;case "_":case "^_":"^_"==e&&(g=35-(g&255));g&&(h=Ib(a,h,0,!0),h=0<g?h*Math.pow(2,g):Math.trunc(h/Math.pow(2,-g)));break;default:return!1}b.push(Ib(a,h))}return!0}
function Lb(a,b,c,d,e,g){var h,m=!1,k=0,l=[],q=[],w=a.Y;for(a.Y=e;c<d;){var v=b[c++].trim();var r=c<d?b[c++]:"";if(v){var t=void 0;var u=a;var A=v,B=g;k=void 0===k?0:k;if(void 0!=A){t=(t=u.La[A.toUpperCase()])&&t.get();if(void 0==t)if(t=A,u.j[t]?t=u.j[t].value:(t=t.substr(0,6),t=u.j[t]&&u.j[t].value),void 0!=t){if(A=u.j[A]&&u.j[A].aj)B?B.push(A):(B=Fb(u,A,B),void 0!==B?t+=B:t=void 0)}else t=wa(A,1<A.length||10<u.Y?u.Y:10);void 0!=t&&(t=Ib(u,Mb(u,t,k)))}u=t}else if("{"==r){v=1;for(u=c;c<d;)if(c++,
r=c<b.length?b[c++]:"","{"==r)v++;else if("}"==r&&!--v)break;u=Lb(a,b,u,c-1,a.Y,g);null!=u&&k&&(u=Mb(a,u,k));v=c<d?b[c++].trim():"";r=c<d?b[c++]:""}else{if(" "==r)continue;if("^B"==r){a.Y=2;continue}if("^O"==r){a.Y=8;continue}if("^D"==r){a.Y=10;continue}if(!(k&-1073741824)){if("+"==r)continue;if("-"==r){k=k<<2|1;continue}if("~"==r||"^-"==r){k=k<<2|2;continue}if("^L"==r){k=k<<2|3;continue}}m=!0;break}if(void 0===u)if(g)g.push(v),u=0;else{m=!0;g=[];break}l.push(Ib(a,u));if(" "==r)if(c<b.length-1&&!b[c])c++,
r=b[c++];else{m=!0;break}if(!r)break;u="<"==a.o[0]?Nb:Ob;if(!u[r]){m=!0;break}q.length&&u[r]<=u[q[q.length-1]]&&Kb(a,l,q,1);q.push(r);a.Y="^_"==r?10:e;k=0}if(m||!Kb(a,l,q)||1!=l.length)m=!0;m?g||x(a,"parse error ("+(v||r)+")"):h=l.pop();a.Y=w;return h}
function Pb(a,b,c,d,e){for(var g;0<=(g=b.indexOf(c));){for(var h=0,m=g+1,k=e;m<b.length;){var l=b[m++];if(l==c){k=-1;break}if(!k)break;k--;l=l.charCodeAt(0);7==d?l&=127:l=l-32&63;h=Ib(a,h*Math.pow(2,d)+l,d*e,!0)}if(0<=k){x(a,"parse error ("+c+b+c+")");return}b=b.substr(0,g)+xa(a,h)+b.substr(m)}return b}
function Fb(a,b,c){var d=void 0;if(b){"{"!=a.o[0]&&(b=b.split(a.o[0]).join("{").split(a.o[1]).join("}"));b=Pb(a,b,'"',7,5);if(!b)return d;b=Pb(a,b,"'",6,6);if(!b)return d;16!=a.Y&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);d=Lb(a,b,0,b.length,a.Y,c)}return d}
function Mb(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-Ib(a,b);break;case 2:b=Jb(a,b,-1);break;case 3:for(d=35;0<=d&&!Hb(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function Ib(a,b,c,d){var e=b;c=c||a.m;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}f=yb.prototype;
f.lb=function(a){function b(m){for(var k=0;k<m.length;k++)if(void 0!=m[k])return!1;return!0}if(-1>a)return Qb(this,this.lb);var c="";if(0<=a){var d=this.a[a];if(void 0!=d){c=d>>8;d&=255;var e=this.i[c],g=this.c[c],h=g[d];void 0!=h?(h>=p&&(h=h-p|0),(c&1?xb(e,h,this.f[c]):wb(e,h,this.f[c]))?(g[d]=void 0,this.a[a]=void 0,b(g)&&(g.length=0,b(this.a)&&(this.a.length=0)),c=this.J("%2d: %s %#0x cleared\n",a,Rb[c],h),--this.L||this.u||(c+=Sb(this,!1))):c=this.J("invalid break address: %#0x\n",h)):c=this.J("no break address at index: %d\n",
a)}else c=this.J("invalid break index: %d\n",a)}else c="missing break index\n";return c};
f.Ya=function(a,b){b=void 0===b?!1:b;if(-1>a)return Qb(this,this.Ya,b);if(0<=a){var c=this.a[a];if(void 0!=c){var d=!0,e=c>>8;c&=255;var g=this.c[e],h=g[c];if(void 0!=h){var m=b?"enabled":"disabled";if(h<p){var k=h;b?d=!1:h=(h>>>0)+p}else k=h-p|0,b?h=k:d=!1;d?(g[c]=h,a=this.J("%2d: %s %#0x %s\n",a,Rb[e],k,m)):a=this.J("%2d: %s %#0x already %s\n",a,Rb[e],k,m)}else a=this.J("no break address at index: %d\n",a)}else a=this.J("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function Qb(a,b,c){for(var d="",e=0;e<a.a.length;e++)void 0!=a.a[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function Tb(a){for(var b="",c=0;c<a.a.length;c++){var d=a.a[c];if(void 0!=d){var e=d>>8;d=a.c[e][d&255];var g="enabled";d>=p&&(g="disabled",d=d-p|0);b+=a.J("%2d: %s %#0x %s\n",c,Rb[e],d,g)}}b||(b="no break addresses found\n");return b}
function Ub(a,b,c){function d(m,k){var l;for(l=0;l<a.a.length&&void 0!=a.a[l];l++);a.a[l]=m<<8|k;return l}function e(m,k){var l=m.indexOf(k.S);0>l&&(l=m.indexOf((k.S>>>0)+p));if(0<=l)l=-(l+1);else{for(l=0;l<m.length&&void 0!=m[l];l++);m[l]=k.S}return l}c=void 0===c?G.pa:c;var g="";if(b){g=a.i[c];var h=e(a.c[c],b);0<=h?(g=c&1?vb(g,b.S,a.f[c]):ub(g,b.S,a.f[c]))?(h=d(c,h),g=a.J("%2d: %s %#0x set\n",h,Rb[c],b.S),a.L++||a.u||(g+=Sb(a,!0))):(g=a.J("invalid break address: %#0x\n",b.S),a.c[c][h]=void 0):
g=a.J("%s %#0x already set\n",Rb[c],b.S)}else g="missing break address\n";return g}f.oc=function(a,b){this.h||0<=this.c[G.Ga].indexOf(a)&&Vb(this,this.J("break on input %#0x: %#0x",a,b))};f.pc=function(a,b){this.h||0<=this.c[G.Ha].indexOf(a)&&Vb(this,this.J("break on output %#0x: %#0x",a,b))};f.qc=function(a,b){this.h||(this.g.length&&0==(a-this.M.c&-4)&&(this.g[this.l++]=a,this.l==this.g.length&&(this.l=0)),0<=this.c[G.pa].indexOf(a)&&Vb(this,this.J("break on read %#0x: %#0x",a,b)))};
f.rc=function(a,b){this.h||0<=this.c[G.Ja].indexOf(a)&&Vb(this,this.J("break on write %#0x: %#0x",a,b))};function Vb(a,b){x(a,b);Wb(a.time)}function Xb(a,b){return xa(a,b.S,a.Y,a.b.h,"")}
function Zb(a,b){var c=void 0===c?10:c;var d="";0>b&&(b=c);b=a.l-b;0>b&&(b+=a.g.length);for(var e,g=[];0<=b&&b<a.g.length&&0<c;){var h=a.g[b++];if(b==a.g.length){if(d)break;b=0}if(void 0!=h||g.length){e||(e=Bb(h));if(h!=e.S||g.length==a.w)Cb(a,e,-g.length),d+=a.cb(e,g),c--;void 0!=h&&(e.S=h,g.push(Gb(a,e,1)))}}return d||"no history"}function $b(a,b,c){var d=[],e="";for(b="number"==typeof b?Bb(b):b;c--;){for(Cb(a,b,d.length);d.length<a.w;)d.push(Gb(a,b,1));Cb(a,b,-d.length);e+=a.cb(b,d)}return e}
function ac(a,b,c,d,e){var g="";c||(c=a.b.f);var h=c>>3;d||(d=128);var m=0,k=d+15>>4||1,l=4==h?16:a.Y;"y"==e&&(l=h,k=d,m=8*h);b||(b=a.s);for(;k--&&0<d;){var q=e=0,w,v="",r="",t=Xb(a,b);for(w=l;0<w&&0<d;w--){var u=Gb(a,b,1);e|=u<<(q++<<3);q==h&&(v+=xa(a,e,0,c,""),v+=1==h?9==w?"-":" ":" ",m&&(r+=xa(a,e,2,c,"")),e=q=0);m||(r+=32<=u&&127>u?String.fromCharCode(u):".");d--}g&&(g+="\n");g+=t+"  "+v+" "+r}a.s=b;return g}
function bc(a){var b=[];lb(a,function(c){c.Ka&&c.Ka(b);c.Eb&&c.Eb(b)});return JSON.stringify(b,null,2)}function cc(a,b,c){for(var d=0,e="",g=0;void 0!=b&&g<c.length;g++){var h=Gb(a,b);if(void 0==h)break;var m=a,k=b,l=c[g];m.h++;m.b.aa(k.S,l);m.h--;e+=a.J("%#06x: %#0x changed to %#0x\n",b.S,h,c[g]);Cb(a,b,1);d++}d||(e+=a.J("%d locations updated\n",d));dc(a.time);return e}
function Sb(a,b){if(void 0==b)return"unrecognized option";tb(a.b,function(c){for(var d=c.ha,e=0;e<c.size;d++,e++)b?ub(a.b,d,a.f[G.pa]):wb(a.b,d,a.f[G.pa])})&&(a.l=0,a.g=b?Array(ec):[]);return a.J("instruction history %s\n",b?"enabled":"disabled")}
f.Cc=function(a){var b="",c=[];var d=a[1];if("*"==a[2])var e=-2;else{e=wa(a[2]);void 0==e&&(e=-1);var g=Eb(this,a[2])}var h=0;a[3]&&(h=wa(a[3].substr("l"==a[3][0]?1:0))||8);for(var m=3;m<a.length;m++)c.push(wa(a[m],16));switch(d[0]){case "b":"c"==d[1]?b=this.lb(e):"d"==d[1]?b=this.Ya(e):"e"==d[1]?b=this.Ya(e,!0):"i"==d[1]?b=Ub(this,g,G.Ga):"l"==d[1]?b=Tb(this):"o"==d[1]?b=Ub(this,g,G.Ha):"r"==d[1]?b=Ub(this,g,G.pa):"w"==d[1]?b=Ub(this,g,G.Ja):(b="break commands:\n",fc.forEach(function(k){b+=k+"\n"}));
break;case "d":if("b"!=d[1]&&d[1])if("w"==d[1])c=16;else if("d"==d[1])c=32;else{"h"==d[1]?b=Zb(this,e):"s"==d[1]?b=bc(this):(b="dump commands:\n",gc.forEach(function(k){b+=k+"\n"}));break}else c=8;b=ac(this,g,c,h,d[2]);break;case "e":b=cc(this,g,c);break;case "g":this.time.start()?(void 0!=g&&Ub(this,g),this.K&&hc(this.K)):b="already started\n";break;case "h":Wb(this.time)||(b="already stopped\n");break;case "p":a.shift();a.shift();d=a.join(" ");this.I("%s = %s\n",d,xa(this,Fb(this,d)));break;case "r":void 0!=
g&&this.M.ob(d.substr(1),g.S);b+=this.M.toString(d[1]);break;case "s":g=bb(a[2]);"h"==d[1]?(this.u=g,b=Sb(this,g)):(b="set commands:\n",ic.forEach(function(k){b+=k+"\n"}));break;case "t":h=wa(a[2],10)||1;jc(this.time,h);break;case "u":h||(h=8);g||(g=this.s);b+=$b(this,g,h);this.s=g;break;case "?":b="debugger commands:\n";kc.forEach(function(k){b+=k+"\n"});break;default:b=void 0}void 0==b&&a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n");return b};
f.cb=function(a,b){var c=this;return this.J("%s %02x         unsupported\n",Xb(this,a),function(){var d=b.shift();Cb(c,a,1);return d}())};f.rh=function(a){a&&!this.time.a&&(this.M.ta(this.M.toString()),(a=this.Ca(Ia.Ma,!0))&&a.focus())};
var kc="b?\t\tbreak commands;d?\t\tdump commands;e [addr] ...\tedit memory;g [addr]\trun (to addr);h\t\thalt;p [expr]\tparse expression;r[a]\t\tdump (all) registers;s?\t\tset commands;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";"),fc="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write".split(";"),
gc="db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),ic=["sh [on|off]\tset instruction history"],Db={LINEAR:1,Tb:0,Ub:2,Si:0},G={pa:0,Ja:1,Ga:2,Ha:3},lc={},Rb=(lc[G.pa]="br",lc[G.Ja]="bw",lc[G.Ga]="bi",lc[G.Ha]="bo",lc),mc={Sb:"PC"},ec=1E5,Ob={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,
">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},Nb={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};
function qb(a,b,c){E.call(this,a,b,c);this.ha=c.addr;this.size=c.size;this.type=c.type||sb.NONE;this.width=c.width||8;this.values=c.values||Array(this.size).fill(0);this.m=Math.pow(2,this.width)-1;this.c=this.i=!1;switch(this.type){case sb.NONE:this.ba=this.oh;this.aa=this.pb;break;case sb.Ba:this.ba=this.Ua;this.aa=this.pb;break;case sb.ka:this.ba=this.Ua,this.aa=this.qb}}n(qb,E);f=qb.prototype;f.ma=function(){this.type==sb.ka&&this.values.fill(0)};f.oh=function(){return this.m};f.Ua=function(a){return this.values[a]};
f.pb=function(){};f.qb=function(a,b){this.values[a]=b;this.c=!0};f.la=function(a){var b=a.shift();return this.ca==b?(this.c=a.shift(),this.i=a.shift(),this.values=a.shift(),!0):!1};f.na=function(a){a.push(this.ca);a.push(this.c);a.push(this.i);a.push(this.values)};var sb={NONE:0,Ba:1,ka:2};function nc(a,b,c){qb.call(this,a,b,c)}n(nc,qb);var oc={NONE:0,Ba:1,ka:2};
function pc(a,b,c){E.call(this,a,b,c);this.time=F(this,Ab);this.da=F(this,mb);this.N=null;this.xa=C(this,"drag",!1);this.$=C(this,"scroll",!1);this.sa=C(this,"hexagonal",!1);this.c=C(this,"buttonDelay",0);this.g=!1;if((this.a=this.T.map)&&!this.a.length)for(a=Object.keys(this.a),b=0;b<a.length;b++){c=[];var d=a[b],e=this.a[d];"string"==typeof e?e=[e]:void 0==e.length&&(c=e.grid,e=e.keys,"string"==typeof e&&(e=[e]));this.a[d]={keys:e,wc:c,state:0}}this.b=null;(a=this.V[qc])&&rc(this,a,this.V[sc],this.T.location);
this.H=[];this.K=[];this.R=this.ea=-1}n(pc,E);function tc(a,b){a.N=b}function uc(a,b,c){for(var d=0;d<a.H.length;d++){var e=a.H[d];e.id==b&&e.Oa(b,c)}}
function rc(a,b,c,d){d=void 0===d?[]:d;a.za=d[0]||0;a.Aa=d[1]||0;a.f=d[2]||b.clientWidth;a.l=d[3]||b.clientHeight;a.m=d[4]||1;a.u=d[5]||1;a.Ea=d[6]||b.naturalWidth||a.f;a.wa=d[7]||b.naturalHeight||a.l;a.ga=d[8]||0;a.oa=d[9]||0;a.Da=d[10]||0;a.Fa=d[11]||0;a.a&&a.a.length?(a.s=a.a.length,a.i=a.a[0].length):(a.i=a.m,a.s=a.u,a.m=a.u=0);a.U=a.f/(a.i+a.i*a.m)|0;a.W=a.l/(a.s+a.s*a.u)|0;a.va=a.U*a.m|0;a.X=a.W*a.u|0;a.j=a.w=-1;vc(a,b);wc(a,b);a.time&&(a.c&&(a.fa=xc(a.time,"timerInputRelease",function(){0>
a.j&&0>a.w&&yc(a,-1,-1)})),a.a&&(a.c&&(a.ya=xc(a.time,"timerKeyRelease",function(){zc(a)})),a.h=0,a.L="",a.o=[],Ac(a,c?document:b),!a.b&&c&&(a.b=c)))}function Bc(a){a.c?Cc(a.time,a.ya,a.c):zc(a)}
function Ac(a,b){b.addEventListener("keydown",function(c){c=c||window.event;var d=document.activeElement;if(!a.b||d==a.b){d=c.which||c.keyCode;var e=hb[d],g=!1;e&&(g=Dc(a,e,!0));a.I(1536,"onKeyDown(keyCode=%#04x): %5.2f (%s)\n",d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()}});b.addEventListener("keypress",function(c){c=c||window.event;var d=c.which||c.charCode,e=String.fromCharCode(d),g=!1;e&&(g=Dc(a,e.toUpperCase()));a.I(1536,"onKeyPress(charCode=%#04x): %5.2f (%s)\n",
d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()});b.addEventListener("keyup",function(c){c=c||window.event;var d=document.activeElement;a.b&&d!=a.b||(c=c.which||c.keyCode,(d=hb[c])&&Dc(a,d,!1),a.I(1536,"onKeyUp(keyCode=%#04x): %5.2f (ignored)\n",c,Date.now()/1E3%60))})}
function vc(a,b){b.addEventListener("mousedown",function(c){if(!a.g){if(a.b){var d=window.scrollX,e=window.scrollY;a.b.focus();window.scrollTo(d,e)}c.button||Ec(a,b,Fc,c)}});b.addEventListener("mousemove",function(c){a.g||Ec(a,b,Gc,c)});b.addEventListener("mouseup",function(c){a.g||c.button||Ec(a,b,Hc,c)});b.addEventListener("mouseout",function(c){a.g||(0>a.j?Ec(a,b,Gc,c):Ec(a,b,Hc,c))})}
function wc(a,b){b.addEventListener("touchstart",function(c){a.$&&(a.g=!0);Ec(a,b,Fc,c)});b.addEventListener("touchmove",function(c){Ec(a,b,Gc,c)});b.addEventListener("touchend",function(c){Ec(a,b,Hc,c)})}
function Dc(a,b,c){if(a.a)if(a.a.length){if(!1===c)return!0;for(c=0;c<a.a.length;c++)for(var d=a.a[c],e=0;e<d.length;e++)if(0<=d[e].split("|").indexOf(b))return a.h?16>a.o.length&&a.o.push(b):(a.h=1,a.L=b,yc(a,e,c),uc(a,b,!0),Bc(a)),!0}else if(void 0!=c)for(d=Object.keys(a.a),e=0;e<d.length;e++){var g=d[e];if(0<=a.a[g].keys.indexOf(b))return uc(a,g,c),a.a[g].state=c?1:0,!0}return!1}function zc(a){1==a.h?(a.h++,uc(a,a.L,!1),a.L="",yc(a,-1,-1),Bc(a)):(a.h=0,a.o.length&&Dc(a,a.o.shift()))}
function Ec(a,b,c,d){var e=-1,g=-1,h=!1,m;if(c<Hc){d=d||window.event;if(d.targetTouches&&d.targetTouches.length){var k=d.targetTouches[0].pageX;var l=d.targetTouches[0].pageY;h=1<d.targetTouches.length}else k=d.pageX,l=d.pageY;var q=m=0;var w=b;do isNaN(w.offsetLeft)||(m+=w.offsetLeft,q+=w.offsetTop);while(w=w.offsetParent);k=a.Ea/b.offsetWidth*(k-m)|0;l=a.wa/b.offsetHeight*(l-q)|0;var v=k-a.za;var r=l-a.Aa;q=m=!1;w=k>=a.ga&&k<a.ga+a.Da&&l>=a.oa&&l<a.oa+a.Fa;if(0<=v&&v<a.f&&0<=r+a.X||w)if(h||a.$||
d.preventDefault(),0<=v&&v<a.f&&0<=r&&r<a.l){q=!0;d=a.f/a.i|0;var t=a.l/a.s|0,u=v/d|0,A=r/t|0;!a.sa||A&1||(v-=d>>1,u=v/d|0,u==a.i-1&&(v=-1));t=A*t+(a.X>>1);v-=u*d+(a.va>>1);r-=t;0<=v&&v<a.U&&0<=r&&r<a.W&&(e=u,g=A,m=!0)}}v=v||0;r=r||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Fc||c==Hc)for(u=0;u<a.K.length;u++)A=a.K[u],c==Hc?A.Oa(A.id,!1):(t=r/(b/A.uc|0)|0,(v/(d/A.tc|0)|0)==A.sh&&t==A.th&&A.Oa(A.id,!0));if(!h)if(c==Fc)a.j=k,a.w=l,q?(yc(a,e,g),m&&a.c&&Cc(a.time,a.fa,a.c,!0)):w&&a.da.ja();else if(c==Gc)0<=
a.j&&0<=a.w&&a.xa?yc(a,e,g):a.N&&a.N(e,g);else if(c==Hc){if(c=a.c)c=a.time,e=a.fa,c=c.a&&0<e&&e<=c.b.length?0<=c.b[e-1].Z:!1;c||yc(a,-1,-1);a.j=a.w=-1}else x(a,"unrecognized action: "+c)}function hc(a){a.b&&a.da.ready&&a.b.focus()}function yc(a,b,c){if(b!=a.R||c!=a.ea)a.R=b,a.ea=c}var Fc=1,Gc=2,Hc=3,sc="power",qc="surface";
function Ic(a,b,c){E.call(this,a,b,c);a=this.V[Jc];if(!a)throw Error("LED binding for '"+Jc+"' missing: '"+this.T.V[Jc]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.type=Ta(C(this,"type",Kc),Lc,Mc);this.c=Nc[this.type][0];this.i=Nc[this.type][1];this.width=C(this,"width",this.c);this.height=C(this,"height",this.i);this.f=C(this,"cols",1);this.o=this.f+C(this,"colsExtra",
0);this.N=C(this,"rows",1);this.w=this.N+C(this,"rowsExtra",0);this.eb=this.width*this.f;this.Za=this.height*this.N;this.h=Oc("black",0);this.b=Pc(this.T.color)||this.h;this.$=Oc(this.b,1,.25);this.X=Oc(this.b,1,2);this.g=Pc(this.T.backgroundColor);this.da=C(this,"fixed",!1);this.da||(b.style.width="100%",b.style.height="auto");this.W=C(this,"hexagonal",!1);this.ea=C(this,"highlight",!0);this.H=C(this,"persistent",this.type<Mc);b.setAttribute("width",this.eb.toString());b.setAttribute("height",this.Za.toString());
b.style.backgroundColor=this.h;a.appendChild(b);this.U=b.getContext("2d");if(this.j=document.createElement("canvas"))this.j.width=this.R=this.c*this.f,this.j.height=this.l=this.i*this.N,this.a=this.j.getContext("2d");this.fa=(this.w+1)*this.o*4;this.buffer=Array(this.fa);this.ga=this.f<this.o?4*(this.o-this.f):0;this.s=this.u=!1;this.m=this.L=0;this.K=-1;var d=this;(this.time=F(this,Ab))&&Qc(this.time,function(e){Rc(d,!1,e)})}n(Ic,E);
function Sc(a){for(var b=a.buffer,c=0;c<b.length;c+=4){var d=a,e=b,g=c;e[g]=d.type<Mc?Tc:" ";e[g+1]=d.b==d.h?null:d.b;e[g+2]=0;e[g+3]=Uc}a.s=a.u=!0;Rc(a,!0)}function Vc(a){a.g?(a.a.fillStyle=a.g,a.a.fillRect(0,0,a.R,a.l)):a.a.clearRect(0,0,a.R,a.l)}
function Rc(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.s||b){if(a.type<Mc){var d=0;if(!a.H||b)Vc(a);else if(a.m){d=a.f-a.m;var e=a.c*d;a.a.drawImage(a.j,a.c*a.m,0,e,a.l,0,0,e,a.l)}for(var g=e=0;g<a.w;g++){for(var h=0;h<a.f;h++){var m=a.buffer[e],k=a.buffer[e+1]||a.h,l=a.ea&&e==a.K;if(a.buffer[e+3]&Uc||l||b){if(h>=d)a:{var q=a,w=m;m=k;var v=h;k=g;var r=l;v=void 0===v?0:v;k=void 0===k?0:k;r=void 0===r?!1:r;var t=0;if(q.W&&!(k&1)&&(t=q.c>>1,v==q.f-1))break a;if(m&&m!=q.b){r=r?Oc(m,1,2):m;var u=Oc(m,
1,.25)}else r=r?q.X:q.b,u=q.$;m=!1;w=w?r:u;r==q.h&&(w=q.g,m=!0);r=v*q.c+t;u=k*q.i;q.H&&(v=v*q.c+t,k*=q.i,q.g?(q.a.fillStyle=q.g,q.a.fillRect(v,k,q.c,q.i)):q.a.clearRect(v,k,q.c,q.i));q.a.fillStyle=w;k=Wc[q.type];3==k.length?(q.a.beginPath(),q.a.arc(r+k[0],u+k[1],k[2],0,2*Math.PI),m?(q.a.globalCompositeOperation="destination-out",q.a.fill(),q.a.globalCompositeOperation="source-over"):q.a.fill()):q.a.fillRect(r+k[0],u+k[1],k[2],k[3])}a.buffer[e+3]=l?a.buffer[e+3]|Uc:a.buffer[e+3]&~Uc}e+=4}e+=a.ga}a.m=
0}else{b="";for(d=0;d<a.buffer.length;d+=4)b+=a.buffer[d]||" ",a.buffer[d+3]&Xc&&(b+=".");Vc(a);for(g=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;h=a;l=e;q=g;l=void 0===l?0:l;q=void 0===q?0:q;if(k=Yc[k])for(m=0;m<k.length;m++)if(v=h,t=Zc[k[m]]){w=(void 0===l?0:l)*v.c;r=(void 0===q?0:q)*v.i;v.a.fillStyle=v.b;v.a.beginPath();if(3==t.length)v.a.arc(w+t[0],r+t[1],t[2],0,2*Math.PI);else for(u=0;u<t.length;u+=2)u?v.a.lineTo(w+t[u],r+t[u+1]):v.a.moveTo(w+t[u],r+t[u+1]);v.a.closePath();v.a.fill()}if(++e==
a.f&&(e=0,++g==a.w))break}}a.U.globalCompositeOperation=a.g&&a.b!=a.h?"source-over":"copy";a.U.drawImage(a.j,0,0,a.R,a.l,0,0,a.eb,a.Za);a.s=!1;a.K=-1}else a.H||a.u||(!c||!a.L||c-a.L>=(1E3/60|0))&&Sc(a);a.u=!1;c&&(a.L=c)}function Pc(a){return(a=a||void 0)&&$c[a]||a}
function Oc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=$c[a]||a;var e=a;var g=16;var h=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);h||(g=10,h=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(h){for(e=1;e<h.length;e++)d[e-1]=Number.parseInt(h[e],g);d.length=e-1;g=!0}else g=!1;if(g){a="rgba(";for(g=0;3>g;g++)h=Math.round(d[g]*c),h=0>h?0:255<h?255:h,a+=h+",";a+=(g<d.length?d[g]:b)+")"}}return a}
Ic.prototype.la=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.b&&c==this.g&&a&&a.length==this.buffer.length){this.buffer=a;for(b=0;b<=this.buffer.length-4;b+=4)this.buffer[b+1]==this.h&&(this.buffer[b+1]=null);Rc(this,!0);return!0}return!1};Ic.prototype.na=function(a){this.buffer&&(a.push(this.b),a.push(this.g),a.push(this.buffer))};
var Lc=0,Kc=1,Mc=3,Jc="container",$c={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",
darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",
goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",
lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",
olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",
slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},Tc=0,Xc=1,Uc=128,ad={},Wc=(ad[Lc]=[4,4,4],ad[Kc]=[16,16,14],ad[2]=[2,2,28,28],ad),Nc=[[8,8],[32,32],[32,32],[96,128]],Zc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,
91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Yc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};
function bd(a,b,c){E.call(this,a,b,c);var d=this;this.da=document.fullscreenEnabled||Za("Edge/");this.L=c.monitorWidth||640;this.s=c.monitorHeight||480;if(a=this.V[cd.ib])this.c=a;else throw Error("unable to find monitor container: "+cd.ib);var e=this.V[cd.ub];e||(e=document.createElement("canvas"),e.setAttribute("class","pcjs-monitor"),e.setAttribute("width",c.monitorWidth),e.setAttribute("height",c.monitorHeight),e.style.backgroundColor=c.monitorColor||"black",a.appendChild(e));this.f=e;this.j=
b=e.getContext("2d");Za("MSIE")&&(a.onresize=function(k,l,q,w){return function(){l.style.height=(k.clientWidth*w/q|0)+"px"}}(a,e,c.monitorWidth,c.monitorHeight),a.onresize());var g=+(c.aspect||Va().aspect);g&&.3<=g&&3.33>=g&&(ab(function(k,l,q){return function(){l.style.height=(k.clientWidth/q|0)+"px"}}(a,e,g)),window.onresize());if(this.T.touchtype){var h=document.createElement("textarea");h.setAttribute("class","pcjs-overlay");Za("iOS")&&(h.setAttribute("autocorrect","off"),h.setAttribute("autocapitalize",
"off"),h.style.fontSize="16px");a.appendChild(h)}this.ya=h||a;(this.w=F(this,zb))&&rc(this.w,this.ya,this.Ca(dd,!0));h=c.smoothing;(e=Va().smoothing)&&(h="true"==e);this.$=h;this.sa=Na(b,"imageSmoothingEnabled");if(this.b=c.monitorRotate)this.b=this.b%360,0<this.b&&(this.b-=360),-90!=this.b?(this.I("unsupported monitor rotation: %d\n",this.b),this.b=0):(b.translate(0,this.s),b.rotate(this.b*Math.PI/180),b.scale(this.s/this.L,this.L/this.s));if(b=this.V[cd.jb])if(c=Na(a,"requestFullscreen")){a.Na=
a[c];if(c=Na(document,"on","fullscreenchange")){var m=Na(document,"fullscreenElement");document.addEventListener(c,function(){ed(d,null!=document[m])},!1)}(c=Na(document,"on","fullscreenerror"))&&document.addEventListener(c,function(){ed(d)},!1)}else this.I("Full-screen API not available\n"),b.parentNode.removeChild(b)}n(bd,E);bd.prototype.ua=function(a,b){var c=this;switch(a){case cd.jb:b.onclick=function(){c.Na()}}E.prototype.ua.call(this,a,b)};
function fd(a){a.j&&(a.j.fillStyle="black",a.j.fillRect(0,0,a.f.width,a.f.height))}
bd.prototype.Na=function(){var a=!1;if(this.c){if(this.c.Na){a="100%";if(screen&&screen.width&&screen.height){var b=screen.width/screen.height,c=this.L/this.s;b>c&&(a=Math.round(c/b*100)+"%")}this.da?(this.f.style.width=a,this.f.style.height="auto",this.f.style.display="block",this.f.style.margin="auto"):(this.c.style.width=a,this.c.style.height="auto");this.c.style.backgroundColor="black";this.c.Na();a=!0}this.w&&hc(this.w)}return a};
function ed(a,b){!b&&a.c&&(a.da?a.f.style.width=a.f.style.height="":a.c.style.width=a.c.style.height="")}bd.prototype.ja=function(a){a?(gd(this),hd(this)):fd(this)};bd.prototype.ma=function(){fd(this)};var cd={ub:"canvas",ib:"container",jb:"fullScreen"};function id(a,b,c){c.type=sb.ka;qb.call(this,a,b,c);a=this.T.bus;if(this.a=kb(this,a))rb(this.a,c.addr,c.size,sb.ka,this);else throw Error(this.J("unable to find bus '%s'",a));}n(id,qb);
function jd(a,b,c){c.type=sb.Ba;qb.call(this,a,b,c);c.revision&&(this.status="revision "+c.revision+" "+this.status);this.g=F(this,kd);rb(this.g,c.addr,c.size,c.type,this);if(H[ld]&&this.V[Qa]){var d=this;c=H[ld];this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.f=this.values.length/this.b|0;this.a=new c(a,b+"LEDs",{"class":"LED",bindings:{container:Pa(this)},type:c.Zi.Ti,cols:this.b,rows:this.f,color:C(this,"colorROM","green"),backgroundColor:C(this,"backgroundColorROM","black"),
persistent:!0}),Sc(this.a);this.h=new pc(a,b+"Input",{"class":"Input",location:[0,0,this.a.eb,this.a.Za,this.b,this.f],bindings:{surface:Pa(this)}});this.j=Ra(this)||"";tc(this.h,function(e,g){if(d.M){var h=d.j;0<=e&&0<=g&&(e=g*d.b+e,g=d.M,h=g.L&&$b(g.L,d.ha+e,1)||"");fb(d,Sa,h)}})}}n(jd,qb);
jd.prototype.la=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.buffer.length==d?(this.a.buffer=c,Rc(this.a,!0)):(this.I("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.I("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};jd.prototype.ja=function(){this.M||(this.M=F(this,nb))};
jd.prototype.Ua=function(a){if(this.a){var b=H[ld],c=this.a,d=b.Yi.Ji;b=b.di.hi;b=(void 0===b?0:b)&129;var e=4*((a/this.b|0)*c.o+a%this.b);if(e<=c.buffer.length-4){if(c.buffer[e]!==d||(c.buffer[e+3]&129)!==b)c.buffer[e]=d,c.buffer[e+3]=c.buffer[e+3]&-130|b|Uc,c.s=!0;c.K=e;c.u=!0;c.m=0}}return this.values[a]};jd.prototype.na=function(a){this.a&&(a.push(this.a.buffer),a.push(this.values))};var Qa="array",Sa="cellDesc";
function md(a,b,c){E.call(this,a,b,c);this.sa=C(this,"cyclesMinimum",1E5);this.xa=C(this,"cyclesMaximum",3E6);this.U=Ta(C(this,"cyclesPerSecond",65E4),this.sa,this.xa);this.K=Ta(C(this,"yieldsPerSecond",nd),30,120);this.ya=Ta(C(this,"yieldsPerUpdate",od),1,this.K);this.fa=(this.w=C(this,"clockByFrame",120>=this.U))||C(this,"requestAnimationFrame",!0);this.Ea=this.Fa=this.$=1;this.ga=this.U/1E4/100;this.h=this.m=this.ga*this.$;this.s=0;this.da=Math.round(1E3/this.K);this.ea=[];this.u=[];this.b=[];
this.L=[];this.Da=this.a=this.N=this.l=!1;this.H=this.g=0;this.Aa=this.ph.bind(this);this.za=this.kb.bind(this);this.va=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);if(this.w)this.f=this.wa=0;else{var d=this;xc(this,"timerYield",function(){pd(d)},this.da)}this.W=this.R=this.j=0;qd(this)||rd(this,this.Ea)}n(md,E);function Qc(a,b){a.ea.push(b)}f=md.prototype;
f.ua=function(a,b){var c=this;switch(a){case sd:b.onclick=function(){td(c)&&(c.a?Wb(c):c.start())};break;case ud:b.onclick=function(){jc(c)};break;case vd:b.addEventListener("mousedown",function(){c.l=!0}),b.addEventListener("mouseup",function(){qd(c);c.l=!1}),b.addEventListener("mousemove",function(){c.l&&qd(c)}),b.addEventListener("change",function(){c.l=!0;qd(c);c.l=!1})}E.prototype.ua.call(this,a,b)};
function xc(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,nc:c,Pa:d,Z:-1});0<=d&&Cc(a,e,d);return e}f.kb=function(a){if(this.w){if(!this.a)return;wd(this);try{this.N=!1;do xd(this,yd(this,zd(this,Ad(this))));while(this.a&&!this.N)}catch(c){x(this,c.message);Wb(this);return}Bd(this)}for(var b=0;b<this.ea.length;b++)this.ea[b](a);this.a&&this.fa&&this.va(this.za)};function Cd(a){var b=a.h/a.ga;if(!b||b>a.$)b=a.$;a.Xa=a.U/a.K*b;a.Fa=b}
function zd(a,b){a.R=a.j=b;if(!a.u.length)return a.j=0,a.R;for(var c=0;0<a.j;)c<a.u.length?b=a.u[c++](b)||1:c=b=0,a.j-=b;return a.R-a.j}function yd(a,b){b=void 0===b?a.R-a.j:b;if(a.w){if(!a.a){if(a.f)for(var c=0;c<a.u.length;c++)a.u[c](-1);a.f=b}a.f-=b;1>a.f&&pd(a)}a.R=a.j=0;a.X+=b;a.W+=b;a.a||(a.W=0);return b}function Dd(a,b){return Math.ceil(a.U*a.Fa/1E3*(void 0===b?1E3:b))}
function Ad(a,b){b=void 0===b?0:b;if(b){var c=b;a.f+=b}else for(c=a.f,1>c&&(c=a.f+=a.wa),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.Z)&&c>d.Z&&(c=d.Z)}return c}function Ed(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function td(a){return a.Da?!0:(x(a,"not powered"),!1)}function xd(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.Z||(d.Z-=b,0>=d.Z&&(d.Z=-1,d.nc(),0<=d.Pa&&Cc(a,c,d.Pa)))}}f.ja=function(a){this.Da=a};
function jc(a,b){td(a)&&(a.a?x(a,"already running"):a.g?Wb(a):Fd(a,b))}function pd(a){a.N=!0;var b=a.s,c=Dd(a);c>=a.K?a.s++:a.s+=Math.ceil(a.K/c);a.s>=a.ya&&b<a.ya&&dc(a);a.s>=a.K&&(a.s=0)}f.ph=function(){this.H=0;if(this.a){wd(this);try{this.N=!1;do{for(var a=Dd(this,this.da),b=this.b.length;0<b;b--){var c=this.b[b-1];!(0>c.Z)&&a>c.Z&&(a=c.Z)}xd(this,yd(this,zd(this,a)))}while(this.a&&!this.N)}catch(d){x(this,d.message);Wb(this);return}this.a&&(this.H=setTimeout(this.Aa,Bd(this)),this.fa||this.kb())}};
function qd(a){var b=a.V[vd];return b?(rd(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.xa-a.sa)+a.sa)/a.U),!0):!1}function rd(a,b){void 0!==b&&(!a.l&&0<a.h&&a.h<.9*a.m&&(b=a.Ea),a.$=b,b=a.ga*a.$,a.m!=b&&(a.m=b,fb(a,Gd,Ed(a.m))),a.h=a.m);a.w&&(a.wa=1E6*a.h/60+1E-8,a.f=0);a.W=0;a.c=a.i=0;Cd(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Pa&&Cc(a,b,c.Pa,!0)}}function Cc(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.Z)&&(c=Dd(a,c),a.a&&(c+=yd(a)),b.Z=c)}
function wd(a){Cd(a);a.X=0;a.oa=0;a.o=Date.now();a.c||(a.c=a.o);if(a.i){var b=a.o-a.i;b>a.da&&(a.c+=b,a.c>a.o&&(a.c=a.o))}}function Bd(a){a.i=Date.now();a.oa&&(a.c+=a.oa,a.o+=a.oa);var b=a.da;a.X&&(b=Math.round(b*a.X/a.Xa));b-=a.i-a.o;var c=a.i-a.c;c&&(a.h=a.W/(10*c)/100);0>b?(-1E3>b&&(a.c-=b),b=0):a.h<a.m&&(b=0);a.i+=b;a.I(256,"after running %d cycles, resting for %dms\n",a.X,b);return b}
f.start=function(){if(this.a||this.g)return!1;this.H&&(clearTimeout(this.H),this.H=0);this.a=!0;this.c=this.i=0;dc(this,!0);this.w||(this.H=setTimeout(this.Aa,0));this.fa&&this.va(this.za);return!0};function Fd(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,xd(a,yd(a,zd(a,Ad(a,1)))),dc(a,!1),a.g&&setTimeout(function(){Fd(a,0)},0)))}function Wb(a){return a.g?(a.g=0,dc(a,!0),!0):a.a?(a.a=!1,yd(a),dc(a,!0),!0):!1}
function dc(a,b){b&&(a.a?x(a,"started with "+Ed(a.m)+" target"):x(a,"stopped"));fb(a,sd,a.a?"Halt":"Run");fb(a,ud,a.g?"Stop":"Step");a.l||fb(a,Gd,a.a&&a.h?Ed(a.h):"Stopped");for(var c=0;c<a.L.length;c++)a.L[c](void 0!=b)}var sd="run",Gd="speed",ud="step",vd="throttle",nd=120,od=60;
function Hd(a,b,c){c.type=oc.ka;qb.call(this,a,b,c);a=this.T.bus;if(this.j=kb(this,a))rb(this.j,c.addr,c.size,oc.ka,this);else throw Error(this.J("unable to find bus '%s'",a));this.l=F(this,zb);c=this.Bc.bind(this);a=Object.keys(Id);for(b=0;b<a.length;b++){var d=this.l,e=a[b],g=c,h=d.a[e];if(h){var m=h.keys;m&&m.length&&d.H.push({id:e,Oa:g});(h=h.wc)&&h.length&&d.K.push({id:e,tc:h[0],uc:h[1],sh:h[2],th:h[3],Oa:g})}}this.ma()}n(Hd,nc);f=Hd.prototype;
f.Bc=function(a,b){a=Id[a];this.a=this.a&~a|(b?a:0)};f.ma=function(){this.f=this.b=this.h=this.a=this.g=0};f.yc=function(a){var b=this.g;this.I(2,"inStatus0(%d): %#04x\n",a,b);return b};f.zc=function(a){var b=this.a;this.I(4,"inStatus1(%d): %#04x\n",a,b);return b};f.Ac=function(a){var b=this.h;this.I(4,"inStatus2(%d): %#04x\n",a,b);return b};f.xc=function(a){var b=this.b>>8-this.f&255;this.I(4,"inShiftResult(%d): %#04x\n",a,b);return b};
f.ih=function(a,b){this.I(4,"outShiftCount(%d): %#04x\n",a,b);this.f=b};f.kh=function(a,b){this.I(4,"outSound1(%d): %#04x\n",a,b)};f.jh=function(a,b){this.I(4,"outShiftData(%d): %#04x\n",a,b);this.b=b<<8|this.b>>8};f.lh=function(a,b){this.I(4,"outSound2(%d): %#04x\n",a,b)};f.mh=function(a,b){this.I(4,"outWatchDog(%d): %#04x\n",a,b)};f.Ua=function(a){var b=255;a=this.ha+a;var c=Jd[a];c&&(b=c.call(this,a));return b};f.qb=function(a,b){a=this.ha+a;var c=Kd[a];c&&c.call(this,a,b)};
f.la=function(a){var b=a.shift();return this.ca==b?(this.g=a.shift(),this.a=a.shift(),this.h=a.shift(),this.b=a.shift(),this.f=a.shift(),!0):!1};f.na=function(a){a.push(this.ca);a.push(this.g);a.push(this.a);a.push(this.h);a.push(this.b);a.push(this.f)};var Jd={0:Hd.prototype.yc,1:Hd.prototype.zc,2:Hd.prototype.Ac,3:Hd.prototype.xc},Kd={2:Hd.prototype.ih,3:Hd.prototype.kh,4:Hd.prototype.jh,5:Hd.prototype.lh,6:Hd.prototype.mh},Id={"1p":4,"2p":2,coin:1,left:32,right:64,fire:16};
function Ld(a,b,c){bd.call(this,a,b,c);this.U=c.bufferAddr;this.wa=c.bufferRAM;this.za=c.bufferWidth;this.Aa=c.bufferHeight;this.Ea=c.cellWidth||1;this.Fa=c.cellHeight||1;this.N=c.bufferBits||1;this.xa=c.bufferLeft||0;if(this.a=c.bufferRotate)this.a=this.a%360,0<this.a&&(this.a-=360),-90!=this.a&&(this.I("unsupported buffer rotation: %d\n",this.a),this.a=0);this.R=c.interruptRate;this.oa=c.refreshRate||60;this.l=F(this,kd);this.M=F(this,nb);a:{this.g=this.za*this.Ea;this.o=this.Aa*this.Fa;a=this.g;
b=this.o;this.a&&(a=this.o,b=this.g);this.h=0;if(!this.wa&&(this.h=(this.g*this.N>>3)*this.o,!rb(this.l,this.U,this.h,sb.ka)))break a;this.K=this.l.f;this.h&&(this.ea=this.j.createImageData(a,b),this.fa=Math.trunc(this.K/this.N),gd(this,Math.ceil(this.h/(this.K>>3))));this.i=document.createElement("canvas");this.i.width=a;this.i.height=b;this.Da=this.i.getContext("2d");this.u=1<<this.N;this.m=Array(this.u+Md);this.m[0]=[0,0,0,255];this.m[1]=[255,255,255,255];this.m[this.u+Nd]=[255,255,0,255];this.m[this.u+
Od]=[0,255,0,255];this.sa&&(this.j[this.sa]=null==this.$?!1:this.$)}this.time=F(this,Ab);this.va=xc(this.time,this.ca,this.Xa.bind(this));this.time.L.push(this.Gb.bind(this));Cc(this.time,this.va,1E3/Math.max(this.oa,this.R));this.ga=0}n(Ld,bd);function gd(a,b){if(b=void 0===b?a.X:b)if(a.X=b,a.W=!1,void 0===a.H||a.H.length!=a.X)a.H=Array(a.X)}
Ld.prototype.Xa=function(a){var b=!0;if(!a){this.R&&(120==this.R?this.ga&1?(Pd(this.M,2),b=!1):Pd(this.M,1):Pd(this.M,4));if(b&&this.W&&this.h){a=this.l;var c=this.U,d=this.h,e=!0,g=c>>>a.c;for(c=a.b-(c&a.j);0<d&&g<a.a.length;){var h=a.a[g];h.c?(h.c=!1,h=h.i=!0):h=!1;h&&(e=!1);d-=c;c=a.b;g++}e&&(b=!1)}Cc(this.time,this.va,1E3/Math.max(this.oa,this.R));this.ga++;if(!b)return}hd(this)};
function hd(a){var b=a.U,c=b+a.h,d=0,e=0,g=0,h=a.g,m=0,k=a.o,l=0,q=0,w=a.N,v=(1<<w)-1;a.xa&&(w=-w,q=a.K+w);for(var r=a.K/a.l.f|0;b<c;){var t=a.l.ba(b);if(a.W&&t===a.H[d])e+=a.fa;else{a.H[d]=t;var u=q;u&&(t=t>>8|(t&255)<<8);e<h&&(h=e);for(var A=a.fa;A--;){var B=t>>u&v,qa=a.ea,P=e++,fa=B;B=a.a?(qa.height-P-1)*qa.width+g:P+g*qa.width;fa&&(208<=P&&236>P?fa=a.u+Nd:28<=P&&72>P&&(fa=a.u+Od));P=a.m[fa];B*=P.length;qa.data[B]=P[0];qa.data[B+1]=P[1];qa.data[B+2]=P[2];qa.data[B+3]=P[3];u+=w}e>m&&(m=e);g<k&&
(k=g);g>=l&&(l=g+1)}b+=r;d++;if(e>=a.g&&(e=0,g++,g>a.o))break}a.W=!0;h<a.g&&(b=m-h,l-=k,a.a&&(c=h,d=b,h=k,b=l,k=a.g-(c+d),l=d),a.Da.putImageData(a.ea,0,0,h,k,b,l),a.j.drawImage(a.i,0,0,a.i.width,a.i.height,0,0,a.L,a.s))}Ld.prototype.Gb=function(){this.time.a||hd(this)};var Nd=0,Od=1,Md=2;
function Qd(a,b,c){E.call(this,a,b,c);Rd(this);this.W=[this.ra,this.pe,this.Lg,this.$d,this.Td,this.Dd,this.Gf,this.ig,this.ra,this.yd,this.me,this.Kd,this.Ud,this.Ed,this.Hf,this.pg,this.ra,this.qe,this.Mg,this.ae,this.Vd,this.Fd,this.If,this.fg,this.ra,this.zd,this.ne,this.Ld,this.Wd,this.Gd,this.Jf,this.gg,this.ra,this.re,this.Ig,this.be,this.Xd,this.Hd,this.Kf,this.xd,this.ra,this.Ad,this.oe,this.Md,this.Yd,this.Id,this.Lf,this.fd,this.ra,this.se,this.Kg,this.ce,this.Zd,this.Jd,this.Mf,this.Ng,
this.ra,this.Bd,this.le,this.Nd,this.Sd,this.Cd,this.Ff,this.gd,this.Ce,this.De,this.Ee,this.Fe,this.Ge,this.He,this.Ie,this.Be,this.Ke,this.Le,this.Me,this.Ne,this.Oe,this.Pe,this.Qe,this.Je,this.Se,this.Te,this.Ue,this.Ve,this.We,this.Xe,this.Ye,this.Re,this.$e,this.af,this.bf,this.cf,this.df,this.ef,this.ff,this.Ze,this.hf,this.jf,this.kf,this.lf,this.mf,this.nf,this.pf,this.gf,this.rf,this.sf,this.tf,this.uf,this.vf,this.wf,this.xf,this.qf,this.zf,this.Af,this.Bf,this.Cf,this.Df,this.Ef,this.Qd,
this.yf,this.ue,this.ve,this.we,this.xe,this.ye,this.ze,this.Ae,this.te,this.Nc,this.Oc,this.Pc,this.Qc,this.Rc,this.Sc,this.Tc,this.Mc,this.Fc,this.Gc,this.Hc,this.Ic,this.Jc,this.Kc,this.Lc,this.Ec,this.Pg,this.Qg,this.Rg,this.Sg,this.Tg,this.Ug,this.Vg,this.Og,this.Ag,this.Bg,this.Cg,this.Dg,this.Eg,this.Fg,this.Gg,this.zg,this.Wc,this.Xc,this.Yc,this.Zc,this.$c,this.ad,this.bd,this.Vc,this.Zg,this.$g,this.ah,this.bh,this.dh,this.eh,this.fh,this.Yg,this.Of,this.Pf,this.Qf,this.Rf,this.Sf,this.Tf,
this.Uf,this.Nf,this.jd,this.kd,this.ld,this.md,this.nd,this.od,this.pd,this.hd,this.lg,this.Yf,this.ge,this.mb,this.rd,this.cg,this.Uc,this.qg,this.yg,this.nb,this.ke,this.mb,this.wd,this.Sa,this.Dc,this.rg,this.kg,this.Zf,this.fe,this.Wf,this.qd,this.dg,this.Wg,this.sg,this.hg,this.nb,this.de,this.Rd,this.dd,this.Sa,this.Hg,this.tg,this.og,this.$f,this.je,this.hh,this.vd,this.eg,this.cd,this.ug,this.ng,this.Xf,this.ie,this.Xg,this.td,this.Sa,this.gh,this.vg,this.mg,this.ag,this.he,this.Od,this.sd,
this.bg,this.Vf,this.wg,this.jg,this.Jg,this.ee,this.Pd,this.ed,this.Sa,this.ud,this.xg];this.a=this.N=0;this.X=F(this,zb);this.U=kb(this,this.T.busIO);this.K=kb(this,this.T.busMemory);this.time=F(this,Ab);this.time.u.push(this.sc.bind(this));this.time.L.push(this.qh.bind(this));this.L=void 0;this.La[mc.Sb]={get:this.vc.bind(this),set:this.v.bind(this)}}n(Qd,E);f=Qd.prototype;
f.sc=function(a){a=void 0===a?0:a;if(0>a)return this.N=0;try{if(this.a=0,this.N=a,Sd(this))for(;this.a<=this.N;)this.R=this.c,this.W[I(this)].call(this)}catch(b){this.c=this.R,x(this,b.message),Wb(this.time)}return this.a};
f.la=function(a){a=a.shift();if(!a||!a.length)return x(this,"invalid saved state"),!1;var b=a.shift(),c=a.shift();if(b!=this.ca||2!==(c|0))return this.I("CPU state mismatch (%s %3.2f)\n",b,c),!1;try{this.b=a.shift(),this.f=a.shift(),this.g=a.shift(),this.h=a.shift(),this.i=a.shift(),this.j=a.shift(),this.l=a.shift(),this.v(a.shift()),this.s=a.shift()&65535,Td(this,a.shift()),this.w=a.shift()}catch(d){return x(this,"CPU state error: "+d.message),!1}return!0};
f.na=function(a){var b=[];b.push(this.ca);b.push(2);b.push(this.b);b.push(this.f);b.push(this.g);b.push(this.h);b.push(this.i);b.push(this.j);b.push(this.l);b.push(this.c);b.push(this.s);b.push(Ud(this));b.push(this.w);a.push(b)};f.$a=function(a){return a&&this.la(a)?!0:!1};f.ja=function(a){a?(this.time.start(),hc(this.X)):Wb(this.time)};f.ma=function(){x(this,"reset");Rd(this);this.time.a||this.ta(this.toString())};f.Ka=function(a){this.na(a)};f.ra=function(){this.a+=4};
f.pe=function(){Vd(this,J(this));this.a+=10};f.Lg=function(){Wd(this,Xd(this),this.b);this.a+=7};f.$d=function(){Vd(this,Xd(this)+1);this.a+=5};f.Td=function(){this.f=Yd(this,this.f);this.a+=5};f.Dd=function(){this.f=Zd(this,this.f);this.a+=5};f.Gf=function(){this.f=I(this);this.a+=7};f.ig=function(){var a=this.b<<1;this.b=a&255|a>>8;$d(this,a&256);this.a+=4};f.yd=function(){var a;ae(this,a=K(this)+Xd(this));$d(this,a>>8&256);this.a+=10};f.me=function(){this.b=L(this,Xd(this));this.a+=7};
f.Kd=function(){Vd(this,Xd(this)-1);this.a+=5};f.Ud=function(){this.g=Yd(this,this.g);this.a+=5};f.Ed=function(){this.g=Zd(this,this.g);this.a+=5};f.Hf=function(){this.g=I(this);this.a+=7};f.pg=function(){var a=this.b<<8&256;this.b=(a|this.b)>>1;$d(this,a);this.a+=4};f.qe=function(){be(this,J(this));this.a+=10};f.Mg=function(){Wd(this,ce(this),this.b);this.a+=7};f.ae=function(){be(this,ce(this)+1);this.a+=5};f.Vd=function(){this.h=Yd(this,this.h);this.a+=5};
f.Fd=function(){this.h=Zd(this,this.h);this.a+=5};f.If=function(){this.h=I(this);this.a+=7};f.fg=function(){var a=this.b<<1;this.b=a&255|de(this);$d(this,a&256);this.a+=4};f.zd=function(){var a;ae(this,a=K(this)+ce(this));$d(this,a>>8&256);this.a+=10};f.ne=function(){this.b=L(this,ce(this));this.a+=7};f.Ld=function(){be(this,ce(this)-1);this.a+=5};f.Wd=function(){this.i=Yd(this,this.i);this.a+=5};f.Gd=function(){this.i=Zd(this,this.i);this.a+=5};f.Jf=function(){this.i=I(this);this.a+=7};
f.gg=function(){var a=this.b<<8;this.b=(de(this)<<8|this.b)>>1;$d(this,a&256);this.a+=4};f.re=function(){ae(this,J(this));this.a+=10};f.Ig=function(){var a=J(this),b=K(this);this.K.aa(a,b&255);this.K.aa(a+1,b>>8&255);this.a+=16};f.be=function(){ae(this,K(this)+1);this.a+=5};f.Xd=function(){this.j=Yd(this,this.j);this.a+=5};f.Hd=function(){this.j=Zd(this,this.j);this.a+=5};f.Kf=function(){this.j=I(this);this.a+=7};
f.xd=function(){var a=0,b=de(this);if((this.o^this.u)&16&&ee||9<(this.b&15))a|=6;if(b||154<=this.b)a|=96,b=fe;this.b=ge(this,a);$d(this,b?256:0);this.a+=4};f.Ad=function(){var a;ae(this,a=K(this)+K(this));$d(this,a>>8&256);this.a+=10};f.oe=function(){ae(this,he(this,J(this)));this.a+=16};f.Md=function(){ae(this,K(this)-1);this.a+=5};f.Yd=function(){this.l=Yd(this,this.l);this.a+=5};f.Id=function(){this.l=Zd(this,this.l);this.a+=5};f.Lf=function(){this.l=I(this);this.a+=7};
f.fd=function(){this.b=~this.b&255;this.a+=4};f.se=function(){this.s=J(this)&65535;this.a+=10};f.Kg=function(){Wd(this,J(this),this.b);this.a+=13};f.ce=function(){this.s=this.s+1&65535;this.a+=5};f.Zd=function(){var a=K(this);Wd(this,a,Yd(this,L(this,a)));this.a+=10};f.Jd=function(){var a=K(this);Wd(this,a,Zd(this,L(this,a)));this.a+=10};f.Mf=function(){Wd(this,K(this),I(this));this.a+=10};f.Ng=function(){this.m|=256;this.a+=4};
f.Bd=function(){var a;ae(this,a=K(this)+this.s);$d(this,a>>8&256);this.a+=10};f.le=function(){this.b=L(this,J(this));this.a+=13};f.Nd=function(){this.s=this.s-1&65535;this.a+=5};f.Sd=function(){this.b=Yd(this,this.b);this.a+=5};f.Cd=function(){this.b=Zd(this,this.b);this.a+=5};f.Ff=function(){this.b=I(this);this.a+=7};f.gd=function(){$d(this,de(this)?0:256);this.a+=4};f.Ce=function(){this.a+=5};f.De=function(){this.f=this.g;this.a+=5};f.Ee=function(){this.f=this.h;this.a+=5};
f.Fe=function(){this.f=this.i;this.a+=5};f.Ge=function(){this.f=this.j;this.a+=5};f.He=function(){this.f=this.l;this.a+=5};f.Ie=function(){this.f=L(this,K(this));this.a+=7};f.Be=function(){this.f=this.b;this.a+=5};f.Ke=function(){this.g=this.f;this.a+=5};f.Le=function(){this.a+=5};f.Me=function(){this.g=this.h;this.a+=5};f.Ne=function(){this.g=this.i;this.a+=5};f.Oe=function(){this.g=this.j;this.a+=5};f.Pe=function(){this.g=this.l;this.a+=5};f.Qe=function(){this.g=L(this,K(this));this.a+=7};
f.Je=function(){this.g=this.b;this.a+=5};f.Se=function(){this.h=this.f;this.a+=5};f.Te=function(){this.h=this.g;this.a+=5};f.Ue=function(){this.a+=5};f.Ve=function(){this.h=this.i;this.a+=5};f.We=function(){this.h=this.j;this.a+=5};f.Xe=function(){this.h=this.l;this.a+=5};f.Ye=function(){this.h=L(this,K(this));this.a+=7};f.Re=function(){this.h=this.b;this.a+=5};f.$e=function(){this.i=this.f;this.a+=5};f.af=function(){this.i=this.g;this.a+=5};f.bf=function(){this.i=this.h;this.a+=5};
f.cf=function(){this.a+=5};f.df=function(){this.i=this.j;this.a+=5};f.ef=function(){this.i=this.l;this.a+=5};f.ff=function(){this.i=L(this,K(this));this.a+=7};f.Ze=function(){this.i=this.b;this.a+=5};f.hf=function(){this.j=this.f;this.a+=5};f.jf=function(){this.j=this.g;this.a+=5};f.kf=function(){this.j=this.h;this.a+=5};f.lf=function(){this.j=this.i;this.a+=5};f.mf=function(){this.a+=5};f.nf=function(){this.j=this.l;this.a+=5};f.pf=function(){this.j=L(this,K(this));this.a+=7};
f.gf=function(){this.j=this.b;this.a+=5};f.rf=function(){this.l=this.f;this.a+=5};f.sf=function(){this.l=this.g;this.a+=5};f.tf=function(){this.l=this.h;this.a+=5};f.uf=function(){this.l=this.i;this.a+=5};f.vf=function(){this.l=this.j;this.a+=5};f.wf=function(){this.a+=5};f.xf=function(){this.l=L(this,K(this));this.a+=7};f.qf=function(){this.l=this.b;this.a+=5};f.zf=function(){Wd(this,K(this),this.f);this.a+=7};f.Af=function(){Wd(this,K(this),this.g);this.a+=7};
f.Bf=function(){Wd(this,K(this),this.h);this.a+=7};f.Cf=function(){Wd(this,K(this),this.i);this.a+=7};f.Df=function(){Wd(this,K(this),this.j);this.a+=7};f.Ef=function(){Wd(this,K(this),this.l);this.a+=7};f.Qd=function(){this.a+=7;this.w|=ie;yd(this.time);this.H&je&&!Ya(4096)||(this.v(this.c-1),Wb(this.time))};f.yf=function(){Wd(this,K(this),this.b);this.a+=7};f.ue=function(){this.b=this.f;this.a+=5};f.ve=function(){this.b=this.g;this.a+=5};f.we=function(){this.b=this.h;this.a+=5};
f.xe=function(){this.b=this.i;this.a+=5};f.ye=function(){this.b=this.j;this.a+=5};f.ze=function(){this.b=this.l;this.a+=5};f.Ae=function(){this.b=L(this,K(this));this.a+=7};f.te=function(){this.a+=5};f.Nc=function(){this.b=ge(this,this.f);this.a+=4};f.Oc=function(){this.b=ge(this,this.g);this.a+=4};f.Pc=function(){this.b=ge(this,this.h);this.a+=4};f.Qc=function(){this.b=ge(this,this.i);this.a+=4};f.Rc=function(){this.b=ge(this,this.j);this.a+=4};f.Sc=function(){this.b=ge(this,this.l);this.a+=4};
f.Tc=function(){this.b=ge(this,L(this,K(this)));this.a+=7};f.Mc=function(){this.b=ge(this,this.b);this.a+=4};f.Fc=function(){this.b=ke(this,this.f);this.a+=4};f.Gc=function(){this.b=ke(this,this.g);this.a+=4};f.Hc=function(){this.b=ke(this,this.h);this.a+=4};f.Ic=function(){this.b=ke(this,this.i);this.a+=4};f.Jc=function(){this.b=ke(this,this.j);this.a+=4};f.Kc=function(){this.b=ke(this,this.l);this.a+=4};f.Lc=function(){this.b=ke(this,L(this,K(this)));this.a+=7};
f.Ec=function(){this.b=ke(this,this.b);this.a+=4};f.Pg=function(){this.b=M(this,this.f);this.a+=4};f.Qg=function(){this.b=M(this,this.g);this.a+=4};f.Rg=function(){this.b=M(this,this.h);this.a+=4};f.Sg=function(){this.b=M(this,this.i);this.a+=4};f.Tg=function(){this.b=M(this,this.j);this.a+=4};f.Ug=function(){this.b=M(this,this.l);this.a+=4};f.Vg=function(){this.b=M(this,L(this,K(this)));this.a+=7};f.Og=function(){this.b=M(this,this.b);this.a+=4};f.Ag=function(){this.b=le(this,this.f);this.a+=4};
f.Bg=function(){this.b=le(this,this.g);this.a+=4};f.Cg=function(){this.b=le(this,this.h);this.a+=4};f.Dg=function(){this.b=le(this,this.i);this.a+=4};f.Eg=function(){this.b=le(this,this.j);this.a+=4};f.Fg=function(){this.b=le(this,this.l);this.a+=4};f.Gg=function(){this.b=le(this,L(this,K(this)));this.a+=7};f.zg=function(){this.b=le(this,this.b);this.a+=4};f.Wc=function(){this.b=me(this,this.f);this.a+=4};f.Xc=function(){this.b=me(this,this.g);this.a+=4};
f.Yc=function(){this.b=me(this,this.h);this.a+=4};f.Zc=function(){this.b=me(this,this.i);this.a+=4};f.$c=function(){this.b=me(this,this.j);this.a+=4};f.ad=function(){this.b=me(this,this.l);this.a+=4};f.bd=function(){this.b=me(this,L(this,K(this)));this.a+=7};f.Vc=function(){this.b=me(this,this.b);this.a+=4};f.Zg=function(){this.b=ne(this,this.f);this.a+=4};f.$g=function(){this.b=ne(this,this.g);this.a+=4};f.ah=function(){this.b=ne(this,this.h);this.a+=4};
f.bh=function(){this.b=ne(this,this.i);this.a+=4};f.dh=function(){this.b=ne(this,this.j);this.a+=4};f.eh=function(){this.b=ne(this,this.l);this.a+=4};f.fh=function(){this.b=ne(this,L(this,K(this)));this.a+=7};f.Yg=function(){this.b=ne(this,this.b);this.a+=4};f.Of=function(){this.b=oe(this,this.f);this.a+=4};f.Pf=function(){this.b=oe(this,this.g);this.a+=4};f.Qf=function(){this.b=oe(this,this.h);this.a+=4};f.Rf=function(){this.b=oe(this,this.i);this.a+=4};
f.Sf=function(){this.b=oe(this,this.j);this.a+=4};f.Tf=function(){this.b=oe(this,this.l);this.a+=4};f.Uf=function(){this.b=oe(this,L(this,K(this)));this.a+=7};f.Nf=function(){this.b=oe(this,this.b);this.a+=4};f.jd=function(){M(this,this.f);this.a+=4};f.kd=function(){M(this,this.g);this.a+=4};f.ld=function(){M(this,this.h);this.a+=4};f.md=function(){M(this,this.i);this.a+=4};f.nd=function(){M(this,this.j);this.a+=4};f.od=function(){M(this,this.l);this.a+=4};
f.pd=function(){M(this,L(this,K(this)));this.a+=7};f.hd=function(){M(this,this.b);this.a+=4};f.lg=function(){pe(this)||(this.v(qe(this)),this.a+=6);this.a+=5};f.Yf=function(){Vd(this,qe(this));this.a+=10};f.ge=function(){var a=J(this);pe(this)||this.v(a);this.a+=10};f.mb=function(){this.v(J(this));this.a+=10};f.rd=function(){var a=J(this);pe(this)||(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.cg=function(){N(this,Xd(this));this.a+=11};f.Uc=function(){this.b=ge(this,I(this));this.a+=7};
f.qg=function(){N(this,this.c);this.v(0);this.a+=11};f.yg=function(){pe(this)&&(this.v(qe(this)),this.a+=6);this.a+=5};f.nb=function(){this.v(qe(this));this.a+=10};f.ke=function(){var a=J(this);pe(this)&&this.v(a);this.a+=10};f.wd=function(){var a=J(this);pe(this)&&(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.Sa=function(){var a=J(this);N(this,this.c);this.v(a);this.a+=17};f.Dc=function(){this.b=ke(this,I(this));this.a+=7};f.rg=function(){N(this,this.c);this.v(8);this.a+=11};
f.kg=function(){de(this)||(this.v(qe(this)),this.a+=6);this.a+=5};f.Zf=function(){be(this,qe(this));this.a+=10};f.fe=function(){var a=J(this);de(this)||this.v(a);this.a+=10};f.Wf=function(){var a=I(this);this.U.aa(a,this.b,this.c+-2&65535);this.a+=10};f.qd=function(){var a=J(this);de(this)||(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.dg=function(){N(this,ce(this));this.a+=11};f.Wg=function(){this.b=M(this,I(this));this.a+=7};f.sg=function(){N(this,this.c);this.v(16);this.a+=11};
f.hg=function(){de(this)&&(this.v(qe(this)),this.a+=6);this.a+=5};f.de=function(){var a=J(this);de(this)&&this.v(a);this.a+=10};f.Rd=function(){var a=I(this);this.b=this.U.ba(a,this.c+-2&65535)&255;this.a+=10};f.dd=function(){var a=J(this);de(this)&&(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.Hg=function(){this.b=le(this,I(this));this.a+=7};f.tg=function(){N(this,this.c);this.v(24);this.a+=11};f.og=function(){re(this)||(this.v(qe(this)),this.a+=6);this.a+=5};
f.$f=function(){ae(this,qe(this));this.a+=10};f.je=function(){var a=J(this);re(this)||this.v(a);this.a+=10};f.hh=function(){var a=qe(this);N(this,K(this));ae(this,a);this.a+=18};f.vd=function(){var a=J(this);re(this)||(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.eg=function(){N(this,K(this));this.a+=11};f.cd=function(){this.b=me(this,I(this));this.a+=7};f.ug=function(){N(this,this.c);this.v(32);this.a+=11};f.ng=function(){re(this)&&(this.v(qe(this)),this.a+=6);this.a+=5};
f.Xf=function(){this.v(K(this));this.a+=5};f.ie=function(){var a=J(this);re(this)&&this.v(a);this.a+=10};f.Xg=function(){var a=K(this);ae(this,ce(this));be(this,a);this.a+=5};f.td=function(){var a=J(this);re(this)&&(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.gh=function(){this.b=ne(this,I(this));this.a+=7};f.vg=function(){N(this,this.c);this.v(40);this.a+=11};f.mg=function(){se(this)||(this.v(qe(this)),this.a+=6);this.a+=5};
f.ag=function(){var a=qe(this);Td(this,a&te|this.H&~te);this.b=a>>8;this.a+=10};f.he=function(){var a=J(this);se(this)||this.v(a);this.a+=10};f.Od=function(){this.H&=~je;this.a+=4};f.sd=function(){var a=J(this);se(this)||(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.bg=function(){N(this,Ud(this)&te|this.b<<8);this.a+=11};f.Vf=function(){this.b=oe(this,I(this));this.a+=7};f.wg=function(){N(this,this.c);this.v(48);this.a+=11};f.jg=function(){se(this)&&(this.v(qe(this)),this.a+=6);this.a+=5};
f.Jg=function(){this.s=K(this)&65535;this.a+=5};f.ee=function(){var a=J(this);se(this)&&this.v(a);this.a+=10};f.Pd=function(){this.H|=je;this.a+=4;Sd(this)};f.ed=function(){var a=J(this);se(this)&&(N(this,this.c),this.v(a),this.a+=6);this.a+=11};f.ud=function(){M(this,I(this));this.a+=7};f.xg=function(){N(this,this.c);this.v(56);this.a+=11};function Rd(a){a.b=0;a.f=0;a.g=0;a.h=0;a.i=0;a.j=0;a.l=0;a.s=0;a.v(a.$);a.R=a.c;Td(a,0);a.w=ue}
f.ob=function(a,b){if(a&&!(0>b))switch(a){case "pc":this.c=b;break;default:x(this,"unrecognized register: "+a)}};function Xd(a){return a.f<<8|a.g}function Vd(a,b){a.f=b>>8&255;a.g=b&255}function ce(a){return a.h<<8|a.i}function be(a,b){a.h=b>>8&255;a.i=b&255}function K(a){return a.j<<8|a.l}function ae(a,b){a.j=b>>8&255;a.l=b&255}f.vc=function(){return this.c};f.v=function(a){this.c=a&65535};function de(a){return a.m&256?fe:0}function $d(a,b){a.m=a.m&255|b}function re(a){return ve[a.o&255]?we:0}
function pe(a){return a.m&255?0:xe}function se(a){return a.o&128?ye:0}function Ud(a){return a.H&~ze|se(a)|pe(a)|((a.o^a.u)&16?ee:0)|re(a)|de(a)}function Td(a,b){a.m=a.o=a.u=0;b&fe&&(a.m|=256);b&we||(a.o|=1);b&ee&&(a.u|=16);b&xe||(a.m|=255);b&ye&&(a.o^=192);a.H=a.H&~(ze|je)|b&je|Ae}function ge(a,b){a.u=a.b^b;return a.o=(a.m=a.b+b)&255}function ke(a,b){a.u=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?1:0))&255}function me(a,b){a.m=a.o=a.u=a.b&b;(a.b|b)&8&&(a.u^=16);return a.m}
function Zd(a,b){a.u=b^255;b=a.o=b+255&255;a.m=a.m&-256|b;return b}function Yd(a,b){a.u=b;b=a.o=b+1&255;a.m=a.m&-256|b;return b}function oe(a,b){return a.o=a.m=a.u=a.b|b}function M(a,b){b^=255;a.u=a.b^b;return a.o=(a.m=a.b+b+1^256)&255}function le(a,b){b^=255;a.u=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?0:1)^256)&255}function ne(a,b){return a.o=a.m=a.u=a.b^b}function L(a,b){return a.K.ba(b)|0}function he(a,b){return a.K.ba(b)|a.K.ba(b+1)<<8}function Wd(a,b,c){a.K.aa(b,c&255)}
function I(a){var b=L(a,a.c);a.v(a.c+1);return b}function J(a){var b=he(a,a.c);a.v(a.c+2);return b}function qe(a){var b=he(a,a.s);a.s=a.s+2&65535;return b}function N(a,b){a.s=a.s-2&65535;var c=a.s;a.K.aa(c,b&255);a.K.aa(c+1,b>>8&255)}function Sd(a){if(a.time.a&&a.w&Be&&a.H&je){var b;for(b=0;8>b&&!(a.w&1<<b);b++);a.w&=~(0>b?255:1<<b);a.H&=~je;a.w&=~ie;a.W[Ce|b<<3].call(a)}return a.w&ie?(yd(a.time),!1):!0}function Pd(a,b){a.w|=1<<b;a.H&je&&yd(a.time)}
f.toString=function(){return this.J("A=%02X BC=%04X DE=%04X HL=%04X SP=%04X I%d S%d Z%d A%d P%d C%d\n%s",this.b,Xd(this),ce(this),K(this),this.s,this.H&je?1:0,se(this)?1:0,pe(this)?1:0,(this.o^this.u)&16&&ee?1:0,re(this)?1:0,de(this)?1:0,this.L&&$b(this.L,this.c,1)||"")};f.qh=function(){void 0===this.L&&(this.L=F(this,De))};
var fe=1,Ae=2,we=4,ee=16,xe=64,ye=128,te=255,je=512,ze=fe|we|ee|xe|ye,ve=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,
0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1],ue=0,Be=255,ie=256,Ce=199;function Ee(a,b,c){yb.call(this,a,b,c);this.style=Fe;this.w=3}n(Ee,yb);
Ee.prototype.cb=function(a,b){function c(P,fa){var Yb=Ge[P];g.style==Fe&&fa&He&&(P==Ie&&(Yb="HL"),Yb="["+Yb+"]");return Yb}function d(P){switch(P&Je){case O:var fa=xa(g,e(),16,8,"");break;case Ke:fa=xa(g,(e()|e()<<8)<<24>>24,16,16,"");break;case Le:fa=xa(g,e()|e()<<8,16,16,"");break;default:return"imm("+xa(g,P,16,16,"")+")"}g.style==Fe&&P&He?fa="["+fa+"]":P&Me||(fa=(g.style==Ne?"$":"0x")+fa);return fa}function e(){var P=b.shift();m+=xa(g,P,16,8,"");Cb(g,a,1);return P}for(var g=this,h=Xb(this,a),m=
"",k=e(),l=Oe[k],q="",w=(this.style!=Fe?Pe:Qe)[l[0]],v=l.length-1,r=Re,t,u=1;u<=v;u++){var A="";t=l[u];if(void 0!==t&&!(t&Q&&this.style==Ne)){var B=t&Se;if(B){var qa=t&Je;qa?r=qa:t|=r;t&Te||(t|=1==u?Ue:Ve);B&R?A=d(t):B&Me?A=c((t&We)>>8,t):B&Xe&&(A=(k>>3&7).toString());if(!A||!A.length){q="INVALID";break}0<q.length&&(q+=",");q+=A||"???"}}}return this.J("%s %-9s%s %-7s %s\n",h,m,t&Ye?"*":" ",w,q)};
var Ne=8080,Fe=8086,Pe="NONE ACI ADC ADD ADI ANA ANI CALL CC CM CNC CNZ CP CPE CPO CZ CMA CMC CMP CPI DAA DAD DCR DCX DI EI HLT IN INR INX JMP JC JM JNC JNZ JP JPE JPO JZ LDA LDAX LHLD LXI MOV MVI NOP ORA ORI OUT PCHL POP PUSH RAL RAR RET RC RM RNC RNZ RP RPE RPO RZ RLC RRC RST SBB SBI SHLD SPHL STA STAX STC SUB SUI XCHG XRA XRI XTHL".split(" "),Qe="NONE ADC ADC ADD ADD AND AND CALL CALLC CALLS CALLNC CALLNZ CALLNS CALLP CALLNP CALLZ NOT CMC CMP CMP DAA ADD DEC DEC CLI STI HLT IN INC INC JMP JC JS JNC JNZ JNS JP JNP JZ MOV MOV MOV MOV MOV MOV NOP OR OR OUT JMP POP PUSH RCL RCR RET RETC RETS RETNC RETNZ RETNS RETP RETNP RETZ ROL ROR RST SBB SBB MOV MOV MOV MOV STC SUB SUB XCHG XOR XOR XCHG".split(" "),
Ie=6,Ge="B C D E H L M A BC DE HL SP PC PS PSW".split(" "),Je=15,Se=240,We=3840,Te=61440,Re=0,O=1,Ke=2,Le=3,Me=16,R=32,He=64,Xe=128,S=1792|Me|O,T=0|Me|O,U=256|Me|O,V=512|Me|O,W=768|Me|O,X=1024|Me|O,Y=1280|Me|O,Z=Ie<<8|Me|O|He,Ze=2048|Me|Le,$e=2304|Me|Le,af=2560|Me|Le,bf=2816|Me|Le,cf=3584|Me|Le,Ve=4096,Ue=8192,Q=16384,Ye=32768,Oe=[[45],[42,Ze,R],[71,Ze|He,S|Q],[29,Ze],[28,T],[22,T],[44,T,R],[63],[45,Ye],[21,af|Q,Ze],[40,S|Q,Ze|He],[23,Ze],[28,U],[22,U],[44,U,R],[64],[45,Ye],[42,$e,R],[71,$e|He,S|
Q],[29,$e],[28,V],[22,V],[44,V,R],[52],[45,Ye],[21,af|Q,$e],[40,S|Q,$e|He],[23,$e],[28,W],[22,W],[44,W,R],[53],[45,Ye],[42,af,R],[68,51|He,af|Q],[29,af],[28,X],[22,X],[44,X,R],[20],[45,Ye],[21,af|Q,af],[41,af|Q,51|He],[23,af],[28,Y],[22,Y],[44,Y,R],[16,S|Q],[45,Ye],[42,bf,R],[70,51|He,S|Q],[29,bf],[28,Z],[22,Z],[44,Z,R],[72],[45,Ye],[21,af|Q,bf],[39,S|Q,51|He],[23,bf],[28,S],[22,S],[44,S,R],[17],[43,T,T],[43,T,U],[43,T,V],[43,T,W],[43,T,X],[43,T,Y],[43,T,Z],[43,T,S],[43,U,T],[43,U,U],[43,U,V],[43,
U,W],[43,U,X],[43,U,Y],[43,U,Z],[43,U,S],[43,V,T],[43,V,U],[43,V,V],[43,V,W],[43,V,X],[43,V,Y],[43,V,Z],[43,V,S],[43,W,T],[43,W,U],[43,W,V],[43,W,W],[43,W,X],[43,W,Y],[43,W,Z],[43,W,S],[43,X,T],[43,X,U],[43,X,V],[43,X,W],[43,X,X],[43,X,Y],[43,X,Z],[43,X,S],[43,Y,T],[43,Y,U],[43,Y,V],[43,Y,W],[43,Y,X],[43,Y,Y],[43,Y,Z],[43,Y,S],[43,Z,T],[43,Z,U],[43,Z,V],[43,Z,W],[43,Z,X],[43,Z,Y],[26],[43,Z,S],[43,S,T],[43,S,U],[43,S,V],[43,S,W],[43,S,X],[43,S,Y],[43,S,Z],[43,S,S],[3,S|Q,T],[3,S|Q,U],[3,S|Q,V],[3,
S|Q,W],[3,S|Q,X],[3,S|Q,Y],[3,S|Q,Z],[3,S|Q,S],[2,S|Q,T],[2,S|Q,U],[2,S|Q,V],[2,S|Q,W],[2,S|Q,X],[2,S|Q,Y],[2,S|Q,Z],[2,S|Q,S],[73,S|Q,T],[73,S|Q,U],[73,S|Q,V],[73,S|Q,W],[73,S|Q,X],[73,S|Q,Y],[73,S|Q,Z],[73,S|Q,S],[66,S|Q,T],[66,S|Q,U],[66,S|Q,V],[66,S|Q,W],[66,S|Q,X],[66,S|Q,Y],[66,S|Q,Z],[66,S|Q,S],[5,S|Q,T],[5,S|Q,U],[5,S|Q,V],[5,S|Q,W],[5,S|Q,X],[5,S|Q,Y],[5,S|Q,Z],[5,S|Q,S],[76,S|Q,T],[76,S|Q,U],[76,S|Q,V],[76,S|Q,W],[76,S|Q,X],[76,S|Q,Y],[76,S|Q,Z],[76,S|Q,S],[46,S|Q,T],[46,S|Q,U],[46,S|Q,
V],[46,S|Q,W],[46,S|Q,X],[46,S|Q,Y],[46,S|Q,Z],[46,S|Q,S],[18,S|Q,T],[18,S|Q,U],[18,S|Q,V],[18,S|Q,W],[18,S|Q,X],[18,S|Q,Y],[18,S|Q,Z],[18,S|Q,S],[58],[50,Ze],[34,51],[30,51],[11,51],[51,Ze],[4,S|Q,R|O],[65,Xe],[62],[54],[38,51],[30,51|Ye],[15,51],[7,51],[1,S|Q,R|O],[65,Xe],[57],[50,$e],[33,51],[48,R|O,S|Q],[10,51],[51,$e],[74,S|Q,R|O],[65,Xe],[55],[54,Ye],[31,51],[27,S|Q,R|O],[8,51],[7,51|Ye],[67,S|Q,R|O],[65,Xe],[61],[50,af],[37,51],[78,bf|He|Q,af|Q],[14,51],[51,af],[6,S|Q,R|O],[65,Xe],[60],[49,
af],[36,51],[75,af|Q,$e|Q],[13,51],[7,51|Ye],[77,S|Q,R|O],[65,Xe],[59],[50,cf],[35,51],[24],[12,51],[51,cf],[47,S|Q,R|O],[65,Xe],[56],[69,bf|Q,af|Q],[32,51],[25],[9,51],[7,51|Ye],[19,S|Q,R|O],[65,Xe]];
function df(a,b){E.call(this,a,a);var c=this;this.M=null;this.h=this.ready=!1;this.a="";this.g=this.f=!1;b=b.trim();"{"==b[0]?ef(this,b):(this.a=b,Ua(this.a,function(d,e,g,h){4==g&&(!h&&e?(ef(c,e),ff(c)):c.I("error (%d) loading configuration: %s\n",h,d))}));window.addEventListener("load",function(){c.g=!0;ff(c)});window.addEventListener((Za("iOS")?"pagehide":Za("Opera")?"unload":void 0)||"beforeunload",function(){gf(c)})}n(df,E);
df.prototype.ua=function(a,b){var c=this;switch(a){case dd:b.onclick=function(){c.ready&&c.ja()};break;case hf:b.onclick=function(){c.ready&&c.ma()}}E.prototype.ua.call(this,a,b)};
function ff(a){if(a.f&&a.g){for(var b in a.b){var c=void 0,d=void 0;try{var e=a.b[b];d=e["class"];if(H[d])if(d==mb)a.I("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,jf,kf),a.a&&a.I("Configuration: %s\n",a.a);else{c=new H[d](a.O,b,e);if(d==nb)if(a.M){a.I("too many CPU devices: %s\n",b);continue}else a.M=c;a.I("%s device: %s\n",d,c.status)}else a.I("unrecognized %s device class: %s\n",b,d)}catch(h){a.I("error initializing %s device '%s': %s\n",d,b,h.message),ob(a,b)}}if(a.c){var g=$a(a);lb(a,function(h){h.$a&&
h.$a(g)})}a.ja(!0)}}function gf(a){if(a.c){var b=[];lb(a,function(c){c.Ka&&c.Ka(b)});eb(a,b)}a.ja(!1)}function ef(a,b){try{a.b=JSON.parse(b),ib(a,a.b[a.O]),a.c=!1!==a.T.autoSave,a.i=!1!==a.T.autoStart,a.f=!0}catch(e){var c=e.message,d=c.match(/position ([0-9]+)/);d&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')");x(a,"machine '"+a.O+"' initialization error: "+c)}}
df.prototype.ja=function(a){a=void 0===a?!this.h:a;var b=this;a&&x(this,"power on");lb(this,function(c){c.ja&&c!=b&&(c!=b.M||b.i||this.ready)&&c.ja(a)});this.ready=!0;(this.h=a)||x(this,"power off")};df.prototype.ma=function(){var a=this;lb(this,function(b){b.ma&&b!=a&&b.ma()})};var dd="power",hf="reset",kd="Bus",nb="CPU",De="Debugger",zb="Input",ld="LED",mb="Machine",Ab="Time",H={};"undefined"!=typeof pb&&(H[kd]=pb);"undefined"!=typeof Qd&&(H[nb]=Qd);"undefined"!=typeof Hd&&(H.Chip=Hd);
"undefined"!=typeof Ee&&(H[De]=Ee);"undefined"!=typeof pc&&(H[zb]=pc);"undefined"!=typeof Ic&&(H[ld]=Ic);"undefined"!=typeof df&&(H[mb]=df);"undefined"!=typeof qb&&(H.Memory=qb);"undefined"!=typeof id&&(H.RAM=id);"undefined"!=typeof jd&&(H.ROM=jd);"undefined"!=typeof md&&(H[Ab]=md);"undefined"!=typeof Ld&&(H.Video=Ld);var jf="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",kf="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";
window.Invaders=function(a,b){var c=new df(a,b);window.command=function(d){return Ja(c,d)};return c};})()

//# sourceMappingURL=invaders.js.map
