(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbgio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/port.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/monitor.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/ram.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/invaders/chip.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/invaders/video.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbg8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/machine.js (C) Jeff Parsons 2012-2019
*/
var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var fa;a:{var ha={jc:!0},ia={};try{ia.__proto__=ha;fa=ia.jc;break a}catch(a){}fa=!1}da=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=da;
function n(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Si=b.prototype}var ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},la="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ma(a,b){if(b){var c=la;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}ma("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ma("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});ma("Number.parseInt",function(a){return a||parseInt});
ma("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function na(){}function oa(){}n(oa,na);
function pa(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var g;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)/))&&
(a=c[1],e=35-((c[2]||35)&255));c=a;if(((d=b)&&10!=d?16==d?null!==c.match(/^-?[0-9a-f]+$/i):8==d?null!==c.match(/^-?[0-7]+$/):2==d&&null!==c.match(/^-?[01]+$/):null!==c.match(/^-?[0-9]+$/))&&!isNaN(g=parseInt(a,b))){e&&(0>g&&(g+=Math.pow(2,36)),g=0<e?g*Math.pow(2,e):Math.trunc(g/Math.pow(2,-e)));var h=g}}return h}
function qa(a,b,c,d){var e;d=void 0===d?0:d;var g=void 0===g?0:g;var h="",m="",l=-1;void 0!=c&&void 0==e&&(e="");c||(c=a.X||10);d&&(l=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:m=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=m=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(l=Math.ceil(Math.log(b)/Math.log(c)))));for(a=g||-1;l--;){a||(h=","+h,a=g);if(void 0==b){if(h="?"+h,0>l)break}else{d=b%c;d+=0<=d&&9>=d?48:
55;h=String.fromCharCode(d)+h;if(!b&&0>l)break;b=Math.trunc(b/c)}a--}return e+h+m}function sa(a,b){var c=a/p|0,d=b/p|0;return(a&b)==(b|0)&&(c&d)==d}var p=Math.pow(2,32);function ta(){}n(ta,oa);f=ta.prototype;f.flush=function(){var a=ua;ua="";this.qa(a)};f.gh=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};
f.qa=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(ua+a.substr(0,b)),ua="",a=a.substr(b+1)));ua+=a};function x(a,b,c){a.qa(b+"\n",c)}f.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.qa(this.J.apply(this,[a].concat(ba(c))))};
f.J=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),g=0,h;for(h=0;h<e.length-6;h+=6){d+=e[h];var m=e[h+5],l="ACDFHIMNSTWYbdfjcsoXx%".indexOf(m);if(0>l)d+="%"+e[h+1]+e[h+2]+e[h+3]+e[h+4]+m;else{if(g<c.length){var k=c[g];"%"!=m&&g++}else k=c[c.length-1];var q=e[h+1],w=e[h+2];"*"==w?(w=k,k=g<c.length?c[g++]:c[c.length-1]):w=+w||0;var v=e[h+3];v=v?+v.substr(1):-1;var t=0<=q.indexOf("#"),r=0<=q.indexOf("0"),
u=null,J=0,A="";l=12>l&&"object"!=typeof k?this.gh(k):k;switch(m){case "C":k=t?"#":"";d+=isNaN(l.getTime())?void 0:this.J(this.J("%%%sW, %%%sF %%%sD, %%%sY",k),l);continue;case "D":k=t?l.getUTCDate():l.getDate();m="d";break;case "A":case "H":case "I":k=t?l.getUTCHours():l.getHours();"A"==m?(k=12>k?"am":"pm",m="s"):("I"==m&&(k=k?12<k?k-12:k:12),m="d");break;case "F":case "M":k=t?l.getUTCMonth():l.getMonth();"F"==m?(k=va[k],m="s"):(k++,m="d");break;case "N":k=t?l.getUTCMinutes():l.getMinutes();m="d";
break;case "S":k=t?l.getUTCSeconds():l.getSeconds();m="d";break;case "T":k=t?"#":"";d+=isNaN(l.getTime())?void 0:this.J(this.J("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",k),l);continue;case "W":k=wa[t?l.getUTCDay():l.getDay()];m="s";break;case "Y":k=t?l.getUTCFullYear():l.getFullYear(),0<v&&(k%=Math.pow(10,v),v=-1),m="d"}switch(m){case "b":d+=k?"true":"false";break;case "d":k=Math.trunc(k);case "f":m=k+"";0<=v&&(m=k.toFixed(v));m.length<w&&(r?(0>k&&(w--,m=m.substr(1)),m=("0000000000"+m).slice(-w),
0>k&&(m="-"+m)):m=("          "+m).slice(-w));d+=m;break;case "j":d+=JSON.stringify(k,null,w||void 0);break;case "c":k="string"==typeof k?k[0]:String.fromCharCode(k);case "s":if(void 0!==k)for("string"!=typeof k&&(k=k.toString()),0<=v&&(k=k.substr(0,v));k.length<w;)k=0<=q.indexOf("-")?k+" ":" "+k;d+=k;break;case "o":J=8,t&&(A="0");case "X":u=xa;case "x":m="";J||(J=16);!A&&t&&(A="0x");u||(u=ya);"string"==typeof k&&(k=Number.parseInt(k,k.match(/(^0x|[a-f])/i)?16:10));r&&!w&&(w=Math.abs(k),w=255>=w?
2:65535>=w?4:4294967295>=w?8:9,w+=A.length);w-=A.length;do v=k&J-1,k>>>=16==J?4:3,r||!m||v||k?m=u[v]+m:(A&&(m=A+m,A=""),0<w&&(m=" "+m));while(0<--w||k);d+=A+m;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+m+")"}}}return d+=e[h]};var ua="",ya="0123456789abcdef",xa="0123456789ABCDEF",wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" "),za=0,y={all:0xffffffffffff};
function Aa(a,b,c,d){this.N=a;this.sa=b;this.V={};this.ka=[];this.ga=0;Ba(this,c);this.version=d||2}var Ca;n(Aa,ta);
Aa.prototype.ra=function(a,b){var c=this;switch(a){case Da.rb:b.onclick=function(){var d=c.Ka(Da.Qa,!0);d&&(d.value="")};break;case Da.Qa:b.value="",b.addEventListener("keydown",function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){var g=!1,h,m=b.value,l=m.lastIndexOf("\n");e==z.Za&&b.selectionStart<=l+1&&(g=!0);e==z.cc?(g=!0,0<c.ga&&(h=c.ka[--c.ga])):e==z.vb&&(g=!0,c.ga<c.ka.length&&(h=c.ka[++c.ga]||""));g&&d.preventDefault();void 0!=h&&(b.value=m.substr(0,l+1)+h)}}),b.addEventListener("keypress",
function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){e=String.fromCharCode(e);var g=b.value,h=g.lastIndexOf("\n");b.selectionStart<=h&&b.setSelectionRange(g.length,g.length);d.stopPropagation();"@"==e&&0<c.ga&&h+1==g.length&&(b.value+=c.ka[--c.ga],e="\r");"\r"==e&&(d.preventDefault(),g=b.value+="\n",b.blur(),b.focus(),(d=Ea(c,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&x(c,d.replace(/\n$/,""),!1))}})}};
function Ba(a,b){b=void 0===b?{}:b;if(b.overrides){var c=Fa();for(h in c)if(0<=b.overrides.indexOf(h)){var d=c[h];if(d.match(/^[+-]?[0-9.]+$/))var e=Number.parseInt(d,10);else"true"==d?e=!0:"false"==d?e=!1:(e=d,d='"'+d+'"');b[h]=e;x(a,"overriding "+a.sa+" property '"+h+"' with "+d)}}a.O||(a.O=b);b=b.bindings;c=Array.isArray(b);for(var g in b){e=b[g];if(c)g=e;else if(e.match(/^[0-9]+$/)){var h=+e;a.V[g]=[];do{e=g+h++;e=document.getElementById(e);if(!e)break;a.V[g].push(e)}while(1);continue}if(h=document.getElementById(e))a.V[g]=
h,a.ra(g,h)}}Aa.prototype.Ka=function(a){return this.V[a]};function Ga(a){var b=Ha.$a;return Ia[a.N]&&Ia[a.N][b]}function Ja(a,b,c){if(a)for(var d=0;d<Ka.length;d++){var e=Ka[d];if(c){if(e+=c,b+e in a)return e}else if(e=e?e+b[0].toUpperCase():b[0],e+=b.substr(1),e in a)return e}return null}function La(a){var b=Ma;return a.O.bindings&&a.O.bindings[b]}function Na(a){if(a=a.V[Oa])var b=a.textContent;return b}function Pa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function B(a,b,c){a=a.O[b];void 0===a?a=c:(b=typeof c,typeof a!=b&&("boolean"==b?a=!!a:"number"==typeof c&&(a=+a)));return a}function Qa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Fa(){var a,b=Ca;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ca=b}return b}function Ra(a){if(void 0===Sa.Oa){var b=!1;if(window)try{window.localStorage.setItem(Sa.Aa,Sa.Aa),b=window.localStorage.getItem(Sa.Aa)==Sa.Aa,window.localStorage.removeItem(Sa.Aa)}catch(c){x(a,c.message),b=!1}Sa.Oa=b}return!!Sa.Oa}
function Ta(a){a=void 0===a?0:a;a%2&&a--;a=a||0;return-1==(a|1)||sa(za,a)?!0:!1}function Ua(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Va(a){var b=null;if(Ra(a)){var c;if(window)try{(c=window.localStorage.getItem(a.N))&&(b=JSON.parse(c))}catch(d){x(a,d.message)}}return b}
function Wa(a){if(window){var b=window.onresize;window.onresize="function"!==typeof b?a:function(){b&&b();a()}}}function Xa(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function Ea(a,b){try{if(b=b.trim())a.ga<a.ka.length&&b==a.ka[a.ga]?a.ga++:(a.ka.push(b),a.ga=a.ka.length);var c=b.split(" "),d=Ga(a);switch(c[0]){case "m":var e="";var g=c[c.length-1].toLowerCase();var h=Xa(g);void 0!=h?c.pop():1>=c.length&&(c=Object.keys(y));for(d=1;d<c.length;d++){g=c[d];var m=y[g];if(!m){e+="unrecognized message group: "+g+"\n";break}void 0!=h&&Ya(a,m,h);e+=g+": "+Ta(m)+"\n"}break;case "?":e="",Za.forEach(function(k){e+=k+"\n"}),e&&(e="default commands:\n"+e);default:if(c.unshift(b),
d)for(a=0;a<d.length;a++){var l=d[a](c);if(void 0!=l){e=e?e+l:l;break}}}}catch(k){e="error: "+k.message+"\n"}return e}Aa.prototype.qa=function(a,b){void 0==b&&(b=Ta(0x800000000000));if(!b){var c=this.Ka(Da.Qa,!0);if(c){c.value+=a;8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096));c.scrollTop=c.scrollHeight;return}}ta.prototype.qa.call(this,a,b)};
Aa.prototype.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());Ta(d)&&ta.prototype.I.call.apply(ta.prototype.I,[this,a].concat(ba(c)))};function $a(a,b){if(Ra(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.N,b)}catch(c){x(a,c.message)}}}function ab(a,b,c){if(a=a.V[b])a.textContent=c}
function Ya(a,b,c){var d=!1;c?(c=za,za=(c|b)+(c/p|0|b/p|0)*p):(d=sa(za,0x800000000000)&&sa(b,0x800000000000),c=za,za=(c&~b)+((c/p|0)&~(b/p|0))*p);d&&a.flush()}
var Da={rb:"clear",Qa:"print"},Za=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m\t\tenable messages"],Ha={$a:"command"},bb={list:[],ec:"version"},Sa={Oa:void 0,Aa:"PCjs.localStorage"},z={Za:8,Zb:9,Jb:10,tb:13,Mi:16,ph:17,jh:18,zi:19,mh:20,uh:27,Xb:32,Ci:33,Bi:34,sh:35,Uh:36,Ib:37,cc:38,Tb:39,Ph:39,vb:40,Kh:44,Di:44,Vh:45,rh:46,Oh:46,Sh:47,ZERO:48,ONE:49,ac:50,$b:51,Ab:52,zb:53,Wb:54,Vb:55,wb:56,Mb:57,Rh:59,Mh:61,nb:65,ob:66,pb:67,ub:68,E:69,yb:70,Cb:71,Db:72,Eb:73,Fb:74,Gb:75,Hb:76,
Kb:77,Lb:78,Nb:79,Ob:80,Q:81,Sb:82,Ub:83,Yb:84,bc:85,dc:86,fc:87,gc:88,hc:89,ic:90,nh:91,Nh:91,Ih:92,Gi:93,Qh:93,Yh:96,oi:96,Hh:96,Zh:97,mi:97,$h:98,li:98,ai:99,ti:99,bi:100,pi:100,ci:101,ii:101,di:102,vi:102,ei:103,ni:103,fi:104,xi:104,gi:105,ui:105,si:106,hi:107,wi:109,ji:110,ki:111,vh:112,zh:113,Ah:114,Bh:115,Ch:116,Dh:117,Eh:118,Fh:119,Gh:120,wh:121,xh:122,yh:123,ri:144,Ki:145,Lh:173,Li:186,th:187,oh:188,qh:189,Ai:190,Ni:191,kh:192,Wh:219,lh:220,Fi:221,Ei:222,Jh:224},C={},cb=(C[z.Za]="\b",C[z.Zb]=
"\t",C[z.Jb]="\n",C[z.tb]="\r",C[z.Xb]=" ",C[z.ZERO]="0",C[z.ONE]="1",C[z.ac]="2",C[z.$b]="3",C[z.Ab]="4",C[z.zb]="5",C[z.Wb]="6",C[z.Vb]="7",C[z.wb]="8",C[z.Mb]="9",C[z.nb]="A",C[z.ob]="B",C[z.pb]="C",C[z.ub]="D",C[z.E]="E",C[z.yb]="F",C[z.Cb]="G",C[z.Db]="H",C[z.Eb]="I",C[z.Fb]="J",C[z.Gb]="K",C[z.Hb]="L",C[z.Kb]="M",C[z.Lb]="N",C[z.Nb]="O",C[z.Ob]="P",C[z.Q]="Q",C[z.Sb]="R",C[z.Ub]="S",C[z.Yb]="T",C[z.bc]="U",C[z.dc]="V",C[z.fc]="W",C[z.gc]="X",C[z.hc]="Y",C[z.ic]="Z",C[z.Ib]="Left",C[z.Tb]="Right",
C),Ka=["","moz","ms","webkit"],Ia={};y.addr=1;y.bus=2;y.port=4;y.memory=8;y.cpu=16;y.video=32;y.monitor=64;y.screen=128;y.timer=256;y.event=512;y.key=1024;y.warn=2048;y.halt=4096;y.buffer=0x800000000000;function D(a,b,c,d){Aa.call(this,a,b,c,d);this.status="OK";db[this.N]||(db[this.N]=[]);db[this.N].push(this);this.Da={};this.S=void 0}n(D,Aa);function eb(a,b){if(a=db[a.N])for(var c in a)b(a[c])}
D.prototype.Ka=function(a,b){b=void 0===b?!1:b;var c=Aa.prototype.Ka.call(this,a,b);if(void 0===c&&b){b=db[this.N];for(var d in b)if(c=b[d].V[a])break;c||(c=null);this.V[a]=c}return c};function fb(a,b){var c=null;if(a=db[a.N])for(var d in a)if(a[d].sa==b){c=a[d];break}return c}function gb(a,b){var c=null;if(a=db[a.N])for(var d in a)if(a[d].O["class"]==b){c=a[d];break}return c}
D.prototype.I=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if("number"==typeof a&&za&1&&Ta(a)&&(void 0===this.S&&(this.S=gb(this,hb)),this.S)){a=c.shift();c=this.J.apply(this,[a].concat(ba(c))).trim();Aa.prototype.I.call(this,"%s at %#0x\n",c,this.S.T);return}Aa.prototype.I.call.apply(Aa.prototype.I,[this,a].concat(ba(c)))};function ib(a,b){if(a=db[a.N])for(var c in a)if(a[c].sa==b){a.splice(c,1);break}}D.prototype.lb=function(a,b){(a=this.Da[a])&&a.set(b)};var db={};
function jb(a,b,c){D.call(this,a,b,c);this.h=c.addrWidth||16;this.f=c.dataWidth||8;this.g=Math.pow(2,this.h);this.i=this.g-1|0;this.a=c.blockSize||1024;this.a>this.g&&(this.a=this.g);this.l=this.g/this.a|0;this.c=Math.log2(this.a)|0;this.j=(1<<this.c)-1;this.b=Array(this.l);a=new E(a,b+".none",{size:this.a,width:this.f});for(b=0;b<this.g;b+=this.a)kb(this,b,this.a,lb.NONE,a)}n(jb,D);
function kb(a,b,c,d,e){for(var g=0,h=0,m=b>>>a.c;0<c&&m<a.b.length;){var l=m*a.a,k=a.a-(b-l);k>c&&(k=c);var q=a.b[m];if(b!=l||k!=a.a)throw Error(a.J("addBlocks(%#0x,%#0x): block boundary error",b,k));if(q&&q.type!=lb.NONE)throw Error(a.J("addBlocks(%#0x,%#0x): block (%d) already exists",b,k,q.type));if(e)if(e.size==a.a)b=e;else{q=void 0;if(e.values&&(q=e.values.slice(g,g+k),q.length!=k))throw Error(a.J("addBlocks(%#0x,%#0x): insufficient values (%d)",b,k,q.length));b=new E(a.N,e.sa+".block"+h,{type:d,
fa:b,size:k,width:a.f,values:q})}else b=new E(a.N,a.sa+".block"+h,{type:d,fa:b,size:k,width:a.f});a.b[m++]=b;b=l+a.a;c-=k;g+=k;h++}return!0}function mb(a,b){for(var c=lb.Ra|lb.za,d=0,e=0;e<a.b.length;e++){var g=a.b[e];g&&g.type&c&&(b(g),d++)}return d}jb.prototype.ca=function(a){return this.b[(a&this.i)>>>this.c].ca(a&this.j)};jb.prototype.aa=function(a,b){this.b[(a&this.i)>>>this.c].aa(a&this.j,b)};
function nb(a,b,c){function d(g){var h=e.Ua(g);e.La(e.fa+g,h);return h}var e=a.b[b>>>a.c];if(void 0==e.fa)return!1;if(e.Ha)if(e.La==c)e.Ha++;else return!1;else e.Ha=1,e.La=c,e.Ua=e.ca,e.ca=d;return!0}function ob(a,b,c){function d(g,h){e.Na(e.fa+g,h);e.Ya(g,h)}var e=a.b[b>>>a.c];if(void 0==e.fa)return!1;if(e.Ia)if(e.Na==c)e.Ia++;else return!1;else e.Ia=1,e.Na=c,e.Ya=e.aa,e.aa=d;return!0}function pb(a,b,c){a=a.b[b>>>a.c];return a.Ha&&a.La==c?(--a.Ha||(a.ca=a.Ua,a.Ua=a.La=void 0),!0):!1}
function qb(a,b,c){a=a.b[b>>>a.c];return a.Ia&&a.Na==c?(--a.Ia||(a.aa=a.Ya,a.Ya=a.Na=void 0),!0):!1}
function rb(a,b,c){D.call(this,a,b,c);this.X=16;this.w=1;this.o=["(",")"];this.j={};this.S=gb(this,hb);this.Da=this.S.Da;this.K=gb(this,sb);this.H=fb(this,this.S.O.busIO);this.a=fb(this,this.S.O.busMemory);this.m=this.a.h;this.M=Math.pow(2,this.m)-1|0;this.L=0;this.c=[];for(var d in F)this.c[F[d]]=[];this.i=[];this.i[F.ja]=this.a;this.i[F.Ba]=this.a;this.i[F.xa]=this.H;this.i[F.ya]=this.H;this.f=[];this.f[F.ja]=this.nc.bind(this);this.f[F.Ba]=this.oc.bind(this);this.f[F.xa]=this.lc.bind(this);this.f[F.ya]=
this.mc.bind(this);this.b=[];this.h=0;this.time=gb(this,tb);this.s=ub();this.l=0;this.g=[];this.v=!1;a=this.vc.bind(this);b=Ha.$a;Ia[this.N]||(Ia[this.N]={});Ia[this.N][b]||(Ia[this.N][b]=[]);Ia[this.N][b].push(a)}n(rb,D);function vb(a,b,c){b.R=b.R+c&a.a.i}function ub(a){a=void 0===a?0:a;var b=wb.Qb;return"number"==typeof a?{R:a,Va:-1,type:b}:{R:a.R,Va:a.Va,type:a.type}}
function xb(a,b){if(b){var c=0,d=b.charAt(c);var e=ub();switch(d){case "&":c++;break;case "#":c++;e.type=wb.Rb;break;case "%":c++,d=b.charAt(c),"%"==d?c++:e.type=wb.LINEAR}d=b.indexOf(":");0<=d&&(c=yb(a,b.substring(c,d)),void 0!=c&&(e.Va=c),c=d+1);e.R=yb(a,b.substring(c))&a.M}return e}function zb(a,b,c){a.h++;var d=a.a.ca(b.R);c&&vb(a,b,c);a.h--;return d}function Ab(a,b,c){if(32>=a.m)return b&c;b=Bb(a,b,0,!0);c=Bb(a,c,0,!0);return((b/p|0)&(c/p|0))*p+((b&c)>>>0)}
function Cb(a,b,c){if(32>=a.m)return b^c;b=Bb(a,b,0,!0);c=Bb(a,c,0,!0);return((b/p|0)^(c/p|0))*p+((b^c)>>>0)}
function Db(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var g=b.pop();var h=b.pop();switch(e){case "*":h*=g;break;case "/":if(!g)return!1;h=Math.trunc(h/g);break;case "^/":if(!g)return!1;h%=g;break;case "+":h+=g;break;case "-":h-=g;break;case "<<":h<<=g;break;case ">>":h>>=g;break;case ">>>":h>>>=g;break;case "<":h=h<g?1:0;break;case "<=":h=h<=g?1:0;break;case ">":h=h>g?1:0;break;case ">=":h=h>=g?1:0;break;case "==":h=h==g?1:0;break;case "!=":h=h!=g?1:0;break;
case "&":h=Ab(a,h,g);break;case "!":case "|":e=h;32>=a.m?h=e|g:(e=Bb(a,e,0,!0),g=Bb(a,g,0,!0),h=(e/p|0|g/p|0)*p+((e|g)>>>0));break;case "^!":h=Cb(a,h,g);break;case "&&":h=h&&g?1:0;break;case "||":h=h||g?1:0;break;case ",,":h=Bb(a,h,18,!0)*Math.pow(2,18)+Bb(a,g,18,!0);break;case "_":case "^_":"^_"==e&&(g=35-(g&255));g&&(h=Bb(a,h,0,!0),h=0<g?h*Math.pow(2,g):Math.trunc(h/Math.pow(2,-g)));break;default:return!1}b.push(Bb(a,h))}return!0}
function Eb(a,b,c,d,e,g){var h,m=!1,l=0,k=[],q=[],w=a.X;for(a.X=e;c<d;){var v=b[c++].trim();var t=c<d?b[c++]:"";if(v){var r=void 0;var u=a;var J=v,A=g;l=void 0===l?0:l;if(void 0!=J){r=(r=u.Da[J.toUpperCase()])&&r.get();if(void 0==r)if(r=J,u.j[r]?r=u.j[r].value:(r=r.substr(0,6),r=u.j[r]&&u.j[r].value),void 0!=r){if(J=u.j[J]&&u.j[J].Ri)A?A.push(J):(A=yb(u,J,A),void 0!==A?r+=A:r=void 0)}else r=pa(J,1<J.length||10<u.X?u.X:10);void 0!=r&&(r=Bb(u,Fb(u,r,l)))}u=r}else if("{"==t){v=1;for(u=c;c<d;)if(c++,
t=c<b.length?b[c++]:"","{"==t)v++;else if("}"==t&&!--v)break;u=Eb(a,b,u,c-1,a.X,g);null!=u&&l&&(u=Fb(a,u,l));v=c<d?b[c++].trim():"";t=c<d?b[c++]:""}else{if(" "==t)continue;if("^B"==t){a.X=2;continue}if("^O"==t){a.X=8;continue}if("^D"==t){a.X=10;continue}if(!(l&-1073741824)){if("+"==t)continue;if("-"==t){l=l<<2|1;continue}if("~"==t||"^-"==t){l=l<<2|2;continue}if("^L"==t){l=l<<2|3;continue}}m=!0;break}if(void 0===u)if(g)g.push(v),u=0;else{m=!0;g=[];break}k.push(Bb(a,u));if(" "==t)if(c<b.length-1&&!b[c])c++,
t=b[c++];else{m=!0;break}if(!t)break;u="<"==a.o[0]?Gb:Hb;if(!u[t]){m=!0;break}q.length&&u[t]<=u[q[q.length-1]]&&Db(a,k,q,1);q.push(t);a.X="^_"==t?10:e;l=0}if(m||!Db(a,k,q)||1!=k.length)m=!0;m?g||x(a,"parse error ("+(v||t)+")"):h=k.pop();a.X=w;return h}
function Ib(a,b,c,d,e){for(var g;0<=(g=b.indexOf(c));){for(var h=0,m=g+1,l=e;m<b.length;){var k=b[m++];if(k==c){l=-1;break}if(!l)break;l--;k=k.charCodeAt(0);7==d?k&=127:k=k-32&63;h=Bb(a,h*Math.pow(2,d)+k,d*e,!0)}if(0<=l){x(a,"parse error ("+c+b+c+")");return}b=b.substr(0,g)+qa(a,h)+b.substr(m)}return b}
function yb(a,b,c){var d=void 0;if(b){"{"!=a.o[0]&&(b=b.split(a.o[0]).join("{").split(a.o[1]).join("}"));b=Ib(a,b,'"',7,5);if(!b)return d;b=Ib(a,b,"'",6,6);if(!b)return d;16!=a.X&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);d=Eb(a,b,0,b.length,a.X,c)}return d}
function Fb(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-Bb(a,b);break;case 2:b=Cb(a,b,-1);break;case 3:for(d=35;0<=d&&!Ab(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function Bb(a,b,c,d){var e=b;c=c||a.m;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}f=rb.prototype;
f.fb=function(a){function b(m){for(var l=0;l<m.length;l++)if(void 0!=m[l])return!1;return!0}if(-1>a)return Jb(this,this.fb);var c="";if(0<=a){var d=this.b[a];if(void 0!=d){c=d>>8;d&=255;var e=this.i[c],g=this.c[c],h=g[d];void 0!=h?(h>=p&&(h=h-p|0),(c&1?qb(e,h,this.f[c]):pb(e,h,this.f[c]))?(g[d]=void 0,this.b[a]=void 0,b(g)&&(g.length=0,b(this.b)&&(this.b.length=0)),c=this.J("%2d: %s %#0x cleared\n",a,Kb[c],h),--this.L||this.v||(c+=Lb(this,!1))):c=this.J("invalid break address: %#0x\n",h)):c=this.J("no break address at index: %d\n",
a)}else c=this.J("invalid break index: %d\n",a)}else c="missing break index\n";return c};
f.Sa=function(a,b){b=void 0===b?!1:b;if(-1>a)return Jb(this,this.Sa,b);if(0<=a){var c=this.b[a];if(void 0!=c){var d=!0,e=c>>8;c&=255;var g=this.c[e],h=g[c];if(void 0!=h){var m=b?"enabled":"disabled";if(h<p){var l=h;b?d=!1:h=(h>>>0)+p}else l=h-p|0,b?h=l:d=!1;d?(g[c]=h,a=this.J("%2d: %s %#0x %s\n",a,Kb[e],l,m)):a=this.J("%2d: %s %#0x already %s\n",a,Kb[e],l,m)}else a=this.J("no break address at index: %d\n",a)}else a=this.J("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function Jb(a,b,c){for(var d="",e=0;e<a.b.length;e++)void 0!=a.b[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function Mb(a){for(var b="",c=0;c<a.b.length;c++){var d=a.b[c];if(void 0!=d){var e=d>>8;d=a.c[e][d&255];var g="enabled";d>=p&&(g="disabled",d=d-p|0);b+=a.J("%2d: %s %#0x %s\n",c,Kb[e],d,g)}}b||(b="no break addresses found\n");return b}
function Nb(a,b,c){function d(m,l){var k;for(k=0;k<a.b.length&&void 0!=a.b[k];k++);a.b[k]=m<<8|l;return k}function e(m,l){var k=m.indexOf(l.R);0>k&&(k=m.indexOf((l.R>>>0)+p));if(0<=k)k=-(k+1);else{for(k=0;k<m.length&&void 0!=m[k];k++);m[k]=l.R}return k}c=void 0===c?F.ja:c;var g="";if(b){g=a.i[c];var h=e(a.c[c],b);0<=h?(g=c&1?ob(g,b.R,a.f[c]):nb(g,b.R,a.f[c]))?(h=d(c,h),g=a.J("%2d: %s %#0x set\n",h,Kb[c],b.R),a.L++||a.v||(g+=Lb(a,!0))):(g=a.J("invalid break address: %#0x\n",b.R),a.c[c][h]=void 0):
g=a.J("%s %#0x already set\n",Kb[c],b.R)}else g="missing break address\n";return g}f.lc=function(a,b){this.h||0<=this.c[F.xa].indexOf(a)&&Ob(this,this.J("break on input %#0x: %#0x",a,b))};f.mc=function(a,b){this.h||0<=this.c[F.ya].indexOf(a)&&Ob(this,this.J("break on output %#0x: %#0x",a,b))};f.nc=function(a,b){this.h||(this.g.length&&0==(a-this.S.c&-4)&&(this.g[this.l++]=a,this.l==this.g.length&&(this.l=0)),0<=this.c[F.ja].indexOf(a)&&Ob(this,this.J("break on read %#0x: %#0x",a,b)))};
f.oc=function(a,b){this.h||0<=this.c[F.Ba].indexOf(a)&&Ob(this,this.J("break on write %#0x: %#0x",a,b))};function Ob(a,b){x(a,b);Pb(a.time)}function Qb(a,b){var c=void 0===c?10:c;var d="";0>b&&(b=c);b=a.l-b;0>b&&(b+=a.g.length);for(var e,g=[];0<=b&&b<a.g.length&&0<c;){var h=a.g[b++];if(b==a.g.length){if(d)break;b=0}if(void 0!=h||g.length){e||(e=ub(h));if(h!=e.R||g.length==a.w)vb(a,e,-g.length),d+=a.Wa(e,g),c--;void 0!=h&&(e.R=h,g.push(zb(a,e,1)))}}return d||"no history"}
function Rb(a,b,c){var d=[],e="";for(b="number"==typeof b?ub(b):b;c--;){for(vb(a,b,d.length);d.length<a.w;)d.push(zb(a,b,1));vb(a,b,-d.length);e+=a.Wa(b,d)}return e}
function Tb(a,b,c,d,e){var g="";c||(c=a.a.f);var h=c>>3;d||(d=128);var m=0,l=d+15>>4||1,k=4==h?16:a.X;"y"==e&&(k=h,l=d,m=8*h);b||(b=a.s);for(;l--&&0<d;){var q=e=0,w,v="",t="",r=qa(a,b.R,a.X,a.a.h);for(w=k;0<w&&0<d;w--){var u=zb(a,b,1);e|=u<<(q++<<3);q==h&&(v+=qa(a,e,0,c),v+=1==h?9==w?"-":" ":" ",m&&(t+=qa(a,e,2,c)),e=q=0);m||(t+=32<=u&&127>u?String.fromCharCode(u):".");d--}g&&(g+="\n");g+=r+"  "+v+" "+t}a.s=b;return g}
function Ub(a,b,c){for(var d=0,e="",g=0;void 0!=b&&g<c.length;g++){var h=zb(a,b);if(void 0==h)break;var m=a,l=b,k=c[g];m.h++;m.a.aa(l.R,k);m.h--;e+=a.J("%#06x: %#0x changed to %#0x\n",b.R,h,c[g]);vb(a,b,1);d++}d||(e+=a.J("%d locations updated\n",d));Vb(a.time);return e}
function Lb(a,b){if(void 0==b)return"unrecognized option";mb(a.a,function(c){for(var d=c.fa,e=0;e<c.size;d++,e++)b?nb(a.a,d,a.f[F.ja]):pb(a.a,d,a.f[F.ja])})&&(a.l=0,a.g=b?Array(Wb):[]);return a.J("instruction history %s\n",b?"enabled":"disabled")}
f.vc=function(a){var b="",c=[];var d=a[1];if("*"==a[2])var e=-2;else{e=pa(a[2]);void 0==e&&(e=-1);var g=xb(this,a[2])}var h=0;a[3]&&(h=pa(a[3].substr("l"==a[3][0]?1:0))||8);for(var m=3;m<a.length;m++)c.push(pa(a[m],16));switch(d[0]){case "b":"c"==d[1]?b=this.fb(e):"d"==d[1]?b=this.Sa(e):"e"==d[1]?b=this.Sa(e,!0):"i"==d[1]?b=Nb(this,g,F.xa):"l"==d[1]?b=Mb(this):"o"==d[1]?b=Nb(this,g,F.ya):"r"==d[1]?b=Nb(this,g,F.ja):"w"==d[1]?b=Nb(this,g,F.Ba):(b="break commands:\n",Xb.forEach(function(l){b+=l+"\n"}));
break;case "d":if("b"!=d[1]&&d[1])if("w"==d[1])c=16;else if("d"==d[1])c=32;else{"h"==d[1]?b=Qb(this,e):(b="dump commands:\n",Yb.forEach(function(l){b+=l+"\n"}));break}else c=8;b=Tb(this,g,c,h,d[2]);break;case "e":b=Ub(this,g,c);break;case "g":this.time.start()?(void 0!=g&&Nb(this,g),this.K&&Zb(this.K)):b="already started\n";break;case "h":Pb(this.time)||(b="already stopped\n");break;case "p":a.shift();a.shift();d=a.join(" ");this.I("%s = %s\n",d,qa(this,yb(this,d)));break;case "r":void 0!=g&&this.S.lb(d.substr(1),
g.R);b+=this.S.toString(d[1]);break;case "s":g=Xa(a[2]);"h"==d[1]?(this.v=g,b=Lb(this,g)):(b="set commands:\n",$b.forEach(function(l){b+=l+"\n"}));break;case "t":h=pa(a[2],10)||1;ac(this.time,h);break;case "u":h||(h=8);g||(g=this.s);b+=Rb(this,g,h);this.s=g;break;case "?":b="debugger commands:\n";bc.forEach(function(l){b+=l+"\n"});break;default:b=void 0}void 0==b&&a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n");return b};
f.Wa=function(a,b){var c=this;return this.J("%s %02x         unsupported\n",qa(this,a.R,this.X,this.a.h),function(){var d=b.shift();vb(c,a,1);return d}())};
var bc="b?\t\tbreak commands;d?\t\tdump commands;e [addr] ...\tedit memory;g [addr]\trun (to addr);h\t\thalt;p [expr]\tparse expression;r[a]\t\tdump (all) registers;s?\t\tset commands;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";"),Xb="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write".split(";"),Yb=
["db  [addr]\tdump bytes (8 bits)","dw  [addr]\tdump words (16 bits)","dd  [addr]\tdump dwords (32 bits)","d*y [addr]\tdump values in binary"],$b=["sh [on|off]\tset instruction history"],wb={LINEAR:1,Qb:0,Rb:2,Ii:0},F={ja:0,Ba:1,xa:2,ya:3},cc={},Kb=(cc[F.ja]="br",cc[F.Ba]="bw",cc[F.xa]="bi",cc[F.ya]="bo",cc),dc={Pb:"PC"},Wb=1E5,Hb={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},
Gb={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};
function E(a,b,c){D.call(this,a,b,c);this.fa=c.addr;this.size=c.size;this.type=c.type||lb.NONE;this.width=c.width||8;this.values=c.values||Array(this.size);this.j=Math.pow(2,this.width)-1;this.c=!1;switch(this.type){case lb.NONE:this.ca=this.l;this.aa=this.i;break;case lb.Ra:this.ca=this.Ma;this.aa=this.i;break;case lb.za:this.ca=this.Ma,this.aa=this.mb}}n(E,D);E.prototype.l=function(){return this.j};E.prototype.Ma=function(a){return this.values[a]};E.prototype.i=function(){};
E.prototype.mb=function(a,b){this.values[a]=b;this.c=!0};var lb={NONE:0,Ra:1,za:2};function ec(a,b,c){E.call(this,a,b,c)}n(ec,E);var fc={NONE:0,Hi:1,cb:2};
function gc(a,b,c){D.call(this,a,b,c);this.time=gb(this,tb);this.K=this.H=this.ba=null;this.ua=B(this,"drag",!1);this.W=B(this,"scroll",!1);this.ha=B(this,"hexagonal",!1);this.c=B(this,"buttonDelay",0);this.g=!1;if((this.a=this.O.map)&&!this.a.length)for(a=Object.keys(this.a),b=0;b<a.length;b++){c=a[b];var d=this.a[c];"string"==typeof d&&(d=[d]);this.a[c]={uc:d,state:0}}this.b=null;if(a=this.V[hc])this.b=this.V[ic],jc(this,a,!0,this.O.location);this.L=this.Y=-1}n(gc,D);
gc.prototype.ra=function(a,b){var c=this;switch(a){case ic:b.onclick=function(){c.ba&&c.ba()};break;case kc:b.onclick=function(){c.H&&c.H()}}D.prototype.ra.call(this,a,b)};function lc(a,b){a.K=b}
function jc(a,b,c,d){d=void 0===d?[]:d;a.wa=d[0]||0;a.pa=d[1]||0;a.f=d[2]||b.clientWidth;a.l=d[3]||b.clientHeight;a.m=d[4]||1;a.v=d[5]||1;a.na=d[6]||b.naturalWidth||a.f;a.ta=d[7]||b.naturalHeight||a.l;a.da=d[8]||0;a.ea=d[9]||0;a.ma=d[10]||0;a.oa=d[11]||0;a.a&&a.a.length?(a.s=a.a.length,a.i=a.a[0].length):(a.i=a.m,a.s=a.v,a.m=a.v=0);a.M=a.f/(a.i+a.i*a.m)|0;a.T=a.l/(a.s+a.s*a.v)|0;a.ia=a.M*a.m|0;a.U=a.T*a.v|0;a.j=a.w=-1;mc(a,b);nc(a,b);a.time&&(a.c&&(a.Z=oc(a.time,"timerInputRelease",function(){0>a.j&&
0>a.w&&pc(a,-1,-1)})),a.a&&(a.c&&(a.va=oc(a.time,"timerKeyRelease",function(){qc(a)})),a.h=0,a.o=[],rc(a,c?document:b),a.b||c||(a.b=b)))}function sc(a){a.c?tc(a.time,a.va,a.c):qc(a)}
function rc(a,b){b.addEventListener("keydown",function(c){c=c||window.event;var d=document.activeElement;if(!a.b||d==a.b){d=c.which||c.keyCode;var e=cb[d],g=!1;e&&(g=uc(a,e,!0));a.I(1536,"onKeyDown(keyCode=%#04x): %5.2f (%s)\n",d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()}});b.addEventListener("keypress",function(c){c=c||window.event;var d=c.which||c.charCode,e=String.fromCharCode(d),g=!1;e&&(g=uc(a,e.toUpperCase()));a.I(1536,"onKeyPress(charCode=%#04x): %5.2f (%s)\n",
d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()});b.addEventListener("keyup",function(c){c=c||window.event;var d=document.activeElement;a.b&&d!=a.b||(c=c.which||c.keyCode,(d=cb[c])&&uc(a,d,!1),a.I(1536,"onKeyUp(keyCode=%#04x): %5.2f (ignored)\n",c,Date.now()/1E3%60))})}
function mc(a,b){b.addEventListener("mousedown",function(c){if(!a.g){if(a.b){var d=window.scrollX,e=window.scrollY;a.b.focus();window.scrollTo(d,e)}c.button||vc(a,b,wc,c)}});b.addEventListener("mousemove",function(c){a.g||vc(a,b,xc,c)});b.addEventListener("mouseup",function(c){a.g||c.button||vc(a,b,yc,c)});b.addEventListener("mouseout",function(c){a.g||(0>a.j?vc(a,b,xc,c):vc(a,b,yc,c))})}
function nc(a,b){b.addEventListener("touchstart",function(c){a.W&&(a.g=!0);vc(a,b,wc,c)});b.addEventListener("touchmove",function(c){vc(a,b,xc,c)});b.addEventListener("touchend",function(c){vc(a,b,yc,c)})}
function uc(a,b,c){if(a.a)if(a.a.length){if(!1===c)return!0;for(c=0;c<a.a.length;c++)for(var d=a.a[c],e=0;e<d.length;e++)if(0<=d[e].split("|").indexOf(b))return a.h?16>a.o.length&&a.o.push(b):(a.h=1,pc(a,e,c),sc(a)),!0}else if(void 0!=c)for(d=Object.keys(a.a),e=0;e<d.length;e++){var g=d[e];if(0<=a.a[g].uc.indexOf(b))return a.a[g].state=c?1:0,!0}a.I("unrecognized key '%s' (0x%02x)\n",b,b.charCodeAt(0));return!1}function qc(a){1==a.h?(a.h++,pc(a,-1,-1),sc(a)):(a.h=0,a.o.length&&uc(a,a.o.shift()))}
function vc(a,b,c,d){var e=-1,g=-1,h=!1,m;if(c<yc){d=d||window.event;if(d.targetTouches&&d.targetTouches.length){var l=d.targetTouches[0].pageX;var k=d.targetTouches[0].pageY;h=1<d.targetTouches.length}else l=d.pageX,k=d.pageY;var q=m=0;var w=b;do isNaN(w.offsetLeft)||(m+=w.offsetLeft,q+=w.offsetTop);while(w=w.offsetParent);l=a.na/b.offsetWidth*(l-m)|0;k=a.ta/b.offsetHeight*(k-q)|0;b=l-a.wa;var v=k-a.pa;q=m=!1;w=l>=a.da&&l<a.da+a.ma&&k>=a.ea&&k<a.ea+a.oa;if(0<=b&&b<a.f&&0<=v+a.U||w)if(h||a.W||d.preventDefault(),
0<=b&&b<a.f&&0<=v&&v<a.l){q=!0;d=a.f/a.i|0;var t=a.l/a.s|0,r=b/d|0,u=v/t|0;!a.ha||u&1||(b-=d>>1,r=b/d|0,r==a.i-1&&(b=-1));t=u*t+(a.U>>1);b-=r*d+(a.ia>>1);v-=t;0<=b&&b<a.M&&0<=v&&v<a.T&&(e=r,g=u,m=!0)}}if(!h)if(c==wc)a.j=l,a.w=k,q?(pc(a,e,g),m&&a.c&&tc(a.time,a.Z,a.c,!0)):w&&a.ba&&a.ba();else if(c==xc)0<=a.j&&0<=a.w&&a.ua?pc(a,e,g):a.K&&a.K(e,g);else if(c==yc){if(c=a.c)c=a.time,e=a.Z,c=c.a&&0<e&&e<=c.b.length?0<=c.b[e-1].$:!1;c||pc(a,-1,-1);a.j=a.w=-1}else x(a,"unrecognized action: "+c)}
function Zb(a){a.b&&a.b.focus()}function pc(a,b,c){if(b!=a.L||c!=a.Y)a.L=b,a.Y=c}var wc=1,xc=2,yc=3,ic="power",kc="reset",hc="surface";
function zc(a,b,c){D.call(this,a,b,c);a=this.V[Ac];if(!a)throw Error("LED binding for '"+Ac+"' missing: '"+this.O.V[Ac]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.type=Pa(B(this,"type",Bc),Cc,Dc);this.b=Ec[this.type][0];this.g=Ec[this.type][1];this.width=B(this,"width",this.b);this.height=B(this,"height",this.g);this.c=B(this,"cols",1);this.o=this.c+B(this,"colsExtra",
0);this.M=B(this,"rows",1);this.w=this.M+B(this,"rowsExtra",0);this.Xa=this.width*this.c;this.Ta=this.height*this.M;this.j=Fc("black",0);this.f=Gc(this.O.color)||this.j;this.Z=Fc(this.f,1,.25);this.Y=Fc(this.f,1,2);this.i=Gc(this.O.backgroundColor);this.da=B(this,"fixed",!1);this.da||(b.style.width="100%",b.style.height="auto");this.W=B(this,"hexagonal",!1);this.ea=B(this,"highlight",!0);this.H=B(this,"persistent",this.type<Dc);b.setAttribute("width",this.Xa.toString());b.setAttribute("height",this.Ta.toString());
b.style.backgroundColor=this.j;a.appendChild(b);this.U=b.getContext("2d");if(this.h=document.createElement("canvas"))this.h.width=this.T=this.b*this.c,this.h.height=this.l=this.g*this.M,this.a=this.h.getContext("2d");this.ha=(this.w+1)*this.o*4;this.buffer=Array(this.ha);this.ia=this.c<this.o?4*(this.o-this.c):0;this.s=this.v=!1;this.m=this.L=0;this.K=-1;var d=this;(this.time=gb(this,tb))&&Hc(this.time,function(e){Ic(d,!1,e)})}n(zc,D);
function Jc(a){for(var b=a.buffer,c=0;c<b.length;c+=4){var d=a,e=b,g=c;e[g]=d.type<Dc?Kc:" ";e[g+1]=d.f==d.j?null:d.f;e[g+2]=0;e[g+3]=Lc}a.s=a.v=!0;Ic(a,!0)}function Mc(a){a.i?(a.a.fillStyle=a.i,a.a.fillRect(0,0,a.T,a.l)):a.a.clearRect(0,0,a.T,a.l)}
function Ic(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.s||b){if(a.type<Dc){var d=0;if(!a.H||b)Mc(a);else if(a.m){d=a.c-a.m;var e=a.b*d;a.a.drawImage(a.h,a.b*a.m,0,e,a.l,0,0,e,a.l)}for(var g=e=0;g<a.w;g++){for(var h=0;h<a.c;h++){var m=a.buffer[e],l=a.buffer[e+1]||a.j,k=a.ea&&e==a.K;if(a.buffer[e+3]&Lc||k||b){if(h>=d)a:{var q=a,w=m;m=l;var v=h;l=g;var t=k;v=void 0===v?0:v;l=void 0===l?0:l;t=void 0===t?!1:t;var r=0;if(q.W&&!(l&1)&&(r=q.b>>1,v==q.c-1))break a;if(m&&m!=q.f){t=t?Fc(m,1,2):m;var u=Fc(m,
1,.25)}else t=t?q.Y:q.f,u=q.Z;m=!1;w=w?t:u;t==q.j&&(w=q.i,m=!0);t=v*q.b+r;u=l*q.g;q.H&&(v=v*q.b+r,l*=q.g,q.i?(q.a.fillStyle=q.i,q.a.fillRect(v,l,q.b,q.g)):q.a.clearRect(v,l,q.b,q.g));q.a.fillStyle=w;l=Nc[q.type];3==l.length?(q.a.beginPath(),q.a.arc(t+l[0],u+l[1],l[2],0,2*Math.PI),m?(q.a.globalCompositeOperation="destination-out",q.a.fill(),q.a.globalCompositeOperation="source-over"):q.a.fill()):q.a.fillRect(t+l[0],u+l[1],l[2],l[3])}a.buffer[e+3]=k?a.buffer[e+3]|Lc:a.buffer[e+3]&~Lc}e+=4}e+=a.ia}a.m=
0}else{b="";for(d=0;d<a.buffer.length;d+=4)b+=a.buffer[d]||" ",a.buffer[d+3]&Oc&&(b+=".");Mc(a);for(g=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;h=a;k=e;q=g;k=void 0===k?0:k;q=void 0===q?0:q;if(l=Pc[l])for(m=0;m<l.length;m++)if(v=h,r=Qc[l[m]]){w=(void 0===k?0:k)*v.b;t=(void 0===q?0:q)*v.g;v.a.fillStyle=v.f;v.a.beginPath();if(3==r.length)v.a.arc(w+r[0],t+r[1],r[2],0,2*Math.PI);else for(u=0;u<r.length;u+=2)u?v.a.lineTo(w+r[u],t+r[u+1]):v.a.moveTo(w+r[u],t+r[u+1]);v.a.closePath();v.a.fill()}if(++e==
a.c&&(e=0,++g==a.w))break}}a.U.globalCompositeOperation=a.i&&a.f!=a.j?"source-over":"copy";a.U.drawImage(a.h,0,0,a.T,a.l,0,0,a.Xa,a.Ta);a.s=!1;a.K=-1}else a.H||a.v||(!c||!a.L||c-a.L>=(1E3/60|0))&&Jc(a);a.v=!1;c&&(a.L=c)}function Gc(a){return(a=a||void 0)&&Rc[a]||a}
function Fc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=Rc[a]||a;var e=a;var g=16;var h=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);h||(g=10,h=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(h){for(e=1;e<h.length;e++)d[e-1]=Number.parseInt(h[e],g);d.length=e-1;g=!0}else g=!1;if(g){a="rgba(";for(g=0;3>g;g++)h=Math.round(d[g]*c),h=0>h?0:255<h?255:h,a+=h+",";a+=(g<d.length?d[g]:b)+")"}}return a}
var Cc=0,Bc=1,Dc=3,Ac="container",Rc={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",
darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",
goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",
lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",
olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",
slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},Kc=0,Oc=1,Lc=128,Sc={},Nc=(Sc[Cc]=[4,4,4],Sc[Bc]=[16,16,14],Sc[2]=[2,2,28,28],Sc),Ec=[[8,8],[32,32],[32,32],[96,128]],Qc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,
91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Pc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};
function Tc(a,b,c){D.call(this,a,b,c);var d=this;this.Z=document.fullscreenEnabled||Ua("Edge/");this.K=c.monitorWidth||640;this.o=c.monitorHeight||480;var e=this.V[Uc.qb];e||(e=document.createElement("canvas"),e.setAttribute("class","pcjs-monitor"),e.setAttribute("width",c.monitorWidth),e.setAttribute("height",c.monitorHeight),e.style.backgroundColor=c.monitorColor||"black");this.i=e;this.U=b=e.getContext("2d");(a=this.V[Uc.ab])?(this.c=a,a.setAttribute("tabindex","0"),a.appendChild(e)):this.I("unable to find monitor element: %s\n",
Uc.ab);a&&Ua("MSIE")&&(a.onresize=function(l,k,q,w){return function(){k.style.height=(l.clientWidth*w/q|0)+"px"}}(a,e,c.monitorWidth,c.monitorHeight),a.onresize());var g=+(c.aspect||Fa().aspect);a&&g&&.3<=g&&3.33>=g&&(Wa(function(l,k,q){return function(){k.style.height=(l.clientWidth/q|0)+"px"}}(a,e,g)),window.onresize());if(this.O.touchscreen&&a){var h=document.createElement("textarea");h.setAttribute("class","pcjs-overlay");Ua("iOS")&&(h.setAttribute("autocorrect","off"),h.setAttribute("autocapitalize",
"off"),h.style.fontSize="16px");a.appendChild(h)}this.Ea=h||a;(this.v=gb(this,sb))&&jc(this.v,this.Ea);h=c.smoothing;(e=Fa().smoothing)&&(h="true"==e);this.Y=h;this.na=Ja(b,"imageSmoothingEnabled");if(this.b=c.monitorRotate)this.b=this.b%360,0<this.b&&(this.b-=360),-90!=this.b?(this.I("unsupported monitor rotation: %d\n",this.b),this.b=0):(b.translate(0,this.o),b.rotate(this.b*Math.PI/180),b.scale(this.o/this.K,this.K/this.o));if(a&&(c=Ja(a,"requestFullscreen")||Ja(a,"requestFullScreen"))){a.Ca=a[c];
if(c=Ja(document,"on","fullscreenchange")){var m=Ja(document,"fullscreenElement")||Ja(document,"fullScreenElement");document.addEventListener(c,function(){Vc(d,null!=document[m])},!1)}(c=Ja(document,"on","fullscreenerror"))&&document.addEventListener(c,function(){Vc(d)},!1)}!(c=this.V[Uc.bb])||a&&a.Ca||(this.I("FullScreen API not available\n"),c.parentNode.removeChild(c))}n(Tc,D);Tc.prototype.ra=function(a,b){var c=this;switch(a){case Uc.bb:b.onclick=function(){c.Ca()}}};
Tc.prototype.Ca=function(){var a=!1;if(this.c){if(this.c.Ca){a="100%";if(screen&&screen.width&&screen.height){var b=screen.width/screen.height,c=this.K/this.o;b>c&&(a=Math.round(c/b*100)+"%")}this.Z?(this.i.style.width=a,this.i.style.height="auto",this.i.style.display="block",this.i.style.margin="auto"):(this.c.style.width=a,this.c.style.height="auto");this.c.style.backgroundColor="black";this.c.Ca();a=!0}this.v&&Zb(this.v)}return a};
function Vc(a,b){!b&&a.c&&(a.Z?a.i.style.width=a.i.style.height="":a.c.style.width=a.c.style.height="")}var Uc={qb:"canvas",ab:"container",bb:"fullScreen"};function Wc(a,b,c){c.type=lb.za;E.call(this,a,b,c);a=this.O.bus;if(this.a=fb(this,this.O.bus))kb(this.a,c.addr,c.size,lb.za,this);else throw Error(this.J("unable to find bus '%s'",a));}n(Wc,E);
function Xc(a,b,c){c.type=lb.Ra;E.call(this,a,b,c);c.revision&&(this.status="revision "+c.revision+" "+this.status);this.g=gb(this,Yc);kb(this.g,c.addr,c.size,c.type,this);if(G[Zc]&&this.V[Ma]){var d=this;c=G[Zc];this.a=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.f=this.values.length/this.a|0;this.b=new c(a,b+"LEDs",{"class":"LED",bindings:{container:La(this)},type:c.Pi.Ji,cols:this.a,rows:this.f,color:B(this,"colorROM","green"),backgroundColor:B(this,"backgroundColorROM","black"),
persistent:!0}),Jc(this.b);this.h=new gc(a,b+"Input",{"class":"Input",location:[0,0,this.b.Xa,this.b.Ta,this.a,this.f],bindings:{surface:La(this)}});this.m=Na(this)||"";lc(this.h,function(e,g){if(d.S){var h=d.m;0<=e&&0<=g&&(e=g*d.a+e,g=d.S,h=g.L&&Rb(g.L,d.fa+e,1)||"");ab(d,Oa,h)}})}}n(Xc,E);Xc.prototype.ba=function(){this.S||(this.S=gb(this,hb))};
Xc.prototype.Ma=function(a){if(this.b){var b=G[Zc],c=this.b,d=b.Oi.yi;b=b.Th.Xh;b=(void 0===b?0:b)&129;var e=4*((a/this.a|0)*c.o+a%this.a);if(e<=c.buffer.length-4){if(c.buffer[e]!==d||(c.buffer[e+3]&129)!==b)c.buffer[e]=d,c.buffer[e+3]=c.buffer[e+3]&-130|b|Lc,c.s=!0;c.K=e;c.v=!0;c.m=0}}return this.values[a]};var Ma="array",Oa="cellDesc";
function $c(a,b,c){D.call(this,a,b,c);this.na=B(this,"cyclesMinimum",1E5);this.wa=B(this,"cyclesMaximum",3E6);this.U=Pa(B(this,"cyclesPerSecond",65E4),this.na,this.wa);this.K=Pa(B(this,"yieldsPerSecond",ad),30,120);this.pa=Pa(B(this,"yieldsPerUpdate",bd),1,this.K);this.ia=(this.w=B(this,"clockByFrame",120>=this.U))||B(this,"requestAnimationFrame",!0);this.ta=this.ua=this.Z=1;this.ma=this.U/1E4/100;this.h=this.m=this.ma*this.Z;this.s=0;this.ea=Math.round(1E3/this.K);this.ha=[];this.v=[];this.b=[];
this.da=[];this.a=this.L=this.l=!1;this.H=this.g=0;this.Fa=this.hh.bind(this);this.Ea=this.eb.bind(this);this.oa=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);if(this.w)this.f=this.va=0;else{var d=this;oc(this,"timerYield",function(){cd(d)},this.ea)}this.W=this.T=this.j=0;dd(this)||ed(this,this.ta)}n($c,D);function Hc(a,b){a.ha.push(b)}f=$c.prototype;
f.ra=function(a,b){var c=this;switch(a){case fd:b.onclick=function(){c.a?Pb(c):c.start()};break;case gd:b.onclick=function(){ac(c)};break;case hd:b.addEventListener("mousedown",function(){c.l=!0}),b.addEventListener("mouseup",function(){dd(c);c.l=!1}),b.addEventListener("mousemove",function(){c.l&&dd(c)}),b.addEventListener("change",function(){c.l=!0;dd(c);c.l=!1})}D.prototype.ra.call(this,a,b)};
function oc(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,kc:c,Ga:d,$:-1});0<=d&&tc(a,e,d);return e}f.eb=function(a){if(this.w){if(!this.a)return;id(this);try{this.L=!1;do jd(this,kd(this,ld(this,md(this))));while(this.a&&!this.L)}catch(c){x(this,c.message);Pb(this);return}nd(this)}for(var b=0;b<this.ha.length;b++)this.ha[b](a);this.a&&this.ia&&this.oa(this.Ea)};function od(a){var b=a.h/a.ma;if(!b||b>a.Z)b=a.Z;a.Pa=a.U/a.K*b;a.ua=b}
function ld(a,b){a.T=a.j=b;if(!a.v.length)return a.j=0,a.T;for(var c=0;0<a.j;)c<a.v.length?b=a.v[c++](b)||1:c=b=0,a.j-=b;return a.T-a.j}function pd(a,b){var c=Date.now();b()&&(a.M+=Date.now()-c)}function kd(a,b){b=void 0===b?a.T-a.j:b;if(a.w){if(!a.a){if(a.f)for(var c=0;c<a.v.length;c++)a.v[c](-1);a.f=b}a.f-=b;1>a.f&&cd(a)}a.T=a.j=0;a.Y+=b;a.W+=b;a.a||(a.W=0);return b}function qd(a,b){return Math.ceil(a.U*a.ua/1E3*(void 0===b?1E3:b))}
function md(a,b){b=void 0===b?0:b;if(b){var c=b;a.f+=b}else for(c=a.f,1>c&&(c=a.f+=a.va),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.$)&&c>d.$&&(c=d.$)}return c}function rd(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function jd(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.$||(d.$-=b,0>=d.$&&(d.$=-1,d.kc(),0<=d.Ga&&tc(a,c,d.Ga)))}}f.ba=function(){Vb(this,!0)};function ac(a,b){a.a?x(a,"already running"):a.g?Pb(a):sd(a,b)}
function cd(a){a.L=!0;var b=a.s,c=qd(a);c>=a.K?a.s++:a.s+=Math.ceil(a.K/c);a.s>=a.pa&&b<a.pa&&Vb(a);a.s>=a.K&&(a.s=0)}f.hh=function(){this.H=0;if(this.a){id(this);try{this.L=!1;do{for(var a=qd(this,this.ea),b=this.b.length;0<b;b--){var c=this.b[b-1];!(0>c.$)&&a>c.$&&(a=c.$)}jd(this,kd(this,ld(this,a)))}while(this.a&&!this.L)}catch(d){x(this,d.message);Pb(this);return}this.a&&(this.H=setTimeout(this.Fa,nd(this)),this.ia||this.eb())}};
function dd(a){var b=a.V[hd];return b?(ed(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.wa-a.na)+a.na)/a.U),!0):!1}function ed(a,b){void 0!==b&&(!a.l&&0<a.h&&a.h<.9*a.m&&(b=a.ta),a.Z=b,b=a.ma*a.Z,a.m!=b&&(a.m=b,ab(a,td,rd(a.m))),a.h=a.m);a.w&&(a.va=1E6*a.h/60+1E-8,a.f=0);a.W=0;a.c=a.i=0;od(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Ga&&tc(a,b,c.Ga,!0)}}function tc(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.$)&&(c=qd(a,c),a.a&&(c+=kd(a)),b.$=c)}
function id(a){od(a);a.Y=0;a.M=0;a.o=Date.now();a.c||(a.c=a.o);if(a.i){var b=a.o-a.i;b>a.ea&&(a.c+=b,a.c>a.o&&(a.c=a.o))}}function nd(a){a.i=Date.now();a.M&&(a.c+=a.M,a.o+=a.M);var b=a.ea;a.Y&&(b=Math.round(b*a.Y/a.Pa));b-=a.i-a.o;var c=a.i-a.c;c&&(a.h=a.W/(10*c)/100);0>b?(-1E3>b&&(a.c-=b),b=0):a.h<a.m&&(b=0);a.i+=b;a.I(256,"after running %d cycles, resting for %dms\n",a.Y,b);return b}
f.start=function(){if(this.a||this.g)return!1;this.H&&(clearTimeout(this.H),this.H=0);this.a=!0;this.c=this.i=0;Vb(this,!0);this.w||(this.H=setTimeout(this.Fa,0));this.ia&&this.oa(this.Ea);return!0};function sd(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,jd(a,kd(a,ld(a,md(a,1)))),Vb(a,!1),a.g&&setTimeout(function(){sd(a,0)},0)))}function Pb(a){return a.g?(a.g=0,Vb(a,!0),!0):a.a?(a.a=!1,kd(a),Vb(a,!0),!0):!1}
function Vb(a,b){b&&(a.a?x(a,"started with "+rd(a.m)+" target"):x(a,"stopped"));ab(a,fd,a.a?"Halt":"Run");ab(a,gd,a.g?"Stop":"Step");a.l||ab(a,td,a.a&&a.h?rd(a.h):"Stopped");for(var c=0;c<a.da.length;c++)a.da[c](void 0!=b)}var fd="run",td="speed",gd="step",hd="throttle",ad=120,bd=60;
function ud(a,b,c){c.type=fc.cb;E.call(this,a,b,c);a=this.O.bus;if(this.b=fb(this,a))kb(this.b,c.addr,c.size,fc.cb,this);else throw Error(this.J("unable to find bus '%s'",a));this.f=gb(this,sb);this.g=this.a=this.h=0}n(ud,ec);f=ud.prototype;f.rc=function(a){this.I(2,"inStatus0(%d): %#04x\n",a,0);return 0};
f.sc=function(a){for(var b=this.h,c=Object.keys(vd),d=0;d<c.length;d++){var e=vd[c[d]];if(this.f){var g=void 0;var h=this.f;h.a&&!h.a.length&&(h=h.a[c[d]])&&(g=h.state);void 0!=g&&(b=b&~e|(g?e:0))}}this.h=b;this.I(4,"inStatus1(%d): %#04x\n",a,b);return b};f.tc=function(a){this.I(4,"inStatus2(%d): %#04x\n",a,0);return 0};f.qc=function(a){var b=this.a>>8-this.g&255;this.I(4,"inShiftResult(%d): %#04x\n",a,b);return b};f.ah=function(a,b){this.I(4,"outShiftCount(%d): %#04x\n",a,b);this.g=b};
f.dh=function(a,b){this.I(4,"outSound1(%d): %#04x\n",a,b)};f.bh=function(a,b){this.I(4,"outShiftData(%d): %#04x\n",a,b);this.a=b<<8|this.a>>8};f.eh=function(a,b){this.I(4,"outSound2(%d): %#04x\n",a,b)};f.fh=function(a,b){this.I(4,"outWatchDog(%d): %#04x\n",a,b)};f.Ma=function(a){var b=255;a=this.fa+a;var c=wd[a];c&&(b=c.call(this,a));return b};f.mb=function(a,b){a=this.fa+a;var c=xd[a];c&&c.call(this,a,b)};
var wd={0:ud.prototype.rc,1:ud.prototype.sc,2:ud.prototype.tc,3:ud.prototype.qc},xd={2:ud.prototype.ah,3:ud.prototype.dh,4:ud.prototype.bh,5:ud.prototype.eh,6:ud.prototype.fh},vd={"1p":4,"2p":2,coin:1,left:32,right:64,fire:16};
function yd(a,b,c){Tc.call(this,a,b,c);this.T=c.bufferAddr;this.wa=c.bufferRAM;this.Fa=c.bufferWidth;this.Pa=c.bufferHeight;this.ua=c.cellWidth||1;this.va=c.cellHeight||1;this.L=c.bufferBits||1;this.pa=c.bufferLeft||0;if(this.a=c.bufferRotate)this.a=this.a%360,0<this.a&&(this.a-=360),-90!=this.a&&(this.I("unsupported buffer rotation: %d\n",this.a),this.a=0);this.M=c.interruptRate;this.ma=c.refreshRate||60;this.j=gb(this,Yc);this.S=gb(this,hb);a:{this.f=this.Fa*this.ua;this.m=this.Pa*this.va;a=this.f;
b=this.m;this.a&&(a=this.m,b=this.f);this.g=0;if(!this.wa&&(this.g=(this.f*this.L>>3)*this.m,!kb(this.j,this.T,this.g,lb.za)))break a;this.H=this.j.f;this.g&&(this.da=this.U.createImageData(a,b),this.ha=Math.trunc(this.H/this.L),this.ea=Math.ceil(this.g/(this.H>>3)),this.W=!1,void 0===this.w||this.w.length!=this.ea)&&(this.w=Array(this.ea));this.h=document.createElement("canvas");this.h.width=a;this.h.height=b;this.ta=this.h.getContext("2d");this.s=1<<this.L;this.l=Array(this.s+zd);this.l[0]=[0,0,
0,255];this.l[1]=[255,255,255,255];this.l[this.s+Ad]=[255,255,0,255];this.l[this.s+Bd]=[0,255,0,255];this.na&&(this.U[this.na]=null==this.Y?!1:this.Y)}this.time=gb(this,tb);this.oa=oc(this.time,this.sa,this.xb.bind(this));this.time.da.push(this.Bb.bind(this));tc(this.time,this.oa,1E3/Math.max(this.ma,this.M));this.ia=0}n(yd,Tc);
yd.prototype.xb=function(a){var b=!0;if(!a){this.M&&(120==this.M?this.ia&1?(Cd(this.S,2),b=!1):Cd(this.S,1):Cd(this.S,4));if(b&&this.W&&this.g){a=this.j;var c=this.T,d=this.g,e=!0,g=c>>>a.c;for(c=a.a-(c&a.j);0<d&&g<a.b.length;){var h=a.b[g];h.c?(h.c=!1,h=!0):h=!1;h&&(e=!1);d-=c;c=a.a;g++}e&&(b=!1)}tc(this.time,this.oa,1E3/Math.max(this.ma,this.M));this.ia++;if(!b)return}Dd(this)};
function Dd(a){var b=a.T,c=b+a.g,d=0,e=0,g=0,h=a.f,m=0,l=a.m,k=0,q=0,w=a.L,v=(1<<w)-1;a.pa&&(w=-w,q=a.H+w);for(var t=a.H/a.j.f|0;b<c;){var r=a.j.ca(b);if(a.W&&r===a.w[d])e+=a.ha;else{a.w[d]=r;var u=q;u&&(r=r>>8|(r&255)<<8);e<h&&(h=e);for(var J=a.ha;J--;){var A=r>>u&v,ra=a.da,P=e++,ea=A;A=a.a?(ra.height-P-1)*ra.width+g:P+g*ra.width;ea&&(208<=P&&236>P?ea=a.s+Ad:28<=P&&72>P&&(ea=a.s+Bd));P=a.l[ea];A*=P.length;ra.data[A]=P[0];ra.data[A+1]=P[1];ra.data[A+2]=P[2];ra.data[A+3]=P[3];u+=w}e>m&&(m=e);g<l&&
(l=g);g>=k&&(k=g+1)}b+=t;d++;if(e>=a.f&&(e=0,g++,g>a.m))break}a.W=!0;h<a.f&&(b=m-h,k-=l,a.a&&(c=h,d=b,h=l,b=k,l=a.f-(c+d),k=d),a.ta.putImageData(a.da,0,0,h,l,b,k),a.U.drawImage(a.h,0,0,a.h.width,a.h.height,0,0,a.K,a.o))}yd.prototype.Bb=function(){this.time.a||Dd(this)};var Ad=0,Bd=1,zd=2;
function Ed(a,b,c){D.call(this,a,b,c);this.v=this.l=this.j=this.i=this.h=this.g=this.f=this.b=0;this.u(this.Z);this.T=this.c;Fd(this,0);this.H=Gd;this.W=[this.la,this.ie,this.Eg,this.Td,this.Md,this.wd,this.zf,this.bg,this.la,this.rd,this.fe,this.Dd,this.Nd,this.xd,this.Af,this.ig,this.la,this.je,this.Fg,this.Ud,this.Od,this.yd,this.Bf,this.Zf,this.la,this.sd,this.ge,this.Ed,this.Pd,this.zd,this.Cf,this.$f,this.la,this.ke,this.Bg,this.Vd,this.Qd,this.Ad,this.Df,this.qd,this.la,this.td,this.he,this.Fd,
this.Rd,this.Bd,this.Ef,this.Zc,this.la,this.le,this.Dg,this.Wd,this.Sd,this.Cd,this.Ff,this.Gg,this.la,this.ud,this.ee,this.Gd,this.Ld,this.vd,this.yf,this.$c,this.ve,this.we,this.xe,this.ye,this.ze,this.Ae,this.Be,this.ue,this.De,this.Ee,this.Fe,this.Ge,this.He,this.Ie,this.Je,this.Ce,this.Le,this.Me,this.Ne,this.Oe,this.Pe,this.Qe,this.Re,this.Ke,this.Te,this.Ue,this.Ve,this.We,this.Xe,this.Ye,this.Ze,this.Se,this.af,this.bf,this.cf,this.df,this.ef,this.ff,this.gf,this.$e,this.jf,this.kf,this.lf,
this.mf,this.nf,this.pf,this.qf,this.hf,this.sf,this.tf,this.uf,this.vf,this.wf,this.xf,this.Jd,this.rf,this.ne,this.oe,this.pe,this.qe,this.re,this.se,this.te,this.me,this.Gc,this.Hc,this.Ic,this.Jc,this.Kc,this.Lc,this.Mc,this.Fc,this.yc,this.zc,this.Ac,this.Bc,this.Cc,this.Dc,this.Ec,this.xc,this.Ig,this.Jg,this.Kg,this.Lg,this.Mg,this.Ng,this.Og,this.Hg,this.tg,this.ug,this.vg,this.wg,this.xg,this.yg,this.zg,this.sg,this.Pc,this.Qc,this.Rc,this.Sc,this.Tc,this.Uc,this.Vc,this.Oc,this.Sg,this.Tg,
this.Ug,this.Vg,this.Wg,this.Xg,this.Yg,this.Rg,this.Hf,this.If,this.Jf,this.Kf,this.Lf,this.Mf,this.Nf,this.Gf,this.bd,this.cd,this.dd,this.ed,this.fd,this.gd,this.hd,this.ad,this.eg,this.Rf,this.$d,this.jb,this.kd,this.Wf,this.Nc,this.jg,this.rg,this.kb,this.de,this.jb,this.pd,this.Ja,this.wc,this.kg,this.dg,this.Sf,this.Zd,this.Pf,this.jd,this.Xf,this.Pg,this.lg,this.ag,this.kb,this.Xd,this.Kd,this.Xc,this.Ja,this.Ag,this.mg,this.hg,this.Tf,this.ce,this.$g,this.od,this.Yf,this.Wc,this.ng,this.gg,
this.Qf,this.be,this.Qg,this.md,this.Ja,this.Zg,this.og,this.fg,this.Uf,this.ae,this.Hd,this.ld,this.Vf,this.Of,this.pg,this.cg,this.Cg,this.Yd,this.Id,this.Yc,this.Ja,this.nd,this.qg];this.a=this.M=0;a=this.Y=gb(this,sb);b=this.sb.bind(this);a.ba=this.ba.bind(this);a.H=b;this.U=fb(this,this.O.busIO);this.K=fb(this,this.O.busMemory);if(this.time=gb(this,tb))this.time.v.push(this.pc.bind(this)),this.time.da.push(this.ih.bind(this));this.L=void 0;this.Da[dc.Pb]={get:this.gb.bind(this),set:this.u.bind(this)}}
n(Ed,D);f=Ed.prototype;f.pc=function(a){a=void 0===a?0:a;if(0>a)return this.M=0;try{Hd(this,a)}catch(c){this.c=this.T,x(this,c.message),Pb(this.time)}if(0>=a){var b=this;pd(this.time,function(){x(b,b.toString())})}return this.a};function Hd(a,b){a.a=0;a.M=b;if(Id(a))for(;a.a<=a.M;)a.T=a.c,a.W[H(a)].call(a)}
function Jd(a,b){b=b.stateCPU||b[0];if(!b||!b.length)return x(a,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return a.I("saved state version mismatch: %3.2f\n",c),!1;try{a.c=b.shift()}catch(d){return x(a,"CPU state error: "+d.message),!1}return!0}f.hb=function(a){return a&&Jd(this,a)?!0:!1};f.ba=function(a){void 0==a&&(a=!this.time.a)&&(this.c=0);a?this.time.start():Pb(this.time)};f.sb=function(){x(this,"reset");this.c=0;this.time.a||x(this,this.toString())};
f.ib=function(a){var b=[];b.push(2);b.push(this.b);b.push(this.f);b.push(this.g);b.push(this.h);b.push(this.i);b.push(this.j);b.push(this.l);b.push(this.gb);b.push(this.v);b.push(Kd(this));b.push(this.H);a.push(b)};f.la=function(){this.a+=4};f.ie=function(){Ld(this,I(this));this.a+=10};f.Eg=function(){Md(this,Nd(this),this.b);this.a+=7};f.Td=function(){Ld(this,Nd(this)+1);this.a+=5};f.Md=function(){this.f=Od(this,this.f);this.a+=5};f.wd=function(){this.f=Pd(this,this.f);this.a+=5};
f.zf=function(){this.f=H(this);this.a+=7};f.bg=function(){var a=this.b<<1;this.b=a&255|a>>8;Qd(this,a&256);this.a+=4};f.rd=function(){var a;Rd(this,a=K(this)+Nd(this));Qd(this,a>>8&256);this.a+=10};f.fe=function(){this.b=L(this,Nd(this));this.a+=7};f.Dd=function(){Ld(this,Nd(this)-1);this.a+=5};f.Nd=function(){this.g=Od(this,this.g);this.a+=5};f.xd=function(){this.g=Pd(this,this.g);this.a+=5};f.Af=function(){this.g=H(this);this.a+=7};
f.ig=function(){var a=this.b<<8&256;this.b=(a|this.b)>>1;Qd(this,a);this.a+=4};f.je=function(){Sd(this,I(this));this.a+=10};f.Fg=function(){Md(this,Td(this),this.b);this.a+=7};f.Ud=function(){Sd(this,Td(this)+1);this.a+=5};f.Od=function(){this.h=Od(this,this.h);this.a+=5};f.yd=function(){this.h=Pd(this,this.h);this.a+=5};f.Bf=function(){this.h=H(this);this.a+=7};f.Zf=function(){var a=this.b<<1;this.b=a&255|Ud(this);Qd(this,a&256);this.a+=4};
f.sd=function(){var a;Rd(this,a=K(this)+Td(this));Qd(this,a>>8&256);this.a+=10};f.ge=function(){this.b=L(this,Td(this));this.a+=7};f.Ed=function(){Sd(this,Td(this)-1);this.a+=5};f.Pd=function(){this.i=Od(this,this.i);this.a+=5};f.zd=function(){this.i=Pd(this,this.i);this.a+=5};f.Cf=function(){this.i=H(this);this.a+=7};f.$f=function(){var a=this.b<<8;this.b=(Ud(this)<<8|this.b)>>1;Qd(this,a&256);this.a+=4};f.ke=function(){Rd(this,I(this));this.a+=10};
f.Bg=function(){var a=I(this),b=K(this);this.K.aa(a,b&255);this.K.aa(a+1,b>>8&255);this.a+=16};f.Vd=function(){Rd(this,K(this)+1);this.a+=5};f.Qd=function(){this.j=Od(this,this.j);this.a+=5};f.Ad=function(){this.j=Pd(this,this.j);this.a+=5};f.Df=function(){this.j=H(this);this.a+=7};f.qd=function(){var a=0,b=Ud(this);if((this.o^this.s)&16&&Vd||9<(this.b&15))a|=6;if(b||154<=this.b)a|=96,b=Wd;this.b=Xd(this,a);Qd(this,b?256:0);this.a+=4};
f.td=function(){var a;Rd(this,a=K(this)+K(this));Qd(this,a>>8&256);this.a+=10};f.he=function(){Rd(this,Yd(this,I(this)));this.a+=16};f.Fd=function(){Rd(this,K(this)-1);this.a+=5};f.Rd=function(){this.l=Od(this,this.l);this.a+=5};f.Bd=function(){this.l=Pd(this,this.l);this.a+=5};f.Ef=function(){this.l=H(this);this.a+=7};f.Zc=function(){this.b=~this.b&255;this.a+=4};f.le=function(){this.v=I(this)&65535;this.a+=10};f.Dg=function(){Md(this,I(this),this.b);this.a+=13};
f.Wd=function(){this.v=this.v+1&65535;this.a+=5};f.Sd=function(){var a=K(this);Md(this,a,Od(this,L(this,a)));this.a+=10};f.Cd=function(){var a=K(this);Md(this,a,Pd(this,L(this,a)));this.a+=10};f.Ff=function(){Md(this,K(this),H(this));this.a+=10};f.Gg=function(){this.m|=256;this.a+=4};f.ud=function(){var a;Rd(this,a=K(this)+this.v);Qd(this,a>>8&256);this.a+=10};f.ee=function(){this.b=L(this,I(this));this.a+=13};f.Gd=function(){this.v=this.v-1&65535;this.a+=5};
f.Ld=function(){this.b=Od(this,this.b);this.a+=5};f.vd=function(){this.b=Pd(this,this.b);this.a+=5};f.yf=function(){this.b=H(this);this.a+=7};f.$c=function(){Qd(this,Ud(this)?0:256);this.a+=4};f.ve=function(){this.a+=5};f.we=function(){this.f=this.g;this.a+=5};f.xe=function(){this.f=this.h;this.a+=5};f.ye=function(){this.f=this.i;this.a+=5};f.ze=function(){this.f=this.j;this.a+=5};f.Ae=function(){this.f=this.l;this.a+=5};f.Be=function(){this.f=L(this,K(this));this.a+=7};
f.ue=function(){this.f=this.b;this.a+=5};f.De=function(){this.g=this.f;this.a+=5};f.Ee=function(){this.a+=5};f.Fe=function(){this.g=this.h;this.a+=5};f.Ge=function(){this.g=this.i;this.a+=5};f.He=function(){this.g=this.j;this.a+=5};f.Ie=function(){this.g=this.l;this.a+=5};f.Je=function(){this.g=L(this,K(this));this.a+=7};f.Ce=function(){this.g=this.b;this.a+=5};f.Le=function(){this.h=this.f;this.a+=5};f.Me=function(){this.h=this.g;this.a+=5};f.Ne=function(){this.a+=5};
f.Oe=function(){this.h=this.i;this.a+=5};f.Pe=function(){this.h=this.j;this.a+=5};f.Qe=function(){this.h=this.l;this.a+=5};f.Re=function(){this.h=L(this,K(this));this.a+=7};f.Ke=function(){this.h=this.b;this.a+=5};f.Te=function(){this.i=this.f;this.a+=5};f.Ue=function(){this.i=this.g;this.a+=5};f.Ve=function(){this.i=this.h;this.a+=5};f.We=function(){this.a+=5};f.Xe=function(){this.i=this.j;this.a+=5};f.Ye=function(){this.i=this.l;this.a+=5};f.Ze=function(){this.i=L(this,K(this));this.a+=7};
f.Se=function(){this.i=this.b;this.a+=5};f.af=function(){this.j=this.f;this.a+=5};f.bf=function(){this.j=this.g;this.a+=5};f.cf=function(){this.j=this.h;this.a+=5};f.df=function(){this.j=this.i;this.a+=5};f.ef=function(){this.a+=5};f.ff=function(){this.j=this.l;this.a+=5};f.gf=function(){this.j=L(this,K(this));this.a+=7};f.$e=function(){this.j=this.b;this.a+=5};f.jf=function(){this.l=this.f;this.a+=5};f.kf=function(){this.l=this.g;this.a+=5};f.lf=function(){this.l=this.h;this.a+=5};
f.mf=function(){this.l=this.i;this.a+=5};f.nf=function(){this.l=this.j;this.a+=5};f.pf=function(){this.a+=5};f.qf=function(){this.l=L(this,K(this));this.a+=7};f.hf=function(){this.l=this.b;this.a+=5};f.sf=function(){Md(this,K(this),this.f);this.a+=7};f.tf=function(){Md(this,K(this),this.g);this.a+=7};f.uf=function(){Md(this,K(this),this.h);this.a+=7};f.vf=function(){Md(this,K(this),this.i);this.a+=7};f.wf=function(){Md(this,K(this),this.j);this.a+=7};
f.xf=function(){Md(this,K(this),this.l);this.a+=7};f.Jd=function(){var a=this.c-1;this.a+=7;this.H|=Zd;kd(this.time);this.L&&Ta(4096)?(this.u(a),Pb(this.time)):this.w&$d||(this.L&&this.u(a),Pb(this.time))};f.rf=function(){Md(this,K(this),this.b);this.a+=7};f.ne=function(){this.b=this.f;this.a+=5};f.oe=function(){this.b=this.g;this.a+=5};f.pe=function(){this.b=this.h;this.a+=5};f.qe=function(){this.b=this.i;this.a+=5};f.re=function(){this.b=this.j;this.a+=5};f.se=function(){this.b=this.l;this.a+=5};
f.te=function(){this.b=L(this,K(this));this.a+=7};f.me=function(){this.a+=5};f.Gc=function(){this.b=Xd(this,this.f);this.a+=4};f.Hc=function(){this.b=Xd(this,this.g);this.a+=4};f.Ic=function(){this.b=Xd(this,this.h);this.a+=4};f.Jc=function(){this.b=Xd(this,this.i);this.a+=4};f.Kc=function(){this.b=Xd(this,this.j);this.a+=4};f.Lc=function(){this.b=Xd(this,this.l);this.a+=4};f.Mc=function(){this.b=Xd(this,L(this,K(this)));this.a+=7};f.Fc=function(){this.b=Xd(this,this.b);this.a+=4};
f.yc=function(){this.b=ae(this,this.f);this.a+=4};f.zc=function(){this.b=ae(this,this.g);this.a+=4};f.Ac=function(){this.b=ae(this,this.h);this.a+=4};f.Bc=function(){this.b=ae(this,this.i);this.a+=4};f.Cc=function(){this.b=ae(this,this.j);this.a+=4};f.Dc=function(){this.b=ae(this,this.l);this.a+=4};f.Ec=function(){this.b=ae(this,L(this,K(this)));this.a+=7};f.xc=function(){this.b=ae(this,this.b);this.a+=4};f.Ig=function(){this.b=M(this,this.f);this.a+=4};
f.Jg=function(){this.b=M(this,this.g);this.a+=4};f.Kg=function(){this.b=M(this,this.h);this.a+=4};f.Lg=function(){this.b=M(this,this.i);this.a+=4};f.Mg=function(){this.b=M(this,this.j);this.a+=4};f.Ng=function(){this.b=M(this,this.l);this.a+=4};f.Og=function(){this.b=M(this,L(this,K(this)));this.a+=7};f.Hg=function(){this.b=M(this,this.b);this.a+=4};f.tg=function(){this.b=be(this,this.f);this.a+=4};f.ug=function(){this.b=be(this,this.g);this.a+=4};f.vg=function(){this.b=be(this,this.h);this.a+=4};
f.wg=function(){this.b=be(this,this.i);this.a+=4};f.xg=function(){this.b=be(this,this.j);this.a+=4};f.yg=function(){this.b=be(this,this.l);this.a+=4};f.zg=function(){this.b=be(this,L(this,K(this)));this.a+=7};f.sg=function(){this.b=be(this,this.b);this.a+=4};f.Pc=function(){this.b=ce(this,this.f);this.a+=4};f.Qc=function(){this.b=ce(this,this.g);this.a+=4};f.Rc=function(){this.b=ce(this,this.h);this.a+=4};f.Sc=function(){this.b=ce(this,this.i);this.a+=4};
f.Tc=function(){this.b=ce(this,this.j);this.a+=4};f.Uc=function(){this.b=ce(this,this.l);this.a+=4};f.Vc=function(){this.b=ce(this,L(this,K(this)));this.a+=7};f.Oc=function(){this.b=ce(this,this.b);this.a+=4};f.Sg=function(){this.b=de(this,this.f);this.a+=4};f.Tg=function(){this.b=de(this,this.g);this.a+=4};f.Ug=function(){this.b=de(this,this.h);this.a+=4};f.Vg=function(){this.b=de(this,this.i);this.a+=4};f.Wg=function(){this.b=de(this,this.j);this.a+=4};
f.Xg=function(){this.b=de(this,this.l);this.a+=4};f.Yg=function(){this.b=de(this,L(this,K(this)));this.a+=7};f.Rg=function(){this.b=de(this,this.b);this.a+=4};f.Hf=function(){this.b=ee(this,this.f);this.a+=4};f.If=function(){this.b=ee(this,this.g);this.a+=4};f.Jf=function(){this.b=ee(this,this.h);this.a+=4};f.Kf=function(){this.b=ee(this,this.i);this.a+=4};f.Lf=function(){this.b=ee(this,this.j);this.a+=4};f.Mf=function(){this.b=ee(this,this.l);this.a+=4};
f.Nf=function(){this.b=ee(this,L(this,K(this)));this.a+=7};f.Gf=function(){this.b=ee(this,this.b);this.a+=4};f.bd=function(){M(this,this.f);this.a+=4};f.cd=function(){M(this,this.g);this.a+=4};f.dd=function(){M(this,this.h);this.a+=4};f.ed=function(){M(this,this.i);this.a+=4};f.fd=function(){M(this,this.j);this.a+=4};f.gd=function(){M(this,this.l);this.a+=4};f.hd=function(){M(this,L(this,K(this)));this.a+=7};f.ad=function(){M(this,this.b);this.a+=4};
f.eg=function(){fe(this)||(this.u(ge(this)),this.a+=6);this.a+=5};f.Rf=function(){Ld(this,ge(this));this.a+=10};f.$d=function(){var a=I(this);fe(this)||this.u(a);this.a+=10};f.jb=function(){this.u(I(this));this.a+=10};f.kd=function(){var a=I(this);fe(this)||(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Wf=function(){N(this,Nd(this));this.a+=11};f.Nc=function(){this.b=Xd(this,H(this));this.a+=7};f.jg=function(){N(this,this.c);this.u(0);this.a+=11};
f.rg=function(){fe(this)&&(this.u(ge(this)),this.a+=6);this.a+=5};f.kb=function(){this.u(ge(this));this.a+=10};f.de=function(){var a=I(this);fe(this)&&this.u(a);this.a+=10};f.pd=function(){var a=I(this);fe(this)&&(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Ja=function(){var a=I(this);N(this,this.c);this.u(a);this.a+=17};f.wc=function(){this.b=ae(this,H(this));this.a+=7};f.kg=function(){N(this,this.c);this.u(8);this.a+=11};f.dg=function(){Ud(this)||(this.u(ge(this)),this.a+=6);this.a+=5};
f.Sf=function(){Sd(this,ge(this));this.a+=10};f.Zd=function(){var a=I(this);Ud(this)||this.u(a);this.a+=10};f.Pf=function(){var a=H(this);this.U.aa(a,this.b,this.c+-2&65535);this.a+=10};f.jd=function(){var a=I(this);Ud(this)||(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Xf=function(){N(this,Td(this));this.a+=11};f.Pg=function(){this.b=M(this,H(this));this.a+=7};f.lg=function(){N(this,this.c);this.u(16);this.a+=11};f.ag=function(){Ud(this)&&(this.u(ge(this)),this.a+=6);this.a+=5};
f.Xd=function(){var a=I(this);Ud(this)&&this.u(a);this.a+=10};f.Kd=function(){var a=H(this);this.b=this.U.ca(a,this.c+-2&65535)&255;this.a+=10};f.Xc=function(){var a=I(this);Ud(this)&&(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Ag=function(){this.b=be(this,H(this));this.a+=7};f.mg=function(){N(this,this.c);this.u(24);this.a+=11};f.hg=function(){he(this)||(this.u(ge(this)),this.a+=6);this.a+=5};f.Tf=function(){Rd(this,ge(this));this.a+=10};
f.ce=function(){var a=I(this);he(this)||this.u(a);this.a+=10};f.$g=function(){var a=ge(this);N(this,K(this));Rd(this,a);this.a+=18};f.od=function(){var a=I(this);he(this)||(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Yf=function(){N(this,K(this));this.a+=11};f.Wc=function(){this.b=ce(this,H(this));this.a+=7};f.ng=function(){N(this,this.c);this.u(32);this.a+=11};f.gg=function(){he(this)&&(this.u(ge(this)),this.a+=6);this.a+=5};f.Qf=function(){this.u(K(this));this.a+=5};
f.be=function(){var a=I(this);he(this)&&this.u(a);this.a+=10};f.Qg=function(){var a=K(this);Rd(this,Td(this));Sd(this,a);this.a+=5};f.md=function(){var a=I(this);he(this)&&(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Zg=function(){this.b=de(this,H(this));this.a+=7};f.og=function(){N(this,this.c);this.u(40);this.a+=11};f.fg=function(){ie(this)||(this.u(ge(this)),this.a+=6);this.a+=5};f.Uf=function(){var a=ge(this);Fd(this,a&je|this.w&~je);this.b=a>>8;this.a+=10};
f.ae=function(){var a=I(this);ie(this)||this.u(a);this.a+=10};f.Hd=function(){this.w&=~$d;this.a+=4};f.ld=function(){var a=I(this);ie(this)||(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.Vf=function(){N(this,Kd(this)&je|this.b<<8);this.a+=11};f.Of=function(){this.b=ee(this,H(this));this.a+=7};f.pg=function(){N(this,this.c);this.u(48);this.a+=11};f.cg=function(){ie(this)&&(this.u(ge(this)),this.a+=6);this.a+=5};f.Cg=function(){this.v=K(this)&65535;this.a+=5};
f.Yd=function(){var a=I(this);ie(this)&&this.u(a);this.a+=10};f.Id=function(){this.w|=$d;this.a+=4;Id(this)};f.Yc=function(){var a=I(this);ie(this)&&(N(this,this.c),this.u(a),this.a+=6);this.a+=11};f.nd=function(){M(this,H(this));this.a+=7};f.qg=function(){N(this,this.c);this.u(56);this.a+=11};f.lb=function(a,b){if(a&&!(0>b))switch(a){case "pc":this.c=b;break;default:x(this,"unrecognized register: "+a)}};function Nd(a){return a.f<<8|a.g}function Ld(a,b){a.f=b>>8&255;a.g=b&255}
function Td(a){return a.h<<8|a.i}function Sd(a,b){a.h=b>>8&255;a.i=b&255}function K(a){return a.j<<8|a.l}function Rd(a,b){a.j=b>>8&255;a.l=b&255}f.gb=function(){return this.c};f.u=function(a){this.c=a&65535};function Ud(a){return a.m&256?Wd:0}function Qd(a,b){a.m=a.m&255|b}function he(a){return ke[a.o&255]?le:0}function fe(a){return a.m&255?0:me}function ie(a){return a.o&128?ne:0}function Kd(a){return a.w&~oe|ie(a)|fe(a)|((a.o^a.s)&16?Vd:0)|he(a)|Ud(a)}
function Fd(a,b){a.m=a.o=a.s=0;b&Wd&&(a.m|=256);b&le||(a.o|=1);b&Vd&&(a.s|=16);b&me||(a.m|=255);b&ne&&(a.o^=192);a.w=a.w&~(oe|$d)|b&$d|pe}function Xd(a,b){a.s=a.b^b;return a.o=(a.m=a.b+b)&255}function ae(a,b){a.s=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?1:0))&255}function ce(a,b){a.m=a.o=a.s=a.b&b;(a.b|b)&8&&(a.s^=16);return a.m}function Pd(a,b){a.s=b^255;b=a.o=b+255&255;a.m=a.m&-256|b;return b}function Od(a,b){a.s=b;b=a.o=b+1&255;a.m=a.m&-256|b;return b}function ee(a,b){return a.o=a.m=a.s=a.b|b}
function M(a,b){b^=255;a.s=a.b^b;return a.o=(a.m=a.b+b+1^256)&255}function be(a,b){b^=255;a.s=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?0:1)^256)&255}function de(a,b){return a.o=a.m=a.s=a.b^b}function L(a,b){return a.K.ca(b)|0}function Yd(a,b){return a.K.ca(b)|a.K.ca(b+1)<<8}function Md(a,b,c){a.K.aa(b,c&255)}function H(a){var b=L(a,a.c);a.u(a.c+1);return b}function I(a){var b=Yd(a,a.c);a.u(a.c+2);return b}function ge(a){var b=Yd(a,a.v);a.v=a.v+2&65535;return b}
function N(a,b){a.v=a.v-2&65535;var c=a.v;a.K.aa(c,b&255);a.K.aa(c+1,b>>8&255)}function Id(a){if(a.time.a&&a.H&qe&&a.w&$d){var b;for(b=0;8>b&&!(a.H&1<<b);b++);a.H&=~(0>b?255:1<<b);a.w&=~$d;a.H&=~Zd;a.W[re|b<<3].call(a)}return a.H&Zd?(kd(a.time),!1):!0}function Cd(a,b){a.H|=1<<b;a.w&$d&&kd(a.time)}
f.toString=function(){return this.J("A=%02X BC=%04X DE=%04X HL=%04X SP=%04X I%d S%d Z%d A%d P%d C%d\n%s",this.b,Nd(this),Td(this),K(this),this.v,this.w&$d?1:0,ie(this)?1:0,fe(this)?1:0,(this.o^this.s)&16&&Vd?1:0,he(this)?1:0,Ud(this)?1:0,this.L&&Rb(this.L,this.c,1)||"")};f.ih=function(a){this.L||(this.L=gb(this,se));a&&!this.time.a&&this.qa(this.toString())};
var Wd=1,pe=2,le=4,Vd=16,me=64,ne=128,je=255,$d=512,oe=Wd|le|Vd|me|ne,ke=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,
0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1],Gd=0,qe=255,Zd=256,re=199;function te(a,b,c){rb.call(this,a,b,c);this.style=ue;this.w=3}n(te,rb);
te.prototype.Wa=function(a,b){function c(P,ea){var Sb=ve[P];g.style==ue&&ea&we&&(P==xe&&(Sb="HL"),Sb="["+Sb+"]");return Sb}function d(P){switch(P&ye){case O:var ea=qa(g,e(),16,8);break;case ze:ea=qa(g,(e()|e()<<8)<<24>>24,16,16);break;case Ae:ea=qa(g,e()|e()<<8,16,16);break;default:return"imm("+qa(g,P,16,16)+")"}g.style==ue&&P&we?ea="["+ea+"]":P&Be||(ea=(g.style==Ce?"$":"0x")+ea);return ea}function e(){var P=b.shift();m+=qa(g,P,16,8);vb(g,a,1);return P}for(var g=this,h=qa(this,a.R,this.X,this.a.h),
m="",l=e(),k=De[l],q="",w=(this.style!=ue?Ee:Fe)[k[0]],v=k.length-1,t=Ge,r,u=1;u<=v;u++){var J="";r=k[u];if(void 0!==r&&!(r&Q&&this.style==Ce)){var A=r&He;if(A){var ra=r&ye;ra?t=ra:r|=t;r&Ie||(r|=1==u?Je:Ke);A&R?J=d(r):A&Be?J=c((r&Le)>>8,r):A&Me&&(J=(l>>3&7).toString());if(!J||!J.length){q="INVALID";break}0<q.length&&(q+=",");q+=J||"???"}}}return this.J("%s %-9s%s %-7s %s\n",h,m,r&Ne?"*":" ",w,q)};
var Ce=8080,ue=8086,Ee="NONE ACI ADC ADD ADI ANA ANI CALL CC CM CNC CNZ CP CPE CPO CZ CMA CMC CMP CPI DAA DAD DCR DCX DI EI HLT IN INR INX JMP JC JM JNC JNZ JP JPE JPO JZ LDA LDAX LHLD LXI MOV MVI NOP ORA ORI OUT PCHL POP PUSH RAL RAR RET RC RM RNC RNZ RP RPE RPO RZ RLC RRC RST SBB SBI SHLD SPHL STA STAX STC SUB SUI XCHG XRA XRI XTHL".split(" "),Fe="NONE ADC ADC ADD ADD AND AND CALL CALLC CALLS CALLNC CALLNZ CALLNS CALLP CALLNP CALLZ NOT CMC CMP CMP DAA ADD DEC DEC CLI STI HLT IN INC INC JMP JC JS JNC JNZ JNS JP JNP JZ MOV MOV MOV MOV MOV MOV NOP OR OR OUT JMP POP PUSH RCL RCR RET RETC RETS RETNC RETNZ RETNS RETP RETNP RETZ ROL ROR RST SBB SBB MOV MOV MOV MOV STC SUB SUB XCHG XOR XOR XCHG".split(" "),
xe=6,ve="B C D E H L M A BC DE HL SP PC PS PSW".split(" "),ye=15,He=240,Le=3840,Ie=61440,Ge=0,O=1,ze=2,Ae=3,Be=16,R=32,we=64,Me=128,S=1792|Be|O,T=0|Be|O,U=256|Be|O,V=512|Be|O,W=768|Be|O,X=1024|Be|O,Y=1280|Be|O,Z=xe<<8|Be|O|we,Oe=2048|Be|Ae,Pe=2304|Be|Ae,Qe=2560|Be|Ae,Re=2816|Be|Ae,Se=3584|Be|Ae,Ke=4096,Je=8192,Q=16384,Ne=32768,De=[[45],[42,Oe,R],[71,Oe|we,S|Q],[29,Oe],[28,T],[22,T],[44,T,R],[63],[45,Ne],[21,Qe|Q,Oe],[40,S|Q,Oe|we],[23,Oe],[28,U],[22,U],[44,U,R],[64],[45,Ne],[42,Pe,R],[71,Pe|we,S|
Q],[29,Pe],[28,V],[22,V],[44,V,R],[52],[45,Ne],[21,Qe|Q,Pe],[40,S|Q,Pe|we],[23,Pe],[28,W],[22,W],[44,W,R],[53],[45,Ne],[42,Qe,R],[68,51|we,Qe|Q],[29,Qe],[28,X],[22,X],[44,X,R],[20],[45,Ne],[21,Qe|Q,Qe],[41,Qe|Q,51|we],[23,Qe],[28,Y],[22,Y],[44,Y,R],[16,S|Q],[45,Ne],[42,Re,R],[70,51|we,S|Q],[29,Re],[28,Z],[22,Z],[44,Z,R],[72],[45,Ne],[21,Qe|Q,Re],[39,S|Q,51|we],[23,Re],[28,S],[22,S],[44,S,R],[17],[43,T,T],[43,T,U],[43,T,V],[43,T,W],[43,T,X],[43,T,Y],[43,T,Z],[43,T,S],[43,U,T],[43,U,U],[43,U,V],[43,
U,W],[43,U,X],[43,U,Y],[43,U,Z],[43,U,S],[43,V,T],[43,V,U],[43,V,V],[43,V,W],[43,V,X],[43,V,Y],[43,V,Z],[43,V,S],[43,W,T],[43,W,U],[43,W,V],[43,W,W],[43,W,X],[43,W,Y],[43,W,Z],[43,W,S],[43,X,T],[43,X,U],[43,X,V],[43,X,W],[43,X,X],[43,X,Y],[43,X,Z],[43,X,S],[43,Y,T],[43,Y,U],[43,Y,V],[43,Y,W],[43,Y,X],[43,Y,Y],[43,Y,Z],[43,Y,S],[43,Z,T],[43,Z,U],[43,Z,V],[43,Z,W],[43,Z,X],[43,Z,Y],[26],[43,Z,S],[43,S,T],[43,S,U],[43,S,V],[43,S,W],[43,S,X],[43,S,Y],[43,S,Z],[43,S,S],[3,S|Q,T],[3,S|Q,U],[3,S|Q,V],[3,
S|Q,W],[3,S|Q,X],[3,S|Q,Y],[3,S|Q,Z],[3,S|Q,S],[2,S|Q,T],[2,S|Q,U],[2,S|Q,V],[2,S|Q,W],[2,S|Q,X],[2,S|Q,Y],[2,S|Q,Z],[2,S|Q,S],[73,S|Q,T],[73,S|Q,U],[73,S|Q,V],[73,S|Q,W],[73,S|Q,X],[73,S|Q,Y],[73,S|Q,Z],[73,S|Q,S],[66,S|Q,T],[66,S|Q,U],[66,S|Q,V],[66,S|Q,W],[66,S|Q,X],[66,S|Q,Y],[66,S|Q,Z],[66,S|Q,S],[5,S|Q,T],[5,S|Q,U],[5,S|Q,V],[5,S|Q,W],[5,S|Q,X],[5,S|Q,Y],[5,S|Q,Z],[5,S|Q,S],[76,S|Q,T],[76,S|Q,U],[76,S|Q,V],[76,S|Q,W],[76,S|Q,X],[76,S|Q,Y],[76,S|Q,Z],[76,S|Q,S],[46,S|Q,T],[46,S|Q,U],[46,S|Q,
V],[46,S|Q,W],[46,S|Q,X],[46,S|Q,Y],[46,S|Q,Z],[46,S|Q,S],[18,S|Q,T],[18,S|Q,U],[18,S|Q,V],[18,S|Q,W],[18,S|Q,X],[18,S|Q,Y],[18,S|Q,Z],[18,S|Q,S],[58],[50,Oe],[34,51],[30,51],[11,51],[51,Oe],[4,S|Q,R|O],[65,Me],[62],[54],[38,51],[30,51|Ne],[15,51],[7,51],[1,S|Q,R|O],[65,Me],[57],[50,Pe],[33,51],[48,R|O,S|Q],[10,51],[51,Pe],[74,S|Q,R|O],[65,Me],[55],[54,Ne],[31,51],[27,S|Q,R|O],[8,51],[7,51|Ne],[67,S|Q,R|O],[65,Me],[61],[50,Qe],[37,51],[78,Re|we|Q,Qe|Q],[14,51],[51,Qe],[6,S|Q,R|O],[65,Me],[60],[49,
Qe],[36,51],[75,Qe|Q,Pe|Q],[13,51],[7,51|Ne],[77,S|Q,R|O],[65,Me],[59],[50,Se],[35,51],[24],[12,51],[51,Se],[47,S|Q,R|O],[65,Me],[56],[69,Re|Q,Qe|Q],[32,51],[25],[9,51],[7,51|Ne],[19,S|Q,R|O],[65,Me]];
function Te(a,b){D.call(this,a,a);var c=this;this.S=null;this.a="";this.c=this.f=!1;b=b.trim();"{"==b[0]?Ue(this,b):(this.a=b,Qa(this.a,function(d,e,g,h){4==g&&(!h&&e?(Ue(c,e),Ve(c)):c.I("error (%d) loading configuration: %s\n",h,d))}));window.addEventListener("load",function(){c.f=!0;Ve(c)});window.addEventListener((Ua("iOS")?"pagehide":Ua("Opera")?"unload":void 0)||"beforeunload",function(){We(c)})}n(Te,D);
function Ve(a){if(a.c&&a.f){for(var b in a.O){var c=void 0,d=void 0;try{var e=a.O[b];d=e["class"];if(G[d])if(d==Xe)a.I("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,Ye,Ze),a.a&&a.I("Configuration: %s\n",a.a);else{c=new G[d](a.N,b,e);if(d==hb)if(a.S){a.I("too many CPU devices: %s\n",b);continue}else a.S=c;a.I("%s device: %s\n",d,c.status)}else a.I("unrecognized %s device class: %s\n",b,d)}catch(h){a.I("error initializing %s device '%s': %s\n",d,b,h.message),ib(a,b)}}if(a.b){var g=Va(a);eb(a,function(h){h.hb&&
h.hb(g)})}eb(a,function(h){h.ba&&h.ba(a.g)})}}function We(a){if(a.b){var b=[];eb(a,function(c){c.ib&&c.ib(b)});$a(a,b)}eb(a,function(c){c.ba&&c.ba(!1)})}
function Ue(a,b){try{a.O=JSON.parse(b);var c=a.O[a.N];Ba(a,c);if(a.version){var d="",e=fb(a,a.N);if(e.version!=a.version){d="Machine";var g=e.version}else c.version&&c.version>a.version&&(d="Config",g=c.version);if(d){var h="Error: "+a.J("%s Device version (%3.2f) incompatible with %s version (%3.2f)",c.Qi,a.version,d,g)+"\n\nClearing your browser's cache may resolve the issue.",m=bb.ec;m&&0>bb.list.indexOf(m)&&(alert(h),bb.list.push(m));x(a,h)}}a.b=!1!==c.autoSave;a.g=!1!==c.autoStart;a.c=!0}catch(l){c=
l.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),x(a,"machine '"+a.N+"' initialization error: "+c)}}var Yc="Bus",hb="CPU",se="Debugger",sb="Input",Zc="LED",Xe="Machine",tb="Time",G={};"undefined"!=typeof jb&&(G[Yc]=jb);"undefined"!=typeof Ed&&(G[hb]=Ed);"undefined"!=typeof ud&&(G.Chip=ud);"undefined"!=typeof te&&(G[se]=te);"undefined"!=typeof gc&&(G[sb]=gc);"undefined"!=typeof zc&&(G[Zc]=zc);"undefined"!=typeof Te&&(G[Xe]=Te);
"undefined"!=typeof E&&(G.Memory=E);"undefined"!=typeof Wc&&(G.RAM=Wc);"undefined"!=typeof Xc&&(G.ROM=Xc);"undefined"!=typeof $c&&(G[tb]=$c);"undefined"!=typeof yd&&(G.Video=yd);var Ye="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",Ze="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";window.Invaders=function(a,b){var c=new Te(a,b);window.command=function(d){return Ea(c,d)};return c};})()

//# sourceMappingURL=invaders.js.map
