(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/ledctrl.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/machine.js (C) Jeff Parsons 2012-2019
*/
var u;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={fc:!0},ha={};try{ha.__proto__=fa;ea=ha.fc;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function v(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Qd=b.prototype}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ka="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function la(a,b){if(b){var c=ka;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}la("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});la("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});la("Number.parseInt",function(a){return a||parseInt});
la("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});
la("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var f=0;f<e&&c<d;)if(this[c++]!=b[f++])return!1;return f>=e}});function ma(){}function na(){}v(na,ma);
function oa(a,b){var c=a/y|0,d=b/y|0;return(a&b)==(b|0)&&(c&d)==d}var y=Math.pow(2,32);function z(){}v(z,na);u=z.prototype;u.flush=function(){var a=pa;pa="";this.Sa(a)};u.kc=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};
u.Sa=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(pa+a.substr(0,b)),pa="",a=a.substr(b+1)));pa+=a};function A(a,b,c){a.Sa(b+"\n",c)}u.na=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.Sa(this.Ca.apply(this,[a].concat(ba(c))))};
u.Ca=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,k;for(k=0;k<e.length-6;k+=6){d+=e[k];var h=e[k+5],n="ACDFHIMNSTWYbdfjcsoXx%".indexOf(h);if(0>n)d+="%"+e[k+1]+e[k+2]+e[k+3]+e[k+4]+h;else{if(f<c.length){var g=c[f];"%"!=h&&f++}else g=c[c.length-1];var l=e[k+1],m=e[k+2];"*"==m?(m=g,g=f<c.length?c[f++]:c[c.length-1]):m=+m||0;var p=e[k+3];p=p?+p.substr(1):-1;var q=0<=l.indexOf("#"),r=0<=l.indexOf("0"),
w=null,x=0,t="";n=12>n&&"object"!=typeof g?this.kc(g):g;switch(h){case "C":g=q?"#":"";d+=isNaN(n.getTime())?void 0:this.Ca(this.Ca("%%%sW, %%%sF %%%sD, %%%sY",g),n);continue;case "D":g=q?n.getUTCDate():n.getDate();h="d";break;case "A":case "H":case "I":g=q?n.getUTCHours():n.getHours();"A"==h?(g=12>g?"am":"pm",h="s"):("I"==h&&(g=g?12<g?g-12:g:12),h="d");break;case "F":case "M":g=q?n.getUTCMonth():n.getMonth();"F"==h?(g=qa[g],h="s"):(g++,h="d");break;case "N":g=q?n.getUTCMinutes():n.getMinutes();h=
"d";break;case "S":g=q?n.getUTCSeconds():n.getSeconds();h="d";break;case "T":g=q?"#":"";d+=isNaN(n.getTime())?void 0:this.Ca(this.Ca("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",g),n);continue;case "W":g=ra[q?n.getUTCDay():n.getDay()];h="s";break;case "Y":g=q?n.getUTCFullYear():n.getFullYear(),0<p&&(g%=Math.pow(10,p),p=-1),h="d"}switch(h){case "b":d+=g?"true":"false";break;case "d":g=Math.trunc(g);case "f":h=g+"";0<=p&&(h=g.toFixed(p));h.length<m&&(r?(0>g&&(m--,h=h.substr(1)),h=("0000000000"+h).slice(-m),
0>g&&(h="-"+h)):h=("          "+h).slice(-m));d+=h;break;case "j":d+=JSON.stringify(g,null,m||void 0);break;case "c":g="string"==typeof g?g[0]:String.fromCharCode(g);case "s":if(void 0!==g)for("string"!=typeof g&&(g=g.toString()),0<=p&&(g=g.substr(0,p));g.length<m;)g=0<=l.indexOf("-")?g+" ":" "+g;d+=g;break;case "o":x=8,q&&(t="0");case "X":w=sa;case "x":h="";x||(x=16);!t&&q&&(t="0x");w||(w=ta);"string"==typeof g&&(g=Number.parseInt(g,g.match(/(^0x|[a-f])/i)?16:10));r&&!m&&(m=Math.abs(g),m=255>=m?
2:65535>=m?4:4294967295>=m?8:9,m+=t.length);m-=t.length;do p=g&x-1,g>>>=16==x?4:3,r||!h||p||g?h=w[p]+h:(t&&(h=t+h,t=""),0<m&&(h=" "+h));while(0<--m||g);d+=t+h;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+h+")"}}}return d+=e[k]};var pa="",ta="0123456789abcdef",sa="0123456789ABCDEF",ra="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),qa="January February March April May June July August September October November December".split(" "),C=0,D={all:0xffffffffffff};
function E(a,b,c,d){this.oa=a;this.Ra=b;this.ka={};this.Ka=[];this.Fa=0;ua(this,c);this.version=d||2}var va;v(E,z);
E.prototype.Na=function(a,b){var c=this;switch(a){case wa.sb:b.onclick=function(){var d=c.Ua(wa.fb,!0);d&&(d.value="")};break;case wa.fb:b.value="",b.addEventListener("keydown",function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){var f=!1,k,h=b.value,n=h.lastIndexOf("\n");e==G.jb&&b.selectionStart<=n+1&&(f=!0);e==G.Zb?(f=!0,0<c.Fa&&(k=c.Ka[--c.Fa])):e==G.vb&&(f=!0,c.Fa<c.Ka.length&&(k=c.Ka[++c.Fa]||""));f&&d.preventDefault();void 0!=k&&(b.value=h.substr(0,n+1)+k)}}),b.addEventListener("keypress",
function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){e=String.fromCharCode(e);var f=b.value,k=f.lastIndexOf("\n");b.selectionStart<=k&&b.setSelectionRange(f.length,f.length);d.stopPropagation();"@"==e&&0<c.Fa&&k+1==f.length&&(b.value+=c.Ka[--c.Fa],e="\r");"\r"==e&&(d.preventDefault(),f=b.value+="\n",b.blur(),b.focus(),(d=xa(c,f.slice(f.lastIndexOf("\n",f.length-2)+1,-1)||""))&&A(c,d.replace(/\n$/,""),!1))}})}};
function ya(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function za(a,b){var c=Aa.kb;I[a.oa]||(I[a.oa]={});I[a.oa][c]||(I[a.oa][c]=[]);I[a.oa][c].push(b)}
function ua(a,b){b=void 0===b?{}:b;if(b.overrides){var c=Ba();for(k in c)if(0<=b.overrides.indexOf(k)){var d=c[k];if(d.match(/^[+-]?[0-9.]+$/))var e=Number.parseInt(d,10);else"true"==d?e=!0:"false"==d?e=!1:(e=d,d='"'+d+'"');b[k]=e;A(a,"overriding "+a.Ra+" property '"+k+"' with "+d)}}a.pa||(a.pa=b);b=b.bindings;c=Array.isArray(b);for(var f in b){e=b[f];if(c)f=e;else if(e.match(/^[0-9]+$/)){var k=+e;a.ka[f]=[];do{e=f+k++;e=document.getElementById(e);if(!e)break;a.ka[f].push(e)}while(1);continue}if(k=
document.getElementById(e))a.ka[f]=k,a.Na(f,k)}}E.prototype.Ua=function(a){return this.ka[a]};function Ca(a){var b=Aa.kb;return I[a.oa]&&I[a.oa][b]}function Da(a,b){return a.pa.bindings&&a.pa.bindings[b]}function Ea(a){if(a=a.ka[Fa])var b=a.textContent;return b}function Ga(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}function J(a,b,c){a=a.pa[b];void 0===a?a=c:(b=typeof c,typeof a!=b&&("boolean"==b?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Ha(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Ba(){var a,b=va;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}va=b}return b}function Ia(a){if(void 0===K.eb){var b=!1;if(window)try{window.localStorage.setItem(K.Ta,K.Ta),b=window.localStorage.getItem(K.Ta)==K.Ta,window.localStorage.removeItem(K.Ta)}catch(c){A(a,c.message),b=!1}K.eb=b}return!!K.eb}
function Ja(a){a=void 0===a?0:a;a%2&&a--;a=a||0;return-1==(a|1)||oa(C,a)?!0:!1}function Ka(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function La(a){var b=null;if(Ia(a)){var c;if(window)try{(c=window.localStorage.getItem(a.oa))&&(b=JSON.parse(c))}catch(d){A(a,d.message)}}return b}
function xa(a,b){try{if(b=b.trim())a.Fa<a.Ka.length&&b==a.Ka[a.Fa]?a.Fa++:(a.Ka.push(b),a.Fa=a.Ka.length);var c=b.split(" "),d=Ca(a);switch(c[0]){case "m":var e="";var f=c[c.length-1].toLowerCase();var k="true"==f||"on"==f?!0:"false"==f||"off"==f?!1:void 0;void 0!=k?c.pop():1>=c.length&&(c=Object.keys(D));for(d=1;d<c.length;d++){f=c[d];var h=D[f];if(!h){e+="unrecognized message group: "+f+"\n";break}void 0!=k&&Ma(a,h,k);e+=f+": "+Ja(h)+"\n"}break;case "?":e="",Na.forEach(function(g){e+=g+"\n"}),e&&
(e="default commands:\n"+e);default:if(c.unshift(b),d)for(a=0;a<d.length;a++){var n=d[a](c);if(void 0!=n){e=e?e+n:n;break}}}}catch(g){e="error: "+g.message+"\n"}return e}E.prototype.Sa=function(a,b){void 0==b&&(b=Ja(0x800000000000));if(!b){var c=this.Ua(wa.fb,!0);if(c){c.value+=a;8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096));c.scrollTop=c.scrollHeight;return}}z.prototype.Sa.call(this,a,b)};
E.prototype.na=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());Ja(d)&&z.prototype.na.call.apply(z.prototype.na,[this,a].concat(ba(c)))};function Oa(a,b){if(Ia(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.oa,b)}catch(c){A(a,c.message)}}}function Pa(a,b,c){if(a=a.ka[b])a.textContent=c}
function Ma(a,b,c){var d=!1;c?(c=C,C=(c|b)+(c/y|0|b/y|0)*y):(d=oa(C,0x800000000000)&&oa(b,0x800000000000),c=C,C=(c&~b)+((c/y|0)&~(b/y|0))*y);d&&a.flush()}
var wa={sb:"clear",fb:"print"},Na=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m\t\tenable messages"],Aa={kb:"command"},Qa={list:[],ac:"version"},K={eb:void 0,Ta:"PCjs.localStorage"},G={jb:8,Vb:9,Hb:10,tb:13,Md:16,tc:17,nc:18,Ad:19,qc:20,yc:27,Tb:32,Dd:33,Cd:34,wc:35,Xc:36,Gb:37,Zb:38,Pb:39,Tc:39,vb:40,Oc:44,Ed:44,Yc:45,vc:46,Sc:46,Wc:47,ZERO:48,ONE:49,Xb:50,Wb:51,zb:52,yb:53,Sb:54,Rb:55,wb:56,Kb:57,Vc:59,Qc:61,pb:65,qb:66,rb:67,ub:68,E:69,xb:70,Ab:71,Bb:72,Cb:73,Db:74,Eb:75,Fb:76,
Ib:77,Jb:78,Lb:79,Mb:80,Q:81,Ob:82,Qb:83,Ub:84,Yb:85,$b:86,bc:87,cc:88,dc:89,ec:90,rc:91,Rc:91,Mc:92,Id:93,Uc:93,$c:96,rd:96,Lc:96,ad:97,pd:97,bd:98,od:98,cd:99,vd:99,dd:100,sd:100,ed:101,ld:101,fd:102,xd:102,gd:103,qd:103,hd:104,zd:104,jd:105,wd:105,ud:106,kd:107,yd:109,md:110,nd:111,zc:112,Dc:113,Ec:114,Fc:115,Gc:116,Hc:117,Ic:118,Jc:119,Kc:120,Ac:121,Bc:122,Cc:123,td:144,Kd:145,Pc:173,Ld:186,xc:187,sc:188,uc:189,Bd:190,Nd:191,oc:192,Zc:219,pc:220,Hd:221,Fd:222,Nc:224},M={},Ra=(M[G.jb]="\b",M[G.Vb]=
"\t",M[G.Hb]="\n",M[G.tb]="\r",M[G.Tb]=" ",M[G.ZERO]="0",M[G.ONE]="1",M[G.Xb]="2",M[G.Wb]="3",M[G.zb]="4",M[G.yb]="5",M[G.Sb]="6",M[G.Rb]="7",M[G.wb]="8",M[G.Kb]="9",M[G.pb]="A",M[G.qb]="B",M[G.rb]="C",M[G.ub]="D",M[G.E]="E",M[G.xb]="F",M[G.Ab]="G",M[G.Bb]="H",M[G.Cb]="I",M[G.Db]="J",M[G.Eb]="K",M[G.Fb]="L",M[G.Ib]="M",M[G.Jb]="N",M[G.Lb]="O",M[G.Mb]="P",M[G.Q]="Q",M[G.Ob]="R",M[G.Qb]="S",M[G.Ub]="T",M[G.Yb]="U",M[G.$b]="V",M[G.bc]="W",M[G.cc]="X",M[G.dc]="Y",M[G.ec]="Z",M[G.Gb]="Left",M[G.Pb]="Right",
M),I={};D.addr=1;D.bus=2;D.port=4;D.memory=8;D.cpu=16;D.video=32;D.monitor=64;D.screen=128;D.timer=256;D.event=512;D.key=1024;D.warn=2048;D.halt=4096;D.buffer=0x800000000000;function N(a,b,c,d){E.call(this,a,b,c,d);this.status="OK";O[this.oa]||(O[this.oa]=[]);O[this.oa].push(this);this.Ea=void 0}v(N,E);function Sa(a,b){if(a=O[a.oa])for(var c in a)b(a[c])}
N.prototype.Ua=function(a,b){b=void 0===b?!1:b;var c=E.prototype.Ua.call(this,a,b);if(void 0===c&&b){b=O[this.oa];for(var d in b)if(c=b[d].ka[a])break;c||(c=null);this.ka[a]=c}return c};function P(a,b){var c=null;if(a=O[a.oa])for(var d in a)if(a[d].pa["class"]==b){c=a[d];break}return c}
N.prototype.na=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if("number"==typeof a&&C&1&&Ja(a)&&(void 0===this.Ea&&(this.Ea=P(this,Ta)),this.Ea)){a=c.shift();c=this.Ca.apply(this,[a].concat(ba(c))).trim();E.prototype.na.call(this,"%s at %#0x\n",c,this.Ea.Ba);return}E.prototype.na.call.apply(E.prototype.na,[this,a].concat(ba(c)))};function Ua(a,b){if(a=O[a.oa])for(var c in a)if(a[c].Ra==b){a.splice(c,1);break}}var O={};
function Q(a,b,c){N.call(this,a,b,c);this.nb=c.addr;this.size=c.size;this.type=c.type||T.NONE;this.width=c.width||8;this.values=c.values||Array(this.size).fill(0);this.da=this.ea=!1}v(Q,N);Q.prototype.Oa=function(a){var b=a.shift();return this.Ra==b?(this.da=a.shift(),this.ea=a.shift(),this.values=a.shift(),!0):!1};Q.prototype.Pa=function(a){a.push(this.Ra);a.push(this.da);a.push(this.ea);a.push(this.values)};var T={NONE:0,gb:1,Gd:2};
function Va(a,b,c){N.call(this,a,b,c);this.ea=c.addrWidth||16;this.da=c.dataWidth||8;this.ca=Math.pow(2,this.ea);this.aa=c.blockSize||1024;this.aa>this.ca&&(this.aa=this.ca);this.ga=this.ca/this.aa|0;this.fa=Math.log2(this.aa)|0;this.ba=Array(this.ga);a=new Q(a,b+".none",{size:this.aa,width:this.da});for(b=0;b<this.ca;b+=this.aa)Wa(this,b,this.aa,T.NONE,a)}v(Va,N);
function Wa(a,b,c,d,e){for(var f=0,k=b>>>a.fa;0<c&&k<a.ba.length;){var h=k*a.aa,n=a.aa-(b-h);n>c&&(n=c);var g=a.ba[k];if(b!=h||n!=a.aa)throw Error(a.Ca("addBlocks(%#0x,%#0x): block boundary error",b,n));if(g&&g.type!=T.NONE)throw Error(a.Ca("addBlocks(%#0x,%#0x): block (%d) already exists",b,n,g.type));var l=g=void 0,m=b,p=a.ea,q=16;p=void 0===p?0:p;g=void 0===g?0:g;var r="",w="",x=-1;q||(q=a.ha||10);p&&(x=Math.ceil(p/Math.log2(q)));if(void 0==l)switch(q){case 8:l="0o";break;case 16:l="0x";break;
case 10:w=".";default:l=""}isNaN(m)||"number"!=typeof m?(m=void 0,l=w=""):(0>m&&-1<m&&(m=-1),p&&(0>m&&(m+=Math.pow(2,p)),m>=Math.pow(2,p)&&(x=Math.ceil(Math.log(m)/Math.log(q)))));for(p=g||-1;x--;){p||(r=","+r,p=g);if(void 0==m){if(r="?"+r,0>x)break}else{var t=m%q;t+=0<=t&&9>=t?48:55;r=String.fromCharCode(t)+r;if(!m&&0>x)break;m=Math.trunc(m/q)}p--}g=a.Ra+"["+(l+r+w)+"]";if(e)if(e.size==a.aa)b=e;else{l=void 0;if(e.values&&(l=e.values.slice(f,f+n),l.length!=n))throw Error(a.Ca("addBlocks(%#0x,%#0x): insufficient values (%d)",
b,n,l.length));b=new Q(a.oa,g,{type:d,nb:b,size:n,width:a.da,values:l})}else b=new Q(a.oa,g,{type:d,nb:b,size:n,width:a.da});a.ba[k++]=b;b=h+a.aa;c-=n;f+=n}}Va.prototype.hb=function(a){var b;if(b=a)a:{for(b=0;b<this.ba.length;b++){var c=this.ba[b];if(!(c.type<=T.gb)&&c.Oa){var d=a.shift();if(!c.Oa(d)){b=!1;break a}}}b=!0}return b?!0:!1};Va.prototype.ib=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if(!(c.type<=T.gb)&&c.Pa){var d=[];c.Pa(d);a.push(d)}}};
function U(a,b,c){N.call(this,a,b,c);this.time=P(this,Xa);this.va=this.ta=this.Aa=this.sa=null;this.Da=J(this,"drag",!1);this.ua=J(this,"scroll",!1);this.La=J(this,"hexagonal",!1);this.ba=J(this,"buttonDelay",0);this.ea=!1;if((this.aa=this.pa.map)&&!this.aa.length)for(a=Object.keys(this.aa),b=0;b<a.length;b++){c=a[b];var d=this.aa[c];"string"==typeof d&&(d=[d]);this.aa[c]={ic:d,state:0}}this.ca=null;if(a=this.ka[Ya])this.ca=this.ka[Za],$a(this,a,this.pa.location);this.xa=this.Ga=-1}v(U,N);
U.prototype.Na=function(a,b){var c=this;switch(a){case Za:b.onclick=function(){c.Aa&&c.Aa()};break;case ab:b.onclick=function(){c.ta&&c.ta()}}N.prototype.Na.call(this,a,b)};function bb(a,b,c){a.Aa=b;a.ta=c}function cb(a,b){a.va=b}function db(a,b){a.sa=b}
function $a(a,b,c){c=void 0===c?[]:c;a.Za=c[0]||0;a.$a=c[1]||0;a.da=c[2]||b.clientWidth;a.ia=c[3]||b.clientHeight;a.ja=c[4]||1;a.qa=c[5]||1;a.Va=c[6]||b.naturalWidth||a.da;a.Xa=c[7]||b.naturalHeight||a.ia;a.Ia=c[8]||0;a.Ja=c[9]||0;a.Qa=c[10]||0;a.Wa=c[11]||0;a.aa&&a.aa.length?(a.ma=a.aa.length,a.ga=a.aa[0].length):(a.ga=a.ja,a.ma=a.qa,a.ja=a.qa=0);a.ya=a.da/(a.ga+a.ga*a.ja)|0;a.za=a.ia/(a.ma+a.ma*a.qa)|0;a.Ma=a.ya*a.ja|0;a.Ba=a.za*a.qa|0;a.ha=a.ra=-1;eb(a,b);fb(a,b);a.time&&(a.ba&&(a.Ha=gb(a.time,
"timerInputRelease",function(){0>a.ha&&0>a.ra&&hb(a,-1,-1)})),a.aa&&(a.ba&&(a.Ya=gb(a.time,"timerKeyRelease",function(){ib(a)})),a.fa=0,a.la=[],jb(a)))}function kb(a){a.ba?lb(a.time,a.Ya,a.ba):ib(a)}
function jb(a){var b=document;b.addEventListener("keydown",function(c){c=c||window.event;var d=document.activeElement;if(!a.ca||d==a.ca){d=c.which||c.keyCode;var e=Ra[d],f=!1;e&&(f=mb(a,e,!0));a.na(1536,"onKeyDown(keyCode=%#04x): %5.2f (%s)\n",d,Date.now()/1E3%60,e?f?"used":"unused":"ignored");f&&c.preventDefault()}});b.addEventListener("keypress",function(c){c=c||window.event;var d=c.which||c.charCode,e=String.fromCharCode(d),f=!1;e&&(f=mb(a,e.toUpperCase()));a.na(1536,"onKeyPress(charCode=%#04x): %5.2f (%s)\n",
d,Date.now()/1E3%60,e?f?"used":"unused":"ignored");f&&c.preventDefault()});b.addEventListener("keyup",function(c){c=c||window.event;var d=document.activeElement;a.ca&&d!=a.ca||(c=c.which||c.keyCode,(d=Ra[c])&&mb(a,d,!1),a.na(1536,"onKeyUp(keyCode=%#04x): %5.2f (ignored)\n",c,Date.now()/1E3%60))})}
function eb(a,b){b.addEventListener("mousedown",function(c){if(!a.ea){if(a.ca){var d=window.scrollX,e=window.scrollY;a.ca.focus();window.scrollTo(d,e)}c.button||V(a,b,nb,c)}});b.addEventListener("mousemove",function(c){a.ea||V(a,b,ob,c)});b.addEventListener("mouseup",function(c){a.ea||c.button||V(a,b,pb,c)});b.addEventListener("mouseout",function(c){a.ea||(0>a.ha?V(a,b,ob,c):V(a,b,pb,c))})}
function fb(a,b){b.addEventListener("touchstart",function(c){a.ua&&(a.ea=!0);V(a,b,nb,c)});b.addEventListener("touchmove",function(c){V(a,b,ob,c)});b.addEventListener("touchend",function(c){V(a,b,pb,c)})}
function mb(a,b,c){if(a.aa)if(a.aa.length){if(!1===c)return!0;for(c=0;c<a.aa.length;c++)for(var d=a.aa[c],e=0;e<d.length;e++)if(0<=d[e].split("|").indexOf(b))return a.fa?16>a.la.length&&a.la.push(b):(a.fa=1,hb(a,e,c),kb(a)),!0}else if(void 0!=c)for(d=Object.keys(a.aa),e=0;e<d.length;e++){var f=d[e];if(0<=a.aa[f].ic.indexOf(b))return a.aa[f].state=c?1:0,!0}return!1}function ib(a){1==a.fa?(a.fa++,hb(a,-1,-1),kb(a)):(a.fa=0,a.la.length&&mb(a,a.la.shift()))}
function V(a,b,c,d){var e=-1,f=-1,k=!1,h;if(c<pb){d=d||window.event;if(d.targetTouches&&d.targetTouches.length){var n=d.targetTouches[0].pageX;var g=d.targetTouches[0].pageY;k=1<d.targetTouches.length}else n=d.pageX,g=d.pageY;var l=h=0;var m=b;do isNaN(m.offsetLeft)||(h+=m.offsetLeft,l+=m.offsetTop);while(m=m.offsetParent);n=a.Va/b.offsetWidth*(n-h)|0;g=a.Xa/b.offsetHeight*(g-l)|0;b=n-a.Za;var p=g-a.$a;l=h=!1;m=n>=a.Ia&&n<a.Ia+a.Qa&&g>=a.Ja&&g<a.Ja+a.Wa;if(0<=b&&b<a.da&&0<=p+a.Ba||m)if(k||a.ua||d.preventDefault(),
0<=b&&b<a.da&&0<=p&&p<a.ia){l=!0;d=a.da/a.ga|0;var q=a.ia/a.ma|0,r=b/d|0,w=p/q|0;!a.La||w&1||(b-=d>>1,r=b/d|0,r==a.ga-1&&(b=-1));q=w*q+(a.Ba>>1);b-=r*d+(a.Ma>>1);p-=q;0<=b&&b<a.ya&&0<=p&&p<a.za&&(e=r,f=w,h=!0)}}if(!k)if(c==nb)a.ha=n,a.ra=g,l?(hb(a,e,f),h&&a.ba&&lb(a.time,a.Ha,a.ba,!0)):m&&a.Aa&&a.Aa();else if(c==ob)0<=a.ha&&0<=a.ra&&a.Da?hb(a,e,f):a.va&&a.va(e,f);else if(c==pb){if(c=a.ba)c=a.time,e=a.Ha,c=c.aa&&0<e&&e<=c.ba.length?0<=c.ba[e-1].wa:!1;c||hb(a,-1,-1);a.ha=a.ra=-1}else A(a,"unrecognized action: "+
c)}function hb(a,b,c){if(b!=a.xa||c!=a.Ga)a.xa=b,a.Ga=c,a.sa&&a.sa(b,c)}var nb=1,ob=2,pb=3,Za="power",ab="reset",Ya="surface";
function qb(a,b,c){N.call(this,a,b,c);a=this.ka[rb];if(!a)throw Error("LED binding for '"+rb+"' missing: '"+this.pa.ka[rb]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Da=a;this.type=Ga(J(this,"type",sb),tb,ub);this.ga=vb[this.type][0];this.ja=vb[this.type][1];this.width=J(this,"width",this.ga);this.height=J(this,"height",this.ja);this.ca=J(this,"cols",1);this.ba=this.ca+
J(this,"colsExtra",0);this.ua=J(this,"rows",1);this.da=this.ua+J(this,"rowsExtra",0);this.cb=this.width*this.ca;this.ab=this.height*this.ua;this.fa=wb("black",0);this.ea=xb(this.pa.color)||this.fa;this.La=wb(this.ea,1,.25);this.Ja=wb(this.ea,1,2);this.ia=xb(this.pa.backgroundColor);this.Ma=J(this,"fixed",!1);this.Ma||(b.style.width="100%",b.style.height="auto");this.Ba=J(this,"hexagonal",!1);this.Qa=J(this,"highlight",!0);this.xa=J(this,"persistent",this.type<ub);b.setAttribute("width",this.cb.toString());
b.setAttribute("height",this.ab.toString());b.style.backgroundColor=this.fa;a.appendChild(b);this.Ga=b.getContext("2d");if(this.qa=document.createElement("canvas"))this.qa.width=this.za=this.ga*this.ca,this.qa.height=this.sa=this.ja*this.ua,this.aa=this.qa.getContext("2d");this.Ha=(this.da+1)*this.ba*4;this.buffer=Array(this.Ha);this.ma=null;this.Ia=this.ca<this.ba?4*(this.ba-this.ca):0;this.ha=this.ra=!1;this.ya=0;this.va=!0;this.la=0;this.ta=-1;var d=this;(this.time=P(this,Xa))&&yb(this.time,function(e){W(d,
!1,e)})}v(qb,N);function zb(a,b){Ab(a,a.buffer);a.ha=a.ra=!0;b&&W(a,!0)}function Bb(a){a.ia?(a.aa.fillStyle=a.ia,a.aa.fillRect(0,0,a.za,a.sa)):a.aa.clearRect(0,0,a.za,a.sa)}
function W(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.ha||b){if(a.type<ub){var d=0;if(!a.xa||b)Bb(a);else if(a.la){d=a.ca-a.la;var e=a.ga*d;a.aa.drawImage(a.qa,a.ga*a.la,0,e,a.sa,0,0,e,a.sa)}for(var f=e=0;f<a.da;f++){for(var k=0;k<a.ca;k++){var h=a.buffer[e],n=a.buffer[e+1]||a.fa,g=!1,l=!!(a.buffer[e+3]&X),m=a.Qa&&e==a.ta;!a.va&&h&&(h=Y,l=g=!0);if(l||m||b){if(k>=d)a:{l=a;var p=h;h=n;var q=k;n=f;var r=m;q=void 0===q?0:q;n=void 0===n?0:n;r=void 0===r?!1:r;var w=0;if(l.Ba&&!(n&1)&&(w=l.ga>>1,q==
l.ca-1))break a;if(h&&h!=l.ea){r=r?wb(h,1,2):h;var x=wb(h,1,.25)}else r=r?l.Ja:l.ea,x=l.La;h=!1;p=p?r:x;r==l.fa&&(p=l.ia,h=!0);r=q*l.ga+w;x=n*l.ja;l.xa&&(q=q*l.ga+w,n*=l.ja,l.ia?(l.aa.fillStyle=l.ia,l.aa.fillRect(q,n,l.ga,l.ja)):l.aa.clearRect(q,n,l.ga,l.ja));l.aa.fillStyle=p;n=Cb[l.type];3==n.length?(l.aa.beginPath(),l.aa.arc(r+n[0],x+n[1],n[2],0,2*Math.PI),h?(l.aa.globalCompositeOperation="destination-out",l.aa.fill(),l.aa.globalCompositeOperation="source-over"):l.aa.fill()):l.aa.fillRect(r+n[0],
x+n[1],n[2],n[3])}a.buffer[e+3]=m||g?a.buffer[e+3]|X:a.buffer[e+3]&~X}e+=4}e+=a.Ia}a.la=0}else{b="";for(d=0;d<a.buffer.length;d+=4)b+=a.buffer[d]||" ",a.buffer[d+3]&Db&&(b+=".");Bb(a);for(f=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;k=a;g=e;m=f;g=void 0===g?0:g;m=void 0===m?0:m;if(l=Eb[l])for(n=0;n<l.length;n++)if(h=k,q=Fb[l[n]]){w=(void 0===g?0:g)*h.ga;p=(void 0===m?0:m)*h.ja;h.aa.fillStyle=h.ea;h.aa.beginPath();if(3==q.length)h.aa.arc(w+q[0],p+q[1],q[2],0,2*Math.PI);else for(r=0;r<q.length;r+=
2)r?h.aa.lineTo(w+q[r],p+q[r+1]):h.aa.moveTo(w+q[r],p+q[r+1]);h.aa.closePath();h.aa.fill()}if(++e==a.ca&&(e=0,++f==a.da))break}}a.Ga.globalCompositeOperation=a.ia&&a.ea!=a.fa?"source-over":"copy";a.Ga.drawImage(a.qa,0,0,a.za,a.sa,0,0,a.cb,a.ab);a.ha=!1;a.ta=-1}else a.xa||a.ra||(!c||!a.ya||c-a.ya>=(1E3/60|0))&&zb(a,!0);a.ra=!1;c&&(a.ya=c)}function Gb(a,b){b=void 0===b?!0:b;a.va!=b&&(a.va=b,a.ha=!0)}function Hb(a,b,c){b=4*(c*a.ba+b);return b<=a.buffer.length-4?a.buffer[b+2]:0}
function Ib(a,b,c){var d;b=4*(c*a.ba+b);b<=a.buffer.length-4&&(d=a.buffer[b]);return d}function xb(a){return(a=a||void 0)&&Jb[a]||a}function wb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=Jb[a]||a;if(Kb(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function Ab(a,b){for(var c=0;c<b.length;c+=4)Lb(a,b,c)}function Lb(a,b,c){b[c]=a.type<ub?Y:" ";b[c+1]=a.ea==a.fa?null:a.ea;b[c+2]=0;b[c+3]=X}
qb.prototype.Oa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.ea&&c==this.ia&&a&&a.length==this.buffer.length){this.buffer=a;for(b=0;b<=this.buffer.length-4;b+=4)this.buffer[b+1]==this.fa&&(this.buffer[b+1]=null);W(this,!0);return!0}return!1};
function Kb(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}qb.prototype.Pa=function(a){this.buffer&&(a.push(this.ea),a.push(this.ia),a.push(this.buffer))};
function Mb(a,b,c,d){var e=null;0<=c&&c<a.da&&0<=b&&b<a.ba&&(e=!1,d=d||a.ea,d==a.fa&&(d=null),b=4*(c*a.ba+b),a.buffer[b+1]!==d&&((a.buffer[b+1]=d)||(a.buffer[b]=Y),a.buffer[b+3]|=X,a.ha=e=!0),a.ta=b,a.ra=!0);return e}function Nb(a,b,c,d){if(0<=c&&c<a.da&&0<=b&&b<a.ba){b=4*(c*a.ba+b);c=0;if(a.buffer[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.buffer[b+2]!==c&&(a.buffer[b+2]=c,a.buffer[b+3]|=X,a.ha=!0);a.ta=b;a.ra=!0}}
function Ob(a,b,c,d){var e=!1,f=0&Pb;b=4*(c*a.ba+b);if(b<=a.buffer.length-4){if(a.buffer[b]!==d||(a.buffer[b+3]&Pb)!==f)a.buffer[b]=d,a.buffer[b+3]=a.buffer[b+3]&~Pb|f|X,a.ha=e=!0;a.ta=b;a.ra=!0;a.la=0}return e}
var tb=0,sb=1,ub=3,rb="container",Jb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",
darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",
goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",
lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",
olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",
slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},Y=0,Pb=129,Db=1,X=128,Qb={},Cb=(Qb[tb]=[4,4,4],Qb[sb]=[16,16,14],Qb[2]=[2,2,28,28],Qb),vb=[[8,8],[32,32],[32,32],[96,128]],Fb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],
D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Eb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};
function Rb(a,b,c){c.type=T.gb;Q.call(this,a,b,c);c.revision&&(this.status="revision "+c.revision+" "+this.status);this.ga=P(this,Sb);Wa(this.ga,c.addr,c.size,c.type,this);if(Z[Tb]&&this.ka[Ub]){var d=this;c=Z[Tb];this.ba=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.ca=this.values.length/this.ba|0;this.aa=new c(a,b+"LEDs",{"class":"LED",bindings:{container:Da(this,Ub)},type:c.Od.Jd,cols:this.ba,rows:this.ca,color:J(this,"colorROM","green"),backgroundColor:J(this,"backgroundColorROM",
"black"),persistent:!0}),zb(this.aa,!0);this.fa=new U(a,b+"Input",{"class":"Input",location:[0,0,this.aa.cb,this.aa.ab,this.ba,this.ca],bindings:{surface:Da(this,Ub)}});this.ha=Ea(this)||"";cb(this.fa,function(e,f){if(d.Ea){var k=d.ha;0<=e&&0<=f&&(k="");Pa(d,Fa,k)}})}}v(Rb,Q);
Rb.prototype.Oa=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.buffer.length==d?(this.aa.buffer=c,W(this.aa,!0)):(this.na("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.na("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Rb.prototype.Aa=function(){this.Ea||(this.Ea=P(this,Ta))};Rb.prototype.Pa=function(a){this.aa&&(a.push(this.aa.buffer),a.push(this.values))};
var Ub="array",Fa="cellDesc";
function Vb(a,b,c){N.call(this,a,b,c);this.Ma=J(this,"cyclesMinimum",1E5);this.Ya=J(this,"cyclesMaximum",3E6);this.xa=Ga(J(this,"cyclesPerSecond",65E4),this.Ma,this.Ya);this.ta=Ga(J(this,"yieldsPerSecond",Wb),30,120);this.Za=Ga(J(this,"yieldsPerUpdate",Xb),1,this.ta);this.Ia=(this.ra=J(this,"clockByFrame",120>=this.xa))||J(this,"requestAnimationFrame",!0);this.Va=this.Wa=this.Ba=1;this.Ja=this.xa/1E4/100;this.fa=this.ja=this.Ja*this.Ba;this.ma=0;this.Da=Math.round(1E3/this.ta);this.Ga=[];this.qa=
[];this.ba=[];this.Ha=[];this.aa=this.ua=this.ia=!1;this.sa=this.ea=0;this.mb=this.lc.bind(this);this.$a=this.ob.bind(this);this.Qa=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);if(this.ra)this.da=this.Xa=0;else{var d=this;gb(this,"timerYield",function(){Yb(d)},this.Da)}this.ya=this.va=this.ha=0;Zb(this)||$b(this,this.Va)}v(Vb,N);function yb(a,b){a.Ga.push(b)}u=Vb.prototype;
u.Na=function(a,b){var c=this;switch(a){case ac:b.onclick=function(){c.aa?bc(c):c.start()};break;case cc:b.onclick=function(){c.aa?A(c,"already running"):c.ea?bc(c):dc(c,void 0)};break;case ec:b.addEventListener("mousedown",function(){c.ia=!0}),b.addEventListener("mouseup",function(){Zb(c);c.ia=!1}),b.addEventListener("mousemove",function(){c.ia&&Zb(c)}),b.addEventListener("change",function(){c.ia=!0;Zb(c);c.ia=!1})}N.prototype.Na.call(this,a,b)};
function gb(a,b,c,d){d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,gc:c,bb:d,wa:-1});0<=d&&lb(a,e,d);return e}u.ob=function(a){if(this.ra){if(!this.aa)return;fc(this);try{this.ua=!1;do gc(this,hc(this,ic(this,jc(this))));while(this.aa&&!this.ua)}catch(c){A(this,c.message);bc(this);return}kc(this)}for(var b=0;b<this.Ga.length;b++)this.Ga[b](a);this.aa&&this.Ia&&this.Qa(this.$a)};function lc(a){var b=a.fa/a.Ja;if(!b||b>a.Ba)b=a.Ba;a.Nb=a.xa/a.ta*b;a.Wa=b}
function ic(a,b){a.va=a.ha=b;if(!a.qa.length)return a.ha=0,a.va;for(var c=0;0<a.ha;)c<a.qa.length?b=a.qa[c++](b)||1:c=b=0,a.ha-=b;return a.va-a.ha}function hc(a,b){b=void 0===b?a.va-a.ha:b;if(a.ra){if(!a.aa){if(a.da)for(var c=0;c<a.qa.length;c++)a.qa[c](-1);a.da=b}a.da-=b;1>a.da&&Yb(a)}a.va=a.ha=0;a.za+=b;a.ya+=b;a.aa||(a.ya=0);return b}function mc(a,b){return Math.ceil(a.xa*a.Wa/1E3*(void 0===b?1E3:b))}
function jc(a,b){b=void 0===b?0:b;if(b){var c=b;a.da+=b}else for(c=a.da,1>c&&(c=a.da+=a.Xa),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.wa)&&c>d.wa&&(c=d.wa)}return c}function nc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function gc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.wa||(d.wa-=b,0>=d.wa&&(d.wa=-1,d.gc(),0<=d.bb&&lb(a,c,d.bb)))}}u.Aa=function(){oc(this,!0)};
function Yb(a){a.ua=!0;var b=a.ma,c=mc(a);c>=a.ta?a.ma++:a.ma+=Math.ceil(a.ta/c);a.ma>=a.Za&&b<a.Za&&oc(a);a.ma>=a.ta&&(a.ma=0)}u.lc=function(){this.sa=0;if(this.aa){fc(this);try{this.ua=!1;do{for(var a=mc(this,this.Da),b=this.ba.length;0<b;b--){var c=this.ba[b-1];!(0>c.wa)&&a>c.wa&&(a=c.wa)}gc(this,hc(this,ic(this,a)))}while(this.aa&&!this.ua)}catch(d){A(this,d.message);bc(this);return}this.aa&&(this.sa=setTimeout(this.mb,kc(this)),this.Ia||this.ob())}};
function Zb(a){var b=a.ka[ec];return b?($b(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Ya-a.Ma)+a.Ma)/a.xa),!0):!1}function $b(a,b){void 0!==b&&(!a.ia&&0<a.fa&&a.fa<.9*a.ja&&(b=a.Va),a.Ba=b,b=a.Ja*a.Ba,a.ja!=b&&(a.ja=b,Pa(a,pc,nc(a.ja))),a.fa=a.ja);a.ra&&(a.Xa=1E6*a.fa/60+1E-8,a.da=0);a.ya=0;a.ca=a.ga=0;lc(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.bb&&lb(a,b,c.bb,!0)}}function lb(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.wa)&&(c=mc(a,c),a.aa&&(c+=hc(a)),b.wa=c)}
function fc(a){lc(a);a.za=0;a.La=0;a.la=Date.now();a.ca||(a.ca=a.la);if(a.ga){var b=a.la-a.ga;b>a.Da&&(a.ca+=b,a.ca>a.la&&(a.ca=a.la))}}function kc(a){a.ga=Date.now();a.La&&(a.ca+=a.La,a.la+=a.La);var b=a.Da;a.za&&(b=Math.round(b*a.za/a.Nb));b-=a.ga-a.la;var c=a.ga-a.ca;c&&(a.fa=a.ya/(10*c)/100);0>b?(-1E3>b&&(a.ca-=b),b=0):a.fa<a.ja&&(b=0);a.ga+=b;a.na(256,"after running %d cycles, resting for %dms\n",a.za,b);return b}
u.start=function(){if(this.aa||this.ea)return!1;this.sa&&(clearTimeout(this.sa),this.sa=0);this.aa=!0;this.ca=this.ga=0;oc(this,!0);this.ra||(this.sa=setTimeout(this.mb,0));this.Ia&&this.Qa(this.$a);return!0};function dc(a,b){b=void 0===b?1:b;a.aa||(b&&!a.ea&&(a.ea=b),a.ea&&(a.ea--,gc(a,hc(a,ic(a,jc(a,1)))),oc(a,!1),a.ea&&setTimeout(function(){dc(a,0)},0)))}function bc(a){a.ea?(a.ea=0,oc(a,!0)):a.aa&&(a.aa=!1,hc(a),oc(a,!0))}
function oc(a,b){b&&(a.aa?A(a,"started with "+nc(a.ja)+" target"):A(a,"stopped"));Pa(a,ac,a.aa?"Halt":"Run");Pa(a,cc,a.ea?"Stop":"Step");a.ia||Pa(a,pc,a.aa&&a.fa?nc(a.fa):"Stopped");for(var c=0;c<a.Ha.length;c++)a.Ha[c](void 0!=b)}var ac="run",pc="speed",cc="step",ec="throttle",Wb=120,Xb=60;
function qc(a,b,c){N.call(this,a,b,c);this.ja=J(this,"wrap",!1);this.qa=(this.ta=J(this,"font",""))&&rc[this.ta]||rc.Helvetica;this.ra=J(this,"rule","");this.ma=J(this,"pattern","");sc(this,this.ua=J(this,"message",""));this.za=J(this,"toggleColor",!1);this.ya=Array(tc(this).length);if(c=P(this,Tb)){this.aa=c;uc(this)||zb(c,!0);(this.ha=P(this,vc))&&bb(this.ha,this.Aa.bind(this),this.lb.bind(this));var d=this;this.va=new U(a,b+"Input",{"class":"Input",location:[0,0,c.cb,c.ab,c.ca,c.ua],drag:!(!this.ha||
!this.ha.Da),scroll:!(!this.ha||!this.ha.ua),hexagonal:c.Ba,bindings:{surface:Da(c,rb)}});db(this.va,function(e,f){var k=d.aa;0<=e&&0<=f&&(d.ia?Mb(k,e,f,d.ia)?Ob(k,e,f,1):d.za?Mb(k,e,f):Ob(k,e,f,1-Ib(k,e,f)):Ob(k,e,f,1-Ib(k,e,f)),Nb(k,e,f,tc(d,!!Ib(k,e,f))),W(k))});this.ga=[];this.xa=c.ea;wc(this,this.xa);xc(this);yc(this,this.pa[zc]);if(this.time=P(this,Xa))this.time.qa.push(this.hc.bind(this)),this.time.Ha.push(this.mc.bind(this));this.Ba=0;za(this,this.jc.bind(this))}}v(qc,N);u=qc.prototype;
u.Na=function(a,b){var c=this,d;switch(a){case Ac:case Bc:b.onchange=function(){Cc(c,a)};Cc(this);break;case zc:b.onchange=function(){yc(c)};break;case Dc:ya(b,Ec(this.pa[Dc]),!1,this.pa.pattern);b.onchange=function(){var e=c.ka[Dc];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?uc(c,e):c.lb())};break;case Fc:b.onclick=function(){var e=Gc(c,!0),f=c.ka[Hc];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');A(c,e)};break;case Ic:b.onclick=function(){var e=Gc(c);A(c,e);var f=window.location.href;
f=0<=f.indexOf("pattern=")?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((0>f.indexOf("?")?"?":"&")+"pattern="+e);window.location=f};break;case Hc:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.ka[Jc];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(Kc)?b.onclick=function(){xc(c,a)}:(d=this.pa[Dc])&&d[a]&&(b.onclick=function(){uc(c,a)})}N.prototype.Na.call(this,a,b)};
function Ec(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
u.hc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.ra){case Lc:var d=0;for(var e=this.aa,f=e.ca,k=e.da,h=this.ya,n=0;n<k;n++)for(var g=0;g<f;g++){var l=h,m=!1,p=4*(n*e.ba+g);if(p<=e.buffer.length-4&&e.buffer[p+1]){m=!0;p=e.buffer[p+2];for(var q=l.length-1;0<=q;q--)l[q]=p&15,p>>>=4}if(m){d++;if(h[0])h[0]--;else{m=(l=Ib(e,g,n))||0;switch(l){case 1:if(m=Y,h[0]=h[2],h[0]){h[0]--;break}case Y:if(h[3]&&(m=this.ga.indexOf(e.buffer[4*(n*e.ba+g)+1]||e.fa),0<=m)){for(m+=h[3];m>=this.ga.length;)m-=
this.ga.length;Mb(e,g,n,this.ga[m])}m=1;h[0]=h[1];h[0]&&h[0]--}m!==l&&Ob(e,g,n,m)}Nb(e,g,n,h)}}break;case Mc:c=a||c;d=c;d=void 0===d?1:d;e=0;f=this.aa;k=f.ba;h=f.da;if(f.la||!Nc(this,d))d=0;else{n=f.buffer;p=4*d;g=4*k;m=q=l=0;for(this.la=this.sa=-1;l<k-d;){for(var r=1,w=m,x=0;x<h;x++){var t=n[m],B=n[m]=n[m+p];t=B!==t?X:0;n[m+1]=n[m+p+1];n[m+2]=n[m+p+2];n[m+3]=n[m+p+3]|t;B&&(e++,r=0);m+=g}m=w+4;l++<f.ca&&(r?q++:(0>this.la&&(this.la=q),q=0))}0>this.la&&(this.la=q);for(this.sa=q;l<k;){p=m;for(q=0;q<
h;q++)Lb(f,n,m),m+=g;m=p+4;l++}f.ha=!0;f.la=d;d=e}break;case Oc:d=0;e=this.aa;f=e.buffer;k=e;k.ma||(k.ma=Array(k.Ha),Ab(k,k.ma));k=k.ma;h=e.ca;n=e.da;g=4*h+e.Ia;l=n*g;m=0;p=m-g;q=p-4;r=p+4;w=m-4;x=m+4;B=m+g;t=B-4;for(var F=B+4,H=0;H<n;H++){H?H==n-1&&(this.ja?(B-=l,t-=l,F-=l):B=t=F=l):this.ja?(p+=l,q+=l,r+=l):p=q=r=l;for(var R=0;R<h;R++){R?1==R?this.ja?(w-=g,q-=g,t-=g):(w=m-4,q=p-4,t=B-4):R==h-1&&(this.ja?(x-=g,r-=g,F-=g):x=r=F=l):this.ja?(w+=g,q+=g,t+=g):w=q=t=l;var S=f[m],L=f[q]+f[p]+f[r]+f[x]+f[F]+
f[B]+f[t]+f[w];3==L?S=1:2!=L&&(S=Y);k[m]=S;k[m+1]=f[m+1];k[m+2]=f[m+2];k[m+3]=f[m+3]|(f[m]!==S?X:0);m+=4;q+=4;p+=4;r+=4;x+=4;F+=4;B+=4;t+=4;w+=4;1==S&&d++}this.ja?(H||(p-=l,q-=l,r-=l),x+=g,r+=g,F+=g):(H||(p=m-g,q=p-4),x=m+4,r=p+4,F=B+4)}f=e.buffer;e.buffer=e.ma;e.ma=f;e.ha=!0}a||A(this,"active cells: "+d);b+=c}while(b<a)}return b};function Pc(a,b){var c=0;(a=a.ka[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function tc(a,b){var c=0;if(b&&(b=a.ka[Qc])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=Pc(a,Rc)+Pc(a,Sc),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<Tc.length;b++)c.push(Pc(a,Tc[b]));return c}
function uc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.ma.match(/^[0-9]/)||(b=a.ma);if(b){var k=a.pa[Dc];k=k&&k[b];if(!k)return A(a,"unknown pattern: "+b),!1;A(a,"loading pattern '"+b+"'");for(var h=b=0;b<k.length;b++){var n=k[b];if("#"==n[0])A(a,n);else if(h++){var g=n.indexOf("!");if(0<=g){f+=n.substr(0,g);break}f+=n}else{var l=n.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!l)return A(a,"unrecognized header line"),!1;var m=+l[1];var p=+l[2];l=l[3]}}}else{if(!a.ma)return!1;
f=0;l=a.ma.split("/");5==l.length&&(d=+l[f++],e=+l[f++]);if(3==l.length||5==l.length)m=+l[f++],p=+l[f++],f=l[f];else return A(a,"unrecognized pattern: "+a.ma),!1;l=a.ra}if(l!=a.ra)return A(a,"unsupported rule: "+l),!1;0>d&&(d=c.ba-m>>1);0>e&&(e=c.da-p>>1);return 0>d||d+m>c.ba||0>e||e+p>c.da?(a.na("pattern too large (%d,%d)\n",m,p),!1):0<Uc(a,d,e,f)}
function Uc(a,b,c,d,e){e=void 0===e?!1:e;var f=a.aa,k=[0,0,0,1],h=0,n=!1,g=!1;d=d.split(/([a-z$])/i);e||zb(f);for(var l=0,m=b,p=0;l<d.length-1;){var q=d[l++],r=d[l++],w=+q;for(q=""===q?1:w;q--;){var x=0,t=!1;switch(r){case "$":n=g=!1;b=m;c++;break;case "C":h=w;g=!0;break;case "R":k[0]=w;n=!0;break;case "G":k[1]=w;n=!0;break;case "B":k[2]=w;n=!0;break;case "A":k[3]=w;n=!0;break;case "b":t=Ob(f,b,c,Y);x++;break;case "o":t=Ob(f,b,c,1);x++;break;default:a.na("unrecognized pattern token: %s\n",r)}if(null==
t)a.na("invalid pattern position (%d,%d)\n",b,c);else{if(n){t=f;var B=k;t=4>B.length||1==B[3]?t.Ca("#%02x%02x%02x",B[0],B[1],B[2]):t.Ca("rgba(%d,%d,%d,%d)",B[0],B[1],B[2],B[3]);Mb(f,b,c,t)}g&&(t=4*(c*f.ba+b),t<=f.buffer.length-4&&f.buffer[t+2]!=h&&(f.buffer[t+2]=h));p<b&&(p=b);b+=x}}}e||W(f,!0);return 0>(p-=m-1)?0:p}
u.Oa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return A(this,"Invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.na("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.da=b.shift(),this.ea=b.shift(),this.ba=b.shift()}catch(d){return A(this,"CPU state error: "+d.message),!1}return Ba().message||Ba().pattern||Ba()[zc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Oa(a)?!0:!1};
u.jc=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":sc(this,a.join(" "));break;case "?":b="";Vc.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};u.hb=function(a){return a&&this.Oa(a)?!0:!1};u.Aa=function(a){this.time&&(a?this.time.start():bc(this.time))};u.lb=function(){A(this,"reset");zb(this.aa,!0);Gb(this.aa,!0);this.ua&&sc(this,this.ua)};u.ib=function(a){this.Pa(a)};
function Nc(a,b,c,d){b=void 0===b?1:b;c&&(a.ea=c,a.ba=d);switch(a.ea){case Wc:return!1;case Xc:case Yc:if(0<a.ba)return a.ba-=b,!0;break;case Zc:if(0<a.ba)return a.ba-=b,!1;break;case $c:if(a.la>a.sa)return!0;break;case ad:Gb(a.aa,!1);a.ea=Zc;break;case bd:Gb(a.aa,!0);a.ea=Zc;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.da>=a.ca.length&&(a.da=0);c=a.ca[a.da++];if("$"==c){d=0;for(var e=a.da;e<a.ca.length;){var f=a.ca.charCodeAt(e)-48;if(0>f||9<f)break;d=10*d+f;e++}if(e<a.ca.length)if(f=
a.ca[e++],"$"==f)a.da=e;else{var k=cd[f];if(k){a.da=e;a=Nc(a,b,k,d);break a}A(a,"unrecognized message code: $"+f)}}" "==c?a.ba+=2:(d=a.aa.ca+1,e=0>a.ba?a.ba:0,c=a.qa[c]||a.qa[c.toUpperCase()],f=Math.round((a.aa.ua-a.qa.height)/2),c&&(a.ba+=Uc(a,d+e,0>f?0:f,c,!0)),a.ba+=2-b);a.ea=Yc;a=!0}else a.ea=Wc,a=!1;return a}
function Gc(a,b){function c(S){var L=!1;null==l[3]&&(l[3]=1);if(x){if(n){if(l[0]!==r[0]||l[1]!==r[1]||l[2]!==r[2]||l[3]!==r[3])L=!0;R!==w&&(L=!0)}g!==q&&(L=!0);if(L||S&&q)n&&(m[0]!==r[0]&&(m[0]=r[0],e+=(r[0]||"")+"R"),m[1]!==r[1]&&(m[1]=r[1],e+=(r[1]||"")+"G"),m[2]!==r[2]&&(m[2]=r[2],e+=(r[2]||"")+"B"),m[3]!==r[3]&&(m[3]=r[3],e+=(r[3]||"")+"A"),p!==w&&(p=w,e+=(w||"")+"C")),1<x&&(e+=x),e+=1===q?"o":"b",L=!0}S?(e+="$",x=0):(L?x=1:x++,q=g,r[0]=l[0],r[1]=l[1],r[2]=l[2],r[3]=l[3],w=R)}var d=a.aa,e="",
f=0,k=a.aa.ba,h=a.aa.da,n=!!a.ga.length,g,l=[0,0,0],m=[0,0,0,1],p=0,q=0,r=[0,0,0,1],w=0,x=0;a=0;var t=d.ba-1,B=d.da-1;if(b){b&&(a=t,t=0);for(k=0;k<d.da;k++)for(h=0;h<d.ba;h++)(g=Ib(d,h,k))&&b&&(a>h&&(a=h),t<h&&(t=h));k=t-a+1;h=B+1;0>k&&(k=0);0>h&&(h=0)}for(var F=0;F<=B;F++){for(var H=a;H<=t;H++){g=Ib(d,H,F);Kb(d.buffer[4*(F*d.ba+H)+1]||d.fa,l);var R=Hb(d,H,F);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,h--,e=e.slice(1);for(;"$$"==e.slice(-2);)h--,e=e.slice(0,-1);"$"==e&&(h=0);e=(b?"":"0/"+f+"/")+k+"/"+h+
"/"+e.slice(0,-1);return e=e.replace(/\$+$/,"")}u.Pa=function(a){var b=[],c=[];b.push(2);b.push(this.ca);b.push(this.da);b.push(this.ea);b.push(this.ba);this.aa&&this.aa.Pa(c);a.push(b);a.push(c)};function sc(a,b){a.ca!=b&&(b&&A(a,"new message: '"+b+"'"),a.ca=b);a.ea=Xc;a.da=a.ba=0}u.toString=function(){return""};
function yc(a,b){var c=a.ka[zc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Da&&(a.Da.style.backgroundImage=b?"url('"+b+"')":"none")}}
function Cc(a,b){var c=a.ka[Ac],d=a.ka[Bc];b=b===Ac;c&&!c.options.length&&(ya(c,a.pa.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.fa=a.pa.colors[c.options[c.selectedIndex].value];for(var e in a.fa)if(b=a.pa[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),A(a,"overriding color '"+e+"' with "+b+" (formerly "+a.fa[e]+")"),a.fa[e]=b;ya(d,a.fa,!0)}c&&d&&d.options.length&&(a.ia=d.options[d.selectedIndex].value,xc(a))}
function wc(a,b){var c=a.ka[Bc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ia=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function xc(a,b){var c=1,d;!b&&a.ia&&(d=a.ka[dd])&&(d.style.backgroundColor=a.ia);if(a.fa)for(var e in a.fa){var f=a.fa[e];a.ga&&(a.ga[c-1]=f);var k=Kc+c++;d=a.ka[k];if(!d)break;d.style.display="inline-block";k==b&&wc(a,f);if(b&&b!=k||f!=a.ia)f=wb(f,1,.5);d.style.backgroundColor=f}for(;;){b=Kc+c++;b=a.ka[b];if(!b)break;b.style.display="none"}}u.mc=function(){this.time.aa||W(this.aa)};
var Ac="colorPalette",Bc="colorSelection",Kc="colorSwatch",dd="colorSwatchSelected",Qc="countInit",Rc="countOn",Sc="countOff",zc="backgroundImage",Dc="patterns",Hc="symbolInput",Jc="symbolPreview",Fc="save",Ic="saveToURL",Tc=[null,Rc,Sc,"countCycle"],Vc=["s\tset string"],Xc="load",Yc="scroll",Zc="pause",Wc="halt",$c="center",ad="off",bd="on",cd={b:ad,c:$c,h:Wc,o:bd,p:Zc,s:Yc},Lc="A4",Mc="L1",Oc="B3/S23",rc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};
function ed(a,b){N.call(this,a,a);var c=this;this.Ea=null;this.aa="";this.ca=this.da=!1;b=b.trim();"{"==b[0]?fd(this,b):(this.aa=b,Ha(this.aa,function(d,e,f,k){4==f&&(!k&&e?(fd(c,e),gd(c)):c.na("error (%d) loading configuration: %s\n",k,d))}));window.addEventListener("load",function(){c.da=!0;gd(c)});window.addEventListener((Ka("iOS")?"pagehide":Ka("Opera")?"unload":void 0)||"beforeunload",function(){hd(c)})}v(ed,N);
function gd(a){if(a.ca&&a.da){for(var b in a.pa){var c=void 0,d=void 0;try{var e=a.pa[b];d=e["class"];if(Z[d])if(d==id)a.na("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,jd,kd),a.aa&&a.na("Configuration: %s\n",a.aa);else{c=new Z[d](a.oa,b,e);if(d==Ta)if(a.Ea){a.na("too many CPU devices: %s\n",b);continue}else a.Ea=c;a.na("%s device: %s\n",d,c.status)}else a.na("unrecognized %s device class: %s\n",b,d)}catch(k){a.na("error initializing %s device '%s': %s\n",d,b,k.message),Ua(a,b)}}if(a.ba){var f=La(a);Sa(a,
function(k){k.hb&&k.hb(f)})}Sa(a,function(k){k.Aa&&k.Aa(a.ea)})}}function hd(a){if(a.ba){var b=[];Sa(a,function(c){c.ib&&c.ib(b)});Oa(a,b)}Sa(a,function(c){c.Aa&&c.Aa(!1)})}
function fd(a,b){try{a.pa=JSON.parse(b);var c=a.pa[a.oa];ua(a,c);if(a.version){var d="",e=null,f=O[a.oa];if(f)for(var k in f)if(f[k].Ra==a.oa){e=f[k];break}var h=e;if(h.version!=a.version){d="Machine";var n=h.version}else c.version&&c.version>a.version&&(d="Config",n=c.version);if(d){var g="Error: "+a.Ca("%s Device version (%3.2f) incompatible with %s version (%3.2f)",c.Pd,a.version,d,n)+"\n\nClearing your browser's cache may resolve the issue.",l=Qa.ac;l&&0>Qa.list.indexOf(l)&&(alert(g),Qa.list.push(l));
A(a,g)}}a.ba=!1!==c.autoSave;a.ea=!1!==c.autoStart;a.ca=!0}catch(m){c=m.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),A(a,"machine '"+a.oa+"' initialization error: "+c)}}var Sb="Bus",Ta="CPU",vc="Input",Tb="LED",id="Machine",Xa="Time",Z={};"undefined"!=typeof Va&&(Z[Sb]=Va);"undefined"!=typeof qc&&(Z[Ta]=qc);"undefined"!=typeof Chip&&(Z.Chip=Chip);"undefined"!=typeof Debugger&&(Z.Debugger=Debugger);"undefined"!=typeof U&&(Z[vc]=U);
"undefined"!=typeof qb&&(Z[Tb]=qb);"undefined"!=typeof ed&&(Z[id]=ed);"undefined"!=typeof Q&&(Z.Memory=Q);"undefined"!=typeof RAM&&(Z.RAM=RAM);"undefined"!=typeof Rb&&(Z.ROM=Rb);"undefined"!=typeof Vb&&(Z[Xa]=Vb);"undefined"!=typeof Video&&(Z.Video=Video);var jd="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",kd="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";window.LEDs=function(a,b){var c=new ed(a,b);window.command=function(d){return xa(c,d)};return c};})()

//# sourceMappingURL=leds.js.map
