(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu/cpu.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu/cpuleds.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/machine.js (C) Jeff Parsons 2012-2019
*/
var t;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={tb:!0},ha={};try{ha.__proto__=fa;ea=ha.tb;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function x(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ae=b.prototype}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},y="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ka(a,b){if(b){var c=y;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}ka("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ka("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});ka("Number.parseInt",function(a){return a||parseInt});
function la(){la=function(){};y.Symbol||(y.Symbol=ma)}function na(a,b){this.aa=a;ja(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.aa};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function oa(){la();var a=y.Symbol.iterator;a||(a=y.Symbol.iterator=y.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[y.Symbol.iterator]=function(){return this};return a}
function qa(a,b){oa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ka("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});
ka("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});
ka("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var f=0;f<e&&c<d;)if(this[c++]!=b[f++])return!1;return f>=e}});var ra=new ArrayBuffer(2);
(new DataView(ra)).setUint16(0,256,!0);new Uint16Array(ra);function sa(){}var z={};z.Defs=sa;function ta(){}x(ta,sa);function ua(a,b){var c=a/A|0,d=b/A|0;return(a&b)==(b|0)&&(c&d)==d}var A=Math.pow(2,32);z.NumIO=ta;function C(){}x(C,ta);t=C.prototype;t.flush=function(){var a=va;va="";this.Va(a)};
t.Pc=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};t.Va=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),wa||(wa=b),a=((b-wa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(va+a.substr(0,c)),va="",a=a.substr(c+1)),wa=null);va+=a;return a.length};function D(a,b,c){a.Va(b+"\n",c)}
t.ja=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.Va(this.za.apply(this,[a].concat(ba(c))))};
t.za=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*|~)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var h=e[g+5],n="ACDFHIMNSTWYbdfjcsoXx%".indexOf(h);if(0>n)d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+h;else{if(f<c.length){var k=c[f];"%"!=h&&f++}else k=c[c.length-1];var m=e[g+1],l=0<=m.indexOf("#"),r=0<=m.indexOf("0"),p=e[g+2];"*"==p||"~"==p?(p="~"==p?(k>>2)+(!l||"x"!=h&&"X"!=h?0:2):k,k=f<c.length?c[f++]:c[c.length-
1]):p=+p||0;var q=e[g+3];q=q?+q.substr(1):-1;var w=null,v=0,u="";n=12>n&&"object"!=typeof k?this.Pc(k):k;switch(h){case "C":k=l?"#":"";d+=isNaN(n.getTime())?void 0:this.za(this.za("%%%sW, %%%sF %%%sD, %%%sY",k),n);continue;case "D":k=l?n.getUTCDate():n.getDate();h="d";break;case "A":case "H":case "I":k=l?n.getUTCHours():n.getHours();"A"==h?(k=12>k?"am":"pm",h="s"):("I"==h&&(k=k?12<k?k-12:k:12),h="d");break;case "F":case "M":k=l?n.getUTCMonth():n.getMonth();"F"==h?(k=xa[k],h="s"):(k++,h="d");break;
case "N":k=l?n.getUTCMinutes():n.getMinutes();h="d";break;case "S":k=l?n.getUTCSeconds():n.getSeconds();h="d";break;case "T":k=l?"#":"";d+=isNaN(n.getTime())?void 0:this.za(this.za("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",k),n);continue;case "W":k=ya[l?n.getUTCDay():n.getDay()];h="s";break;case "Y":k=l?n.getUTCFullYear():n.getFullYear(),0<q&&(k%=Math.pow(10,q),q=-1),h="d"}switch(h){case "b":d+=k?"true":"false";break;case "d":k=Math.trunc(k);case "f":k=+k;h=k+"";0<=q&&(h=k.toFixed(q));h.length<
p&&(r?(0>k&&(p--,h=h.substr(1)),h=("0000000000"+h).slice(-p),0>k&&(h="-"+h)):h=("          "+h).slice(-p));d+=h;break;case "j":d+=JSON.stringify(k,null,p||void 0);break;case "c":k="string"==typeof k?k[0]:String.fromCharCode(k);case "s":if(void 0!==k)for("string"!=typeof k&&(k=k.toString()),0<=q&&(k=k.substr(0,q));k.length<p;)k=0<=m.indexOf("-")?k+" ":" "+k;d+=k;break;case "o":v=8,l&&(u="0");case "X":w=za;case "x":h="";v||(v=16);!u&&l&&(u="0x");w||(w=Aa);"string"==typeof k&&(k=Number.parseInt(k,k.match(/(^0x|[a-f])/i)?
16:10));r&&!p&&(p=Math.abs(k),p=255>=p?2:65535>=p?4:4294967295>=p?8:9,p+=u.length);p-=u.length;do l=k&v-1,k>>>=16==v?4:3,r||!h||l||k?h=w[l]+h:(u&&(h=u+h,u=""),0<p&&(h=" "+h));while(0<--p||k);d+=u+h;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+h+")"}}}return d+=e[g]};var va="",wa=null,Aa="0123456789abcdef",za="0123456789ABCDEF",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" ");
z.StdIO=C;function E(a){this.ka={};this.Ca=0;this.qa=this;a&&(this.qa.Ca=0,this.qa.Ja=[],this.qa.Ea=0,this.qa.ab={},this.qa.ie=!1)}var Ba;x(E,C);E.prototype.Na=function(a,b){var c=this;switch(a){case Ca.ec:b.onclick=function(){var d=c.$a(Ca.nb,!0);d&&(d.value="")};break;case Ca.nb:Da(b),b.addEventListener("keydown",function(d){Ea(c,d,!0)}),b.addEventListener("keypress",function(d){Ea(c,d)})}};
function Fa(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function Ga(a,b){var c=Ha.Ab;a.qa.ab[c]||(a.qa.ab[c]=[]);a.qa.ab[c].push(b)}function Da(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}E.prototype.$a=function(a){return this.ka[a]};
function Ia(a){var b=window;if(b){do{for(var c=0;c<Ja.length;c++){var d=Ja[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ka(a,b){return a.la.bindings&&a.la.bindings[b]}function La(a){if(a=a.ka[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function G(a,b,c,d){a=a.la[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Pa(){var a,b=Ba;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ba=b}return b}function Qa(a){if(void 0===H.lb){var b=!1;if(window)try{window.localStorage.setItem(H.Wa,H.Wa),b=window.localStorage.getItem(H.Wa)==H.Wa,window.localStorage.removeItem(H.Wa)}catch(c){D(a,c.message),b=!1}H.lb=b}return!!H.lb}
function Ra(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.Ca;return-1==(b|1)||ua(a.qa.Ca,b)?!0:!1}function Sa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ta(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.pa))&&(b=JSON.parse(c))}catch(d){D(a,d.message)}}return b}
function Ea(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.qa,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==I.xb&&f.selectionStart<=h+1&&(a=!0);d==I.Fc?(a=!0,0<e.Ea&&(g=e.Ja[--e.Ea])):d==I.hc&&(a=!0,e.Ea<e.Ja.length&&(g=e.Ja[++e.Ea]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Ea&&c+1==
g.length&&(f.value+=e.Ja[--e.Ea],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ua(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&D(a,b.replace(/\n$/,""),!1))}}
function Va(a,b){if(void 0!=b){var c=a.qa;try{if(b=b.trim())c.Ea<c.Ja.length&&b==c.Ja[c.Ea]?c.Ea++:(c.Ja.push(b),c.Ea=c.Ja.length);var d=b.split(" "),e=d[0],f=a.qa.ab[Ha.Ab];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(l){g+=l+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var n="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=n&&d.pop();1>=d.length&&(void 0!=n&&(h=n,n=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(K));
for(f=1;f<d.length;f++){e=d[f];var k=K[e];if(!k){g+="unrecognized message: "+e+"\n";break}void 0!=n&&Xa(a,k,n);if(void 0==h||h==Ra(a,k))g+=a.za("%8s: %b\n",e,Ra(a,k))}Ra(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(l){g+=l+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(l){g="error: "+l.message+"\n"}}return g}
function Ua(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Va(a,b[d])}return c}E.prototype.Va=function(a,b){void 0==b&&(b=Ra(this,0x800000000000));if(!b){var c=this.$a(Ca.nb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Sa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return C.prototype.Va.call(this,a,b)};
E.prototype.ja=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return Ra(this,d)?C.prototype.ja.call.apply(C.prototype.ja,[this,a].concat(ba(c))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.pa,b)}catch(c){D(a,c.message)}}}function $a(a,b,c){(a=a.ka[b])&&a.textContent!=c&&(a.textContent=c)}
function Xa(a,b,c){var d=!1;c?(c=a.qa.Ca,a.qa.Ca=(c|b)+(c/A|0|b/A|0)*A):(d=ua(a.qa.Ca,0x800000000000)&&ua(b,0x800000000000),c=a.qa.Ca,a.qa.Ca=(c&~b)+((c/A|0)&~(b/A|0))*A);d&&a.flush()}
var Ca={ec:"clear",nb:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],K={all:0xffffffffffff,buffer:0x800000000000},Ha={Ab:"command"},ab={Bb:13,kb:65,wb:66,yb:67,Cb:68,E:69,Db:70,Eb:71,Fb:72,Gb:73,Hb:74,Ib:75,Jb:76,Lb:77,Mb:78,Nb:79,Ob:80,Q:81,
Pb:82,Qb:83,Rb:84,Sb:85,Tb:86,Ub:87,Vb:88,Wb:89,sb:90,tb:97,le:98,me:99,d:100,e:101,qe:102,re:103,te:104,ue:105,ve:106,k:107,we:108,xe:109,n:110,ye:111,p:112,q:113,r:114,ze:115,t:116,Be:117,Ce:118,De:119,x:120,y:121,z:122},I={xb:8,Cc:9,qc:10,Bb:13,yc:16,fc:17,dc:18,Zd:19,mb:20,$c:27,Ac:32,be:33,ae:34,Zc:35,vd:36,Kb:37,Fc:38,rb:39,sd:39,hc:40,pd:44,ce:44,wd:45,Yc:46,rd:46,ud:47,ZERO:48,ONE:49,Ec:50,Dc:51,pc:52,oc:53,zc:54,xc:55,ic:56,rc:57,nc:59,mc:61,kb:65,wb:66,yb:67,Cb:68,E:69,Db:70,Eb:71,Fb:72,
Gb:73,Hb:74,Ib:75,Jb:76,Lb:77,Mb:78,Nb:79,Ob:80,Q:81,Pb:82,Qb:83,Rb:84,Sb:85,Tb:86,Ub:87,Vb:88,Wb:89,sb:90,zb:91,qd:91,od:92,fe:93,td:93,Ad:96,Rd:96,nd:96,Bd:97,Pd:97,Cd:98,Od:98,Dd:99,Ud:99,Ed:100,Sd:100,Fd:101,Ld:101,Gd:102,Wd:102,Hd:103,Qd:103,Id:104,Yd:104,Jd:105,Vd:105,Td:106,Kd:107,Xd:109,Md:110,Nd:111,ad:112,ed:113,fd:114,gd:115,hd:116,jd:117,kd:118,ld:119,md:120,bd:121,cd:122,dd:123,sc:144,vc:145,lc:173,wc:186,jc:187,Xc:188,gc:189,$d:190,he:191,Vc:192,xd:219,Wc:220,ee:221,de:222,kc:224,yd:901,
je:1E3},bb={},cb=(bb[I.nc]=I.wc,bb[I.mc]=I.jc,bb[I.lc]=I.gc,bb[I.kc]=I.zb,bb),db={Kb:1,rb:2,zd:3},L={},eb=(L[I.xb]="\b",L[I.Cc]="\t",L[I.qc]="\n",L[I.Bb]="\r",L[I.Ac]=" ",L[I.ZERO]="0",L[I.ONE]="1",L[I.Ec]="2",L[I.Dc]="3",L[I.pc]="4",L[I.oc]="5",L[I.zc]="6",L[I.xc]="7",L[I.ic]="8",L[I.rc]="9",L[I.kb]="A",L[I.wb]="B",L[I.yb]="C",L[I.Cb]="D",L[I.E]="E",L[I.Db]="F",L[I.Eb]="G",L[I.Fb]="H",L[I.Gb]="I",L[I.Hb]="J",L[I.Ib]="K",L[I.Jb]="L",L[I.Lb]="M",L[I.Mb]="N",L[I.Nb]="O",L[I.Ob]="P",L[I.Q]="Q",L[I.Pb]=
"R",L[I.Qb]="S",L[I.Rb]="T",L[I.Sb]="U",L[I.Tb]="V",L[I.Ub]="W",L[I.Vb]="X",L[I.Wb]="Y",L[I.sb]="Z",L[I.Kb]="Left",L[I.rb]="Right",L),fb={list:[],Gc:"version"},Ja=["","moz","ms","webkit"],gb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",
cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",
dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",
lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",
midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",
royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},H={lb:void 0,Wa:"PCjs.localStorage"};
z.WebIO=E;function M(a,b,c,d){E.call(this,a==b);this.pa=a;this.xa=b;O[this.pa]||(O[this.pa]={});O[this.pa][this.xa]&&this.ja("warning: machine configuration contains multiple '%s' devices\n",this.xa);O[this.pa][this.xa]=this;this.id=this.pa+"."+this.xa;hb.push(this);this.qa=ib(this,this.pa);jb(this,c,d)}x(M,E);
function jb(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d=Pa();for(h in d)if(0<=c.indexOf(h)){var e=d[h];if(e.match(/^[+-]?[0-9.]+$/))var f=Number.parseInt(e,10);else"true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"');b[h]=f;D(a,"overriding "+a.xa+" property '"+h+"' with "+e)}}a.la=b;c=b.bindings;c=void 0===c?{}:c;a.la.ka||(a.la.ka=c);d=Array.isArray(c);c.container||(c.container=a.xa);for(var g in c){f=c[g];if(d)g=f;else if(f.match(/^[0-9]+$/)){var h=+f;a.ka[g]=[];do{f=
g+h++;f=document.getElementById(f);if(!f)break;a.ka[g].push(f)}while(1);continue}if(h=document.getElementById(f))a.ka[g]=h,a.Na(g,h)}b=void 0===b?{}:b;a.version=2;if(a.version){g="";var n;a.pa!=a.xa&&(n=ib(a,a.pa).version)&&n!=a.version&&(g="Machine");g||(n=b.version)&&n>a.version&&(g="Config");g&&(n="Error: "+a.za("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.ne,a.version,g,n)+"\n\nClearing your browser's cache may resolve the issue.",(b=fb.Gc)&&0>fb.list.indexOf(b)&&(alert(n),
fb.list.push(b)),D(a,n))}}function kb(a,b){var c;try{var d=O[a.pa];if(d)for(c in d){var e=d[c];if("Machine"!=e.la["class"]&&!b(e))break}}catch(f){a.ja("error while enumerating device '%s': %s\n",c,f.message)}}M.prototype.$a=function(a,b){b=void 0===b?!1:b;if(a){var c=E.prototype.$a.call(this,a,b);if(void 0===c&&b){b=O[this.pa];for(var d in b)if(c=b[d].ka[a])break;c||(c=null);this.ka[a]=c}}return c};
function ib(a,b){var c=b,d=a.pa,e=d.indexOf(".");0<e&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=O[d])&&e[b]||null;if(!b){for(e=0;e<hb.length;e++)if(hb[e].id===c){b=hb[e];break}if(!b)throw Error(a.za("unable to find device with ID '%s'",c));}return b}function P(a,b,c){var d=null,e=O[a.pa];if(e)for(var f in e)if(e[f].la["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.za("unable to find device with class '%s'",b));return d}
M.prototype.ja=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&Ra(this,a)&&(void 0===this.Ra&&(this.Ra=P(this,"Debugger",!1)),this.qa.Ca&lb&&(void 0===this.Oa&&(this.Oa=P(this,"CPU")),this.Oa))?(a=c.shift(),E.prototype.ja.call(this,"%#06x: %s.%s\n",this.Oa.Qc,this.xa,this.za.apply(this,[a].concat(ba(c))).trim())):E.prototype.ja.call.apply(E.prototype.ja,[this,a].concat(ba(c)))};function mb(a,b){(a=O[a.pa])&&delete a[b]}var O={},hb=[],lb=1;
K.addr=lb;K.bus=2;K.memory=4;K.ports=8;K.chips=16;K.kbd=32;K.serial=64;K.misc=128;K.cpu=256;K.video=512;K.monitor=1024;K.screen=2048;K.time=4096;K.timer=8192;K.event=16384;K.input=32768;K.key=65536;K.mouse=131072;K.touch=262144;K.warn=524288;K.halt=1048576;window&&(window.PCjs||(window.PCjs={}),O=window.PCjs.Machines||(window.PCjs.Machines={}),hb=window.PCjs.Components||(window.PCjs.Components=[]));z.Device=M;
function nb(a,b,c){M.call(this,a,b,c);this.type="static"==c.type?ob:pb;this.da=c.addrWidth||16;this.ca=Math.pow(2,this.da);this.aa=c.blockSize||(16<this.da?4096:1024);this.aa>this.ca&&(this.aa=this.ca);this.ga=this.ca/this.aa|0;this.fa=Math.log2(this.aa)|0;this.ea=c.dataWidth||8;this.ba=Array(this.ga);a=new Q(a,b+"[NONE]",{size:this.aa,bus:this.xa});for(b=0;b<this.ca;b+=this.aa)qb(this,b,this.aa,R.NONE,a)}x(nb,M);
function qb(a,b,c,d,e){for(var f=0,g=b>>>a.fa;0<c&&g<a.ba.length;){var h=g*a.aa,n=a.aa-(b-h);n>c&&(n=c);var k=a.ba[g];if(b!=h||n!=a.aa||k&&k.type!=R.NONE)break;var m=k=void 0,l=b,r=a.da,p=16;r=void 0===r?0:r;k=void 0===k?0:k;var q="",w="",v=-1;p||(p=a.ha||10);r&&(v=Math.ceil(r/Math.log2(p)));if(void 0==m)switch(p){case 8:m="0o";break;case 16:m="0x";break;case 10:w=".";default:m=""}isNaN(l)||"number"!=typeof l?(l=void 0,m=w=""):(0>l&&-1<l&&(l=-1),r&&(0>l&&(l+=Math.pow(2,r)),l>=Math.pow(2,r)&&(v=Math.ceil(Math.log(l)/
Math.log(p)))));for(r=k||-1;v--;){r||(q=","+q,r=k);if(void 0==l){if(q="?"+q,0>v)break}else{var u=l%p;l=Math.trunc(l/p);u+=0<=u&&9>=u?48:55;q=String.fromCharCode(u)+q;if(!l&&0>v)break}r--}k=a.xa+"["+(m+q+w)+"]";if(e)if(e.size==a.aa)b=e;else{m=void 0;if(e.values&&(m=e.values.slice(f,f+n),m.length!=n))break;b=new Q(a.pa,k,{type:d,Xb:b,size:n,bus:a.xa,values:m})}else b=new Q(a.pa,k,{type:d,Xb:b,size:n,bus:a.xa});a.ba[g]=b;b=h+a.aa;c-=n;f+=n;g++}}t=nb.prototype;t.Ha=function(){};
t.ub=function(a){return a&&this.Ga(a)?!0:!1};t.vb=function(a){this.Ia(a)};t.Ga=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==pb||c.type&R.qb)&&c.Ga){var d=a.shift();if(!c.Ga(d))return!1}}return!0};t.Ia=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==pb||c.type&R.qb)&&c.Ia){var d=[];c.Ia(d);a.push(d)}}};var ob=0,pb=1;z.Bus=nb;
function Q(a,b,c){M.call(this,a,b,c);this.Xb=c.addr;this.size=c.size;this.type=c.type||R.NONE;this.ca=(a=this.la.bus)?ib(this,a):P(this,a="Bus");if(!this.ca)throw Error(this.za("unable to find bus '%s'",a));this.ea=this.ca.ea;this.ha=Math.pow(2,this.ea)-1;this.values=this.ba=null;if(a=this.ca.type==ob)if(a=8==this.ea)a=ib(this,this.pa),a=!1!==(a&&a.la&&a.la.ArrayBuffer);a&&(this.ba=new ArrayBuffer(this.size),new DataView(this.ba,0,this.size),this.values=new Uint8Array(this.ba,0,this.size),new Uint16Array(this.ba,
0,this.size>>1),new Int32Array(this.ba,0,this.size>>2));this.ga=!1;rb(this,c.values)}x(Q,M);function rb(a,b){if(!a.values)b?a.values=b:a.values=Array(a.size).fill(a.ha);else if(b)for(var c=0;c<a.size;c++)a.values[c]=b[c]}Q.prototype.Ha=function(){this.type>=R.qb&&this.values.fill(0)};
Q.prototype.Ga=function(a){var b=a.shift();if(this.xa==b){this.ga=a.shift();a.shift();a=a.shift();var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}rb(this,a);return!0}return!1};Q.prototype.Ia=function(a){a.push(this.xa);a.push(this.ga);a.push(!1);for(var b=this.values,c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}a.push(e.length>=b.length?b:e)};
var R={NONE:1,tc:2,qb:4,ge:14,ke:12};z.Memory=Q;
function sb(a,b,c){c.type=R.tc;Q.call(this,a,b,c);qb(this.ca,c.addr,c.size,c.type,this);this.Oa=this.Ra=void 0;if(z.LED&&this.ka[tb]){var d=this;this.da=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.fa=this.values.length/this.da|0;this.aa=new ub(a,b+"LEDs",{"class":"LED",bindings:{container:Ka(this,tb)},type:vb,cols:this.da,rows:this.fa,color:G(this,"colorROM","green"),backgroundColor:G(this,"backgroundColorROM","black"),persistent:!0}),wb(this.aa,!0);this.ia=new xb(a,b+"Input",{"class":"Input",
location:[0,0,this.aa.Aa,this.aa.ya,this.da,this.fa],bindings:{surface:Ka(this,tb)}});this.ma=La(this)||"";yb(this.ia,function(e,f){if(d.Oa){var g=d.ma;0<=e&&0<=f&&(g="");$a(d,Ma,g)}})}}x(sb,Q);
sb.prototype.Ga=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.aa.length==d?(this.aa.aa=c,U(this.aa,!0)):(this.ja("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.ja("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};sb.prototype.Fa=function(){void 0===this.Oa&&(this.Oa=P(this,"CPU"));void 0===this.Ra&&(this.Ra=P(this,"Debugger",!1))};
sb.prototype.Ia=function(a){this.aa&&(a.push(this.aa.aa),a.push(this.values))};var tb="array",Ma="cellDesc";z.ROM=sb;
function xb(a,b,c){M.call(this,a,b,c);this.Ca=32768;this.ia=this.oa=null;this.time=P(this,"Time");this.qa=P(this,"Machine");this.va=G(this,"drag",!1);this.ma=G(this,"scroll",!1);this.Aa=G(this,"hexagonal",!1);this.ea=G(this,"releaseDelay",0,void 0);this.fa=!1;a=this.la.map;this.ba=this.ca=null;if(a)if(a.length)this.ba=a;else{this.ca={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.ca[f]=
{keys:g,se:e,state:0}}}this.ra=[];this.sa=[];this.da=this.ta=null;(a=this.ka[zb])&&Ab(this,a,this.$a(c.focusBinding,!0),this.la.location);this.Ha()}x(xb,M);function yb(a,b){a.oa=b}function Bb(a,b){a.ia=b}function Cb(a,b,c){for(var d=0;d<a.ra.length;d++){var e=a.ra[d];e.id===b&&e.ac(b,c)}}
function Ab(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.ba||a.ca){var e={};e.Tc=d[0]||0;e.Uc=d[1]||0;e.Xa=d[2]||b.clientWidth;e.eb=d[3]||b.clientHeight;e.fb=d[4]||1;e.ib=d[5]||1;e.Kc=d[6]||b.naturalWidth||e.Xa;e.Mc=d[7]||b.naturalHeight||e.eb;e.bc=d[8]||0;e.cc=d[9]||0;e.Jc=d[10]||0;e.Lc=d[11]||0;a.ba?(e.hb=a.ba.length,e.Ya=a.ba[0].length):(e.Ya=e.fb,e.hb=e.ib,e.fb=e.ib=0);e.Yb=e.Xa/(e.Ya+e.Ya*e.fb)|0;e.Zb=e.eb/(e.hb+e.hb*e.ib)|0;e.Ic=e.Yb*e.fb|0;e.$b=e.Zb*e.ib|0;e.Za=e.jb=-1;Db(a,b,e);Eb(a,b,e);a.time&&
a.ea&&(a.ya=Fb(a.time,"timerInputRelease",function(){0>e.Za&&0>e.jb&&Gb(a,-1,-1)}))}if(a.ba||a.ca)a.time&&a.ea&&(a.Ba=Fb(a.time,"timerKeyRelease",function(){Hb(a)})),a.ga=0,a.na="",a.ha=[],d=b,c&&(d=c,a.da||"BUTTON"!=c.nodeName||(d=document,a.da=c,Ib(a,b),a.ta=b)),Ib(a,d),a.da||(a.da=d)}function Jb(a){a.ea?Kb(a.time,a.Ba,a.ea):Hb(a)}
function Ib(a,b){function c(e,f,g){var h=document.activeElement;a.ja(81920,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.da&&e!=a.da&&e!=a.ta?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Lb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Lb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Lb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Db(a,b,c){b.addEventListener("mousedown",function(d){if(!a.fa){var e=a.da;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||V(a,b,Mb,d,c)}});b.addEventListener("mousemove",function(d){a.fa||V(a,b,Nb,d,c)});b.addEventListener("mouseup",function(d){a.fa||d.button||V(a,b,W,d,c)});b.addEventListener("mouseout",function(d){a.fa||(0>c.Za?V(a,b,Nb,d,c):V(a,b,W,d,c))})}
function Eb(a,b,c){b.addEventListener("touchstart",function(d){a.ma&&(a.fa=!0);V(a,b,Mb,d,c)});b.addEventListener("touchmove",function(d){V(a,b,Nb,d,c)});b.addEventListener("touchend",function(d){V(a,b,W,d,c)})}
function Lb(a,b,c,d){if(void 0!=c){var e=cb[b]||b;var f=eb[b];var g=Ob[e];d=d&&d.location==db.rb;g&Pb&&d&&(g>>=1);g&&(g&Qb&&(c=!(a.aa&g)),a.aa=c?a.aa|g:a.aa&~g,Cb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=ab.kb&&b<=ab.sb?a.aa&(Rb|Sb)||(a.aa|=Sb,Cb(a,I.mb,!0)):b>=ab.tb&&b<=ab.z&&a.aa&Sb&&(a.aa&=~Sb,Cb(a,I.mb,!1));if(a.ba){if(void 0!=c)return!1;for(e=0;e<a.ba.length;e++)for(g=a.ba[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.ga?16>a.ha.length&&a.ha.push(b):(a.ga=1,a.na=
f,Gb(a,d,e),Cb(a,f,!0),Jb(a)),!0}if(a.ca){if(void 0==c)return!0;b=Object.keys(a.ca);for(e=0;e<b.length;e++)if(g=b[e],0<=a.ca[g].keys.indexOf(f))return Cb(a,g,c),a.ca[g].state=c?1:0,!0}return!1}function Hb(a){1==a.ga?(a.ga++,Cb(a,a.na,!1),a.na="",Gb(a,-1,-1),Jb(a)):(a.ga=0,a.ha.length&&Lb(a,a.ha.shift()))}xb.prototype.Ha=function(){this.aa=0;this.ua=this.wa=-1};
function V(a,b,c,d,e){var f=-1,g=-1,h=!1,n=-1,k=-1;if(c<W){d=d||window.event;d.targetTouches&&d.targetTouches.length?(n=d.targetTouches[0].clientX,k=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(n=d.clientX,k=d.clientY);var m=d.target.getBoundingClientRect();n-=m.left;k-=m.top;n=e.Kc/b.offsetWidth*n|0;k=e.Mc/b.offsetHeight*k|0;var l=n-e.Tc;var r=k-e.Uc;var p=m=!1;var q=n>=e.bc&&n<e.bc+e.Jc&&k>=e.cc&&k<e.cc+e.Lc;if(0<=l&&l<e.Xa&&0<=r+e.$b||q)if(h||a.ma||d.preventDefault(),0<=l&&l<e.Xa&&0<=
r&&r<e.eb){p=!0;d=e.Xa/e.Ya|0;var w=e.eb/e.hb|0,v=l/d|0,u=r/w|0;!a.Aa||u&1||(l-=d>>1,v=l/d|0,v==e.Ya-1&&(l=-1));w=u*w+(e.$b>>1);l-=v*d+(e.Ic>>1);r-=w;0<=l&&l<e.Yb&&0<=r&&r<e.Zb&&(f=v,g=u,m=!0)}}l=l||0;r=r||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Mb||c==W)for(v=0;v<a.sa.length;v++)u=a.sa[v],c==W?u.ac(u.id,!1):(w=r/(b/u.pe|0)|0,(l/(d/u.oe|0)|0)==u.Ee&&w==u.Fe&&u.ac(u.id,!0));if(!h)if(c==Mb)e.Za=n,e.jb=k,p?(Gb(a,f,g),m&&a.ea&&Kb(a.time,a.ya,a.ea,!0)):q&&a.qa.Fa();else if(c==Nb)0<=e.Za&&0<=e.jb&&a.va?
Gb(a,f,g):a.oa&&a.oa(f,g);else if(c==W){if(c=a.ea)c=a.time,f=a.ya,c=c.aa&&0<f&&f<=c.ba.length?0<=c.ba[f-1].Da:!1;c||Gb(a,-1,-1);e.Za=e.jb=-1}else D(a,"unrecognized action: "+c)}function Gb(a,b,c){if(b!=a.ua||c!=a.wa)a.ua=b,a.wa=c,a.ia&&a.ia(b,c)}var Mb=1,Nb=2,W=3,zb="surface",Rb=3,Pb=170,Sb=512,Qb=3584,X={},Ob=(X[I.yc]=2,X[I.fc]=8,X[I.dc]=32,X[I.zb]=128,X[I.mb]=Sb,X[I.sc]=1024,X[I.vc]=2048,X);z.Input=xb;
function ub(a,b,c){M.call(this,a,b,c,["color","backgroundColor"]);a=this.ka[Tb];if(!a)throw Error("LED "+this.la.ka[Tb]+" binding for '"+Tb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Qa=a;this.type=Na(G(this,"type",vb,Ub),Vb,Wb);this.ha=Xb[this.type][0];this.na=Xb[this.type][1];this.width=G(this,"width",this.ha,void 0);this.height=G(this,"height",this.na,void 0);
this.da=G(this,"cols",1,void 0);this.ca=this.da+G(this,"colsExtra",0,void 0);this.wa=G(this,"rows",1,void 0);this.ea=this.wa+G(this,"rowsExtra",0,void 0);this.Aa=this.width*this.da;this.ya=this.height*this.wa;this.ga=Yb("black",0);this.fa=Zb(this.la.color)||this.ga;this.cb=Yb(this.fa,1,.25);this.bb=Yb(this.fa,1,2);this.ma=Zb(this.la.backgroundColor);this.ob=G(this,"fixed",!1);this.ob||(b.style.width="100%",b.style.height="auto");this.Pa=G(this,"hexagonal",!1);this.pb=G(this,"highlight",!0);this.Ka=
G(this,"persistent",this.type<Wb);b.setAttribute("width",this.Aa.toString());b.setAttribute("height",this.ya.toString());b.style.backgroundColor=this.ga;a.appendChild(b);this.Sa=b.getContext("2d");if(this.sa=document.createElement("canvas"))this.sa.width=this.Ma=this.ha*this.da,this.sa.height=this.ua=this.na*this.wa,this.ba=this.sa.getContext("2d");this.Ta=(this.ea+1)*this.ca*4;this.aa=Array(this.Ta);this.ra=null;this.Ua=this.da<this.ca?4*(this.ca-this.da):0;this.ia=this.ta=!1;this.La=0;this.Ba=!0;
this.oa=0;this.va=-1;var d=this;this.time=P(this,"Time");$b(this.time,function(e){U(d,!1,e)});wb(d,!0)}x(ub,M);function wb(a,b){ac(a,a.aa);a.ia=a.ta=!0;b&&U(a,!0)}function bc(a){a.ma?(a.ba.fillStyle=a.ma,a.ba.fillRect(0,0,a.Ma,a.ua)):a.ba.clearRect(0,0,a.Ma,a.ua)}
function U(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.ia||b){if(a.type<Wb){var d=0;if(!a.Ka||b)bc(a);else if(a.oa){d=a.da-a.oa;var e=a.ha*d;a.ba.drawImage(a.sa,a.ha*a.oa,0,e,a.ua,0,0,e,a.ua)}for(var f=e=0;f<a.ea;f++){for(var g=0;g<a.da;g++){var h=a.aa[e],n=a.aa[e+1]||a.ga,k=!1,m=!!(a.aa[e+3]&Y),l=a.pb&&e==a.va;!a.Ba&&h&&(h=Z,m=k=!0);if(m||l||b){if(g>=d)a:{m=a;var r=h;h=n;var p=g;n=f;var q=l;p=void 0===p?0:p;n=void 0===n?0:n;q=void 0===q?!1:q;var w=0;if(m.Pa&&!(n&1)&&(w=m.ha>>1,p==m.da-1))break a;
if(h&&h!=m.fa){q=q?Yb(h,1,2):h;var v=Yb(h,1,.25)}else q=q?m.bb:m.fa,v=m.cb;h=!1;r=r?q:v;q==m.ga&&(r=m.ma,h=!0);q=p*m.ha+w;v=n*m.na;m.Ka&&(p=p*m.ha+w,n*=m.na,m.ma?(m.ba.fillStyle=m.ma,m.ba.fillRect(p,n,m.ha,m.na)):m.ba.clearRect(p,n,m.ha,m.na));m.ba.fillStyle=r;n=cc[m.type];3==n.length?(m.ba.beginPath(),m.ba.arc(q+n[0],v+n[1],n[2],0,2*Math.PI),h?(m.ba.globalCompositeOperation="destination-out",m.ba.fill(),m.ba.globalCompositeOperation="source-over"):m.ba.fill()):m.ba.fillRect(q+n[0],v+n[1],n[2],n[3])}a.aa[e+
3]=l||k?a.aa[e+3]|Y:a.aa[e+3]&~Y}e+=4}e+=a.Ua}a.oa=0}else{b="";for(d=0;d<a.aa.length;d+=4)b+=a.aa[d]||" ",a.aa[d+3]&dc&&(b+=".");bc(a);for(f=e=d=0;d<b.length;d++){m=b[d];"."==m&&e&&e--;g=a;k=e;l=f;k=void 0===k?0:k;l=void 0===l?0:l;if(m=ec[m])for(n=0;n<m.length;n++)if(h=g,p=fc[m[n]]){w=(void 0===k?0:k)*h.ha;r=(void 0===l?0:l)*h.na;h.ba.fillStyle=h.fa;h.ba.beginPath();if(3==p.length)h.ba.arc(w+p[0],r+p[1],p[2],0,2*Math.PI);else for(q=0;q<p.length;q+=2)q?h.ba.lineTo(w+p[q],r+p[q+1]):h.ba.moveTo(w+p[q],
r+p[q+1]);h.ba.closePath();h.ba.fill()}if(++e==a.da&&(e=0,++f==a.ea))break}}a.Sa.globalCompositeOperation=a.ma&&a.fa!=a.ga?"source-over":"copy";a.Sa.drawImage(a.sa,0,0,a.Ma,a.ua,0,0,a.Aa,a.ya);a.ia=!1;a.va=-1}else a.Ka||a.ta||(!c||!a.La||c-a.La>=(1E3/60|0))&&wb(a,!0);a.ta=!1;c&&(a.La=c)}function gc(a,b){b=void 0===b?!0:b;a.Ba!=b&&(a.Ba=b,a.ia=!0)}function hc(a,b,c){b=4*(c*a.ca+b);return b<=a.aa.length-4?a.aa[b+2]:0}function ic(a,b,c){var d;b=4*(c*a.ca+b);b<=a.aa.length-4&&(d=a.aa[b]);return d}
function Zb(a){return(a=a||void 0)&&gb[a]||a}function Yb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=gb[a]||a;if(jc(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function ac(a,b){for(var c=0;c<b.length;c+=4)kc(a,b,c)}function kc(a,b,c){b[c]=a.type<Wb?Z:" ";b[c+1]=a.fa==a.ga?null:a.fa;b[c+2]=0;b[c+3]=Y}
ub.prototype.Ga=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.fa&&c==this.ma&&a&&a.length==this.aa.length){this.aa=a;for(b=0;b<=this.aa.length-4;b+=4)this.aa[b+1]==this.ga&&(this.aa[b+1]=null);U(this,!0);return!0}return!1};function jc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
ub.prototype.Ia=function(a){this.aa&&(a.push(this.fa),a.push(this.ma),a.push(this.aa))};function lc(a,b,c,d){var e=null;0<=c&&c<a.ea&&0<=b&&b<a.ca&&(e=!1,d=d||a.fa,d==a.ga&&(d=null),b=4*(c*a.ca+b),a.aa[b+1]!==d&&((a.aa[b+1]=d)||(a.aa[b]=Z),a.aa[b+3]|=Y,a.ia=e=!0),a.va=b,a.ta=!0);return e}function mc(a,b,c,d){if(0<=c&&c<a.ea&&0<=b&&b<a.ca){b=4*(c*a.ca+b);c=0;if(a.aa[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.aa[b+2]!==c&&(a.aa[b+2]=c,a.aa[b+3]|=Y,a.ia=!0);a.va=b;a.ta=!0}}
function nc(a,b,c,d){var e=!1,f=0&oc;b=4*(c*a.ca+b);if(b<=a.aa.length-4){if(a.aa[b]!==d||(a.aa[b+3]&oc)!==f)a.aa[b]=d,a.aa[b+3]=a.aa[b+3]&~oc|f|Y,a.ia=e=!0;a.va=b;a.ta=!0;a.oa=0}return e}
var Vb=0,vb=1,Wb=3,Ub={small:Vb,round:vb,square:2,digit:Wb},Tb="container",Z=0,oc=129,dc=1,Y=128,pc={},cc=(pc[Vb]=[4,4,4],pc[vb]=[16,16,14],pc[2]=[2,2,28,28],pc),Xb=[[8,8],[32,32],[32,32],[96,128]],fc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},ec={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};z.LED=ub;
function qc(a,b,c){M.call(this,a,b,c);this.Pa=G(this,"cyclesMinimum",1E5,void 0);this.bb=G(this,"cyclesMaximum",1E9,void 0);this.Qa=Na(G(this,"cyclesPerSecond",1E6,void 0),this.Pa,this.bb);this.ta=1E3/60;this.uc=G(this,"updatesPerSecond",2,void 0)||2;this.pb=1E3/this.uc;this.Ua=0;this.Bc=G(this,"timeLock",!0);this.La=this.na=0;this.Ka=this.ga=1;this.Ta=this.ia=this.Qa/1E4/100;this.ya=[];this.sa=[];this.ba=[];this.Aa=[];this.Sa=this.aa=this.wa=this.ha=!1;this.ma=this.da=0;a=Ia("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ta}this.cb=window[a].bind(window,this.Rc.bind(this),d);this.ob=window[Ia("cancelAnimationFrame")||"clearTimeout"].bind(window);this.va=this.ua=this.fa=this.ca=this.Ma=0;rc(this)||sc(this,this.Ka)}x(qc,M);function $b(a,b){a.ya.push(b)}t=qc.prototype;
t.Na=function(a,b){var c=this;switch(a){case tc:b.onclick=function(){uc(c)&&(c.aa?vc(c):c.start())};break;case wc:b.onclick=function(){sc(c,c.ga<<1);xc(c,yc(c.ia))};break;case zc:b.onclick=function(){uc(c)&&(c.aa?D(c,"already running"):c.da?vc(c):Ac(c,void 0))};break;case Bc:b.addEventListener("mousedown",function(){c.ha=!0}),b.addEventListener("mouseup",function(){rc(c);c.ha=!1}),b.addEventListener("mousemove",function(){c.ha&&rc(c)}),b.addEventListener("change",function(){c.ha=!0;rc(c);c.ha=!1})}M.prototype.Na.call(this,
a,b)};function Fb(a,b,c){var d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,Hc:c,gb:d,Da:-1});0<=d&&Kb(a,e,d);return e}
function Cc(a,b,c,d){var e=0,f=a.ia,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.ja(4096,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.ta&&(1<a.ga&&(a.ga>>=1,a.ja(524288,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ta,a.ga)),e=d));a.na=f;a.La=f/a.Ta;b=a.La/a.ga;a.Ma=g/b/60+1E-8;a.ja(4096,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Ma,g,b,60);return e}
function Dc(a,b){a.ua=a.fa=b;if(!a.sa.length)return a.fa=0,a.ua;for(var c=0;0<a.fa;){if(c<a.sa.length){var d=a.sa[c++];b=d.Sc.call(d,b)||1}else c=b=0;a.fa-=b}return a.ua-a.fa}function Ec(a,b){b=void 0===b?a.ua-a.fa:b;if(!a.aa){if(a.ca)for(var c=0;c<a.sa.length;c++);a.ca=b}a.ca-=b;1>a.ca&&(a.wa=!0);a.va+=b;a.ua=a.fa=0;a.aa||(a.va=0);return b}
function Fc(a,b){b=void 0===b?0:b;if(b){var c=b;a.ca+=b}else for(c=a.ca,1>c&&(c=a.ca+=a.Ma),0>c&&(a.ja(524288,"warning: cycle count dropped below zero: %f\n",c),c=a.ca=0),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.Da)&&c>d.Da&&(c=d.Da)}return c}function yc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function uc(a){return a.Sa?!0:(D(a,"not powered"),!1)}
function Gc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.Da||(d.Da-=b,0>=d.Da&&(d.Da=-1,d.Hc(),0<=d.gb&&Kb(a,c,d.gb)))}}t.Fa=function(a){this.Sa=a;void 0===this.Ra&&(this.Ra=P(this,"Debugger",!1))};
t.Rc=function(a){a=void 0===a?Date.now():a;this.ma=0;if(this.aa){var b=Date.now();if(this.oa){var c=b-this.ra-this.ta;c>this.ta&&(this.ea+=c,this.ja(524288,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.ra=b;this.ea||(this.ea=b);this.Ba=0;try{this.wa=!1;do Gc(this,Ec(this,Dc(this,Fc(this))));while(this.aa&&!this.wa)}catch(d){D(this,d.message),vc(this)}this.oa=Date.now();this.Ba&&(this.ea+=this.Ba,this.ra+=this.Ba);this.ra+=Cc(this,this.va,this.oa-this.ea,this.oa-this.ra);
this.oa-this.Ua>=this.pb&&this.update();for(b=0;b<this.ya.length;b++)this.ya[b](a);this.ma=this.cb()}};function sc(a,b){if(void 0!==b){if(1>b||!a.ha&&0<a.na&&a.na<.9*a.ia)b=a.Ka;a.ga=b;b=a.Ta*a.ga;a.ia!=b&&(a.ia=b,xc(a,yc(a.ia)))}a.ea=a.oa=0;a.ca=a.va=0;Cc(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.gb&&Kb(a,b,c.gb,!0)}}function rc(a){var b=a.ka[Bc];return b?(sc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.bb-a.Pa)+a.Pa)/a.Qa|0),!0):!1}
function Kb(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.Da)&&(c=Math.ceil(a.Qa*(a.Bc?a.Ka:a.La)/1E3*(void 0===c?1E3:c)),a.aa&&(c+=Ec(a)),b.Da=c)}t.start=function(){if(this.aa||this.da)return!1;this.aa=!0;this.ea=this.oa=0;this.update(!0);this.ma=this.cb();return!0};function Ac(a,b){b=void 0===b?1:b;a.aa||(b&&!a.da&&(a.da=b),a.da&&(a.da--,Gc(a,Ec(a,Dc(a,Fc(a,1)))),a.update(!1),a.da&&setTimeout(function(){Ac(a,0)},0)))}
function vc(a){a.aa?(a.aa=!1,Ec(a),a.ma&&(a.ob(a.ma),a.ma=0),a.update(!0)):a.da&&(a.da=0,a.update(!0))}t.update=function(a){a&&D(this,this.aa?"started with "+yc(this.ia)+" target":"stopped");$a(this,tc,this.aa?"Halt":"Run");$a(this,zc,this.da?"Stop":"Step");this.ha||(this.ja(4096,"getSpeedCurrent(%5.3fhz)\n",1E6*this.na),xc(this,this.aa&&this.na?yc(this.na):"Stopped"));for(a=0;a<this.Aa.length;a++){var b=this.Aa[a];b.Oc.call(b)}this.Ua=Date.now();this.wa=!0};
function xc(a,b){$a(a,Hc,b);$a(a,wc,b)}var tc="run",wc="setSpeed",Hc="speed",zc="step",Bc="throttle";z.Time=qc;function Ic(a,b,c){c["class"]="CPU";M.call(this,a,b,c)}x(Ic,M);
function Jc(a,b,c){Ic.call(this,a,b,c);this.ia=G(this,"wrap",!1);this.ra=(this.ua=G(this,"font",""))&&Kc[this.ua]||Kc.Helvetica;this.sa=G(this,"rule","");this.na=G(this,"pattern","");Lc(this,this.va=G(this,"message",""));this.Ba=G(this,"toggleColor",!1);this.Aa=Array(Mc(this).length);if(c=P(this,"LED",!1)){this.aa=c;Nc(this)||wb(c,!0);this.oa=P(this,"Input",!1);var d=this;this.wa=new xb(a,b+"Input",{"class":"Input",location:[0,0,c.Aa,c.ya,c.da,c.wa],drag:!(!this.oa||!this.oa.va),scroll:!(!this.oa||
!this.oa.ma),hexagonal:c.Pa,bindings:{surface:Ka(c,Tb)}});Bb(this.wa,function(e,f){var g=d.aa;0<=e&&0<=f&&(d.ha?lc(g,e,f,d.ha)?nc(g,e,f,1):d.Ba?lc(g,e,f):nc(g,e,f,1-ic(g,e,f)):nc(g,e,f,1-ic(g,e,f)),mc(g,e,f,Mc(d,!!ic(g,e,f))),U(g))});this.ga=[];this.ya=c.fa;Oc(this,this.ya);Pc(this);Qc(this,this.la[Rc]);this.time=P(this,"Time");this.time.sa.push(this);this.time.Aa.push(this);this.Qc=0;Ga(this,this.Nc.bind(this))}}x(Jc,Ic);t=Jc.prototype;
t.Na=function(a,b){var c=this,d;switch(a){case Sc:case Tc:b.onchange=function(){Uc(c,a)};Uc(this);break;case Rc:b.onchange=function(){Qc(c)};break;case Vc:Fa(b,Wc(this.la[Vc]),!1,this.la.pattern);b.onchange=function(){var e=c.ka[Vc];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Nc(c,e):c.Ha())};break;case Xc:b.onclick=function(){var e=Yc(c,!0),f=c.ka[Zc];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');D(c,e)};break;case $c:b.onclick=function(){var e=Yc(c);D(c,e);var f=window.location.href;
f=0<=f.indexOf("pattern=")?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((0>f.indexOf("?")?"?":"&")+"pattern="+e);window.location=f};break;case Zc:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.ka[ad];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(bd)?b.onclick=function(){Pc(c,a)}:(d=this.la[Vc])&&d[a]&&(b.onclick=function(){Nc(c,a)})}Ic.prototype.Na.call(this,a,b)};
function Wc(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
t.Sc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.sa){case cd:var d=0;for(var e=this.aa,f=e.da,g=e.ea,h=this.Aa,n=0;n<g;n++)for(var k=0;k<f;k++){var m=h,l=!1,r=4*(n*e.ca+k);if(r<=e.aa.length-4&&e.aa[r+1]){l=!0;r=e.aa[r+2];for(var p=m.length-1;0<=p;p--)m[p]=r&15,r>>>=4}if(l){d++;if(h[0])h[0]--;else{l=(m=ic(e,k,n))||0;switch(m){case 1:if(l=Z,h[0]=h[2],h[0]){h[0]--;break}case Z:if(h[3]&&(l=this.ga.indexOf(e.aa[4*(n*e.ca+k)+1]||e.ga),0<=l)){for(l+=h[3];l>=this.ga.length;)l-=this.ga.length;
lc(e,k,n,this.ga[l])}l=1;h[0]=h[1];h[0]&&h[0]--}l!==m&&nc(e,k,n,l)}mc(e,k,n,h)}}break;case dd:c=a||c;d=c;d=void 0===d?1:d;e=0;f=this.aa;g=f.ca;h=f.ea;if(f.oa||!ed(this,d))d=0;else{n=f.aa;r=4*d;k=4*g;l=p=m=0;for(this.ma=this.ta=-1;m<g-d;){for(var q=1,w=l,v=0;v<h;v++){var u=n[l],B=n[l]=n[l+r];u=B!==u?Y:0;n[l+1]=n[l+r+1];n[l+2]=n[l+r+2];n[l+3]=n[l+r+3]|u;B&&(e++,q=0);l+=k}l=w+4;m++<f.da&&(q?p++:(0>this.ma&&(this.ma=p),p=0))}0>this.ma&&(this.ma=p);for(this.ta=p;m<g;){r=l;for(p=0;p<h;p++)kc(f,n,l),l+=
k;l=r+4;m++}f.ia=!0;f.oa=d;d=e}break;case fd:d=0;e=this.aa;f=e.aa;g=e;g.ra||(g.ra=Array(g.Ta),ac(g,g.ra));g=g.ra;h=e.da;n=e.ea;k=4*h+e.Ua;m=n*k;l=0;r=l-k;p=r-4;q=r+4;w=l-4;v=l+4;B=l+k;u=B-4;for(var F=B+4,J=0;J<n;J++){J?J==n-1&&(this.ia?(B-=m,u-=m,F-=m):B=u=F=m):this.ia?(r+=m,p+=m,q+=m):r=p=q=m;for(var S=0;S<h;S++){S?1==S?this.ia?(w-=k,p-=k,u-=k):(w=l-4,p=r-4,u=B-4):S==h-1&&(this.ia?(v-=k,q-=k,F-=k):v=q=F=m):this.ia?(w+=k,p+=k,u+=k):w=p=u=m;var T=f[l],N=f[p]+f[r]+f[q]+f[v]+f[F]+f[B]+f[u]+f[w];3==N?
T=1:2!=N&&(T=Z);g[l]=T;g[l+1]=f[l+1];g[l+2]=f[l+2];g[l+3]=f[l+3]|(f[l]!==T?Y:0);l+=4;p+=4;r+=4;q+=4;v+=4;F+=4;B+=4;u+=4;w+=4;1==T&&d++}this.ia?(J||(r-=m,p-=m,q-=m),v+=k,q+=k,F+=k):(J||(r=l-k,p=r-4),v=l+4,q=r+4,F=B+4)}f=e.aa;e.aa=e.ra;e.ra=f;e.ia=!0}a||D(this,"active cells: "+d);b+=c}while(b<a)}return b};function gd(a,b){var c=0;(a=a.ka[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Mc(a,b){var c=0;if(b&&(b=a.ka[hd])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=gd(a,id)+gd(a,jd),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<kd.length;b++)c.push(gd(a,kd[b]));return c}
function Nc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.na.match(/^[0-9]/)||(b=a.na);if(b){var g=a.la[Vc];g=g&&g[b];if(!g)return D(a,"unknown pattern: "+b),!1;D(a,"loading pattern '"+b+"'");for(var h=b=0;b<g.length;b++){var n=g[b];if("#"==n[0])D(a,n);else if(h++){var k=n.indexOf("!");if(0<=k){f+=n.substr(0,k);break}f+=n}else{var m=n.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!m)return D(a,"unrecognized header line"),!1;var l=+m[1];var r=+m[2];m=m[3]}}}else{if(!a.na)return!1;
f=0;m=a.na.split("/");5==m.length&&(d=+m[f++],e=+m[f++]);if(3==m.length||5==m.length)l=+m[f++],r=+m[f++],f=m[f];else return D(a,"unrecognized pattern: "+a.na),!1;m=a.sa}if(m!=a.sa)return D(a,"unsupported rule: "+m),!1;0>d&&(d=c.ca-l>>1);0>e&&(e=c.ea-r>>1);return 0>d||d+l>c.ca||0>e||e+r>c.ea?(a.ja("pattern too large (%d,%d)\n",l,r),!1):0<ld(a,d,e,f)}
function ld(a,b,c,d,e){e=void 0===e?!1:e;var f=a.aa,g=[0,0,0,1],h=0,n=!1,k=!1;d=d.split(/([a-z$])/i);e||wb(f);for(var m=0,l=b,r=0;m<d.length-1;){var p=d[m++],q=d[m++],w=+p;for(p=""===p?1:w;p--;){var v=0,u=!1;switch(q){case "$":n=k=!1;b=l;c++;break;case "C":h=w;k=!0;break;case "R":g[0]=w;n=!0;break;case "G":g[1]=w;n=!0;break;case "B":g[2]=w;n=!0;break;case "A":g[3]=w;n=!0;break;case "b":u=nc(f,b,c,Z);v++;break;case "o":u=nc(f,b,c,1);v++;break;default:a.ja("unrecognized pattern token: %s\n",q)}if(null==
u)a.ja("invalid pattern position (%d,%d)\n",b,c);else{if(n){u=f;var B=g;u=4>B.length||1==B[3]?u.za("#%02x%02x%02x",B[0],B[1],B[2]):u.za("rgba(%d,%d,%d,%d)",B[0],B[1],B[2],B[3]);lc(f,b,c,u)}k&&(u=4*(c*f.ca+b),u<=f.aa.length-4&&f.aa[u+2]!=h&&(f.aa[u+2]=h));r<b&&(r=b);b+=v}}}e||U(f,!0);return 0>(r-=l-1)?0:r}
t.Ga=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return D(this,"Invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.ja("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.da=b.shift(),this.ea=b.shift(),this.ba=b.shift()}catch(d){return D(this,"CPU state error: "+d.message),!1}return Pa().message||Pa().pattern||Pa()[Rc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Ga(a)?!0:!1};
t.Nc=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Lc(this,a.join(" "));break;case "?":b="";md.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};t.ub=function(a){return a&&this.Ga(a)?!0:!1};t.Fa=function(a){a?this.time.start():vc(this.time)};t.Ha=function(){D(this,"reset");wb(this.aa,!0);gc(this.aa,!0);this.va&&Lc(this,this.va)};t.vb=function(a){this.Ia(a)};t.Oc=function(){this.time.aa||U(this.aa)};
function ed(a,b,c,d){b=void 0===b?1:b;c&&(a.ea=c,a.ba=d);switch(a.ea){case nd:return!1;case od:case pd:if(0<a.ba)return a.ba-=b,!0;break;case qd:if(0<a.ba)return a.ba-=b,!1;break;case rd:if(a.ma>a.ta)return!0;break;case sd:gc(a.aa,!1);a.ea=qd;break;case td:gc(a.aa,!0);a.ea=qd;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.da>=a.ca.length&&(a.da=0);c=a.ca[a.da++];if("$"==c){d=0;for(var e=a.da;e<a.ca.length;){var f=a.ca.charCodeAt(e)-48;if(0>f||9<f)break;d=10*d+f;e++}if(e<a.ca.length)if(f=
a.ca[e++],"$"==f)a.da=e;else{var g=ud[f];if(g){a.da=e;a=ed(a,b,g,d);break a}D(a,"unrecognized message code: $"+f)}}" "==c?a.ba+=2:(d=a.aa.da+1,e=0>a.ba?a.ba:0,c=a.ra[c]||a.ra[c.toUpperCase()],f=Math.round((a.aa.wa-a.ra.height)/2),c&&(a.ba+=ld(a,d+e,0>f?0:f,c,!0)),a.ba+=2-b);a.ea=pd;a=!0}else a.ea=nd,a=!1;return a}
function Yc(a,b){function c(T){var N=!1;null==m[3]&&(m[3]=1);if(v){if(n){if(m[0]!==q[0]||m[1]!==q[1]||m[2]!==q[2]||m[3]!==q[3])N=!0;S!==w&&(N=!0)}k!==p&&(N=!0);if(N||T&&p)n&&(l[0]!==q[0]&&(l[0]=q[0],e+=(q[0]||"")+"R"),l[1]!==q[1]&&(l[1]=q[1],e+=(q[1]||"")+"G"),l[2]!==q[2]&&(l[2]=q[2],e+=(q[2]||"")+"B"),l[3]!==q[3]&&(l[3]=q[3],e+=(q[3]||"")+"A"),r!==w&&(r=w,e+=(w||"")+"C")),1<v&&(e+=v),e+=1===p?"o":"b",N=!0}T?(e+="$",v=0):(N?v=1:v++,p=k,q[0]=m[0],q[1]=m[1],q[2]=m[2],q[3]=m[3],w=S)}var d=a.aa,e="",
f=0,g=a.aa.ca,h=a.aa.ea,n=!!a.ga.length,k,m=[0,0,0],l=[0,0,0,1],r=0,p=0,q=[0,0,0,1],w=0,v=0;a=0;var u=d.ca-1,B=d.ea-1;if(b){b&&(a=u,u=0);for(g=0;g<d.ea;g++)for(h=0;h<d.ca;h++)(k=ic(d,h,g))&&b&&(a>h&&(a=h),u<h&&(u=h));g=u-a+1;h=B+1;0>g&&(g=0);0>h&&(h=0)}for(var F=0;F<=B;F++){for(var J=a;J<=u;J++){k=ic(d,J,F);jc(d.aa[4*(F*d.ca+J)+1]||d.ga,m);var S=hc(d,J,F);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,h--,e=e.slice(1);for(;"$$"==e.slice(-2);)h--,e=e.slice(0,-1);"$"==e&&(h=0);e=(b?"":"0/"+f+"/")+g+"/"+h+"/"+
e.slice(0,-1);return e=e.replace(/\$+$/,"")}t.Ia=function(a){var b=[],c=[];b.push(2);b.push(this.ca);b.push(this.da);b.push(this.ea);b.push(this.ba);this.aa&&this.aa.Ia(c);a.push(b);a.push(c)};function Lc(a,b){a.ca!=b&&(b&&D(a,"new message: '"+b+"'"),a.ca=b);a.ea=od;a.da=a.ba=0}t.toString=function(){return""};
function Qc(a,b){var c=a.ka[Rc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Qa&&(a.Qa.style.backgroundImage=b?"url('"+b+"')":"none")}}
function Uc(a,b){var c=a.ka[Sc],d=a.ka[Tc];b=b===Sc;c&&!c.options.length&&(Fa(c,a.la.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.fa=a.la.colors[c.options[c.selectedIndex].value];for(var e in a.fa)if(b=a.la[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),D(a,"overriding color '"+e+"' with "+b+" (formerly "+a.fa[e]+")"),a.fa[e]=b;Fa(d,a.fa,!0)}c&&d&&d.options.length&&(a.ha=d.options[d.selectedIndex].value,Pc(a))}
function Oc(a,b){var c=a.ka[Tc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ha=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Pc(a,b){var c=1,d;!b&&a.ha&&(d=a.ka[vd])&&(d.style.backgroundColor=a.ha);if(a.fa)for(var e in a.fa){var f=a.fa[e];a.ga&&(a.ga[c-1]=f);var g=bd+c++;d=a.ka[g];if(!d)break;d.style.display="inline-block";g==b&&Oc(a,f);if(b&&b!=g||f!=a.ha)f=Yb(f,1,.5);d.style.backgroundColor=f}for(;;){b=bd+c++;b=a.ka[b];if(!b)break;b.style.display="none"}}
var Sc="colorPalette",Tc="colorSelection",bd="colorSwatch",vd="colorSwatchSelected",hd="countInit",id="countOn",jd="countOff",Rc="backgroundImage",Vc="patterns",Zc="symbolInput",ad="symbolPreview",Xc="save",$c="saveToURL",kd=[null,id,jd,"countCycle"],md=["s\t\tset string"],od="load",pd="scroll",qd="pause",nd="halt",rd="center",sd="off",td="on",ud={b:sd,c:rd,h:nd,o:td,p:qd,s:pd},cd="A4",dd="L1",fd="B3/S23",Kc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};z.CPULEDS=Jc;
function wd(a,b,c){M.call(this,a,a);var d=this;this.ca=this.aa=!1;this.ha=c;this.ba="";this.ga=this.fa=!1;this.Ca=0;b=b.trim();"{"==b[0]?xd(this,b):(this.ba=b,Oa(this.ba,function(e,f,g,h){4==g&&(!h&&f?(xd(d,f),yd(d)):d.ja("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.ga=!0;yd(d)});window.addEventListener(Sa("iOS")?"pagehide":Sa("Opera")?"unload":"beforeunload",function(){zd(d)});window.addEventListener("pageshow",function(){d.aa&&!d.ca&&d.Fa(!0)})}
x(wd,M);wd.prototype.Na=function(a,b){var c=this;switch(a){case Ad:b.onclick=function(){c.aa&&c.Fa()};break;case Bd:b.onclick=function(){c.aa&&c.Ha()}}M.prototype.Na.call(this,a,b)};
function yd(a){var b=!0;if(a.fa&&a.ga){for(var c in a.da){var d=void 0,e=a.da[c];try{d=e["class"],z[d]?"Machine"==d?(a.ja("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,Cd,Dd),a.ba&&a.ja("Configuration: %s\n",a.ba)):new z[d](a.pa,c,e):a.ja("unrecognized %s device class: %s\n",c,d)}catch(g){e.optional||(a.ja("error initializing %s device '%s': %s\n",d,c,g.message),b=!1),mb(a,c)}}if(a.ea){var f=Ta(a);kb(a,function(g){return g.ub&&!g.ub(f)?(g.ja("unable to restore state for device: %s\n",g.xa),!1):!0})}a.Fa(b)}}
function xd(a,b){try{a.da=JSON.parse(b);jb(a,a.da[a.pa],["autoSave","autoStart"]);a.ea=!1!==a.la.autoSave;a.ia=!1!==a.la.autoStart;if(a.ha){var c=eval("("+a.ha+")"),d;for(d in c)a.la[d]=c[d]}a.fa=!0}catch(e){c=e.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),D(a,"machine '"+a.pa+"' initialization error: "+c)}}
wd.prototype.Fa=function(a){a=void 0===a?!this.ca:a;var b=this;a&&D(this,"power on");kb(this,function(c){c.Fa&&c!=b&&("CPU"!=c.la["class"]||b.ia||b.aa?c.Fa(a):c.time.update(!0));return!0});this.aa=!0;(this.ca=a)||D(this,"power off")};wd.prototype.Ha=function(){var a=this;kb(this,function(b){b.Ha&&b!=a&&b.Ha();return!0})};function zd(a){if(a.ea){var b=[];kb(a,function(c){c.vb&&c.vb(b);return!0});Za(a,b)}a.Fa(!1)}
var Ad="power",Bd="reset",Cd="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",Dd="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";window.LEDs=function(a,b,c){var d=new wd(a,b,c);window.command=function(e){return Ua(d,e)};return d};z.Machine=wd;})()

//# sourceMappingURL=leds.js.map
