(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu/cpu.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu/ledctrl.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/machine.js (C) Jeff Parsons 2012-2019
*/
var u;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={ub:!0},ha={};try{ha.__proto__=fa;ea=ha.ub;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function x(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Fe=b.prototype}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},y="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function z(a,b){if(b){var c=y;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}z("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});z("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
function ka(){ka=function(){};y.Symbol||(y.Symbol=la)}function ma(a,b){this.aa=a;ja(this,"description",{configurable:!0,writable:!0,value:b})}ma.prototype.toString=function(){return this.aa};var la=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ma("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function na(){ka();var a=y.Symbol.iterator;a||(a=y.Symbol.iterator=y.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}});na=function(){}}function oa(a){na();a={next:a};a[y.Symbol.iterator]=function(){return this};return a}
function pa(a,b){na();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}z("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});z("Number.parseInt",function(a){return a||parseInt});z("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});
z("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});
z("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var f=0;f<e&&c<d;)if(this[c++]!=b[f++])return!1;return f>=e}});var qa=new ArrayBuffer(2);
(new DataView(qa)).setUint16(0,256,!0);new Uint16Array(qa);function ra(){}var A={};A.Defs=ra;function sa(){}x(sa,ra);function ta(a,b){var c=a/B|0,d=b/B|0;return(a&b)==(b|0)&&(c&d)==d}function ua(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var B=Math.pow(2,32);A.NumIO=sa;function D(){this.bb={};for(var a=0;22>a;a++)this.bb["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}x(D,sa);u=D.prototype;
u.flush=function(){var a=va;va="";this.Va(a)};u.Vc=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};u.Va=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),wa||(wa=b),a=((b-wa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(va+a.substr(0,c)),va="",a=a.substr(c+1)),wa=null);va+=a;return a.length};
function E(a,b,c){a.Va(b+"\n",c)}u.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.Va(this.za.apply(this,[a].concat(ba(c))))};
u.za=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var l=e[g+5];if(void 0===this.bb[l])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+l;else{if(f<c.length){var h=c[f];"%"!=l&&f++}else h=c[c.length-1];var r=e[g+1],k=0<=r.indexOf("#"),m=0<=r.indexOf("0"),n=e[g+2];"*"==n?(n=h,h=f<c.length?c[f++]:c[c.length-1]):n=+n||0;var q=e[g+3];q=q?+q.substr(1):
-1;var t=null,w=0,v="";var p=0<="ACDFHIMNSTWY".indexOf(l)&&"object"!=typeof h?this.Vc(h):h;switch(l){case "C":h=k?"#":"";d+=isNaN(p.getTime())?void 0:this.za(this.za("%%%sW, %%%sF %%%sD, %%%sY",h),p);continue;case "D":h=k?p.getUTCDate():p.getDate();l="d";break;case "A":case "H":case "I":h=k?p.getUTCHours():p.getHours();"A"==l?(h=12>h?"am":"pm",l="s"):("I"==l&&(h=h?12<h?h-12:h:12),l="d");break;case "F":case "M":h=k?p.getUTCMonth():p.getMonth();"F"==l?(h=xa[h],l="s"):(h++,l="d");break;case "N":h=k?
p.getUTCMinutes():p.getMinutes();l="d";break;case "S":h=k?p.getUTCSeconds():p.getSeconds();l="d";break;case "T":h=k?"#":"";d+=isNaN(p.getTime())?void 0:this.za(this.za("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),p);continue;case "W":h=ya[k?p.getUTCDay():p.getDay()];l="s";break;case "Y":h=k?p.getUTCFullYear():p.getFullYear(),0<q&&(h%=Math.pow(10,q),q=-1),l="d"}switch(l){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(m=!0,n<q&&(n=q),q=-1);case "f":h=+h;p=h+"";0<=q&&(p=h.toFixed(q));
p.length<n&&(m?(0>h&&(n--,p=p.substr(1)),p=("0000000000"+p).slice(-n),0>h&&(p="-"+p)):p=("          "+p).slice(-n));d+=p;break;case "j":d+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<n;)h=0<=r.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":w=8,k&&(v="0");case "X":t=za;case "x":p="";w||(w=16);!v&&k&&(v="0x");t||(t=Aa);h=Math.trunc(h);0<=q&&(m=!0,n<q&&(n=
q));m&&!n&&(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9,n+=v.length);n-=v.length;do k=h&w-1,h>>>=16==w?4:3,m||!p||k||h?p=t[k]+p:(v&&(p=v+p,v=""),0<n&&(p=" "+p));while(0<--n||h);d+=v+p;break;case "%":d+="%";break;default:this.bb[l]?d+=this.bb[l](l,r,n,q,h):d+="(unimplemented sprintf type: %"+l+")"}}}return d+=e[g]};var va="",wa=null,Aa="0123456789abcdef",za="0123456789ABCDEF",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" ");
A.StdIO=D;function G(a){D.call(this);this.la={};this.Ca=0;this.na=this;a&&(this.na.Ca=0,this.na.La=[],this.na.Ea=0,this.na.cb={},this.na.pe=!1)}var Ba;x(G,D);G.prototype.Na=function(a,b){var c=this,d=this;switch(a){case Ca.kc:b.onclick=function(){var e=c.$a(Ca.pb,!0);e&&(e.value="")};break;case Ca.pb:Da(b),b.addEventListener("keydown",function(e){Ea(d,e,!0)}),b.addEventListener("keypress",function(e){Ea(d,e)})}};
function Fa(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function Ga(a,b){var c=Ha.Cb;a.na.cb[c]||(a.na.cb[c]=[]);a.na.cb[c].push(b)}function Da(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}G.prototype.$a=function(a){return this.la[a]};
function Ia(a){var b=window;if(b){do{for(var c=0;c<Ja.length;c++){var d=Ja[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ka(a,b){return a.ja.bindings&&a.ja.bindings[b]}function La(a){if(a=a.la[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function H(a,b,c,d){a=a.ja[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Pa(){var a,b=Ba;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ba=b}return b}function Qa(a){if(void 0===I.nb){var b=!1;if(window)try{window.localStorage.setItem(I.Wa,I.Wa),b=window.localStorage.getItem(I.Wa)==I.Wa,window.localStorage.removeItem(I.Wa)}catch(c){E(a,c.message),b=!1}I.nb=b}return!!I.nb}
function Ra(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.Ca;return-1==(b|1)||ta(a.na.Ca,b)?!0:!1}function Sa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ta(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.qa))&&(b=JSON.parse(c))}catch(d){E(a,d.message)}}return b}
function Ea(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.na,f=b.target;if(c){a=!1;var g;c=f.value;var l=c.lastIndexOf("\n");d==K.zb&&f.selectionStart<=l+1&&(a=!0);d==K.Jc?(a=!0,0<e.Ea&&(g=e.La[--e.Ea])):d==K.nc&&(a=!0,e.Ea<e.La.length&&(g=e.La[++e.Ea]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,l+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Ea&&c+1==
g.length&&(f.value+=e.La[--e.Ea],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ua(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&E(a,b.replace(/\n$/,""),!1))}}
function Va(a,b){if(void 0!=b){var c=a.na;try{if(b=b.trim())c.Ea<c.La.length&&b==c.La[c.Ea]?c.Ea++:(c.La.push(b),c.Ea=c.La.length);var d=b.split(" "),e=d[0],f=a.na.cb[Ha.Cb];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(m){g+=m+"\n"});g&&(g="message commands:\n"+g);break}g="";var l=void 0;e=d[d.length-1].toLowerCase();var h="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(l=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(L));
for(f=1;f<d.length;f++){e=d[f];var r=L[e];if(!r){g+="unrecognized message: "+e+"\n";break}void 0!=h&&Xa(a,r,h);if(void 0==l||l==Ra(a,r))g+=a.za("%8s: %b\n",e,Ra(a,r))}Ra(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(m){g+=m+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var k=f[a](d);if(void 0!=k){g=g?g+k:k;break}}}}catch(m){g="error: "+m.message+"\n"}}return g}
function Ua(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Va(a,b[d])}return c}G.prototype.Va=function(a,b){void 0==b&&(b=Ra(this,0x800000000000));if(!b){var c=this.$a(Ca.pb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Sa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return D.prototype.Va.call(this,a,b)};
G.prototype.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return Ra(this,d)?D.prototype.ka.call.apply(D.prototype.ka,[this,a].concat(ba(c))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.qa,b)}catch(c){E(a,c.message)}}}function $a(a,b,c){(a=a.la[b])&&a.textContent!=c&&(a.textContent=c)}
function Xa(a,b,c){var d=!1;c?(c=a.na.Ca,a.na.Ca=(c|b)+(c/B|0|b/B|0)*B):(d=ta(a.na.Ca,0x800000000000)&&ta(b,0x800000000000),c=a.na.Ca,a.na.Ca=(c&~b)+((c/B|0)&~(b/B|0))*B);d&&a.flush()}
var Ca={kc:"clear",pb:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],L={all:0xffffffffffff,buffer:0x800000000000},Ha={Cb:"command"},ab={Db:13,mb:65,yb:66,Ab:67,Eb:68,E:69,Fb:70,Gb:71,Hb:72,Ib:73,Jb:74,Kb:75,Lb:76,Nb:77,Ob:78,Qb:79,Rb:80,Q:81,
Sb:82,Ub:83,Vb:84,Wb:85,Xb:86,Yb:87,Zb:88,$b:89,tb:90,ub:97,qe:98,re:99,d:100,e:101,ve:102,we:103,ye:104,ze:105,Ae:106,k:107,Be:108,Ce:109,n:110,De:111,p:112,q:113,r:114,Ee:115,t:116,Ge:117,He:118,Ie:119,x:120,y:121,z:122},K={zb:8,Gc:9,wc:10,Db:13,Dc:16,lc:17,jc:18,de:19,ob:20,ed:27,Fc:32,ge:33,fe:34,dd:35,Ad:36,Mb:37,Jc:38,qb:39,xd:39,nc:40,ud:44,he:44,Bd:45,cd:46,wd:46,zd:47,ZERO:48,ONE:49,Ic:50,Hc:51,vc:52,uc:53,Ec:54,Cc:55,oc:56,xc:57,tc:59,sc:61,mb:65,yb:66,Ab:67,Eb:68,E:69,Fb:70,Gb:71,Hb:72,
Ib:73,Jb:74,Kb:75,Lb:76,Nb:77,Ob:78,Qb:79,Rb:80,Q:81,Sb:82,Ub:83,Vb:84,Wb:85,Xb:86,Yb:87,Zb:88,$b:89,tb:90,Bb:91,vd:91,td:92,ke:93,yd:93,Fd:96,Wd:96,sd:96,Gd:97,Ud:97,Hd:98,Td:98,Id:99,Zd:99,Jd:100,Xd:100,Kd:101,Qd:101,Ld:102,ae:102,Md:103,Vd:103,Nd:104,ce:104,Od:105,$d:105,Yd:106,Pd:107,be:109,Rd:110,Sd:111,fd:112,kd:113,ld:114,md:115,nd:116,od:117,pd:118,qd:119,rd:120,gd:121,hd:122,jd:123,yc:144,Ac:145,rc:173,Bc:186,pc:187,bd:188,mc:189,ee:190,me:191,$c:192,Cd:219,ad:220,je:221,ie:222,qc:224,Dd:901,
ne:1E3},bb={},cb=(bb[K.tc]=K.Bc,bb[K.sc]=K.pc,bb[K.rc]=K.mc,bb[K.qc]=K.Bb,bb),db={Mb:1,qb:2,Ed:3},M={},eb=(M[K.zb]="\b",M[K.Gc]="\t",M[K.wc]="\n",M[K.Db]="\r",M[K.Fc]=" ",M[K.ZERO]="0",M[K.ONE]="1",M[K.Ic]="2",M[K.Hc]="3",M[K.vc]="4",M[K.uc]="5",M[K.Ec]="6",M[K.Cc]="7",M[K.oc]="8",M[K.xc]="9",M[K.mb]="A",M[K.yb]="B",M[K.Ab]="C",M[K.Eb]="D",M[K.E]="E",M[K.Fb]="F",M[K.Gb]="G",M[K.Hb]="H",M[K.Ib]="I",M[K.Jb]="J",M[K.Kb]="K",M[K.Lb]="L",M[K.Nb]="M",M[K.Ob]="N",M[K.Qb]="O",M[K.Rb]="P",M[K.Q]="Q",M[K.Sb]=
"R",M[K.Ub]="S",M[K.Vb]="T",M[K.Wb]="U",M[K.Xb]="V",M[K.Yb]="W",M[K.Zb]="X",M[K.$b]="Y",M[K.tb]="Z",M[K.Mb]="Left",M[K.qb]="Right",M),fb={list:[],Mc:"version"},Ja=["","moz","ms","webkit"],gb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",
cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",
dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",
lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",
midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",
royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},I={nb:void 0,Wa:"PCjs.localStorage"};
A.WebIO=G;function O(a,b,c,d){G.call(this,a==b);this.qa=a;this.xa=b;P[this.qa]||(P[this.qa]={});P[this.qa][this.xa]&&this.ka("warning: machine configuration contains multiple '%s' devices\n",this.xa);P[this.qa][this.xa]=this;this.id=this.qa+"."+this.xa;hb.push(this);this.na=ib(this,this.qa);this.ab=!0;jb(this,c,d);this.Pb=[]}x(O,G);
function jb(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d=Pa();for(l in d)if(0<=c.indexOf(l)){var e=d[l];if(e.match(/^[+-]?[0-9.]+$/))var f=Number.parseInt(e,10);else"true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"');b[l]=f;E(a,"overriding "+a.xa+" property '"+l+"' with "+e)}}a.ja=b;c=b.bindings;c=void 0===c?{}:c;a.ja.la||(a.ja.la=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.xa);for(var g in c){f=c[g];if(d)g=f;else if(f.match(/^[0-9]+$/)){var l=
+f;a.la[g]=[];do{f=g+l++;f=document.getElementById(f);if(!f)break;a.la[g].push(f)}while(1);continue}if(l=document.getElementById(f))a.la[g]=l,a.Na(g,l)}b=void 0===b?{}:b;a.version=2;if(a.version){g="";var h;a.qa!=a.xa&&(h=ib(a,a.qa).version)&&h!=a.version&&(g="Machine");g||(h=b.version)&&h>a.version&&(g="Config");g&&(h="Error: "+a.za("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.se,a.version,g,h)+"\n\nClearing your browser's cache may resolve the issue.",(b=fb.Mc)&&0>fb.list.indexOf(b)&&
(alert(h),fb.list.push(b)),E(a,h))}}function kb(a,b){var c;try{var d=P[a.qa];if(d)for(c in d){var e=d[c];if("Machine"!=e.ja["class"]&&!b(e))return!1}return!0}catch(f){a.ka("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.$a=function(a,b){b=void 0===b?!1:b;if(a){var c=G.prototype.$a.call(this,a,b);if(void 0===c&&b){b=P[this.qa];for(var d in b)if(c=b[d].la[a])break;c||(c=null);this.la[a]=c}}return c};
function ib(a,b){var c=b,d=a.qa,e=d.indexOf(".");0<e&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=P[d])&&e[b]||null;if(!b){for(e=0;e<hb.length;e++)if(hb[e].id===c){b=hb[e];break}if(!b)throw Error(a.za("unable to find device with ID '%s'",c));}return b}function Q(a,b,c){var d=null,e=P[a.qa];if(e)for(var f in e)if(e[f].ja["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.za("unable to find device with class '%s'",b));return d}
function lb(a){return a==a.na&&a.ab?kb(a,function(b){return lb(b)}):a.ab}function mb(a,b){b=void 0===b?a.ab:b;a.ab=b;if(lb(a)){for(;b=a.Pb.shift();)b();a!=a.na&&mb(a.na)}}function nb(a,b){lb(a)?b():a.Pb.push(b)}
O.prototype.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&Ra(this,a)&&(void 0===this.Pa&&(this.Pa=Q(this,"Debugger",!1)),this.na.Ca&ob&&(void 0===this.Oa&&(this.Oa=Q(this,"CPU")),this.Oa))?(a=c.shift(),G.prototype.ka.call(this,"%#06x: %s.%s\n",this.Oa.Wc,this.xa,this.za.apply(this,[a].concat(ba(c))).trim())):G.prototype.ka.call.apply(G.prototype.ka,[this,a].concat(ba(c)))};function pb(a,b){(a=P[a.qa])&&delete a[b]}var P={},hb=[],ob=1;
L.addr=ob;L.bus=2;L.memory=4;L.ports=8;L.chips=16;L.kbd=32;L.serial=64;L.misc=128;L.cpu=256;L["int"]=512;L.trap=1024;L.video=2048;L.monitor=4096;L.screen=8192;L.time=16384;L.timer=32768;L.event=65536;L.input=131072;L.key=262144;L.mouse=524288;L.touch=1048576;L.warn=2097152;L.halt=4194304;window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines=P),window.PCjs.Components||(window.PCjs.Components=hb));A.Device=O;
function qb(a,b,c){O.call(this,a,b,c);this.type="static"==c.type?rb:sb;this.da=c.addrWidth||16;this.ca=Math.pow(2,this.da);this.aa=c.blockSize||(16<this.da?4096:1024);this.aa>this.ca&&(this.aa=this.ca);this.ha=this.ca/this.aa|0;this.ea=Math.log2(this.aa)|0;this.ga=(1<<this.ea)-1;this.fa=c.dataWidth||8;this.ba=Array(this.ha);a=new R(a,b+"[NONE]",{size:this.aa,bus:this.xa});for(b=0;b<this.ca;b+=this.aa)tb(this,b,this.aa,S.NONE,a)}x(qb,O);
function tb(a,b,c,d,e){for(var f=b>>>a.ea;0<c&&f<a.ba.length;){var g=f*a.aa,l=a.aa-(b-g);l>c&&(l=c);var h=a.ba[f];if(b!=g||l!=a.aa||h&&h.type!=S.NONE)break;var r=h=void 0,k=b,m=a.da,n=16;m=void 0===m?0:m;h=void 0===h?0:h;var q="",t="",w=-1;n||(n=a.ia||10);m&&(w=Math.ceil(m/Math.log2(n)));if(void 0==r)switch(n){case 8:r="0o";break;case 16:r="0x";break;case 10:t=".";default:r=""}isNaN(k)||"number"!=typeof k?(k=void 0,r=t=""):(0>k&&-1<k&&(k=-1),m&&(0>k&&(k+=Math.pow(2,m)),k>=Math.pow(2,m)&&(w=Math.ceil(Math.log(k)/
Math.log(n)))));for(m=h||-1;w--;){m||(q=","+q,m=h);if(void 0==k){if(q="?"+q,0>w)break}else{var v=k%n;k=Math.trunc(k/n);v+=0<=v&&9>=v?48:55;q=String.fromCharCode(v)+q;if(!k&&0>w)break}m--}h=a.xa+"["+(r+q+t)+"]";b=e?e.size==a.aa?e:new R(a.qa,h,{type:d,vb:b,size:l,bus:a.xa}):new R(a.qa,h,{type:d,vb:b,size:l,bus:a.xa});a.ba[f]=b;b=g+a.aa;c-=l;f++}}u=qb.prototype;u.Ga=function(){};u.wb=function(a){return a&&this.Ja(a)?!0:!1};u.xb=function(a){this.Ka(a)};
u.Ja=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==sb||c.type&S.Tb)&&c.Ja){var d=a.shift();if(!c.Ja(d))return!1}}return!0};u.Ka=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==sb||c.type&S.Tb)&&c.Ka){var d=[];c.Ka(d);a.push(d)}}};var rb=0,sb=1;A.Bus=qb;
function R(a,b,c){O.call(this,a,b,c);this.vb=c.addr;this.size=c.size;this.type=c.type||S.NONE;this.ca=(a=this.ja.bus)?ib(this,a):Q(this,a="Bus");if(!this.ca)throw Error(this.za("unable to find bus '%s'",a));this.ha=this.ca.fa;this.fa=this.ga=!1;this.values=this.ba=null;if(a=this.ca.type==rb)if(a=8==this.ha)a=ib(this,this.qa),a=!1!==(a&&a.ja&&a.ja.ArrayBuffer);a&&(this.ga=!0);ub(this,c.values);vb(this)}x(R,O);
function ub(a,b){"string"==typeof b?(mb(a,!1),Oa(b,function(c,d,e,f){4==e&&(!f&&d?(c=JSON.parse(d),ub(a,c.values),mb(a,!0)):a.ka("error (%d) loading resource: %s\n",f,c))})):a.ja.values=b}function vb(a,b){if(a.type>S.NONE&&(a.ga?(a.ba=new ArrayBuffer(a.size),new DataView(a.ba,0,a.size),a.values=new Uint8Array(a.ba,0,a.size),new Uint16Array(a.ba,0,a.size>>1),new Int32Array(a.ba,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}
R.prototype.Ga=function(){if(this.ja.values)a:{var a=this.ca,b=this.vb,c=this.size,d=this.ja.values,e=0,f=b&a.ga;b>>>=a.ea;c>d.length&&(c=d.length);for(;0<c&&b<a.ba.length;){var g=a.ba[b++];if(!g)break a;for(;0<c&&f<g.size;){var l=f++,h=d[e++];g.values[l]=h;c--}f=0}}else this.values&&this.values.fill(0)};
R.prototype.Ja=function(a){var b=a.shift();if(this.xa==b){this.fa=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}vb(this,a)}return!0}return!1};R.prototype.Ka=function(a){a.push(this.xa);a.push(this.fa);a.push(!1);a.push(this.values?ua(this.values):this.values)};var S={NONE:1,zc:2,Tb:4,le:14,oe:12};A.Memory=R;
function wb(a,b,c){c.type=S.zc;R.call(this,a,b,c);tb(this.ca,c.addr,c.size,c.type,this);nb(this,this.Ga.bind(this));this.Oa=this.Pa=void 0;if(A.LED&&this.la[xb]){var d=this;this.da=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.ea=this.values.length/this.da|0;this.aa=new yb(a,b+"LEDs",{"class":"LED",bindings:{container:Ka(this,xb)},type:zb,cols:this.da,rows:this.ea,color:H(this,"colorROM","green"),backgroundColor:H(this,"backgroundColorROM","black"),persistent:!0}),Ab(this.aa,!0);this.ia=
new Bb(a,b+"Input",{"class":"Input",location:[0,0,this.aa.Aa,this.aa.ya,this.da,this.ea],bindings:{surface:Ka(this,xb)}});this.ma=La(this)||"";Cb(this.ia,function(e,f){if(d.Oa){var g=d.ma;0<=e&&0<=f&&(g="");$a(d,Ma,g)}})}}x(wb,R);
wb.prototype.Ja=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.aa.length==d?(this.aa.aa=c,T(this.aa,!0)):(this.ka("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.ka("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};wb.prototype.Fa=function(){void 0===this.Oa&&(this.Oa=Q(this,"CPU"));void 0===this.Pa&&(this.Pa=Q(this,"Debugger",!1))};
wb.prototype.Ka=function(a){this.aa&&(a.push(this.aa.aa),a.push(this.values))};var xb="array",Ma="cellDesc";A.ROM=wb;
function Bb(a,b,c){O.call(this,a,b,c);this.Ca=131072;this.ia=this.pa=null;this.time=Q(this,"Time");this.na=Q(this,"Machine");this.va=H(this,"drag",!1);this.ma=H(this,"scroll",!1);this.Aa=H(this,"hexagonal",!1);this.ea=H(this,"releaseDelay",0,void 0);this.fa=!1;a=this.ja.map;this.ba=this.ca=null;if(a)if(a.length)this.ba=a;else{this.ca={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.ca[f]=
{keys:g,xe:e,state:0}}}this.ra=[];this.sa=[];this.da=this.ta=null;(a=this.la[Db])&&Eb(this,a,this.$a(c.focusBinding,!0),this.ja.location);this.Ga()}x(Bb,O);function Cb(a,b){a.pa=b}function Fb(a,b){a.ia=b}function Gb(a,b,c){for(var d=0;d<a.ra.length;d++){var e=a.ra[d];e.id===b&&e.dc(b,c)}}
function Eb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.ba||a.ca){var e={};e.Yc=d[0]||0;e.Zc=d[1]||0;e.Xa=d[2]||b.clientWidth;e.gb=d[3]||b.clientHeight;e.hb=d[4]||1;e.kb=d[5]||1;e.Qc=d[6]||b.naturalWidth||e.Xa;e.Sc=d[7]||b.naturalHeight||e.gb;e.hc=d[8]||0;e.ic=d[9]||0;e.Pc=d[10]||0;e.Rc=d[11]||0;a.ba?(e.jb=a.ba.length,e.Ya=a.ba[0].length):(e.Ya=e.hb,e.jb=e.kb,e.hb=e.kb=0);e.ac=e.Xa/(e.Ya+e.Ya*e.hb)|0;e.bc=e.gb/(e.jb+e.jb*e.kb)|0;e.Oc=e.ac*e.hb|0;e.cc=e.bc*e.kb|0;e.Za=e.lb=-1;Hb(a,b,e);Ib(a,b,e);a.time&&
a.ea&&(a.ya=Jb(a.time,"timerInputRelease",function(){0>e.Za&&0>e.lb&&Kb(a,-1,-1)}))}if(a.ba||a.ca)a.time&&a.ea&&(a.Ba=Jb(a.time,"timerKeyRelease",function(){Lb(a)})),a.ga=0,a.oa="",a.ha=[],d=b,c&&(d=c,a.da||"BUTTON"!=c.nodeName||(d=document,a.da=c,Mb(a,b),a.ta=b)),Mb(a,d),a.da||(a.da=d)}function Nb(a){a.ea?Ob(a.time,a.Ba,a.ea):Lb(a)}
function Mb(a,b){function c(e,f,g){var l=document.activeElement;a.ka(327680,"%s.onKey%s(%d): %5.2f (%s)\n",l.id||l.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.da&&e!=a.da&&e!=a.ta?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Pb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Pb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Pb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Hb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.fa){var e=a.da;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||W(a,b,Qb,d,c)}});b.addEventListener("mousemove",function(d){a.fa||W(a,b,Rb,d,c)});b.addEventListener("mouseup",function(d){a.fa||d.button||W(a,b,Sb,d,c)});b.addEventListener("mouseout",function(d){a.fa||(0>c.Za?W(a,b,Rb,d,c):W(a,b,Sb,d,c))})}
function Ib(a,b,c){b.addEventListener("touchstart",function(d){a.ma&&(a.fa=!0);W(a,b,Qb,d,c)});b.addEventListener("touchmove",function(d){W(a,b,Rb,d,c)});b.addEventListener("touchend",function(d){W(a,b,Sb,d,c)})}
function Pb(a,b,c,d){if(void 0!=c){var e=cb[b]||b;var f=eb[b];var g=Tb[e];d=d&&d.location==db.qb;g&Ub&&d&&(g>>=1);g&&(g&Vb&&(c=!(a.aa&g)),a.aa=c?a.aa|g:a.aa&~g,Gb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=ab.mb&&b<=ab.tb?a.aa&(Wb|Xb)||(a.aa|=Xb,Gb(a,K.ob,!0)):b>=ab.ub&&b<=ab.z&&a.aa&Xb&&(a.aa&=~Xb,Gb(a,K.ob,!1));if(a.ba){if(void 0!=c)return!1;for(e=0;e<a.ba.length;e++)for(g=a.ba[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.ga?16>a.ha.length&&a.ha.push(b):(a.ga=1,a.oa=
f,Kb(a,d,e),Gb(a,f,!0),Nb(a)),!0}if(a.ca){if(void 0==c)return!0;b=Object.keys(a.ca);for(e=0;e<b.length;e++)if(g=b[e],0<=a.ca[g].keys.indexOf(f))return Gb(a,g,c),a.ca[g].state=c?1:0,!0}return!1}function Lb(a){1==a.ga?(a.ga++,Gb(a,a.oa,!1),a.oa="",Kb(a,-1,-1),Nb(a)):(a.ga=0,a.ha.length&&Pb(a,a.ha.shift()))}Bb.prototype.Ga=function(){this.aa=0;this.ua=this.wa=-1};
function W(a,b,c,d,e){var f=-1,g=-1,l=!1,h=-1,r=-1;if(c<Sb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,r=d.targetTouches[0].clientY,l=1<d.targetTouches.length):(h=d.clientX,r=d.clientY);var k=d.target.getBoundingClientRect();h-=k.left;r-=k.top;h=e.Qc/b.offsetWidth*h|0;r=e.Sc/b.offsetHeight*r|0;var m=h-e.Yc;var n=r-e.Zc;var q=k=!1;var t=h>=e.hc&&h<e.hc+e.Pc&&r>=e.ic&&r<e.ic+e.Rc;if(0<=m&&m<e.Xa&&0<=n+e.cc||t)if(l||a.ma||d.preventDefault(),0<=m&&m<e.Xa&&
0<=n&&n<e.gb){q=!0;d=e.Xa/e.Ya|0;var w=e.gb/e.jb|0,v=m/d|0,p=n/w|0;!a.Aa||p&1||(m-=d>>1,v=m/d|0,v==e.Ya-1&&(m=-1));w=p*w+(e.cc>>1);m-=v*d+(e.Oc>>1);n-=w;0<=m&&m<e.ac&&0<=n&&n<e.bc&&(f=v,g=p,k=!0)}}m=m||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Qb||c==Sb)for(v=0;v<a.sa.length;v++)p=a.sa[v],c==Sb?p.dc(p.id,!1):(w=n/(b/p.ue|0)|0,(m/(d/p.te|0)|0)==p.Je&&w==p.Ke&&p.dc(p.id,!0));if(!l)if(c==Qb)e.Za=h,e.lb=r,q?(Kb(a,f,g),k&&a.ea&&Ob(a.time,a.ya,a.ea,!0)):t&&a.na.Fa();else if(c==Rb)0<=e.Za&&0<=e.lb&&
a.va?Kb(a,f,g):a.pa&&a.pa(f,g);else if(c==Sb){if(c=a.ea)c=a.time,f=a.ya,c=c.aa&&0<f&&f<=c.ba.length?0<=c.ba[f-1].Da:!1;c||Kb(a,-1,-1);e.Za=e.lb=-1}else E(a,"unrecognized action: "+c)}function Kb(a,b,c){if(b!=a.ua||c!=a.wa)a.ua=b,a.wa=c,a.ia&&a.ia(b,c)}var Qb=1,Rb=2,Sb=3,Db="surface",Wb=3,Ub=170,Xb=512,Vb=3584,X={},Tb=(X[K.Dc]=2,X[K.lc]=8,X[K.jc]=32,X[K.Bb]=128,X[K.ob]=Xb,X[K.yc]=1024,X[K.Ac]=2048,X);A.Input=Bb;
function yb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.la[Yb];if(!a)throw Error("LED "+this.ja.la[Yb]+" binding for '"+Yb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ra=a;this.type=Na(H(this,"type",zb,Zb),$b,ac);this.ha=bc[this.type][0];this.oa=bc[this.type][1];this.width=H(this,"width",this.ha,void 0);this.height=H(this,"height",this.oa,void 0);
this.da=H(this,"cols",1,void 0);this.ca=this.da+H(this,"colsExtra",0,void 0);this.wa=H(this,"rows",1,void 0);this.ea=this.wa+H(this,"rowsExtra",0,void 0);this.Aa=this.width*this.da;this.ya=this.height*this.wa;this.ga=cc("black",0);this.fa=dc(this.ja.color)||this.ga;this.fb=cc(this.fa,1,.25);this.eb=cc(this.fa,1,2);this.ma=dc(this.ja.backgroundColor);this.rb=H(this,"fixed",!1);this.rb||(b.style.width="100%",b.style.height="auto");this.Qa=H(this,"hexagonal",!1);this.sb=H(this,"highlight",!0);this.Ha=
H(this,"persistent",this.type<ac);b.setAttribute("width",this.Aa.toString());b.setAttribute("height",this.ya.toString());b.style.backgroundColor=this.ga;a.appendChild(b);this.Sa=b.getContext("2d");if(this.sa=document.createElement("canvas"))this.sa.width=this.Ma=this.ha*this.da,this.sa.height=this.ua=this.oa*this.wa,this.ba=this.sa.getContext("2d");this.Ta=(this.ea+1)*this.ca*4;this.aa=Array(this.Ta);this.ra=null;this.Ua=this.da<this.ca?4*(this.ca-this.da):0;this.ia=this.ta=!1;this.Ia=0;this.Ba=!0;
this.pa=0;this.va=-1;var d=this;this.time=Q(this,"Time");ec(this.time,function(e){T(d,!1,e)});Ab(d,!0)}x(yb,O);function Ab(a,b){fc(a,a.aa);a.ia=a.ta=!0;b&&T(a,!0)}function gc(a){a.ma?(a.ba.fillStyle=a.ma,a.ba.fillRect(0,0,a.Ma,a.ua)):a.ba.clearRect(0,0,a.Ma,a.ua)}
function T(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.ia||b){if(a.type<ac){var d=0;if(!a.Ha||b)gc(a);else if(a.pa){d=a.da-a.pa;var e=a.ha*d;a.ba.drawImage(a.sa,a.ha*a.pa,0,e,a.ua,0,0,e,a.ua)}for(var f=e=0;f<a.ea;f++){for(var g=0;g<a.da;g++){var l=a.aa[e],h=a.aa[e+1]||a.ga,r=!1,k=!!(a.aa[e+3]&Y),m=a.sb&&e==a.va;!a.Ba&&l&&(l=hc,k=r=!0);if(k||m||b){if(g>=d)a:{k=a;var n=l;l=h;var q=g;h=f;var t=m;q=void 0===q?0:q;h=void 0===h?0:h;t=void 0===t?!1:t;var w=0;if(k.Qa&&!(h&1)&&(w=k.ha>>1,q==k.da-1))break a;
if(l&&l!=k.fa){t=t?cc(l,1,2):l;var v=cc(l,1,.25)}else t=t?k.eb:k.fa,v=k.fb;l=!1;n=n?t:v;t==k.ga&&(n=k.ma,l=!0);t=q*k.ha+w;v=h*k.oa;k.Ha&&(q=q*k.ha+w,h*=k.oa,k.ma?(k.ba.fillStyle=k.ma,k.ba.fillRect(q,h,k.ha,k.oa)):k.ba.clearRect(q,h,k.ha,k.oa));k.ba.fillStyle=n;h=ic[k.type];3==h.length?(k.ba.beginPath(),k.ba.arc(t+h[0],v+h[1],h[2],0,2*Math.PI),l?(k.ba.globalCompositeOperation="destination-out",k.ba.fill(),k.ba.globalCompositeOperation="source-over"):k.ba.fill()):k.ba.fillRect(t+h[0],v+h[1],h[2],h[3])}a.aa[e+
3]=m||r?a.aa[e+3]|Y:a.aa[e+3]&~Y}e+=4}e+=a.Ua}a.pa=0}else{b="";for(d=0;d<a.aa.length;d+=4)b+=a.aa[d]||" ",a.aa[d+3]&jc&&(b+=".");gc(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;r=e;m=f;r=void 0===r?0:r;m=void 0===m?0:m;if(k=kc[k])for(h=0;h<k.length;h++)if(l=g,q=lc[k[h]]){w=(void 0===r?0:r)*l.ha;n=(void 0===m?0:m)*l.oa;l.ba.fillStyle=l.fa;l.ba.beginPath();if(3==q.length)l.ba.arc(w+q[0],n+q[1],q[2],0,2*Math.PI);else for(t=0;t<q.length;t+=2)t?l.ba.lineTo(w+q[t],n+q[t+1]):l.ba.moveTo(w+q[t],
n+q[t+1]);l.ba.closePath();l.ba.fill()}if(++e==a.da&&(e=0,++f==a.ea))break}}a.Sa.globalCompositeOperation=a.ma&&a.fa!=a.ga?"source-over":"copy";a.Sa.drawImage(a.sa,0,0,a.Ma,a.ua,0,0,a.Aa,a.ya);a.ia=!1;a.va=-1}else a.Ha||a.ta||(!c||!a.Ia||c-a.Ia>=(1E3/60|0))&&Ab(a,!0);a.ta=!1;c&&(a.Ia=c)}function mc(a,b){b=void 0===b?!0:b;a.Ba!=b&&(a.Ba=b,a.ia=!0)}function nc(a,b,c){b=4*(c*a.ca+b);return b<=a.aa.length-4?a.aa[b+2]:0}function oc(a,b,c){var d;b=4*(c*a.ca+b);b<=a.aa.length-4&&(d=a.aa[b]);return d}
function dc(a){return(a=a||void 0)&&gb[a]||a}function cc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=gb[a]||a;if(pc(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function fc(a,b){for(var c=0;c<b.length;c+=4)qc(a,b,c)}function qc(a,b,c){b[c]=a.type<ac?hc:" ";b[c+1]=a.fa==a.ga?null:a.fa;b[c+2]=0;b[c+3]=Y}
yb.prototype.Ja=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.fa&&c==this.ma&&a&&a.length==this.aa.length){this.aa=a;for(b=0;b<=this.aa.length-4;b+=4)this.aa[b+1]==this.ga&&(this.aa[b+1]=null);T(this,!0);return!0}return!1};function pc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
yb.prototype.Ka=function(a){this.aa&&(a.push(this.fa),a.push(this.ma),a.push(this.aa))};function rc(a,b,c,d){var e=null;0<=c&&c<a.ea&&0<=b&&b<a.ca&&(e=!1,d=d||a.fa,d==a.ga&&(d=null),b=4*(c*a.ca+b),a.aa[b+1]!==d&&((a.aa[b+1]=d)||(a.aa[b]=hc),a.aa[b+3]|=Y,a.ia=e=!0),a.va=b,a.ta=!0);return e}function sc(a,b,c,d){if(0<=c&&c<a.ea&&0<=b&&b<a.ca){b=4*(c*a.ca+b);c=0;if(a.aa[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.aa[b+2]!==c&&(a.aa[b+2]=c,a.aa[b+3]|=Y,a.ia=!0);a.va=b;a.ta=!0}}
function tc(a,b,c,d){var e=!1,f=0&uc;b=4*(c*a.ca+b);if(b<=a.aa.length-4){if(a.aa[b]!==d||(a.aa[b+3]&uc)!==f)a.aa[b]=d,a.aa[b+3]=a.aa[b+3]&~uc|f|Y,a.ia=e=!0;a.va=b;a.ta=!0;a.pa=0}return e}
var $b=0,zb=1,ac=3,Zb={small:$b,round:zb,square:2,digit:ac},Yb="container",hc=0,uc=129,jc=1,Y=128,vc={},ic=(vc[$b]=[4,4,4],vc[zb]=[16,16,14],vc[2]=[2,2,28,28],vc),bc=[[8,8],[32,32],[32,32],[96,128]],lc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},kc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};A.LED=yb;
function wc(a,b,c){O.call(this,a,b,c);this.Qa=H(this,"cyclesMinimum",1E5,void 0);this.eb=H(this,"cyclesMaximum",1E9,void 0);this.Ra=Na(H(this,"cyclesPerSecond",1E6,void 0),this.Qa,this.eb);this.ta=1E3/60;this.Kc=H(this,"updatesPerSecond",2,void 0)||2;this.sb=1E3/this.Kc;this.Ua=0;this.Lc=H(this,"timeLock",!0);this.Ia=this.pa=0;this.Ha=this.ga=1;this.Ta=this.ia=this.Ra/1E4/100;this.ya=[];this.ma=[];this.ba=[];this.Aa=[];this.Sa=this.aa=this.wa=this.ha=!1;this.oa=this.da=0;a=Ia("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ta}this.fb=window[a].bind(window,this.Xc.bind(this),d);this.rb=window[Ia("cancelAnimationFrame")||"clearTimeout"].bind(window);this.va=this.ua=this.ea=this.ca=this.Ma=0;xc(this)||yc(this,this.Ha)}x(wc,O);function ec(a,b){a.ya.push(b)}u=wc.prototype;
u.Na=function(a,b){var c=this;switch(a){case zc:b.onclick=function(){Ac(c)&&(c.aa?Bc(c):c.start())};break;case Cc:b.onclick=function(){yc(c,c.ga<<1);Dc(c,Ec(c.ia))};break;case Fc:b.onclick=function(){Ac(c)&&(c.aa?E(c,"already running"):c.da?Bc(c):Gc(c,void 0))};break;case Hc:b.addEventListener("mousedown",function(){c.ha=!0}),b.addEventListener("mouseup",function(){xc(c);c.ha=!1}),b.addEventListener("mousemove",function(){c.ha&&xc(c)}),b.addEventListener("change",function(){c.ha=!0;xc(c);c.ha=!1})}O.prototype.Na.call(this,
a,b)};function Jb(a,b,c){var d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,Nc:c,ib:d,Da:-1});0<=d&&Ob(a,e,d);return e}
function Ic(a,b,c,d){var e=0,f=a.ia,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.ka(16384,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.ta&&(1<a.ga&&(a.ga>>=1,a.ka(2097152,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ta,a.ga)),e=d));a.pa=f;a.Ia=f/a.Ta;b=a.Ia/a.ga;a.Ma=g/b/60+1E-8;a.ka(16384,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Ma,g,b,60);return e}
function Jc(a,b){a.ua=a.ea=b;if(!a.ma.length)return a.ea=0,a.ua;for(var c=0;0<a.ea;){if(c<a.ma.length){var d=a.ma[c++];b=d.fc.call(d,b)||1}else c=b=0;a.ea-=b}return a.ua-a.ea}function Kc(a,b){b=void 0===b?a.ua-a.ea:b;if(!a.aa){if(a.ca)for(var c=0;c<a.ma.length;c++){var d=a.ma[c];d.gc.call(d)}a.ca=b}a.ca-=b;1>a.ca&&(a.wa=!0);a.va+=b;a.ua=a.ea=0;a.aa||(a.va=0);return b}
function Lc(a,b){b=void 0===b?0:b;if(b){var c=b;a.ca+=b}else for(c=a.ca,1>c&&(c=a.ca+=a.Ma),0>c&&(a.ka(2097152,"warning: cycle count dropped below zero: %f\n",c),c=a.ca=0),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.Da)&&c>d.Da&&(c=d.Da)}return c}function Ec(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Ac(a){return a.Sa?!0:(E(a,"not powered"),!1)}
function Mc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.Da||(d.Da-=b,0>=d.Da&&(d.Da=-1,d.Nc(),0<=d.ib&&Ob(a,c,d.ib)))}}u.Fa=function(a){this.Sa=a;void 0===this.Pa&&(this.Pa=Q(this,"Debugger",!1))};
u.Xc=function(a){a=void 0===a?Date.now():a;this.oa=0;if(this.aa){var b=Date.now();if(this.ra){var c=b-this.sa-this.ta;c>this.ta&&(this.fa+=c,this.ka(2097152,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.sa=b;this.fa||(this.fa=b);this.Ba=0;try{this.wa=!1;do Mc(this,Kc(this,Jc(this,Lc(this))));while(this.aa&&!this.wa)}catch(d){E(this,d.message),Bc(this)}this.ra=Date.now();this.Ba&&(this.fa+=this.Ba,this.sa+=this.Ba);this.sa+=Ic(this,this.va,this.ra-this.fa,this.ra-this.sa);
this.ra-this.Ua>=this.sb&&this.update();for(b=0;b<this.ya.length;b++)this.ya[b](a);this.oa=this.fb()}};function yc(a,b){if(void 0!==b){if(1>b||!a.ha&&0<a.pa&&a.pa<.9*a.ia)b=a.Ha;a.ga=b;b=a.Ta*a.ga;a.ia!=b&&(a.ia=b,Dc(a,Ec(a.ia)))}a.fa=a.ra=0;a.ca=a.va=0;Ic(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.ib&&Ob(a,b,c.ib,!0)}}function xc(a){var b=a.la[Hc];return b?(yc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.eb-a.Qa)+a.Qa)/a.Ra|0),!0):!1}
function Ob(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.Da)&&(c=Math.ceil(a.Ra*(a.Lc?a.Ha:a.Ia)/1E3*(void 0===c?1E3:c)),a.aa&&(c+=Kc(a)),b.Da=c)}u.start=function(){if(this.aa||this.da)return!1;this.aa=!0;this.fa=this.ra=0;this.update(!0);this.oa=this.fb();return!0};function Gc(a,b){b=void 0===b?1:b;a.aa||(b&&!a.da&&(a.da=b),a.da&&(a.da--,Mc(a,Kc(a,Jc(a,Lc(a,1)))),a.update(!1),a.da&&setTimeout(function(){Gc(a,0)},0)))}
function Bc(a){a.aa?(a.aa=!1,Kc(a),a.oa&&(a.rb(a.oa),a.oa=0),a.update(!0)):a.da&&(a.da=0,a.update(!0))}u.update=function(a){a&&E(this,this.aa?"started with "+Ec(this.ia)+" target":"stopped");$a(this,zc,this.aa?"Halt":"Run");$a(this,Fc,this.da?"Stop":"Step");this.ha||(this.ka(16384,"getSpeedCurrent(%5.3fhz)\n",1E6*this.pa),Dc(this,this.aa&&this.pa?Ec(this.pa):"Stopped"));for(a=0;a<this.Aa.length;a++){var b=this.Aa[a];b.Uc.call(b)}this.Ua=Date.now();this.wa=!0};
function Dc(a,b){$a(a,Nc,b);$a(a,Cc,b)}var zc="run",Cc="setSpeed",Nc="speed",Fc="step",Hc="throttle";A.Time=wc;function Z(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.Pa=void 0;this.Wc=0;this.time=Q(this,"Time");this.time.ma.push(this);this.time.Aa.push(this);this.sa=this.pa=0}x(Z,O);Z.prototype.abort=function(a){E(this,a.message);Bc(this.time)};Z.prototype.fc=function(a){this.sa=this.pa=void 0===a?0:a;return this.ec()};Z.prototype.gc=function(){this.sa-=this.pa;this.pa=0};
Z.prototype.ec=function(){return this.sa-this.pa};
function Oc(a,b,c){Z.call(this,a,b,c);this.ia=H(this,"wrap",!1);this.ta=(this.wa=H(this,"font",""))&&Pc[this.wa]||Pc.Helvetica;this.ua=H(this,"rule","");this.oa=H(this,"pattern","");Qc(this,this.ya=H(this,"message",""));this.Ia=H(this,"toggleColor",!1);this.Ha=Array(Rc(this).length);if(c=Q(this,"LED",!1)){this.aa=c;Sc(this)||Ab(c,!0);this.ra=Q(this,"Input",!1);var d=this;this.Aa=new Bb(a,b+"Input",{"class":"Input",location:[0,0,c.Aa,c.ya,c.da,c.wa],drag:!(!this.ra||!this.ra.va),scroll:!(!this.ra||
!this.ra.ma),hexagonal:c.Qa,bindings:{surface:Ka(c,Yb)}});Fb(this.Aa,function(e,f){var g=d.aa;0<=e&&0<=f&&(d.ha?rc(g,e,f,d.ha)?tc(g,e,f,1):d.Ia?rc(g,e,f):tc(g,e,f,1-oc(g,e,f)):tc(g,e,f,1-oc(g,e,f)),sc(g,e,f,Rc(d,!!oc(g,e,f))),T(g))});this.ga=[];this.Ba=c.fa;Tc(this,this.Ba);Uc(this);Vc(this,this.ja[Wc]);Ga(this,this.Tc.bind(this))}}x(Oc,Z);u=Oc.prototype;
u.Na=function(a,b){var c=this,d;switch(a){case Xc:case Yc:b.onchange=function(){Zc(c,a)};Zc(this);break;case Wc:b.onchange=function(){Vc(c)};break;case $c:Fa(b,ad(this.ja[$c]),!1,this.ja.pattern);b.onchange=function(){var e=c.la[$c];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Sc(c,e):c.Ga())};break;case bd:b.onclick=function(){var e=cd(c,!0),f=c.la[dd];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');E(c,e)};break;case ed:b.onclick=function(){var e=cd(c);E(c,e);var f=window.location.href;
f=0<=f.indexOf("pattern=")?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((0>f.indexOf("?")?"?":"&")+"pattern="+e);window.location=f};break;case dd:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.la[fd];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(gd)?b.onclick=function(){Uc(c,a)}:(d=this.ja[$c])&&d[a]&&(b.onclick=function(){Sc(c,a)})}Z.prototype.Na.call(this,a,b)};
function ad(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
u.fc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.ua){case hd:var d=0;for(var e=this.aa,f=e.da,g=e.ea,l=this.Ha,h=0;h<g;h++)for(var r=0;r<f;r++){var k=l,m=!1,n=4*(h*e.ca+r);if(n<=e.aa.length-4&&e.aa[n+1]){m=!0;n=e.aa[n+2];for(var q=k.length-1;0<=q;q--)k[q]=n&15,n>>>=4}if(m){d++;if(l[0])l[0]--;else{m=(k=oc(e,r,h))||0;switch(k){case 1:if(m=hc,l[0]=l[2],l[0]){l[0]--;break}case hc:if(l[3]&&(m=this.ga.indexOf(e.aa[4*(h*e.ca+r)+1]||e.ga),0<=m)){for(m+=l[3];m>=this.ga.length;)m-=
this.ga.length;rc(e,r,h,this.ga[m])}m=1;l[0]=l[1];l[0]&&l[0]--}m!==k&&tc(e,r,h,m)}sc(e,r,h,l)}}break;case id:c=a||c;d=c;d=void 0===d?1:d;e=0;f=this.aa;g=f.ca;l=f.ea;if(f.pa||!jd(this,d))d=0;else{h=f.aa;n=4*d;r=4*g;m=q=k=0;for(this.ma=this.va=-1;k<g-d;){for(var t=1,w=m,v=0;v<l;v++){var p=h[m],C=h[m]=h[m+n];p=C!==p?Y:0;h[m+1]=h[m+n+1];h[m+2]=h[m+n+2];h[m+3]=h[m+n+3]|p;C&&(e++,t=0);m+=r}m=w+4;k++<f.da&&(t?q++:(0>this.ma&&(this.ma=q),q=0))}0>this.ma&&(this.ma=q);for(this.va=q;k<g;){n=m;for(q=0;q<l;q++)qc(f,
h,m),m+=r;m=n+4;k++}f.ia=!0;f.pa=d;d=e}break;case kd:d=0;e=this.aa;f=e.aa;g=e;g.ra||(g.ra=Array(g.Ta),fc(g,g.ra));g=g.ra;l=e.da;h=e.ea;r=4*l+e.Ua;k=h*r;m=0;n=m-r;q=n-4;t=n+4;w=m-4;v=m+4;C=m+r;p=C-4;for(var F=C+4,J=0;J<h;J++){J?J==h-1&&(this.ia?(C-=k,p-=k,F-=k):C=p=F=k):this.ia?(n+=k,q+=k,t+=k):n=q=t=k;for(var U=0;U<l;U++){U?1==U?this.ia?(w-=r,q-=r,p-=r):(w=m-4,q=n-4,p=C-4):U==l-1&&(this.ia?(v-=r,t-=r,F-=r):v=t=F=k):this.ia?(w+=r,q+=r,p+=r):w=q=p=k;var V=f[m],N=f[q]+f[n]+f[t]+f[v]+f[F]+f[C]+f[p]+f[w];
3==N?V=1:2!=N&&(V=hc);g[m]=V;g[m+1]=f[m+1];g[m+2]=f[m+2];g[m+3]=f[m+3]|(f[m]!==V?Y:0);m+=4;q+=4;n+=4;t+=4;v+=4;F+=4;C+=4;p+=4;w+=4;1==V&&d++}this.ia?(J||(n-=k,q-=k,t-=k),v+=r,t+=r,F+=r):(J||(n=m-r,q=n-4),v=m+4,t=n+4,F=C+4)}f=e.aa;e.aa=e.ra;e.ra=f;e.ia=!0}a||E(this,"active cells: "+d);b+=c}while(b<a)}return b};u.gc=function(){};u.ec=function(){return 0};function ld(a,b){var c=0;(a=a.la[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Rc(a,b){var c=0;if(b&&(b=a.la[md])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=ld(a,nd)+ld(a,od),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<pd.length;b++)c.push(ld(a,pd[b]));return c}
function Sc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.oa.match(/^[0-9]/)||(b=a.oa);if(b){var g=a.ja[$c];g=g&&g[b];if(!g)return E(a,"unknown pattern: "+b),!1;E(a,"loading pattern '"+b+"'");for(var l=b=0;b<g.length;b++){var h=g[b];if("#"==h[0])E(a,h);else if(l++){var r=h.indexOf("!");if(0<=r){f+=h.substr(0,r);break}f+=h}else{var k=h.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!k)return E(a,"unrecognized header line"),!1;var m=+k[1];var n=+k[2];k=k[3]}}}else{if(!a.oa)return!1;
f=0;k=a.oa.split("/");5==k.length&&(d=+k[f++],e=+k[f++]);if(3==k.length||5==k.length)m=+k[f++],n=+k[f++],f=k[f];else return E(a,"unrecognized pattern: "+a.oa),!1;k=a.ua}if(k!=a.ua)return E(a,"unsupported rule: "+k),!1;0>d&&(d=c.ca-m>>1);0>e&&(e=c.ea-n>>1);return 0>d||d+m>c.ca||0>e||e+n>c.ea?(a.ka("pattern too large (%d,%d)\n",m,n),!1):0<qd(a,d,e,f)}
function qd(a,b,c,d,e){e=void 0===e?!1:e;var f=a.aa,g=[0,0,0,1],l=0,h=!1,r=!1;d=d.split(/([a-z$])/i);e||Ab(f);for(var k=0,m=b,n=0;k<d.length-1;){var q=d[k++],t=d[k++],w=+q;for(q=""===q?1:w;q--;){var v=0,p=!1;switch(t){case "$":h=r=!1;b=m;c++;break;case "C":l=w;r=!0;break;case "R":g[0]=w;h=!0;break;case "G":g[1]=w;h=!0;break;case "B":g[2]=w;h=!0;break;case "A":g[3]=w;h=!0;break;case "b":p=tc(f,b,c,hc);v++;break;case "o":p=tc(f,b,c,1);v++;break;default:a.ka("unrecognized pattern token: %s\n",t)}if(null==
p)a.ka("invalid pattern position (%d,%d)\n",b,c);else{if(h){p=f;var C=g;p=4>C.length||1==C[3]?p.za("#%02x%02x%02x",C[0],C[1],C[2]):p.za("rgba(%d,%d,%d,%d)",C[0],C[1],C[2],C[3]);rc(f,b,c,p)}r&&(p=4*(c*f.ca+b),p<=f.aa.length-4&&f.aa[p+2]!=l&&(f.aa[p+2]=l));n<b&&(n=b);b+=v}}}e||T(f,!0);return 0>(n-=m-1)?0:n}
u.Ja=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return E(this,"Invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.ka("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.da=b.shift(),this.ea=b.shift(),this.ba=b.shift()}catch(d){return E(this,"Controller state error: "+d.message),!1}return Pa().message||Pa().pattern||Pa()[Wc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Ja(a)?!0:!1};
u.Tc=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Qc(this,a.join(" "));break;case "?":b="";rd.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};u.wb=function(a){return a&&this.Ja(a)?!0:!1};u.Fa=function(a){a?this.time.start():Bc(this.time)};u.Ga=function(){E(this,"reset");Ab(this.aa,!0);mc(this.aa,!0);this.ya&&Qc(this,this.ya)};u.xb=function(a){this.Ka(a)};u.Uc=function(){this.time.aa||T(this.aa)};
function jd(a,b,c,d){b=void 0===b?1:b;c&&(a.ea=c,a.ba=d);switch(a.ea){case sd:return!1;case td:case ud:if(0<a.ba)return a.ba-=b,!0;break;case vd:if(0<a.ba)return a.ba-=b,!1;break;case wd:if(a.ma>a.va)return!0;break;case xd:mc(a.aa,!1);a.ea=vd;break;case yd:mc(a.aa,!0);a.ea=vd;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.da>=a.ca.length&&(a.da=0);c=a.ca[a.da++];if("$"==c){d=0;for(var e=a.da;e<a.ca.length;){var f=a.ca.charCodeAt(e)-48;if(0>f||9<f)break;d=10*d+f;e++}if(e<a.ca.length)if(f=
a.ca[e++],"$"==f)a.da=e;else{var g=zd[f];if(g){a.da=e;a=jd(a,b,g,d);break a}E(a,"unrecognized message code: $"+f)}}" "==c?a.ba+=2:(d=a.aa.da+1,e=0>a.ba?a.ba:0,c=a.ta[c]||a.ta[c.toUpperCase()],f=Math.round((a.aa.wa-a.ta.height)/2),c&&(a.ba+=qd(a,d+e,0>f?0:f,c,!0)),a.ba+=2-b);a.ea=ud;a=!0}else a.ea=sd,a=!1;return a}
function cd(a,b){function c(V){var N=!1;null==k[3]&&(k[3]=1);if(v){if(h){if(k[0]!==t[0]||k[1]!==t[1]||k[2]!==t[2]||k[3]!==t[3])N=!0;U!==w&&(N=!0)}r!==q&&(N=!0);if(N||V&&q)h&&(m[0]!==t[0]&&(m[0]=t[0],e+=(t[0]||"")+"R"),m[1]!==t[1]&&(m[1]=t[1],e+=(t[1]||"")+"G"),m[2]!==t[2]&&(m[2]=t[2],e+=(t[2]||"")+"B"),m[3]!==t[3]&&(m[3]=t[3],e+=(t[3]||"")+"A"),n!==w&&(n=w,e+=(w||"")+"C")),1<v&&(e+=v),e+=1===q?"o":"b",N=!0}V?(e+="$",v=0):(N?v=1:v++,q=r,t[0]=k[0],t[1]=k[1],t[2]=k[2],t[3]=k[3],w=U)}var d=a.aa,e="",
f=0,g=a.aa.ca,l=a.aa.ea,h=!!a.ga.length,r,k=[0,0,0],m=[0,0,0,1],n=0,q=0,t=[0,0,0,1],w=0,v=0;a=0;var p=d.ca-1,C=d.ea-1;if(b){b&&(a=p,p=0);for(g=0;g<d.ea;g++)for(l=0;l<d.ca;l++)(r=oc(d,l,g))&&b&&(a>l&&(a=l),p<l&&(p=l));g=p-a+1;l=C+1;0>g&&(g=0);0>l&&(l=0)}for(var F=0;F<=C;F++){for(var J=a;J<=p;J++){r=oc(d,J,F);pc(d.aa[4*(F*d.ca+J)+1]||d.ga,k);var U=nc(d,J,F);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,l--,e=e.slice(1);for(;"$$"==e.slice(-2);)l--,e=e.slice(0,-1);"$"==e&&(l=0);e=(b?"":"0/"+f+"/")+g+"/"+l+"/"+
e.slice(0,-1);return e=e.replace(/\$+$/,"")}u.Ka=function(a){var b=[],c=[];b.push(2);b.push(this.ca);b.push(this.da);b.push(this.ea);b.push(this.ba);this.aa&&this.aa.Ka(c);a.push(b);a.push(c)};function Qc(a,b){a.ca!=b&&(b&&E(a,"new message: '"+b+"'"),a.ca=b);a.ea=td;a.da=a.ba=0}u.toString=function(){return""};
function Vc(a,b){var c=a.la[Wc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Ra&&(a.Ra.style.backgroundImage=b?"url('"+b+"')":"none")}}
function Zc(a,b){var c=a.la[Xc],d=a.la[Yc];b=b===Xc;c&&!c.options.length&&(Fa(c,a.ja.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.fa=a.ja.colors[c.options[c.selectedIndex].value];for(var e in a.fa)if(b=a.ja[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),E(a,"overriding color '"+e+"' with "+b+" (formerly "+a.fa[e]+")"),a.fa[e]=b;Fa(d,a.fa,!0)}c&&d&&d.options.length&&(a.ha=d.options[d.selectedIndex].value,Uc(a))}
function Tc(a,b){var c=a.la[Yc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ha=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Uc(a,b){var c=1,d;!b&&a.ha&&(d=a.la[Ad])&&(d.style.backgroundColor=a.ha);if(a.fa)for(var e in a.fa){var f=a.fa[e];a.ga&&(a.ga[c-1]=f);var g=gd+c++;d=a.la[g];if(!d)break;d.style.display="inline-block";g==b&&Tc(a,f);if(b&&b!=g||f!=a.ha)f=cc(f,1,.5);d.style.backgroundColor=f}for(;;){b=gd+c++;b=a.la[b];if(!b)break;b.style.display="none"}}
var Xc="colorPalette",Yc="colorSelection",gd="colorSwatch",Ad="colorSwatchSelected",md="countInit",nd="countOn",od="countOff",Wc="backgroundImage",$c="patterns",dd="symbolInput",fd="symbolPreview",bd="save",ed="saveToURL",pd=[null,nd,od,"countCycle"],rd=["s\t\tset string"],td="load",ud="scroll",vd="pause",sd="halt",wd="center",xd="off",yd="on",zd={b:xd,c:wd,h:sd,o:yd,p:vd,s:ud},hd="A4",id="L1",kd="B3/S23",Pc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};A.LEDCtrl=Oc;
function Bd(a,b,c){O.call(this,a,a);var d=this;this.ba=!1;this.ga=c;this.aa="";this.fa=this.ea=!1;mb(this,!1);this.Ca=0;b=b.trim();"{"==b[0]?Cd(this,b):(this.aa=b,Oa(this.aa,function(e,f,g,l){4==g&&(!l&&f?(Cd(d,f),Dd(d)):d.ka("error (%d) loading configuration: %s\n",l,e))}));window.addEventListener("load",function(){d.fa=!0;Dd(d)});window.addEventListener(Sa("iOS")?"pagehide":Sa("Opera")?"unload":"beforeunload",function(){Ed(d)});window.addEventListener("pageshow",function(){d.ba||d.Fa(!0)})}
x(Bd,O);Bd.prototype.Na=function(a,b){var c=this;switch(a){case Fd:b.onclick=function(){c.Fa()};break;case Gd:b.onclick=function(){c.Ga()}}O.prototype.Na.call(this,a,b)};
function Dd(a){var b=!0;if(a.ea&&a.fa){for(var c in a.ca){var d=void 0,e=a.ca[c];try{d=e["class"],A[d]?"Machine"==d?(a.ka("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,Hd,Id),a.aa&&a.ka("Configuration: %s\n",a.aa)):new A[d](a.qa,c,e):a.ka("unrecognized %s device class: %s\n",c,d)}catch(g){e.optional||(a.ka("error initializing %s device '%s': %s\n",d,c,g.message),b=!1),pb(a,c)}}if(a.da){var f=Ta(a);kb(a,function(g){return g.wb&&!g.wb(f)?(g.ka("unable to restore state for device: %s\n",g.xa),!1):!0})}mb(a,!0);
nb(a,a.Fa.bind(a,b))}}function Cd(a,b){try{a.ca=JSON.parse(b);jb(a,a.ca[a.qa],["autoSave","autoStart"]);a.da=!1!==a.ja.autoSave;a.ha=!1!==a.ja.autoStart;if(a.ga){var c=eval("("+a.ga+")"),d;for(d in c)a.ja[d]=c[d]}a.ea=!0}catch(e){c=e.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),E(a,"machine '"+a.qa+"' initialization error: "+c)}}
Bd.prototype.Fa=function(a){a=void 0===a?!this.ba:a;if(lb(this)){var b=this;a&&E(this,"power on");kb(this,function(c){c.Fa&&c!=b&&("CPU"!=c.ja["class"]||b.ha||lb(b)?c.Fa(a):c.time.update(!0));return!0});(this.ba=a)||E(this,"power off")}};Bd.prototype.Ga=function(){if(lb(this)){var a=this;kb(this,function(b){b.Ga&&b!=a&&b.Ga();return!0});E(this,"reset")}};function Ed(a){if(a.da){var b=[];kb(a,function(c){c.xb&&c.xb(b);return!0});Za(a,b)}a.Fa(!1)}
var Fd="power",Gd="reset",Hd="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",Id="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";window.LEDs=function(a,b,c){var d=new Bd(a,b,c);window.command=function(e){return Ua(d,e)};return d};A.Machine=Bd;})()

//# sourceMappingURL=leds.js.map
