(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu/tms1500.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/machine.js (C) Jeff Parsons 2012-2019
*/
var r;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={$b:!0},ha={};try{ha.__proto__=fa;ea=ha.$b;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function t(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Xd=b.prototype}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},u="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ka(a,b){if(b){var c=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}ka("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ka("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});ka("Number.parseInt",function(a){return a||parseInt});
function la(){la=function(){};u.Symbol||(u.Symbol=ma)}function na(a,b){this.a=a;ja(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.a};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function oa(){la();var a=u.Symbol.iterator;a||(a=u.Symbol.iterator=u.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[u.Symbol.iterator]=function(){return this};return a}
function qa(a,b){oa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ka("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});
ka("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});var ra=new ArrayBuffer(2);(new DataView(ra)).setUint16(0,256,!0);new Uint16Array(ra);function sa(){}var y={};y.Defs=sa;function ta(){}t(ta,sa);function ua(a,b){var c=a/z|0,d=b/z|0;return(a&b)==(b|0)&&(c&d)==d}var z=Math.pow(2,32);y.NumIO=ta;function A(){}t(A,ta);r=A.prototype;
r.flush=function(){var a=va;va="";this.ka(a)};r.ic=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};r.ka=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(va+a.substr(0,b)),va="",a=a.substr(b+1)));va+=a;return a.length};function B(a,b,c){a.ka(b+"\n",c)}
r.M=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.ka(this.N.apply(this,[a].concat(ba(c))))};
r.N=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*|~)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var l=e[g+5],k="ACDFHIMNSTWYbdfjcsoXx%".indexOf(l);if(0>k)d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+l;else{if(f<c.length){var h=c[f];"%"!=l&&f++}else h=c[c.length-1];var n=e[g+1],m=0<=n.indexOf("#"),p=0<=n.indexOf("0"),q=e[g+2];"*"==q||"~"==q?(q="~"==q?(h>>2)+(!m||"x"!=l&&"X"!=l?0:2):h,h=f<c.length?c[f++]:c[c.length-
1]):q=+q||0;var v=e[g+3];v=v?+v.substr(1):-1;var w=null,C=0,x="";k=12>k&&"object"!=typeof h?this.ic(h):h;switch(l){case "C":h=m?"#":"";d+=isNaN(k.getTime())?void 0:this.N(this.N("%%%sW, %%%sF %%%sD, %%%sY",h),k);continue;case "D":h=m?k.getUTCDate():k.getDate();l="d";break;case "A":case "H":case "I":h=m?k.getUTCHours():k.getHours();"A"==l?(h=12>h?"am":"pm",l="s"):("I"==l&&(h=h?12<h?h-12:h:12),l="d");break;case "F":case "M":h=m?k.getUTCMonth():k.getMonth();"F"==l?(h=wa[h],l="s"):(h++,l="d");break;case "N":h=
m?k.getUTCMinutes():k.getMinutes();l="d";break;case "S":h=m?k.getUTCSeconds():k.getSeconds();l="d";break;case "T":h=m?"#":"";d+=isNaN(k.getTime())?void 0:this.N(this.N("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),k);continue;case "W":h=xa[m?k.getUTCDay():k.getDay()];l="s";break;case "Y":h=m?k.getUTCFullYear():k.getFullYear(),0<v&&(h%=Math.pow(10,v),v=-1),l="d"}switch(l){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h);case "f":h=+h;l=h+"";0<=v&&(l=h.toFixed(v));l.length<q&&(p?(0>
h&&(q--,l=l.substr(1)),l=("0000000000"+l).slice(-q),0>h&&(l="-"+l)):l=("          "+l).slice(-q));d+=l;break;case "j":d+=JSON.stringify(h,null,q||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!==h)for("string"!=typeof h&&(h=h.toString()),0<=v&&(h=h.substr(0,v));h.length<q;)h=0<=n.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":C=8,m&&(x="0");case "X":w=ya;case "x":l="";C||(C=16);!x&&m&&(x="0x");w||(w=za);"string"==typeof h&&(h=Number.parseInt(h,h.match(/(^0x|[a-f])/i)?
16:10));p&&!q&&(q=Math.abs(h),q=255>=q?2:65535>=q?4:4294967295>=q?8:9,q+=x.length);q-=x.length;do m=h&C-1,h>>>=16==C?4:3,p||!l||m||h?l=w[m]+l:(x&&(l=x+l,x=""),0<q&&(l=" "+l));while(0<--q||h);d+=x+l;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+l+")"}}}return d+=e[g]};var va="",za="0123456789abcdef",ya="0123456789ABCDEF",xa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),wa="January February March April May June July August September October November December".split(" ");
y.StdIO=A;function D(a){this.O={};this.ca=0;this.J=this;a&&(this.J.ca=0,this.J.la=[],this.J.da=0,this.J.Fa={},this.J.cd=!1)}var Aa;t(D,A);D.prototype.ua=function(a,b){var c=this;switch(a){case Ba.jb:b.onclick=function(){var d=c.xa(Ba.Ja,!0);d&&(d.value="")};break;case Ba.Ja:Ca(b),b.addEventListener("keydown",function(d){Da(c,d,!0)}),b.addEventListener("keypress",function(d){Da(c,d)})}};
function Ea(a,b){b=void 0===b?{}:b;var c=Array.isArray(b);b.container||(b.container=a.W);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.O[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.O[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.O[d]=f,a.ua(d,f)}}function Ca(a){a.value="";a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false")}D.prototype.xa=function(a){return this.O[a]};
function Fa(a){var b=Ga;return a.I.bindings&&a.I.bindings[b]}function Ha(a){if(a=a.O[Ia])var b=a.textContent;return b}function Ja(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}function E(a,b,c,d){a=a.I[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Ka(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function La(a){if(void 0===F.Ia){var b=!1;if(window)try{window.localStorage.setItem(F.ta,F.ta),b=window.localStorage.getItem(F.ta)==F.ta,window.localStorage.removeItem(F.ta)}catch(c){B(a,c.message),b=!1}F.Ia=b}return!!F.Ia}function G(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ca;return-1==(b|1)||ua(a.J.ca,b)?!0:!1}
function Ma(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Na(a){var b=null;if(La(a)){var c;if(window)try{(c=window.localStorage.getItem(a.w))&&(b=JSON.parse(c))}catch(d){B(a,d.message)}}return b}
function Da(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.J,f=b.target;if(c){a=!1;var g;c=f.value;var l=c.lastIndexOf("\n");d==H.Na&&f.selectionStart<=l+1&&(a=!0);d==H.Tb?(a=!0,0<e.da&&(g=e.la[--e.da])):d==H.nb&&(a=!0,e.da<e.la.length&&(g=e.la[++e.da]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,l+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.da&&c+1==g.length&&
(f.value+=e.la[--e.da],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Oa(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&B(a,b.replace(/\n$/,""),!1))}}
function Pa(a,b){if(void 0!=b){var c=a.J;try{if(b=b.trim())c.da<c.la.length&&b==c.la[c.da]?c.da++:(c.la.push(b),c.da=c.la.length);var d=b.split(" "),e=d[0],f=a.J.Fa[Qa.Oa];switch(e[0]){case "m":if("?"==e[1]){var g="";Ra.forEach(function(m){g+=m+"\n"});g&&(g="message commands:\n"+g);break}g="";var l=void 0;e=d[d.length-1].toLowerCase();var k="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(l=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(I));for(f=
1;f<d.length;f++){e=d[f];var h=I[e];if(!h){g+="unrecognized message: "+e+"\n";break}void 0!=k&&Sa(a,h,k);if(void 0==l||l==G(a,h))g+=a.N("%8s: %b\n",e,G(a,h))}G(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ta.forEach(function(m){g+=m+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var n=f[a](d);if(void 0!=n){g=g?g+n:n;break}}}}catch(m){g="error: "+m.message+"\n"}}return g}
function Oa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Pa(a,b[d])}return c}D.prototype.ka=function(a,b){void 0==b&&(b=G(this,0x800000000000));if(!b){var c=this.xa(Ba.Ja,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Ma("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return A.prototype.ka.call(this,a,b)};
D.prototype.M=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return G(this,d)?A.prototype.M.call.apply(A.prototype.M,[this,a].concat(ba(c))):0};function Ua(a,b){if(La(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.w,b)}catch(c){B(a,c.message)}}}function J(a,b,c){if(a=a.O[b])a.textContent=c}
function Sa(a,b,c){var d=!1;c?(c=a.J.ca,a.J.ca=(c|b)+(c/z|0|b/z|0)*z):(d=ua(a.J.ca,0x800000000000)&&ua(b,0x800000000000),c=a.J.ca,a.J.ca=(c&~b)+((c/z|0)&~(b/z|0))*z);d&&a.flush()}
var Ba={jb:"clear",Ja:"print"},Ta=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Ra=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],I={all:0xffffffffffff,buffer:0x800000000000},Qa={Oa:"command"},H={Na:8,Pb:9,Bb:10,lb:13,Pd:16,wc:17,qc:18,Ed:19,tc:20,Bc:27,Nb:32,Hd:33,Gd:34,zc:35,$c:36,Ab:37,Tb:38,Jb:39,
Wc:39,nb:40,Rc:44,Id:44,ad:45,yc:46,Vc:46,Zc:47,ZERO:48,ONE:49,Rb:50,Qb:51,rb:52,qb:53,Mb:54,Lb:55,ob:56,Fb:57,Yc:59,Tc:61,gb:65,hb:66,ib:67,mb:68,E:69,pb:70,sb:71,tb:72,ub:73,vb:74,xb:75,zb:76,Db:77,Eb:78,Gb:79,Hb:80,Q:81,Ib:82,Kb:83,Ob:84,Sb:85,Ub:86,Wb:87,Xb:88,Yb:89,Zb:90,uc:91,Uc:91,Pc:92,Ld:93,Xc:93,dd:96,vd:96,Oc:96,ed:97,td:97,fd:98,sd:98,gd:99,zd:99,hd:100,wd:100,jd:101,pd:101,kd:102,Bd:102,ld:103,ud:103,md:104,Dd:104,nd:105,Ad:105,yd:106,od:107,Cd:109,qd:110,rd:111,Cc:112,Gc:113,Hc:114,
Ic:115,Jc:116,Kc:117,Lc:118,Mc:119,Nc:120,Dc:121,Ec:122,Fc:123,xd:144,Nd:145,Sc:173,Od:186,Ac:187,vc:188,xc:189,Fd:190,Qd:191,rc:192,bd:219,sc:220,Kd:221,Jd:222,Qc:224,Rd:1E3},K={},Va=(K[H.Na]="\b",K[H.Pb]="\t",K[H.Bb]="\n",K[H.lb]="\r",K[H.Nb]=" ",K[H.ZERO]="0",K[H.ONE]="1",K[H.Rb]="2",K[H.Qb]="3",K[H.rb]="4",K[H.qb]="5",K[H.Mb]="6",K[H.Lb]="7",K[H.ob]="8",K[H.Fb]="9",K[H.gb]="A",K[H.hb]="B",K[H.ib]="C",K[H.mb]="D",K[H.E]="E",K[H.pb]="F",K[H.sb]="G",K[H.tb]="H",K[H.ub]="I",K[H.vb]="J",K[H.xb]="K",
K[H.zb]="L",K[H.Db]="M",K[H.Eb]="N",K[H.Gb]="O",K[H.Hb]="P",K[H.Q]="Q",K[H.Ib]="R",K[H.Kb]="S",K[H.Ob]="T",K[H.Sb]="U",K[H.Ub]="V",K[H.Wb]="W",K[H.Xb]="X",K[H.Yb]="Y",K[H.Zb]="Z",K[H.Ab]="Left",K[H.Jb]="Right",K),Wa={list:[],Vb:"version"},Xa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",
chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",
deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",
lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",
mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",
red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},F={Ia:void 0,
ta:"PCjs.localStorage"};y.WebIO=D;function L(a,b,c,d){D.call(this,a==b);this.w=a;this.W=b;M[this.w]||(M[this.w]={});M[this.w][this.W]&&this.M("warning: machine configuration contains multiple '%s' devices\n",this.W);M[this.w][this.W]=this;this.id=this.w+"."+this.W;Ya.push(this);this.J=N(this,this.w);Za(this,c,d);this.Cb={};this.Y=this.ma=void 0}t(L,D);
function Za(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d,e=Aa;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,l=/([^&=]+)=?([^&]*)/g;f=l.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Aa=e}d=e;for(var k in d)0<=c.indexOf(k)&&(f=d[k],f.match(/^[+-]?[0-9.]+$/)?e=Number.parseInt(f,10):"true"==f?e=!0:"false"==f?e=!1:(e=f,f='"'+f+'"'),b[k]=e,B(a,"overriding "+a.W+" property '"+
k+"' with "+f))}a.I=b;Ea(a,b.bindings);b=void 0===b?{}:b;a.version=2;if(a.version){c="";var h;a.w!=a.W&&(h=N(a,a.w).version)&&h!=a.version&&(c="Machine");c||(h=b.version)&&h>a.version&&(c="Config");c&&(h="Error: "+a.N("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.Td,a.version,c,h)+"\n\nClearing your browser's cache may resolve the issue.",(b=Wa.Vb)&&0>Wa.list.indexOf(b)&&(alert(h),Wa.list.push(b)),B(a,h))}}
function $a(a,b){var c;try{var d=M[a.w];if(d)for(c in d){var e=d[c];if("Machine"!=e.I["class"]&&!b(e))break}}catch(f){a.M("error while enumerating device '%s': %s\n",c,f.message)}}L.prototype.xa=function(a,b){b=void 0===b?!1:b;if(a){var c=D.prototype.xa.call(this,a,b);if(void 0===c&&b){b=M[this.w];for(var d in b)if(c=b[d].O[a])break;c||(c=null);this.O[a]=c}}return c};
function N(a,b,c){var d=b,e=a.w,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=M[e])&&f[b]||null;if(!b){for(f=0;f<Ya.length;f++)if(Ya[f].id===d){b=Ya[f];break}if(!b&&(void 0===c||c))throw Error(a.N("unable to find device with ID '%s'",d));}return b}function O(a,b,c){var d=null,e=M[a.w];if(e)for(var f in e)if(e[f].I["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.N("unable to find device with class '%s'",b));return d}
L.prototype.M=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&G(this,a)&&(void 0===this.ma&&(this.ma=O(this,"Debugger")),this.J.ca&ab&&(void 0===this.Y&&(this.Y=O(this,"CPU")),this.Y))?(a=c.shift(),D.prototype.M.call(this,"%#06x: %s.%s\n",this.Y.ia,this.W,this.N.apply(this,[a].concat(ba(c))).trim())):D.prototype.M.call.apply(D.prototype.M,[this,a].concat(ba(c)))};function bb(a,b){(a=M[a.w])&&delete a[b]}
L.prototype.cb=function(a,b){(a=this.Cb[a])&&a.set(b)};var M={},Ya=[],ab=1;I.addr=ab;I.bus=2;I.memory=4;I.ports=8;I.chips=16;I.kbd=32;I.serial=64;I.misc=128;I.cpu=256;I.video=512;I.monitor=1024;I.screen=2048;I.timer=4096;I.event=8192;I.input=16384;I.key=32768;I.mouse=65536;I.touch=131072;I.warn=262144;I.halt=524288;window&&(window.PCjs||(window.PCjs={}),M=window.PCjs.Machines||(window.PCjs.Machines={}),Ya=window.PCjs.Components||(window.PCjs.Components=[]));y.Device=L;
function cb(a,b,c){L.call(this,a,b,c);this.type="static"==c.type?db:eb;this.h=c.addrWidth||16;this.c=Math.pow(2,this.h);this.m=this.c-1|0;this.a=c.blockSize||(16<this.h?4096:1024);this.a>this.c&&(this.a=this.c);this.u=this.c/this.a|0;this.j=Math.log2(this.a)|0;this.s=(1<<this.j)-1;this.l=c.dataWidth||8;this.b=Array(this.u);this.f=0;a=new P(a,b+"[NONE]",{size:this.a,bus:this.W});for(b=0;b<this.c;b+=this.a)fb(this,b,this.a,Q.NONE,a);a=this.f;this.f+=this.type;a&&this.f||(this.ya=this.jc)}t(cb,L);
function fb(a,b,c,d,e){for(var f=0,g=b>>>a.j;0<c&&g<a.b.length;){var l=g*a.a,k=a.a-(b-l);k>c&&(k=c);var h=a.b[g];if(b!=l||k!=a.a||h&&h.type!=Q.NONE)break;var n=h=void 0,m=b,p=a.h,q=16;p=void 0===p?0:p;h=void 0===h?0:h;var v="",w="",C=-1;q||(q=a.v||10);p&&(C=Math.ceil(p/Math.log2(q)));if(void 0==n)switch(q){case 8:n="0o";break;case 16:n="0x";break;case 10:w=".";default:n=""}isNaN(m)||"number"!=typeof m?(m=void 0,n=w=""):(0>m&&-1<m&&(m=-1),p&&(0>m&&(m+=Math.pow(2,p)),m>=Math.pow(2,p)&&(C=Math.ceil(Math.log(m)/
Math.log(q)))));for(p=h||-1;C--;){p||(v=","+v,p=h);if(void 0==m){if(v="?"+v,0>C)break}else{var x=m%q;m=Math.trunc(m/q);x+=0<=x&&9>=x?48:55;v=String.fromCharCode(x)+v;if(!m&&0>C)break}p--}h=a.W+"["+(n+v+w)+"]";if(e)if(e.size==a.a)b=e;else{n=void 0;if(e.values&&(n=e.values.slice(f,f+k),n.length!=k))break;b=new P(a.w,h,{type:d,Ka:b,size:k,bus:a.W,values:n})}else b=new P(a.w,h,{type:d,Ka:b,size:k,bus:a.W});a.b[g]=b;b=l+a.a;c-=k;f+=k;g++}}r=cb.prototype;r.na=function(){};
r.La=function(a){return a&&this.ga(a)?!0:!1};r.Ma=function(a){this.ha(a)};r.ga=function(a){for(var b=0;b<this.b.length;b++){var c=this.b[b];if((this.type==eb||c.type&Q.Aa)&&c.ga){var d=a.shift();if(!c.ga(d))return!1}}return!0};r.ha=function(a){for(var b=0;b<this.b.length;b++){var c=this.b[b];if((this.type==eb||c.type&Q.Aa)&&c.ha){var d=[];c.ha(d);a.push(d)}}};r.jc=function(a){return this.b[a>>>this.j].ya(a&this.s)};var db=0,eb=1;y.Bus=cb;
function P(a,b,c){L.call(this,a,b,c);this.Ka=c.addr;this.size=c.size;this.type=c.type||Q.NONE;this.f=(a=this.I.bus)?N(this,a):O(this,a="Bus");if(!this.f)throw Error(this.N("unable to find bus '%s'",a));this.j=this.f.l;this.h=Math.pow(2,this.j)-1;this.values=this.c=null;a=this.bb;if(b=this.f.type==db)if(b=8==this.j)b=N(this,this.w),b=!1!==(b&&b.I&&b.I.ArrayBuffer);b&&(this.c=new ArrayBuffer(this.size),new DataView(this.c,0,this.size),this.values=new Uint8Array(this.c,0,this.size),new Uint16Array(this.c,
0,this.size>>1),new Int32Array(this.c,0,this.size>>2));this.m=!1;gb(this,c.values);switch(this.type){case Q.NONE:this.ya=this.kc;break;case Q.Wa:this.ya=a;break;case Q.Aa:this.ya=a}}t(P,L);function gb(a,b){if(!a.values)b?a.values=b:a.values=Array(a.size).fill(a.h);else if(b)for(var c=0;c<a.size;c++)a.values[c]=b[c]}r=P.prototype;r.na=function(){this.type>=Q.Aa&&this.values.fill(0)};r.kc=function(){return this.h};r.bb=function(a){return this.values[a]};
r.ga=function(a){var b=a.shift();if(this.W==b){this.m=a.shift();a.shift();a=a.shift();var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}gb(this,a);return!0}return!1};r.ha=function(a){a.push(this.W);a.push(this.m);a.push(!1);for(var b=this.values,c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}a.push(e.length>=b.length?b:e)};var Q={NONE:1,Wa:2,Aa:4,Md:14,Sd:12};
y.Memory=P;
function R(a,b,c){c.type=Q.Wa;P.call(this,a,b,c);fb(this.f,c.addr,c.size,c.type,this);this.Y=this.ma=void 0;if(y.LED&&this.O[Ga]){var d=this;this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.l=this.values.length/this.b|0;this.a=new hb(a,b+"LEDs",{"class":"LED",bindings:{container:Fa(this)},type:ib,cols:this.b,rows:this.l,color:E(this,"colorROM","green"),backgroundColor:E(this,"backgroundColorROM","black"),persistent:!0}),jb(this.a);this.s=new kb(a,b+"Input",{"class":"Input",location:[0,
0,this.a.aa,this.a.T,this.b,this.l],bindings:{surface:Fa(this)}});this.u=Ha(this)||"";lb(this.s,function(e,f){if(d.Y){var g=d.u;0<=e&&0<=f&&(e=f*d.b+e,g=mb(d.Y,d.Ka+e,d.values[e]));J(d,Ia,g)}})}}t(R,P);
R.prototype.ga=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.a.length==d?(this.a.a=c,S(this.a,!0)):(this.M("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.M("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};R.prototype.ea=function(){void 0===this.Y&&(this.Y=O(this,"CPU"));void 0===this.ma&&(this.ma=O(this,"Debugger",!1))&&this.ma.wb&&this.ma.wb(this.I.symbols)};
R.prototype.bb=function(a){this.a&&nb(this.a,a%this.b,a/this.b|0,ob,T);return this.values[a]};R.prototype.ha=function(a){this.a&&(a.push(this.a.a),a.push(this.values))};var Ga="array",Ia="cellDesc";y.ROM=R;
function kb(a,b,c){L.call(this,a,b,c);this.ca=16384;this.m=this.u=null;this.time=O(this,"Time");this.J=O(this,"Machine");this.V=E(this,"drag",!1);this.R=E(this,"scroll",!1);this.U=E(this,"hexagonal",!1);this.f=E(this,"releaseDelay",0,void 0);this.h=!1;a=this.I.map;this.a=this.b=null;if(a)if(a.length)this.a=a;else{this.b={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.b[f]={keys:g,
Wd:e,state:0}}}this.v=[];this.H=[];this.c=this.K=null;(a=this.O[pb])&&qb(this,a,this.xa(c.focusBinding,!0),this.I.location);this.na()}t(kb,L);function lb(a,b){a.u=b}function rb(a,b,c){for(var d=0;d<a.v.length;d++){var e=a.v[d];e.id==b&&e.ab(b,c)}}
function qb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.a||a.b){var e={};e.oc=d[0]||0;e.pc=d[1]||0;e.va=d[2]||b.clientWidth;e.Ba=d[3]||b.clientHeight;e.Ca=d[4]||1;e.Ga=d[5]||1;e.dc=d[6]||b.naturalWidth||e.va;e.fc=d[7]||b.naturalHeight||e.Ba;e.eb=d[8]||0;e.fb=d[9]||0;e.cc=d[10]||0;e.ec=d[11]||0;a.a?(e.Ea=a.a.length,e.wa=a.a[0].length):(e.wa=e.Ca,e.Ea=e.Ga,e.Ca=e.Ga=0);e.Ya=e.va/(e.wa+e.wa*e.Ca)|0;e.Za=e.Ba/(e.Ea+e.Ea*e.Ga)|0;e.bc=e.Ya*e.Ca|0;e.$a=e.Za*e.Ga|0;e.za=e.Ha=-1;sb(a,b,e);tb(a,b,e);a.time&&
a.f&&(a.T=ub(a.time,"timerInputRelease",function(){0>e.za&&0>e.Ha&&vb(a,-1,-1)}))}if(a.a||a.b)a.time&&a.f&&(a.X=ub(a.time,"timerKeyRelease",function(){wb(a)})),a.j=0,a.s="",a.l=[],d=b,c&&(d=c,a.c||"BUTTON"!=c.nodeName||(d=document,a.c=c,xb(a,b),a.K=b)),xb(a,d),a.c||(a.c=d)}function yb(a){a.f?zb(a.time,a.X,a.f):wb(a)}
function xb(a,b){function c(e,f,g){var l=document.activeElement;a.M(40960,"%s.onKey%s(%d): %5.2f (%s)\n",l.id||l.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e){var f=document.activeElement;return a.c&&f!=a.c&&f!=a.K?null:e||window.event}b.addEventListener("keydown",function(e){if(e=d(e)){var f=e.which||e.keyCode,g=Ab(a,f,!0);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(e)){var f=e.which||e.charCode,g=Ab(a,f);c("Press",
f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(e)){var f=e.which||e.keyCode;Ab(a,f,!1);c("Up",f);e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function sb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.h){var e=a.c;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||U(a,b,Bb,d,c)}});b.addEventListener("mousemove",function(d){a.h||U(a,b,Cb,d,c)});b.addEventListener("mouseup",function(d){a.h||d.button||U(a,b,V,d,c)});b.addEventListener("mouseout",function(d){a.h||(0>c.za?U(a,b,Cb,d,c):U(a,b,V,d,c))})}
function tb(a,b,c){b.addEventListener("touchstart",function(d){a.R&&(a.h=!0);U(a,b,Bb,d,c)});b.addEventListener("touchmove",function(d){U(a,b,Cb,d,c)});b.addEventListener("touchend",function(d){U(a,b,V,d,c)})}
function Ab(a,b,c){var d;void 0!=c?d=Va[b]:d=String.fromCharCode(b).toUpperCase();if(a.a){if(!1===c)return!0;for(var e=0;e<a.a.length;e++)for(var f=a.a[e],g=0;g<f.length;g++)if(0<=f[g].split("|").indexOf(d))return a.j?16>a.l.length&&a.l.push(b):(a.j=1,a.s=d,vb(a,g,e),rb(a,d,!0),yb(a)),!0}if(a.b&&void 0!=c)for(b=Object.keys(a.b),e=0;e<b.length;e++)if(f=b[e],0<=a.b[f].keys.indexOf(d))return rb(a,f,c),a.b[f].state=c?1:0,!0;return!1}
function wb(a){1==a.j?(a.j++,rb(a,a.s,!1),a.s="",vb(a,-1,-1),yb(a)):(a.j=0,a.l.length&&Ab(a,a.l.shift()))}kb.prototype.na=function(){this.L=this.S=-1};
function U(a,b,c,d,e){var f=-1,g=-1,l=!1,k=-1,h=-1;if(c<V){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,h=d.targetTouches[0].clientY,l=1<d.targetTouches.length):(k=d.clientX,h=d.clientY);var n=d.target.getBoundingClientRect();k-=n.left;h-=n.top;k=e.dc/b.offsetWidth*k|0;h=e.fc/b.offsetHeight*h|0;var m=k-e.oc;var p=h-e.pc;var q=n=!1;var v=k>=e.eb&&k<e.eb+e.cc&&h>=e.fb&&h<e.fb+e.ec;if(0<=m&&m<e.va&&0<=p+e.$a||v)if(l||a.R||d.preventDefault(),0<=m&&m<e.va&&0<=
p&&p<e.Ba){q=!0;d=e.va/e.wa|0;var w=e.Ba/e.Ea|0,C=m/d|0,x=p/w|0;!a.U||x&1||(m-=d>>1,C=m/d|0,C==e.wa-1&&(m=-1));w=x*w+(e.$a>>1);m-=C*d+(e.bc>>1);p-=w;0<=m&&m<e.Ya&&0<=p&&p<e.Za&&(f=C,g=x,n=!0)}}m=m||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Bb||c==V)for(C=0;C<a.H.length;C++)x=a.H[C],c==V?x.ab(x.id,!1):(w=p/(b/x.Vd|0)|0,(m/(d/x.Ud|0)|0)==x.Yd&&w==x.Zd&&x.ab(x.id,!0));if(!l)if(c==Bb)e.za=k,e.Ha=h,q?(vb(a,f,g),n&&a.f&&zb(a.time,a.T,a.f,!0)):v&&a.J.ea();else if(c==Cb)0<=e.za&&0<=e.Ha&&a.V?vb(a,f,
g):a.u&&a.u(f,g);else if(c==V){if(c=a.f)c=a.time,f=a.T,c=c.a&&0<f&&f<=c.b.length?0<=c.b[f-1].Z:!1;c||vb(a,-1,-1);e.za=e.Ha=-1}else B(a,"unrecognized action: "+c)}function vb(a,b,c){if(b!=a.L||c!=a.S)a.L=b,a.S=c,a.m&&a.m(b,c)}var Bb=1,Cb=2,V=3,pb="surface";y.Input=kb;
function hb(a,b,c){L.call(this,a,b,c,["color","backgroundColor"]);a=this.O[Db];if(!a)throw Error("LED binding for '"+Db+"' missing: '"+this.I.O[Db]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.sa=a;this.type=Ja(E(this,"type",ib,Eb),Fb,Gb);this.f=Hb[this.type][0];this.m=Hb[this.type][1];this.width=E(this,"width",this.f,void 0);this.height=E(this,"height",this.m,void 0);
this.h=E(this,"cols",1,void 0);this.H=this.h+E(this,"colsExtra",0,void 0);this.X=E(this,"rows",1,void 0);this.R=this.X+E(this,"rowsExtra",0,void 0);this.aa=this.width*this.h;this.T=this.height*this.X;this.l=Ib("black",0);this.c=Jb(this.I.color)||this.l;this.ja=Ib(this.c,1,.25);this.ia=Ib(this.c,1,2);this.j=Jb(this.I.backgroundColor);this.oa=E(this,"fixed",!1);this.oa||(b.style.width="100%",b.style.height="auto");this.fa=E(this,"hexagonal",!1);this.pa=E(this,"highlight",!0);this.S=E(this,"persistent",
this.type<Gb);b.setAttribute("width",this.aa.toString());b.setAttribute("height",this.T.toString());b.style.backgroundColor=this.l;a.appendChild(b);this.ba=b.getContext("2d");if(this.s=document.createElement("canvas"))this.s.width=this.$=this.f*this.h,this.s.height=this.u=this.m*this.X,this.b=this.s.getContext("2d");this.qa=(this.R+1)*this.H*4;this.a=Array(this.qa);this.ra=this.h<this.H?4*(this.H-this.h):0;this.K=this.L=!1;this.v=this.V=0;this.U=-1;var d=this;this.time=O(this,"Time");Kb(this.time,
function(e){S(d,!1,e)});jb(d)}t(hb,L);function jb(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Gb?Lb:" ";e[f+1]=d.c==d.l?null:d.c;e[f+2]=0;e[f+3]=T}a.K=a.L=!0;S(a,!0)}function Mb(a){a.j?(a.b.fillStyle=a.j,a.b.fillRect(0,0,a.$,a.u)):a.b.clearRect(0,0,a.$,a.u)}
function S(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.K||b){if(a.type<Gb){var d=0;if(!a.S||b)Mb(a);else if(a.v){d=a.h-a.v;var e=a.f*d;a.b.drawImage(a.s,a.f*a.v,0,e,a.u,0,0,e,a.u)}for(var f=e=0;f<a.R;f++){for(var g=0;g<a.h;g++){var l=a.a[e],k=a.a[e+1]||a.l,h=a.pa&&e==a.U;if(a.a[e+3]&T||h||b){if(g>=d)a:{var n=a,m=l;l=k;var p=g;k=f;var q=h;p=void 0===p?0:p;k=void 0===k?0:k;q=void 0===q?!1:q;var v=0;if(n.fa&&!(k&1)&&(v=n.f>>1,p==n.h-1))break a;if(l&&l!=n.c){q=q?Ib(l,1,2):l;var w=Ib(l,1,.25)}else q=
q?n.ia:n.c,w=n.ja;l=!1;m=m?q:w;q==n.l&&(m=n.j,l=!0);q=p*n.f+v;w=k*n.m;n.S&&(p=p*n.f+v,k*=n.m,n.j?(n.b.fillStyle=n.j,n.b.fillRect(p,k,n.f,n.m)):n.b.clearRect(p,k,n.f,n.m));n.b.fillStyle=m;k=Nb[n.type];3==k.length?(n.b.beginPath(),n.b.arc(q+k[0],w+k[1],k[2],0,2*Math.PI),l?(n.b.globalCompositeOperation="destination-out",n.b.fill(),n.b.globalCompositeOperation="source-over"):n.b.fill()):n.b.fillRect(q+k[0],w+k[1],k[2],k[3])}a.a[e+3]=h?a.a[e+3]|T:a.a[e+3]&~T}e+=4}e+=a.ra}a.v=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&Ob&&(b+=".");Mb(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;h=e;n=f;h=void 0===h?0:h;n=void 0===n?0:n;if(k=Pb[k])for(l=0;l<k.length;l++)if(p=g,v=Qb[k[l]]){m=(void 0===h?0:h)*p.f;q=(void 0===n?0:n)*p.m;p.b.fillStyle=p.c;p.b.beginPath();if(3==v.length)p.b.arc(m+v[0],q+v[1],v[2],0,2*Math.PI);else for(w=0;w<v.length;w+=2)w?p.b.lineTo(m+v[w],q+v[w+1]):p.b.moveTo(m+v[w],q+v[w+1]);p.b.closePath();p.b.fill()}if(++e==a.h&&(e=0,++f==a.R))break}}a.ba.globalCompositeOperation=
a.j&&a.c!=a.l?"source-over":"copy";a.ba.drawImage(a.s,0,0,a.$,a.u,0,0,a.aa,a.T);a.K=!1;a.U=-1}else a.S||a.L||(!c||!a.V||c-a.V>=(1E3/60|0))&&jb(a);a.L=!1;c&&(a.V=c)}function Jb(a){return(a=a||void 0)&&Xa[a]||a}
function Ib(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=Xa[a]||a;var e=a;var f=16;var g=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);g||(f=10,g=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(g){for(e=1;e<g.length;e++)d[e-1]=Number.parseInt(g[e],f);d.length=e-1;f=!0}else f=!1;if(f){a="rgba(";for(f=0;3>f;f++)g=Math.round(d[f]*c),g=0>g?0:255<g?255:g,a+=g+",";a+=(f<d.length?d[f]:b)+")"}}return a}
hb.prototype.ga=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.j&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.l&&(this.a[b+1]=null);S(this,!0);return!0}return!1};hb.prototype.ha=function(a){this.a&&(a.push(this.c),a.push(this.j),a.push(this.a))};
function nb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&Rb;b=4*(c*a.H+b);if(b<=a.a.length-4){if(a.a[b]!==d||(a.a[b+3]&Rb)!==e)a.a[b]=d,a.a[b+3]=a.a[b+3]&~Rb|e|T,a.K=f=!0;a.U=b;a.L=!0;a.v=0}return f}
var Fb=0,ib=1,Gb=3,Eb={small:Fb,round:ib,square:2,digit:Gb},Db="container",Lb=0,ob=1,Rb=129,Ob=1,T=128,Sb={},Nb=(Sb[Fb]=[4,4,4],Sb[ib]=[16,16,14],Sb[2]=[2,2,28,28],Sb),Hb=[[8,8],[32,32],[32,32],[96,128]],Qb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Pb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};y.LED=hb;
function Tb(a,b,c){L.call(this,a,b,c);this.qa=E(this,"cyclesMinimum",1E5,void 0);this.Sa=E(this,"cyclesMaximum",3E6,void 0);this.aa=Ja(E(this,"cyclesPerSecond",65E4,void 0),this.qa,this.Sa);this.V=Ja(E(this,"yieldsPerSecond",Ub,void 0),30,120);this.Ta=Ja(E(this,"yieldsPerUpdate",Vb,void 0),1,this.V);this.oa=(this.L=E(this,"clockByFrame",120>=this.aa))||E(this,"requestAnimationFrame",!0);this.Pa=this.Qa=this.ba=1;this.pa=this.aa/1E4/100;this.l=this.u=this.pa*this.ba;this.H=0;this.fa=Math.round(1E3/
this.V);this.ia=[];this.K=[];this.b=[];this.ja=[];this.sa=this.a=this.X=this.s=!1;this.R=this.h=0;this.Va=this.lc.bind(this);this.Ua=this.Xa.bind(this);this.ra=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);this.j=this.S=this.U=this.T=0;if(this.L)this.f=this.Ra=0;else{var d=this;ub(this,"timerYield",function(){Wb(d)},this.fa)}this.T=this.S=this.j=0;Xb(this)||Yb(this,this.Pa)}t(Tb,L);function Kb(a,b){a.ia.push(b)}r=Tb.prototype;
r.ua=function(a,b){var c=this;switch(a){case Zb:b.onclick=function(){$b(c)&&(c.a?W(c):c.start())};break;case ac:b.onclick=function(){bc(c)};break;case cc:b.addEventListener("mousedown",function(){c.s=!0}),b.addEventListener("mouseup",function(){Xb(c);c.s=!1}),b.addEventListener("mousemove",function(){c.s&&Xb(c)}),b.addEventListener("change",function(){c.s=!0;Xb(c);c.s=!1})}L.prototype.ua.call(this,a,b)};
function ub(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,ac:c,Da:d,Z:-1});0<=d&&zb(a,e,d);return e}r.Xa=function(a){if(this.L){if(!this.a)return;dc(this);try{this.X=!1;do ec(this,fc(this,gc(this,hc(this))));while(this.a&&!this.X)}catch(c){B(this,c.message);W(this);return}ic(this)}for(var b=0;b<this.ia.length;b++)this.ia[b](a);this.a&&this.oa&&this.ra(this.Ua)};function jc(a){var b=a.l/a.pa;if(!b||b>a.ba)b=a.ba;a.yb=a.aa/a.V*b;a.Qa=b}
function gc(a,b){a.S=a.j=b;if(!a.K.length)return a.j=0,a.S;for(var c=0;0<a.j;){if(c<a.K.length){var d=a.K[c++];b=d.mc.call(d,b)||1}else c=b=0;a.j-=b}return a.S-a.j}function kc(a,b){var c=Date.now();b()&&(a.$+=Date.now()-c)}function fc(a,b){b=void 0===b?a.S-a.j:b;if(a.L){if(!a.a){if(a.f)for(var c=0;c<a.K.length;c++){var d=a.K[c];d.nc.call(d)}a.f=b}a.f-=b;1>a.f&&Wb(a)}a.S=a.j=0;a.U+=b;a.T+=b;a.a||(a.T=0);return b}
function hc(a,b){b=void 0===b?0:b;if(b){var c=b;a.f+=b}else for(c=a.f,1>c&&(c=a.f+=a.Ra),0>c&&(a.M("warning: nCyclesDeposited dropped below zero: %f\n",a.f),c=0),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.Z)&&c>d.Z&&(c=d.Z)}return c}function lc(a,b){return Math.ceil(a.aa*a.Qa/1E3*(void 0===b?1E3:b))}function mc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function $b(a){return a.sa?!0:(B(a,"not powered"),!1)}
function ec(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.Z||(d.Z-=b,0>=d.Z&&(d.Z=-1,d.ac(),0<=d.Da&&zb(a,c,d.Da)))}}r.ea=function(a){this.sa=a};function bc(a,b){$b(a)&&(a.a?B(a,"already running"):a.h?W(a):nc(a,b))}
r.lc=function(){this.R=0;if(this.a){dc(this);try{this.X=!1;do{for(var a=lc(this,this.fa),b=this.b.length;0<b;b--){var c=this.b[b-1];!(0>c.Z)&&a>c.Z&&(a=c.Z)}ec(this,fc(this,gc(this,a)))}while(this.a&&!this.X)}catch(d){B(this,d.message);W(this);return}this.a&&(this.R=setTimeout(this.Va,ic(this)),this.oa||this.Xa())}};function Xb(a){var b=a.O[cc];return b?(Yb(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Sa-a.qa)+a.qa)/a.aa),!0):!1}
function Yb(a,b){void 0!==b&&(!a.s&&0<a.l&&a.l<.9*a.u&&(b=a.Pa),a.ba=b,b=a.pa*a.ba,a.u!=b&&(a.u=b,J(a,oc,mc(a.u))),a.l=a.u);a.L&&(a.Ra=1E6*a.l/60+1E-8,a.f=0);a.T=0;a.c=a.m=0;jc(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Da&&zb(a,b,c.Da,!0)}}function zb(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.Z)&&(c=lc(a,c),a.a&&(c+=fc(a)),b.Z=c)}function dc(a){jc(a);a.U=0;a.$=0;a.v=Date.now();a.c||(a.c=a.v);if(a.m){var b=a.v-a.m;b>a.fa&&(a.c+=b,a.c>a.v&&(a.c=a.v))}}
function ic(a){a.m=Date.now();a.$&&(a.c+=a.$,a.v+=a.$);var b=a.fa;a.U&&(b=Math.round(b*a.U/a.yb));b-=a.m-a.v;var c=a.m-a.c;c&&(a.l=a.T/(10*c)/100);0>b?(-1E3>b&&(a.c-=b),b=0):a.l<a.u&&(b=0);a.m+=b;a.M(4096,"after running %d cycles, resting for %dms\n",a.U,b);return b}r.start=function(){if(this.a||this.h)return!1;this.R&&(clearTimeout(this.R),this.R=0);this.a=!0;this.c=this.m=0;this.update(!0);this.L||(this.R=setTimeout(this.Va,0));this.oa&&this.ra(this.Ua);return!0};
function nc(a,b){b=void 0===b?1:b;a.a||(b&&!a.h&&(a.h=b),a.h&&(a.h--,ec(a,fc(a,gc(a,hc(a,1)))),a.update(!1),a.h&&setTimeout(function(){nc(a,0)},0)))}function W(a){return a.h?(a.h=0,a.update(!0),!0):a.a?(a.a=!1,fc(a),a.update(!0),!0):!1}
r.update=function(a){a&&(this.a?B(this,"started with "+mc(this.u)+" target"):B(this,"stopped"));J(this,Zb,this.a?"Halt":"Run");J(this,ac,this.h?"Stop":"Step");this.s||J(this,oc,this.a&&this.l?mc(this.l):"Stopped");for(var b=0;b<this.ja.length;b++){var c=this.ja[b];c.hc.call(c,void 0!=a)}};function Wb(a){a.X=!0;var b=a.H,c=lc(a);c>=a.V?a.H++:a.H+=Math.ceil(a.V/c);a.H>=a.Ta&&b<a.Ta&&a.update();a.H>=a.V&&(a.H=0)}var Zb="run",oc="speed",ac="step",cc="throttle",Ub=120,Vb=60;y.Time=Tb;
function X(a,b,c){L.call(this,a.w,b);this.Y=a;this.name=b;this.g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.fa[c]=[this,-1];for(var d=0;d<this.g.length;d++)c=this.N("reg%s-%02d",this.name,d),b.push(c),a.fa[c]=[this,d];Ea(a,b)}}t(X,L);r=X.prototype;r.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.g[f]=a.g[f]+b.g[f]+e,e=0,this.g[f]>=d&&(this.g[f]-=d,e=1);e&&(this.Y.l=!0);pc(this,c)};r.get=function(){return this.g};
function qc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.g.length;d++)a.g[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.g[d]=b&15,b>>>=4;return a}r.move=function(a,b){for(var c=b[0],d=b[1];c<=d;c++)this.g[c]=a.g[c];pc(a,b)};r.set=function(a){if(a&&a.length==this.g.length)for(var b=0;b<this.g.length;b++)this.g[b]=a[b]};r.store=function(a){for(var b=0,c=this.g.length;b<c;b++)this.g[b]=a.g[b]};
r.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.g[f]=a.g[f]-b.g[f]-e,e=0,0>this.g[f]&&(this.g[f]+=d,e=1);e&&(this.Y.l=!0);pc(this,c)};r.toString=function(a){a=void 0===a?!1:a;var b=this.W+"=";a&&3>b.length&&(b+=" ");for(var c=this.g.length-1;0<=c;c--)b=a?b+ya[this.g[c]]:b+(za[this.g[c]]+(c%4?"":" "));return b};function pc(a,b){a.Y.j=a.g[b[0]];b[0]<b[1]&&(a.Y.j|=a.g[b[0]+1]<<4)}
function rc(a,b,c){L.call(this,a,b,c);this.type=Number.parseInt(E(this,"type","1501").slice(-4),10);this.fa={};this.a=Array(4);for(a=0;4>a;a++)this.a[a]=new X(this,String.fromCharCode(65+a));this.K=this.a[0];this.S=this.a[1];this.qa=this.a[2];this.sa=this.a[3];this.v=Array(8);for(a=0;8>a;a++)this.v[a]=new X(this,"X"+a);this.L=Array(8);for(a=0;8>a;a++)this.L[a]=new X(this,"Y"+a);this.ja=new X(this,"Supp",!0);this.U=new X(this,"Temp",!0);this.u=10;this.l=!1;this.T=this.ia=this.b=this.j=this.m=0;this.h=
[-1,-1,-1];this.pa=this.s=0;this.ra=N(this,this.I.input);this.ra.m=this.kb.bind(this);this.f=N(this,this.I.output,!1);this.oa=O(this,"Bus");this.c=O(this,"ROM");(this.time=O(this,"Time"))&&this.c&&(this.time.K.push(this),this.time.ja.push(this));this.aa=this.ba=this.R=void 0;this.$=this.V=-1;this.H={};this.X=sc;a=this.gc.bind(this);b=Qa.Oa;this.J.Fa[b]||(this.J.Fa[b]=[]);this.J.Fa[b].push(a)}t(rc,L);function tc(a,b){a.H[b]&&(a.H[b]=!1,B(a,"break on "+uc[b]),W(a.time))}
function vc(a){a.f&&jb(a.f);if(a.c){var b=a.c;b.a&&jb(b.a)}wc(a,!1)}r=rc.prototype;r.mc=function(a){for(this.pa=this.s=a=void 0===a?0:a;0<this.s;){if(this.$==this.b){this.$=-1;B(this,"break");W(this.time);break}var b=this.oa.ya(this.b);this.b=(this.ia=this.b)+1&this.oa.m;if(void 0==b||!xc(this,b)){this.b=this.ia;B(this,"unimplemented opcode");W(this.time);break}this.s-=yc}if(0>=a){var c=this;kc(this.time,function(){var d=c.c;d.a&&S(d.a);c.ka(c.toString())})}return this.pa-this.s};
r.nc=function(){this.s=0};
function xc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.l&&(a.b=a.b&1024|b&1023):(a.push(a.b),a.b=b&2047),a.l=!1,!0;var c;var d=b&zc;switch(d){case Ac:case Bc:case Cc:case Dc:case Ec:case Fc:case Gc:case Hc:case Ic:case Jc:case Kc:case Lc:d=Mc[d];var e=(b&Nc)>>Oc;var f=(b&Pc)>>Qc;var g=(b&Rc)>>Sc;var l=(c=b&Tc)?Uc:Vc;switch(f){case 0:case 1:case 2:case 3:var k=a.a[f];break;case 4:k=qc(a.U,1,d);break;case 5:l=c?Wc:Xc;break;case 6:k=qc(a.U,a.j&15,d);break;case 7:k=qc(a.U,a.j&255,d)}switch(g){case 0:var h=
a.a[e];break;case 1:h=4>f?a.a[f]:void 0;break;case 2:h=5>f?a.ja:5==f?a.a[e]:void 0;break;case 3:if(c)a.a[e].move(k,d);else{a=a.K;e=k;b=d[0];for(k=d[1];b<=k;b++)h=a.g[b],a.g[b]=e.g[b],e.g[b]=h;pc(e,d)}return!0}if(!h)break;b=b>=Hc?16:a.u;switch(l){case Vc:h.add(a.a[e],k,d,b);break;case Uc:h.sub(a.a[e],k,d,b);break;case Xc:b=h;a=a.a[e];e=d[1];for(k=d[0];e>k;e--)b.g[e]=a.g[e-1];b.g[e]=0;pc(b,d);break;case Wc:b=h;a=a.a[e];e=d[0];for(k=d[1];e<k;e++)b.g[e]=a.g[e+1];b.g[e]=0;pc(b,d)}return!0;case Yc:e=(b&
Zc)>>$c;d=(b&ad)>>bd;k=1<<((b&cd)>>dd);if(!d)break;d+=12;switch(b&ed){case fd:a.a[e].g[d]|=k;break;case gd:a.a[e].g[d]&=~k;break;case hd:a.a[e].g[d]&k&&(a.l=!0);break;case id:a.a[e].g[d]^=k}return!0;case jd:switch(b&kd){case ld:a.K.store(a.L[a.m]);break;case md:a.m=b>>4&7;break;case nd:a.b=a.j;break;case od:a.l=!1;d=a.h[0];e=0;for(b=a.h.length-1;e<b;)a.h[e]=a.h[++e];a.h[e]=-1;a.b=d;break;case pd:a.v[a.m].store(a.K);break;case qd:a.K.store(a.v[a.m]);break;case rd:a.L[a.m].store(a.K);break;case sd:tc(a,
"o");if(a.f){d=0;for(e=11;0<=e;d++,e--)b=void 0,a.S.g[e]&8?b=" ":a.S.g[e]&1?b="-":b=ya[a.K.g[e]],nb(a.f,d,0,b,a.S.g[e]&2?Ob:0)&&tc(a,"om");wc(a)}a.s-=31*yc;a.T&&(a.j=a.T,a.l=!0,tc(a,"i"));break;case td:a.u=10;break;case ud:a.u=16;break;case vd:a.m=a.j&7;break;default:return!1}return!0}return!1}
r.ga=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return B(this,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.M("saved state version mismatch: %3.2f\n",c),!1;try{this.a.forEach(function(d){return d.set(b.shift())}),this.v.forEach(function(d){return d.set(b.shift())}),this.L.forEach(function(d){return d.set(b.shift())}),this.ja.set(b.shift()),this.U.set(b.shift()),this.u=b.shift(),this.l=b.shift(),this.m=b.shift(),this.j=b.shift(),this.b=b.shift(),this.h=b.shift(),this.T=
b.shift()}catch(d){return B(this,"CPU state error: "+d.message),!1}return(a=a.stateROM||a[1])&&this.c&&!this.c.ga(a)?!1:!0};
r.gc=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,l=3;l<a.length;l++)d.push(Number.parseInt(a[l],16));this.X=sc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in uc)c=uc[f],b+="break on "+c+" (b"+f+"): "+(this.H[f]||!1)+"\n";break}(c=uc[f])?(this.H[f]=!this.H[f],b="break on "+c+" (b"+f+"): "+this.H[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.c.values[f];if(void 0==
a)break;this.c.values[f]=d[g];b+=this.N("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.N("%d locations updated\n",c);break;case "g":this.time.start()?this.$=f:b="already started\n";break;case "h":W(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.X=wd);g=Number.parseInt(a[2],10)||1;bc(this.time,g);break;case "r":"c"==e[1]&&(this.X=wd);this.cb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.V?this.V:this.b;g--;){c=this.c&&this.c.values[f];if(void 0==
c)break;b+=mb(this,f++,c)}this.V=f;break;case "?":b="additional commands:\n";xd.forEach(function(k){b+=k+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};r.kb=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.T=c};r.La=function(a){return a&&this.ga(a)?!0:!1};r.ea=function(a){a?this.time.start():(W(this.time),vc(this))};r.na=function(){B(this,"reset");this.b=0;var a=this.c;a.values=a.I.values;vc(this);this.time.a||this.ka(this.toString())};r.Ma=function(a){this.ha(a)};
r.hc=function(a){for(var b in this.O){var c=this.fa[b];if(c){var d=c[0];c=c[1];J(this,b,0>c?d.toString():ya[d.g[c]])}}a&&!this.time.a&&(a=this.c,a.a&&S(a.a),this.ka(this.toString()))};r.push=function(a){for(var b=this.h.length-1;0<b;)this.h[b]=this.h[--b];this.h[0]=a};
r.ha=function(a){var b=[],c=[];b.push(2);this.a.forEach(function(d){return b.push(d.get())});this.v.forEach(function(d){return b.push(d.get())});this.L.forEach(function(d){return b.push(d.get())});b.push(this.ja.get());b.push(this.U.get());b.push(this.u);b.push(this.l);b.push(this.m);b.push(this.j);b.push(this.b);b.push(this.h);b.push(this.T);this.c&&this.c.ha(c);a.push(b);a.push(c)};r.cb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.b=b;break;default:B(this,"unrecognized register: "+a)}};
function mb(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.N("%#06x",f);else if(0<=c){var g=c&zc;var l;switch(g){case Ac:case Bc:case Cc:case Dc:case Ec:case Fc:case Gc:case Hc:case Ic:case Jc:case Kc:case Lc:f="";e=Mc[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&Nc)>>Oc;var k=(c&Pc)>>Qc;var h=(c&Rc)>>Sc;var n=c&Tc;e="LOAD";var m=l="?";var p=n?5==k?">>":"-":5==k?"<<":"+";switch(h){case 0:l=
Y[g];break;case 1:4>k&&(l=Y[k]);break;case 2:6>k&&(l="NUL");break;case 3:n?(e="MOVE",l=Y[g],m=Y[k]):(e="XCHG",g||(l="A"),4>k&&(m=Y[k])),k=-1}switch(k){case 0:case 1:case 2:case 3:m=Y[g]+p+Y[k];break;case 4:case 5:m=Y[g]+p+"1";break;case 6:m=Y[g]+p+"R5L";break;case 7:m=Y[g]+p+"R5"}f=l+","+m+","+f;break;case Yc:switch(c&ed){case fd:e="SET";break;case gd:e="CLR";break;case hd:e="TST";break;case id:e="NOT"}f=a.a[(c&Zc)>>$c].name;g=(c&ad)>>bd;f+="["+(g?g+12:"?")+":"+((c&cd)>>dd)+"]";break;case jd:switch(c&
kd){case ld:e="STORE";f="A,Y[RAB]";break;case md:e="STORE";f="RAB,"+((c&112)>>4);break;case nd:e="BR";f="R5";break;case od:e="RET";break;case pd:e="STORE";f="X[RAB],A";break;case qd:e="STORE";f="A,X[RAB]";break;case rd:e="STORE";f="Y[RAB],A";break;case sd:e="DISP";break;case td:e="BCDS";break;case ud:e="BCDR";break;case vd:e="STORE",f="RAB,R5L"}}}return a.N(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
r.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.X){this.c&&(d+=mb(this,this.b,this.c.values[this.b],!0));d+="  ";b=0;for(a=this.a.length;b<a;b++)d+=this.a[b].toString()+" ";d+="\n ";d+=" COND="+(this.l?1:0);d+=" BASE="+this.u;d+=" R5="+this.N("%02X",this.j);d+=" RAB="+this.m+" ST=";this.h.forEach(function(f){d+=c.N("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=
this.toString(a,this.a);0<=a.indexOf("a")&&(d+=this.toString(a,this.v),d+=this.toString(a,this.L));d+="COND="+(this.l?1:0);d+=" BASE="+this.u;d+=" R5="+this.N("%#04x",this.j);d+=" RAB="+this.m+" ";this.h.forEach(function(f,g){d+=c.N("ST%d=%#06x ",g,f&65535)});this.c&&(d+="\n"+mb(this,this.b,this.c.values[this.b]));this.V=this.b;return d};
function wc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==yd?!!(a.qa.g[14]&8):!!(a.S.g[15]&4));if(a.aa!==d){if(c=a.O["2nd"])c.style.opacity=d?"1":"0",void 0===a.aa&&a.f&&(c.style.color=a.f.color);a.aa=d}d=b&&(a.type==yd?!!(a.S.g[15]&4):!!(a.sa.g[15]&8));if(a.ba!==d){if(c=a.O.INV)c.style.opacity=d?"1":"0",void 0===a.ba&&a.f&&(c.style.color=a.f.color);a.ba=d}c=a.type==yd?a.v[4].g[15]>>2:a.qa.g[15];b=b?c?1==c?zd:Ad:Bd:Cd;if(a.R!==b){if(c=a.O.Deg)c.style.opacity=b==Bd?"1":"0",void 0===a.R&&a.f&&(c.style.color=
a.f.color);if(c=a.O.Rad)c.style.opacity=b==zd?"1":"0",void 0===a.R&&a.f&&(c.style.color=a.f.color);if(c=a.O.Grad)c.style.opacity=b==Ad?"1":"0",void 0===a.R&&a.f&&(c.style.color=a.f.color);a.R=b}}
var zc=3840,Ac=0,Bc=256,Cc=512,Dc=768,Ec=1024,Fc=1280,Gc=1792,Hc=2048,Ic=2304,Jc=2560,Yc=3072,Kc=3328,jd=3584,Lc=3840,Nc=192,Oc=6,Pc=56,Qc=3,Rc=6,Sc=1,Tc=1,ed=3,fd=0,gd=1,hd=2,id=3,Zc=192,$c=6,ad=48,bd=4,cd=12,dd=2,kd=15,ld=0,md=1,nd=2,od=3,pd=4,qd=5,rd=6,sd=7,td=8,ud=9,vd=10,Z={},Mc=(Z[Ac]=[12,12],Z[Bc]=[0,15],Z[Cc]=[2,12],Z[Dc]=[0,12],Z[Ec]=[2,2],Z[Fc]=[0,1],Z[Gc]=[0,13],Z[Hc]=[14,14],Z[Ic]=[13,15],Z[Jc]=[14,15],Z[Kc]=[13,13],Z[Lc]=[15,15],Z),yc=128,Vc=0,Uc=1,Xc=2,Wc=3,yd=1501,Cd=0,Bd=1,zd=2,Ad=
3,uc={i:"input",o:"output",om:"output modification"},sc=0,wd=1,Y="A B C D 1 ? R5L R5".split(" "),xd="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");y.CPU=rc;
function Dd(a,b,c){L.call(this,a,a);var d=this;this.f=this.a=!1;this.m=c;this.b="";this.l=this.j=!1;this.ca=262144;b=b.trim();"{"==b[0]?Ed(this,b):(this.b=b,Ka(this.b,function(e,f,g,l){4==g&&(!l&&f?(Ed(d,f),Fd(d)):d.M("error (%d) loading configuration: %s\n",l,e))}));window.addEventListener("load",function(){d.l=!0;Fd(d)});window.addEventListener(Ma("iOS")?"pagehide":Ma("Opera")?"unload":"beforeunload",function(){Gd(d)});window.addEventListener("pageshow",function(){d.f||d.ea(!0)})}t(Dd,L);
Dd.prototype.ua=function(a,b){var c=this;switch(a){case Hd:b.onclick=function(){c.a&&c.ea()};break;case Id:b.onclick=function(){c.a&&c.na()}}L.prototype.ua.call(this,a,b)};
function Fd(a){var b=!0;if(a.j&&a.l){for(var c in a.c){var d=void 0;try{var e=a.c[c];d=e["class"];y[d]?"Machine"==d?(a.M("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,Jd,Kd),a.b&&a.M("Configuration: %s\n",a.b)):new y[d](a.w,c,e):a.M("unrecognized %s device class: %s\n",c,d)}catch(g){a.M("error initializing %s device '%s': %s\n",d,c,g.message),bb(a,c),b=!1}}if(a.h){var f=Na(a);$a(a,function(g){return g.La&&!g.La(f)?(g.M("unable to restore state for device: %s\n",g.W),!1):!0})}a.ea(b)}}
function Gd(a){if(a.h){var b=[];$a(a,function(c){c.Ma&&c.Ma(b);return!0});Ua(a,b)}a.ea(!1)}function Ed(a,b){try{a.c=JSON.parse(b);Za(a,a.c[a.w],["autoSave","autoStart"]);a.h=!1!==a.I.autoSave;a.s=!1!==a.I.autoStart;if(a.m){var c=eval("("+a.m+")"),d;for(d in c)a.I[d]=c[d]}a.j=!0}catch(e){c=e.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),B(a,"machine '"+a.w+"' initialization error: "+c)}}
Dd.prototype.ea=function(a){a=void 0===a?!this.f:a;var b=this;a&&B(this,"power on");$a(this,function(c){c.ea&&c!=b&&("CPU"!=c.I["class"]||b.s||b.a?c.ea(a):c.time.update(!0));return!0});this.a=!0;(this.f=a)||B(this,"power off")};Dd.prototype.na=function(){var a=this;$a(this,function(b){b.na&&b!=a&&b.na();return!0})};var Hd="power",Id="reset",Jd="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",Kd="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";
window.TMS1500=function(a,b,c){var d=new Dd(a,b,c);window.command=function(e){return Oa(d,e)};return d};y.Machine=Dd;})()

//# sourceMappingURL=ti42.js.map
