(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu/tms1500.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/main/machine.js (C) Jeff Parsons 2012-2019
*/
var r;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={bc:!0},ha={};try{ha.__proto__=fa;ea=ha.bc;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function t(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Zd=b.prototype}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},u="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ka(a,b){if(b){var c=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}ka("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ka("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});ka("Number.parseInt",function(a){return a||parseInt});
function la(){la=function(){};u.Symbol||(u.Symbol=ma)}function na(a,b){this.a=a;ja(this,"description",{configurable:!0,writable:!0,value:b})}na.prototype.toString=function(){return this.a};var ma=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new na("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function oa(){la();var a=u.Symbol.iterator;a||(a=u.Symbol.iterator=u.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}});oa=function(){}}function pa(a){oa();a={next:a};a[u.Symbol.iterator]=function(){return this};return a}
function qa(a,b){oa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ka("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});
ka("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});var ra=new ArrayBuffer(2);(new DataView(ra)).setUint16(0,256,!0);new Uint16Array(ra);function sa(){}var y={};y.Defs=sa;function ta(){}t(ta,sa);function ua(a,b){var c=a/z|0,d=b/z|0;return(a&b)==(b|0)&&(c&d)==d}var z=Math.pow(2,32);y.NumIO=ta;function A(){}t(A,ta);r=A.prototype;
r.flush=function(){var a=va;va="";this.ja(a)};r.kc=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};r.ja=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(va+a.substr(0,b)),va="",a=a.substr(b+1)));va+=a;return a.length};function B(a,b,c){a.ja(b+"\n",c)}
r.L=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.ja(this.N.apply(this,[a].concat(ba(c))))};
r.N=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*|~)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var l=e[g+5],k="ACDFHIMNSTWYbdfjcsoXx%".indexOf(l);if(0>k)d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+l;else{if(f<c.length){var h=c[f];"%"!=l&&f++}else h=c[c.length-1];var n=e[g+1],m=0<=n.indexOf("#"),p=0<=n.indexOf("0"),q=e[g+2];"*"==q||"~"==q?(q="~"==q?(h>>2)+(!m||"x"!=l&&"X"!=l?0:2):h,h=f<c.length?c[f++]:c[c.length-
1]):q=+q||0;var v=e[g+3];v=v?+v.substr(1):-1;var w=null,C=0,x="";k=12>k&&"object"!=typeof h?this.kc(h):h;switch(l){case "C":h=m?"#":"";d+=isNaN(k.getTime())?void 0:this.N(this.N("%%%sW, %%%sF %%%sD, %%%sY",h),k);continue;case "D":h=m?k.getUTCDate():k.getDate();l="d";break;case "A":case "H":case "I":h=m?k.getUTCHours():k.getHours();"A"==l?(h=12>h?"am":"pm",l="s"):("I"==l&&(h=h?12<h?h-12:h:12),l="d");break;case "F":case "M":h=m?k.getUTCMonth():k.getMonth();"F"==l?(h=wa[h],l="s"):(h++,l="d");break;case "N":h=
m?k.getUTCMinutes():k.getMinutes();l="d";break;case "S":h=m?k.getUTCSeconds():k.getSeconds();l="d";break;case "T":h=m?"#":"";d+=isNaN(k.getTime())?void 0:this.N(this.N("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),k);continue;case "W":h=xa[m?k.getUTCDay():k.getDay()];l="s";break;case "Y":h=m?k.getUTCFullYear():k.getFullYear(),0<v&&(h%=Math.pow(10,v),v=-1),l="d"}switch(l){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h);case "f":h=+h;l=h+"";0<=v&&(l=h.toFixed(v));l.length<q&&(p?(0>
h&&(q--,l=l.substr(1)),l=("0000000000"+l).slice(-q),0>h&&(l="-"+l)):l=("          "+l).slice(-q));d+=l;break;case "j":d+=JSON.stringify(h,null,q||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!==h)for("string"!=typeof h&&(h=h.toString()),0<=v&&(h=h.substr(0,v));h.length<q;)h=0<=n.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":C=8,m&&(x="0");case "X":w=ya;case "x":l="";C||(C=16);!x&&m&&(x="0x");w||(w=za);"string"==typeof h&&(h=Number.parseInt(h,h.match(/(^0x|[a-f])/i)?
16:10));p&&!q&&(q=Math.abs(h),q=255>=q?2:65535>=q?4:4294967295>=q?8:9,q+=x.length);q-=x.length;do m=h&C-1,h>>>=16==C?4:3,p||!l||m||h?l=w[m]+l:(x&&(l=x+l,x=""),0<q&&(l=" "+l));while(0<--q||h);d+=x+l;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+l+")"}}}return d+=e[g]};var va="",za="0123456789abcdef",ya="0123456789ABCDEF",xa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),wa="January February March April May June July August September October November December".split(" ");
y.StdIO=A;function D(a){this.O={};this.ca=0;this.I=this;a&&(this.I.ca=0,this.I.ka=[],this.I.da=0,this.I.Ea={},this.I.Fd=!1)}var Aa;t(D,A);D.prototype.ta=function(a,b){var c=this;switch(a){case Ba.lb:b.onclick=function(){var d=c.wa(Ba.Ja,!0);d&&(d.value="")};break;case Ba.Ja:Ca(b),b.addEventListener("keydown",function(d){Da(c,d,!0)}),b.addEventListener("keypress",function(d){Da(c,d)})}};
function Ea(a,b){b=void 0===b?{}:b;var c=Array.isArray(b);b.container||(b.container=a.X);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.O[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.O[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.O[d]=f,a.ta(d,f)}}function Ca(a){a.value="";a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false")}D.prototype.wa=function(a){return this.O[a]};
function Fa(a){var b=Ga;return a.M.bindings&&a.M.bindings[b]}function Ha(a){if(a=a.O[Ia])var b=a.textContent;return b}function Ja(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}function E(a,b,c,d){a=a.M[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Ka(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function La(a){if(void 0===F.Ha){var b=!1;if(window)try{window.localStorage.setItem(F.sa,F.sa),b=window.localStorage.getItem(F.sa)==F.sa,window.localStorage.removeItem(F.sa)}catch(c){B(a,c.message),b=!1}F.Ha=b}return!!F.Ha}function G(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ca;return-1==(b|1)||ua(a.I.ca,b)?!0:!1}
function Ma(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Na(a){var b=null;if(La(a)){var c;if(window)try{(c=window.localStorage.getItem(a.w))&&(b=JSON.parse(c))}catch(d){B(a,d.message)}}return b}
function Da(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.I,f=b.target;if(c){a=!1;var g;c=f.value;var l=c.lastIndexOf("\n");d==H.Oa&&f.selectionStart<=l+1&&(a=!0);d==H.Vb?(a=!0,0<e.da&&(g=e.ka[--e.da])):d==H.pb&&(a=!0,e.da<e.ka.length&&(g=e.ka[++e.da]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,l+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.da&&c+1==g.length&&
(f.value+=e.ka[--e.da],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Oa(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&B(a,b.replace(/\n$/,""),!1))}}
function Pa(a,b){if(void 0!=b){var c=a.I;try{if(b=b.trim())c.da<c.ka.length&&b==c.ka[c.da]?c.da++:(c.ka.push(b),c.da=c.ka.length);var d=b.split(" "),e=d[0],f=a.I.Ea[Qa.Pa];switch(e[0]){case "m":if("?"==e[1]){var g="";Ra.forEach(function(m){g+=m+"\n"});g&&(g="message commands:\n"+g);break}g="";var l=void 0;e=d[d.length-1].toLowerCase();var k="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(l=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(I));for(f=
1;f<d.length;f++){e=d[f];var h=I[e];if(!h){g+="unrecognized message: "+e+"\n";break}void 0!=k&&Sa(a,h,k);if(void 0==l||l==G(a,h))g+=a.N("%8s: %b\n",e,G(a,h))}G(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ta.forEach(function(m){g+=m+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var n=f[a](d);if(void 0!=n){g=g?g+n:n;break}}}}catch(m){g="error: "+m.message+"\n"}}return g}
function Oa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Pa(a,b[d])}return c}D.prototype.ja=function(a,b){void 0==b&&(b=G(this,0x800000000000));if(!b){var c=this.wa(Ba.Ja,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Ma("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return A.prototype.ja.call(this,a,b)};
D.prototype.L=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return G(this,d)?A.prototype.L.call.apply(A.prototype.L,[this,a].concat(ba(c))):0};function Ua(a,b){if(La(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.w,b)}catch(c){B(a,c.message)}}}function J(a,b,c){if(a=a.O[b])a.textContent=c}
function Sa(a,b,c){var d=!1;c?(c=a.I.ca,a.I.ca=(c|b)+(c/z|0|b/z|0)*z):(d=ua(a.I.ca,0x800000000000)&&ua(b,0x800000000000),c=a.I.ca,a.I.ca=(c&~b)+((c/z|0)&~(b/z|0))*z);d&&a.flush()}
var Ba={lb:"clear",Ja:"print"},Ta=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Ra=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],I={all:0xffffffffffff,buffer:0x800000000000},Qa={Pa:"command"},H={Oa:8,Rb:9,Cb:10,nb:13,Rd:16,yc:17,sc:18,Gd:19,vc:20,Dc:27,Pb:32,Jd:33,Id:34,Bc:35,bd:36,Bb:37,Vb:38,Lb:39,
Yc:39,pb:40,Tc:44,Kd:44,cd:45,Ac:46,Xc:46,ad:47,ZERO:48,ONE:49,Tb:50,Sb:51,tb:52,sb:53,Ob:54,Nb:55,qb:56,Hb:57,$c:59,Vc:61,ib:65,jb:66,kb:67,ob:68,E:69,rb:70,ub:71,vb:72,wb:73,xb:74,yb:75,Ab:76,Eb:77,Gb:78,Ib:79,Jb:80,Q:81,Kb:82,Mb:83,Qb:84,Ub:85,Wb:86,Yb:87,Zb:88,$b:89,ac:90,wc:91,Wc:91,Rc:92,Nd:93,Zc:93,ed:96,wd:96,Qc:96,fd:97,ud:97,gd:98,td:98,hd:99,Ad:99,jd:100,xd:100,kd:101,qd:101,ld:102,Cd:102,md:103,vd:103,nd:104,Ed:104,od:105,Bd:105,zd:106,pd:107,Dd:109,rd:110,sd:111,Ec:112,Ic:113,Jc:114,
Kc:115,Lc:116,Mc:117,Nc:118,Oc:119,Pc:120,Fc:121,Gc:122,Hc:123,yd:144,Pd:145,Uc:173,Qd:186,Cc:187,xc:188,zc:189,Hd:190,Sd:191,tc:192,dd:219,uc:220,Md:221,Ld:222,Sc:224,Td:1E3},K={},Va=(K[H.Oa]="\b",K[H.Rb]="\t",K[H.Cb]="\n",K[H.nb]="\r",K[H.Pb]=" ",K[H.ZERO]="0",K[H.ONE]="1",K[H.Tb]="2",K[H.Sb]="3",K[H.tb]="4",K[H.sb]="5",K[H.Ob]="6",K[H.Nb]="7",K[H.qb]="8",K[H.Hb]="9",K[H.ib]="A",K[H.jb]="B",K[H.kb]="C",K[H.ob]="D",K[H.E]="E",K[H.rb]="F",K[H.ub]="G",K[H.vb]="H",K[H.wb]="I",K[H.xb]="J",K[H.yb]="K",
K[H.Ab]="L",K[H.Eb]="M",K[H.Gb]="N",K[H.Ib]="O",K[H.Jb]="P",K[H.Q]="Q",K[H.Kb]="R",K[H.Mb]="S",K[H.Qb]="T",K[H.Ub]="U",K[H.Wb]="V",K[H.Yb]="W",K[H.Zb]="X",K[H.$b]="Y",K[H.ac]="Z",K[H.Bb]="Left",K[H.Lb]="Right",K),Wa={list:[],Xb:"version"},Xa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",
chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",
deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",
lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",
mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",
red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},F={Ha:void 0,
sa:"PCjs.localStorage"};y.WebIO=D;function L(a,b,c,d){D.call(this,a==b);this.w=a;this.X=b;M[this.w]||(M[this.w]={});M[this.w][this.X]&&this.L("warning: machine configuration contains multiple '%s' devices\n",this.X);M[this.w][this.X]=this;this.id=this.w+"."+this.X;Ya.push(this);this.I=N(this,this.w);Za(this,c,d);this.Fb={}}t(L,D);
function Za(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d,e=Aa;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,l=/([^&=]+)=?([^&]*)/g;f=l.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Aa=e}d=e;for(var k in d)0<=c.indexOf(k)&&(f=d[k],f.match(/^[+-]?[0-9.]+$/)?e=Number.parseInt(f,10):"true"==f?e=!0:"false"==f?e=!1:(e=f,f='"'+f+'"'),b[k]=e,B(a,"overriding "+a.X+" property '"+
k+"' with "+f))}a.M=b;Ea(a,b.bindings);b=void 0===b?{}:b;a.version=2;if(a.version){c="";var h;a.w!=a.X&&(h=N(a,a.w).version)&&h!=a.version&&(c="Machine");c||(h=b.version)&&h>a.version&&(c="Config");c&&(h="Error: "+a.N("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.Vd,a.version,c,h)+"\n\nClearing your browser's cache may resolve the issue.",(b=Wa.Xb)&&0>Wa.list.indexOf(b)&&(alert(h),Wa.list.push(b)),B(a,h))}}
function $a(a,b){var c;try{var d=M[a.w];if(d)for(c in d){var e=d[c];if("Machine"!=e.M["class"]&&!b(e))break}}catch(f){a.L("error while enumerating device '%s': %s\n",c,f.message)}}L.prototype.wa=function(a,b){b=void 0===b?!1:b;if(a){var c=D.prototype.wa.call(this,a,b);if(void 0===c&&b){b=M[this.w];for(var d in b)if(c=b[d].O[a])break;c||(c=null);this.O[a]=c}}return c};
function N(a,b,c){var d=b,e=a.w,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=M[e])&&f[b]||null;if(!b){for(f=0;f<Ya.length;f++)if(Ya[f].id===d){b=Ya[f];break}if(!b&&(void 0===c||c))throw Error(a.N("unable to find device with ID '%s'",d));}return b}function O(a,b,c){var d=null,e=M[a.w];if(e)for(var f in e)if(e[f].M["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.N("unable to find device with class '%s'",b));return d}
L.prototype.L=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&G(this,a)&&(void 0===this.ra&&(this.ra=O(this,"Debugger")),this.I.ca&ab&&(void 0===this.Y&&(this.Y=O(this,"CPU")),this.Y))?(a=c.shift(),D.prototype.L.call(this,"%#06x: %s.%s\n",this.Y.Na,this.X,this.N.apply(this,[a].concat(ba(c))).trim())):D.prototype.L.call.apply(D.prototype.L,[this,a].concat(ba(c)))};function bb(a,b){(a=M[a.w])&&delete a[b]}
L.prototype.fb=function(a,b){(a=this.Fb[a])&&a.set(b)};var M={},Ya=[],ab=1;I.addr=ab;I.bus=2;I.memory=4;I.ports=8;I.chips=16;I.kbd=32;I.serial=64;I.misc=128;I.cpu=256;I.video=512;I.monitor=1024;I.screen=2048;I.timer=4096;I.event=8192;I.input=16384;I.key=32768;I.mouse=65536;I.touch=131072;I.warn=262144;I.halt=524288;window&&(window.PCjs||(window.PCjs={}),M=window.PCjs.Machines||(window.PCjs.Machines={}),Ya=window.PCjs.Components||(window.PCjs.Components=[]));y.Device=L;
function cb(a,b,c){L.call(this,a,b,c);this.type="static"==c.type?db:eb;this.h=c.addrWidth||16;this.c=Math.pow(2,this.h);this.m=this.c-1|0;this.a=c.blockSize||(16<this.h?4096:1024);this.a>this.c&&(this.a=this.c);this.u=this.c/this.a|0;this.j=Math.log2(this.a)|0;this.s=(1<<this.j)-1;this.l=c.dataWidth||8;this.b=Array(this.u);this.f=0;a=new P(a,b+"[NONE]",{size:this.a,bus:this.X});for(b=0;b<this.c;b+=this.a)fb(this,b,this.a,Q.NONE,a);a=this.f;this.f+=this.type;a&&this.f||(this.xa=this.lc)}t(cb,L);
function fb(a,b,c,d,e){for(var f=0,g=b>>>a.j;0<c&&g<a.b.length;){var l=g*a.a,k=a.a-(b-l);k>c&&(k=c);var h=a.b[g];if(b!=l||k!=a.a||h&&h.type!=Q.NONE)break;var n=h=void 0,m=b,p=a.h,q=16;p=void 0===p?0:p;h=void 0===h?0:h;var v="",w="",C=-1;q||(q=a.v||10);p&&(C=Math.ceil(p/Math.log2(q)));if(void 0==n)switch(q){case 8:n="0o";break;case 16:n="0x";break;case 10:w=".";default:n=""}isNaN(m)||"number"!=typeof m?(m=void 0,n=w=""):(0>m&&-1<m&&(m=-1),p&&(0>m&&(m+=Math.pow(2,p)),m>=Math.pow(2,p)&&(C=Math.ceil(Math.log(m)/
Math.log(q)))));for(p=h||-1;C--;){p||(v=","+v,p=h);if(void 0==m){if(v="?"+v,0>C)break}else{var x=m%q;m=Math.trunc(m/q);x+=0<=x&&9>=x?48:55;v=String.fromCharCode(x)+v;if(!m&&0>C)break}p--}h=a.X+"["+(n+v+w)+"]";if(e)if(e.size==a.a)b=e;else{n=void 0;if(e.values&&(n=e.values.slice(f,f+k),n.length!=k))break;b=new P(a.w,h,{type:d,Ka:b,size:k,bus:a.X,values:n})}else b=new P(a.w,h,{type:d,Ka:b,size:k,bus:a.X});a.b[g]=b;b=l+a.a;c-=k;f+=k;g++}}r=cb.prototype;r.la=function(){};
r.La=function(a){return a&&this.ga(a)?!0:!1};r.Ma=function(a){this.ha(a)};r.ga=function(a){for(var b=0;b<this.b.length;b++){var c=this.b[b];if((this.type==eb||c.type&Q.za)&&c.ga){var d=a.shift();if(!c.ga(d))return!1}}return!0};r.ha=function(a){for(var b=0;b<this.b.length;b++){var c=this.b[b];if((this.type==eb||c.type&Q.za)&&c.ha){var d=[];c.ha(d);a.push(d)}}};r.lc=function(a){return this.b[a>>>this.j].xa(a&this.s)};var db=0,eb=1;y.Bus=cb;
function P(a,b,c){L.call(this,a,b,c);this.Ka=c.addr;this.size=c.size;this.type=c.type||Q.NONE;this.f=(a=this.M.bus)?N(this,a):O(this,a="Bus");if(!this.f)throw Error(this.N("unable to find bus '%s'",a));this.j=this.f.l;this.h=Math.pow(2,this.j)-1;this.values=this.c=null;a=this.eb;if(b=this.f.type==db)if(b=8==this.j)b=N(this,this.w),b=!1!==(b&&b.M&&b.M.ArrayBuffer);b&&(this.c=new ArrayBuffer(this.size),new DataView(this.c,0,this.size),this.values=new Uint8Array(this.c,0,this.size),new Uint16Array(this.c,
0,this.size>>1),new Int32Array(this.c,0,this.size>>2));this.m=!1;gb(this,c.values);switch(this.type){case Q.NONE:this.xa=this.mc;break;case Q.Ya:this.xa=a;break;case Q.za:this.xa=a}}t(P,L);function gb(a,b){if(!a.values)b?a.values=b:a.values=Array(a.size).fill(a.h);else if(b)for(var c=0;c<a.size;c++)a.values[c]=b[c]}r=P.prototype;r.la=function(){this.type>=Q.za&&this.values.fill(0)};r.mc=function(){return this.h};r.eb=function(a){return this.values[a]};
r.ga=function(a){var b=a.shift();if(this.X==b){this.m=a.shift();a.shift();a=a.shift();var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}gb(this,a);return!0}return!1};r.ha=function(a){a.push(this.X);a.push(this.m);a.push(!1);for(var b=this.values,c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}a.push(e.length>=b.length?b:e)};var Q={NONE:1,Ya:2,za:4,Od:14,Ud:12};
y.Memory=P;
function R(a,b,c){c.type=Q.Ya;P.call(this,a,b,c);fb(this.f,c.addr,c.size,c.type,this);this.Y=this.ra=void 0;if(y.LED&&this.O[Ga]){var d=this;this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.l=this.values.length/this.b|0;this.a=new hb(a,b+"LEDs",{"class":"LED",bindings:{container:Fa(this)},type:ib,cols:this.b,rows:this.l,color:E(this,"colorROM","green"),backgroundColor:E(this,"backgroundColorROM","black"),persistent:!0}),jb(this.a);this.s=new kb(a,b+"Input",{"class":"Input",location:[0,
0,this.a.$,this.a.T,this.b,this.l],bindings:{surface:Fa(this)}});this.u=Ha(this)||"";lb(this.s,function(e,f){if(d.Y){var g=d.u;0<=e&&0<=f&&(e=f*d.b+e,g=mb(d.Y,d.Ka+e,d.values[e]));J(d,Ia,g)}})}}t(R,P);
R.prototype.ga=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.a.length==d?(this.a.a=c,S(this.a,!0)):(this.L("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.L("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};R.prototype.ea=function(){void 0===this.Y&&(this.Y=O(this,"CPU"));void 0===this.ra&&(this.ra=O(this,"Debugger",!1))};
R.prototype.eb=function(a){this.a&&nb(this.a,a%this.b,a/this.b|0,ob,T);return this.values[a]};R.prototype.ha=function(a){this.a&&(a.push(this.a.a),a.push(this.values))};var Ga="array",Ia="cellDesc";y.ROM=R;
function kb(a,b,c){L.call(this,a,b,c);this.ca=16384;this.m=this.u=null;this.time=O(this,"Time");this.I=O(this,"Machine");this.V=E(this,"drag",!1);this.R=E(this,"scroll",!1);this.U=E(this,"hexagonal",!1);this.f=E(this,"releaseDelay",0,void 0);this.h=!1;a=this.M.map;this.a=this.b=null;if(a)if(a.length)this.a=a;else{this.b={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.b[f]={keys:g,
Yd:e,state:0}}}this.v=[];this.H=[];this.c=this.J=null;(a=this.O[pb])&&qb(this,a,this.wa(c.focusBinding,!0),this.M.location);this.la()}t(kb,L);function lb(a,b){a.u=b}function rb(a,b,c){for(var d=0;d<a.v.length;d++){var e=a.v[d];e.id==b&&e.cb(b,c)}}
function qb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.a||a.b){var e={};e.qc=d[0]||0;e.rc=d[1]||0;e.ua=d[2]||b.clientWidth;e.Aa=d[3]||b.clientHeight;e.Ba=d[4]||1;e.Fa=d[5]||1;e.fc=d[6]||b.naturalWidth||e.ua;e.hc=d[7]||b.naturalHeight||e.Aa;e.gb=d[8]||0;e.hb=d[9]||0;e.ec=d[10]||0;e.gc=d[11]||0;a.a?(e.Da=a.a.length,e.va=a.a[0].length):(e.va=e.Ba,e.Da=e.Fa,e.Ba=e.Fa=0);e.$a=e.ua/(e.va+e.va*e.Ba)|0;e.ab=e.Aa/(e.Da+e.Da*e.Fa)|0;e.dc=e.$a*e.Ba|0;e.bb=e.ab*e.Fa|0;e.ya=e.Ga=-1;sb(a,b,e);tb(a,b,e);a.time&&
a.f&&(a.T=ub(a.time,"timerInputRelease",function(){0>e.ya&&0>e.Ga&&vb(a,-1,-1)}))}if(a.a||a.b)a.time&&a.f&&(a.W=ub(a.time,"timerKeyRelease",function(){wb(a)})),a.j=0,a.s="",a.l=[],d=b,c&&(d=c,a.c||"BUTTON"!=c.nodeName||(d=document,a.c=c,xb(a,b),a.J=b)),xb(a,d),a.c||(a.c=d)}function yb(a){a.f?zb(a.time,a.W,a.f):wb(a)}
function xb(a,b){function c(e,f,g){var l=document.activeElement;a.L(40960,"%s.onKey%s(%d): %5.2f (%s)\n",l.id||l.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e){var f=document.activeElement;return a.c&&f!=a.c&&f!=a.J?null:e||window.event}b.addEventListener("keydown",function(e){if(e=d(e)){var f=e.which||e.keyCode,g=Ab(a,f,!0);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(e)){var f=e.which||e.charCode,g=Ab(a,f);c("Press",
f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(e)){var f=e.which||e.keyCode;Ab(a,f,!1);c("Up",f);e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function sb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.h){var e=a.c;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||U(a,b,Bb,d,c)}});b.addEventListener("mousemove",function(d){a.h||U(a,b,Cb,d,c)});b.addEventListener("mouseup",function(d){a.h||d.button||U(a,b,V,d,c)});b.addEventListener("mouseout",function(d){a.h||(0>c.ya?U(a,b,Cb,d,c):U(a,b,V,d,c))})}
function tb(a,b,c){b.addEventListener("touchstart",function(d){a.R&&(a.h=!0);U(a,b,Bb,d,c)});b.addEventListener("touchmove",function(d){U(a,b,Cb,d,c)});b.addEventListener("touchend",function(d){U(a,b,V,d,c)})}
function Ab(a,b,c){var d;void 0!=c?d=Va[b]:d=String.fromCharCode(b).toUpperCase();if(a.a){if(!1===c)return!0;for(var e=0;e<a.a.length;e++)for(var f=a.a[e],g=0;g<f.length;g++)if(0<=f[g].split("|").indexOf(d))return a.j?16>a.l.length&&a.l.push(b):(a.j=1,a.s=d,vb(a,g,e),rb(a,d,!0),yb(a)),!0}if(a.b&&void 0!=c)for(b=Object.keys(a.b),e=0;e<b.length;e++)if(f=b[e],0<=a.b[f].keys.indexOf(d))return rb(a,f,c),a.b[f].state=c?1:0,!0;return!1}
function wb(a){1==a.j?(a.j++,rb(a,a.s,!1),a.s="",vb(a,-1,-1),yb(a)):(a.j=0,a.l.length&&Ab(a,a.l.shift()))}kb.prototype.la=function(){this.K=this.S=-1};
function U(a,b,c,d,e){var f=-1,g=-1,l=!1,k=-1,h=-1;if(c<V){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,h=d.targetTouches[0].clientY,l=1<d.targetTouches.length):(k=d.clientX,h=d.clientY);var n=d.target.getBoundingClientRect();k-=n.left;h-=n.top;k=e.fc/b.offsetWidth*k|0;h=e.hc/b.offsetHeight*h|0;var m=k-e.qc;var p=h-e.rc;var q=n=!1;var v=k>=e.gb&&k<e.gb+e.ec&&h>=e.hb&&h<e.hb+e.gc;if(0<=m&&m<e.ua&&0<=p+e.bb||v)if(l||a.R||d.preventDefault(),0<=m&&m<e.ua&&0<=
p&&p<e.Aa){q=!0;d=e.ua/e.va|0;var w=e.Aa/e.Da|0,C=m/d|0,x=p/w|0;!a.U||x&1||(m-=d>>1,C=m/d|0,C==e.va-1&&(m=-1));w=x*w+(e.bb>>1);m-=C*d+(e.dc>>1);p-=w;0<=m&&m<e.$a&&0<=p&&p<e.ab&&(f=C,g=x,n=!0)}}m=m||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Bb||c==V)for(C=0;C<a.H.length;C++)x=a.H[C],c==V?x.cb(x.id,!1):(w=p/(b/x.Xd|0)|0,(m/(d/x.Wd|0)|0)==x.$d&&w==x.ae&&x.cb(x.id,!0));if(!l)if(c==Bb)e.ya=k,e.Ga=h,q?(vb(a,f,g),n&&a.f&&zb(a.time,a.T,a.f,!0)):v&&a.I.ea();else if(c==Cb)0<=e.ya&&0<=e.Ga&&a.V?vb(a,f,
g):a.u&&a.u(f,g);else if(c==V){if(c=a.f)c=a.time,f=a.T,c=c.a&&0<f&&f<=c.b.length?0<=c.b[f-1].ba:!1;c||vb(a,-1,-1);e.ya=e.Ga=-1}else B(a,"unrecognized action: "+c)}function vb(a,b,c){if(b!=a.K||c!=a.S)a.K=b,a.S=c,a.m&&a.m(b,c)}var Bb=1,Cb=2,V=3,pb="surface";y.Input=kb;
function hb(a,b,c){L.call(this,a,b,c,["color","backgroundColor"]);a=this.O[Db];if(!a)throw Error("LED binding for '"+Db+"' missing: '"+this.M.O[Db]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ia=a;this.type=Ja(E(this,"type",ib,Eb),Fb,Gb);this.f=Hb[this.type][0];this.m=Hb[this.type][1];this.width=E(this,"width",this.f,void 0);this.height=E(this,"height",this.m,void 0);
this.h=E(this,"cols",1,void 0);this.H=this.h+E(this,"colsExtra",0,void 0);this.W=E(this,"rows",1,void 0);this.R=this.W+E(this,"rowsExtra",0,void 0);this.$=this.width*this.h;this.T=this.height*this.W;this.l=Ib("black",0);this.c=Jb(this.M.color)||this.l;this.ma=Ib(this.c,1,.25);this.ia=Ib(this.c,1,2);this.j=Jb(this.M.backgroundColor);this.na=E(this,"fixed",!1);this.na||(b.style.width="100%",b.style.height="auto");this.fa=E(this,"hexagonal",!1);this.oa=E(this,"highlight",!0);this.S=E(this,"persistent",
this.type<Gb);b.setAttribute("width",this.$.toString());b.setAttribute("height",this.T.toString());b.style.backgroundColor=this.l;a.appendChild(b);this.aa=b.getContext("2d");if(this.s=document.createElement("canvas"))this.s.width=this.Z=this.f*this.h,this.s.height=this.u=this.m*this.W,this.b=this.s.getContext("2d");this.qa=(this.R+1)*this.H*4;this.a=Array(this.qa);this.pa=this.h<this.H?4*(this.H-this.h):0;this.J=this.K=!1;this.v=this.V=0;this.U=-1;var d=this;this.time=O(this,"Time");Kb(this.time,
function(e){S(d,!1,e)});jb(d)}t(hb,L);function jb(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Gb?Lb:" ";e[f+1]=d.c==d.l?null:d.c;e[f+2]=0;e[f+3]=T}a.J=a.K=!0;S(a,!0)}function Mb(a){a.j?(a.b.fillStyle=a.j,a.b.fillRect(0,0,a.Z,a.u)):a.b.clearRect(0,0,a.Z,a.u)}
function S(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.J||b){if(a.type<Gb){var d=0;if(!a.S||b)Mb(a);else if(a.v){d=a.h-a.v;var e=a.f*d;a.b.drawImage(a.s,a.f*a.v,0,e,a.u,0,0,e,a.u)}for(var f=e=0;f<a.R;f++){for(var g=0;g<a.h;g++){var l=a.a[e],k=a.a[e+1]||a.l,h=a.oa&&e==a.U;if(a.a[e+3]&T||h||b){if(g>=d)a:{var n=a,m=l;l=k;var p=g;k=f;var q=h;p=void 0===p?0:p;k=void 0===k?0:k;q=void 0===q?!1:q;var v=0;if(n.fa&&!(k&1)&&(v=n.f>>1,p==n.h-1))break a;if(l&&l!=n.c){q=q?Ib(l,1,2):l;var w=Ib(l,1,.25)}else q=
q?n.ia:n.c,w=n.ma;l=!1;m=m?q:w;q==n.l&&(m=n.j,l=!0);q=p*n.f+v;w=k*n.m;n.S&&(p=p*n.f+v,k*=n.m,n.j?(n.b.fillStyle=n.j,n.b.fillRect(p,k,n.f,n.m)):n.b.clearRect(p,k,n.f,n.m));n.b.fillStyle=m;k=Nb[n.type];3==k.length?(n.b.beginPath(),n.b.arc(q+k[0],w+k[1],k[2],0,2*Math.PI),l?(n.b.globalCompositeOperation="destination-out",n.b.fill(),n.b.globalCompositeOperation="source-over"):n.b.fill()):n.b.fillRect(q+k[0],w+k[1],k[2],k[3])}a.a[e+3]=h?a.a[e+3]|T:a.a[e+3]&~T}e+=4}e+=a.pa}a.v=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&Ob&&(b+=".");Mb(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;h=e;n=f;h=void 0===h?0:h;n=void 0===n?0:n;if(k=Pb[k])for(l=0;l<k.length;l++)if(p=g,v=Qb[k[l]]){m=(void 0===h?0:h)*p.f;q=(void 0===n?0:n)*p.m;p.b.fillStyle=p.c;p.b.beginPath();if(3==v.length)p.b.arc(m+v[0],q+v[1],v[2],0,2*Math.PI);else for(w=0;w<v.length;w+=2)w?p.b.lineTo(m+v[w],q+v[w+1]):p.b.moveTo(m+v[w],q+v[w+1]);p.b.closePath();p.b.fill()}if(++e==a.h&&(e=0,++f==a.R))break}}a.aa.globalCompositeOperation=
a.j&&a.c!=a.l?"source-over":"copy";a.aa.drawImage(a.s,0,0,a.Z,a.u,0,0,a.$,a.T);a.J=!1;a.U=-1}else a.S||a.K||(!c||!a.V||c-a.V>=(1E3/60|0))&&jb(a);a.K=!1;c&&(a.V=c)}function Jb(a){return(a=a||void 0)&&Xa[a]||a}
function Ib(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=Xa[a]||a;var e=a;var f=16;var g=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);g||(f=10,g=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(g){for(e=1;e<g.length;e++)d[e-1]=Number.parseInt(g[e],f);d.length=e-1;f=!0}else f=!1;if(f){a="rgba(";for(f=0;3>f;f++)g=Math.round(d[f]*c),g=0>g?0:255<g?255:g,a+=g+",";a+=(f<d.length?d[f]:b)+")"}}return a}
hb.prototype.ga=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.j&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.l&&(this.a[b+1]=null);S(this,!0);return!0}return!1};hb.prototype.ha=function(a){this.a&&(a.push(this.c),a.push(this.j),a.push(this.a))};
function nb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&Rb;b=4*(c*a.H+b);if(b<=a.a.length-4){if(a.a[b]!==d||(a.a[b+3]&Rb)!==e)a.a[b]=d,a.a[b+3]=a.a[b+3]&~Rb|e|T,a.J=f=!0;a.U=b;a.K=!0;a.v=0}return f}
var Fb=0,ib=1,Gb=3,Eb={small:Fb,round:ib,square:2,digit:Gb},Db="container",Lb=0,ob=1,Rb=129,Ob=1,T=128,Sb={},Nb=(Sb[Fb]=[4,4,4],Sb[ib]=[16,16,14],Sb[2]=[2,2,28,28],Sb),Hb=[[8,8],[32,32],[32,32],[96,128]],Qb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Pb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};y.LED=hb;
function Tb(a,b,c){L.call(this,a,b,c);this.pa=E(this,"cyclesMinimum",1E5,void 0);this.Ua=E(this,"cyclesMaximum",3E6,void 0);this.$=Ja(E(this,"cyclesPerSecond",65E4,void 0),this.pa,this.Ua);this.W=Ja(E(this,"yieldsPerSecond",Ub,void 0),30,120);this.Va=Ja(E(this,"yieldsPerUpdate",Vb,void 0),1,this.W);this.na=(this.K=E(this,"clockByFrame",120>=this.$))||E(this,"requestAnimationFrame",!0);this.Ra=this.Sa=this.aa=1;this.qa=this.$/1E4/100;this.l=this.u=this.qa*this.aa;this.H=0;this.fa=Math.round(1E3/this.W);
this.ia=[];this.J=[];this.b=[];this.ma=[];this.Ia=this.a=this.oa=this.s=!1;this.S=this.R=this.h=0;this.Xa=this.nc.bind(this);this.Wa=this.Za.bind(this);this.Qa=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);this.zb=(window.cancelAnimationFrame||window.webkitCancelAnimationFrame||window.clearTimeout).bind(window);this.j=this.T=this.V=this.U=0;if(this.K)this.f=this.Ta=0;else{var d=this;ub(this,"timerYield",function(){Wb(d)},this.fa)}this.U=this.T=
this.j=0;Xb(this)||Yb(this,this.Ra)}t(Tb,L);function Kb(a,b){a.ia.push(b)}r=Tb.prototype;r.ta=function(a,b){var c=this;switch(a){case Zb:b.onclick=function(){$b(c)&&(c.a?W(c):c.start())};break;case ac:b.onclick=function(){bc(c)};break;case cc:b.addEventListener("mousedown",function(){c.s=!0}),b.addEventListener("mouseup",function(){Xb(c);c.s=!1}),b.addEventListener("mousemove",function(){c.s&&Xb(c)}),b.addEventListener("change",function(){c.s=!0;Xb(c);c.s=!1})}L.prototype.ta.call(this,a,b)};
function ub(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,cc:c,Ca:d,ba:-1});0<=d&&zb(a,e,d);return e}r.Za=function(a){if(this.K){this.R=0;if(!this.a)return;dc(this,!0)}for(var b=0;b<this.ia.length;b++)this.ia[b](a);this.a&&this.na&&(this.R=this.Qa(this.Wa))};function ec(a){var b=a.l/a.qa;if(!b||b>a.aa)b=a.aa;a.Db=a.$/a.W*b;a.Sa=b}
function fc(a,b){a.T=a.j=b;if(!a.J.length)return a.j=0,a.T;for(var c=0;0<a.j;){if(c<a.J.length){var d=a.J[c++];b=d.oc.call(d,b)||1}else c=b=0;a.j-=b}return a.T-a.j}function gc(a,b){var c=Date.now();b()&&(a.Z+=Date.now()-c)}function hc(a,b){b=void 0===b?a.T-a.j:b;if(a.K){if(!a.a){if(a.f)for(var c=0;c<a.J.length;c++){var d=a.J[c];d.pc.call(d)}a.f=b}a.f-=b;1>a.f&&Wb(a)}a.T=a.j=0;a.V+=b;a.U+=b;a.a||(a.U=0);return b}
function ic(a,b,c){if(c=void 0===c?0:c)b=c,a.f+=c;else for((void 0===b?0:b)?(b=a.f,1>b&&(b=a.f+=a.Ta),0>b&&(a.L("warning: nCycles dropped below zero: %f\n",b),b=a.f=0),b|=0):b=jc(a,a.fa),c=a.b.length;0<c;c--){var d=a.b[c-1];!(0>d.ba)&&b>d.ba&&(b=d.ba)}return b}function jc(a,b){return Math.ceil(a.$*a.Sa/1E3*(void 0===b?1E3:b))}function kc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function $b(a){return a.Ia?!0:(B(a,"not powered"),!1)}
function lc(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.ba||(d.ba-=b,0>=d.ba&&(d.ba=-1,d.cc(),0<=d.Ca&&zb(a,c,d.Ca)))}}r.ea=function(a){this.Ia=a;void 0===this.ra&&(this.ra=O(this,"Debugger",!1))};function bc(a,b){$b(a)&&(a.a?B(a,"already running"):a.h?W(a):mc(a,b))}r.nc=function(){this.S=0;if(this.a){var a=dc(this);this.a&&(this.S=setTimeout(this.Xa,a),this.na||this.Za())}};
function dc(a,b){b=void 0===b?!1:b;ec(a);a.V=0;a.Z=0;a.v=Date.now();a.c||(a.c=a.v);if(a.m){var c=a.v-a.m;c>a.fa&&(a.c+=c,a.c>a.v&&(a.c=a.v))}try{a.oa=!1;do lc(a,hc(a,fc(a,ic(a,b))));while(a.a&&!a.oa)}catch(d){B(a,d.message),W(a)}a.m=Date.now();a.Z&&(a.c+=a.Z,a.v+=a.Z);b=a.fa;a.V&&(b=Math.round(b*a.V/a.Db));b-=a.m-a.v;if(c=a.m-a.c)a.l=a.U/(10*c)/100;0>b?(-1E3>b&&(a.c-=b),b=0):a.l<a.u&&(b=0);a.m+=b;a.L(4096,"after running %d cycles, resting for %dms\n",a.V,b);return b}
function Xb(a){var b=a.O[cc];return b?(Yb(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Ua-a.pa)+a.pa)/a.$),!0):!1}function Yb(a,b){void 0!==b&&(!a.s&&0<a.l&&a.l<.9*a.u&&(b=a.Ra),a.aa=b,b=a.qa*a.aa,a.u!=b&&(a.u=b,J(a,nc,kc(a.u))),a.l=a.u);a.K&&(a.Ta=1E6*a.l/60+1E-8,a.f=0);a.U=0;a.c=a.m=0;ec(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Ca&&zb(a,b,c.Ca,!0)}}function zb(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.ba)&&(c=jc(a,c),a.a&&(c+=hc(a)),b.ba=c)}
r.start=function(){if(this.a||this.h)return!1;this.a=!0;this.c=this.m=0;this.update(!0);this.K||(this.S=setTimeout(this.Xa,0));this.na&&(this.R=this.Qa(this.Wa));return!0};function mc(a,b){b=void 0===b?1:b;a.a||(b&&!a.h&&(a.h=b),a.h&&(a.h--,lc(a,hc(a,fc(a,ic(a,!0,1)))),a.update(!1),a.h&&setTimeout(function(){mc(a,0)},0)))}function W(a){return a.a?(a.a=!1,hc(a),a.S&&(clearTimeout(a.S),a.S=0),a.R&&(a.zb(a.R),a.R=0),a.update(!0),!0):a.h?(a.h=0,a.update(!0),!0):!1}
r.update=function(a){a&&(this.a?B(this,"started with "+kc(this.u)+" target"):B(this,"stopped"));J(this,Zb,this.a?"Halt":"Run");J(this,ac,this.h?"Stop":"Step");this.s||J(this,nc,this.a&&this.l?kc(this.l):"Stopped");for(var b=0;b<this.ma.length;b++){var c=this.ma[b];c.jc.call(c,void 0!=a)}};function Wb(a){a.oa=!0;var b=a.H,c=jc(a);c>=a.W?a.H++:a.H+=Math.ceil(a.W/c);a.H>=a.Va&&b<a.Va&&a.update();a.H>=a.W&&(a.H=0)}var Zb="run",nc="speed",ac="step",cc="throttle",Ub=120,Vb=60;y.Time=Tb;
function X(a,b,c){L.call(this,a.w,b);this.Y=a;this.name=b;this.g=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.fa[c]=[this,-1];for(var d=0;d<this.g.length;d++)c=this.N("reg%s-%02d",this.name,d),b.push(c),a.fa[c]=[this,d];Ea(a,b)}}t(X,L);r=X.prototype;r.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.g[f]=a.g[f]+b.g[f]+e,e=0,this.g[f]>=d&&(this.g[f]-=d,e=1);e&&(this.Y.l=!0);oc(this,c)};r.get=function(){return this.g};
function pc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.g.length;d++)a.g[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.g[d]=b&15,b>>>=4;return a}r.move=function(a,b){for(var c=b[0],d=b[1];c<=d;c++)this.g[c]=a.g[c];oc(a,b)};r.set=function(a){if(a&&a.length==this.g.length)for(var b=0;b<this.g.length;b++)this.g[b]=a[b]};r.store=function(a){for(var b=0,c=this.g.length;b<c;b++)this.g[b]=a.g[b]};
r.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.g[f]=a.g[f]-b.g[f]-e,e=0,0>this.g[f]&&(this.g[f]+=d,e=1);e&&(this.Y.l=!0);oc(this,c)};r.toString=function(a){a=void 0===a?!1:a;var b=this.X+"=";a&&3>b.length&&(b+=" ");for(var c=this.g.length-1;0<=c;c--)b=a?b+ya[this.g[c]]:b+(za[this.g[c]]+(c%4?"":" "));return b};function oc(a,b){a.Y.j=a.g[b[0]];b[0]<b[1]&&(a.Y.j|=a.g[b[0]+1]<<4)}
function qc(a,b,c){L.call(this,a,b,c);this.type=Number.parseInt(E(this,"type","1501").slice(-4),10);this.fa={};this.a=Array(4);for(a=0;4>a;a++)this.a[a]=new X(this,String.fromCharCode(65+a));this.J=this.a[0];this.S=this.a[1];this.oa=this.a[2];this.pa=this.a[3];this.v=Array(8);for(a=0;8>a;a++)this.v[a]=new X(this,"X"+a);this.K=Array(8);for(a=0;8>a;a++)this.K[a]=new X(this,"Y"+a);this.ia=new X(this,"Supp",!0);this.U=new X(this,"Temp",!0);this.u=10;this.l=!1;this.T=this.Na=this.b=this.j=this.m=0;this.h=
[-1,-1,-1];this.na=this.s=0;this.qa=N(this,this.M.input);this.qa.m=this.mb.bind(this);this.f=N(this,this.M.output,!1);this.ma=O(this,"Bus");this.c=O(this,"ROM");(this.time=O(this,"Time"))&&this.c&&(this.time.J.push(this),this.time.ma.push(this));this.$=this.aa=this.R=void 0;this.Z=this.V=-1;this.H={};this.W=rc;a=this.ic.bind(this);b=Qa.Pa;this.I.Ea[b]||(this.I.Ea[b]=[]);this.I.Ea[b].push(a)}t(qc,L);function sc(a,b){a.H[b]&&(a.H[b]=!1,B(a,"break on "+tc[b]),W(a.time))}
function uc(a){a.f&&jb(a.f);if(a.c){var b=a.c;b.a&&jb(b.a)}vc(a,!1)}r=qc.prototype;r.oc=function(a){for(this.na=this.s=a=void 0===a?0:a;0<this.s;){if(this.Z==this.b){this.Z=-1;B(this,"break");W(this.time);break}var b=this.ma.xa(this.b);this.b=(this.Na=this.b)+1&this.ma.m;if(void 0==b||!wc(this,b)){this.b=this.Na;B(this,"unimplemented opcode");W(this.time);break}this.s-=xc}if(0>=a){var c=this;gc(this.time,function(){var d=c.c;d.a&&S(d.a);c.ja(c.toString())})}return this.na-this.s};
r.pc=function(){this.s=0};
function wc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.l&&(a.b=a.b&1024|b&1023):(a.push(a.b),a.b=b&2047),a.l=!1,!0;var c;var d=b&yc;switch(d){case zc:case Ac:case Bc:case Cc:case Dc:case Ec:case Fc:case Gc:case Hc:case Ic:case Jc:case Kc:d=Lc[d];var e=(b&Mc)>>Nc;var f=(b&Oc)>>Pc;var g=(b&Qc)>>Rc;var l=(c=b&Sc)?Tc:Uc;switch(f){case 0:case 1:case 2:case 3:var k=a.a[f];break;case 4:k=pc(a.U,1,d);break;case 5:l=c?Vc:Wc;break;case 6:k=pc(a.U,a.j&15,d);break;case 7:k=pc(a.U,a.j&255,d)}switch(g){case 0:var h=
a.a[e];break;case 1:h=4>f?a.a[f]:void 0;break;case 2:h=5>f?a.ia:5==f?a.a[e]:void 0;break;case 3:if(c)a.a[e].move(k,d);else{a=a.J;e=k;b=d[0];for(k=d[1];b<=k;b++)h=a.g[b],a.g[b]=e.g[b],e.g[b]=h;oc(e,d)}return!0}if(!h)break;b=b>=Gc?16:a.u;switch(l){case Uc:h.add(a.a[e],k,d,b);break;case Tc:h.sub(a.a[e],k,d,b);break;case Wc:b=h;a=a.a[e];e=d[1];for(k=d[0];e>k;e--)b.g[e]=a.g[e-1];b.g[e]=0;oc(b,d);break;case Vc:b=h;a=a.a[e];e=d[0];for(k=d[1];e<k;e++)b.g[e]=a.g[e+1];b.g[e]=0;oc(b,d)}return!0;case Xc:e=(b&
Yc)>>Zc;d=(b&$c)>>ad;k=1<<((b&bd)>>cd);if(!d)break;d+=12;switch(b&dd){case ed:a.a[e].g[d]|=k;break;case fd:a.a[e].g[d]&=~k;break;case gd:a.a[e].g[d]&k&&(a.l=!0);break;case hd:a.a[e].g[d]^=k}return!0;case id:switch(b&jd){case kd:a.J.store(a.K[a.m]);break;case ld:a.m=b>>4&7;break;case md:a.b=a.j;break;case nd:a.l=!1;d=a.h[0];e=0;for(b=a.h.length-1;e<b;)a.h[e]=a.h[++e];a.h[e]=-1;a.b=d;break;case od:a.v[a.m].store(a.J);break;case pd:a.J.store(a.v[a.m]);break;case qd:a.K[a.m].store(a.J);break;case rd:sc(a,
"o");if(a.f){d=0;for(e=11;0<=e;d++,e--)b=void 0,a.S.g[e]&8?b=" ":a.S.g[e]&1?b="-":b=ya[a.J.g[e]],nb(a.f,d,0,b,a.S.g[e]&2?Ob:0)&&sc(a,"om");vc(a)}a.s-=31*xc;a.T&&(a.j=a.T,a.l=!0,sc(a,"i"));break;case sd:a.u=10;break;case td:a.u=16;break;case ud:a.m=a.j&7;break;default:return!1}return!0}return!1}
r.ga=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return B(this,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.L("saved state version mismatch: %3.2f\n",c),!1;try{this.a.forEach(function(d){return d.set(b.shift())}),this.v.forEach(function(d){return d.set(b.shift())}),this.K.forEach(function(d){return d.set(b.shift())}),this.ia.set(b.shift()),this.U.set(b.shift()),this.u=b.shift(),this.l=b.shift(),this.m=b.shift(),this.j=b.shift(),this.b=b.shift(),this.h=b.shift(),this.T=
b.shift()}catch(d){return B(this,"CPU state error: "+d.message),!1}return(a=a.stateROM||a[1])&&this.c&&!this.c.ga(a)?!1:!0};
r.ic=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,l=3;l<a.length;l++)d.push(Number.parseInt(a[l],16));this.W=rc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in tc)c=tc[f],b+="break on "+c+" (b"+f+"): "+(this.H[f]||!1)+"\n";break}(c=tc[f])?(this.H[f]=!this.H[f],b="break on "+c+" (b"+f+"): "+this.H[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.c.values[f];if(void 0==
a)break;this.c.values[f]=d[g];b+=this.N("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.N("%d locations updated\n",c);break;case "g":this.time.start()?this.Z=f:b="already started\n";break;case "h":W(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.W=vd);g=Number.parseInt(a[2],10)||1;bc(this.time,g);break;case "r":"c"==e[1]&&(this.W=vd);this.fb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.V?this.V:this.b;g--;){c=this.c&&this.c.values[f];if(void 0==
c)break;b+=mb(this,f++,c)}this.V=f;break;case "?":b="additional commands:\n";wd.forEach(function(k){b+=k+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};r.mb=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.T=c};r.La=function(a){return a&&this.ga(a)?!0:!1};r.ea=function(a){a?this.time.start():(W(this.time),uc(this))};r.la=function(){B(this,"reset");this.b=0;var a=this.c;a.values=a.M.values;uc(this);this.time.a||this.ja(this.toString())};r.Ma=function(a){this.ha(a)};
r.jc=function(a){for(var b in this.O){var c=this.fa[b];if(c){var d=c[0];c=c[1];J(this,b,0>c?d.toString():ya[d.g[c]])}}a&&!this.time.a&&(a=this.c,a.a&&S(a.a),this.ja(this.toString()))};r.push=function(a){for(var b=this.h.length-1;0<b;)this.h[b]=this.h[--b];this.h[0]=a};
r.ha=function(a){var b=[],c=[];b.push(2);this.a.forEach(function(d){return b.push(d.get())});this.v.forEach(function(d){return b.push(d.get())});this.K.forEach(function(d){return b.push(d.get())});b.push(this.ia.get());b.push(this.U.get());b.push(this.u);b.push(this.l);b.push(this.m);b.push(this.j);b.push(this.b);b.push(this.h);b.push(this.T);this.c&&this.c.ha(c);a.push(b);a.push(c)};r.fb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.b=b;break;default:B(this,"unrecognized register: "+a)}};
function mb(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.N("%#06x",f);else if(0<=c){var g=c&yc;var l;switch(g){case zc:case Ac:case Bc:case Cc:case Dc:case Ec:case Fc:case Gc:case Hc:case Ic:case Jc:case Kc:f="";e=Lc[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&Mc)>>Nc;var k=(c&Oc)>>Pc;var h=(c&Qc)>>Rc;var n=c&Sc;e="LOAD";var m=l="?";var p=n?5==k?">>":"-":5==k?"<<":"+";switch(h){case 0:l=
Y[g];break;case 1:4>k&&(l=Y[k]);break;case 2:6>k&&(l="NUL");break;case 3:n?(e="MOVE",l=Y[g],m=Y[k]):(e="XCHG",g||(l="A"),4>k&&(m=Y[k])),k=-1}switch(k){case 0:case 1:case 2:case 3:m=Y[g]+p+Y[k];break;case 4:case 5:m=Y[g]+p+"1";break;case 6:m=Y[g]+p+"R5L";break;case 7:m=Y[g]+p+"R5"}f=l+","+m+","+f;break;case Xc:switch(c&dd){case ed:e="SET";break;case fd:e="CLR";break;case gd:e="TST";break;case hd:e="NOT"}f=a.a[(c&Yc)>>Zc].name;g=(c&$c)>>ad;f+="["+(g?g+12:"?")+":"+((c&bd)>>cd)+"]";break;case id:switch(c&
jd){case kd:e="STORE";f="A,Y[RAB]";break;case ld:e="STORE";f="RAB,"+((c&112)>>4);break;case md:e="BR";f="R5";break;case nd:e="RET";break;case od:e="STORE";f="X[RAB],A";break;case pd:e="STORE";f="A,X[RAB]";break;case qd:e="STORE";f="Y[RAB],A";break;case rd:e="DISP";break;case sd:e="BCDS";break;case td:e="BCDR";break;case ud:e="STORE",f="RAB,R5L"}}}return a.N(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
r.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.W){this.c&&(d+=mb(this,this.b,this.c.values[this.b],!0));d+="  ";b=0;for(a=this.a.length;b<a;b++)d+=this.a[b].toString()+" ";d+="\n ";d+=" COND="+(this.l?1:0);d+=" BASE="+this.u;d+=" R5="+this.N("%02X",this.j);d+=" RAB="+this.m+" ST=";this.h.forEach(function(f){d+=c.N("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=
this.toString(a,this.a);0<=a.indexOf("a")&&(d+=this.toString(a,this.v),d+=this.toString(a,this.K));d+="COND="+(this.l?1:0);d+=" BASE="+this.u;d+=" R5="+this.N("%#04x",this.j);d+=" RAB="+this.m+" ";this.h.forEach(function(f,g){d+=c.N("ST%d=%#06x ",g,f&65535)});this.c&&(d+="\n"+mb(this,this.b,this.c.values[this.b]));this.V=this.b;return d};
function vc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==xd?!!(a.oa.g[14]&8):!!(a.S.g[15]&4));if(a.$!==d){if(c=a.O["2nd"])c.style.opacity=d?"1":"0",void 0===a.$&&a.f&&(c.style.color=a.f.color);a.$=d}d=b&&(a.type==xd?!!(a.S.g[15]&4):!!(a.pa.g[15]&8));if(a.aa!==d){if(c=a.O.INV)c.style.opacity=d?"1":"0",void 0===a.aa&&a.f&&(c.style.color=a.f.color);a.aa=d}c=a.type==xd?a.v[4].g[15]>>2:a.oa.g[15];b=b?c?1==c?yd:zd:Ad:Bd;if(a.R!==b){if(c=a.O.Deg)c.style.opacity=b==Ad?"1":"0",void 0===a.R&&a.f&&(c.style.color=
a.f.color);if(c=a.O.Rad)c.style.opacity=b==yd?"1":"0",void 0===a.R&&a.f&&(c.style.color=a.f.color);if(c=a.O.Grad)c.style.opacity=b==zd?"1":"0",void 0===a.R&&a.f&&(c.style.color=a.f.color);a.R=b}}
var yc=3840,zc=0,Ac=256,Bc=512,Cc=768,Dc=1024,Ec=1280,Fc=1792,Gc=2048,Hc=2304,Ic=2560,Xc=3072,Jc=3328,id=3584,Kc=3840,Mc=192,Nc=6,Oc=56,Pc=3,Qc=6,Rc=1,Sc=1,dd=3,ed=0,fd=1,gd=2,hd=3,Yc=192,Zc=6,$c=48,ad=4,bd=12,cd=2,jd=15,kd=0,ld=1,md=2,nd=3,od=4,pd=5,qd=6,rd=7,sd=8,td=9,ud=10,Z={},Lc=(Z[zc]=[12,12],Z[Ac]=[0,15],Z[Bc]=[2,12],Z[Cc]=[0,12],Z[Dc]=[2,2],Z[Ec]=[0,1],Z[Fc]=[0,13],Z[Gc]=[14,14],Z[Hc]=[13,15],Z[Ic]=[14,15],Z[Jc]=[13,13],Z[Kc]=[15,15],Z),xc=128,Uc=0,Tc=1,Wc=2,Vc=3,xd=1501,Bd=0,Ad=1,yd=2,zd=
3,tc={i:"input",o:"output",om:"output modification"},rc=0,vd=1,Y="A B C D 1 ? R5L R5".split(" "),wd="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");y.CPU=qc;
function Cd(a,b,c){L.call(this,a,a);var d=this;this.c=this.a=!1;this.m=c;this.b="";this.l=this.j=!1;this.ca=262144;b=b.trim();"{"==b[0]?Dd(this,b):(this.b=b,Ka(this.b,function(e,f,g,l){4==g&&(!l&&f?(Dd(d,f),Ed(d)):d.L("error (%d) loading configuration: %s\n",l,e))}));window.addEventListener("load",function(){d.l=!0;Ed(d)});window.addEventListener(Ma("iOS")?"pagehide":Ma("Opera")?"unload":"beforeunload",function(){Fd(d)});window.addEventListener("pageshow",function(){d.a&&!d.c&&d.ea(!0)})}t(Cd,L);
Cd.prototype.ta=function(a,b){var c=this;switch(a){case Gd:b.onclick=function(){c.a&&c.ea()};break;case Hd:b.onclick=function(){c.a&&c.la()}}L.prototype.ta.call(this,a,b)};
function Ed(a){var b=!0;if(a.j&&a.l){for(var c in a.f){var d=void 0;try{var e=a.f[c];d=e["class"];y[d]?"Machine"==d?(a.L("PCjs %s v%3.2f\n%s\n%s\n",e.name,2,Id,Jd),a.b&&a.L("Configuration: %s\n",a.b)):new y[d](a.w,c,e):a.L("unrecognized %s device class: %s\n",c,d)}catch(g){a.L("error initializing %s device '%s': %s\n",d,c,g.message),bb(a,c),b=!1}}if(a.h){var f=Na(a);$a(a,function(g){return g.La&&!g.La(f)?(g.L("unable to restore state for device: %s\n",g.X),!1):!0})}a.ea(b)}}
function Dd(a,b){try{a.f=JSON.parse(b);Za(a,a.f[a.w],["autoSave","autoStart"]);a.h=!1!==a.M.autoSave;a.s=!1!==a.M.autoStart;if(a.m){var c=eval("("+a.m+")"),d;for(d in c)a.M[d]=c[d]}a.j=!0}catch(e){c=e.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),B(a,"machine '"+a.w+"' initialization error: "+c)}}
Cd.prototype.ea=function(a){a=void 0===a?!this.c:a;var b=this;a&&B(this,"power on");$a(this,function(c){c.ea&&c!=b&&("CPU"!=c.M["class"]||b.s||b.a?c.ea(a):c.time.update(!0));return!0});this.a=!0;(this.c=a)||B(this,"power off")};Cd.prototype.la=function(){var a=this;$a(this,function(b){b.la&&b!=a&&b.la();return!0})};function Fd(a){if(a.h){var b=[];$a(a,function(c){c.Ma&&c.Ma(b);return!0});Ua(a,b)}a.ea(!1)}var Gd="power",Hd="reset",Id="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",Jd="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";
window.TMS1500=function(a,b,c){var d=new Cd(a,b,c);window.command=function(e){return Oa(d,e)};return d};y.Machine=Cd;})()

//# sourceMappingURL=ti55.js.map
