(function(){/*
 https://www.pcjs.org/modules/devices/lib/webio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/device.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/defs.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/numio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/lib/stdio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/bus.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbgio.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/memory.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/port.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/input.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/led.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/monitor.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/ram.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/rom.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/time.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/vt100/video.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/cpu8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/dbg8080.js (C) Jeff Parsons 2012-2019
 https://www.pcjs.org/modules/devices/machine.js (C) Jeff Parsons 2012-2019
*/
var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ca(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={Ac:!0},ia={};try{ia.__proto__=ha;fa=ia.Ac;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function n(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.kj=b.prototype}var ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},la="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ma(a,b){if(b){var c=la;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}ma("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ma("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});ma("Number.parseInt",function(a){return a||parseInt});
function na(){na=function(){};la.Symbol||(la.Symbol=oa)}function pa(a,b){this.a=a;ka(this,"description",{configurable:!0,writable:!0,value:b})}pa.prototype.toString=function(){return this.a};var oa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new pa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function qa(){na();var a=la.Symbol.iterator;a||(a=la.Symbol.iterator=la.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ka(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(aa(this))}});qa=function(){}}function ra(a){qa();a={next:a};a[la.Symbol.iterator]=function(){return this};return a}
function ta(a,b){qa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ma("Array.prototype.keys",function(a){return a?a:function(){return ta(this,function(b){return b})}});
ma("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});var ua,va=new ArrayBuffer(2);(new DataView(va)).setUint16(0,256,!0);ua=256===(new Uint16Array(va))[0];function wa(){}var q={};q.Defs=wa;function ya(){}n(ya,wa);
function za(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var g;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)/))&&
(a=c[1],e=35-((c[2]||35)&255));c=a;if(((d=b)&&10!=d?16==d?null!==c.match(/^-?[0-9a-f]+$/i):8==d?null!==c.match(/^-?[0-7]+$/):2==d&&null!==c.match(/^-?[01]+$/):null!==c.match(/^-?[0-9]+$/))&&!isNaN(g=parseInt(a,b))){e&&(0>g&&(g+=Math.pow(2,36)),g=0<e?g*Math.pow(2,e):Math.trunc(g/Math.pow(2,-e)));var h=g}}return h}
function Aa(a,b,c,d,e){d=void 0===d?0:d;var g=void 0===g?0:g;var h="",k="",l=-1;c||(c=a.da||10);d&&(l=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:k=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=k=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(l=Math.ceil(Math.log(b)/Math.log(c)))));for(a=g||-1;l--;){a||(h=","+h,a=g);if(void 0==b){if(h="?"+h,0>l)break}else{d=b%c;d+=0<=d&&9>=d?48:55;h=String.fromCharCode(d)+h;
if(!b&&0>l)break;b=Math.trunc(b/c)}a--}return e+h+k}function Ba(a,b){var c=a/y|0,d=b/y|0;return(a&b)==(b|0)&&(c&d)==d}var y=Math.pow(2,32);q.NumIO=ya;function Ca(){}n(Ca,ya);f=Ca.prototype;f.flush=function(){var a=Da;Da="";this.Ba(a)};f.oh=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ca(b)))};
f.Ba=function(a,b){b||(b=a.lastIndexOf("\n"),0<=b&&(console.log(Da+a.substr(0,b)),Da="",a=a.substr(b+1)));Da+=a};function z(a,b,c){a.Ba(b+"\n",c)}f.O=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.Ba(this.J.apply(this,[a].concat(ca(c))))};
f.J=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),g=0,h;for(h=0;h<e.length-6;h+=6){d+=e[h];var k=e[h+5],l="ACDFHIMNSTWYbdfjcsoXx%".indexOf(k);if(0>l)d+="%"+e[h+1]+e[h+2]+e[h+3]+e[h+4]+k;else{if(g<c.length){var m=c[g];"%"!=k&&g++}else m=c[c.length-1];var r=e[h+1],w=e[h+2];"*"==w?(w=m,m=g<c.length?c[g++]:c[c.length-1]):w=+w||0;var t=e[h+3];t=t?+t.substr(1):-1;var p=0<=r.indexOf("#"),u=0<=r.indexOf("0"),
v=null,x=0,A="";l=12>l&&"object"!=typeof m?this.oh(m):m;switch(k){case "C":m=p?"#":"";d+=isNaN(l.getTime())?void 0:this.J(this.J("%%%sW, %%%sF %%%sD, %%%sY",m),l);continue;case "D":m=p?l.getUTCDate():l.getDate();k="d";break;case "A":case "H":case "I":m=p?l.getUTCHours():l.getHours();"A"==k?(m=12>m?"am":"pm",k="s"):("I"==k&&(m=m?12<m?m-12:m:12),k="d");break;case "F":case "M":m=p?l.getUTCMonth():l.getMonth();"F"==k?(m=Ea[m],k="s"):(m++,k="d");break;case "N":m=p?l.getUTCMinutes():l.getMinutes();k="d";
break;case "S":m=p?l.getUTCSeconds():l.getSeconds();k="d";break;case "T":m=p?"#":"";d+=isNaN(l.getTime())?void 0:this.J(this.J("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",m),l);continue;case "W":m=Fa[p?l.getUTCDay():l.getDay()];k="s";break;case "Y":m=p?l.getUTCFullYear():l.getFullYear(),0<t&&(m%=Math.pow(10,t),t=-1),k="d"}switch(k){case "b":d+=m?"true":"false";break;case "d":m=Math.trunc(m);case "f":m=+m;k=m+"";0<=t&&(k=m.toFixed(t));k.length<w&&(u?(0>m&&(w--,k=k.substr(1)),k=("0000000000"+k).slice(-w),
0>m&&(k="-"+k)):k=("          "+k).slice(-w));d+=k;break;case "j":d+=JSON.stringify(m,null,w||void 0);break;case "c":m="string"==typeof m?m[0]:String.fromCharCode(m);case "s":if(void 0!==m)for("string"!=typeof m&&(m=m.toString()),0<=t&&(m=m.substr(0,t));m.length<w;)m=0<=r.indexOf("-")?m+" ":" "+m;d+=m;break;case "o":x=8,p&&(A="0");case "X":v=Ga;case "x":k="";x||(x=16);!A&&p&&(A="0x");v||(v=Ha);"string"==typeof m&&(m=Number.parseInt(m,m.match(/(^0x|[a-f])/i)?16:10));u&&!w&&(w=Math.abs(m),w=255>=w?
2:65535>=w?4:4294967295>=w?8:9,w+=A.length);w-=A.length;do t=m&x-1,m>>>=16==x?4:3,u||!k||t||m?k=v[t]+k:(A&&(k=A+k,A=""),0<w&&(k=" "+k));while(0<--w||m);d+=A+k;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+k+")"}}}return d+=e[h]};var Da="",Ha="0123456789abcdef",Ga="0123456789ABCDEF",Fa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ea="January February March April May June July August September October November December".split(" ");q.StdIO=Ca;
var Ia=0,B={all:0xffffffffffff};function Ja(){this.Z={};this.va=[];this.oa=0;this.status="OK"}var Ka;n(Ja,Ca);
Ja.prototype.Ca=function(a,b){var c=this;switch(a){case La.Fb:b.onclick=function(){var d=c.La(La.Ua,!0);d&&(d.value="")};break;case La.Ua:b.value="",b.addEventListener("keydown",function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){var g=!1,h,k=b.value,l=k.lastIndexOf("\n");e==C.mb&&b.selectionStart<=l+1&&(g=!0);e==C.tc?(g=!0,0<c.oa&&(h=c.va[--c.oa])):e==C.Ib&&(g=!0,c.oa<c.va.length&&(h=c.va[++c.oa]||""));g&&d.preventDefault();void 0!=h&&(b.value=k.substr(0,l+1)+h)}}),b.addEventListener("keypress",
function(d){d=d||window.event;var e=d.which||d.keyCode;if(e){e=String.fromCharCode(e);var g=b.value,h=g.lastIndexOf("\n");b.selectionStart<=h&&b.setSelectionRange(g.length,g.length);d.stopPropagation();"@"==e&&0<c.oa&&h+1==g.length&&(b.value+=c.va[--c.oa],e="\r");"\r"==e&&(d.preventDefault(),g=b.value+="\n",b.blur(),b.focus(),(d=Ma(c,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&z(c,d.replace(/\n$/,""),!1))}})}};Ja.prototype.La=function(a){return this.Z[a]};
function Na(a){var b=Oa.nb;return Pa[a.N]&&Pa[a.N][b]}function Qa(a,b,c){if(a){do{for(var d=0;d<Ra.length;d++){var e=Ra[d];if(c){if(e+=c,b+e in a)return e}else if(e=e?e+b[0].toUpperCase():b[0],e+=b.substr(1),e in a)return e}if(0>b.indexOf("screen"))break;b=b.replace("screen","Screen")}while(1)}return null}function Sa(a){var b=Ta;return a.S.bindings&&a.S.bindings[b]}function Ua(a){if(a=a.Z[Va])var b=a.textContent;return b}function Wa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function D(a,b,c){a=a.S[b];void 0===a?a=c:(b=typeof c,typeof a!=b&&("boolean"==b?a=!!a:"number"==typeof c&&(a=+a)));return a}function Xa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Ya(){var a,b=Ka;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ka=b}return b}function Za(a){if(void 0===$a.cb){var b=!1;if(window)try{window.localStorage.setItem($a.Pa,$a.Pa),b=window.localStorage.getItem($a.Pa)==$a.Pa,window.localStorage.removeItem($a.Pa)}catch(c){z(a,c.message),b=!1}$a.cb=b}return!!$a.cb}
function ab(a){a=void 0===a?0:a;a%2&&a--;a=a||0;return-1==(a|1)||Ba(Ia,a)?!0:!1}function bb(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function cb(a){var b=null;if(Za(a)){var c;if(window)try{(c=window.localStorage.getItem(a.N))&&(b=JSON.parse(c))}catch(d){z(a,d.message)}}return b}
function db(a){if(window){var b=window.onresize;window.onresize="function"!==typeof b?a:function(){b&&b();a()}}}function eb(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function Ma(a,b){b=void 0===b?"?":b;try{if(b=b.trim())a.oa<a.va.length&&b==a.va[a.oa]?a.oa++:(a.va.push(b),a.oa=a.va.length);var c=b.split(" "),d=Na(a);switch(c[0]){case "m":var e="";var g=c[c.length-1].toLowerCase();var h=eb(g);void 0!=h?c.pop():1>=c.length&&(c=Object.keys(B));for(d=1;d<c.length;d++){g=c[d];var k=B[g];if(!k){e+="unrecognized message group: "+g+"\n";break}void 0!=h&&fb(a,k,h);e+=g+": "+ab(k)+"\n"}break;case "?":e="",gb.forEach(function(m){e+=m+"\n"}),e&&(e="default commands:\n"+e);
default:if(c.unshift(b),d)for(a=0;a<d.length;a++){var l=d[a](c);if(void 0!=l){e=e?e+l:l;break}}}}catch(m){e="error: "+m.message+"\n"}return e}Ja.prototype.Ba=function(a,b){void 0==b&&(b=ab(0x800000000000));if(!b){var c=this.La(La.Ua,!0);if(c){c.value+=a;8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096));c.scrollTop=c.scrollHeight;c.setSelectionRange(c.value.length,c.value.length);return}}Ca.prototype.Ba.call(this,a,b)};
Ja.prototype.O=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());ab(d)&&Ca.prototype.O.call.apply(Ca.prototype.O,[this,a].concat(ca(c)))};function hb(a,b){if(Za(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.N,b)}catch(c){z(a,c.message)}}}function ib(a,b,c){if(a=a.Z[b])a.textContent=c}
function fb(a,b,c){var d=!1;c?(c=Ia,Ia=(c|b)+(c/y|0|b/y|0)*y):(d=Ba(Ia,0x800000000000)&&Ba(b,0x800000000000),c=Ia,Ia=(c&~b)+((c/y|0)&~(b/y|0))*y);d&&a.flush()}
var La={Fb:"clear",Ua:"print"},gb=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m\t\tenable messages"],Oa={nb:"command"},jb={list:[],vc:"version"},$a={cb:void 0,Pa:"PCjs.localStorage"},C={mb:8,pc:9,Zb:10,Gb:13,cj:16,Lh:17,Fh:18,Si:19,Ih:20,Qh:27,nc:32,Vi:33,Ui:34,Oh:35,oi:36,Yb:37,tc:38,jc:39,ki:39,Ib:40,fi:44,Wi:44,pi:45,Nh:46,ji:46,ni:47,ZERO:48,ONE:49,rc:50,qc:51,Mb:52,Lb:53,mc:54,lc:55,Jb:56,bc:57,mi:59,hi:61,Bb:65,Cb:66,Db:67,Hb:68,E:69,Kb:70,Nb:71,Pb:72,Rb:73,Tb:74,Vb:75,Xb:76,
$b:77,ac:78,cc:79,dc:80,Q:81,hc:82,kc:83,oc:84,sc:85,uc:86,wc:87,xc:88,yc:89,zc:90,Jh:91,ii:91,di:92,Zi:93,li:93,si:96,Ji:96,ci:96,ti:97,Hi:97,ui:98,Gi:98,vi:99,Ni:99,wi:100,Ki:100,xi:101,Di:101,yi:102,Pi:102,zi:103,Ii:103,Ai:104,Ri:104,Bi:105,Oi:105,Mi:106,Ci:107,Qi:109,Ei:110,Fi:111,Rh:112,Vh:113,Wh:114,Xh:115,Yh:116,Zh:117,$h:118,ai:119,bi:120,Sh:121,Th:122,Uh:123,Li:144,aj:145,gi:173,bj:186,Ph:187,Kh:188,Mh:189,Ti:190,dj:191,Gh:192,ri:219,Hh:220,Yi:221,Xi:222,ei:224},E={},kb=(E[C.mb]="\b",E[C.pc]=
"\t",E[C.Zb]="\n",E[C.Gb]="\r",E[C.nc]=" ",E[C.ZERO]="0",E[C.ONE]="1",E[C.rc]="2",E[C.qc]="3",E[C.Mb]="4",E[C.Lb]="5",E[C.mc]="6",E[C.lc]="7",E[C.Jb]="8",E[C.bc]="9",E[C.Bb]="A",E[C.Cb]="B",E[C.Db]="C",E[C.Hb]="D",E[C.E]="E",E[C.Kb]="F",E[C.Nb]="G",E[C.Pb]="H",E[C.Rb]="I",E[C.Tb]="J",E[C.Vb]="K",E[C.Xb]="L",E[C.$b]="M",E[C.ac]="N",E[C.cc]="O",E[C.dc]="P",E[C.Q]="Q",E[C.hc]="R",E[C.kc]="S",E[C.oc]="T",E[C.sc]="U",E[C.uc]="V",E[C.wc]="W",E[C.xc]="X",E[C.yc]="Y",E[C.zc]="Z",E[C.Yb]="Left",E[C.jc]="Right",
E),Ra=["","moz","ms","webkit"],Pa={};q.WebIO=Ja;B.addr=1;B.bus=2;B.port=4;B.memory=8;B.cpu=16;B.video=32;B.monitor=64;B.screen=128;B.timer=256;B.event=512;B.key=1024;B.mouse=2048;B.touch=2048;B.warn=4096;B.halt=8192;B.buffer=0x800000000000;
function F(a,b,c,d){Ja.call(this);this.N=a;this.ga=b;lb(this,c);this.version=d||2;mb[this.N]||(mb[this.N]=[]);mb[this.N][this.ga]&&this.O("warning: machine configuration contains multiple '%s' devices\n",this.ga);mb[this.N][this.ga]=this;this.Sa={};this.Y=void 0}n(F,Ja);
function lb(a,b){b=void 0===b?{}:b;if(b.overrides){var c=Ya();for(g in c)if(0<=b.overrides.indexOf(g)){var d=c[g];if(d.match(/^[+-]?[0-9.]+$/))var e=Number.parseInt(d,10);else"true"==d?e=!0:"false"==d?e=!1:(e=d,d='"'+d+'"');b[g]=e;z(a,"overriding "+a.ga+" property '"+g+"' with "+d)}}a.S=b;c=b.bindings;var g=Array.isArray(c);for(var h in c){d=c[h];if(g)h=d;else if(d.match(/^[0-9]+$/)){e=+d;a.Z[h]=[];do{d=h+e++;d=document.getElementById(d);if(!d)break;a.Z[h].push(d)}while(1);continue}if(e=document.getElementById(d))a.Z[h]=
e,a.Ca(h,e)}if(a.version){h="";c=nb(a,a.N);if(c.version!=a.version){h="Machine";var k=c.version}else b.version&&b.version>a.version&&(h="Config",k=b.version);h&&(k="Error: "+a.J("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.fj,a.version,h,k)+"\n\nClearing your browser's cache may resolve the issue.",(b=jb.vc)&&0>jb.list.indexOf(b)&&(alert(k),jb.list.push(b)),z(a,k))}}function G(a,b,c,d){a.Sa[b]={get:c.bind(a),set:d.bind(a)}}
function ob(a,b){var c;try{var d=mb[a.N];if(d)for(c in d){var e=d[c];"Machine"!=e.S["class"]&&b(e)}}catch(g){a.O("error while enumerating device '%s': %s\n",c,g.message)}}F.prototype.La=function(a,b){b=void 0===b?!1:b;var c=Ja.prototype.La.call(this,a,b);if(void 0===c&&b){b=mb[this.N];for(var d in b)if(c=b[d].Z[a])break;c||(c=null);this.Z[a]=c}return c};function nb(a,b,c){var d=mb[a.N];d=d&&d[b]||null;if(!d&&(void 0===c||c))throw Error(a.J("unable to find device with ID '%s'",b));return d}
function pb(a,b,c){var d=null,e=mb[a.N];if(e)for(var g in e)if(e[g].S["class"]==b){if(d){d=null;break}d=e[g]}if(!d&&(void 0===c||c))throw Error(a.J("unable to find device with class '%s'",b));return d}function qb(a,b){return(a=a.Sa[b])&&a.get()}
F.prototype.O=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if("number"==typeof a&&Ia&1&&ab(a)&&(void 0===this.Y&&(this.Y=pb(this,"CPU")),this.Y)){a=c.shift();c=this.J.apply(this,[a].concat(ca(c))).trim();Ja.prototype.O.call(this,"%s at %#0x\n",c,this.Y.R);return}Ja.prototype.O.call.apply(Ja.prototype.O,[this,a].concat(ca(c)))};function rb(a,b){(a=mb[a.N])&&delete a[b]}function sb(a,b,c){(a=a.Sa[b])&&a.set(c)}var mb={};q.Device=F;
function tb(a,b,c){F.call(this,a,b,c);this.type="static"==c.type?ub:vb;this.j=c.addrWidth||16;this.i=Math.pow(2,this.j);this.h=this.i-1|0;this.b=c.blockSize||1024;this.b>this.i&&(this.b=this.i);this.o=this.i/this.b|0;this.c=Math.log2(this.b)|0;this.g=(1<<this.c)-1;this.f=c.dataWidth||8;this.l=Math.pow(2,this.f)-1;this.m=!1!==c.littleEndian;this.a=Array(this.o);a=new wb(a,b+"[NONE]",{size:this.b,bus:this.ga});for(b=0;b<this.i;b+=this.b)xb(this,b,this.b,yb.NONE,a);zb(this)}n(tb,F);
function xb(a,b,c,d,e){for(var g=0,h=b>>>a.c;0<c&&h<a.a.length;){var k=h*a.b,l=a.b-(b-k);l>c&&(l=c);var m=a.a[h];if(b!=k||l!=a.b||m&&m.type!=yb.NONE)return!1;m=a.ga+"["+Aa(a,b,16,a.j)+"]";if(e)if(e.size==a.b)b=e;else{var r=void 0;if(e.values&&(r=e.values.slice(g,g+l),r.length!=l))return!1;b=new wb(a.N,m,{type:d,ja:b,size:l,bus:a.ga,values:r})}else b=new wb(a.N,m,{type:d,ja:b,size:l,bus:a.ga});a.a[h]=b;b=k+a.b;c-=l;g+=l;h++}return!0}
function Ab(a,b){for(var c=yb.ic,d=0,e=0;e<a.a.length;e++){var g=a.a[e];g&&g.type&c&&(b(g),d++)}return d}f=tb.prototype;f.Da=function(){};f.gb=function(a){return a&&this.xa(a)?!0:!1};f.Ra=function(a){this.za(a)};f.xa=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(!(c.type<=yb.Va)&&c.xa){var d=a.shift();if(!c.xa(d))return!1}}return!0};f.za=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(!(c.type<=yb.Va)&&c.za){var d=[];c.za(d);a.push(d)}}};
f.ph=function(a){return this.a[a>>>this.c].$(a&this.g)};f.Bh=function(a,b){this.a[a>>>this.c].ba(a&this.g,b)};f.qh=function(a){return a&1?this.$(a+1&this.h)|this.$(a)<<this.f:this.a[a>>>this.c].qa(a&this.g)};f.rh=function(a){return a&1?this.$(a)|this.$(a+1&this.h)<<this.f:this.a[a>>>this.c].qa(a&this.g)};f.Ch=function(a,b){a&1?(this.ba(a,b>>this.f),this.ba(a+1&this.h,b&this.l)):this.a[a>>>this.c].ca(a&this.g,b)};
f.Dh=function(a,b){a&1?(this.ba(a,b&this.l),this.ba(a+1&this.h,b>>this.f)):this.a[a>>>this.c].ca(a&this.g,b)};function zb(a){a.$=a.ph;a.ba=a.Bh;a.m?(a.qa=a.rh,a.ca=a.Dh):(a.qa=a.qh,a.ca=a.Ch)}f.$a=function(a,b){return this.a[a>>>this.c].$a(b)?(zb(this),!0):!1};f.jb=function(a,b){return this.a[a>>>this.c].jb(b)?(zb(this),!0):!1};f.ab=function(a,b){return this.a[a>>>this.c].ab(b)?(zb(this),!0):!1};f.lb=function(a,b){return this.a[a>>>this.c].lb(b)?(zb(this),!0):!1};var ub=0,vb=1;q.Bus=tb;
function Bb(a,b,c){F.call(this,a,b,c);this.da=16;this.v=1;this.o=["(",")"];this.j={};a=this.Y=pb(this,"CPU");a.L=this;this.Sa=a.Sa;this.K=pb(this,"Input",!1);this.I=nb(this,this.Y.S.busIO,!1);this.b=nb(this,this.Y.S.busMemory);this.m=this.b.j;this.M=Math.pow(2,this.m)-1|0;this.L=0;this.c=[];for(var d in H)this.c[H[d]]=[];this.i=[];this.i[H.ua]=this.b;this.i[H.Qa]=this.b;this.i[H.Na]=this.I;this.i[H.Oa]=this.I;this.f=[];this.f[H.ua]=this.Ec.bind(this);this.f[H.Qa]=this.Fc.bind(this);this.f[H.Na]=this.Cc.bind(this);
this.f[H.Oa]=this.Dc.bind(this);this.a=[];this.h=0;this.time=pb(this,"Time");this.time.L.push(this.Ah.bind(this));this.s=Cb();this.l=0;this.g=[];this.u=!1;d=this.Ic.bind(this);a=Oa.nb;Pa[this.N]||(Pa[this.N]={});Pa[this.N][a]||(Pa[this.N][a]=[]);Pa[this.N][a].push(d)}n(Bb,F);function Db(a,b,c){b.X=b.X+c&a.b.h}function Cb(a){a=void 0===a?0:a;var b=Eb.fc;return"number"==typeof a?{X:a,ib:-1,type:b}:{X:a.X,ib:a.ib,type:a.type}}
function Fb(a,b){if(b){var c=0,d=b.charAt(c);var e=Cb();switch(d){case "&":c++;break;case "#":c++;e.type=Eb.gc;break;case "%":c++,d=b.charAt(c),"%"==d?c++:e.type=Eb.LINEAR}d=b.indexOf(":");0<=d&&(c=Gb(a,b.substring(c,d)),void 0!=c&&(e.ib=c),c=d+1);e.X=Gb(a,b.substring(c))&a.M}return e}function Hb(a,b,c){a.h++;var d=a.b.$(b.X);c&&Db(a,b,c);a.h--;return d}function Ib(a,b,c){if(32>=a.m)return b&c;b=Kb(a,b,0,!0);c=Kb(a,c,0,!0);return((b/y|0)&(c/y|0))*y+((b&c)>>>0)}
function Lb(a,b,c){if(32>=a.m)return b^c;b=Kb(a,b,0,!0);c=Kb(a,c,0,!0);return((b/y|0)^(c/y|0))*y+((b^c)>>>0)}
function Mb(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var g=b.pop();var h=b.pop();switch(e){case "*":h*=g;break;case "/":if(!g)return!1;h=Math.trunc(h/g);break;case "^/":if(!g)return!1;h%=g;break;case "+":h+=g;break;case "-":h-=g;break;case "<<":h<<=g;break;case ">>":h>>=g;break;case ">>>":h>>>=g;break;case "<":h=h<g?1:0;break;case "<=":h=h<=g?1:0;break;case ">":h=h>g?1:0;break;case ">=":h=h>=g?1:0;break;case "==":h=h==g?1:0;break;case "!=":h=h!=g?1:0;break;
case "&":h=Ib(a,h,g);break;case "!":case "|":e=h;32>=a.m?h=e|g:(e=Kb(a,e,0,!0),g=Kb(a,g,0,!0),h=(e/y|0|g/y|0)*y+((e|g)>>>0));break;case "^!":h=Lb(a,h,g);break;case "&&":h=h&&g?1:0;break;case "||":h=h||g?1:0;break;case ",,":h=Kb(a,h,18,!0)*Math.pow(2,18)+Kb(a,g,18,!0);break;case "_":case "^_":"^_"==e&&(g=35-(g&255));g&&(h=Kb(a,h,0,!0),h=0<g?h*Math.pow(2,g):Math.trunc(h/Math.pow(2,-g)));break;default:return!1}b.push(Kb(a,h))}return!0}
function Nb(a,b,c,d,e,g){var h,k=!1,l=0,m=[],r=[],w=a.da;for(a.da=e;c<d;){var t=b[c++].trim();var p=c<d?b[c++]:"";if(t){var u=void 0;var v=a;var x=t,A=g;l=void 0===l?0:l;if(void 0!=x){u=qb(v,x.toUpperCase());if(void 0==u)if(u=x,v.j[u]?u=v.j[u].value:(u=u.substr(0,6),u=v.j[u]&&v.j[u].value),void 0!=u){if(x=v.j[x]&&v.j[x].jj)A?A.push(x):(A=Gb(v,x,A),void 0!==A?u+=A:u=void 0)}else u=za(x,1<x.length||10<v.da?v.da:10);void 0!=u&&(u=Kb(v,Ob(v,u,l)))}v=u}else if("{"==p){t=1;for(v=c;c<d;)if(c++,p=c<b.length?
b[c++]:"","{"==p)t++;else if("}"==p&&!--t)break;v=Nb(a,b,v,c-1,a.da,g);null!=v&&l&&(v=Ob(a,v,l));t=c<d?b[c++].trim():"";p=c<d?b[c++]:""}else{if(" "==p)continue;if("^B"==p){a.da=2;continue}if("^O"==p){a.da=8;continue}if("^D"==p){a.da=10;continue}if(!(l&-1073741824)){if("+"==p)continue;if("-"==p){l=l<<2|1;continue}if("~"==p||"^-"==p){l=l<<2|2;continue}if("^L"==p){l=l<<2|3;continue}}k=!0;break}if(void 0===v)if(g)g.push(t),v=0;else{k=!0;g=[];break}m.push(Kb(a,v));if(" "==p)if(c<b.length-1&&!b[c])c++,
p=b[c++];else{k=!0;break}if(!p)break;v="<"==a.o[0]?Pb:Qb;if(!v[p]){k=!0;break}r.length&&v[p]<=v[r[r.length-1]]&&Mb(a,m,r,1);r.push(p);a.da="^_"==p?10:e;l=0}if(k||!Mb(a,m,r)||1!=m.length)k=!0;k?g||z(a,"parse error ("+(t||p)+")"):h=m.pop();a.da=w;return h}
function Rb(a,b,c,d,e){for(var g;0<=(g=b.indexOf(c));){for(var h=0,k=g+1,l=e;k<b.length;){var m=b[k++];if(m==c){l=-1;break}if(!l)break;l--;m=m.charCodeAt(0);7==d?m&=127:m=m-32&63;h=Kb(a,h*Math.pow(2,d)+m,d*e,!0)}if(0<=l){z(a,"parse error ("+c+b+c+")");return}b=b.substr(0,g)+Aa(a,h)+b.substr(k)}return b}
function Gb(a,b,c){var d=void 0;if(b){"{"!=a.o[0]&&(b=b.split(a.o[0]).join("{").split(a.o[1]).join("}"));b=Rb(a,b,'"',7,5);if(!b)return d;b=Rb(a,b,"'",6,6);if(!b)return d;16!=a.da&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);d=Nb(a,b,0,b.length,a.da,c)}return d}
function Ob(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-Kb(a,b);break;case 2:b=Lb(a,b,-1);break;case 3:for(d=35;0<=d&&!Ib(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function Kb(a,b,c,d){var e=b;c=c||a.m;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}f=Bb.prototype;
f.rb=function(a){function b(k){for(var l=0;l<k.length;l++)if(void 0!=k[l])return!1;return!0}if(-1>a)return Sb(this,this.rb);var c="";if(0<=a){var d=this.a[a];if(void 0!=d){c=d>>8;d&=255;var e=this.i[c];if(e){var g=this.c[c],h=g[d];void 0!=h?(h>=y&&(h=h-y|0),(c&1?e.lb(h,this.f[c]):e.ab(h,this.f[c]))?(g[d]=void 0,this.a[a]=void 0,b(g)&&(g.length=0,b(this.a)&&(this.a.length=0)),c=this.J("%2d: %s %#0x cleared\n",a,Tb[c],h),--this.L||this.u||(c+=Ub(this,!1))):c=this.J("invalid break address: %#0x\n",h)):
c=this.J("no break address at index: %d\n",a)}else c="invalid bus"}else c=this.J("invalid break index: %d\n",a)}else c="missing break index\n";return c};
f.fb=function(a,b){b=void 0===b?!1:b;if(-1>a)return Sb(this,this.fb,b);if(0<=a){var c=this.a[a];if(void 0!=c){var d=!0,e=c>>8;c&=255;var g=this.c[e],h=g[c];if(void 0!=h){var k=b?"enabled":"disabled";if(h<y){var l=h;b?d=!1:h=(h>>>0)+y}else l=h-y|0,b?h=l:d=!1;d?(g[c]=h,a=this.J("%2d: %s %#0x %s\n",a,Tb[e],l,k)):a=this.J("%2d: %s %#0x already %s\n",a,Tb[e],l,k)}else a=this.J("no break address at index: %d\n",a)}else a=this.J("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function Sb(a,b,c){for(var d="",e=0;e<a.a.length;e++)void 0!=a.a[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function Vb(a){for(var b="",c=0;c<a.a.length;c++){var d=a.a[c];if(void 0!=d){var e=d>>8;d=a.c[e][d&255];var g="enabled";d>=y&&(g="disabled",d=d-y|0);b+=a.J("%2d: %s %#0x %s\n",c,Tb[e],d,g)}}b||(b="no break addresses found\n");return b}
function Wb(a,b,c){function d(k,l){var m;for(m=0;m<a.a.length&&void 0!=a.a[m];m++);a.a[m]=k<<8|l;return m}function e(k,l){var m=k.indexOf(l.X);0>m&&(m=k.indexOf((l.X>>>0)+y));if(0<=m)m=-(m+1);else{for(m=0;m<k.length&&void 0!=k[m];m++);k[m]=l.X}return m}c=void 0===c?H.ua:c;var g="";if(b)if(g=a.i[c]){var h=e(a.c[c],b);0<=h?(g=c&1?g.jb(b.X,a.f[c]):g.$a(b.X,a.f[c]))?(h=d(c,h),g=a.J("%2d: %s %#0x set\n",h,Tb[c],b.X),a.L++||a.u||(g+=Ub(a,!0))):(g=a.J("invalid break address: %#0x\n",b.X),a.c[c][h]=void 0):
g=a.J("%s %#0x already set\n",Tb[c],b.X)}else g="invalid bus";else g="missing break address\n";return g}f.Cc=function(a,b,c){this.h||(void 0==a?Xb(this,this.J("break on unknown input %#0x: %#0x",b,c)):(a+=b,0<=this.c[H.Na].indexOf(a)&&Xb(this,this.J("break on input %#0x: %#0x",a,c))))};f.Dc=function(a,b,c){this.h||(void 0==a?Xb(this,this.J("break on unknown output %#0x: %#0x",b,c)):(a+=b,0<=this.c[H.Oa].indexOf(a)&&Xb(this,this.J("break on output %#0x: %#0x",a,c))))};
f.Ec=function(a,b,c){this.h||(void 0==a?Xb(this,this.J("break on unknown read %#0x: %#0x",b,c)):(a+=b,this.g.length&&0==(a-this.Y.l&-4)&&(this.g[this.l++]=a,this.l==this.g.length&&(this.l=0)),0<=this.c[H.ua].indexOf(a)&&Xb(this,this.J("break on read %#0x: %#0x",a,c))))};f.Fc=function(a,b,c){this.h||(void 0==a?Xb(this,this.J("break on unknown write %#0x: %#0x",b,c)):(a+=b,0<=this.c[H.Qa].indexOf(a)&&Xb(this,this.J("break on write %#0x: %#0x",a,c))))};function Xb(a,b){z(a,b);Yb(a.time)}
function Zb(a,b){return Aa(a,b.X,a.da,a.b.j,"")}function $b(a,b){var c=void 0===c?10:c;var d="";0>b&&(b=c);b=a.l-b;0>b&&(b+=a.g.length);for(var e,g=[];0<=b&&b<a.g.length&&0<c;){var h=a.g[b++];if(b==a.g.length){if(d)break;b=0}if(void 0!=h||g.length){e||(e=Cb(h));if(h!=e.X||g.length==a.v)Db(a,e,-g.length),d+=a.kb(e,g),c--;void 0!=h&&(e.X=h,g.push(Hb(a,e,1)))}}return d||"no history"}
function ac(a,b,c){var d=[],e="";for(b="number"==typeof b?Cb(b):b;c--;){for(Db(a,b,d.length);d.length<a.v;)d.push(Hb(a,b,1));Db(a,b,-d.length);e+=a.kb(b,d)}return e}
function bc(a,b,c,d,e){var g="";c||(c=a.b.f);var h=c>>3;d||(d=128);var k=0,l=d+15>>4||1,m=4==h?16:a.da;"y"==e&&(m=h,l=d,k=8*h);b||(b=a.s);for(;l--&&0<d;){var r=e=0,w,t="",p="",u=Zb(a,b);for(w=m;0<w&&0<d;w--){var v=Hb(a,b,1);e|=v<<(r++<<3);r==h&&(t+=Aa(a,e,0,c,""),t+=1==h?9==w?"-":" ":" ",k&&(p+=Aa(a,e,2,c,"")),e=r=0);k||(p+=32<=v&&127>v?String.fromCharCode(v):".");d--}g&&(g+="\n");g+=u+"  "+t+" "+p}a.s=b;return g}
function cc(a){var b=[];ob(a,function(c){c.Ra&&c.Ra(b);c.Sb&&c.Sb(b)});return JSON.stringify(b,null,2)}function dc(a,b,c){for(var d=0,e="",g=0;void 0!=b&&g<c.length;g++){var h=Hb(a,b);if(void 0==h)break;var k=a,l=b,m=c[g];k.h++;k.b.ba(l.X,m);k.h--;e+=a.J("%#06x: %#0x changed to %#0x\n",b.X,h,c[g]);Db(a,b,1);d++}d||(e+=a.J("%d locations updated\n",d));ec(a.time);return e}
function Ub(a,b){if(void 0==b)return"unrecognized option";Ab(a.b,function(c){b?a.b.$a(c.ja,a.f[H.ua]):a.b.ab(c.ja,a.f[H.ua])})&&(a.l=0,a.g=b?Array(fc):[]);return a.J("instruction history %s\n",b?"enabled":"disabled")}
f.Ic=function(a){var b="",c=[];var d=a[1];if("*"==a[2])var e=-2;else{e=za(a[2]);void 0==e&&(e=-1);var g=Fb(this,a[2])}var h=0;a[3]&&(h=za(a[3].substr("l"==a[3][0]?1:0))||8);for(var k=3;k<a.length;k++)c.push(za(a[k],16));switch(d[0]){case "b":"c"==d[1]?b=this.rb(e):"d"==d[1]?b=this.fb(e):"e"==d[1]?b=this.fb(e,!0):"i"==d[1]?b=Wb(this,g,H.Na):"l"==d[1]?b=Vb(this):"o"==d[1]?b=Wb(this,g,H.Oa):"r"==d[1]?b=Wb(this,g,H.ua):"w"==d[1]?b=Wb(this,g,H.Qa):(b="break commands:\n",gc.forEach(function(l){b+=l+"\n"}));
break;case "d":if("b"!=d[1]&&d[1])if("w"==d[1])c=16;else if("d"==d[1])c=32;else{"h"==d[1]?b=$b(this,e):"s"==d[1]?b=cc(this):(b="dump commands:\n",hc.forEach(function(l){b+=l+"\n"}));break}else c=8;b=bc(this,g,c,h,d[2]);break;case "e":b=dc(this,g,c);break;case "g":this.time.start()?(void 0!=g&&Wb(this,g),this.K&&ic(this.K)):b="already started\n";break;case "h":Yb(this.time)||(b="already stopped\n");break;case "p":a.shift();a.shift();d=a.join(" ");b+=this.J("%s = %s\n",d,Aa(this,Gb(this,d)));break;
case "r":if(h=d.substr(1).toUpperCase()){if(void 0==qb(this.Y,h)){b+=this.J("unrecognized register: %s\n",h);break}void 0!=g&&sb(this.Y,h,g.X)}b+=this.Y.toString(d[1]);break;case "s":g=eb(a[2]);"h"==d[1]?(this.u=g,b=Ub(this,g)):(b="set commands:\n",jc.forEach(function(l){b+=l+"\n"}));break;case "t":h=za(a[2],10)||1;kc(this.time,h);break;case "u":h||(h=8);g||(g=this.s);b+=ac(this,g,h);this.s=g;break;case "?":b="debugger commands:\n";lc.forEach(function(l){b+=l+"\n"});break;default:b=void 0}void 0==
b&&a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n");return b};f.kb=function(a,b){var c=this;return this.J("%s %02x         unsupported\n",Zb(this,a),function(){var d=b.shift();Db(c,a,1);return d}())};f.Ah=function(a){a&&!this.time.a&&(this.Y.Ba(this.Y.toString()),(a=this.La(La.Ua,!0))&&a.focus())};
var lc="b?\t\tbreak commands;d?\t\tdump commands;e [addr] ...\tedit memory;g [addr]\trun (to addr);h\t\thalt;p [expr]\tparse expression;r? [value]\tdisplay/set registers;s?\t\tset commands;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";"),gc="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write".split(";"),
hc="db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),jc=["sh [on|off]\tset instruction history"],Eb={LINEAR:1,fc:0,gc:2,$i:0},H={ua:0,Qa:1,Na:2,Oa:3},mc={},Tb=(mc[H.ua]="br",mc[H.Qa]="bw",mc[H.Na]="bi",mc[H.Oa]="bo",mc),nc={ec:"PC"},fc=1E5,Qb={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,
">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},Pb={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};q.DbgIO=Bb;
function wb(a,b,c){F.call(this,a,b,c);this.ja=c.addr;this.size=c.size;this.type=c.type||yb.NONE;this.j=(a=this.S.bus)?nb(this,a):pb(this,a="Bus");if(!this.j)throw Error(this.J("unable to find bus '%s'",a));this.b=this.j.f;this.s=Math.pow(2,this.b)-1;this.U=Math.pow(2,2*this.b)-1;this.f=!1!==this.j.m;this.values=this.M=this.c=this.L=null;a=this.f?this.xh:this.wh;if(b=8==this.b)b=nb(this,this.N),b=!1!==(b&&b.S&&b.S.ArrayBuffer);b&&(this.c=new ArrayBuffer(this.size),this.L=new DataView(this.c,0,this.size),
this.values=new Uint8Array(this.c,0,this.size),this.M=new Uint16Array(this.c,0,this.size>>1),new Int32Array(this.c,0,this.size>>2),a=this.f==ua?this.uh:this.vh);this.l=!1;oc(this,c.values);switch(this.type){case yb.NONE:this.$=this.sh;this.ba=this.bb;this.qa=this.th;this.ca=this.bb;break;case yb.Va:this.$=this.hb;this.ba=this.bb;this.qa=a;this.ca=this.bb;break;case yb.Wa:this.$=this.hb,this.ba=this.vb,this.qa=a,this.ca=this.zb}this.m=this.o=0;this.v=this.K=this.u=this.I=null}n(wb,F);
function oc(a,b){if(!a.values)b?a.values=b:a.values=Array(a.size).fill(a.s);else if(b)for(var c=0;c<a.size;c++)a.values[c]=b[c]}f=wb.prototype;f.Da=function(){this.type>=yb.Wa&&this.values.fill(0)};f.sh=function(){return this.s};f.th=function(){return this.U};f.hb=function(a){return this.values[a]};f.wh=function(a){return this.values[a+1]|this.values[a]<<this.b};f.xh=function(a){return this.values[a]|this.values[a+1]<<this.b};f.uh=function(a){return this.M[a>>>1]};
f.vh=function(a){return this.L.getUint16(a,this.f)};f.bb=function(){};f.Eh=function(a,b){this.values[a]=b};f.vb=function(a,b){this.values[a]=b;this.l=!0;this.ba=this.Eh};f.yb=function(a,b){this.values[a]=b>>this.b;this.values[a+1]=b&this.s};f.Ab=function(a,b){this.values[a]=b&this.s;this.values[a+1]=b>>this.b};f.wb=function(a,b){this.M[a>>>1]=b};f.xb=function(a,b){this.L.setUint16(a,b,this.f)};
f.zb=function(a,b){this.c?this.f==ua?(this.wb(a,b),this.ca=this.wb):(this.xb(a,b),this.ca=this.xb):this.f?(this.Ab(a,b),this.ca=this.Ab):(this.yb(a,b),this.ca=this.yb)};f.$a=function(a){if(!this.m){var b=this;this.m=1;this.h=a;this.u=this.$;this.v=this.qa;this.$=function(c){var d=b.u(c);b.h(b.ja,c,d);return d};this.qa=function(c){var d=b.v(c);b.h(b.ja,c,d);b.h(b.ja,c+1,d);return d};return!0}return this.h==a?(this.m++,!0):!1};
f.jb=function(a){if(!this.o){var b=this;this.o=1;this.i=a;this.I=this.ba;this.K=this.ca;this.ba=function(c,d){b.i(b.ja,c,d);b.I(c,d)};this.ca=function(c,d){b.i(b.ja,c,d);b.i(b.ja,c+1,d);b.K(c,d)};return!0}return this.i==a?(this.o++,!0):!1};f.ab=function(a){return this.m&&this.h==a?(--this.m||(this.$=this.u,this.qa=this.v,this.u=this.v=this.h=void 0),!0):!1};f.lb=function(a){return this.o&&this.i==a?(--this.o||(this.ba=this.I,this.ca=this.K,this.I=this.K=this.i=void 0),!0):!1};
f.xa=function(a){var b=a.shift();if(this.ga==b){this.l=a.shift();a.shift();a=a.shift();var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],g=a[d++];e--;)c[b++]=g;a=c}oc(this,a);return!0}return!1};f.za=function(a){a.push(this.ga);a.push(this.l);a.push(!1);for(var b=this.values,c=0,d=0,e=[];c<b.length;){for(var g=b[c],h=c+1;h<b.length&&b[h]===g;)h++;e[d++]=h-c;e[d++]=g;c=h}a.push(e.length>=b.length?b:e)};var yb={NONE:1,Va:2,Wa:4,ic:14,ej:12};
q.Memory=wb;function pc(a,b,c){wb.call(this,a,b,c)}n(pc,wb);q.Port=pc;
function qc(a,b,c){F.call(this,a,b,c);this.time=pb(this,"Time");this.ha=pb(this,"Machine");this.K=null;this.Ha=D(this,"drag",!1);this.ea=D(this,"scroll",!1);this.ra=D(this,"hexagonal",!1);this.c=D(this,"buttonDelay",0);this.g=!1;if((this.a=this.S.map)&&!this.a.length)for(a=Object.keys(this.a),b=0;b<a.length;b++){c=[];var d=a[b],e=this.a[d];"string"==typeof e?e=[e]:void 0==e.length&&(c=e.grid,e=e.keys,"string"==typeof e&&(e=[e]));this.a[d]={keys:e,ij:c,state:0}}this.b=null;(a=this.Z[rc])&&sc(this,
a,this.Z[tc],this.S.location);this.L=[];this.M=[];this.R=this.ka=-1}n(qc,F);function uc(a,b){a.K=b}function vc(a,b,c){for(var d=0;d<a.L.length;d++){var e=a.L[d];e.id==b&&e.sb(b,c)}}
function sc(a,b,c,d){d=void 0===d?[]:d;a.Ja=d[0]||0;a.Ka=d[1]||0;a.f=d[2]||b.clientWidth;a.l=d[3]||b.clientHeight;a.m=d[4]||1;a.u=d[5]||1;a.Fa=d[6]||b.naturalWidth||a.f;a.Aa=d[7]||b.naturalHeight||a.l;a.ma=d[8]||0;a.na=d[9]||0;a.Ea=d[10]||0;a.Ga=d[11]||0;a.a&&a.a.length?(a.s=a.a.length,a.i=a.a[0].length):(a.i=a.m,a.s=a.u,a.m=a.u=0);a.T=a.f/(a.i+a.i*a.m)|0;a.U=a.l/(a.s+a.s*a.u)|0;a.ta=a.T*a.m|0;a.W=a.U*a.u|0;a.j=a.v=-1;wc(a,b);xc(a,b);a.time&&(a.c&&(a.la=yc(a.time,"timerInputRelease",function(){0>
a.j&&0>a.v&&zc(a,-1,-1)})),a.a&&(a.c&&(a.Ia=yc(a.time,"timerKeyRelease",function(){Ac(a)})),a.h=0,a.I="",a.o=[],Bc(a,c?document:b),!a.b&&c&&(a.b=c)))}function Cc(a){a.c?Dc(a.time,a.Ia,a.c):Ac(a)}
function Bc(a,b){b.addEventListener("keydown",function(c){c=c||window.event;var d=document.activeElement;if(!a.b||d==a.b){d=c.which||c.keyCode;var e=kb[d],g=!1;e&&(g=Ec(a,e,!0));a.O(1536,"onKeyDown(keyCode=%#04x): %5.2f (%s)\n",d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()}});b.addEventListener("keypress",function(c){c=c||window.event;var d=c.which||c.charCode,e=String.fromCharCode(d),g=!1;e&&(g=Ec(a,e.toUpperCase()));a.O(1536,"onKeyPress(charCode=%#04x): %5.2f (%s)\n",
d,Date.now()/1E3%60,e?g?"used":"unused":"ignored");g&&c.preventDefault()});b.addEventListener("keyup",function(c){c=c||window.event;var d=document.activeElement;a.b&&d!=a.b||(c=c.which||c.keyCode,(d=kb[c])&&Ec(a,d,!1),a.O(1536,"onKeyUp(keyCode=%#04x): %5.2f (ignored)\n",c,Date.now()/1E3%60))})}
function wc(a,b){b.addEventListener("mousedown",function(c){if(!a.g){if(a.b){var d=window.scrollX,e=window.scrollY;a.b.focus();window.scrollTo(d,e)}c.button||Fc(a,b,Gc,c)}});b.addEventListener("mousemove",function(c){a.g||Fc(a,b,Hc,c)});b.addEventListener("mouseup",function(c){a.g||c.button||Fc(a,b,Ic,c)});b.addEventListener("mouseout",function(c){a.g||(0>a.j?Fc(a,b,Hc,c):Fc(a,b,Ic,c))})}
function xc(a,b){b.addEventListener("touchstart",function(c){a.ea&&(a.g=!0);Fc(a,b,Gc,c)});b.addEventListener("touchmove",function(c){Fc(a,b,Hc,c)});b.addEventListener("touchend",function(c){Fc(a,b,Ic,c)})}
function Ec(a,b,c){if(a.a)if(a.a.length){if(!1===c)return!0;for(c=0;c<a.a.length;c++)for(var d=a.a[c],e=0;e<d.length;e++)if(0<=d[e].split("|").indexOf(b))return a.h?16>a.o.length&&a.o.push(b):(a.h=1,a.I=b,zc(a,e,c),vc(a,b,!0),Cc(a)),!0}else if(void 0!=c)for(d=Object.keys(a.a),e=0;e<d.length;e++){var g=d[e];if(0<=a.a[g].keys.indexOf(b))return vc(a,g,c),a.a[g].state=c?1:0,!0}return!1}function Ac(a){1==a.h?(a.h++,vc(a,a.I,!1),a.I="",zc(a,-1,-1),Cc(a)):(a.h=0,a.o.length&&Ec(a,a.o.shift()))}
function Fc(a,b,c,d){var e=-1,g=-1,h=!1,k;if(c<Ic){d=d||window.event;if(d.targetTouches&&d.targetTouches.length){var l=d.targetTouches[0].pageX;var m=d.targetTouches[0].pageY;h=1<d.targetTouches.length}else l=d.pageX,m=d.pageY;var r=k=0;var w=b;do isNaN(w.offsetLeft)||(k+=w.offsetLeft,r+=w.offsetTop);while(w=w.offsetParent);l=a.Fa/b.offsetWidth*(l-k)|0;m=a.Aa/b.offsetHeight*(m-r)|0;var t=l-a.Ja;var p=m-a.Ka;r=k=!1;w=l>=a.ma&&l<a.ma+a.Ea&&m>=a.na&&m<a.na+a.Ga;if(0<=t&&t<a.f&&0<=p+a.W||w)if(h||a.ea||
d.preventDefault(),0<=t&&t<a.f&&0<=p&&p<a.l){r=!0;d=a.f/a.i|0;var u=a.l/a.s|0,v=t/d|0,x=p/u|0;!a.ra||x&1||(t-=d>>1,v=t/d|0,v==a.i-1&&(t=-1));u=x*u+(a.W>>1);t-=v*d+(a.ta>>1);p-=u;0<=t&&t<a.T&&0<=p&&p<a.U&&(e=v,g=x,k=!0)}}t=t||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Gc||c==Ic)for(v=0;v<a.M.length;v++)x=a.M[v],c==Ic?x.sb(x.id,!1):(u=p/(b/x.hj|0)|0,(t/(d/x.gj|0)|0)==x.lj&&u==x.mj&&x.sb(x.id,!0));if(!h)if(c==Gc)a.j=l,a.v=m,r?(zc(a,e,g),k&&a.c&&Dc(a.time,a.la,a.c,!0)):w&&a.ha.pa();else if(c==Hc)0<=
a.j&&0<=a.v&&a.Ha?zc(a,e,g):a.K&&a.K(e,g);else if(c==Ic){if(c=a.c)c=a.time,e=a.la,c=c.a&&0<e&&e<=c.b.length?0<=c.b[e-1].fa:!1;c||zc(a,-1,-1);a.j=a.v=-1}else z(a,"unrecognized action: "+c)}function ic(a){a.b&&a.ha.a&&a.b.focus()}function zc(a,b,c){if(b!=a.R||c!=a.ka)a.R=b,a.ka=c}var Gc=1,Hc=2,Ic=3,tc="power",rc="surface";q.Input=qc;
function Jc(a,b,c){F.call(this,a,b,c);a=this.Z[Kc];if(!a)throw Error("LED binding for '"+Kc+"' missing: '"+this.S.Z[Kc]+"'");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.type=Wa(D(this,"type",Lc),Mc,Nc);this.f=Oc[this.type][0];this.j=Oc[this.type][1];this.width=D(this,"width",this.f);this.height=D(this,"height",this.j);this.g=D(this,"cols",1);this.s=this.g+D(this,"colsExtra",
0);this.T=D(this,"rows",1);this.I=this.T+D(this,"rowsExtra",0);this.W=this.width*this.g;this.L=this.height*this.T;this.i=Pc("black",0);this.c=Qc(this.S.color)||this.i;this.la=Pc(this.c,1,.25);this.ka=Pc(this.c,1,2);this.h=Qc(this.S.backgroundColor);this.ma=D(this,"fixed",!1);this.ma||(b.style.width="100%",b.style.height="auto");this.ha=D(this,"hexagonal",!1);this.na=D(this,"highlight",!0);this.K=D(this,"persistent",this.type<Nc);b.setAttribute("width",this.W.toString());b.setAttribute("height",this.L.toString());
b.style.backgroundColor=this.i;a.appendChild(b);this.ea=b.getContext("2d");if(this.l=document.createElement("canvas"))this.l.width=this.U=this.f*this.g,this.l.height=this.m=this.j*this.T,this.b=this.l.getContext("2d");this.ra=(this.I+1)*this.s*4;this.a=Array(this.ra);this.ta=this.g<this.s?4*(this.s-this.g):0;this.u=this.v=!1;this.o=this.R=0;this.M=-1;var d=this;this.time=pb(this,"Time");Rc(this.time,function(e){Sc(d,!1,e)})}n(Jc,F);
function Tc(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,g=c;e[g]=d.type<Nc?Uc:" ";e[g+1]=d.c==d.i?null:d.c;e[g+2]=0;e[g+3]=Vc}a.u=a.v=!0;Sc(a,!0)}function Wc(a){a.h?(a.b.fillStyle=a.h,a.b.fillRect(0,0,a.U,a.m)):a.b.clearRect(0,0,a.U,a.m)}
function Sc(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.u||b){if(a.type<Nc){var d=0;if(!a.K||b)Wc(a);else if(a.o){d=a.g-a.o;var e=a.f*d;a.b.drawImage(a.l,a.f*a.o,0,e,a.m,0,0,e,a.m)}for(var g=e=0;g<a.I;g++){for(var h=0;h<a.g;h++){var k=a.a[e],l=a.a[e+1]||a.i,m=a.na&&e==a.M;if(a.a[e+3]&Vc||m||b){if(h>=d)a:{var r=a,w=k;k=l;var t=h;l=g;var p=m;t=void 0===t?0:t;l=void 0===l?0:l;p=void 0===p?!1:p;var u=0;if(r.ha&&!(l&1)&&(u=r.f>>1,t==r.g-1))break a;if(k&&k!=r.c){p=p?Pc(k,1,2):k;var v=Pc(k,1,.25)}else p=
p?r.ka:r.c,v=r.la;k=!1;w=w?p:v;p==r.i&&(w=r.h,k=!0);p=t*r.f+u;v=l*r.j;r.K&&(t=t*r.f+u,l*=r.j,r.h?(r.b.fillStyle=r.h,r.b.fillRect(t,l,r.f,r.j)):r.b.clearRect(t,l,r.f,r.j));r.b.fillStyle=w;l=Xc[r.type];3==l.length?(r.b.beginPath(),r.b.arc(p+l[0],v+l[1],l[2],0,2*Math.PI),k?(r.b.globalCompositeOperation="destination-out",r.b.fill(),r.b.globalCompositeOperation="source-over"):r.b.fill()):r.b.fillRect(p+l[0],v+l[1],l[2],l[3])}a.a[e+3]=m?a.a[e+3]|Vc:a.a[e+3]&~Vc}e+=4}e+=a.ta}a.o=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&Yc&&(b+=".");Wc(a);for(g=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;h=a;m=e;r=g;m=void 0===m?0:m;r=void 0===r?0:r;if(l=Zc[l])for(k=0;k<l.length;k++)if(t=h,u=$c[l[k]]){w=(void 0===m?0:m)*t.f;p=(void 0===r?0:r)*t.j;t.b.fillStyle=t.c;t.b.beginPath();if(3==u.length)t.b.arc(w+u[0],p+u[1],u[2],0,2*Math.PI);else for(v=0;v<u.length;v+=2)v?t.b.lineTo(w+u[v],p+u[v+1]):t.b.moveTo(w+u[v],p+u[v+1]);t.b.closePath();t.b.fill()}if(++e==a.g&&(e=0,++g==a.I))break}}a.ea.globalCompositeOperation=
a.h&&a.c!=a.i?"source-over":"copy";a.ea.drawImage(a.l,0,0,a.U,a.m,0,0,a.W,a.L);a.u=!1;a.M=-1}else a.K||a.v||(!c||!a.R||c-a.R>=(1E3/60|0))&&Tc(a);a.v=!1;c&&(a.R=c)}function Qc(a){return(a=a||void 0)&&ad[a]||a}
function Pc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=ad[a]||a;var e=a;var g=16;var h=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);h||(g=10,h=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(h){for(e=1;e<h.length;e++)d[e-1]=Number.parseInt(h[e],g);d.length=e-1;g=!0}else g=!1;if(g){a="rgba(";for(g=0;3>g;g++)h=Math.round(d[g]*c),h=0>h?0:255<h?255:h,a+=h+",";a+=(g<d.length?d[g]:b)+")"}}return a}
Jc.prototype.xa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.h&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.i&&(this.a[b+1]=null);Sc(this,!0);return!0}return!1};Jc.prototype.za=function(a){this.a&&(a.push(this.c),a.push(this.h),a.push(this.a))};
var Mc=0,Lc=1,Nc=3,Kc="container",ad={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",
darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",
goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",
lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",
olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",
slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},Uc=0,Yc=1,Vc=128,bd={},Xc=(bd[Mc]=[4,4,4],bd[Lc]=[16,16,14],bd[2]=[2,2,28,28],bd),Oc=[[8,8],[32,32],[32,32],[96,128]],$c={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,
91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Zc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};
q.LED=Jc;
function cd(a,b,c){F.call(this,a,b,c);var d=this;this.na=document.fullscreenEnabled||bb("Edge/");this.l=c.monitorWidth||640;this.h=c.monitorHeight||480;if(a=this.Z[dd.ob])this.b=a;else throw Error("unable to find monitor container: "+dd.ob);var e=this.Z[dd.Eb];e||(e=document.createElement("canvas"),e.setAttribute("class","pcjs-monitor"),e.setAttribute("width",c.monitorWidth),e.setAttribute("height",c.monitorHeight),e.style.backgroundColor=c.monitorColor||"black",a.appendChild(e));this.c=e;this.g=
b=e.getContext("2d");bb("MSIE")&&(a.onresize=function(l,m,r,w){return function(){m.style.height=(l.clientWidth*w/r|0)+"px"}}(a,e,c.monitorWidth,c.monitorHeight),a.onresize());var g=+(c.aspect||Ya().aspect);g&&.3<=g&&3.33>=g&&(db(function(l,m,r){return function(){m.style.height=(l.clientWidth/r|0)+"px"}}(a,e,g)),window.onresize());if(this.S.touchtype){var h=document.createElement("textarea");h.setAttribute("class","pcjs-overlay");bb("iOS")&&(h.setAttribute("autocorrect","off"),h.setAttribute("autocapitalize",
"off"),h.style.fontSize="16px");a.appendChild(h)}if(this.s=pb(this,"Input",!1))this.Ob=h||a,sc(this.s,this.Ob,this.La(ed,!0));this.Ja=this.l;this.Ka=this.h;h=c.smoothing;(e=Ya().smoothing)&&(h="true"==e);this.ma=h;this.Ga=Qa(b,"imageSmoothingEnabled");if(this.a=c.monitorRotate)this.a=this.a%360,0<this.a&&(this.a-=360),-90!=this.a?(this.O("unsupported monitor rotation: %d\n",this.a),this.a=0):(b.translate(0,this.h),b.rotate(this.a*Math.PI/180),b.scale(this.h/this.l,this.l/this.h));if(b=this.Z[dd.pb])if(c=
Qa(a,"requestFullscreen")){a.Xa=a[c];if(c=Qa(document,"on","fullscreenchange")){var k=Qa(document,"fullscreenElement");document.addEventListener(c,function(){fd(d,null!=document[k])},!1)}(c=Qa(document,"on","fullscreenerror"))&&document.addEventListener(c,function(){fd(d)},!1)}else this.O("Full-screen API not available\n"),b.parentNode.removeChild(b)}n(cd,F);cd.prototype.Ca=function(a,b){var c=this;switch(a){case dd.pb:b.onclick=function(){c.Xa()}}F.prototype.Ca.call(this,a,b)};
function gd(a){a.g&&(a.g.fillStyle="black",a.g.fillRect(0,0,a.c.width,a.c.height))}
cd.prototype.Xa=function(){var a=!1;if(this.b){if(this.b.Xa){a="100%";if(screen&&screen.width&&screen.height){var b=screen.width/screen.height,c=this.l/this.h;b>c&&(a=Math.round(c/b*100)+"%")}this.na?(this.c.style.width=a,this.c.style.height="auto",this.c.style.display="block",this.c.style.margin="auto"):(this.b.style.width=a,this.b.style.height="auto");this.b.style.backgroundColor="black";this.b.Xa();a=!0}this.s&&ic(this.s)}return a};
function fd(a,b){!b&&a.b&&(a.na?a.c.style.width=a.c.style.height="":a.b.style.width=a.b.style.height="")}cd.prototype.pa=function(a){a?(hd(this),id(this)):gd(this)};cd.prototype.Da=function(){gd(this)};var dd={Eb:"canvas",ob:"container",pb:"fullScreen"};q.Monitor=cd;function jd(a,b,c){c.type=yb.Wa;wb.call(this,a,b,c);xb(this.j,c.addr,c.size,c.type,this)}n(jd,wb);q.RAM=jd;
function kd(a,b,c){c.type=yb.Va;wb.call(this,a,b,c);c.revision&&(this.status="revision "+c.revision+" "+this.status);xb(this.j,c.addr,c.size,c.type,this);if(q.LED&&this.Z[Ta]){var d=this;this.g=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.R=this.values.length/this.g|0;this.a=new Jc(a,b+"LEDs",{"class":"LED",bindings:{container:Sa(this)},type:Lc,cols:this.g,rows:this.R,color:D(this,"colorROM","green"),backgroundColor:D(this,"backgroundColorROM","black"),persistent:!0}),Tc(this.a);this.T=
new qc(a,b+"Input",{"class":"Input",location:[0,0,this.a.W,this.a.L,this.g,this.R],bindings:{surface:Sa(this)}});this.W=Ua(this)||"";uc(this.T,function(e,g){if(d.Y){var h=d.W;0<=e&&0<=g&&(e=g*d.g+e,g=d.Y,h=g.L&&ac(g.L,d.ja+e,1)||"");ib(d,Va,h)}})}}n(kd,wb);
kd.prototype.xa=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.a.length==d?(this.a.a=c,Sc(this.a,!0)):(this.O("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.O("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};kd.prototype.pa=function(){this.Y||(this.Y=pb(this,"CPU"))};
kd.prototype.hb=function(a){if(this.a){var b=this.a,c=Vc;c=(void 0===c?0:c)&129;var d=4*((a/this.g|0)*b.s+a%this.g);if(d<=b.a.length-4){if(1!==b.a[d]||(b.a[d+3]&129)!==c)b.a[d]=1,b.a[d+3]=b.a[d+3]&-130|c|Vc,b.u=!0;b.M=d;b.v=!0;b.o=0}}return this.values[a]};kd.prototype.za=function(a){this.a&&(a.push(this.a.a),a.push(this.values))};var Ta="array",Va="cellDesc";q.ROM=kd;
function ld(a,b,c){F.call(this,a,b,c);this.ra=D(this,"cyclesMinimum",1E5);this.Ha=D(this,"cyclesMaximum",3E6);this.T=Wa(D(this,"cyclesPerSecond",65E4),this.ra,this.Ha);this.K=Wa(D(this,"yieldsPerSecond",md),30,120);this.Ia=Wa(D(this,"yieldsPerUpdate",nd),1,this.K);this.la=(this.v=D(this,"clockByFrame",120>=this.T))||D(this,"requestAnimationFrame",!0);this.Fa=this.Ga=this.ea=1;this.ma=this.T/1E4/100;this.h=this.m=this.ma*this.ea;this.s=0;this.ha=Math.round(1E3/this.K);this.ka=[];this.u=[];this.b=[];
this.L=[];this.Ea=this.a=this.M=this.l=!1;this.I=this.g=0;this.Ka=this.yh.bind(this);this.Ja=this.qb.bind(this);this.ta=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.setTimeout).bind(window);if(this.v)this.f=this.Aa=0;else{var d=this;yc(this,"timerYield",function(){od(d)},this.ha)}this.U=this.R=this.j=0;pd(this)||qd(this,this.Fa)}n(ld,F);function Rc(a,b){a.ka.push(b)}f=ld.prototype;
f.Ca=function(a,b){var c=this;switch(a){case rd:b.onclick=function(){sd(c)&&(c.a?Yb(c):c.start())};break;case td:b.onclick=function(){kc(c)};break;case ud:b.addEventListener("mousedown",function(){c.l=!0}),b.addEventListener("mouseup",function(){pd(c);c.l=!1}),b.addEventListener("mousemove",function(){c.l&&pd(c)}),b.addEventListener("change",function(){c.l=!0;pd(c);c.l=!1})}F.prototype.Ca.call(this,a,b)};
function yc(a,b,c,d){d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,Bc:c,Ya:d,fa:-1});0<=d&&Dc(a,e,d);return e}f.qb=function(a){if(this.v){if(!this.a)return;vd(this);try{this.M=!1;do wd(this,xd(this,yd(this,zd(this))));while(this.a&&!this.M)}catch(c){z(this,c.message);Yb(this);return}Ad(this)}for(var b=0;b<this.ka.length;b++)this.ka[b](a);this.a&&this.la&&this.ta(this.Ja)};function Bd(a){var b=a.h/a.ma;if(!b||b>a.ea)b=a.ea;a.eb=a.T/a.K*b;a.Ga=b}
function yd(a,b){a.R=a.j=b;if(!a.u.length)return a.j=0,a.R;for(var c=0;0<a.j;)c<a.u.length?b=a.u[c++](b)||1:c=b=0,a.j-=b;return a.R-a.j}function xd(a,b){b=void 0===b?a.R-a.j:b;if(a.v){if(!a.a){if(a.f)for(var c=0;c<a.u.length;c++)a.u[c](-1);a.f=b}a.f-=b;1>a.f&&od(a)}a.R=a.j=0;a.W+=b;a.U+=b;a.a||(a.U=0);return b}function Cd(a,b){return Math.ceil(a.T*a.Ga/1E3*(void 0===b?1E3:b))}
function zd(a,b){b=void 0===b?0:b;if(b){var c=b;a.f+=b}else for(c=a.f,1>c&&(c=a.f+=a.Aa),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.fa)&&c>d.fa&&(c=d.fa)}return c}function Dd(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function sd(a){return a.Ea?!0:(z(a,"not powered"),!1)}function wd(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.fa||(d.fa-=b,0>=d.fa&&(d.fa=-1,d.Bc(),0<=d.Ya&&Dc(a,c,d.Ya)))}}f.pa=function(a){this.Ea=a};
function kc(a,b){sd(a)&&(a.a?z(a,"already running"):a.g?Yb(a):Ed(a,b))}function od(a){a.M=!0;var b=a.s,c=Cd(a);c>=a.K?a.s++:a.s+=Math.ceil(a.K/c);a.s>=a.Ia&&b<a.Ia&&ec(a);a.s>=a.K&&(a.s=0)}f.yh=function(){this.I=0;if(this.a){vd(this);try{this.M=!1;do{for(var a=Cd(this,this.ha),b=this.b.length;0<b;b--){var c=this.b[b-1];!(0>c.fa)&&a>c.fa&&(a=c.fa)}wd(this,xd(this,yd(this,a)))}while(this.a&&!this.M)}catch(d){z(this,d.message);Yb(this);return}this.a&&(this.I=setTimeout(this.Ka,Ad(this)),this.la||this.qb())}};
function pd(a){var b=a.Z[ud];return b?(qd(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Ha-a.ra)+a.ra)/a.T),!0):!1}function qd(a,b){void 0!==b&&(!a.l&&0<a.h&&a.h<.9*a.m&&(b=a.Fa),a.ea=b,b=a.ma*a.ea,a.m!=b&&(a.m=b,ib(a,Fd,Dd(a.m))),a.h=a.m);a.v&&(a.Aa=1E6*a.h/60+1E-8,a.f=0);a.U=0;a.c=a.i=0;Bd(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Ya&&Dc(a,b,c.Ya,!0)}}function Dc(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.fa)&&(c=Cd(a,c),a.a&&(c+=xd(a)),b.fa=c)}
function vd(a){Bd(a);a.W=0;a.na=0;a.o=Date.now();a.c||(a.c=a.o);if(a.i){var b=a.o-a.i;b>a.ha&&(a.c+=b,a.c>a.o&&(a.c=a.o))}}function Ad(a){a.i=Date.now();a.na&&(a.c+=a.na,a.o+=a.na);var b=a.ha;a.W&&(b=Math.round(b*a.W/a.eb));b-=a.i-a.o;var c=a.i-a.c;c&&(a.h=a.U/(10*c)/100);0>b?(-1E3>b&&(a.c-=b),b=0):a.h<a.m&&(b=0);a.i+=b;a.O(256,"after running %d cycles, resting for %dms\n",a.W,b);return b}
f.start=function(){if(this.a||this.g)return!1;this.I&&(clearTimeout(this.I),this.I=0);this.a=!0;this.c=this.i=0;ec(this,!0);this.v||(this.I=setTimeout(this.Ka,0));this.la&&this.ta(this.Ja);return!0};function Ed(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,wd(a,xd(a,yd(a,zd(a,1)))),ec(a,!1),a.g&&setTimeout(function(){Ed(a,0)},0)))}function Yb(a){return a.g?(a.g=0,ec(a,!0),!0):a.a?(a.a=!1,xd(a),ec(a,!0),!0):!1}
function ec(a,b){b&&(a.a?z(a,"started with "+Dd(a.m)+" target"):z(a,"stopped"));ib(a,rd,a.a?"Halt":"Run");ib(a,td,a.g?"Stop":"Step");a.l||ib(a,Fd,a.a&&a.h?Dd(a.h):"Stopped");for(var c=0;c<a.L.length;c++)a.L[c](void 0!=b)}var rd="run",Fd="speed",td="step",ud="throttle",md=120,nd=60;q.Time=ld;
function Gd(a,b,c){cd.call(this,a,b,c);this.M=c.bufferAddr;this.eb=c.bufferRAM;this.m=c.bufferWidth;this.o=c.bufferHeight;this.Ia=this.aa=c.cellWidth||1;this.V=c.cellHeight||1;this.u=null;this.ka=!1;this.ra=c.bufferBits||1;this.Ea=c.interruptRate;this.Fa=c.refreshRate||60;this.ea=this.l/this.m|0;this.ha=this.h/this.o|0;1<this.V&&(this.o++,this.Ha=0,this.la=!1);this.i=nb(this,c.bus);a:{this.R=this.m*this.aa;this.T=this.o*this.V;a=this.R;b=this.T;this.K=0;if(!this.eb&&(this.K=(this.R*this.ra>>3)*this.T,
!xb(this.i,this.M,this.K,yb.Wa)))break a;hd(this,(this.m+1)*this.o);this.I=document.createElement("canvas");this.I.width=a;this.I.height=b;this.W=this.I.getContext("2d");this.j={};this.Qb=1<<this.ra;this.L=Array(this.Qb);this.L[0]=[0,0,0,255];this.L[1]=[255,255,255,255];this.v=Array(this.m);this.Ga&&(this.g[this.Ga]=null==this.ma?!1:this.ma)}this.u=c.fontROM;this.u&&(this.ka=!0,this.j[Hd]=[Id(this,this.aa,this.V),Id(this,this.aa,this.V,!1)],this.j[Jd]=[Id(this,2*this.aa,this.V),Id(this,2*this.aa,
this.V,!1)],this.j[Kd]=this.j[Ld]=[Id(this,2*this.aa,2*this.V),Id(this,2*this.aa,2*this.V,!1)]);this.Y=pb(this,"CPU");this.time=pb(this,"Time");this.Aa=yc(this.time,this.ga,this.Ub.bind(this));this.time.L.push(this.Wb.bind(this));Dc(this.time,this.Aa,1E3/Math.max(this.Fa,this.Ea))}n(Gd,cd);
function Id(a,b,c,d){var e=8>=a.Ia?8:16,g=8<e?15:0,h=a.u.length/e,k=!1===d,l={aa:b,V:c};l.canvas=document.createElement("canvas");l.canvas.width=16*b;l.canvas.height=h/16*c;l.context=l.canvas.getContext("2d");for(var m=l.context.createImageData(b,c),r=0;r<h;r++){for(var w=0,t=w;w<a.V;w++){var p=r*e+(g+w&e-1);p=d&&8==w?255:a.u[p];for(var u=0;u<c/a.V;u++){for(var v=0,x=0,A=x;x<a.aa;x++){var sa=p&128>>(7<x?7:x);v=a.ka&&!sa&&v?v:sa;for(var Z=0;Z<b/a.aa;Z++){k&&(v=!v);var S=m,ba=A+t*S.width,xa=a.L[v?1:
0];ba*=xa.length;S.data[ba]=xa[0];S.data[ba+1]=xa[1];S.data[ba+2]=xa[2];S.data[ba+3]=xa[3];A++}v=sa}t++}}l.context.putImageData(m,(r&15)*b,(r>>4)*c)}return l}function hd(a,b){a.U=!1;b&&(a.ta=b,void 0===a.f||a.f.length!=a.ta)&&(a.f=Array(a.ta))}
Gd.prototype.Ub=function(a){var b=!0;if(!a){if(b&&this.U&&this.K){var c=this.i,d=this.M,e=this.K,g=!0,h=d>>>c.c;for(d=c.b-(d&c.g);0<e&&h<c.a.length;){var k=c.a[h];k.l?(k.l=!1,k.ba=k.vb,k.ca=k.zb,k=!0):k=!1;k&&(g=!1);e-=d;d=c.b;h++}g&&(b=!1)}Dc(this.time,this.Aa,1E3/Math.max(this.Fa,this.Ea))}b&&id(this,a)};
function id(a,b){for(var c=0,d,e=-1,g=2,h=0,k=0,l=-1,m=a.M;c<a.o;){var r=0,w=m,t=a.m;d=e;for(d!=Hd&&(t>>=1);;){var p=a.i.$(w++);if((p&Md)==Md){p=a.i.$(w++);e=p&Nd;m=(p&Od)<<8|a.i.$(w);m+=p&Pd?Qd:Rd;break}if(r<t)a.v[r++]=p;else break}if(g)g--;else{for(;r<a.v.length;)a.v[r++]=0;if(0<=d)for(w=a.U&&a.f[h]==t,a.f[h++]=t,t=0;t<r;t++){var u=a.v[t];if(!w||u!==a.f[h]){a.f[l=h]=u;p=a;var v=a.W;var x=u&127;if(u=p.j[d][u&128?1:0]){var A=(x&15)*u.aa,sa=(x>>4)*u.V,Z=u.aa,S=u.V;if(v){var ba=t*p.aa;var xa=c*p.V;
var Jb=p.aa;x=p.V}else ba=t*p.ea,xa=c*p.ha,Jb=p.ea,x=p.ha;u.aa>p.aa&&(ba*=2,Jb*=2);u.V>p.V&&(d==Ld&&(sa+=p.V),S=p.V);v?v.drawImage(u.canvas,A,sa,Z,S,ba,xa,Jb,x):p.g.drawImage(u.canvas,A,sa,Z,S,ba,xa,Jb,x)}k++}h++}c++}}a.U=!0;!b&&a.la&&1==k&&(a.f[l]=-1,k=0);a.la=!1;(k||b)&&a.W&&a.g.drawImage(a.I,0,a.Ha,a.R,a.T-a.V,0,0,a.Ja,a.Ka)}Gd.prototype.Wb=function(){this.time.a||id(this)};var Hd=96,Jd=64,Kd=32,Ld=0,Md=127,Od=15,Pd=16,Nd=96,Qd=8192,Rd=16384;q.Video=Gd;
function Sd(a,b,c){F.call(this,a,b,c);var d=this;Td(this);this.W=[this.ya,this.ve,this.Rg,this.fe,this.Zd,this.Jd,this.Mf,this.og,this.ya,this.Ed,this.se,this.Qd,this.$d,this.Kd,this.Nf,this.vg,this.ya,this.we,this.Sg,this.ge,this.ae,this.Ld,this.Of,this.lg,this.ya,this.Fd,this.te,this.Rd,this.be,this.Md,this.Pf,this.mg,this.ya,this.xe,this.Og,this.he,this.ce,this.Nd,this.Qf,this.Dd,this.ya,this.Gd,this.ue,this.Sd,this.de,this.Od,this.Rf,this.md,this.ya,this.ye,this.Qg,this.ie,this.ee,this.Pd,this.Sf,
this.Tg,this.ya,this.Hd,this.re,this.Td,this.Yd,this.Id,this.Lf,this.nd,this.Ie,this.Je,this.Ke,this.Le,this.Me,this.Ne,this.Oe,this.He,this.Qe,this.Re,this.Se,this.Te,this.Ue,this.Ve,this.We,this.Pe,this.Ye,this.Ze,this.$e,this.af,this.bf,this.cf,this.df,this.Xe,this.ff,this.gf,this.hf,this.jf,this.kf,this.lf,this.mf,this.ef,this.pf,this.qf,this.rf,this.sf,this.tf,this.uf,this.vf,this.nf,this.xf,this.yf,this.zf,this.Af,this.Bf,this.Cf,this.Df,this.wf,this.Ff,this.Gf,this.Hf,this.If,this.Jf,this.Kf,
this.Wd,this.Ef,this.Ae,this.Be,this.Ce,this.De,this.Ee,this.Fe,this.Ge,this.ze,this.Tc,this.Uc,this.Vc,this.Wc,this.Xc,this.Yc,this.Zc,this.Sc,this.Lc,this.Mc,this.Nc,this.Oc,this.Pc,this.Qc,this.Rc,this.Kc,this.Vg,this.Wg,this.Xg,this.Yg,this.Zg,this.$g,this.ah,this.Ug,this.Gg,this.Hg,this.Ig,this.Jg,this.Kg,this.Lg,this.Mg,this.Fg,this.bd,this.cd,this.dd,this.ed,this.fd,this.gd,this.hd,this.ad,this.fh,this.gh,this.hh,this.ih,this.jh,this.kh,this.lh,this.eh,this.Uf,this.Vf,this.Wf,this.Xf,this.Yf,
this.Zf,this.$f,this.Tf,this.pd,this.qd,this.rd,this.sd,this.td,this.ud,this.vd,this.od,this.rg,this.dg,this.me,this.tb,this.xd,this.ig,this.$c,this.wg,this.Eg,this.ub,this.qe,this.tb,this.Cd,this.Za,this.Jc,this.xg,this.qg,this.eg,this.le,this.bg,this.wd,this.jg,this.bh,this.yg,this.ng,this.ub,this.je,this.Xd,this.kd,this.Za,this.Ng,this.zg,this.ug,this.fg,this.pe,this.nh,this.Bd,this.kg,this.jd,this.Ag,this.tg,this.cg,this.oe,this.dh,this.zd,this.Za,this.mh,this.Bg,this.sg,this.gg,this.ne,this.Ud,
this.yd,this.hg,this.ag,this.Cg,this.pg,this.Pg,this.ke,this.Vd,this.ld,this.Za,this.Ad,this.Dg];this.a=this.M=0;this.U=pb(this,"Input",!1);this.T=nb(this,this.S.busIO);this.K=nb(this,this.S.busMemory);this.time=pb(this,"Time");this.time.u.push(this.Gc.bind(this));this.time.L.push(this.zh.bind(this));this.L=void 0;G(this,"A",function(){return d.b},function(e){return d.b=e&255});G(this,"B",function(){return d.c},function(e){return d.c=e&255});G(this,"C",function(){return d.f},function(e){return d.f=
e&255});G(this,"D",function(){return d.g},function(e){return d.g=e&255});G(this,"E",function(){return d.h},function(e){return d.h=e&255});G(this,"H",function(){return d.i},function(e){return d.i=e&255});G(this,"L",function(){return d.j},function(e){return d.j=e&255});G(this,"CF",function(){return Ud(d)?1:0},function(e){d.m=e?d.m|256:d.m&255});G(this,"PF",function(){return Vd(d)?1:0},function(e){e?Vd(d)||(d.o^=1):Vd(d)&&(d.o^=1)});G(this,"AF",function(){return Wd(d)?1:0},function(e){d.s=e?~d.o&16|
d.s&-17:d.o&16|d.s&-17});G(this,"ZF",function(){return Xd(d)?1:0},function(e){d.m=e?d.m&-256:d.m|255});G(this,"SF",function(){return Yd(d)?1:0},function(e){e?Yd(d)||(d.o^=192):Yd(d)&&(d.o^=192)});G(this,"IF",function(){return d.u&Zd?1:0},function(e){d.u=e?d.u|Zd:d.u&~Zd});G(this,"BC",this.wa,this.Ta);G(this,"DE",this.sa,this.Ma);G(this,"HL",this.H,this.ia);G(this,nc.ec,this.Hc,this.w)}n(Sd,F);f=Sd.prototype;
f.Gc=function(a){a=void 0===a?0:a;if(0>a)return this.M=0;try{if(this.a=0,this.M=a,$d(this))for(;this.a<=this.M;)this.R=this.l,this.W[I(this)].call(this)}catch(b){this.l=this.R,z(this,b.message),Yb(this.time)}return this.a};
f.xa=function(a){a=a.shift();if(!a||!a.length)return z(this,"invalid saved state"),!1;var b=a.shift(),c=a.shift();if(b!=this.ga||2!==(c|0))return this.O("CPU state mismatch (%s %3.2f)\n",b,c),!1;try{this.b=a.shift(),this.c=a.shift(),this.f=a.shift(),this.g=a.shift(),this.h=a.shift(),this.i=a.shift(),this.j=a.shift(),this.w(a.shift()),this.v=a.shift()&65535,ae(this,a.shift()),this.I=a.shift()}catch(d){return z(this,"CPU state error: "+d.message),!1}return!0};
f.za=function(a){var b=[];b.push(this.ga);b.push(2);b.push(this.b);b.push(this.c);b.push(this.f);b.push(this.g);b.push(this.h);b.push(this.i);b.push(this.j);b.push(this.l);b.push(this.v);b.push(be(this));b.push(this.I);a.push(b)};f.gb=function(a){return a&&this.xa(a)?!0:!1};f.pa=function(a){a?(this.time.start(),this.U&&ic(this.U)):Yb(this.time)};f.Da=function(){z(this,"reset");Td(this);this.time.a||this.Ba(this.toString())};f.Ra=function(a){this.za(a)};f.ya=function(){this.a+=4};
f.ve=function(){this.Ta(J(this));this.a+=10};f.Rg=function(){ce(this,this.wa(),this.b);this.a+=7};f.fe=function(){this.Ta(this.wa()+1);this.a+=5};f.Zd=function(){this.c=de(this,this.c);this.a+=5};f.Jd=function(){this.c=ee(this,this.c);this.a+=5};f.Mf=function(){this.c=I(this);this.a+=7};f.og=function(){var a=this.b<<1;this.b=a&255|a>>8;fe(this,a&256);this.a+=4};f.Ed=function(){var a;this.ia(a=this.H()+this.wa());fe(this,a>>8&256);this.a+=10};f.se=function(){this.b=K(this,this.wa());this.a+=7};
f.Qd=function(){this.Ta(this.wa()-1);this.a+=5};f.$d=function(){this.f=de(this,this.f);this.a+=5};f.Kd=function(){this.f=ee(this,this.f);this.a+=5};f.Nf=function(){this.f=I(this);this.a+=7};f.vg=function(){var a=this.b<<8&256;this.b=(a|this.b)>>1;fe(this,a);this.a+=4};f.we=function(){this.Ma(J(this));this.a+=10};f.Sg=function(){ce(this,this.sa(),this.b);this.a+=7};f.ge=function(){this.Ma(this.sa()+1);this.a+=5};f.ae=function(){this.g=de(this,this.g);this.a+=5};
f.Ld=function(){this.g=ee(this,this.g);this.a+=5};f.Of=function(){this.g=I(this);this.a+=7};f.lg=function(){var a=this.b<<1;this.b=a&255|Ud(this);fe(this,a&256);this.a+=4};f.Fd=function(){var a;this.ia(a=this.H()+this.sa());fe(this,a>>8&256);this.a+=10};f.te=function(){this.b=K(this,this.sa());this.a+=7};f.Rd=function(){this.Ma(this.sa()-1);this.a+=5};f.be=function(){this.h=de(this,this.h);this.a+=5};f.Md=function(){this.h=ee(this,this.h);this.a+=5};f.Pf=function(){this.h=I(this);this.a+=7};
f.mg=function(){var a=this.b<<8;this.b=(Ud(this)<<8|this.b)>>1;fe(this,a&256);this.a+=4};f.xe=function(){this.ia(J(this));this.a+=10};f.Og=function(){var a=J(this);this.K.ca(a,this.H()&65535);this.a+=16};f.he=function(){this.ia(this.H()+1);this.a+=5};f.ce=function(){this.i=de(this,this.i);this.a+=5};f.Nd=function(){this.i=ee(this,this.i);this.a+=5};f.Qf=function(){this.i=I(this);this.a+=7};
f.Dd=function(){var a=0,b=Ud(this);if(Wd(this)||9<(this.b&15))a|=6;if(b||154<=this.b)a|=96,b=ge;this.b=he(this,a);fe(this,b?256:0);this.a+=4};f.Gd=function(){var a;this.ia(a=this.H()+this.H());fe(this,a>>8&256);this.a+=10};f.ue=function(){this.ia(ie(this,J(this)));this.a+=16};f.Sd=function(){this.ia(this.H()-1);this.a+=5};f.de=function(){this.j=de(this,this.j);this.a+=5};f.Od=function(){this.j=ee(this,this.j);this.a+=5};f.Rf=function(){this.j=I(this);this.a+=7};
f.md=function(){this.b=~this.b&255;this.a+=4};f.ye=function(){this.v=J(this)&65535;this.a+=10};f.Qg=function(){ce(this,J(this),this.b);this.a+=13};f.ie=function(){this.v=this.v+1&65535;this.a+=5};f.ee=function(){var a=this.H();ce(this,a,de(this,K(this,a)));this.a+=10};f.Pd=function(){var a=this.H();ce(this,a,ee(this,K(this,a)));this.a+=10};f.Sf=function(){ce(this,this.H(),I(this));this.a+=10};f.Tg=function(){this.m|=256;this.a+=4};
f.Hd=function(){var a;this.ia(a=this.H()+this.v);fe(this,a>>8&256);this.a+=10};f.re=function(){this.b=K(this,J(this));this.a+=13};f.Td=function(){this.v=this.v-1&65535;this.a+=5};f.Yd=function(){this.b=de(this,this.b);this.a+=5};f.Id=function(){this.b=ee(this,this.b);this.a+=5};f.Lf=function(){this.b=I(this);this.a+=7};f.nd=function(){fe(this,Ud(this)?0:256);this.a+=4};f.Ie=function(){this.a+=5};f.Je=function(){this.c=this.f;this.a+=5};f.Ke=function(){this.c=this.g;this.a+=5};
f.Le=function(){this.c=this.h;this.a+=5};f.Me=function(){this.c=this.i;this.a+=5};f.Ne=function(){this.c=this.j;this.a+=5};f.Oe=function(){this.c=K(this,this.H());this.a+=7};f.He=function(){this.c=this.b;this.a+=5};f.Qe=function(){this.f=this.c;this.a+=5};f.Re=function(){this.a+=5};f.Se=function(){this.f=this.g;this.a+=5};f.Te=function(){this.f=this.h;this.a+=5};f.Ue=function(){this.f=this.i;this.a+=5};f.Ve=function(){this.f=this.j;this.a+=5};f.We=function(){this.f=K(this,this.H());this.a+=7};
f.Pe=function(){this.f=this.b;this.a+=5};f.Ye=function(){this.g=this.c;this.a+=5};f.Ze=function(){this.g=this.f;this.a+=5};f.$e=function(){this.a+=5};f.af=function(){this.g=this.h;this.a+=5};f.bf=function(){this.g=this.i;this.a+=5};f.cf=function(){this.g=this.j;this.a+=5};f.df=function(){this.g=K(this,this.H());this.a+=7};f.Xe=function(){this.g=this.b;this.a+=5};f.ff=function(){this.h=this.c;this.a+=5};f.gf=function(){this.h=this.f;this.a+=5};f.hf=function(){this.h=this.g;this.a+=5};
f.jf=function(){this.a+=5};f.kf=function(){this.h=this.i;this.a+=5};f.lf=function(){this.h=this.j;this.a+=5};f.mf=function(){this.h=K(this,this.H());this.a+=7};f.ef=function(){this.h=this.b;this.a+=5};f.pf=function(){this.i=this.c;this.a+=5};f.qf=function(){this.i=this.f;this.a+=5};f.rf=function(){this.i=this.g;this.a+=5};f.sf=function(){this.i=this.h;this.a+=5};f.tf=function(){this.a+=5};f.uf=function(){this.i=this.j;this.a+=5};f.vf=function(){this.i=K(this,this.H());this.a+=7};
f.nf=function(){this.i=this.b;this.a+=5};f.xf=function(){this.j=this.c;this.a+=5};f.yf=function(){this.j=this.f;this.a+=5};f.zf=function(){this.j=this.g;this.a+=5};f.Af=function(){this.j=this.h;this.a+=5};f.Bf=function(){this.j=this.i;this.a+=5};f.Cf=function(){this.a+=5};f.Df=function(){this.j=K(this,this.H());this.a+=7};f.wf=function(){this.j=this.b;this.a+=5};f.Ff=function(){ce(this,this.H(),this.c);this.a+=7};f.Gf=function(){ce(this,this.H(),this.f);this.a+=7};
f.Hf=function(){ce(this,this.H(),this.g);this.a+=7};f.If=function(){ce(this,this.H(),this.h);this.a+=7};f.Jf=function(){ce(this,this.H(),this.i);this.a+=7};f.Kf=function(){ce(this,this.H(),this.j);this.a+=7};f.Wd=function(){this.a+=7;this.I|=je;xd(this.time);this.u&Zd&&!ab(8192)||(this.w(this.l-1),Yb(this.time))};f.Ef=function(){ce(this,this.H(),this.b);this.a+=7};f.Ae=function(){this.b=this.c;this.a+=5};f.Be=function(){this.b=this.f;this.a+=5};f.Ce=function(){this.b=this.g;this.a+=5};
f.De=function(){this.b=this.h;this.a+=5};f.Ee=function(){this.b=this.i;this.a+=5};f.Fe=function(){this.b=this.j;this.a+=5};f.Ge=function(){this.b=K(this,this.H());this.a+=7};f.ze=function(){this.a+=5};f.Tc=function(){this.b=he(this,this.c);this.a+=4};f.Uc=function(){this.b=he(this,this.f);this.a+=4};f.Vc=function(){this.b=he(this,this.g);this.a+=4};f.Wc=function(){this.b=he(this,this.h);this.a+=4};f.Xc=function(){this.b=he(this,this.i);this.a+=4};f.Yc=function(){this.b=he(this,this.j);this.a+=4};
f.Zc=function(){this.b=he(this,K(this,this.H()));this.a+=7};f.Sc=function(){this.b=he(this,this.b);this.a+=4};f.Lc=function(){this.b=ke(this,this.c);this.a+=4};f.Mc=function(){this.b=ke(this,this.f);this.a+=4};f.Nc=function(){this.b=ke(this,this.g);this.a+=4};f.Oc=function(){this.b=ke(this,this.h);this.a+=4};f.Pc=function(){this.b=ke(this,this.i);this.a+=4};f.Qc=function(){this.b=ke(this,this.j);this.a+=4};f.Rc=function(){this.b=ke(this,K(this,this.H()));this.a+=7};
f.Kc=function(){this.b=ke(this,this.b);this.a+=4};f.Vg=function(){this.b=L(this,this.c);this.a+=4};f.Wg=function(){this.b=L(this,this.f);this.a+=4};f.Xg=function(){this.b=L(this,this.g);this.a+=4};f.Yg=function(){this.b=L(this,this.h);this.a+=4};f.Zg=function(){this.b=L(this,this.i);this.a+=4};f.$g=function(){this.b=L(this,this.j);this.a+=4};f.ah=function(){this.b=L(this,K(this,this.H()));this.a+=7};f.Ug=function(){this.b=L(this,this.b);this.a+=4};f.Gg=function(){this.b=le(this,this.c);this.a+=4};
f.Hg=function(){this.b=le(this,this.f);this.a+=4};f.Ig=function(){this.b=le(this,this.g);this.a+=4};f.Jg=function(){this.b=le(this,this.h);this.a+=4};f.Kg=function(){this.b=le(this,this.i);this.a+=4};f.Lg=function(){this.b=le(this,this.j);this.a+=4};f.Mg=function(){this.b=le(this,K(this,this.H()));this.a+=7};f.Fg=function(){this.b=le(this,this.b);this.a+=4};f.bd=function(){this.b=me(this,this.c);this.a+=4};f.cd=function(){this.b=me(this,this.f);this.a+=4};
f.dd=function(){this.b=me(this,this.g);this.a+=4};f.ed=function(){this.b=me(this,this.h);this.a+=4};f.fd=function(){this.b=me(this,this.i);this.a+=4};f.gd=function(){this.b=me(this,this.j);this.a+=4};f.hd=function(){this.b=me(this,K(this,this.H()));this.a+=7};f.ad=function(){this.b=me(this,this.b);this.a+=4};f.fh=function(){this.b=ne(this,this.c);this.a+=4};f.gh=function(){this.b=ne(this,this.f);this.a+=4};f.hh=function(){this.b=ne(this,this.g);this.a+=4};
f.ih=function(){this.b=ne(this,this.h);this.a+=4};f.jh=function(){this.b=ne(this,this.i);this.a+=4};f.kh=function(){this.b=ne(this,this.j);this.a+=4};f.lh=function(){this.b=ne(this,K(this,this.H()));this.a+=7};f.eh=function(){this.b=ne(this,this.b);this.a+=4};f.Uf=function(){this.b=oe(this,this.c);this.a+=4};f.Vf=function(){this.b=oe(this,this.f);this.a+=4};f.Wf=function(){this.b=oe(this,this.g);this.a+=4};f.Xf=function(){this.b=oe(this,this.h);this.a+=4};
f.Yf=function(){this.b=oe(this,this.i);this.a+=4};f.Zf=function(){this.b=oe(this,this.j);this.a+=4};f.$f=function(){this.b=oe(this,K(this,this.H()));this.a+=7};f.Tf=function(){this.b=oe(this,this.b);this.a+=4};f.pd=function(){L(this,this.c);this.a+=4};f.qd=function(){L(this,this.f);this.a+=4};f.rd=function(){L(this,this.g);this.a+=4};f.sd=function(){L(this,this.h);this.a+=4};f.td=function(){L(this,this.i);this.a+=4};f.ud=function(){L(this,this.j);this.a+=4};
f.vd=function(){L(this,K(this,this.H()));this.a+=7};f.od=function(){L(this,this.b);this.a+=4};f.rg=function(){Xd(this)||(this.w(pe(this)),this.a+=6);this.a+=5};f.dg=function(){this.Ta(pe(this));this.a+=10};f.me=function(){var a=J(this);Xd(this)||this.w(a);this.a+=10};f.tb=function(){this.w(J(this));this.a+=10};f.xd=function(){var a=J(this);Xd(this)||(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.ig=function(){M(this,this.wa());this.a+=11};f.$c=function(){this.b=he(this,I(this));this.a+=7};
f.wg=function(){M(this,this.l);this.w(0);this.a+=11};f.Eg=function(){Xd(this)&&(this.w(pe(this)),this.a+=6);this.a+=5};f.ub=function(){this.w(pe(this));this.a+=10};f.qe=function(){var a=J(this);Xd(this)&&this.w(a);this.a+=10};f.Cd=function(){var a=J(this);Xd(this)&&(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.Za=function(){var a=J(this);M(this,this.l);this.w(a);this.a+=17};f.Jc=function(){this.b=ke(this,I(this));this.a+=7};f.xg=function(){M(this,this.l);this.w(8);this.a+=11};
f.qg=function(){Ud(this)||(this.w(pe(this)),this.a+=6);this.a+=5};f.eg=function(){this.Ma(pe(this));this.a+=10};f.le=function(){var a=J(this);Ud(this)||this.w(a);this.a+=10};f.bg=function(){var a=I(this);this.T.ba(a,this.b,this.l+-2&65535);this.a+=10};f.wd=function(){var a=J(this);Ud(this)||(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.jg=function(){M(this,this.sa());this.a+=11};f.bh=function(){this.b=L(this,I(this));this.a+=7};f.yg=function(){M(this,this.l);this.w(16);this.a+=11};
f.ng=function(){Ud(this)&&(this.w(pe(this)),this.a+=6);this.a+=5};f.je=function(){var a=J(this);Ud(this)&&this.w(a);this.a+=10};f.Xd=function(){var a=I(this);this.b=this.T.$(a,this.l+-2&65535)&255;this.a+=10};f.kd=function(){var a=J(this);Ud(this)&&(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.Ng=function(){this.b=le(this,I(this));this.a+=7};f.zg=function(){M(this,this.l);this.w(24);this.a+=11};f.ug=function(){Vd(this)||(this.w(pe(this)),this.a+=6);this.a+=5};
f.fg=function(){this.ia(pe(this));this.a+=10};f.pe=function(){var a=J(this);Vd(this)||this.w(a);this.a+=10};f.nh=function(){var a=pe(this);M(this,this.H());this.ia(a);this.a+=18};f.Bd=function(){var a=J(this);Vd(this)||(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.kg=function(){M(this,this.H());this.a+=11};f.jd=function(){this.b=me(this,I(this));this.a+=7};f.Ag=function(){M(this,this.l);this.w(32);this.a+=11};f.tg=function(){Vd(this)&&(this.w(pe(this)),this.a+=6);this.a+=5};
f.cg=function(){this.w(this.H());this.a+=5};f.oe=function(){var a=J(this);Vd(this)&&this.w(a);this.a+=10};f.dh=function(){var a=this.H();this.ia(this.sa());this.Ma(a);this.a+=5};f.zd=function(){var a=J(this);Vd(this)&&(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.mh=function(){this.b=ne(this,I(this));this.a+=7};f.Bg=function(){M(this,this.l);this.w(40);this.a+=11};f.sg=function(){Yd(this)||(this.w(pe(this)),this.a+=6);this.a+=5};
f.gg=function(){var a=pe(this);ae(this,a&qe|this.u&~qe);this.b=a>>8;this.a+=10};f.ne=function(){var a=J(this);Yd(this)||this.w(a);this.a+=10};f.Ud=function(){this.u&=~Zd;this.a+=4};f.yd=function(){var a=J(this);Yd(this)||(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.hg=function(){M(this,be(this)&qe|this.b<<8);this.a+=11};f.ag=function(){this.b=oe(this,I(this));this.a+=7};f.Cg=function(){M(this,this.l);this.w(48);this.a+=11};f.pg=function(){Yd(this)&&(this.w(pe(this)),this.a+=6);this.a+=5};
f.Pg=function(){this.v=this.H()&65535;this.a+=5};f.ke=function(){var a=J(this);Yd(this)&&this.w(a);this.a+=10};f.Vd=function(){this.u|=Zd;this.a+=4;$d(this)};f.ld=function(){var a=J(this);Yd(this)&&(M(this,this.l),this.w(a),this.a+=6);this.a+=11};f.Ad=function(){L(this,I(this));this.a+=7};f.Dg=function(){M(this,this.l);this.w(56);this.a+=11};function Td(a){a.b=0;a.c=0;a.f=0;a.g=0;a.h=0;a.i=0;a.j=0;a.v=0;a.w(a.ea);a.R=a.l;ae(a,0);a.I=re}f.wa=function(){return this.c<<8|this.f};
f.Ta=function(a){this.c=a>>8&255;this.f=a&255};f.sa=function(){return this.g<<8|this.h};f.Ma=function(a){this.g=a>>8&255;this.h=a&255};f.H=function(){return this.i<<8|this.j};f.ia=function(a){this.i=a>>8&255;this.j=a&255};f.Hc=function(){return this.l};f.w=function(a){this.l=a&65535};function Ud(a){return a.m&256?ge:0}function fe(a,b){a.m=a.m&255|b}function Vd(a){return se[a.o&255]?te:0}function Wd(a){return(a.o^a.s)&16?ue:0}function Xd(a){return a.m&255?0:ve}function Yd(a){return a.o&128?we:0}
function be(a){return a.u&~xe|Yd(a)|Xd(a)|Wd(a)|Vd(a)|Ud(a)}function ae(a,b){a.m=a.o=a.s=0;b&ge&&(a.m|=256);b&te||(a.o|=1);b&ue&&(a.s|=16);b&ve||(a.m|=255);b&we&&(a.o^=192);a.u=a.u&~(xe|Zd)|b&Zd|ye}function he(a,b){a.s=a.b^b;return a.o=(a.m=a.b+b)&255}function ke(a,b){a.s=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?1:0))&255}function me(a,b){a.m=a.o=a.s=a.b&b;(a.b|b)&8&&(a.s^=16);return a.m}function ee(a,b){a.s=b^255;b=a.o=b+255&255;a.m=a.m&-256|b;return b}
function de(a,b){a.s=b;b=a.o=b+1&255;a.m=a.m&-256|b;return b}function oe(a,b){return a.o=a.m=a.s=a.b|b}function L(a,b){b^=255;a.s=a.b^b;return a.o=(a.m=a.b+b+1^256)&255}function le(a,b){b^=255;a.s=a.b^b;return a.o=(a.m=a.b+b+(a.m&256?0:1)^256)&255}function ne(a,b){return a.o=a.m=a.s=a.b^b}function K(a,b){return a.K.$(b)|0}function ie(a,b){return a.K.qa(b)}function ce(a,b,c){a.K.ba(b,c&255)}function I(a){var b=K(a,a.l);a.w(a.l+1);return b}function J(a){var b=ie(a,a.l);a.w(a.l+2);return b}
function pe(a){var b=ie(a,a.v);a.v=a.v+2&65535;return b}function M(a,b){a.v=a.v-2&65535;a.K.ca(a.v,b&65535)}function $d(a){if(a.time.a&&a.I&ze&&a.u&Zd){var b;for(b=0;8>b&&!(a.I&1<<b);b++);a.I&=~(0>b?255:1<<b);a.u&=~Zd;a.I&=~je;a.W[Ae|b<<3].call(a)}return a.I&je?(xd(a.time),!1):!0}
f.toString=function(){return this.J("A=%02X BC=%04X DE=%04X HL=%04X SP=%04X I%d S%d Z%d A%d P%d C%d\n%s",this.b,this.wa(),this.sa(),this.H(),this.v,this.u&Zd?1:0,Yd(this)?1:0,Xd(this)?1:0,Wd(this)?1:0,Vd(this)?1:0,Ud(this)?1:0,this.L&&ac(this.L,this.l,1)||"")};f.zh=function(){};
var ge=1,ye=2,te=4,ue=16,ve=64,we=128,qe=255,Zd=512,xe=ge|te|ue|ve|we,se=[1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,
0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,0,1],re=0,ze=255,je=256,Ae=199;q.CPU=Sd;function Be(a,b,c){Bb.call(this,a,b,c);this.style=Ce;this.v=3}n(Be,Bb);
Be.prototype.kb=function(a,b){function c(Z,S){var ba=De[Z];g.style==Ce&&S&Ee&&(Z==Fe&&(ba="HL"),ba="["+ba+"]");return ba}function d(Z){switch(Z&Ge){case N:var S=Aa(g,e(),16,8,"");break;case He:S=Aa(g,(e()|e()<<8)<<24>>24,16,16,"");break;case Ie:S=Aa(g,e()|e()<<8,16,16,"");break;default:return"imm("+Aa(g,Z,16,16,"")+")"}g.style==Ce&&Z&Ee?S="["+S+"]":Z&Je||(S=(g.style==Ke?"$":"0x")+S);return S}function e(){var Z=b.shift();k+=Aa(g,Z,16,8,"");Db(g,a,1);return Z}for(var g=this,h=Zb(this,a),k="",l=e(),
m=Le[l],r="",w=(this.style!=Ce?Me:Ne)[m[0]],t=m.length-1,p=Oe,u,v=1;v<=t;v++){var x="";u=m[v];if(void 0!==u&&!(u&O&&this.style==Ke)){var A=u&Pe;if(A){var sa=u&Ge;sa?p=sa:u|=p;u&Qe||(u|=1==v?Re:Se);A&P?x=d(u):A&Je?x=c((u&Te)>>8,u):A&Ue&&(x=(l>>3&7).toString());if(!x||!x.length){r="INVALID";break}0<r.length&&(r+=",");r+=x||"???"}}}return this.J("%s %-9s%s %-7s %s\n",h,k,u&Ve?"*":" ",w,r)};
var Ke=8080,Ce=8086,Me="NONE ACI ADC ADD ADI ANA ANI CALL CC CM CNC CNZ CP CPE CPO CZ CMA CMC CMP CPI DAA DAD DCR DCX DI EI HLT IN INR INX JMP JC JM JNC JNZ JP JPE JPO JZ LDA LDAX LHLD LXI MOV MVI NOP ORA ORI OUT PCHL POP PUSH RAL RAR RET RC RM RNC RNZ RP RPE RPO RZ RLC RRC RST SBB SBI SHLD SPHL STA STAX STC SUB SUI XCHG XRA XRI XTHL".split(" "),Ne="NONE ADC ADC ADD ADD AND AND CALL CALLC CALLS CALLNC CALLNZ CALLNS CALLP CALLNP CALLZ NOT CMC CMP CMP DAA ADD DEC DEC CLI STI HLT IN INC INC JMP JC JS JNC JNZ JNS JP JNP JZ MOV MOV MOV MOV MOV MOV NOP OR OR OUT JMP POP PUSH RCL RCR RET RETC RETS RETNC RETNZ RETNS RETP RETNP RETZ ROL ROR RST SBB SBB MOV MOV MOV MOV STC SUB SUB XCHG XOR XOR XCHG".split(" "),
Fe=6,De="B C D E H L M A BC DE HL SP PC PS PSW".split(" "),Ge=15,Pe=240,Te=3840,Qe=61440,Oe=0,N=1,He=2,Ie=3,Je=16,P=32,Ee=64,Ue=128,Q=1792|Je|N,R=0|Je|N,T=256|Je|N,U=512|Je|N,V=768|Je|N,W=1024|Je|N,X=1280|Je|N,Y=Fe<<8|Je|N|Ee,We=2048|Je|Ie,Xe=2304|Je|Ie,Ye=2560|Je|Ie,Ze=2816|Je|Ie,$e=3584|Je|Ie,Se=4096,Re=8192,O=16384,Ve=32768,Le=[[45],[42,We,P],[71,We|Ee,Q|O],[29,We],[28,R],[22,R],[44,R,P],[63],[45,Ve],[21,Ye|O,We],[40,Q|O,We|Ee],[23,We],[28,T],[22,T],[44,T,P],[64],[45,Ve],[42,Xe,P],[71,Xe|Ee,Q|
O],[29,Xe],[28,U],[22,U],[44,U,P],[52],[45,Ve],[21,Ye|O,Xe],[40,Q|O,Xe|Ee],[23,Xe],[28,V],[22,V],[44,V,P],[53],[45,Ve],[42,Ye,P],[68,51|Ee,Ye|O],[29,Ye],[28,W],[22,W],[44,W,P],[20],[45,Ve],[21,Ye|O,Ye],[41,Ye|O,51|Ee],[23,Ye],[28,X],[22,X],[44,X,P],[16,Q|O],[45,Ve],[42,Ze,P],[70,51|Ee,Q|O],[29,Ze],[28,Y],[22,Y],[44,Y,P],[72],[45,Ve],[21,Ye|O,Ze],[39,Q|O,51|Ee],[23,Ze],[28,Q],[22,Q],[44,Q,P],[17],[43,R,R],[43,R,T],[43,R,U],[43,R,V],[43,R,W],[43,R,X],[43,R,Y],[43,R,Q],[43,T,R],[43,T,T],[43,T,U],[43,
T,V],[43,T,W],[43,T,X],[43,T,Y],[43,T,Q],[43,U,R],[43,U,T],[43,U,U],[43,U,V],[43,U,W],[43,U,X],[43,U,Y],[43,U,Q],[43,V,R],[43,V,T],[43,V,U],[43,V,V],[43,V,W],[43,V,X],[43,V,Y],[43,V,Q],[43,W,R],[43,W,T],[43,W,U],[43,W,V],[43,W,W],[43,W,X],[43,W,Y],[43,W,Q],[43,X,R],[43,X,T],[43,X,U],[43,X,V],[43,X,W],[43,X,X],[43,X,Y],[43,X,Q],[43,Y,R],[43,Y,T],[43,Y,U],[43,Y,V],[43,Y,W],[43,Y,X],[26],[43,Y,Q],[43,Q,R],[43,Q,T],[43,Q,U],[43,Q,V],[43,Q,W],[43,Q,X],[43,Q,Y],[43,Q,Q],[3,Q|O,R],[3,Q|O,T],[3,Q|O,U],[3,
Q|O,V],[3,Q|O,W],[3,Q|O,X],[3,Q|O,Y],[3,Q|O,Q],[2,Q|O,R],[2,Q|O,T],[2,Q|O,U],[2,Q|O,V],[2,Q|O,W],[2,Q|O,X],[2,Q|O,Y],[2,Q|O,Q],[73,Q|O,R],[73,Q|O,T],[73,Q|O,U],[73,Q|O,V],[73,Q|O,W],[73,Q|O,X],[73,Q|O,Y],[73,Q|O,Q],[66,Q|O,R],[66,Q|O,T],[66,Q|O,U],[66,Q|O,V],[66,Q|O,W],[66,Q|O,X],[66,Q|O,Y],[66,Q|O,Q],[5,Q|O,R],[5,Q|O,T],[5,Q|O,U],[5,Q|O,V],[5,Q|O,W],[5,Q|O,X],[5,Q|O,Y],[5,Q|O,Q],[76,Q|O,R],[76,Q|O,T],[76,Q|O,U],[76,Q|O,V],[76,Q|O,W],[76,Q|O,X],[76,Q|O,Y],[76,Q|O,Q],[46,Q|O,R],[46,Q|O,T],[46,Q|O,
U],[46,Q|O,V],[46,Q|O,W],[46,Q|O,X],[46,Q|O,Y],[46,Q|O,Q],[18,Q|O,R],[18,Q|O,T],[18,Q|O,U],[18,Q|O,V],[18,Q|O,W],[18,Q|O,X],[18,Q|O,Y],[18,Q|O,Q],[58],[50,We],[34,51],[30,51],[11,51],[51,We],[4,Q|O,P|N],[65,Ue],[62],[54],[38,51],[30,51|Ve],[15,51],[7,51],[1,Q|O,P|N],[65,Ue],[57],[50,Xe],[33,51],[48,P|N,Q|O],[10,51],[51,Xe],[74,Q|O,P|N],[65,Ue],[55],[54,Ve],[31,51],[27,Q|O,P|N],[8,51],[7,51|Ve],[67,Q|O,P|N],[65,Ue],[61],[50,Ye],[37,51],[78,Ze|Ee|O,Ye|O],[14,51],[51,Ye],[6,Q|O,P|N],[65,Ue],[60],[49,
Ye],[36,51],[75,Ye|O,Xe|O],[13,51],[7,51|Ve],[77,Q|O,P|N],[65,Ue],[59],[50,$e],[35,51],[24],[12,51],[51,$e],[47,Q|O,P|N],[65,Ue],[56],[69,Ze|O,Ye|O],[32,51],[25],[9,51],[7,51|Ve],[19,Q|O,P|N],[65,Ue]];q.Debugger=Be;
function af(a,b){F.call(this,a,a);var c=this;this.i=this.a=!1;this.b="";this.h=this.g=!1;b=b.trim();"{"==b[0]?bf(this,b):(this.b=b,Xa(this.b,function(d,e,g,h){4==g&&(!h&&e?(bf(c,e),cf(c)):c.O("error (%d) loading configuration: %s\n",h,d))}));window.addEventListener("load",function(){c.h=!0;cf(c)});window.addEventListener((bb("iOS")?"pagehide":bb("Opera")?"unload":void 0)||"beforeunload",function(){df(c)})}n(af,F);
af.prototype.Ca=function(a,b){var c=this;switch(a){case ed:b.onclick=function(){c.a&&c.pa()};break;case ef:b.onclick=function(){c.a&&c.Da()}}F.prototype.Ca.call(this,a,b)};
function cf(a){var b=!0;if(a.g&&a.h){for(var c in a.c){var d=void 0,e=void 0;try{var g=a.c[c];e=g["class"];q[e]?"Machine"==e?(a.O("PCjs %s v%3.2f\n%s\n%s\n",g.name,2,ff,gf),a.b&&a.O("Configuration: %s\n",a.b)):(d=new q[e](a.N,c,g),a.O("%s device: %s\n",e,d.status)):a.O("unrecognized %s device class: %s\n",c,e)}catch(k){a.O("error initializing %s device '%s': %s\n",e,c,k.message),rb(a,c),b=!1}}if(a.f){var h=cb(a);ob(a,function(k){k.gb&&k.gb(h)})}a.pa(b)}}
function df(a){if(a.f){var b=[];ob(a,function(c){c.Ra&&c.Ra(b)});hb(a,b)}a.pa(!1)}function bf(a,b){try{a.c=JSON.parse(b),lb(a,a.c[a.N]),a.f=!1!==a.S.autoSave,a.j=!1!==a.S.autoStart,a.g=!0}catch(e){var c=e.message,d=c.match(/position ([0-9]+)/);d&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')");z(a,"machine '"+a.N+"' initialization error: "+c)}}
af.prototype.pa=function(a){a=void 0===a?!this.i:a;var b=this;a&&z(this,"power on");ob(this,function(c){c.pa&&c!=b&&("CPU"!=c.S["class"]||b.j||b.a)&&c.pa(a)});this.a=!0;(this.i=a)||z(this,"power off")};af.prototype.Da=function(){var a=this;ob(this,function(b){b.Da&&b!=a&&b.Da()})};var ed="power",ef="reset",ff="Copyright \u00a9 2012-2019 Jeff Parsons <Jeff@pcjs.org>",gf="License: GPL version 3 or later <http://gnu.org/licenses/gpl.html>";
window.VT100=function(a,b){var c=new af(a,b);window.command=function(d){return Ma(c,d)};return c};q.Machine=af;})()

//# sourceMappingURL=vt100.js.map
