(function(){var l;
function ba(a,b){var c;if(a){b||(b=10);var d=a.charAt(0),f=0<a.indexOf(",");f&&(a=a.replace(/,/g,""));"#"==d?(b=8,d=null):"$"==d&&(b=16,d=null);null==d?a=a.substr(1):("0"==d&&(d=a.charAt(1),"b"==d&&f&&(b=2,d=null),"o"==d?(b=8,d=null):"x"==d&&(b=16,d=null)),null==d?a=a.substr(2):(d=a.charAt(a.length-1).toLowerCase(),"y"==d?(b=2,d=null):"."==d?(b=10,d=null):"h"==d&&(b=16,d=null),null==d&&(a=a.substr(0,a.length-1))));var e,d=a;((f=b)&&10!=f?16==f?d.match(/^[0-9a-f]+$/i):8==f?d.match(/^[0-7]+$/):2==f&&
d.match(/^[01]+$/):d.match(/^[0-9]+$/))&&!isNaN(e=parseInt(a,b))&&(c=e|0)}return c}function r(a,b,c){var d="";b?11<b&&(b=11):b=a&-65536?11:6;if(null==a||isNaN(a))for(;0<b--;)d="?"+d;else for(;0<b--;)d=String.fromCharCode((a&7)+48)+d,a>>=3;return(c?"0o":"")+d}function t(a,b,c){var d="";b?8<b&&(b=8):b=a&-65536?8:4;if(null==a||isNaN(a))for(;0<b--;)d="?"+d;else for(;0<b--;){var f=a&15,f=f+(0<=f&&9>=f?48:55),d=String.fromCharCode(f)+d;a>>=4}return(c?"0x":"")+d}
function ca(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));return b}function da(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase());return b}function ia(){var a=ja();return-1!==a.indexOf("pcjs.org",a.length-8)}var ka={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"};function la(a){return a.replace(/[&<>"']/g,function(a){return ka[a]})}function ma(a,b){return(a+"                                        ").slice(0,b)}
function na(a){return String.prototype.trim?a.trim():a.replace(/^\s+|\s+$/g,"")}function oa(a,b,c){var d=0,f=a.length,e=0;for(c||(c=function(a,b){return a>b?1:a<b?-1:0});d<f;){var g=d+f>>1,h;h=c(b,a[g]);0<h?d=g+1:(f=g,e=!h)}return e?d:~d}var pa=Date.now||function(){return+new Date};function qa(){function a(a){return(10>a?"0":"")+a}var b=new Date;return b.getFullYear()+"-"+a(b.getMonth()+1)+"-"+a(b.getDate())+" "+a(b.getHours())+":"+a(b.getMinutes())+":"+a(b.getSeconds())}
function ra(a,b,c,d){var f=0,e=null,g=null;if("object"==typeof resources&&(e=resources[a]))return d&&d(a,e,f),[e,f];if(c&&"function"==typeof resources)return resources(a,function(b,c){d&&d(a,b,c)}),g;var h=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");c&&(h.onreadystatechange=function(){4===h.readyState&&(e=h.responseText,200==h.status||!h.status&&e.length&&"file:"==(window?window.location.protocol:"file:")||(f=h.status||-1),d&&d(a,e,f))});if(b&&"object"==
typeof b){var k="",m;for(m in b)b.hasOwnProperty(m)&&(k&&(k+="&"),k+=m+"="+encodeURIComponent(b[m]));k=k.replace(/%20/g,"+");h.open("POST",a,!!c);h.setRequestHeader("Content-type","application/x-www-form-urlencoded");h.send(k)}else h.open("GET",a,!!c),"bytes"==b&&h.overrideMimeType("text/plain; charset=x-user-defined"),h.send();c||(e=h.responseText,200!=h.status&&(f=h.status||-1),d&&d(a,e,f),g=[e,f]);return g}function ja(){return"http://"+(window?window.location.host:"www.pcjs.org")}
function v(a){window&&window.alert(a)}function ta(a){var b=!1;window&&(b=window.confirm(a));return b}var ua=null;function va(){if(null==ua){var a=!1;if(window)try{window.localStorage.setItem("PCjs.localStorage","PCjs.localStorage"),a="PCjs.localStorage"==window.localStorage.getItem("PCjs.localStorage"),window.localStorage.removeItem("PCjs.localStorage")}catch(b){a=!1}ua=a}return ua}function za(a){var b;if(window)try{b=window.localStorage.getItem(a)}catch(c){}return b}
function Aa(a,b){try{return window.localStorage.setItem(a,b),!0}catch(c){}return!1}function Ba(a){if(window){var b=window?window.navigator.userAgent:"";return"iOS"==a&&b.match(/(iPod|iPhone|iPad)/)&&b.match(/AppleWebKit/)||"MSIE"==a&&b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)?!0:!1}return!1}function Ca(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function Da(a,b){function c(){b(100===d)&&(f=setTimeout(c,d),d=100)}var d=0,f=null,e=!1;a.onmousedown=function(){e||f||(d=500,c())};a.ontouchstart=function(){f||(d=500,c())};a.onmouseup=a.onmouseout=function(){f&&(clearTimeout(f),f=null)};a.ontouchend=a.ontouchcancel=function(){f&&(clearTimeout(f),f=null);e=!0}}var Ea={init:[],show:[],exit:[]},Fa=!1,Ga=!1,Ha=!0;function Ia(a,b){if(window){var c=window[a];window[a]="function"!==typeof c?b:function(){c&&c();b()}}}function Pa(a){Ea.init.push(a)}
function Qa(a){if(Ha)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){v(""+("An unexpected exception occurred:\n\n"+c.message+"\n\nPlease send this information to support@pcjs.org. Thanks."))}}function Ra(a){!Ha&&a?(Ha=!0,Fa&&Sa("init"),Ga&&Sa("show")):Ha=a}function Sa(a){Ea[a]&&Qa(Ea[a])}Ia("onload",function(){Fa=!0;Qa(Ea.init)});Ia("onpageshow",function(){Ga=!0;Qa(Ea.show)});Ia(Ba("Opera")||Ba("iOS")?"onunload":"onbeforeunload",function(){Qa(Ea.exit)});
function w(a,b,c,d){this.type=a;b||(b={id:"",name:""});this.id=b.id||"";this.name=b.name;this.vc=b.comment;this.Sc=b;b=this.id.indexOf(".");0>b?this.Fb=this.id:(this.wc=this.id.substr(0,b),this.Fb=this.id.substr(b+1));this[a]=c;this.u={ready:!1,Kb:!1,ic:!1,ja:!1,error:!1};this.ac=null;this.u.error=!1;this.K={};this.G=null;this.ka=d||0;x.push(this)}var Ta=void 0,Ua={};
if(window){Ta||(Ta=window.location.search.substr(1));for(var Va,Wa=/\+/g,Xa=/([^&=]+)=?([^&]*)/g;Va=Xa.exec(Ta);)Ua[decodeURIComponent(Va[1].replace(Wa," "))]=decodeURIComponent(Va[2].replace(Wa," "))}function Ya(a){function b(){}if(window){if(!a)throw new TypeError;if(Object.create)return Object.create(a);var c=typeof a;if("object"!==c&&"function"!==c)throw new TypeError;}b.prototype=a;return new b}
function B(a,b){b||(b=w);a.prototype=Ya(b.prototype);a.prototype.constructor=a;a.prototype.parent=b.prototype}if(window){window.PCjs||(window.PCjs={});var Za=window.PCjs.Machines||(window.PCjs.Machines={}),x=window.PCjs.Components||(window.PCjs.Components=[])}else Za={},x=[];function $a(a,b,c){Za[a]&&b&&(Za[a][b]=c)}function ab(a){var b,c=[];a&&(a=0<(b=a.indexOf("."))?a.substr(0,b+1):"");for(b=0;b<x.length;b++){var d=x[b];a&&d.id.indexOf(a)||c.push(d)}return c}
function bb(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<x.length;d++)if(c)c==x[d]&&(c=null);else if(!(a!=x[d].type||b&&x[d].id.indexOf(b)))return x[d]}return null}function C(a){var b=null;if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(c){v(c.message+" ("+a+")")}return b}
function cb(a,b){b=D(b.parentNode,"pdp11-control");for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,f=0;f<d.length;f++){var e=d[f];if(1===e.nodeType){var g=e.getAttribute("class");if(g)for(var h=g.split(" "),k=0;k<h.length;k++)switch(g=h[k],g){case "pdp11-binding":(g=C(e))&&g.binding&&a.xa(g.type,g.binding,e,g.value),k=h.length}}}}
function D(a,b,c){c&&(b+="-"+c+"-object");if(a.getElementsByClassName)return a.getElementsByClassName(b);var d;c=[];a=a.getElementsByTagName("*");var f=new RegExp("(^| )"+b+"( |$)");b=0;for(d=a.length;b<d;b++)f.test(a[b].className)&&c.push(a[b]);return c}
w.prototype={constructor:w,parent:null,toString:function(){return this.name?this.name:this.id||this.type},xa:function(a,b,c){switch(b){case "clear":return this.K[b]||(this.K[b]=c,c.onclick=function(a){return function(){a.K.print&&(a.K.print.value="")}}(this)),!0;case "print":return this.K[b]||(this.kb=this.K[b]=c,c.value="",this.g=function(a){return function(b,c){8192<a.value.length&&(a.value=a.value.substr(a.value.length-4096));a.value+=(void 0!==c?c+": ":"")+(b||"")+"\n";a.scrollTop=a.scrollHeight}}(c),
this.ra=function(a){this.g(a,this.Fb)}),!0;default:return!1}},log:function(){},g:function(){},status:function(a){this.g(this.Fb+": "+a)},ra:function(a,b,c){c=c||this.type;b||v((c?c+": ":"")+a)},Qa:function(){return this.u.ja=!0},Pa:function(a,b){b&&(this.u.ja=!1);return!0}};function db(a,b,c,d){a.G&&(!0===c||E(a,c|0))&&a.G.message(b,d)}function E(a,b){if(a.G){a===a.G?b|=0:b=b||a.ka;var c=a.G.ka&b;return!!b&&c===b||!!(c&a.G.Oc)}return!1}
function eb(a,b){if(a.u.ic)return a.u.Kb=!1,a.u.ic=!1;if(a.u.error)return a.g(a.toString()+" error"),!1;a.u.Kb=b;return a.u.Kb}function fb(a,b){a.u.Kb&&(b?a.u.ic=!0:void 0===b&&a.g(a.toString()+" busy"));return a.u.Kb}function F(a){if(!a.u.error&&(a.u.ready=!0,a.u.ready)){var b=a.ac;a.ac=null;b&&b()}}function gb(a,b){b&&(a.u.ready?b():a.ac=b);return a.u.ready}function tb(a){return a.u.error?(a.g(a.toString()+" error"),!0):!1}function ub(a,b){a.u.error=!0;a.ra(b)}
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return f.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),f=this;c.prototype=this.prototype;b.prototype=new c;return b});
var vb="undefined"!==typeof ArrayBuffer,G={cpu:1,trap:16,bus:64,mem:128,keyboard:65536,key:131072,disk:2097152,serial:8388608,speaker:33554432,computer:67108864,log:268435456,warn:536870912,buffer:1073741824,halt:-2147483648};function wb(a){w.call(this,"Panel",a,wb)}B(wb);l=wb.prototype;l.xa=function(a,b,c,d){return this.B&&this.B.xa(a,b,c,d)||this.b&&this.b.xa(a,b,c,d)||this.G&&this.G.xa(a,b,c,d)?!0:this.parent.xa.call(this,a,b,c,d)};l.Ya=function(a,b,c,d){this.B=a;this.H=b;this.b=c;this.G=d};
l.Qa=function(a,b){b||xb();return!0};l.Pa=function(){return!0};l.Ha=function(){};function xb(){for(var a=!1,b=D(document,"pdp11","panel"),c=0;c<b.length;c++){var d=b[c],f=C(d),e;a:{e=f.id;if(void 0!==e){var g;for(g=0;g<x.length;g++)if(x[g].id===e){e=x[g];break a}}e=null}e||(a=!0,e=new wb(f));cb(e,d);a&&F(e)}}Pa(xb);
function yb(a,b,c){w.call(this,"Bus",a,yb,64);this.b=b;this.G=c;this.I=a.busWidth||16;this.D=Math.pow(2,this.I);this.j=this.D-1|0;this.Z=(this.I>>1)+2;10>this.Z&&(this.Z=10);15<this.Z&&(this.Z=15);this.Ea=1<<this.Z;this.L=this.Ea>>2;this.f=this.Ea-1;this.A=this.D/this.Ea|0;this.B=this.A-1;this.Ta=[];this.F=null;this.Mb=this.Kc;a=new H;zb(a,this.G);this.O=Array(this.A);for(b=0;b<this.A;b++)this.O[b]=a;this.Hb=Array(4);this.Hb[0]=Ab;this.Hb[1]=Bb;this.Hb[2]=Cb;this.Hb[3]=Db;Eb(this,this.D-8192,8192,
Fb,this);Eb(this,57344,8192,Fb,this);F(this)}B(yb);function Ab(a,b){var c=this.controller,d=c.Ta[a];if(d){E(c)&&db(c,d[5]+".readByte("+r(b)+")",0,!0);if(d[0])return d[0](b);if(d[2])return b&1?d[2](b&-2)>>8:d[2](b)&255}else if(b&1&&(d=c.Ta[a&-2])&&(E(c)&&db(c,d[5]+".readByte("+r(b)+")",0,!0),d[2]))return d[2](b&-2)>>8;c.g("warning: unconverted read access to byte @"+r(b));return c.Mb(b,-1,1)}
function Bb(a,b,c){var d=this.controller,f=d.Ta[a];if(f){E(d)&&db(d,f[5]+".writeByte("+r(c)+","+r(b)+")",0,!0);if(f[1]){f[1](b,c);return}if(f[3]){a=f[2]?f[2](c):0;if(c&1)f[3](a&255|b<<8,c&-2);else f[3](a&-256|b,c);return}}else if(c&1&&(f=d.Ta[a&-2])&&(E(d)&&db(d,f[5]+".writeByte("+r(c)+","+r(b)+")",0,!0),f[3])){c&=-2;a=f[2]?f[2](c):0;f[3](a&255|b<<8,c);return}d.g("warning: unconverted write access to byte @"+r(c));d.Mb(c,b,1)}
function Cb(a,b){var c=this.controller;if(a=c.Ta[a]){E(c)&&db(c,a[5]+".readWord("+r(b)+")",0,!0);if(a[2])return a[2](b);if(a[0])return a[0](b)|a[0](b+1)<<8}c.g("warning: unconverted read access to word @"+r(b));return c.Mb(b,-1,0)}function Db(a,b,c){var d=this.controller;if(a=d.Ta[a]){E(d)&&db(d,a[5]+".writeWord("+r(c)+","+r(b)+")",0,!0);if(a[3]){a[3](b,c);return}if(a[1]){a[1](b&255,c);a[1](b>>8,c+1);return}}d.g("warning: unconverted write access to word @"+r(c));d.Mb(c,b,0)}l=yb.prototype;
l.reset=function(){this.F&&this.F()};l.Kc=function(){return 0};l.Qa=function(a,b){b||this.reset();return!0};
function Eb(a,b,c,d,f){for(var e=b,g=c,h=e>>>a.Z;0<g&&h<a.O.length;){var k=a.O[h],m=h*a.Ea,n=a.Ea-(e-m);n>g&&(n=g);if(k&&k.size){if(k.type==d&&k.controller==f){if(e+g<=k.w)return k.Yb+=k.w-e,k.w=e,!0;if(e>=k.w+k.Yb){n=k.size-(e-m);n>g&&(n=g);k.Yb=e-k.w+n;e=m+a.Ea;g-=n;h++;continue}}return Gb(1,e,g)}e=new H(e,n,a.Ea,d,f);zb(e,a.G,k);a.O[h++]=e;e=m+a.Ea;g-=n}return 0>=g?(a.status(Math.floor(c/1024)+"Kb "+Hb[d]+" at "+t(b,8,!0)),!0):Gb(2,b,c)}
l.sb=function(a){return this.O[(a&this.j)>>>this.Z].wb(a&this.f,a)};l.Ka=function(a){var b=a&this.f,c=(a&this.j)>>>this.Z;return b!=this.f?this.O[c].Rb(b,a):this.O[c++].wb(b,a)|this.O[c&this.B].wb(0,a+1)<<8};function Ib(a,b){var c=b&a.f,d=(b&a.j)>>>a.Z;return c!=a.f?a.O[d].oc(c,b):a.O[d++].Qb(c,b)|a.O[d&a.B].Qb(0,b+1)<<8}l.Vb=function(a,b){this.O[(a&this.j)>>>this.Z].Cb(a&this.f,b&255,a)};
l.pb=function(a,b){var c=a&this.f,d=(a&this.j)>>>this.Z;c!=this.f?this.O[d].Jc(c,b&65535,a):(this.O[d++].Cb(c,b&255,a),this.O[d&this.B].Cb(0,b>>8&255,a+1))};function Jb(a){for(var b=0,c=[],d=0;d<a.A;d++){var f=a.O[d];if(f.Xa||f.Rc){c[b++]=d;var e=b++;if(f=f.save()){for(var g=0,h=0,k=[];g<f.length;){for(var m=f[g],n=g+1;n<f.length&&f[n]===m;)n++;k[h++]=n-g;k[h++]=m;g=n}k.length<f.length&&(f=k)}c[e]=f}}return c}
function Kb(a,b){var c=Lb,d;for(d in c)for(var f=c[d],e=f[0]?f[0].bind(b):null,g=f[1]?f[1].bind(b):null,h=f[2]?f[2].bind(b):null,k=f[3]?f[3].bind(b):null,m=a,n=+d,f=f[4],p=+d;p<=n;p+=2){var q=p&8191;void 0!==m.Ta[q]?v("I/O address already registered: "+t(p,8,!0)):m.Ta[q]=[e,g,h,k,!1,f||"unknown"]}}function Mb(a,b,c){a.F=b;a.Mb=c}function Gb(a,b,c){v("Memory block error ("+a+": "+t(b)+","+t(c)+")");return!1}
function I(a){w.call(this,"Device",a,I);this.f={nc:[],va:0,ya:128,G:127,Qc:0};this.B={data:0,wd:0,tb:20,pd:0};this.j={M:0,sc:-1};this.A={Tb:2496,oa:0,R:128,Ub:0,Sb:0,wa:0,Ec:0,qa:[],hb:[406,406,406,406],aa:[12,12,12,12]};this.D={M:129,Jb:0,ga:0,$a:0,Ua:0,fb:0,qa:[],aa:[40,40,40,40],hb:[1024,1024,512,512],Mc:[157,157,29,29]};this.F={b:[8210,8208,8210,8226],aa:[22,22,22,50],gb:[19,19,19,32],hc:[815,411,815,630],qa:[],T:2176,zb:0,xb:0,Ga:[0,0,0,0,0,0,0,0],Fa:0,sa:[4544,4544,4544,4544,4544,4544,4544,
4544],yb:[0,0,0,0,0,0,0,0],ob:0,md:[0,0,0,0,0,0,0,0],Fc:0,Gc:[0,0,0,0,0,0,0,0],f:[0,0,0,0,0,0,0,0],nd:[1,2,3,4,5,6,7,8],Hc:[0,0,0,0,0,0,0,0],Sa:[0,0,0,0,0,0,0,0],gc:[0,0,0,0,0,0,0,0],kd:[0,0,0,0,0,0,0,0],ld:[0,0,0,0,0,0,0,0],hd:[0,0,0,0,0,0,0,0],jd:[0,0,0,0,0,0,0,0],eb:0,qc:0}}B(I);
var Nb=[4127,448,4191,450,4383,452,2591,454,21983,32768,65534,13791,16384,65534,770,2719,454,2591,65534,257,0,2566,33028,34051,33282,1281,33537,0,2758,32771,770,1025,1793,0,3078,33794,34305,513,0,5574,43690,4480,4097,4162,4227,4292,4357,57665,1281,769,0,3138,34305,1281,0,24707,2691,2627,24769,34561,1793,0,3076,20739,24899,2691,34562,2753,1281,0,2624,33537,0,16385,24641,1537,1793,0,193,8279,21589,516,12549,1538,2629,513,0,38336,65281,32769,0,32258,2561,2689,32258,3008,514,3009,769,0,5574,510,2551,
2,0,9678,208,769,0,5582,226,135,0,2598,5606,236,2,0,95,242,128,5573,57344,2591,6,5599,256,4,5574,510,3045,5599,460,76,2591,78,5571,65510,5579,12,5570,512,4224,4104,3024,8197,33788,4224,4609,8193,769,0,2640,8197,33785,6145,2625,8193,769,0,8194,761,2574,5572,43690,5579,24,5568,2048,5570,512,2628,4360,2632,2632,8708,769,0,3103,65514,34562,0,305,35406,754,258,119,65160,3024,32403,5579,36,5568,3072,35446,1,740,5570,512,4224,4104,3024,8197,33788,5569,3,2574,3039,454,528,5582,24,4224,2632,2632,8200,769,
0,3024,3103,65514,34562,0,264,8197,33779,5003,2574,32337,260,0,258,5579,12,6080,448,6081,450,6084,452,116,2,6084,65400,17860,65024,21956,62976,38848,65401,3200,161,76,0,16944,10797];l=I.prototype;l.Ya=function(a,b,c,d){this.H=b;this.b=c;this.G=d;var f=this;this.j.sc=Ob(this.b,function(){f.j.Za|=128;f.j.Za&64&&(J(f.b,0,6,64),Pb(f.b,f.j.sc))});Kb(b,this);Mb(b,this.reset.bind(this),this.Lc.bind(this));F(this)};l.$c=function(){var a=this.j.Za;this.j.Za&=-129;return a};
l.rd=function(a){this.j.Za=a;a&64&&Pb(this.b,this.j.sc);this.j.Za=a&-129};l.ad=function(){var a=this.b;return a.I&62337|a.za<<5|a.Ba<<1};l.sd=function(a){var b=4,c=this.b;c.I=a&=62337;c.za=a>>5&3;c.Ba=a>>1&15;c.bc=a&257?a&1?6:4:0;Qb(c);a=c.I;a&1|256&&(b=this.b.nb&16?1:2);this.B.tb=this.B.tb&-8|b};l.cd=function(){return this.f.va};l.ud=function(a){this.f.va=this.f.va&128|a&-129};l.dd=function(){return this.f.ya};
l.vd=function(a){if(128==(this.f.ya&192)&&a&64){var b=this;J(this.b,8,4,52,function(){b.f.ya|=128;return!!(b.f.ya&64)})}this.f.ya=this.f.ya&128|a&-129};l.bd=function(){return Zb(this.b)};l.td=function(a){$b(this.b,a&-1809|Zb(this.b)&1808);this.b.C|=128};
function ac(a){var b=a.A,c,d,f,e=b.wa>>13&7;"undefined"===typeof b.qa[e]&&(b.qa[e]={cache:[],postProcess:a.ed,drive:e,blocksize:256,mapped:0,maxblock:b.hb[e]*b.aa[e],url:"rk"+e+".dsk"});b.R&=-129;switch(b.R>>1&7){case 0:b.Tb=2496;b.oa=0;b.R=128;b.wa=0;break;case 1:if((b.wa>>4&511)>=b.hb[e]){b.oa|=32832;b.R|=49152;break}if((b.wa&15)>=b.aa[e]){b.oa|=32800;b.R|=49152;break}c=(b.wa>>4&511)*b.aa[e]+(b.wa&15);d=(b.R&48)<<12|b.Sb;f=65536-b.Ub&65535;bc(a,b.qa[e],c,d,f);return;case 2:if((b.wa>>4&511)>=b.hb[e])b.oa|=
32832,b.R|=49152;else if((b.wa&15)>=b.aa[e])b.oa|=32800,b.R|=49152;else{c=(b.wa>>4&511)*b.aa[e]+(b.wa&15);d=(b.R&48)<<12|b.Sb;f=65536-b.Ub&65535;a.dc(b.qa[e],c,d,f);return}}b.Tb=e<<13|b.Tb&8176|b.wa%9&15;J(a.b,20,5,144,function(){b.R=b.R&65534|128;return!!(b.R&64)})}l.ed=function(a,b,c,d,f){var e=this.A;e.Sb=d&65535;e.R=e.R&-49|d>>12&48;e.Ub=65536-f&65535;switch(a){case 1:e.oa|=33024;e.R|=49152;break;case 2:e.oa|=33792,e.R|=49152}J(this.b,20,5,144,function(){e.R=e.R&65534|128;return!!(e.R&64)})};
function cc(a){var b=a.D,c,d,f,e=b.M>>8&3;b.M&=-2;"undefined"===typeof b.qa[e]&&(b.qa[e]={cache:[],postProcess:a.fd,drive:e,blocksize:128,mapped:1,maxblock:b.hb[e]*b.aa[e],url:"rl"+e+".dsk"});switch(b.M>>1&7){case 2:b.$a&8&&(b.M&=63);b.$a=b.Mc[e]|b.fb&64;break;case 3:1==(b.ga&3)&&(b.fb=b.ga&4?b.fb+(b.ga&65408)&65408|b.ga<<2&64:b.fb-(b.ga&65408)&65408|b.ga<<2&64,b.ga=b.fb);break;case 4:b.$a=b.fb;break;case 5:if(b.ga>>6>=b.hb[e]){b.M|=37888;break}if((b.ga&63)>=b.aa[e]){b.M|=37888;break}c=(b.ga>>6)*
b.aa[e]+(b.ga&63);d=(b.Ua&63)<<16|b.Jb;f=65536-b.$a&65535;bc(a,b.qa[e],c,d,f);return;case 6:if(b.ga>>6>=b.hb[e])b.M|=37888;else if((b.ga&63)>=b.aa[e])b.M|=37888;else{c=(b.ga>>6)*b.aa[e]+(b.ga&63);d=(b.Ua&63)<<16|b.Jb;f=65536-b.$a&65535;a.dc(b.qa[e],c,d,f);return}}J(a.b,20,5,112,function(){b.M|=129;return!!(b.M&64)})}
l.fd=function(a,b,c,d,f){var e=this.D;e.Jb=d&65535;e.M=e.M&-49|d>>12&48;e.Ua=d>>16&63;e.ga=~~(c/e.aa[b.Na])<<6|c%e.aa[b.Na];e.fb=e.ga;e.$a=65536-f&65535;switch(a){case 1:e.M|=33792;break;case 2:e.M|=40960}J(this.b,20,5,112,function(){e.M|=129;return!!(e.M&64)})};function dc(a){a=a.F;a.T=2176;a.Fa=0;a.sa=[4544,4544,4544,4544,4544,4544,4544,4544];a.yb=[0,0,0,0,0,0,0,0];a.ob=a.zb=a.xb=a.eb=a.qc=0}
function ec(a,b){var c=a.F,d,f,e;c.T&=-16513;c.Fa&=-2049;c.sa[b]&=-1153;J(a.b,-1,0,172);"undefined"===typeof c.qa[b]&&(c.qa[b]={cache:[],postProcess:a.gd,drive:b,blocksize:256,mapped:0,maxblock:c.hc[0]*c.gb[0]*c.aa[0],url:"rp"+b+".dsk"});switch(c.T&63){case 5:c.gc[b]=c.Sa[b];c.T|=32896;c.sa[b]|=32896;c.ob|=1<<b;break;case 9:dc(a);break;case 19:c.sa[b]|=64;break;case 49:if(c.Sa[b]>=c.hc[0]||c.Ga[b]>>8>=c.gb[0]||(c.Ga[b]&255)>=c.aa[0]){c.yb[b]|=1024;c.T|=49152;break}d=(c.Sa[b]*c.gb[0]+(c.Ga[b]>>8))*
c.aa[0]+(c.Ga[b]&255);f=(c.eb&63)<<16|c.xb;e=65536-c.zb&65535;bc(a,c.qa[b],d,f,e);return;case 57:if(c.Sa[b]>=c.hc[0]||c.Ga[b]>>8>=c.gb[0]||(c.Ga[b]&255)>=c.aa[0])c.yb[b]|=1024,c.T|=49152;else{d=(c.Sa[b]*c.gb[0]+(c.Ga[b]>>8))*c.aa[0]+(c.Ga[b]&255);f=(c.eb&63)<<16|c.xb;e=65536-c.zb&65535;a.dc(c.qa[b],d,f,e);return}}J(a.b,3,5,172,function(){c.T=c.T&65534|128;c.sa[b]|=128;return!!(c.T&64)})}
l.gd=function(a,b,c,d,f){var e=this.F;e.zb=65536-f&65535;e.xb=d&65535;e.T=e.T&-769|d>>8&768;e.eb=d>>16&63;f=~~(c/e.aa[0]);d=~~(f/e.gb[0]);e.Ga[b.Na]=f%e.gb[0]<<8|c%e.aa[0];e.gc[b.Na]=e.Sa[b.Na]=d;e.ob|=1<<b.Na;c>=b.Xc-1&&(e.sa[b.Na]|=1024);switch(a){case 1:e.Fa|=512;e.T|=49152;break;case 2:e.Fa|=2048,e.T|=49152}J(this.b,20,5,172,function(){e.sa[b.Na]|=128;e.T=e.T&65534|128;return!!(e.T&64)})};
function fc(a,b,c,d,f,e){var g=~~((e+c.Va-1)/c.Va),h=new XMLHttpRequest;2048>g&&d+2048<c.Xc&&(g=2048);h.open("GET",c.url,!0);h.setRequestHeader("Range","bytes="+(d*c.Va<<1)+"-"+(((d+g)*c.Va<<1)-1));h.responseType="arraybuffer";h.onreadystatechange=function(){if(4==h.readyState){var g=b.bind(a),m,n,p,q;m=h.response;if(h.status&&206!=h.status||!m)c.mc(1,c,d,f,e);else{m=new Uint8Array(m);n=d;for(q=0;q<m.length;){if("undefined"===typeof c.cache[n])for(c.cache[n]=[],p=0;p<c.Va;p++)c.cache[n][p]=q<m.length?
m[q]&255|m[q+1]<<8&65280:0,q+=2;else q+=c.Va<<1;n++}g(c,d,f,e)}}};h.send(null)}function K(a,b,c,d,f){c&1?f?d=0<=d?d<<8&65280|b&255:b:a.b.N(4,122):0<=d?f&&(d=b&65280|d&255):d=b;return d}l.dc=function(a,b,c,d){for(var f;0<d;){if("undefined"===typeof a.cache[b]){fc(this,this.dc,a,b,c,d);return}for(f=0;f<a.Va&&0<d;f++){var e=a.Wc?gc(this.b,c):c;this.b.H.pb(e,a.cache[b][f]&65535);c+=2;--d}b++}a.mc(0,a,b,c,d)};
function bc(a,b,c,d,f){for(var e,g;0<f;){if("undefined"===typeof b.cache[c])for(b.cache[c]=[],e=0;e<b.Va;e++)b.cache[c][e]=0;for(e=0;e<b.Va&&0<f;e++){g=a.b.ec(b.Wc?gc(a.b,d):d);if(0>g){b.mc(2,b,c,d,f);return}b.cache[c][e]=g;d+=2;--f}c++}b.mc(0,b,c,d,f)}l.reset=function(){this.B.tb=this.B.tb&-120|20;this.f.va=0;this.f.ya=128;this.j.Za=0;this.A.R=128;this.D.M=128;dc(this)};
l.Lc=function(a,b,c){var d,f,e=this.b;switch(a&-64){case 4194240:switch(a&-2){case 4194300:0>b?d=e.cb&65280:(a&1&&(b<<=8),e.cb=b|255,d=0);break;case 4194298:if(0>b)d=e.pc;else{a&1&&(b<<=8);if(d=b&65024){f=d>>9;do d+=34;while(f>>=1)}e.pc=d;e.C|=2}break;case 4194294:if(70!==e.lb)return e.N(4,222);0>b?d=e.J:d=e.J=0;break;case 4194292:if(70!==e.lb)return e.N(4,224);d=1;break;case 4194290:if(70!==e.lb)return e.N(4,226);d=0;break;case 4194288:if(70!==e.lb)return e.N(4,228);d=61183;break;case 4194296:0<=
b&&!(a&1)&&(b&=255);case 4194286:case 4194284:case 4194282:case 4194280:case 4194278:case 4194276:case 4194274:case 4194272:if(70!==e.lb)return e.N(4,232);f=a-4194272>>1;0>b?d=e.kc[f]:(d=K(this,e.kc[f],a,b,c),0<=d&&(e.kc[f]=d));break;case 4194254:return a&1?e.P>>14&1?(0<=b&&(e.i[6]=b),d=e.i[6]):(0<=b&&(e.Aa[3]=b),d=e.Aa[3]):e.P>>14&0?(0<=b&&(e.i[6]=b),d=e.i[6]):(0<=b&&(e.Aa[1]=b),d=e.Aa[1]),d;case 4194252:case 4194250:case 4194248:return f=a&7,e.P&2048?(0<=b&&(e.i[f]=b),d=e.i[f]):(0<=b&&(e.Ra[f]=
b),d=e.Ra[f]),d;case 4194246:return a&1?(0<=b&&(e.i[7]=b),d=e.i[7]):e.P>>14&0?(0<=b&&(e.i[6]=b),d=e.i[6]):(0<=b&&(e.Aa[0]=b),d=e.Aa[0]),d;case 4194244:case 4194242:case 4194240:return f=a&7,e.P&2048?(0<=b&&(e.Ra[f]=b),d=e.Ra[f]):(0<=b&&(e.i[f]=b),d=e.i[f]),d;default:return e.J|=16,e.N(4,124)}break;case 4194176:f=a>>1&31;d=K(this,e.na[3][f],a,b,c);0<=d&&(e.na[3][f]=d,e.na[3][f&15]&=65295);break;case 4194112:var g=this.f;switch(a&-2){case 4194174:d=K(this,e.fc,a,b,c);0<=d&&(e.fc=d);break;case 4194172:d=
e.bb;d&65280&&(d=(d<<8|d>>8)&65535);break;case 4194168:0>b?d=this.B.pd&65535:(d=K(this,this.B.data,a,b,c),0<=d&&(this.B.data=d));break;case 4194166:0<=b&&(b&127&&(g.Qc=0),g.ya&=-129,J(e,100,4,52,function(){g.ya|=128;return!!(g.ya&64)}));d=0;break;case 4194162:d=0;0>b&&(g.va&=-129,0<g.nc.length&&(d=g.nc.shift(),0<g.nc.length&&setTimeout(function(){g.va|=128;g.va&64&&J(e,40,4,48)},50)));break;case 4194160:0>b?d=g.va:(d=K(this,g.va,a,b,c),0<=d&&(g.va=g.va&128|d&-129));break;default:return e.J|=16,e.N(4,
126)}break;case 4194048:f=this.A;switch(a&-2){case 4194048:d=K(this,f.Tb,a,b,c);0<=d&&(f.Tb=d);break;case 4194050:d=K(this,f.oa,a,b,c);0<=d&&(f.oa=d);break;case 4194052:d=K(this,f.R,a,b,c);0<=b&&0<=d&&(f.R=d&-36993|f.R&36992,f.R&1&&ac(this));break;case 4194054:d=K(this,f.Ub,a,b,c);0<=d&&(f.Ub=d);break;case 4194056:d=K(this,f.Sb,a,b,c);0<=d&&(f.Sb=d);break;case 4194058:d=K(this,f.wa,a,b,c);0<=d&&(f.wa=d);break;case 4194060:break;case 4194062:d=K(this,f.Ec,a,b,c);0<=d&&(f.Ec=d);break;default:return e.J|=
16,e.N(4,128)}break;case 4193728:var h=this.F;f=h.Fa&7;switch(a&-2){case 4193728:d=K(this,h.T,a,b,c);0<=b&&0<=d&&(h.eb=h.eb&60|d>>8&3,h.T=d&17279|h.T&34944|2048,d&1&&h.T&128?ec(this,f):192==(d&192)&&J(e,0,5,172));break;case 4193730:d=K(this,h.zb,a,b,c);0<=d&&(h.zb=d);break;case 4193732:d=K(this,h.xb,a,b,c);0<=d&&(h.xb=d&65534);break;case 4193734:d=K(this,h.Ga[f],a,b,c);0<=d&&(h.Ga[f]=d&7967);break;case 4193736:d=K(this,h.Fa,a,b,c);0<=d&&(h.Fa=d&63|h.Fa&65472,d&128&&dc(this));break;case 4193738:d=
h.sa[f];break;case 4193740:d=h.yb[f];break;case 4193742:d=K(this,h.ob,a,b,c);0<=d&&(h.ob=d&255);break;case 4193744:d=h.md[f];break;case 4193746:d=K(this,h.Fc,a,b,c);0<=d&&(h.Fc=d);break;case 4193748:d=K(this,h.Gc[f],a,b,c);0<=d&&(h.Gc[f]=d&1023);break;case 4193750:d=8210;break;case 4193752:d=h.nd[f];break;case 4193754:d=K(this,h.Hc[f],a,b,c);0<=d&&(h.Hc[f]=d);break;case 4193756:d=K(this,h.Sa[f],a,b,c);0<=d&&(h.Sa[f]=d&511);break;case 4193758:h.gc[f]=h.Sa[f];d=h.gc[f];break;case 4193760:d=h.kd[f];
break;case 4193762:d=h.ld[f];break;case 4193764:d=h.hd[f];break;case 4193766:d=h.jd[f];break;case 4193768:d=K(this,h.eb,a,b,c);0<=d&&(h.eb=d&63,h.T=h.T&-769|(d&3)<<8);break;case 4193770:d=K(this,h.qc,a,b,c);0<=d&&(h.qc=d);break;default:return e.J|=16,e.N(4,132)}break;case 4192512:f=this.D;switch(a&-2){case 4192512:d=K(this,f.M,a,b,c);0<=b&&0<=d&&(f.Ua=f.Ua&60|d>>4&3,f.M=f.M&-1023|d&1022,f.M&128||cc(this));break;case 4192514:d=K(this,f.Jb,a,b,c);0<=d&&(f.Jb=d&65534);break;case 4192516:d=K(this,f.ga,
a,b,c);0<=d&&(f.ga=d);break;case 4192518:d=K(this,f.$a,a,b,c);0<=d&&(f.$a=d);break;case 4192520:d=K(this,f.Ua,a,b,c);0<=d&&(f.Ua=d&63,f.M=f.M&-49|(f.Ua&3)<<4);break;default:return e.J|=16,e.N(4,134)}break;case 4191552:switch(a&-2){case 4191566:0>b?d=e.nb:(d=K(this,e.nb,a,b,c),0<=d&&(70!==e.lb&&(d&=-49),e.nb=d,e.cc[0]=d&4?15:7,e.cc[1]=d&2?15:7,e.cc[3]=d&1?15:7,e.bc&&(f=2,e.nb&16&&(f=1),this.B.tb=this.B.tb&-8|f)));break;default:return e.J|=16,e.N(4,136)}break;case 4191424:f=a>>1&31;d=K(this,e.na[0][f],
a,b,c);0<=d&&(e.na[0][f]=d,e.na[0][f&15]&=65295);break;case 4191360:f=a>>1&31;d=K(this,e.na[1][f],a,b,c);0<=d&&(e.na[1][f]=d,e.na[1][f&15]&=65295);break;case 4190400:case 4190336:if(70!==e.lb)return e.N(4,234);f=a>>2&31;d=e.Wb[f];a&2&&(d>>=16);d&=65535;0<=b&&(d=K(this,d,a,b,c),0<=d&&(e.Wb[f]=a&2?d<<16|e.Wb[f]&65535:e.Wb[f]&4294901760|d&65534));break;case 4188672:case 4188736:case 4188800:case 4188864:case 4188928:case 4188992:case 4189056:case 4189120:if(0>b)d=Nb[a>>1&255];else return e.J|=16,e.N(4,
138);break;default:return e.J|=16,e.N(4,142)}c&&0<=d&&(a&1?d>>=8:d&=255);"undefined"===typeof d&&console.log("panic(76)");return d};var hc={},Lb=(hc[65382]=[null,null,I.prototype.$c,I.prototype.rd,"LKS"],hc[65392]=[null,null,I.prototype.cd,I.prototype.ud,"RCSR"],hc[65396]=[null,null,I.prototype.dd,I.prototype.vd,"XCSR"],hc[65402]=[null,null,I.prototype.ad,I.prototype.sd,"MMR0"],hc[65534]=[null,null,I.prototype.bd,I.prototype.td,"PSW"],hc);
Pa(function(){for(var a=D(document,"pdp11","device"),b=0;b<a.length;b++){var c=a[b],d=C(c),d=new I(d);cb(d,c)}});var ic;if(vb){var jc=new ArrayBuffer(2);(new DataView(jc)).setUint16(0,256,!0);ic=256===(new Uint16Array(jc))[0]}else ic=!1;var kc=ic;
function H(a,b,c,d,f){this.id=lc+=2;this.b=null;this.w=a;this.Yb=b;this.size=c||0;this.type=d||mc;this.j=d==nc;this.controller=null;zb(this);this.Xa=this.Rc=!1;if(c)if(f)this.controller=f,this.b=null,oc(this,f.Hb);else if(vb)this.D=new ArrayBuffer(c),this.F=new DataView(this.D,0,c),this.f=new Uint8Array(this.D,0,c),this.L=new Uint16Array(this.D,0,c>>1),this.b=new Int32Array(this.D,0,c>>2),oc(this,kc?pc:qc);else{this.b=Array(c>>2);for(a=0;a<this.b.length;a++)this.b[a]=0;oc(this,rc)}else oc(this)}
var mc=0,nc=2,Fb=4,Hb=["NONE","RAM","ROM","VID","H/W"],lc=0;
H.prototype={constructor:H,parent:null,save:function(){var a,b;if(this.controller)a=null;else if(vb)for(a=Array(this.size>>2),b=0;b<a.length;b++)a[b]=this.F.getInt32(b<<2,!0);else a=this.b;return a},restore:function(a){if(this.controller)return!a;if(a&&this.size==a.length<<2){var b;if(vb)for(b=0;b<a.length;b++)this.F.setInt32(b<<2,a[b],!0);else this.b=a;return this.Xa=!0}return!1},jb:function(a,b){b?this.B++||sc(this,tc,!1):this.K++||uc(this,tc,!1)},S:function(){this.G&&E(this.G,129)&&this.G.message("attempt to read invalid block %"+
t(this.w),!0);return 255},A:function(a,b){this.G&&E(this.G,129)&&this.G.message("attempt to write "+t(b,4,!0)+" to invalid block %"+t(this.w),!0)},W:function(a,b){return this.wb(a++,b++)|this.wb(a,b)<<8},I:function(a,b,c){this.Cb(a++,b&255,c++);this.Cb(a,b>>8,c)},da:function(a){return this.b[a>>2]>>>((a&3)<<3)&255},ma:function(a){var b=a>>2;a=(a&3)<<3;var c=this.b[b]>>a;return 24>a?c&65535:c&255|(this.b[b+1]&255)<<8},Ba:function(a,b){var c=a>>2;a=(a&3)<<3;this.b[c]=this.b[c]&~(255<<a)|b<<a;this.Xa=
!0},Fb:function(a,b){var c=a>>2;a=(a&3)<<3;24>a?this.b[c]=this.b[c]&~(65535<<a)|b<<a:(this.b[c]=this.b[c]&16777215|b<<24,c++,this.b[c]=this.b[c]&-256|b>>8);this.Xa=!0},ba:function(a,b){if(this.G&&null!=this.w){var c=this.G;vc(c,this.w+a,1,c.W)&&c.pa(!0)}return this.Qb(a,b)},ia:function(a,b){if(this.G&&null!=this.w){var c=this.G;vc(c,this.w+a,2,c.W)&&c.pa(!0)}return this.oc(a,b)},ua:function(a,b,c){if(this.G&&null!=this.w){var d=this.G;vc(d,this.w+a,1,d.D)&&d.pa(!0)}this.j?this.A(a,b,c):this.Db(a,
b,c)},Da:function(a,b,c){if(this.G&&null!=this.w){var d=this.G;vc(d,this.w+a,2,d.D)&&d.pa(!0)}this.j?this.A(a,b,c):this.tc(a,b,c)},$:function(a){return this.f[a]},ca:function(a){return this.f[a]},fa:function(a){return this.F.getUint16(a,!0)},la:function(a){return a&1?this.f[a]|this.f[a+1]<<8:this.L[a>>1]},ta:function(a,b){this.f[a]=b;this.Xa=!0},za:function(a,b){this.f[a]=b;this.Xa=!0},Ca:function(a,b){this.F.setUint16(a,b,!0);this.Xa=!0},Ia:function(a,b){a&1?(this.f[a]=b,this.f[a+1]=b>>8):this.L[a>>
1]=b;this.Xa=!0}};function zb(a,b,c){a.G=b;a.K=a.B=0;c&&((a.K=c.K)&&uc(a,tc,!1),(a.B=c.B)&&sc(a,tc,!1))}function wc(a,b){b?--a.B||(a.Cb=a.j?a.A:a.Db,a.Jc=a.j?a.I:a.tc):--a.K||(a.wb=a.Qb,a.Rb=a.oc)}function sc(a,b,c){c&&a.B||(a.Cb=!a.j&&b[1]||a.A,a.Jc=!a.j&&b[3]||a.I);if(c||void 0===c)a.Db=b[1]||a.A,a.tc=b[3]||a.I}function uc(a,b,c){c&&a.K||(a.wb=b[0]||a.S,a.Rb=b[2]||a.W);if(c||void 0===c)a.Qb=b[0]||a.S,a.oc=b[2]||a.W}function oc(a,b){b||(b=xc);uc(a,b,void 0);sc(a,b,void 0)}
var xc=[],rc=[H.prototype.da,H.prototype.Ba,H.prototype.ma,H.prototype.Fb],tc=[H.prototype.ba,H.prototype.ua,H.prototype.ia,H.prototype.Da];if(vb)var qc=[H.prototype.$,H.prototype.ta,H.prototype.fa,H.prototype.Ca],pc=[H.prototype.ca,H.prototype.za,H.prototype.la,H.prototype.Ia];
function yc(a,b){w.call(this,"CPU",a,yc,1);var c=a.multiplier||1;this.Da=a.cycles||b;this.ab=c;this.ib=Math.round(this.Da/1E4)/100;this.mb=this.ib*this.ab;this.u.ha=!1;this.u.rc=!1;this.u.Ib=a.autoStart;this.u.zc=!1;this.u.rb=!1;this.Nb=this.ia=0;this.Ob=a.csStart;this.ub=a.csInterval;this.vb=a.csStop;this.S=[];this.$b=this.od.bind(this);F(this)}B(yc);var zc=["power","reset"];l=yc.prototype;
l.Ya=function(a,b,c,d){this.B=a;this.H=b;this.G=d;for(b=0;b<zc.length;b++)(c=this.K[zc[b]])&&this.B.xa(null,zc[b],c);this.ta=null;a=Ac(a,"autoStart");null!=a&&(this.u.Ib="true"==a?!0:"false"==a?!1:!!a);F(this)};l.reset=function(){};l.save=function(){return null};l.restore=function(){return!1};
l.Qa=function(a,b){if(!b){if(a&&this.restore){Bc(this);if(!this.restore(a))return!1;Cc(this)}else this.reset();this.G?(a=this.G,a.g("Type ? for help with PDP11 Debugger commands"),a.Ha(),a.ib&&(b=a.ib,a.ib=null,Dc(a,b))):this.g("No debugger detected")}L(this);return!0};l.Pa=function(a){return a?this.save():!0};l.Ib=function(){return this.u.Ib||!this.G&&void 0===this.K.run?(this.Ab(!0),!0):!1};l.Bc=function(){return 0};
function Cc(a){void 0===a.Ob&&(a.Ob=0);void 0===a.ub&&(a.ub=-1);void 0===a.vb&&(a.vb=-1);a.u.rb=0<=a.Ob&&0<a.ub;a.u.rb&&(a.Nb=0,a.ia=a.Ob-a.fa)}function Ec(a,b){if(a.u.rb){var c=!1;a.Nb=a.Nb+a.Bc()|0;a.ia-=b;0>=a.ia&&(a.ia+=a.ub,c=!0);0<=a.vb&&a.vb<=Yc(a)&&(a.ub=a.vb=-1,Cc(a),a.pa(),c=!0);c&&a.g(Yc(a)+" cycles: checksum="+t(a.Nb))}}
function Zc(a,b,c,d){if(a.K[b]){void 0===c&&(ub(a,"Value for "+b+" is invalid"),a.pa());var f=a.G&&a.G.da||8;c=!a.u.ha||a.u.zc?8==f?r(c,d):t(c,d):"--------".substr(0,d||4);a.K[b].textContent!=c&&(a.K[b].textContent=c)}}
l.xa=function(a,b,c){var d=this;a=!1;switch(b){case "power":case "reset":this.K[b]=c;a=!0;break;case "run":this.K[b]=c;c.onclick=function(){var a;if(a=d.B)if(a=d.B,a.u.ja)a=!0;else{var b=null,c,h=ab(a.id);for(c=0;c<h.length&&(b=h[c],b===a||b.u.ready);c++);if(c==h.length)for(c=0;c<h.length&&(b=h[c],b===a||b.u.ja);c++);c==h.length&&(b=a);v("The "+b.type+" component ("+b.id+") is not "+(b.u.ready?"powered yet":"ready yet"+(b.ac?" (waiting for notification)":""))+".");a=!1}a&&(d.u.ha?d.pa():d.Ab())};
a=!0;break;case "speed":this.K[b]=c;a=!0;break;case "setSpeed":this.K[b]=c,c.onclick=function(){$c(d,d.ab<<1,!0)},c.textContent=this.mb.toFixed(2)+"Mhz",a=!0}return a};function ad(a,b,c){a.fa+=b;c&&(a.da=a.b=0)}function bd(a,b){var c=1;b&&1<a.ab&&a.ba&&(c=a.ba/a.ib);a.Lb=Math.round(1E3/30);a.Ia=Math.floor(a.Da/30*c);b||(a.la=a.Ia);a.qb=0}function Yc(a){return a.fa+a.$+a.da-a.b}function Bc(a){a.ba=0;a.Zb=0;a.fa=a.$=a.da=a.b=0;Cc(a);$c(a,1)}
function $c(a,b,c){var d=!1;if(void 0!==b){.8>a.ba/a.mb?b=1:d=!0;a.ab=b;b=a.ib*a.ab;if(a.mb!=b){a.mb=b;b=a.mb.toFixed(2)+"Mhz";var f=a.K.setSpeed;f&&(f.textContent=b);a.g("target speed: "+b)}c&&a.B&&a.B.Xb()}ad(a,a.$);a.$=0;a.W=pa();a.ca=0;bd(a);return d}function Ob(a,b){var c=a.S.length;a.S.push([-1,b]);return c}function Pb(a,b){var c;0<=b&&b<a.S.length&&0>a.S[b][0]&&(c=a.Da*a.ab/1E3*(1E3/60),a.S[b][0]=c)}
function cd(a,b){for(var c=a.S.length-1;0<=c;c--){var d=a.S[c];0>d[0]||b>d[0]&&(b=d[0])}return b}function dd(a,b){for(var c=a.S.length-1;0<=c;c--){var d=a.S[c];0>d[0]||(d[0]-=b,0>=d[0]&&(d[0]=-1,d[1]()))}}function ed(a){a.da-=a.b;a.b=0}
l.od=function(){if(this.u.ha){this.qb>=this.Da&&bd(this,!0);this.ua=0;this.Ca=pa();if(this.ca){var a=this.Ca-this.ca;a>this.Lb&&(this.W+=a,this.W>this.Ca&&(this.W=this.Ca))}try{do{var b=cd(this,this.u.rb?1:this.Ia);try{this.Bb(b)}catch(f){if("number"!=typeof f)throw f;}var c=this.da-this.b;dd(this,c);this.ua+=c;this.$+=c;ad(this,0,!0);Ec(this,c);this.la-=c;if(0>=this.la){this.la+=this.Ia;15<=++this.Zb&&(this.B&&this.B.Ha(),this.Zb=0);break}}while(this.u.ha)}catch(f){this.pa();L(this);this.B&&this.B.stop(pa(),
Yc(this));ub(this,f.stack||f.message);return}if(this.u.ha){a=setTimeout;b=this.$b;this.ca=pa();c=this.Lb;this.ua&&(c=Math.round(c*this.ua/this.Ia));var c=c-(this.ca-this.Ca),d=this.ca-this.W;d&&(this.ba=Math.round(this.$/(10*d))/100,864E5<=d&&(this.fa=0,$c(this)));if(0>c||this.ba<this.mb)-1E3>c&&(this.W-=c),c=0;this.qb+=this.ua;this.ca+=c;a(b,c)}}};
l.Ab=function(a){if(tb(this))return!1;if(this.u.ha)return this.g(this.toString()+" busy"),!1;$c(this);this.u.ha=!0;this.u.rc=!0;this.ta&&this.ta.start();var b=this.K.run;b&&(b.textContent="Halt");this.B&&(a&&this.B.Xb(!0),this.B.start(this.W,Yc(this)));L(this,!0);setTimeout(this.$b,0);return!0};l.Bb=function(){return 0};
l.pa=function(a){if(this.u.ha){ed(this);ad(this,this.$);this.$=0;this.u.ha=!1;this.ta&&this.ta.stop();var b=this.K.run;b&&(b.textContent="Run");this.B&&this.B.stop(pa(),Yc(this));L(this)}this.u.complete=a};function L(a,b){a.B&&a.B.Ha(b)}
function fd(a){this.Yc=+a.model||1170;this.lc=a.resetAddr||0;yc.call(this,a,6666667);this.Gb=0;this.decode=gd.bind(this);this.U=65536;this.V=32768;this.Y=65535;this.X=32768;this.P=15;this.i=[0,0,0,0,0,0,0,this.lc];this.Ra=[0,0,0,0,0,0];this.Aa=[0,0,0,0];this.Ba=this.D=0;this.na=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[65535,65535,65535,65535,65535,65535,65535,65535,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];this.Wb=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.kc=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.L=this.f=this.F=this.j=this.C=0;this.lb=70;this.ma=-1;hd(this);this.u.complete=this.u.Pc=!1}B(fd,yc);l=fd.prototype;l.reset=function(){this.u.ha&&this.pa();hd(this);Bc(this);this.u.error=!1;this.parent.reset.call(this)};
function hd(a){a.cb=255;a.J=0;a.pc=0;a.I=0;a.bb=0;a.fc=0;a.nb=0;a.bc=0;a.za=0;a.cc=[7,7,7,7];a.A=[];a.C|=2;Qb(a)}function Qb(a){a.bc?(a.Eb=65536,a.ea=a.Uc,a.Rb=a.La):(a.Eb=0,a.ea=a.Tc,a.Rb=a.ec)}l.Bc=function(){return 0};l.save=function(){var a=new M(this);a.set(0,[]);a.set(1,[this.fa,this.ab]);a.set(2,Jb(this.H));return a.data()};
l.restore=function(a){var b=a[1];this.fa=b[1];$c(this,b[3]);a:{b=this.H;a=a[2];var c;for(c=0;c<a.length-1;c+=2){var d=a[c],f=a[c+1];if(f&&f.length<b.L){for(var e=0,g=Array(b.L),h=0;h<f.length-1;)for(var k=f[h++],m=f[h++];k--;)g[e++]=m;f=g}e=b.O[d];if(!e||!e.restore(f)){v("Unable to restore memory block "+d);b=!1;break a}}b=!0}return b};
l.xa=function(a,b,c){switch(b){case "R0":case "R1":case "R2":case "R3":case "R4":case "R5":case "R6":case "R7":case "NF":case "ZF":case "VF":case "CF":case "PS":this.K[b]=c;this.Gb++;a=!0;break;default:a=this.parent.xa.call(this,a,b,c)}return a};
l.Ha=function(a){if(this.Gb&&(a||!this.u.ha||this.u.zc)){for(a=0;a<this.i.length;a++)Zc(this,"R"+a,this.i[a]);a=Zb(this);Zc(this,"PS",a);Zc(this,"NF",a&8?1:0,1);Zc(this,"ZF",a&4?1:0,1);Zc(this,"VF",a&2?1:0,1);Zc(this,"CF",a&1?1:0,1)}if(a=this.K.speed)a.textContent=this.u.ha&&this.ba?this.ba.toFixed(2)+"Mhz":"Stopped"};function N(a){return a.U&65536?1:0}function id(a){return a.V&32768?2:0}function jd(a){return a.Y&65535?0:4}l.Oa=function(){return this.X&32768?8:0};
function kd(a){var b=a.La(a.i[7]);a.i[7]=a.i[7]+2&65535;return b}function ld(a,b){a.i[7]=b&65535}function J(a,b,c,d,f){for(var e=a.A.length;0<e--;)if(a.A[e].qd===d){0<e&&(a.A[e-1].Wa+=a.A[e].Wa);a.A.splice(e,1);break}if(0<=b){for(e=a.A.length;0<e--;){if(a.A[e].Wa>b){a.A[e].Wa-=b;break}b-=a.A[e].Wa}a.A.splice(e+1,0,{delay:b,priority:c<<5&224,vector:d,callback:f})}a.C|=2}function Zb(a){return a.P=a.P&63728|a.Oa()|jd(a)|id(a)|N(a)}
function $b(a,b){a.X=b<<12;a.Y=~b&4;a.V=b<<14;a.U=b<<16;if((b^a.P)&2048)for(var c=a.Ra.length;0<=--c;){var d=a.i[c];a.i[c]=a.Ra[c];a.Ra[c]=d}a.D=b>>14&3;c=a.P>>14&3;a.D!=c&&(a.Aa[c]=a.i[6],a.i[6]=a.Aa[a.D]);a.C|=2;a.P=b}function O(a,b){a.C&128||(a.X=a.Y=b,a.V=0)}function md(a,b,c){a.C&128||(a.X=a.Y=a.U=b,a.V=c||0)}function nd(a,b,c,d){a.C&128||(a.X=a.Y=a.U=b,a.V=(c^b)&(d^b))}function od(a,b){a.C&128||(a.X=a.Y=a.U=b,a.V=a.X^a.U>>1)}function pd(a,b,c,d){a.C&128||(a.X=a.Y=a.U=b,a.V=(c^d)&(d^b))}
l.N=function(a){var b=!1;0>this.ma?this.ma=Zb(this):this.D||(a=4,b=!0);this.I&57344||(this.bb=63222,this.fc=a);this.D=0;var c=this.La(a|65536),d=this.La(a+2&65535|65536);$b(this,d&-12289|this.ma>>2&12288);b&&(this.J|=4,this.i[6]=4);qd(this,this.ma);qd(this,this.i[7]);ld(this,c);this.C&=-113;this.ma=-1;throw a;};function rd(a){var b=sd(a),c=sd(a)&-1793;a.P&49152&&(c=c&-225|a.P&63712);ld(a,b);$b(a,c);a.C&=-17}
function gc(a,b){var c=b>>13&31;31>c?a.nb&32&&(b=a.Wb[c]+(b&8190)&4194302,3932160<=b&&4186112>b&&console.log("panic(898)")):b|=4186112;return b}
function td(a,b,c){var d,f,e,g=0;if(c&a.bc){d=b>>13&a.cc[a.D];f=a.na[a.D][d];e=(a.na[a.D][d+16]<<6)+(b&8191)&4194303;a.nb&16?3932160<=e&&4186112>e&&(e=gc(a,e&262143)):(e&=262143,253952<=e&&(e|=4186112));3932160>e&&(3915776<=e&&(a.J|=32,a.N(4,12)),e&1&&!(c&1)&&(a.J|=64,a.N(4,14)));switch(f&7){case 1:g=4096;case 2:f|=128;c&4&&(g=8192);break;case 4:g=4096;case 5:c&4&&(g=4096);case 6:f|=c&4?192:128;break;default:g=32768}32512!==(f&32520)&&(f&8?f&32512&&(b&8128)<(f>>2&8128)&&(g|=16384):(b&8128)>(f>>2&
8128)&&(g|=16384));a.na[a.D][d]=f;if(4194170!==e||a.D)a.za=a.D,a.Ba=d;g&&(g&57344&&(0<=a.ma&&(g|=128),a.I&57344||(a.I=a.I|g|a.za<<5|a.Ba<<1),a.N(168,16)),a.I&61440||!(4191360>e||4194239<e)||(a.I|=4096,a.I&512&&(a.C|=32)))}else e=b&65535,57344<=e?e|=4186112:e&1&&!(c&1)&&(a.J|=64,a.N(4,10));return e}l.ec=function(a){return 4194304<=a?this.i[a-4194304]:0<=a?this.H.Ka(a):a};l.La=function(a){return this.ec(td(this,a,2))};function sd(a){var b=a.La(a.i[6]|65536);a.i[6]=a.i[6]+2&65535;return b}
function qd(a,b){var c=a.i[6]-2&65535;a.i[6]=c;a.I&57344||(a.bb=a.bb<<8|246);!a.D&&c<=a.cb&&4<c&&(c<=a.cb-32?(a.J|=4,a.i[6]=4,a.N(4,18)):(a.J|=8,a.C|=4));c=td(a,c|65536,4);a.H.pb(c,b&65535)}
function ud(a,b,c){var d,f,e=c&8?0:a.Eb,g=b>>3&7;b&=7;c&4?(a.j=g,a.f=b):(a.F=g,a.L=b);switch(g){case 0:return a.N(4,20),0;case 1:return 6===b&&!a.D&&c&4&&(a.i[6]<=a.cb||65534<=a.i[6])&&(a.i[6]<=a.cb-32||65534<=a.i[6]?(a.J|=4,a.i[6]=4,a.N(4,22)):(a.J|=8,a.C|=64)),a.b-=3,7===b?a.i[b]:a.i[b]|e;case 2:f=2;d=a.i[b];7!==b&&(d|=e,6>b&&c&1&&(f=1));a.b-=3;break;case 3:f=2;d=a.i[b];7!==b&&(d|=e);d=a.La(d);d|=e;a.b-=7;break;case 4:f=-2;6>b&&c&1&&(f=-1);d=a.i[b]+f&65535;7!==b&&(d|=e);a.b-=4;break;case 5:f=-2;
d=a.i[b]-2&65535;7!==b&&(d|=e);d=a.La(d)|e;a.b-=8;break;case 6:return d=kd(a),d=d+a.i[b]&65535|e,a.b-=6,d;case 7:return d=kd(a),d=d+a.i[b]&65535,d=a.La(d|65536)|e,a.b-=10,d}a.i[b]=a.i[b]+f&65535;!e||a.I&57344||(a.bb=a.bb<<8|f<<3&248|b);6==b&&!a.D&&c&4&&0>=f&&(a.i[6]<=a.cb||65534<=a.i[6])&&(a.i[6]<=a.cb-32?(a.J|=4,a.i[6]=4,a.N(4,24)):(a.J|=8,a.C|=64));return d}l.Tc=function(a,b){return ud(this,a,b)};l.Uc=function(a,b){return td(this,ud(this,a,b),b)};
function vd(a,b,c){b&56?(b=ud(a,b,2),c&65536||61440!==(a.P&61440)&&(b&=65535),a.D=a.P>>12&3,c=a.La(b|c&65536),a.D=a.P>>14&3):(a.F=0,c=b&7,c=6!=c||(a.P>>2&12288)===(a.P&12288)?a.i[c]:a.Aa[a.P>>12&3]);return c}function wd(a,b,c,d){a.I&57344||(a.bb=22);b&56?(b=ud(a,b,4),c&65536||(b&=65535),a.D=a.P>>12&3,b=td(a,b|c&65536,4),a.D=a.P>>14&3,a.H.pb(b,d&65535)):(a.j=0,c=b&7,6!=c||(a.P>>2&12288)===(a.P&12288)?a.i[c]=d:a.Aa[a.P>>12&3]=d)}function P(a,b){b&56?a=a.Rb(ud(a,b,2)):(a.F=0,a=a.i[b&7]);return a}
function xd(a,b){b&56?(b=a.ea(b,3),a=a.H.sb(b)):(a.F=0,a=a.i[b&7]&255);return a}function R(a,b,c,d){b&56?(b=a.ea(b,6),c=d.call(a,c,a.ec(b)),a.H.pb(b,c&65535)):(a.j=0,b&=7,a.i[b]=d.call(a,c,a.i[b]))}function S(a,b,c,d){b&56?(b=a.ea(b,7),c=d.call(a,c,a.H.sb(b)),b&1&&a.b--,a.H.Vb(b,c&255)):(a.j=0,b&=7,a.i[b]=a.i[b]&65280|d.call(a,c,a.i[b]))}function yd(a,b,c){b&56?(b=a.ea(b,4),a.H.pb(b,c&65535)):(a.j=0,a.i[b&7]=c&65535);return c}
function zd(a,b,c,d){b&56?(d=a.ea(b,5),d&1&&a.b--,a.H.Vb(d,c&255)):(a.j=0,b&=7,a.i[b]=c?d&1?c<<24>>24&65535:a.i[b]&-256|c&255:a.i[b]&-256);return c}function T(a,b){ld(a,a.i[7]+(b<<24>>23))}
l.Bb=function(a){this.u.complete=!0;var b=this.u.Pc=this.G&&Ad(this.G),c=a?this.u.rc?0:1:-1;this.u.rc=!1;this.da=this.b=a;do{if(b){if(Bd(this.G,this.i[7],c)){this.pa();break}c=1}if(this.C&&(this.C&112&&(this.C&32?this.N(168,28):this.C&64?this.N(4,30):this.C&16&&this.N(12,32),this.C&=-113),this.C&7))if(this.C&2){this.C&=-3;a=null;for(var d=this.pc&224,f=this.A.length;0<=--f;){if(0<this.A[f].Wa){this.A[f].Wa--;this.C|=2;break}if(this.A[f].xc){if(!this.A[f].xc()){this.A.splice(f,1);continue}this.A[f].xc=
null}this.A[f].Zc>d&&(d=this.A[f].Zc,a=this.A[f],this.A.splice(f,1))}d>(this.P&224)&&(this.C&4&&(this.i[7]=this.i[7]+2&65535,this.C&=-5),a?this.N(a.qd,26):this.N(160,26))}else this.C&1&&this.C++;this.I&57344||(this.bb=0,this.fc=this.i[7]);this.C=this.C&7|this.P&16;this.decode(kd(this))}while(0<this.b);return this.u.complete?this.da-this.b:void 0===this.u.complete?0:-1};Pa(function(){for(var a=D(document,"pdp11","cpu"),b=0;b<a.length;b++){var c=a[b],d=C(c),d=new fd(d);cb(d,c)}});
function Cd(a,b){var c=b+a;nd(this,c,a,b);return c&65535}function Dd(a,b){var c=b+a;nd(this,c<<8,a<<8,b<<8);return c&255}function Ed(a,b){a=b<<1;od(this,a);return a&65535}function Fd(a,b){a=b<<1;od(this,a<<8);return a&255}function Gd(a,b){a=b&32768|b>>1|b<<16;od(this,a);return a&65535}function Hd(a,b){a=b&2048|b>>1|b<<8;od(this,a<<8);return a&255}function Id(a,b){a=b&~a;O(this,a);return a}function Jd(a,b){a=b&~a;O(this,a<<8);return a}function Kd(a,b){a|=b;O(this,a);return a}
function Ld(a,b){a|=b;O(this,a<<8);return a}function Md(a,b){a=~b|65536;md(this,a);return a&65535}function Nd(a,b){a=~b|256;md(this,a<<8);return a&255}function Od(a,b){a=b-a;this.C&128||(this.X=this.Y=a,this.V=b&(b^a));return a&65535}function Pd(a,b){a=b-a;var c=a<<8;b<<=8;this.C&128||(this.X=this.Y=c,this.V=b&(b^c));return a&255}function Qd(a,b){a=b+a;this.C&128||(this.X=this.Y=a,this.V=a&(b^a));return a&65535}
function Rd(a,b){a=b+a;var c=a<<8;this.C&128||(this.X=this.Y=c,this.V=c&(b<<8^c));return a&255}function Sd(a,b){a=-b;md(this,a,a&b&32768);return a&65535}function Td(a,b){a=-b;md(this,a<<8,(a&b&128)<<8);return a&255}function Ud(a,b){a=b<<1|this.U>>16&1;od(this,a);return a&65535}function Vd(a,b){a=b<<1|this.U>>16&1;od(this,a<<8);return a&255}function Wd(a,b){a=(this.U&65536|b)>>1|b<<16;od(this,a);return a&65535}function Xd(a,b){a=((this.U&65536)>>8|b)>>1|b<<8;od(this,a<<8);return a&255}
function Yd(a,b){var c=b-a;pd(this,c,a,b);return c&65535}function Zd(a,b){var c=b-a;pd(this,c<<8,a<<8,b<<8);return c&255}function $d(a,b){this.C&128||(this.X=this.Y=b&65280,this.V=this.U=0);return(b<<8|b>>8)&65535}function ae(a,b){a^=b;O(this,a);return a&65535}
function be(a){var b=P(this,a);a=a>>6&7;var c=this.i[a];c&32768&&(c|=4294901760);this.U=this.V=0;b&=63;b&32?(b=64-b,16<b&&(b=16),this.U=c<<17-b,c>>=b):b&&(16<b?(this.V=c,c=0):(this.U=c<<=b,(b=c>>15&65535)&&65535!==b&&(this.V=32768)));this.i[a]=c&65535;this.X=this.Y=c;--this.b}
function ce(a){var b=P(this,a);a=a>>6&7;var c=this.i[a]<<16|this.i[a|1];this.U=this.V=0;b&=63;if(b&32){b=64-b;32<b&&(b=32);var d=c>>b-1;this.U=d<<16;d>>=1;c&2147483648&&(d|=4294967295<<32-b)}else b?(d=c<<b-1,this.U=d>>15,d<<=1,32<b&&(b=32),(c>>=32-b)&&4294967295!==(c|4294967295<<b&4294967295)&&(this.V=32768)):d=c;this.i[a]=d>>16&65535;this.i[a|1]=d&65535;this.X=d>>16;this.Y=d>>16|d;--this.b}function U(a){a&1&&(this.U=0);a&2&&(this.V=0);a&4&&(this.Y=1);a&8&&(this.X=0);--this.b}
function de(a){var b=P(this,a);if(b){a=a>>6&7;var c=this.i[a]<<16|this.i[a|1];this.U=this.V=0;b&32768&&(b|=-65536);var d=~~(c/b);-32768<=d&&32767>=d?(this.i[a]=d&65535,this.i[a|1]=c-d*b&65535,this.Y=d>>16|d,this.X=d>>16):(this.V=32768,this.Y=d>>15|d,this.X=c>>16,-1===b&&65534===this.i[a]&&(this.i[a]=this.i[a|1]=1))}else this.Y=this.X=0,this.V=32768,this.U=65536;--this.b}function ee(a){ld(this,ud(this,a,8));--this.b}
function fe(a){var b=ud(this,a,8);a=a>>6&7;qd(this,this.i[a]);this.i[a]=this.i[7];ld(this,b);--this.b}var ge=[3,9,9,13,10,14,12,16,4,9,9,13,10,14,13,17];function he(a){var b=P(this,a);a=a>>6&7;b&32768&&(b|=-65536);var c=this.i[a];c&32768&&(c|=-65536);b=~~(b*c);this.i[a]=b>>16&65535;this.i[a|1]=b&65535;this.C&128||(this.X=b>>16,this.Y=this.X|b,this.V=0,this.U=-32768>b||32767<b?65536:0);--this.b}function Ce(){--this.b}
function W(a){a&1&&(this.U=65536);a&2&&(this.V=32768);a&4&&(this.Y=0);a&8&&(this.X=32768);--this.b}function De(a){var b=(a&448)>>6;(this.i[b]=this.i[b]-1&65535)&&ld(this,this.i[7]-((a&63)<<1));--this.b}function Ee(a){R(this,a,0,$d);this.b-=this.j?9:3+(7==this.f?2:0)}function Fe(a){R(this,a,P(this,(a&448)>>6),ae);this.b-=this.j?9:3+(7==this.f?2:0)}function X(){this.N(8,6)}function gd(a){Ge[a>>12].call(this,a)}
var Ge=[function(a){He[a>>8&15].call(this,a)},function(a){O(this,yd(this,a,P(this,a>>6)));this.b-=ge[(this.F?8:0)+this.j]+(7!=this.f||this.j?0:2)},function(a){var b=P(this,a>>6);a=P(this,a);pd(this,b-a,a,b);this.b-=this.j?4+(this.L&&6<=this.f?1:0):(this.F?4:3)+(7==this.f?2:0)},function(a){O(this,P(this,a>>6)&P(this,a));this.b-=this.j?4+(this.L&&6<=this.f?1:0):(this.F?4:3)+(7==this.f?2:0)},function(a){R(this,a,P(this,a>>6),Id);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:0)},
function(a){R(this,a,P(this,a>>6),Kd);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:0)},function(a){R(this,a,P(this,a>>6),Cd);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:0)},function(a){Ie[a>>8&15].call(this,a)},function(a){Je[a>>8&15].call(this,a)},function(a){var b=xd(this,a>>6);O(this,zd(this,a,b,1)<<8);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:0)},function(a){var b=xd(this,a>>6)<<8;a=xd(this,a)<<8;pd(this,b-a,a,b);this.b-=this.j?
4+(this.L&&6<=this.f?1:0):(this.F?4:3)+(7==this.f?2:0)},function(a){O(this,(xd(this,a>>6)&xd(this,a))<<8);this.b-=this.j?4+(this.L&&6<=this.f?1:0):(this.F?4:3)+(7==this.f?2:0)},function(a){S(this,a,xd(this,a>>6),Jd);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:0)},function(a){S(this,a,xd(this,a>>6),Ld);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:0)},function(a){R(this,a,P(this,a>>6),Yd);this.b-=this.j?9+(this.L&&6<=this.f?1:0):(this.F?5:3)+(7==this.f?2:
0)},X],He=[function(a){Ke[a>>4&15].call(this,a)},function(a){T(this,a);--this.b},function(a){jd(this)||T(this,a);--this.b},function(a){jd(this)&&T(this,a);--this.b},function(a){!this.Oa()==!id(this)&&T(this,a);--this.b},function(a){!this.Oa()!=!id(this)&&T(this,a);--this.b},function(a){jd(this)||!this.Oa()!=!id(this)||T(this,a);--this.b},function(a){(jd(this)||!this.Oa()!=!id(this))&&T(this,a);--this.b},fe,fe,function(a){Le[a>>6&3].call(this,a)},function(a){Me[a>>6&3].call(this,a)},function(a){Ne[a>>
6&3].call(this,a)},function(a){Oe[a>>6&3].call(this,a)},X,X],Le=[function(a){md(this,yd(this,a,0));this.b-=this.j?9:3+(7==this.f?2:0)},function(a){R(this,a,0,Md);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){R(this,a,1,Qd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){R(this,a,1,Od);this.b-=this.j?9:3+(7==this.f?2:0)}],Me=[function(a){R(this,a,0,Sd);--this.b},function(a){R(this,a,N(this)?1:0,Cd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){R(this,a,N(this)?1:0,Yd);this.b-=this.j?9:3+(7==this.f?
2:0)},function(a){a=P(this,a);md(this,a);--this.b}],Ne=[function(a){R(this,a,0,Wd);--this.b},function(a){R(this,a,0,Ud);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){R(this,a,0,Gd);--this.b},function(a){R(this,a,0,Ed);this.b-=this.j?9:3+(7==this.f?2:0)}],Oe=[function(a){a=this.i[7]+((a&63)<<1)&65535;var b=this.La(a|65536);ld(this,this.i[5]);this.i[6]=a+2&65535;this.i[5]=b;--this.b},function(a){a=vd(this,a,0);qd(this,a);O(this,a);--this.b},function(a){var b=sd(this);wd(this,a,0,b);O(this,b);--this.b},
function(a){O(this,yd(this,a,this.Oa?65535:0));this.b-=this.j?9:3+(7==this.f?2:0)}],Ke=[function(a){Pe[a&15].call(this,a)},X,X,X,ee,ee,ee,ee,function(a){var b=sd(this);a&=7;ld(this,this.i[a]);this.i[a]=b;--this.b},function(a){this.P&49152||(this.P=this.P&-2017|(a&7)<<5,this.C|=1);--this.b},function(a){Qe[a&15].call(this,a)},function(a){Re[a&15].call(this,a)},Ee,Ee,Ee,Ee],Qe=[Ce,function(){this.U=0;--this.b},function(){this.V=0;--this.b},U,function(){this.Y=1;--this.b},U,U,U,function(){this.X=0;--this.b},
U,U,U,U,U,U,U],Re=[Ce,function(){this.U=65536;--this.b},function(){this.V=32768;--this.b},W,function(){this.Y=0;--this.b},W,W,W,function(){this.X=32768;--this.b},W,W,W,W,W,W,W],Pe=[function(){this.P&49152?(this.J|=128,this.N(4,3)):ed(this);--this.b},function(){this.C|=4;this.i[7]=this.i[7]+-2&65535;--this.b},function(){rd(this);this.C|=this.P&16;--this.b},function(){this.N(12,1);--this.b},function(){this.N(16,4);--this.b},function(){this.P&49152||(hd(this),this.H.reset());--this.b},function(){rd(this);
--this.b},X,X,X,X,X,X,X,X,X],Ie=[he,he,de,de,be,be,ce,ce,Fe,Fe,X,X,X,X,De,De],Je=[function(a){this.Oa()||T(this,a);--this.b},function(a){this.Oa()&&T(this,a);--this.b},function(a){N(this)||jd(this)||T(this,a);--this.b},function(a){(N(this)||jd(this))&&T(this,a);--this.b},function(a){id(this)||T(this,a);--this.b},function(a){id(this)&&T(this,a);--this.b},function(a){N(this)||T(this,a);--this.b},function(a){N(this)&&T(this,a);--this.b},function(){this.N(24,2);--this.b},function(){this.N(28,5);--this.b},
function(a){Se[a>>6&3].call(this,a)},function(a){Te[a>>6&3].call(this,a)},function(a){Ue[a>>6&3].call(this,a)},function(a){Ve[a>>6&3].call(this,a)},X,X],Se=[function(a){md(this,zd(this,a,0));this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,0,Nd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,1,Rd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,1,Pd);this.b-=this.j?9:3+(7==this.f?2:0)}],Te=[function(a){S(this,a,0,Td);--this.b},function(a){S(this,a,N(this)?1:0,Dd);this.b-=
this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,N(this)?1:0,Zd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){a=xd(this,a);md(this,a<<8);--this.b}],Ue=[function(a){S(this,a,0,Xd);--this.b},function(a){S(this,a,0,Vd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,0,Hd);--this.b},function(a){S(this,a,0,Fd);this.b-=this.j?9:3+(7==this.f?2:0)}],Ve=[X,function(a){a=vd(this,a,65536);qd(this,a);O(this,a);--this.b},function(a){var b=sd(this);wd(this,a,65536,b);O(this,b);--this.b},X];
function We(a){w.call(this,"ROM",a,We);this.f=null;this.D=a.addr;this.j=a.size;this.F=a.writable;this.B=a.alias;this.A=a.file;this.I=ca(this.A);if(this.A){a=this.A;var b=da(this.I);"json"!=b&&"hex"!=b&&(a=ja()+"/api/v1/dump?file="+this.A+"&format=bytes&decimal=true");var c=this;ra(a,null,!0,function(a,b,e){Xe(c,a,b,e)})}}B(We);We.prototype.Ya=function(a,b,c,d){this.H=b;this.b=c;this.G=d;Ye(this)};
We.prototype.Qa=function(){if(this.Ma){if(this.G){var a=this.G,b=this.id,c=this.D,d=this.j,f=this.Ma,e=[],g;for(g in f){var h=f[g];"number"==typeof h&&(f[g]=h={o:h});var k=h.o,m=h.a;if(void 0!==k){var n=e,k=[k>>>0,g],p=oa(n,k,a.yc);0>p&&n.splice(-(p+1),0,k)}m&&(h.a=m.replace(/''/g,'"'))}a.F.push({xd:b,w:c,Vc:d,Ma:f,uc:e})}delete this.Ma}return!0};We.prototype.Pa=function(){return!0};
function Xe(a,b,c,d){if(d)a.ra("Unable to load system ROM (error "+d+": "+b+")");else{$a(a.wc,b,c);var f;if("["==c.charAt(0)||"{"==c.charAt(0))try{var e,g,h=eval("("+c+")");if(e=h.bytes)a.f=e;else if(e=h.words)for(a.f=Array(2*e.length),g=f=0;f<e.length;f++)a.f[g++]=e[f]&255,a.f[g++]=e[f]>>8&255;else if(e=h.data)for(a.f=Array(4*e.length),g=f=0;f<e.length;f++)a.f[g++]=e[f]&255,a.f[g++]=e[f]>>8&255,a.f[g++]=e[f]>>16&255,a.f[g++]=e[f]>>24&255;else a.f=h;a.Ma=h.symbols;if(!a.f.length){v("Empty ROM: "+
b);return}if(1==a.f.length){v(a.f[0]);return}}catch(k){a.ra("ROM data error: "+k.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.f=Array(b.length),f=0;f<b.length;f++)a.f[f]=ba(b[f],16);Ye(a)}}
function Ye(a){if(!gb(a))if(!a.A)F(a);else if(a.f&&a.H){a.j||(a.j=a.f.length);if(a.f.length!=a.j)ub(a,"ROM size ("+t(a.f.length,8,!0)+") does not match specified size ("+t(a.j,8,!0)+")");else{var b;b=a.D;if(Eb(a.H,b,a.j,a.F?1:nc)){var c;for(c=0;c<a.f.length;c++){var d=a.H,f=b+c;d.O[(f&d.j)>>>d.Z].Db(f&d.f,a.f[c]&255,f)}b=!0}else b=!1;if(b){b=[];"number"==typeof a.B?b.push(a.B):null!=a.B&&a.B.length&&(b=a.B);for(c=0;c<b.length;c++){for(var e=a,d=b[c],f=e.H,g=e.j,h=[],k=e.D>>>f.Z;0<g&&k<f.O.length;)h.push(f.O[k++]),
g-=f.Ea;f=e.H;e=e.j;g=0;for(d>>>=f.Z;0<e&&d<f.O.length;){k=h[g++];if(!k)break;f.O[d++]=k;e-=f.Ea}}delete a.f}}F(a)}}Pa(function(){for(var a=D(document,"pdp11","rom"),b=0;b<a.length;b++){var c=a[b],d=C(c),d=new We(d);cb(d,c)}});function Ze(a){w.call(this,"RAM",a,Ze);this.B=a.addr;this.j=a.size;this.f=!1}B(Ze);l=Ze.prototype;l.Ya=function(a,b,c,d){this.H=b;this.b=c;this.G=d;F(this)};l.Qa=function(a,b){b||this.reset();return!0};l.Pa=function(a){return a?this.save():!0};
l.reset=function(){!this.f&&this.j&&Eb(this.H,this.B,this.j,1)&&(this.f=!0);this.f||v("No RAM allocated")};l.save=function(){return null};l.restore=function(){return!0};Pa(function(){for(var a=D(document,"pdp11","ram"),b=0;b<a.length;b++){var c=a[b],d=C(c),d=new Ze(d);cb(d,c)}});function $e(a){w.call(this,"Keyboard",a,$e,65536);F(this)}B($e);$e.prototype.xa=function(){return!1};$e.prototype.Ya=function(a,b,c,d){this.B=a;this.b=c;this.G=d;this.ta=null};
Pa(function(){for(var a=D(document,"pdp11","keyboard"),b=0;b<a.length;b++){var c=a[b],d=C(c),d=new $e(d);cb(d,c)}});function af(a){w.call(this,"Debugger",a,af);this.da=a.base||16;this.Da=!1;this.$=this.Ca=this.I=0;this.ca=!1;this.A=-1;this.j=[];this.ia={}}B(af);var bf={"||":0,"&&":1,"|":2,"^":3,"&":4,"!=":5,"==":5,">=":6,">":6,"<=":6,"<":6,">>>":7,">>":7,"<<":7,"-":8,"+":8,"%":9,"/":9,"*":9};af.prototype.Cc=function(){return-1};af.prototype.Dc=function(){};
function cf(a,b,c,d){if(c)if(b){0>a.A&&a.j.length&&(a.A=0);if(0>a.A||b!=a.j[a.A])a.j.splice(0,0,b),a.A=0;a.A--}else a.ca?b="end":b=a.j[a.A+1];a=[];if(b){b=b.toLowerCase().replace(/""/g,"'");c=0;var f=null;d=d||";";for(var e=0;e<=b.length;e++){var g=b.charAt(e);if('"'==g||"'"==g)f?g==f&&(f=null):f=g;else if(g==d&&!f||!g)a.push(na(b.substring(c,e))),c=e+1}}return a}
function df(a,b,c){for(c=c||-1;c--&&b.length;){var d=b.pop();if(2>a.length)return!1;var f=a.pop(),e=a.pop();switch(d){case "*":d=e*f;break;case "/":if(!f)return!1;d=e/f;break;case "%":if(!f)return!1;d=e%f;break;case "+":d=e+f;break;case "-":d=e-f;break;case "<<":d=e<<f;break;case ">>":d=e>>f;break;case ">>>":d=e>>>f;break;case "<":d=e<f?1:0;break;case "<=":d=e<=f?1:0;break;case ">":d=e>f?1:0;break;case ">=":d=e>=f?1:0;break;case "==":d=e==f?1:0;break;case "!=":d=e!=f?1:0;break;case "&":d=e&f;break;
case "^":d=e^f;break;case "|":d=e|f;break;case "&&":d=e&&f?1:0;break;case "||":d=e||f?1:0;break;default:return!1}a.push(d|0)}return!0}
function ef(a,b,c){var d;if(b){b=ff(a,b);for(var f=0,e=!1,g=b,h=[],k=[],m=b.split(/(\|\||&&|\||^|&|!=|==|>=|>>>|>>|>|<=|<<|<|-|\+|%|\/|\*)/);f<m.length;){var n=m[f++],p=n.length,n=na(n);if(!n){e=!0;break}n=gf(a,n,null,!1===c);if(void 0===n){e=!0;c=!1;break}h.push(n);if(f==m.length)break;var n=m[f++],q=n.length;k.length&&bf[n]<bf[k[k.length-1]]&&df(h,k,1);k.push(n);b=b.substr(p+q)}df(h,k)&&1==h.length||(e=!0);e?c&&a.g("error parsing '"+g+"' at character "+(g.length-b.length)):(d=h.pop(),c&&hf(a,null,
d))}return d}function ff(a,b){for(var c,d=a.Da?"(":"{",f=a.Da?")":"}",e=new RegExp(a.Da?"\\((.*?)\\)":"\\{(.*?)\\}");(c=b.match(e))&&!(0<=c[1].indexOf(d));){var g=ef(a,c[1]);b=b.replace(d+c[1]+f,null!=g?Y(a,g):"undefined")}for(;(c=b.match(/\[(.*?)]/))&&!(0<=c[1].indexOf("["));)b=b.replace("["+c[1]+"]","unimplemented");for(;c=b.match(/\$([a-z]+)/i);){d=null;switch(c[1].toLowerCase()){case "ops":d=a.$-a.Ca}if(null==d)break;b=b.replace(c[0],d.toString())}return b}
function gf(a,b,c,d){var f;null!=b?(f=a.Cc(b),0<=f?f=a.Dc(f):(f=a.ia[b],null==f&&(f=ba(b,a.da))),null!=f||d||a.g("invalid "+(c?c:"value")+": "+b)):d||a.g("missing "+(c||"value"));return f}
function hf(a,b,c){var d,f=!1;if(void 0!==c){f=!0;d=c;var e=0,g="";if(!e||4<e)e=4;for(var h=0;h<e;h++){g&&(g=","+g);var k=d&255,m=8,n="";m?32<m&&(m=32):m=32;if(null==k||isNaN(k))for(;0<m--;)n="?"+n;else for(;0<m--;)n=(k&1?"1":"0")+n,k>>=1;g=n+g;d>>=8}d=t(c,0,!0)+" "+c+". "+r(c,0,!0)+" "+("0b"+g)}a.g((null!=b?b+": ":"")+d);return f}function jf(a,b){if(b)return hf(a,b,a.ia[b]);var c=0;for(b in a.ia)hf(a,b,a.ia[b]),c++;return 0<c}
function Y(a,b,c,d){switch(a.da){case 8:a=r(b,3*c);break;case 10:a=b.toString();break;default:a=t(b,2*c)}d&&"0"==a.charAt(0)&&(a=a.replace(/^0+([0-9A-F]+)$/i,"$1"));return a}
function kf(a){af.call(this,a);this.Da=!0;this.S=Z();this.qb=Z();this.ba=Z();this.F=[];this.f=this.W=this.D=[];lf(this);this.ua=0;mf(this);this.Ia={};nf(this,a.messages);this.ib=a.commands;var b=this;window?void 0===window.pdp11&&(window.pdp11=function(a){return Dc(b,a)}):void 0===global.pdp11&&(global.pdp11=function(a){return Dc(b,a)})}B(kf,af);
var of={"?":"help/print","a [#]":"assemble","b [#]":"breakpoint",c:"clear output","d [#]":"dump memory","e [#]":"edit memory","g [#]":"go [to #]",h:"halt","if":"eval expression","int [#]":"request interrupt",k:"stack trace",ln:"list nearest symbol(s)",m:"messages",p:"step over",print:"print expression",r:"dump/set registers",reset:"reset machine",s:"set options","t [#]":"trace","u [#]":"unassemble",v:"print version","var":"assign variable"},pf="NONE ADC ADCB ADD ASL ASLB ASR ASRB BCC BCS BEQ BGE BGT BHI BIC BICB BIS BISB BIT BITB BLE BLOS BLT BMI BNE BPL BPT BR BVC BVS CCC CLC CLCN CLCV CLCVN CLCVZ CLCZ CLCZN CLN CLR CLRB CLV CLVN CLVZ CLVZN CLZ CLZN CMP CMPB COM COMB DEC DECB INC INCB HALT JMP JSR MARK MFPD MFPI MFPS MOV MOVB MTPD MTPI MTPS NEG NEGB NOP RESET ROL ROLB ROR RORB RTI RTS SBC SBCB SCC SEC SECN SECV SECVN SECVZ SECZ SECZN SEN SEV SEVN SEVZ SEVZN SEZ SEZN SUB SWAB SXT TST TSTB WAIT MUL DIV ASH ASHC XOR SOB EMT TRAP SPL IOT RTT MFPT".split(" "),
qf={61440:{4096:[62,4032,63],8192:[47,4032,63],12288:[18,4032,63],16384:[14,4032,63],20480:[16,4032,63],24576:[3,4032,63],36864:[63,4032,63],40960:[48,4032,63],45056:[19,4032,63],49152:[15,4032,63],53248:[17,4032,63],57344:[94,4032,63]},65024:{2048:[57,448,63],28672:[100,63,448],29184:[101,63,448],29696:[102,63,448],30208:[103,63,448],30720:[104,448,63],32256:[105,448,8192]},65280:{256:[27,4096],512:[24,4096],768:[10,4096],1024:[11,4096],1280:[22,4096],1536:[12,4096],1792:[20,4096],32768:[25,4096],
33024:[23,4096],33280:[13,4096],33536:[21,4096],33792:[28,4096],34048:[29,4096],34304:[8,4096],34560:[9,4096],34816:[106],35072:[107]},65472:{64:[56,63],192:[95,63],2560:[39,63],2624:[49,63],2688:[53,63],2752:[51,63],2816:[67,63],2880:[1,63],2944:[77,63],3008:[97,63],3072:[73,63],3136:[71,63],3200:[6,63],3264:[4,63],3328:[58,24576],3392:[60,63],3456:[65,63],3520:[96,63],35328:[40,63],35392:[50,63],35456:[54,63],35520:[52,63],35584:[68,63],35648:[2,63],35712:[78,63],35776:[98,63],35840:[74,63],35904:[72,
63],35968:[7,63],36032:[5,63],36096:[66,63],36160:[59,63],36224:[64,63],36288:[61,63]},65528:{128:[76,7],152:[108,12288]},65535:{0:[55],1:[99],2:[75],3:[26],4:[109],5:[70],6:[110],7:[111],160:[69],161:[31],162:[41],163:[33],164:[45],165:[36],166:[43],167:[35],168:[38],169:[32],170:[42],171:[34],172:[46],173:[37],174:[44],175:[30],176:[69],177:[80],178:[88],179:[82],180:[92],181:[85],182:[90],183:[84],184:[87],185:[81],186:[89],187:[83],188:[93],189:[86],190:[91],191:[79]}};l=kf.prototype;
l.Ya=function(a,b,c,d){this.H=b;this.b=c;this.B=a;(a=Ac(a,"messages"))&&nf(this,a);this.Lb=qf;rf(this,function(a){a:{var b=d.H.O,c=a[0],f=a=0,k=b.length;if(c){a=d.ea(sf(d,c));if(-1===a){d.g("invalid address: "+c);break a}f=a>>>d.H.Z;k=1}d.g("blockid   physical   blockaddr   used    size    type");d.g("--------  ---------  ----------  ------  ------  ----");for(var c=-1,m=0;k--;){var n=b[f];n.type==c?m++||d.g("..."):(c=n.type,m=Hb[c],n&&d.g(t(n.id,8)+"  %"+t(f<<d.H.Z,8)+"  %%"+t(n.w,8)+"  "+t(n.Yb,
4,!0)+"  "+t(n.size,4,!0)+"  "+m),c!=mc&&(c=-1),m=0);a+=d.H.Ea;f++}}});F(this)};
l.xa=function(a,b,c){var d=this;switch(b){case "debugInput":return this.ta=this.K[b]=c,c.onkeydown=function(a){var b;if(13==a.keyCode)b=c.value,c.value="",Dc(d,b,!0);else if(27==a.keyCode)c.value=b="";else if(38==a.keyCode?(b=null,d.A<d.j.length-1&&(b=d.j[++d.A])):40==a.keyCode&&(0<d.A?b=d.j[--d.A]:(b="",d.A=-1)),null!=b){var f=b.length;c.value=b;c.setSelectionRange(f,f)}null!=b&&a.preventDefault&&a.preventDefault()},!0;case "debugEnter":return this.K[b]=c,Da(c,function(){if(d.ta){var a=d.ta.value;
d.ta.value="";Dc(d,a,!0);return!0}return!1}),!0;case "step":return this.K[b]=c,Da(c,function(a){var b=!1;fb(d,!0)||(eb(d,!0),b=d.Bb(a?1:0),eb(d,!1));return b}),!0}return!1};l.Xb=function(){this.ta&&this.ta.focus()};l.ea=function(a){a=a&&a.w;null==a&&(a=-1);return a};l.sb=function(a,b){var c=255,d=this.ea(a,!1,1);-1!==d&&(c=this.H,c=c.O[(d&c.j)>>>c.Z].Qb(d&c.f,d),b&&tf(a,b));return c};l.Ka=function(a,b){var c=65535,d=this.ea(a,!1,2);-1!==d&&(c=Ib(this.H,d),b&&tf(a,b));return c};
l.Vb=function(a,b,c){var d=this.ea(a,!0,1);if(-1!==d){var f=this.H;f.O[(d&f.j)>>>f.Z].Db(d&f.f,b&255,d);c&&tf(a,c);L(this.b,!0)}};l.pb=function(a,b,c){var d=this.ea(a,!0,2);if(-1!==d){var f=this.H,e=d&f.f,g=(d&f.j)>>>f.Z;e!=f.f?f.O[g].tc(e,b&65535,d):(f.O[g++].Db(e,b&255,d),f.O[g&f.B].Db(0,b>>8&255,d+1));c&&tf(a,c);L(this.b,!0)}};function Z(a){return{w:a,Ja:!1}}function uf(a){return[a.w,a.Ja]}function vf(a){return{w:a[0],Ja:a[1]}}
function sf(a,b,c){var d;c=(c?a.S:a.qb).w;if(void 0!==b){d=b=ff(a,b);var f;if(d.match(/^[a-z_][a-z0-9_]*$/i))for(d=d.toUpperCase(),c=0;c<a.F.length;c++){var e=a.F[c].Ma[d];if(void 0!==e){d=e.o;void 0!==d&&(f=Z(d));break}}if(d=f)return d;c=ef(a,b,void 0)}null!=c&&(d=Z(c));return d}function wf(a,b,c){c&&(c=c.match(/(['"])(.*?)\1/))&&(b.Nc=cf(a,b.Ic=c[2]))}function tf(a,b){null!=a.w&&(a.w+=b||1)}
function nf(a,b){a.G=a;a.ka=a.Oc=536870912;a.za=null;a.Ba=[];b=cf(a,b.replace("keys","key").replace("kbd","keyboard"),!1,"|");if(b.length)for(var c in G){var d;a:if(d=void 0,Array.prototype.indexOf)d=b.indexOf(c,d);else{d=d||0;0>d&&(d+=b.length);0>d&&(d=0);for(var f=b.length;d<f;d++)if(d in b&&b[d]===c)break a;d=-1}0<=d&&(a.ka|=G[c],a.g(c+" messages enabled"))}}function rf(a,b){for(var c in G)if(64==G[c]){a.Ia[c]=b;break}}
l.Cc=function(a){var b=-1;a=a.toUpperCase();switch(a){case "SP":b=6;break;case "PC":b=7;break;default:"R"==a.charAt(0)&&(b=+a.charAt(1),0>b||7<b)&&(b=-1)}return b};function xf(a){return 6>a?"R"+a:6==a?"SP":"PC"}l.Dc=function(a){var b;0<=a&&(8>a?b=this.b.i[a]:16>a?b=this.b.Ra[a-8]:20>a?b=this.b.Aa[a-16]:20==a&&(b=Zb(this.b)));return b};
l.message=function(a,b){b&&(a+=" at "+Y(this,Z(this.b.i[7]).w));this.ka&1073741824?this.Ba.push(a):this.za&&a==this.za||(this.za=a,this.ka&-2147483648&&(this.pa(),a+=" (cpu halted)"),this.g(a),this.b&&(a=this.b,ed(a),a.la=0,L(a)))};
function mf(a){var b;if(Ad(a)){if(!a.L||!a.L.length){a.L=Array(1E3);for(b=0;b<a.L.length;b++)a.L[b]=Z();a.ma=0;a.g("instruction history buffer allocated")}if(!a.la||!a.la.length)for(a.la=Array(256),b=0;b<a.la.length;b++)a.la[b]=[b,0]}else a.L&&a.L.length&&a.g("instruction history buffer freed"),a.ma=0,a.L=[],a.la=[]}l.Ab=function(a){if(!yf(this))return!1;this.b.Ab(a);return!0};
l.Bb=function(a,b,c){if(!yf(this))return!1;this.I=0;a||Ad(this)&&Bd(this,this.b.i[7],0);try{a=cd(this.b,a);var d=this.b.Bb(a);0<d&&(dd(this.b,a),this.I+=d,ad(this.b,d,!0),Ec(this.b,d),this.$++)}catch(f){"number"!=typeof f&&(this.I=0,ub(this.b,f.stack||f.message))}!1!==c&&L(this.b);this.Ha(b||!1);return 0<this.I};l.pa=function(a){this.b&&this.b.pa(a)};l.Ha=function(a){void 0===a&&(a=!0);this.S=Z(this.b.i[7]);a&&1!=this.fa?zf(this):Af(this)};
function yf(a){var b;if(b=a.b&&gb(a.b))b=a.b,b.u.ja?b=!0:(b.g(b.toString()+" not powered"),b=!1);return b&&!a.b.u.ha?!tb(a.b):!1}l.Qa=function(a,b){return!b&&(this.reset(!0),a&&this.restore&&!this.restore(a))?!1:!0};l.Pa=function(a,b){b&&this.g(a?"suspending":"shutting down");return a?this.save():!0};l.reset=function(a){mf(this);this.$=this.Ca=0;this.za=null;this.I=0;this.S=Z(this.b.i[7]);this.u.ha=!1;Bf(this);a||this.Ha()};
l.save=function(){var a=new M(this);a.set(0,uf(this.S));a.set(1,uf(this.ba));a.set(2,[this.j,this.ca,this.ka]);a.set(3,this.F);return a.data()};l.restore=function(a){var b=0;void 0!==a[2]&&(this.S=vf(a[b++]),this.ba=vf(a[b++]),this.j=a[b][0],"string"==typeof this.j&&(this.j=[this.j]),this.ca=a[b][1],this.ka|=a[b][2]);a[3]&&(this.F=a[3]);return!0};l.start=function(a,b){this.fa||this.g("running");this.u.ha=!0;this.Zb=a;this.$b=b};
l.stop=function(a,b){if(this.u.ha){this.u.ha=!1;this.I=b-this.$b;if(!this.fa){b="stopped";if(this.I){a-=this.Zb;var c=0<a?Math.round(1E3*this.I/a):0;b+=" (";Ad(this)&&(b+=this.$+" opcodes, ",this.Ca-=this.$,this.$=0);b+=this.I+" cycles, "+a+" ms, "+c+" hz)"}else E(this,-2147483648)&&(b+=" (use the 't' command to execute blocked faults)");this.g(b)}this.Ha(!0);this.Xb();Bf(this,this.b.i[7])}};function Ad(a){return 1<a.f.length||!!a.ua}
function Bd(a,b,c){var d=a.b;if(0<c&&(a.ua&&!--a.ua||vc(a,b,1,a.f)))return!0;0<=c&&a.la.length&&(a.$++,null!=Ib(a.H,b)&&(b=a.L[a.ma],b.w=d.i[7],b.Ja=!1,++a.ma==a.L.length&&(a.ma=0)));return!1}function lf(a){var b,c;a.f=["bp"];if(a.W)for(b=1;b<a.W.length;b++){c=a.W[b];var d=a.H;c=a.ea(c);wc(d.O[c>>>d.Z],!1)}a.W=["br"];if(a.D)for(b=1;b<a.D.length;b++)c=a.D[b],d=a.H,c=a.ea(c),wc(d.O[c>>>d.Z],!0);a.D=["bw"];a.Eb=0}
l.jb=function(a,b,c){var d=!0;c||Cf(this,a,b,!1,!0);if(a!=this.f){var f=this.ea(b);if(-1===f)this.g("invalid address: "+Y(this,b.w)),d=!1;else{var e=this.H;e.O[f>>>e.Z].jb(f&e.f,a==this.D)}}d&&(a.push(b),c?b.Ja=!0:(Df(this,a,a.length-1,"set"),mf(this)));return d};function Cf(a,b,c,d,f){var e=!1;c=a.ea(c);for(var g=1;g<b.length;g++){var h=b[g];if(c==a.ea(h)&&(!d||h.Ja)){e=!0;h.Ja||f||Df(a,b,g,"cleared");b.splice(g,1);b!=a.f&&(d=a.H,wc(d.O[c>>>d.Z],b==a.D));h.Ja||mf(a);break}}return e}
function Ef(a,b){for(var c=1;c<b.length;c++)Df(a,b,c);return b.length-1}function Df(a,b,c,d){c=b[c];a.g(b[0]+" "+Y(a,c.w)+(d?" "+d:c.Ic?' "'+c.Ic+'"':""))}function Bf(a,b){if(void 0!==b)vc(a,b,1,a.f,!0),a.fa=0;else for(b=1;b<a.f.length;b++){var c=a.f[b];if(c.Ja){if(!Cf(a,a.f,c,!0))break;b=0}}}
function vc(a,b,c,d,f){var e=!1;if(!a.Eb++)for(var g=1;!e&&g<d.length;g++){var h=d[g];if(!f||h.Ja)for(var k=a.ea(h),m=0;m<c;m++)if(b+m==k){var n,e=!0;h.Ja&&(Cf(a,d,h,!0),f=!0);if(n=h.Nc){for(var e=!1,p=0;p<n.length;p++)if(!Ff(a,n[p],!0)){if(n[p].indexOf("if")){e=!0;break}for(var q=p+1;q<n.length&&n[q].indexOf("else");q++)p++;if(q==n.length){e=!0;break}}a.b.u.ha||(e=!0)}if(e){f||Df(a,d,g,"hit");break}}}a.Eb--;return e}
function Gf(a,b,c,d){var f=Z(b.w),e=a.Ka(b,2),g,h;for(h in a.Lb)if(g=a.Lb[h][e&h])break;g||(g=[0]);h="";for(var k=pf[g[0]],m=g.length-1,n=1;n<=m;n++){var p=g[n];if(void 0!==p){var q;q=a;var y=p,p=b,u="",z=y&61440;if(4096==z)p=p.w+((e&255)<<24>>23)&65535,u=Y(q,p);else if(8192==z)p=p.w-((e&63)<<1)&65535,u=Y(q,p);else if(12288==z)u=Y(q,e&7,1);else if(24576==z)u=Y(q,e&63,1);else if(z=e&y,y&4032&&(z>>=6,y>>=6),y&63)switch(y=z&7,z&56){case 0:u=xf(y);break;case 8:u="@"+xf(y);break;case 16:7>y?u="("+xf(y)+
")+":(z=q.Ka(p,2),u="#"+Y(q,z,0,!0));break;case 24:7>y?u="@("+xf(y)+")+":(z=q.Ka(p,2),u="@#"+Y(q,z,0,!0));break;case 32:u="-("+xf(y)+")";break;case 40:u="@-("+xf(y)+")";break;case 48:z=q.Ka(p,2);u=Y(q,z,0,!0)+"("+xf(y)+")";7==y&&(u=[u,Y(q,z+p.w&65535)]);break;case 56:z=q.Ka(p,2),u="@"+Y(q,z)+"("+xf(y)+")",7==y&&(u=[u,Y(q,z+p.w&65535)])}q=u;if(!q||!q.length){h="INVALID";break}"string"!=typeof q&&(c=q[1],d=null,q=q[0]);0<h.length&&(h+=",");h+=q||"???"}}e="";g=Y(a,f.w)+":";if(-1!==f.w&&-1!==b.w){do if(e+=
" "+Y(a,a.Ka(f,2)),null==f.w)break;while(f.w!=b.w)}g+=ma(e,24);g+=ma(k,5);h&&(g+=" "+h);c&&(g=ma(g,60)+";"+c,g=a.b.u.rb?g+("cycles="+Yc(a.b).toString()+" cs="+t(a.b.Nb)):g+(null!=d?"="+d.toString():""));return g}function Hf(a,b){switch(b){case "N":a=a.b.Oa();break;case "Z":a=jd(a.b);break;case "V":a=id(a.b);break;case "C":a=N(a.b);break;default:a=0}return b.charAt(0)+(a?"1":"0")+" "}
function If(a,b){var c="",d=a.b;8>b?(c=xf(b),c+="="+Y(a,d.i[b])):13>b?c="A"+(b-8)+"="+Y(a,d.Ra[b-8]):16<=b&&20>b?c="S"+(b-16)+"="+Y(a,d.Aa[b-16]):20==b&&(c="PS="+Y(a,Zb(d)));c&&(c+=" ");return c}function Jf(a){var b,c="";for(b=0;6>b;b++)c+=If(a,b);c=c+"\n"+(If(a,6)+If(a,7)+If(a,20));return c+=Hf(a,"T")+Hf(a,"N")+Hf(a,"Z")+Hf(a,"V")+Hf(a,"C")}l.yc=function(a,b){return a[0]>b[0]?1:a[0]<b[0]?-1:0};
function Kf(a,b,c){var d=[],f=a.ea(b)>>>0;for(b=0;b<a.F.length;b++){var e=a.F[b],g=e.w>>>0,h=e.Vc;if(f>=g&&f<g+h){f=oa(e.uc,[f-g],a.yc);0<=f?Lf(a,b,f,d):c&&(f=~f,Lf(a,b,f-1,d),Lf(a,b,f,d));break}}return d}function Lf(a,b,c,d){var f={},e=a.F[b].uc,g=0,h=null;0<=c&&c<e.length&&(g=e[c][0],h=e[c][1]);h&&(f=a.F[b].Ma[h],h="."==h.charAt(0)?null:f.l||h);d.push(h);d.push(g);d.push(f.a);d.push(f.c)}
function Mf(a,b){var c=b.match(/^\s*([A-Z_]?[A-Z0-9_]*)\s*(=?)\s*(.*)$/i);if(c){if(!c[1])return jf(a)||a.g("no variables"),!0;if(!c[2])return jf(a,c[1]);if(!c[3])return delete a.ia[c[1]],!0;b=ef(a,c[3]);return void 0!==b?(a.ia[c[1]]=b,!0):!1}a.g("invalid assignment:"+b);return!1}
function Nf(a,b,c){var d=null;if(b=sf(a,b,!0)){a.ea(b);var f=Kf(a,b,!0);if(f.length){var e,g;f[0]&&(g="",(e=b.w-f[1])&&(g=" + "+t(e,4,!0)),e=f[0]+" ("+Y(a,f[1])+")"+g,c&&a.g(e),d=e);4<f.length&&f[4]&&(g="",(e=f[5]-b.w)&&(g=" - "+t(e,4,!0)),e=f[4]+" ("+Y(a,f[5])+")"+g,c&&a.g(e),d||(d=e))}else c&&a.g("no symbols")}return d}
function zf(a,b){var c;if(b&&"?"==b[1])a.g("register commands:"),a.g("\tr\tdump registers"),a.g("\trx [#]\tset flag or register x to [#]");else{var d=a.b;null==c&&(c=!0);if(b&&1<b.length){var f=b[1],e=f.indexOf("=");if(0<e)b=f.substr(e+1),f=f.substr(0,e);else if(2<b.length)b=b[2];else{a.g("missing value for "+b[1]);return}e=ef(a,b);if(void 0===e)return;b=f.toUpperCase();switch(b){case "SP":case "R6":d.i[6]=e&65535;break;case "PC":case "R7":ld(d,e);a.S=Z(d.i[7]);break;case "N":d.X=e?32768:0;break;
case "Z":d.Y=e?0:1;break;case "V":d.V=e?32768:0;break;case "C":d.U=e?65536:0;break;default:if("R"==b.charAt(0)&&(b=+b.charAt(1),0<=b&&6>b)){d.i[b]=e&65535;break}a.g("unknown register: "+f);return}L(d);a.g("updated registers:")}a.g(Jf(a));c&&(a.S=Z(d.i[7]),Af(a,Y(a,a.S.w)))}}function Of(a,b){b=na(b);var c=b.match(/^(['"])(.*?)\1$/);c?a.g(c[2]):ef(a,b,!0)}
function Pf(a,b,c){var d="t"!=b;c=gf(a,c,null,!0)||1;var f=1==c?0:1;"tc"==b&&(f=c,c=1);Ca(c,function(){return eb(a,!0)&&a.Bb(f,d,!1)},function(){L(a.b);eb(a,!1)})}
function Af(a,b,c,d){if(b=sf(a,b,!0)){void 0===d&&(d=1);var f=256;if(void 0!==c){d=sf(a,c,!0);if(!d||d.w<b.w)return;f=d.w-b.w;if(256<f){a.g("range too large");return}d=-1}c=0;for(var e;0<f&&d--;){e=fb(a,!1)||a.fa?a.I:null;var g=null!=e?"cycles":null,h=Kf(a,b),k=b.w;if(h[0]&&d&&(!c&&d||0>h[0].indexOf("+"))){var m=h[0]+":";h[2]&&(m+=" "+h[2]);a.g(m)}h[3]&&(g=h[3],e=null);e=Gf(a,b,g,e);a.g(e);a.S=b;f-=b.w-k;c++}}}
function Ff(a,b,c){var d=!0;try{b.length&&"end"!=b?c||a.g(">> "+b):(a.ca&&(a.g("ended assemble at "+Y(a,a.ba.w)),a.S=a.ba,a.ca=!1),b="");var f=b.charAt(0);if('"'==f||"'"==f)return!0;a.za=null;if(gb(a)&&0<b.length){a.ca&&(b="a "+Y(a,a.ba.w)+" "+b);var e=b.replace(/ +/g," ").split(" ");if(e&&e.length)for(var g=e[0],h=g.charAt(0),k=1;k<g.length;k++){var m=g.charAt(k);if("?"==h||"r"==h||"a">m||"z"<m){e[0]=g.substr(k);e.unshift(g.substr(0,k));break}}switch(e[0].charAt(0)){case "a":var n=sf(a,e[1],!0);
if(n)if(a.ba=n,void 0===e[2])a.g("begin assemble at "+Y(a,n.w)),a.ca=!0,L(a.b);else{var p;a.g("not supported yet");p=[];if(p.length){for(var q=0;q<p.length;q++)a.Vb(n,p[q],1);a.g(Gf(a,a.ba))}}break;case "b":a:{var y=e[0],u=e[1],z=b;if("?"==u)a.g("breakpoint commands:"),a.g("\tbp [a]\tset exec breakpoint at addr [a]"),a.g("\tbr [a]\tset read breakpoint at addr [a]"),a.g("\tbw [a]\tset write breakpoint at addr [a]"),a.g("\tbc [a]\tclear breakpoint at addr [a]"),a.g("\tbl\tlist all breakpoints"),a.g("\tbn [n]\tbreak after [n] instruction(s)");
else{var wa=y.charAt(1);if("l"==wa){var Fc;Fc=0+Ef(a,a.f);Fc+=Ef(a,a.W);(Fc+=Ef(a,a.D))||a.g("no breakpoints")}else if("n"==wa)a.ua=gf(a,u),a.g("break after "+a.ua+" instruction(s)");else if(void 0===u)a.g("missing breakpoint address");else{var Q=Z();if("*"!=u&&(Q=sf(a,u,!0),!Q))break a;"c"==wa?null==Q.w?(lf(a),a.g("all breakpoints cleared")):Cf(a,a.f,Q)||Cf(a,a.W,Q)||Cf(a,a.D,Q)||a.g("breakpoint missing: "+Y(a,Q.w)):null!=Q.w&&(wf(a,Q,z),"p"==wa?a.jb(a.f,Q):"r"==wa?a.jb(a.W,Q):"w"==wa?a.jb(a.D,Q):
a.g("unknown breakpoint command: "+wa))}}}break;case "c":a.kb&&(a.kb.value="");break;case "d":a:{var Ja,Ka=e[0],ea=e[1],xa=e[2],hg=e[3];if("?"==ea){var La="";for(Ja in G)a.Ia[Ja]&&(La&&(La+=","),La+=Ja);La+=",state,symbols";a.g("dump memory commands:");a.g("\tdb [a] [#]    dump # bytes at address a");a.g("\tdw [a] [#]    dump # words at address a");a.g("\tdd [a] [#]    dump # dwords at address a");a.g("\tdh [#] [#]    dump # instructions from history");La.length&&a.g("dump extension commands:\n\t"+
La)}else if("state"==ea){var ie=Qf(a.B,!0);"console"==xa?console.log(ie):(a.kb&&(a.kb.value=""),a.g(ie))}else if("symbols"==ea)for(var Gc=0;Gc<a.F.length;Gc++){var Hc=a.F[Gc],Ma;for(Ma in Hc.Ma)if("."!=Ma.charAt(0)){var je=Hc.Ma[Ma].o;if(void 0!==je){var ke=Hc.Ma[Ma].l;ke&&(Ma=ke);a.g(Y(a,je)+" "+Ma)}}}else{if("d"==Ka){for(Ja in G)if(e[1]==Ja){var le=a.Ia[Ja];le?(e.shift(),e.shift(),le(e)):a.g("no dump registered for "+ea);break a}ea||(Ka=a.lc||"db")}else a.lc=Ka;if("dh"==Ka){var me=ea,ne=xa,oe="",
pe=0,aa=a.ma,fa=a.L;if(fa.length){var V=+me||a.Gb,hb=+ne||10;isNaN(V)?V=hb:oe="more ";V>fa.length&&(a.g("note: only "+fa.length+" available"),V=fa.length);aa-=V;0>aa&&(null==fa[fa.length-1].w?(V=aa+V,aa=0):aa+=fa.length);var Ic=[];"call"==ne&&(hb=1E5,Ic=["CALL"]);for(void 0!==me&&a.g(V+" instructions earlier:");0<hb&&aa!=a.ma;){var qe=fa[aa++];if(null==qe.w)break;var ib=Z(qe.w),ig=V--,re=Gf(a,ib,"history",ig);(!Ic.length||0<=re.indexOf(Ic[0]))&&a.g(re);ib.jc&&(aa+=ib.jc,hb-=ib.jc,V-=ib.jc);aa>=fa.length&&
(aa=0);a.Gb=V;pe++;hb--}}pe||(a.g("no "+oe+"history available"),a.Gb=void 0)}else{var Rb=sf(a,ea);if(Rb){var Sb=0;xa&&("l"==xa.charAt(0)&&(xa=xa.substr(1)||hg),Sb=gf(a,xa)>>>0,65536<Sb&&(Sb=65536));for(var jb="",Na="dd"==Ka?4:"dw"==Ka?2:1,Tb=Na*Sb||128,jg=Tb+15>>4||1;jg--&&0<Tb;){var kb=0,Jc=0,lb,Kc="",se="",ea=Y(a,Rb.w);for(lb=4==Na?16:a.da;0<lb&&0<Tb;lb--){var Ub=a.sb(Rb,1),kb=kb|Ub<<(Jc++<<3);Jc==Na&&(Kc+=8==a.da?r(kb,3*Na):t(kb,2*Na),Kc+=1==Na?9==lb?"-":" ":"  ",kb=Jc=0);se+=32<=Ub&&128>Ub?String.fromCharCode(Ub):
".";Tb--}jb&&(jb+="\n");jb+=ea+"  "+Kc+(0==lb?" "+se:"")}jb&&a.g(jb);a.qb=Rb}}}}break;case "e":if("else"==e[0])break;var Oa,Lc,Mc,Nc,Oc=e[0],Pc=e[1];"eb"==Oc?(Oa=1,Lc=255,Mc=a.sb,Nc=a.Vb):"e"==Oc||"ew"==Oc?(Oa=2,Lc=65535,Mc=a.Ka,Nc=a.pb):Pc=null;if(null==Pc)a.g("edit memory commands:"),a.g("\teb [a] [...]  edit bytes at address a"),a.g("\tew [a] [...]  edit words at address a");else{var Vb=sf(a,Pc);if(Vb)for(var Wb=2;Wb<e.length;Wb++){var mb=ef(a,e[Wb]);if(void 0===mb){a.g("unrecognized value: "+
e[Wb]);break}mb&~Lc&&a.g("warning: "+t(mb)+" exceeds "+Oa+"-byte value");var kg=Mc.call(a,Vb);a.g("changing "+Y(a,Vb.w)+" from "+Y(a,kg,Oa)+" to "+Y(a,mb,Oa));Nc.call(a,Vb,mb,Oa)}}break;case "g":a:{var te=e[1],lg=b;if(void 0!==te){var Qc=sf(a,te,!0);if(!Qc)break a;wf(a,Qc,lg);a.jb(a.f,Qc,!0)}a.Ab(!0)||c||a.g("cpu busy or unavailable, run command ignored")}break;case "h":a:{var Rc;if(a.u.ha)Rc="halting",a.pa();else{if(fb(a,!0))break a;Rc="already halted"}c||a.g(Rc)}break;case "i":if("if"==e[0]){var Sc;
var nb=b.substr(2),nb=na(nb);ef(a,nb)?(c||a.g("true: "+nb),Sc=!0):(c||a.g("false: "+nb),Sc=!1);Sc||(d=!1)}break;case "k":var mg=e[0];if("?"==e[1])a.g("stack trace commands:"),a.g("\tk\tshow frame addresses"),a.g("\tks\tshow symbol information");else{var Tc=0,ue=Z(),ob=Z(a.b.i[6]);for(a.g("stack trace for "+Y(a,ob.w));10>Tc;){for(var ya=null,ng=256;65536>ob.w>>>0;){ue.w=a.Ka(ob,2);if(null==ob.w||!ng--)break;for(var og=a,Xb=ue,ve=null,pb=Xb.w,we=pb,Uc=1;6>=Uc&&pb;Uc++){if(2<Uc){Xb.w=pb;var Yb=Gf(og,
Xb);if(0<=Yb.indexOf("JSR")){var xe=Yb.indexOf(" ");if(pb+(Yb.indexOf(" ",xe+1)-xe-1)/2==we){ve=Yb;break}}}pb--}Xb.w=we;if(ya=ve)break}if(!ya||null==ya)break;var ye=null;if("ks"==mg){var ze=ya.match(/[0-9A-F]+$/);ze&&(ye=Nf(a,ze[0]))}ya=ma(ya,50)+"  ;"+(ye||"stack="+Y(a,ob.w));a.g(ya);Tc++}Tc||a.g("no return addresses found")}break;case "l":"ln"==e[0]&&Nf(a,e[1],!0);break;case "m":a:{var ga,ha=null,A=e[1];"?"==A&&(A=void 0);if(void 0!==A){var sa=0;if("all"==A)sa=1878917119,A=null;else if("on"==A)ha=
!0,A=null;else if("off"==A)ha=!1,A=null;else{"keys"==A&&(A="key");"kbd"==A&&(A="keyboard");for(ga in G)if(A==ga){sa=G[ga];ha=!!(a.ka&sa);break}if(!sa){a.g("unknown message category: "+A);break a}}if(sa)if("on"==e[2])a.ka|=sa,ha=!0;else if("off"==e[2]&&(a.ka&=~sa,ha=!1,1073741824==sa)){for(var Vc=0;Vc<a.Ba.length;Vc++)a.g(a.Ba[Vc]);a.Ba=[]}}var pg=0,qb="";for(ga in G)if(!A||A==ga){var qg=!!(a.ka&G[ga]);if(null===ha||ha==qg)qb&&(qb+=","),++pg%10||(qb+="\n\t"),"key"==ga&&(ga="keys"),qb+=ga}void 0===
A&&a.g("message commands:\n\tm [category] [on|off]\tturn categories on/off");a.g((null!==ha?ha?"messages on:  ":"messages off: ":"message categories:\n\t")+(qb||"none"));mf(a)}break;case "p":if("print"==e[0]){Of(a,b.substr(5));break}var rg="pr"==e[0]?1:0;if(a.fa)a.g("step in progress");else{var Ae=Z(a.b.i[7]);a.sb(Ae);a.fa?(a.jb(a.f,Ae,!0),a.Ab()||(a.B&&a.B.Xb(),a.fa=0)):Pf(a,rg?"tr":"t")}break;case "r":if("reset"==b){a.B&&a.B.reset();break}zf(a,e);break;case "s":a:switch(e[1]){case "base":if(e[2]){var rb=
+e[2];if(8==rb||10==rb||16==rb)a.da=rb;else{a.g("invalid base: "+rb);break}}a.g("default base: "+a.da);break;case "cs":var sb;void 0!==e[3]&&(sb=+e[3]);switch(e[2]){case "int":a.b.ub=sb;break;case "start":a.b.Ob=sb;break;case "stop":a.b.vb=sb;break;default:a.g("unknown cs option");break a}void 0!==sb&&Cc(a.b);a.g("checksums "+(a.b.u.rb?"enabled":"disabled"));break;case "sp":void 0!==e[2]&&($c(a.b,+e[2])||a.g("warning: using 1x multiplier, previous target not reached"));a.g("target speed: "+(a.b.mb.toFixed(2)+
"Mhz")+" ("+a.b.ab+"x)");break;case "?":a.g("debugger options:");a.g("\tbase #\t\tset default base to #");a.g("\tcs int #\tset checksum cycle interval to #");a.g("\tcs start #\tset checksum cycle start count to #");a.g("\tcs stop #\tset checksum cycle stop count to #");a.g("\tsp #\t\tset speed multiplier to #");break;default:e[1]&&a.g("unknown option: "+e[1])}break;case "t":Pf(a,e[0],e[1]);break;case "u":Af(a,e[1],e[2],8);break;case "v":if("var"==e[0]){Mf(a,b.substr(3))||(d=!1);break}a.g("PDP11js version 1.30.0 ("+
a.b.Yc+",RELEASE"+(vb?",TYPEDARRAYS":",LONGARRAYS")+")");a.g(window?window.navigator.userAgent:"");break;case "?":if(e[1]){Of(a,b.substr(1));break}var Wc="commands:",Xc;for(Xc in of)Wc+="\n"+ma(Xc,9)+of[Xc];Ad(a)||(Wc+="\nnote: history disabled if no exec breakpoints");a.g(Wc);break;default:a.g("unknown command: "+b),d=!1}}}catch(Be){a.g("debugger error: "+(Be.stack||Be.message)),d=!1}return d}function Dc(a,b,c){b=cf(a,b,c);for(var d in b)if(!Ff(a,b[+d]))return!1;return!0}
Pa(function(){for(var a=D(document,"pdp11","debugger"),b=0;b<a.length;b++){var c=a[b],d=C(c),d=new kf(d);cb(d,c)}});
function Rf(a,b,c){w.call(this,"Computer",a,Rf,67108864);this.u.ja=!1;Sf(this,b);this.W=Ac(this,"autoPower",a);this.B=0;this.fa=a.busWidth||a.buswidth;this.f=Tf;this.L=null;this.F=this.ca=!1;this.url=Ac(this,"url")||"";(Math.random()+.1).toString(36);this.j=Uf(this);if(this.b=bb("CPU",this.id)){this.G=bb("Debugger",this.id);this.H=new yb({id:this.wc+".bus",busWidth:this.fa},this.b,this.G);var d,f=ab(this.id);if((this.A=bb("Panel",this.id))&&this.A.kb)for(b=0;b<f.length;b++)d=f[b],d.ra=this.A.ra,d.g=
this.A.g,d.kb=this.A.kb;this.g("PDP11js v1.30.0\nCopyright \u00a9 2012-2016 Jeff Parsons <Jeff@pcjs.org>\nLicense: GPL version 3 or later <http://gnu.org/licenses/gpl.html>");this.g("Portions adapted from the PDP-11/70 Emulator v1.3 by Paul Nankervis <paulnank@hotmail.com>");for(b=0;b<f.length;b++)d=f[b],d.Ya&&d.Ya(this,this.H,this.b,this.G);b=null;d=a.resume;void 0!==d&&(1<d.length?b=this.I=d:this.f=parseInt(d,10));var e;if(a=Ac(this,"state")||(e=!0,a.state))b=this.$=a,e||(this.F=!0,this.f=Tf),this.f&&
(this.S=new M(this,"1.30.0"),Vf(this.S)?b=null:delete this.S);!b&&this.f&&(b=Wf(this))&&(this.F=!0);if(b){var g=this;ra(b,null,!0,function(a,b,c){c?(g.I=null,g.F=!1,g.ra("Unable to load machine state from server (error "+c+(b?": "+na(b):"")+")")):(g.L=b,g.ca=!0);F(g)})}else F(this);this.K.power||(this.W=!0);!c&&this.W&&Xf(this,this.Pb)}else v("Unable to find CPU component")}B(Rf);var Tf=0;
function Sf(a,b){if(!b){var c;if("object"==typeof resources&&(c=resources.parms))try{b=eval("("+c+")")}catch(d){v(d.message+" ("+c+")")}}a.da=b}function Ac(a,b,c){var d=b.toLowerCase(),d=Ua[b]||Ua[d];void 0===d&&a.da&&(d=a.da[b]);void 0===d&&c&&(d=c[b]);void 0===d&&"object"==typeof resources&&resources[b]&&(d=b);return d}function Xf(a,b,c){for(var d=ab(a.id),f=0;f<=d.length;f++){var e=f<d.length?d[f]:a;if(!gb(e)){gb(e,function(){Xf(a,b,c)});return}}b.call(a,c)}
function Yf(a,b){var c=new M(a,"1.30.0","validate");if(Vf(c)&&Zf(c)){var d=c.get("timestamp"),f=b?b.get("timestamp"):"unknown";d!=f&&(a.ra("Machine state may be out-of-date\n("+d+" vs. "+f+")\nCheck your browser's local storage limits"),b||c.clear())}}l=Rf.prototype;
l.Pb=function(a){void 0===a&&(a=this.f||(this.L?1:Tf));if(!this.B){this.B++;var b=!1,c=!1;this.ba=!1;var d=this.S||new M(this,"1.30.0");if(-1==a)b=!0;else if(a>Tf){if(Vf(d,this.L)){this.D=new M(this,"1.30.0","failsafe");Vf(this.D)&&($f(this,d),a=2,ag(this.D));this.D.set("timestamp",qa());bg(this.D);var f=this.f&&!this.F;if(1==a||ta("Click OK to restore the previous PDP11js machine state, or CANCEL to reset the machine.")){if(c=Zf(d)){var e=d.get("code"),g=d.get("data");e&&("ok"==e?Vf(d,g):("error"==
e&&"no machine state"!=g?(this.ra("Error: "+g),"unable to verify user"==g&&(Aa("user",""),this.j=null)):this.g(e+": "+g),ag(d),Vf(d)?(c=Zf(d),f=!0):c=!1))}f&&Yf(this,c?d:null)}else 2==a&&d.clear()}else Yf(this);delete this.L;delete this.S}f=ab(this.id);for(e=0;e<f.length;e++)g=f[e],g!==this&&g!=this.b&&(c=cg(this,g,d,b,c));b=[d,a,c];-1!=a?Xf(this,this.Ac,b):this.Ac(b)}};
function cg(a,b,c,d,f){if(!b.u.ja){b.u.ja=!0;if(b.Qa){var e=null;f&&((e=c.get(b.id))||(e=c.get(b.id.replace(/[a-z0-9]\./i,"."))));"string"===typeof e&&(e=null);!b.Qa(e,d)&&e&&(v("Unable to restore state for "+b.type),a.$&&!a.ca?(c.clear(),a.f=Tf,window&&window.location.reload()):a.ba=!0,b.Qa(null),f=!1)}if(!d&&b.vc)for(a=b.vc.split("|"),c=0;c<a.length;c++)b.status(a[c])}return f}
l.Ac=function(a){var b=a[0],c=0>a[1];a=a[2];this.ia=!0;this.u.ja=!0;var d=this.K.power;d&&(d.textContent="Shutdown");this.b&&(cg(this,this.b,b,c,a),this.b.Ib());this.ba&&($f(this,b),b.clear());!c&&this.D&&(this.D.clear(),delete this.D);this.B=0};
function $f(a,b){if(ta("There may be a problem with your PDP11js machine.\n\nTo help us diagnose it, click OK to send this PDP11js machine state to http://www.pcjs.org.")){var c=a.j||"";b=b.toString();var d={app:"PDP11js",ver:"1.30.0"};d.url=a.url;d.user=c;d.type="bug";d.data=b;ra("http://www.pcjs.org/api/v1/report",d,!0)}}
function Qf(a,b,c){var d,f="none";if(a.B)return null;a.B--;var e=new M(a,"1.30.0"),g=new M(a,"1.30.0","validate"),h=qa();g.set("timestamp",h);e.set("timestamp",h);e.set("version","1.30.0");e.set("url",window?window.location.href:null);e.set("browser",window?window.navigator.userAgent:"");a.b&&a.b.Pa&&(c&&a.b.pa(),d=a.b.Pa(b,c),"object"===typeof d&&e.set(a.b.id,d),c&&(a.b.u.ja=!1,!1===d&&(f=null)));for(var h=ab(a.id),k=0;k<h.length;k++){var m=h[k];m.u.ja&&(m.Pa&&(d=m.Pa(b,c),"object"===typeof d&&e.set(m.id,
d)),c&&(m.u.ja=!1,!1===d&&(f=null)))}f&&(c?(h=d=!1,b?(a.j&&dg(a,a.j,e.toString()),bg(g)&&bg(e)||(f=null,d=h=!0)):a.f&&(d=!0,h=3==a.f),d&&e.clear(h)):f=e.toString());c&&(a.u.ja=!1,b=a.K.power)&&(b.textContent="Power");a.B=0;return f}l.reset=function(){this.H&&this.H.reset&&(db(this,"Resetting "+this.H.type),this.H.reset());for(var a=ab(this.id),b=0;b<a.length;b++){var c=a[b];c!==this&&c!==this.H&&c.reset&&(db(this,"Resetting "+c.type),c.reset())}};
l.start=function(a,b){for(var c=ab(this.id),d=0;d<c.length;d++){var f=c[d];"CPU"!=f.type&&f!==this&&f.start&&f.start(a,b)}};l.stop=function(a,b){for(var c=ab(this.id),d=0;d<c.length;d++){var f=c[d];"CPU"!=f.type&&f!==this&&f.stop&&f.stop(a,b)}};
l.xa=function(a,b,c){var d=this;switch(b){case "power":return this.K[b]=c,c.onclick=function(){d.B||(d.u.ja?Qf(d,!1,!0):Xf(d,d.Pb))},!0;case "reset":return this.K[b]=c,c.onclick=function(){if(d.u.ja&&!d.B)if(d.f&&!d.I){var a=ta("Click OK to save changes to this PDP11js machine.\n\nWARNING: If you CANCEL, all disk changes will be discarded.");Qf(d,a,!0);!a&&d.$?window&&window.location.reload():d.Pb(Tf)}else d.reset(),d.b&&d.b.Ib()},!0;case "save":if(ia())c.parentNode.removeChild(c);else return this.K[b]=
c,c.onclick=function(){var a=Uf(d,!0);if(a){var b=!!(d.f&&!d.I||d.$),c=Qf(d,b);b?dg(d,a,c):d.ra("Resume disabled, machine state not saved")}},!0}return!1};
function Uf(a,b){var c=a.j;c||((c=za("user"),void 0!==c)?!c&&b&&(b=null,window&&(b=window.prompt("Saving machine states on the pcjs.org server is currently unsupported.\n\nIf you're running your own server, enter your user ID below.","")),c=b)&&((c=eg(a,c))||a.ra("The user ID is invalid.")):b&&a.ra("Browser local storage is not available"));return c}
function eg(a,b){a.j=null;b=ra(ja()+"/api/v1/user?req=verify&user="+b);var c=b[1];if(!b[0]&&c)try{b=eval("("+c+")"),b.code&&"ok"==b.code&&(Aa("user",b.data),a.j=b.data)}catch(d){v(d.message+" ("+c+")")}return a.j}function Wf(a){var b=null;a.j&&(b=ja()+"/api/v1/user?req=load&user="+a.j+"&state="+fg(a,"1.30.0"));return b}
function dg(a,b,c){if(c){var d={req:"store"};d.user=b;d.state=fg(a,"1.30.0");d.data=c;b=ra(ja()+"/api/v1/user",d);d=b[0];if(b[1]){if(d){var f=d.indexOf("\n");0<f&&(d=d.substr(0,f));d.indexOf("Error: ")||(d=d.substr(7))}d='{"code":'+b[1]+',"data":"'+d+'"}'}b=JSON.parse(d);b&&"ok"==b.code?a.ra("Machine state saved to server"):c&&(c=b&&b.data||"unable to save machine state",c="error"==b.code?"Error: "+c:"Error "+b.code+": "+c,a.ra(c),Aa("user",""),a.j=null)}}l.Xb=function(){};
l.Ha=function(a){this.b&&this.b.Ha(a);this.A&&this.A.Ha(a)};Pa(function(){for(var a=D(document,"pdp11-machine"),b=0;b<a.length;b++)for(var c=a[b],d=C(c),c=D(c,"pdp11","computer"),f=0;f<c.length;f++){var e=c[f],g=C(e),g=new Rf(g,d,!0);cb(g,e);g.W&&Xf(g,g.Pb)}});Ea.show.push(function(){for(var a=D(document,"pdp11","computer"),b=0;b<a.length;b++){var c=C(a[b]);(c=bb("Computer",c.id))&&c.ia&&!c.u.ja&&c.Pb(-1)}});
Ea.exit.push(function(){for(var a=D(document,"pdp11","computer"),b=0;b<a.length;b++){var c=C(a[b]);(c=bb("Computer",c.id))&&c.u.ja&&Qf(c,!(!c.f||c.I),!0)}});function M(a,b,c){this.id=a.id;this.key=fg(a,b,c);this.G=a.G;ag(this,a.Sc)}function fg(a,b,c){a=a.id;if(b){var d=b.indexOf(".");0<d&&(a+=".v"+b.substr(0,d))}c&&(a+="."+c);return a}
M.prototype={constructor:M,set:function(a,b){try{this[this.id][a]=b}catch(c){}},get:function(a){return this[this.id][a]||null},value:function(){return this[this.id]},data:function(){return this[this.id]},toString:function(){var a=this[this.id];return"string"==typeof a?a:JSON.stringify(a)},clear:function(a){ag(this);var b=[];try{for(var c=0,d=window.localStorage.length;c<d;c++)b.push(window.localStorage.key(c))}catch(f){}for(c=0;c<b.length;c++)if((d=b[c])&&(a||d.substr(0,this.key.length)==this.key)){try{window.localStorage.removeItem(d)}catch(f){}b.splice(c,
1);c=0}}};function ag(a,b){a[a.id]={};b&&a.set("parms",b);a.b=!1}function bg(a){var b=!0;if(va()){var c=JSON.stringify(a[a.id]);Aa(a.key,c)||(v("Unable to store "+c.length+" bytes in browser local storage"),b=!1)}return b}function Zf(a){var b=!0;try{a[a.id]=JSON.parse(a[a.id])}catch(c){v(c.message||c),b=!1}return b}function Vf(a,b){return b?(a[a.id]=b,a.b=!0):a.b?!0:va()&&(b=za(a.key))?(a[a.id]=b,a.b=!0):!1}var gg=0;
function sg(a,b,c,d,f,e){f("Loading "+a+"...");ra(a,null,!0,function(g,h,k){k?(h||(h="unable to load "+a+" ("+k+")"),e(h,null)):tg(h,a,b,c,d,f,e)})}
function tg(a,b,c,d,f,e,g){function h(a,e){if(e)g(e,null);else{c&&($a(c,b,a),(e=b)&&0>e.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(e=window.location.pathname+e),d?"}"==d.slice(-1)?(d=d.slice(0,-1),1<d.length&&(d+=",")):d='{state:"'+d+'",':d="{",d+='url:"'+e+'"}',"object"==typeof resources&&(e=null),a=a.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(d?" parms='"+d+"'":"")+(e?' url="'+e+'"':"")));f||(a=a.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1PDP11js$2"),
a=a.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1pdp11$2"));e=null;if("<"==a.charAt(0))try{f||(a=a.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(e=new window.ActiveXObject("Microsoft.XMLDOM"),e.async=!1,e.loadXML(a)):e=(new window.DOMParser).parseFromString(a,"text/xml")}catch(n){e=null,a=n.message}else a="unrecognized XML: "+(255<a.length?a.substr(0,255)+"...":a);g(a,e)}}a?f?ug(a,e,h):h(a,null):g("no data"+(b?" for file: "+b:""),null)}
function ug(a,b,c){var d;if(d=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(a)){var f=d[2];b("Loading "+f+"...");ra(f,null,!0,function(e,g,h){if(h||!g)c(a,"unable to resolve XML reference: "+d[0]+" ("+h+")");else{if(e=d[3])if(h=g.match(new RegExp("<"+d[1]+"[^>]*>"))){for(var k=h[0],m,n=/( [a-z]+=)(['"])(.*?)\2/g;m=n.exec(e);)k=0>k.indexOf(m[1])?k.replace(">",m[0]+">"):k.replace(new RegExp(m[1]+"(['\"])(.*?)\\1"),m[0]);h[0]!=k&&(g=g.replace(h[0],k))}else{c(a,"missing <"+d[1]+"> in "+f);return}g=g.replace(/<\?xml[^>]*>[\r\n]*/,
"");a=a.replace(d[0],g);ug(a,b,c)}})}else c(a,null)}
function vg(a,b,c,d){function f(a){if(void 0===h){var b=g&&D(g,"machine-warning");h=b&&b[0]||g}h&&(h.innerHTML=la(a))}function e(a){f("Error: "+a);k&&(--gg||Ra(!0));k=!1}var g,h,k=!0;gg++;Za[a]={};try{if(g=document.getElementById(a)){var m;if("object"==typeof resources&&(m=resources.css)){var n=document.head||document.getElementsByTagName("head")[0],p=document.createElement("style");p.type="text/css";p.styleSheet?p.styleSheet.cssText=m:p.appendChild(document.createTextNode(m));n.appendChild(p)}c||
(c="/versions/pdp11/1.30.0/components.xsl");m=function(d,h){h?sg(c,null,null,!1,f,function(d,k){k?($a(a,c,d),f("Processing "+b+"..."),window.ActiveXObject||"ActiveXObject"in window?(k=h.transformNode(k))?(g.outerHTML=k,--gg||Ra(!0)):e("transformNodeToObject failed"):document.implementation&&document.implementation.createDocument?(d=new XSLTProcessor,d.importStylesheet(k),(k=d.transformToFragment(h,document))?g.parentNode?(g.parentNode.replaceChild(k,g),--gg||Ra(!0)):e("invalid machine element: "+
a):e("transformToFragment failed")):e("unable to transform XML: unsupported browser")):e(d)}):e(d)};"<"!=b.charAt(0)?sg(b,a,d,!0,f,m):tg(b,null,a,d,!1,f,m)}else e("missing machine element: "+a)}catch(q){e(q.message)}return k}window.embedPDP11=function(a,b,c,d){Ra(!1);return vg(a,b,c,d)};window.enableEvents=Ra;window.sendEvent=Sa;})();
