(function(){var l;
function aa(a,b){var c;if(a){b||(b=10);var d=a.charAt(0),f=0<a.indexOf(",");f&&(a=a.replace(/,/g,""));"#"==d?(b=8,d=null):"$"==d&&(b=16,d=null);null==d?a=a.substr(1):("0"==d&&(d=a.charAt(1),"b"==d&&f&&(b=2,d=null),"o"==d?(b=8,d=null):"x"==d&&(b=16,d=null)),null==d?a=a.substr(2):(d=a.charAt(a.length-1).toLowerCase(),"y"==d?(b=2,d=null):"."==d?(b=10,d=null):"h"==d&&(b=16,d=null),null==d&&(a=a.substr(0,a.length-1))));var e,d=a;((f=b)&&10!=f?16==f?d.match(/^[0-9a-f]+$/i):8==f?d.match(/^[0-7]+$/):2==f&&
d.match(/^[01]+$/):d.match(/^[0-9]+$/))&&!isNaN(e=parseInt(a,b))&&(c=e|0)}return c}function r(a,b,c){var d="";b?11<b&&(b=11):b=a&-65536?11:6;if(null==a||isNaN(a))for(;0<b--;)d="?"+d;else for(;0<b--;)d=String.fromCharCode((a&7)+48)+d,a>>=3;return(c?"0o":"")+d}function t(a,b,c){var d="";b?8<b&&(b=8):b=a&-65536?8:4;if(null==a||isNaN(a))for(;0<b--;)d="?"+d;else for(;0<b--;){var f=a&15,f=f+(0<=f&&9>=f?48:55),d=String.fromCharCode(f)+d;a>>=4}return(c?"0x":"")+d}
function ca(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));return b}function da(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase());return b}function ea(){var a=fa();return-1!==a.indexOf("pcjs.org",a.length-8)}var ka={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"};function la(a){return a.replace(/[&<>"']/g,function(a){return ka[a]})}function ma(a,b){return(a+"                                        ").slice(0,b)}
function na(a){return String.prototype.trim?a.trim():a.replace(/^\s+|\s+$/g,"")}function oa(a,b,c){var d=0,f=a.length,e=0;for(c||(c=function(a,b){return a>b?1:a<b?-1:0});d<f;){var g=d+f>>1,h;h=c(b,a[g]);0<h?d=g+1:(f=g,e=!h)}return e?d:~d}var pa=Date.now||function(){return+new Date};function qa(){function a(a){return(10>a?"0":"")+a}var b=new Date;return b.getFullYear()+"-"+a(b.getMonth()+1)+"-"+a(b.getDate())+" "+a(b.getHours())+":"+a(b.getMinutes())+":"+a(b.getSeconds())}
function ra(a,b,c,d){var f=0,e=null,g=null;if("object"==typeof resources&&(e=resources[a]))return d&&d(a,e,f),[e,f];if(c&&"function"==typeof resources)return resources(a,function(b,c){d&&d(a,b,c)}),g;var h=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");c&&(h.onreadystatechange=function(){4===h.readyState&&(e=h.responseText,200==h.status||!h.status&&e.length&&"file:"==(window?window.location.protocol:"file:")||(f=h.status||-1),d&&d(a,e,f))});if(b&&"object"==
typeof b){var k="",m;for(m in b)b.hasOwnProperty(m)&&(k&&(k+="&"),k+=m+"="+encodeURIComponent(b[m]));k=k.replace(/%20/g,"+");h.open("POST",a,!!c);h.setRequestHeader("Content-type","application/x-www-form-urlencoded");h.send(k)}else h.open("GET",a,!!c),"bytes"==b&&h.overrideMimeType("text/plain; charset=x-user-defined"),h.send();c||(e=h.responseText,200!=h.status&&(f=h.status||-1),d&&d(a,e,f),g=[e,f]);return g}function fa(){return"http://"+(window?window.location.host:"www.pcjs.org")}
function x(a){window&&window.alert(a)}function sa(a){var b=!1;window&&(b=window.confirm(a));return b}var ta=null;function va(){if(null==ta){var a=!1;if(window)try{window.localStorage.setItem("PCjs.localStorage","PCjs.localStorage"),a="PCjs.localStorage"==window.localStorage.getItem("PCjs.localStorage"),window.localStorage.removeItem("PCjs.localStorage")}catch(b){a=!1}ta=a}return ta}function wa(a){var b;if(window)try{b=window.localStorage.getItem(a)}catch(c){}return b}
function za(a,b){try{return window.localStorage.setItem(a,b),!0}catch(c){}return!1}function Aa(a){if(window){var b=window?window.navigator.userAgent:"";return"iOS"==a&&b.match(/(iPod|iPhone|iPad)/)&&b.match(/AppleWebKit/)||"MSIE"==a&&b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)?!0:!1}return!1}function Ba(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function Ca(a,b){function c(){b(100===d)&&(f=setTimeout(c,d),d=100)}var d=0,f=null,e=!1;a.onmousedown=function(){e||f||(d=500,c())};a.ontouchstart=function(){f||(d=500,c())};a.onmouseup=a.onmouseout=function(){f&&(clearTimeout(f),f=null)};a.ontouchend=a.ontouchcancel=function(){f&&(clearTimeout(f),f=null);e=!0}}var Da={init:[],show:[],exit:[]},Ea=!1,Fa=!1,Ga=!0;function Ha(a,b){if(window){var c=window[a];window[a]="function"!==typeof c?b:function(){c&&c();b()}}}function Ia(a){Da.init.push(a)}
function Ja(a){if(Ga)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){x(""+("An unexpected exception occurred:\n\n"+c.message+"\n\nPlease send this information to support@pcjs.org. Thanks."))}}function Qa(a){!Ga&&a?(Ga=!0,Ea&&Ra("init"),Fa&&Ra("show")):Ga=a}function Ra(a){Da[a]&&Ja(Da[a])}Ha("onload",function(){Ea=!0;Ja(Da.init)});Ha("onpageshow",function(){Fa=!0;Ja(Da.show)});Ha(Aa("Opera")||Aa("iOS")?"onunload":"onbeforeunload",function(){Ja(Da.exit)});
function y(a,b,c,d){this.type=a;b||(b={id:"",name:""});this.id=b.id||"";this.name=b.name;this.sc=b.comment;this.Sc=b;b=this.id.indexOf(".");0>b?this.fc=this.id:(this.vc=this.id.substr(0,b),this.fc=this.id.substr(b+1));this[a]=c;this.u={ready:!1,Jb:!1,gc:!1,ja:!1,error:!1};this.Yb=null;this.u.error=!1;this.M={};this.G=null;this.ka=d||0;A.push(this)}var Sa=void 0,Ta={};
if(window){Sa||(Sa=window.location.search.substr(1));for(var Ua,Va=/\+/g,Wa=/([^&=]+)=?([^&]*)/g;Ua=Wa.exec(Sa);)Ta[decodeURIComponent(Ua[1].replace(Va," "))]=decodeURIComponent(Ua[2].replace(Va," "))}function Xa(a){function b(){}if(window){if(!a)throw new TypeError;if(Object.create)return Object.create(a);var c=typeof a;if("object"!==c&&"function"!==c)throw new TypeError;}b.prototype=a;return new b}
function C(a,b){b||(b=y);a.prototype=Xa(b.prototype);a.prototype.constructor=a;a.prototype.parent=b.prototype}if(window){window.PCjs||(window.PCjs={});var Ya=window.PCjs.Machines||(window.PCjs.Machines={}),A=window.PCjs.Components||(window.PCjs.Components=[])}else Ya={},A=[];function Za(a,b,c){Ya[a]&&b&&(Ya[a][b]=c)}function $a(a){var b,c=[];a&&(a=0<(b=a.indexOf("."))?a.substr(0,b+1):"");for(b=0;b<A.length;b++){var d=A[b];a&&d.id.indexOf(a)||c.push(d)}return c}
function ab(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<A.length;d++)if(c)c==A[d]&&(c=null);else if(!(a!=A[d].type||b&&A[d].id.indexOf(b)))return A[d]}return null}function D(a){var b=null;if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(c){x(c.message+" ("+a+")")}return b}
function bb(a,b){b=E(b.parentNode,"pdp11-control");for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,f=0;f<d.length;f++){var e=d[f];if(1===e.nodeType){var g=e.getAttribute("class");if(g)for(var h=g.split(" "),k=0;k<h.length;k++)switch(g=h[k],g){case "pdp11-binding":(g=D(e))&&g.binding&&a.xa(g.type,g.binding,e,g.value),k=h.length}}}}
function E(a,b,c){c&&(b+="-"+c+"-object");if(a.getElementsByClassName)return a.getElementsByClassName(b);var d;c=[];a=a.getElementsByTagName("*");var f=new RegExp("(^| )"+b+"( |$)");b=0;for(d=a.length;b<d;b++)f.test(a[b].className)&&c.push(a[b]);return c}
y.prototype={constructor:y,parent:null,toString:function(){return this.name?this.name:this.id||this.type},xa:function(a,b,c){switch(b){case "clear":return this.M[b]||(this.M[b]=c,c.onclick=function(a){return function(){a.M.print&&(a.M.print.value="")}}(this)),!0;case "print":return this.M[b]||(this.jb=this.M[b]=c,c.value="",this.g=function(a){return function(b,c){8192<a.value.length&&(a.value=a.value.substr(a.value.length-4096));a.value+=(void 0!==c?c+": ":"")+(b||"")+"\n";a.scrollTop=a.scrollHeight}}(c),
this.ra=function(a){this.g(a,this.fc)}),!0;default:return!1}},log:function(){},g:function(){},status:function(a){this.g(this.fc+": "+a)},ra:function(a,b,c){c=c||this.type;b||x((c?c+": ":"")+a)},Qa:function(){return this.u.ja=!0},Pa:function(a,b){b&&(this.u.ja=!1);return!0}};function cb(a,b,c,d){a.G&&(!0===c||F(a,c|0))&&a.G.message(b,d)}function F(a,b){if(a.G){a===a.G?b|=0:b=b||a.ka;var c=a.G.ka&b;return!!b&&c===b||!!(c&a.G.Mc)}return!1}
function db(a,b){if(a.u.gc)return a.u.Jb=!1,a.u.gc=!1;if(a.u.error)return a.g(a.toString()+" error"),!1;a.u.Jb=b;return a.u.Jb}function eb(a,b){a.u.Jb&&(b?a.u.gc=!0:void 0===b&&a.g(a.toString()+" busy"));return a.u.Jb}function G(a){if(!a.u.error&&(a.u.ready=!0,a.u.ready)){var b=a.Yb;a.Yb=null;b&&b()}}function fb(a,b){b&&(a.u.ready?b():a.Yb=b);return a.u.ready}function gb(a){return a.u.error?(a.g(a.toString()+" error"),!0):!1}function hb(a,b){a.u.error=!0;a.ra(b)}
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return f.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),f=this;c.prototype=this.prototype;b.prototype=new c;return b});
var ub="undefined"!==typeof ArrayBuffer,H={cpu:1,trap:16,bus:64,mem:128,keyboard:65536,key:131072,disk:2097152,serial:8388608,speaker:33554432,computer:67108864,log:268435456,warn:536870912,buffer:1073741824,halt:-2147483648};function vb(a){y.call(this,"Panel",a,vb)}C(vb);l=vb.prototype;l.xa=function(a,b,c,d){return this.B&&this.B.xa(a,b,c,d)||this.b&&this.b.xa(a,b,c,d)||this.G&&this.G.xa(a,b,c,d)?!0:this.parent.xa.call(this,a,b,c,d)};l.Ya=function(a,b,c,d){this.B=a;this.I=b;this.b=c;this.G=d};
l.Qa=function(a,b){b||wb();return!0};l.Pa=function(){return!0};l.Ha=function(){};function wb(){for(var a=!1,b=E(document,"pdp11","panel"),c=0;c<b.length;c++){var d=b[c],f=D(d),e;a:{e=f.id;if(void 0!==e){var g;for(g=0;g<A.length;g++)if(A[g].id===e){e=A[g];break a}}e=null}e||(a=!0,e=new vb(f));bb(e,d);a&&G(e)}}Ia(wb);
function xb(a,b,c){y.call(this,"Bus",a,xb,64);this.b=b;this.G=c;this.H=a.busWidth||16;this.C=Math.pow(2,this.H);this.j=this.C-1|0;this.Z=(this.H>>1)+2;10>this.Z&&(this.Z=10);15<this.Z&&(this.Z=15);this.Ea=1<<this.Z;this.K=this.Ea>>2;this.f=this.Ea-1;this.A=this.C/this.Ea|0;this.B=this.A-1;this.Ta=[];this.F=null;this.Kb=this.Ic;a=new I;yb(a,this.G);this.O=Array(this.A);for(b=0;b<this.A;b++)this.O[b]=a;this.Fb=Array(4);this.Fb[0]=zb;this.Fb[1]=Ab;this.Fb[2]=Bb;this.Fb[3]=Cb;Db(this,this.C-8192,8192,
Eb,this);Db(this,57344,8192,Eb,this);G(this)}C(xb);function zb(a,b){var c=this.controller,d=c.Ta[a];if(d){F(c)&&cb(c,d[5]+".readByte("+r(b)+")",0,!0);if(d[0])return d[0](b);if(d[2])return b&1?d[2](b&-2)>>8:d[2](b)&255}else if(b&1&&(d=c.Ta[a&-2])&&(F(c)&&cb(c,d[5]+".readByte("+r(b)+")",0,!0),d[2]))return d[2](b&-2)>>8;c.g("warning: unconverted read access to byte @"+r(b));return c.Kb(b,-1,1)}
function Ab(a,b,c){var d=this.controller,f=d.Ta[a];if(f){F(d)&&cb(d,f[5]+".writeByte("+r(c)+","+r(b)+")",0,!0);if(f[1]){f[1](b,c);return}if(f[3]){a=f[2]?f[2](c):0;if(c&1)f[3](a&255|b<<8,c&-2);else f[3](a&-256|b,c);return}}else if(c&1&&(f=d.Ta[a&-2])&&(F(d)&&cb(d,f[5]+".writeByte("+r(c)+","+r(b)+")",0,!0),f[3])){c&=-2;a=f[2]?f[2](c):0;f[3](a&255|b<<8,c);return}d.g("warning: unconverted write access to byte @"+r(c));d.Kb(c,b,1)}
function Bb(a,b){var c=this.controller;if(a=c.Ta[a]){F(c)&&cb(c,a[5]+".readWord("+r(b)+")",0,!0);if(a[2])return a[2](b);if(a[0])return a[0](b)|a[0](b+1)<<8}c.g("warning: unconverted read access to word @"+r(b));return c.Kb(b,-1,0)}function Cb(a,b,c){var d=this.controller;if(a=d.Ta[a]){F(d)&&cb(d,a[5]+".writeWord("+r(c)+","+r(b)+")",0,!0);if(a[3]){a[3](b,c);return}if(a[1]){a[1](b&255,c);a[1](b>>8,c+1);return}}d.g("warning: unconverted write access to word @"+r(c));d.Kb(c,b,0)}l=xb.prototype;
l.reset=function(){this.F&&this.F()};l.Ic=function(){return 0};l.Qa=function(a,b){b||this.reset();return!0};
function Db(a,b,c,d,f){for(var e=b,g=c,h=e>>>a.Z;0<g&&h<a.O.length;){var k=a.O[h],m=h*a.Ea,n=a.Ea-(e-m);n>g&&(n=g);if(k&&k.size){if(k.type==d&&k.controller==f){if(e+g<=k.w)return k.Vb+=k.w-e,k.w=e,!0;if(e>=k.w+k.Vb){n=k.size-(e-m);n>g&&(n=g);k.Vb=e-k.w+n;e=m+a.Ea;g-=n;h++;continue}}return Fb(1,e,g)}e=new I(e,n,a.Ea,d,f);yb(e,a.G,k);a.O[h++]=e;e=m+a.Ea;g-=n}return 0>=g?(a.status(Math.floor(c/1024)+"Kb "+Gb[d]+" at "+t(b,8,!0)),!0):Fb(2,b,c)}
l.sb=function(a){return this.O[(a&this.j)>>>this.Z].wb(a&this.f,a)};l.Ka=function(a){var b=a&this.f,c=(a&this.j)>>>this.Z;return b!=this.f?this.O[c].Bc(b,a):this.O[c++].wb(b,a)|this.O[c&this.B].wb(0,a+1)<<8};function Hb(a,b){var c=b&a.f,d=(b&a.j)>>>a.Z;return c!=a.f?a.O[d].lc(c,b):a.O[d++].Ob(c,b)|a.O[d&a.B].Ob(0,b+1)<<8}l.Sb=function(a,b){this.O[(a&this.j)>>>this.Z].Cb(a&this.f,b&255,a)};
l.ob=function(a,b){var c=a&this.f,d=(a&this.j)>>>this.Z;c!=this.f?this.O[d].Hc(c,b&65535,a):(this.O[d++].Cb(c,b&255,a),this.O[d&this.B].Cb(0,b>>8&255,a+1))};function Ib(a){for(var b=0,c=[],d=0;d<a.A;d++){var f=a.O[d];if(f.Xa||f.Pc){c[b++]=d;var e=b++;if(f=f.save()){for(var g=0,h=0,k=[];g<f.length;){for(var m=f[g],n=g+1;n<f.length&&f[n]===m;)n++;k[h++]=n-g;k[h++]=m;g=n}k.length<f.length&&(f=k)}c[e]=f}}return c}
function Jb(a,b){var c=Kb,d;for(d in c)for(var f=c[d],e=f[0]?f[0].bind(b):null,g=f[1]?f[1].bind(b):null,h=f[2]?f[2].bind(b):null,k=f[3]?f[3].bind(b):null,m=a,n=+d,f=f[4],q=+d;q<=n;q+=2){var p=q&8191;void 0!==m.Ta[p]?x("I/O address already registered: "+t(q,8,!0)):m.Ta[p]=[e,g,h,k,!1,f||"unknown"]}}function Lb(a,b,c){a.F=b;a.Kb=c}function Fb(a,b,c){x("Memory block error ("+a+": "+t(b)+","+t(c)+")");return!1}
function J(a){y.call(this,"Device",a,J);this.f={kc:[],va:0,ya:128,G:127,Oc:0};this.B={data:0,vd:0,tb:20,od:0};this.j={N:0,pc:-1};this.A={Qb:2496,oa:0,R:128,Rb:0,Pb:0,wa:0,Cc:0,qa:[],hb:[406,406,406,406],aa:[12,12,12,12]};this.C={N:129,Ib:0,ga:0,$a:0,Ua:0,fb:0,qa:[],aa:[40,40,40,40],hb:[1024,1024,512,512],Kc:[157,157,29,29]};this.F={b:[8210,8208,8210,8226],aa:[22,22,22,50],gb:[19,19,19,32],ec:[815,411,815,630],qa:[],T:2176,zb:0,xb:0,Ga:[0,0,0,0,0,0,0,0],Fa:0,sa:[4544,4544,4544,4544,4544,4544,4544,
4544],yb:[0,0,0,0,0,0,0,0],nb:0,ld:[0,0,0,0,0,0,0,0],Dc:0,Ec:[0,0,0,0,0,0,0,0],f:[0,0,0,0,0,0,0,0],md:[1,2,3,4,5,6,7,8],Fc:[0,0,0,0,0,0,0,0],Sa:[0,0,0,0,0,0,0,0],dc:[0,0,0,0,0,0,0,0],jd:[0,0,0,0,0,0,0,0],kd:[0,0,0,0,0,0,0,0],gd:[0,0,0,0,0,0,0,0],hd:[0,0,0,0,0,0,0,0],eb:0,nc:0}}C(J);
var Mb=[4127,448,4191,450,4383,452,2591,454,21983,32768,65534,13791,16384,65534,770,2719,454,2591,65534,257,0,2566,33028,34051,33282,1281,33537,0,2758,32771,770,1025,1793,0,3078,33794,34305,513,0,5574,43690,4480,4097,4162,4227,4292,4357,57665,1281,769,0,3138,34305,1281,0,24707,2691,2627,24769,34561,1793,0,3076,20739,24899,2691,34562,2753,1281,0,2624,33537,0,16385,24641,1537,1793,0,193,8279,21589,516,12549,1538,2629,513,0,38336,65281,32769,0,32258,2561,2689,32258,3008,514,3009,769,0,5574,510,2551,
2,0,9678,208,769,0,5582,226,135,0,2598,5606,236,2,0,95,242,128,5573,57344,2591,6,5599,256,4,5574,510,3045,5599,460,76,2591,78,5571,65510,5579,12,5570,512,4224,4104,3024,8197,33788,4224,4609,8193,769,0,2640,8197,33785,6145,2625,8193,769,0,8194,761,2574,5572,43690,5579,24,5568,2048,5570,512,2628,4360,2632,2632,8708,769,0,3103,65514,34562,0,305,35406,754,258,119,65160,3024,32403,5579,36,5568,3072,35446,1,740,5570,512,4224,4104,3024,8197,33788,5569,3,2574,3039,454,528,5582,24,4224,2632,2632,8200,769,
0,3024,3103,65514,34562,0,264,8197,33779,5003,2574,32337,260,0,258,5579,12,6080,448,6081,450,6084,452,116,2,6084,65400,17860,65024,21956,62976,38848,65401,3200,161,76,0,16944,10797];l=J.prototype;l.Ya=function(a,b,c,d){this.I=b;this.b=c;this.G=d;var f=this;this.j.pc=Nb(this.b,function(){f.j.Za|=128;f.j.Za&64&&(K(f.b,0,6,64),Ob(f.b,f.j.pc))});Jb(b,this);Lb(b,this.reset.bind(this),this.Jc.bind(this));G(this)};l.Zc=function(){var a=this.j.Za;this.j.Za&=-129;return a};
l.qd=function(a){this.j.Za=a;a&64&&Ob(this.b,this.j.pc);this.j.Za=a&-129};l.$c=function(){var a=this.b;return a.K&62337|a.za<<5|a.Ba<<1};l.rd=function(a){var b=4,c=this.b;c.K=a&=62337;c.za=a>>5&3;c.Ba=a>>1&15;c.$b=a&257?a&1?6:4:0;Pb(c);a=c.K;a&1|256&&(b=this.b.mb&16?1:2);this.B.tb=this.B.tb&-8|b};l.bd=function(){return this.f.va};l.td=function(a){this.f.va=this.f.va&128|a&-129};l.cd=function(){return this.f.ya};
l.ud=function(a){if(128==(this.f.ya&192)&&a&64){var b=this;K(this.b,8,4,52,function(){b.f.ya|=128;return!!(b.f.ya&64)})}this.f.ya=this.f.ya&128|a&-129};l.ad=function(){return Qb(this.b)};l.sd=function(a){Rb(this.b,a&-1809|Qb(this.b)&1808);this.b.D|=128};
function Sb(a){var b=a.A,c,d,f,e=b.wa>>13&7;"undefined"===typeof b.qa[e]&&(b.qa[e]={cache:[],postProcess:a.dd,drive:e,blocksize:256,mapped:0,maxblock:b.hb[e]*b.aa[e],url:"rk"+e+".dsk"});b.R&=-129;switch(b.R>>1&7){case 0:b.Qb=2496;b.oa=0;b.R=128;b.wa=0;break;case 1:if((b.wa>>4&511)>=b.hb[e]){b.oa|=32832;b.R|=49152;break}if((b.wa&15)>=b.aa[e]){b.oa|=32800;b.R|=49152;break}c=(b.wa>>4&511)*b.aa[e]+(b.wa&15);d=(b.R&48)<<12|b.Pb;f=65536-b.Rb&65535;ac(a,b.qa[e],c,d,f);return;case 2:if((b.wa>>4&511)>=b.hb[e])b.oa|=
32832,b.R|=49152;else if((b.wa&15)>=b.aa[e])b.oa|=32800,b.R|=49152;else{c=(b.wa>>4&511)*b.aa[e]+(b.wa&15);d=(b.R&48)<<12|b.Pb;f=65536-b.Rb&65535;a.bc(b.qa[e],c,d,f);return}}b.Qb=e<<13|b.Qb&8176|b.wa%9&15;K(a.b,20,5,144,function(){b.R=b.R&65534|128;return!!(b.R&64)})}l.dd=function(a,b,c,d,f){var e=this.A;e.Pb=d&65535;e.R=e.R&-49|d>>12&48;e.Rb=65536-f&65535;switch(a){case 1:e.oa|=33024;e.R|=49152;break;case 2:e.oa|=33792,e.R|=49152}K(this.b,20,5,144,function(){e.R=e.R&65534|128;return!!(e.R&64)})};
function bc(a){var b=a.C,c,d,f,e=b.N>>8&3;b.N&=-2;"undefined"===typeof b.qa[e]&&(b.qa[e]={cache:[],postProcess:a.ed,drive:e,blocksize:128,mapped:1,maxblock:b.hb[e]*b.aa[e],url:"rl"+e+".dsk"});switch(b.N>>1&7){case 2:b.$a&8&&(b.N&=63);b.$a=b.Kc[e]|b.fb&64;break;case 3:1==(b.ga&3)&&(b.fb=b.ga&4?b.fb+(b.ga&65408)&65408|b.ga<<2&64:b.fb-(b.ga&65408)&65408|b.ga<<2&64,b.ga=b.fb);break;case 4:b.$a=b.fb;break;case 5:if(b.ga>>6>=b.hb[e]){b.N|=37888;break}if((b.ga&63)>=b.aa[e]){b.N|=37888;break}c=(b.ga>>6)*
b.aa[e]+(b.ga&63);d=(b.Ua&63)<<16|b.Ib;f=65536-b.$a&65535;ac(a,b.qa[e],c,d,f);return;case 6:if(b.ga>>6>=b.hb[e])b.N|=37888;else if((b.ga&63)>=b.aa[e])b.N|=37888;else{c=(b.ga>>6)*b.aa[e]+(b.ga&63);d=(b.Ua&63)<<16|b.Ib;f=65536-b.$a&65535;a.bc(b.qa[e],c,d,f);return}}K(a.b,20,5,112,function(){b.N|=129;return!!(b.N&64)})}
l.ed=function(a,b,c,d,f){var e=this.C;e.Ib=d&65535;e.N=e.N&-49|d>>12&48;e.Ua=d>>16&63;e.ga=~~(c/e.aa[b.Na])<<6|c%e.aa[b.Na];e.fb=e.ga;e.$a=65536-f&65535;switch(a){case 1:e.N|=33792;break;case 2:e.N|=40960}K(this.b,20,5,112,function(){e.N|=129;return!!(e.N&64)})};function cc(a){a=a.F;a.T=2176;a.Fa=0;a.sa=[4544,4544,4544,4544,4544,4544,4544,4544];a.yb=[0,0,0,0,0,0,0,0];a.nb=a.zb=a.xb=a.eb=a.nc=0}
function dc(a,b){var c=a.F,d,f,e;c.T&=-16513;c.Fa&=-2049;c.sa[b]&=-1153;K(a.b,-1,0,172);"undefined"===typeof c.qa[b]&&(c.qa[b]={cache:[],postProcess:a.fd,drive:b,blocksize:256,mapped:0,maxblock:c.ec[0]*c.gb[0]*c.aa[0],url:"rp"+b+".dsk"});switch(c.T&63){case 5:c.dc[b]=c.Sa[b];c.T|=32896;c.sa[b]|=32896;c.nb|=1<<b;break;case 9:cc(a);break;case 19:c.sa[b]|=64;break;case 49:if(c.Sa[b]>=c.ec[0]||c.Ga[b]>>8>=c.gb[0]||(c.Ga[b]&255)>=c.aa[0]){c.yb[b]|=1024;c.T|=49152;break}d=(c.Sa[b]*c.gb[0]+(c.Ga[b]>>8))*
c.aa[0]+(c.Ga[b]&255);f=(c.eb&63)<<16|c.xb;e=65536-c.zb&65535;ac(a,c.qa[b],d,f,e);return;case 57:if(c.Sa[b]>=c.ec[0]||c.Ga[b]>>8>=c.gb[0]||(c.Ga[b]&255)>=c.aa[0])c.yb[b]|=1024,c.T|=49152;else{d=(c.Sa[b]*c.gb[0]+(c.Ga[b]>>8))*c.aa[0]+(c.Ga[b]&255);f=(c.eb&63)<<16|c.xb;e=65536-c.zb&65535;a.bc(c.qa[b],d,f,e);return}}K(a.b,3,5,172,function(){c.T=c.T&65534|128;c.sa[b]|=128;return!!(c.T&64)})}
l.fd=function(a,b,c,d,f){var e=this.F;e.zb=65536-f&65535;e.xb=d&65535;e.T=e.T&-769|d>>8&768;e.eb=d>>16&63;f=~~(c/e.aa[0]);d=~~(f/e.gb[0]);e.Ga[b.Na]=f%e.gb[0]<<8|c%e.aa[0];e.dc[b.Na]=e.Sa[b.Na]=d;e.nb|=1<<b.Na;c>=b.Wc-1&&(e.sa[b.Na]|=1024);switch(a){case 1:e.Fa|=512;e.T|=49152;break;case 2:e.Fa|=2048,e.T|=49152}K(this.b,20,5,172,function(){e.sa[b.Na]|=128;e.T=e.T&65534|128;return!!(e.T&64)})};
function ec(a,b,c,d,f,e){var g=~~((e+c.Va-1)/c.Va),h=new XMLHttpRequest;2048>g&&d+2048<c.Wc&&(g=2048);h.open("GET",c.url,!0);h.setRequestHeader("Range","bytes="+(d*c.Va<<1)+"-"+(((d+g)*c.Va<<1)-1));h.responseType="arraybuffer";h.onreadystatechange=function(){if(4==h.readyState){var g=b.bind(a),m,n,q,p;m=h.response;if(h.status&&206!=h.status||!m)c.jc(1,c,d,f,e);else{m=new Uint8Array(m);n=d;for(p=0;p<m.length;){if("undefined"===typeof c.cache[n])for(c.cache[n]=[],q=0;q<c.Va;q++)c.cache[n][q]=p<m.length?
m[p]&255|m[p+1]<<8&65280:0,p+=2;else p+=c.Va<<1;n++}g(c,d,f,e)}}};h.send(null)}function L(a,b,c,d,f){c&1?f?d=0<=d?d<<8&65280|b&255:b:a.b.L(4,122):0<=d?f&&(d=b&65280|d&255):d=b;return d}l.bc=function(a,b,c,d){for(var f;0<d;){if("undefined"===typeof a.cache[b]){ec(this,this.bc,a,b,c,d);return}for(f=0;f<a.Va&&0<d;f++){var e=a.Vc?fc(this.b,c):c;this.b.I.ob(e,a.cache[b][f]&65535);c+=2;--d}b++}a.jc(0,a,b,c,d)};
function ac(a,b,c,d,f){for(var e,g;0<f;){if("undefined"===typeof b.cache[c])for(b.cache[c]=[],e=0;e<b.Va;e++)b.cache[c][e]=0;for(e=0;e<b.Va&&0<f;e++){g=gc(a.b,b.Vc?fc(a.b,d):d);if(0>g){b.jc(2,b,c,d,f);return}b.cache[c][e]=g;d+=2;--f}c++}b.jc(0,b,c,d,f)}l.reset=function(){this.B.tb=this.B.tb&-120|20;this.f.va=0;this.f.ya=128;this.j.Za=0;this.A.R=128;this.C.N=128;cc(this)};
l.Jc=function(a,b,c){var d,f,e=this.b;switch(a&-64){case 4194240:switch(a&-2){case 4194300:0>b?d=e.cb&65280:(a&1&&(b<<=8),e.cb=b|255,d=0);break;case 4194298:if(0>b)d=e.mc;else{a&1&&(b<<=8);if(d=b&65024){f=d>>9;do d+=34;while(f>>=1)}e.mc=d;e.D|=2}break;case 4194294:if(70!==e.kb)return e.L(4,222);0>b?d=e.J:d=e.J=0;break;case 4194292:if(70!==e.kb)return e.L(4,224);d=1;break;case 4194290:if(70!==e.kb)return e.L(4,226);d=0;break;case 4194288:if(70!==e.kb)return e.L(4,228);d=61183;break;case 4194296:0<=
b&&!(a&1)&&(b&=255);case 4194286:case 4194284:case 4194282:case 4194280:case 4194278:case 4194276:case 4194274:case 4194272:if(70!==e.kb)return e.L(4,232);f=a-4194272>>1;0>b?d=e.ic[f]:(d=L(this,e.ic[f],a,b,c),0<=d&&(e.ic[f]=d));break;case 4194254:return a&1?e.P>>14&1?(0<=b&&(e.i[6]=b),d=e.i[6]):(0<=b&&(e.Aa[3]=b),d=e.Aa[3]):e.P>>14&0?(0<=b&&(e.i[6]=b),d=e.i[6]):(0<=b&&(e.Aa[1]=b),d=e.Aa[1]),d;case 4194252:case 4194250:case 4194248:return f=a&7,e.P&2048?(0<=b&&(e.i[f]=b),d=e.i[f]):(0<=b&&(e.Ra[f]=
b),d=e.Ra[f]),d;case 4194246:return a&1?(0<=b&&(e.i[7]=b),d=e.i[7]):e.P>>14&0?(0<=b&&(e.i[6]=b),d=e.i[6]):(0<=b&&(e.Aa[0]=b),d=e.Aa[0]),d;case 4194244:case 4194242:case 4194240:return f=a&7,e.P&2048?(0<=b&&(e.Ra[f]=b),d=e.Ra[f]):(0<=b&&(e.i[f]=b),d=e.i[f]),d;default:return e.J|=16,e.L(4,124)}break;case 4194176:f=a>>1&31;d=L(this,e.na[3][f],a,b,c);0<=d&&(e.na[3][f]=d,e.na[3][f&15]&=65295);break;case 4194112:var g=this.f;switch(a&-2){case 4194174:d=L(this,e.cc,a,b,c);0<=d&&(e.cc=d);break;case 4194172:d=
e.bb;d&65280&&(d=(d<<8|d>>8)&65535);break;case 4194168:0>b?d=this.B.od&65535:(d=L(this,this.B.data,a,b,c),0<=d&&(this.B.data=d));break;case 4194166:0<=b&&(b&127&&(g.Oc=0),g.ya&=-129,K(e,100,4,52,function(){g.ya|=128;return!!(g.ya&64)}));d=0;break;case 4194162:d=0;0>b&&(g.va&=-129,0<g.kc.length&&(d=g.kc.shift(),0<g.kc.length&&setTimeout(function(){g.va|=128;g.va&64&&K(e,40,4,48)},50)));break;case 4194160:0>b?d=g.va:(d=L(this,g.va,a,b,c),0<=d&&(g.va=g.va&128|d&-129));break;default:return e.J|=16,e.L(4,
126)}break;case 4194048:f=this.A;switch(a&-2){case 4194048:d=L(this,f.Qb,a,b,c);0<=d&&(f.Qb=d);break;case 4194050:d=L(this,f.oa,a,b,c);0<=d&&(f.oa=d);break;case 4194052:d=L(this,f.R,a,b,c);0<=b&&0<=d&&(f.R=d&-36993|f.R&36992,f.R&1&&Sb(this));break;case 4194054:d=L(this,f.Rb,a,b,c);0<=d&&(f.Rb=d);break;case 4194056:d=L(this,f.Pb,a,b,c);0<=d&&(f.Pb=d);break;case 4194058:d=L(this,f.wa,a,b,c);0<=d&&(f.wa=d);break;case 4194060:break;case 4194062:d=L(this,f.Cc,a,b,c);0<=d&&(f.Cc=d);break;default:return e.J|=
16,e.L(4,128)}break;case 4193728:var h=this.F;f=h.Fa&7;switch(a&-2){case 4193728:d=L(this,h.T,a,b,c);0<=b&&0<=d&&(h.eb=h.eb&60|d>>8&3,h.T=d&17279|h.T&34944|2048,d&1&&h.T&128?dc(this,f):192==(d&192)&&K(e,0,5,172));break;case 4193730:d=L(this,h.zb,a,b,c);0<=d&&(h.zb=d);break;case 4193732:d=L(this,h.xb,a,b,c);0<=d&&(h.xb=d&65534);break;case 4193734:d=L(this,h.Ga[f],a,b,c);0<=d&&(h.Ga[f]=d&7967);break;case 4193736:d=L(this,h.Fa,a,b,c);0<=d&&(h.Fa=d&63|h.Fa&65472,d&128&&cc(this));break;case 4193738:d=
h.sa[f];break;case 4193740:d=h.yb[f];break;case 4193742:d=L(this,h.nb,a,b,c);0<=d&&(h.nb=d&255);break;case 4193744:d=h.ld[f];break;case 4193746:d=L(this,h.Dc,a,b,c);0<=d&&(h.Dc=d);break;case 4193748:d=L(this,h.Ec[f],a,b,c);0<=d&&(h.Ec[f]=d&1023);break;case 4193750:d=8210;break;case 4193752:d=h.md[f];break;case 4193754:d=L(this,h.Fc[f],a,b,c);0<=d&&(h.Fc[f]=d);break;case 4193756:d=L(this,h.Sa[f],a,b,c);0<=d&&(h.Sa[f]=d&511);break;case 4193758:h.dc[f]=h.Sa[f];d=h.dc[f];break;case 4193760:d=h.jd[f];
break;case 4193762:d=h.kd[f];break;case 4193764:d=h.gd[f];break;case 4193766:d=h.hd[f];break;case 4193768:d=L(this,h.eb,a,b,c);0<=d&&(h.eb=d&63,h.T=h.T&-769|(d&3)<<8);break;case 4193770:d=L(this,h.nc,a,b,c);0<=d&&(h.nc=d);break;default:return e.J|=16,e.L(4,132)}break;case 4192512:f=this.C;switch(a&-2){case 4192512:d=L(this,f.N,a,b,c);0<=b&&0<=d&&(f.Ua=f.Ua&60|d>>4&3,f.N=f.N&-1023|d&1022,f.N&128||bc(this));break;case 4192514:d=L(this,f.Ib,a,b,c);0<=d&&(f.Ib=d&65534);break;case 4192516:d=L(this,f.ga,
a,b,c);0<=d&&(f.ga=d);break;case 4192518:d=L(this,f.$a,a,b,c);0<=d&&(f.$a=d);break;case 4192520:d=L(this,f.Ua,a,b,c);0<=d&&(f.Ua=d&63,f.N=f.N&-49|(f.Ua&3)<<4);break;default:return e.J|=16,e.L(4,134)}break;case 4191552:switch(a&-2){case 4191566:0>b?d=e.mb:(d=L(this,e.mb,a,b,c),0<=d&&(70!==e.kb&&(d&=-49),e.mb=d,e.ac[0]=d&4?15:7,e.ac[1]=d&2?15:7,e.ac[3]=d&1?15:7,e.$b&&(f=2,e.mb&16&&(f=1),this.B.tb=this.B.tb&-8|f)));break;default:return e.J|=16,e.L(4,136)}break;case 4191424:f=a>>1&31;d=L(this,e.na[0][f],
a,b,c);0<=d&&(e.na[0][f]=d,e.na[0][f&15]&=65295);break;case 4191360:f=a>>1&31;d=L(this,e.na[1][f],a,b,c);0<=d&&(e.na[1][f]=d,e.na[1][f&15]&=65295);break;case 4190400:case 4190336:if(70!==e.kb)return e.L(4,234);f=a>>2&31;d=e.Tb[f];a&2&&(d>>=16);d&=65535;0<=b&&(d=L(this,d,a,b,c),0<=d&&(e.Tb[f]=a&2?d<<16|e.Tb[f]&65535:e.Tb[f]&4294901760|d&65534));break;case 4188672:case 4188736:case 4188800:case 4188864:case 4188928:case 4188992:case 4189056:case 4189120:if(0>b)d=Mb[a>>1&255];else return e.J|=16,e.L(4,
138);break;default:return e.J|=16,e.L(4,142)}c&&0<=d&&(a&1?d>>=8:d&=255);"undefined"===typeof d&&console.log("panic(76)");return d};var hc={},Kb=(hc[65382]=[null,null,J.prototype.Zc,J.prototype.qd,"LKS"],hc[65392]=[null,null,J.prototype.bd,J.prototype.td,"RCSR"],hc[65396]=[null,null,J.prototype.cd,J.prototype.ud,"XCSR"],hc[65402]=[null,null,J.prototype.$c,J.prototype.rd,"MMR0"],hc[65534]=[null,null,J.prototype.ad,J.prototype.sd,"PSW"],hc);
Ia(function(){for(var a=E(document,"pdp11","device"),b=0;b<a.length;b++){var c=a[b],d=D(c),d=new J(d);bb(d,c)}});var ic;if(ub){var jc=new ArrayBuffer(2);(new DataView(jc)).setUint16(0,256,!0);ic=256===(new Uint16Array(jc))[0]}else ic=!1;var kc=ic;
function I(a,b,c,d,f){this.id=lc+=2;this.b=null;this.w=a;this.Vb=b;this.size=c||0;this.type=d||mc;this.j=d==nc;this.controller=null;yb(this);this.Xa=this.Pc=!1;if(c)if(f)this.controller=f,this.b=null,oc(this,f.Fb);else if(ub)this.C=new ArrayBuffer(c),this.F=new DataView(this.C,0,c),this.f=new Uint8Array(this.C,0,c),this.K=new Uint16Array(this.C,0,c>>1),this.b=new Int32Array(this.C,0,c>>2),oc(this,kc?pc:qc);else{this.b=Array(c>>2);for(a=0;a<this.b.length;a++)this.b[a]=0;oc(this,rc)}else oc(this)}
var mc=0,nc=2,Eb=4,Gb=["NONE","RAM","ROM","VID","H/W"],lc=0;
I.prototype={constructor:I,parent:null,save:function(){var a,b;if(this.controller)a=null;else if(ub)for(a=Array(this.size>>2),b=0;b<a.length;b++)a[b]=this.F.getInt32(b<<2,!0);else a=this.b;return a},restore:function(a){if(this.controller)return!a;if(a&&this.size==a.length<<2){var b;if(ub)for(b=0;b<a.length;b++)this.F.setInt32(b<<2,a[b],!0);else this.b=a;return this.Xa=!0}return!1},ib:function(a,b){b?this.B++||sc(this,tc,!1):this.M++||uc(this,tc,!1)},S:function(){this.G&&F(this.G,129)&&this.G.message("attempt to read invalid block %"+
t(this.w),!0);return 255},A:function(a,b){this.G&&F(this.G,129)&&this.G.message("attempt to write "+t(b,4,!0)+" to invalid block %"+t(this.w),!0)},W:function(a,b){return this.wb(a++,b++)|this.wb(a,b)<<8},H:function(a,b,c){this.Cb(a++,b&255,c++);this.Cb(a,b>>8,c)},ea:function(a){return this.b[a>>2]>>>((a&3)<<3)&255},ma:function(a){var b=a>>2;a=(a&3)<<3;var c=this.b[b]>>a;return 24>a?c&65535:c&255|(this.b[b+1]&255)<<8},Ba:function(a,b){var c=a>>2;a=(a&3)<<3;this.b[c]=this.b[c]&~(255<<a)|b<<a;this.Xa=
!0},La:function(a,b){var c=a>>2;a=(a&3)<<3;24>a?this.b[c]=this.b[c]&~(65535<<a)|b<<a:(this.b[c]=this.b[c]&16777215|b<<24,c++,this.b[c]=this.b[c]&-256|b>>8);this.Xa=!0},ca:function(a,b){if(this.G&&null!=this.w){var c=this.G;vc(c,this.w+a,1,c.W)&&c.pa(!0)}return this.Ob(a,b)},ia:function(a,b){if(this.G&&null!=this.w){var c=this.G;vc(c,this.w+a,2,c.W)&&c.pa(!0)}return this.lc(a,b)},ua:function(a,b,c){if(this.G&&null!=this.w){var d=this.G;vc(d,this.w+a,1,d.C)&&d.pa(!0)}this.j?this.A(a,b,c):this.Db(a,
b,c)},Da:function(a,b,c){if(this.G&&null!=this.w){var d=this.G;vc(d,this.w+a,2,d.C)&&d.pa(!0)}this.j?this.A(a,b,c):this.qc(a,b,c)},$:function(a){return this.f[a]},da:function(a){return this.f[a]},fa:function(a){return this.F.getUint16(a,!0)},la:function(a){return a&1?this.f[a]|this.f[a+1]<<8:this.K[a>>1]},ta:function(a,b){this.f[a]=b;this.Xa=!0},za:function(a,b){this.f[a]=b;this.Xa=!0},Ca:function(a,b){this.F.setUint16(a,b,!0);this.Xa=!0},Ia:function(a,b){a&1?(this.f[a]=b,this.f[a+1]=b>>8):this.K[a>>
1]=b;this.Xa=!0}};function yb(a,b,c){a.G=b;a.M=a.B=0;c&&((a.M=c.M)&&uc(a,tc,!1),(a.B=c.B)&&sc(a,tc,!1))}function wc(a,b){b?--a.B||(a.Cb=a.j?a.A:a.Db,a.Hc=a.j?a.H:a.qc):--a.M||(a.wb=a.Ob,a.Bc=a.lc)}function sc(a,b,c){c&&a.B||(a.Cb=!a.j&&b[1]||a.A,a.Hc=!a.j&&b[3]||a.H);if(c||void 0===c)a.Db=b[1]||a.A,a.qc=b[3]||a.H}function uc(a,b,c){c&&a.M||(a.wb=b[0]||a.S,a.Bc=b[2]||a.W);if(c||void 0===c)a.Ob=b[0]||a.S,a.lc=b[2]||a.W}function oc(a,b){b||(b=xc);uc(a,b,void 0);sc(a,b,void 0)}
var xc=[],rc=[I.prototype.ea,I.prototype.Ba,I.prototype.ma,I.prototype.La],tc=[I.prototype.ca,I.prototype.ua,I.prototype.ia,I.prototype.Da];if(ub)var qc=[I.prototype.$,I.prototype.ta,I.prototype.fa,I.prototype.Ca],pc=[I.prototype.da,I.prototype.za,I.prototype.la,I.prototype.Ia];
function yc(a,b){y.call(this,"CPU",a,yc,1);var c=a.multiplier||1;this.Da=a.cycles||b;this.ab=c;this.qb=Math.round(this.Da/1E4)/100;this.lb=this.qb*this.ab;this.u.ha=!1;this.u.oc=!1;this.u.Gb=a.autoStart;this.u.wc=!1;this.u.rb=!1;this.Lb=this.ia=0;this.Mb=a.csStart;this.ub=a.csInterval;this.vb=a.csStop;this.S=[];this.Zb=this.nd.bind(this);G(this)}C(yc);var zc=["power","reset"];l=yc.prototype;
l.Ya=function(a,b,c,d){this.B=a;this.I=b;this.G=d;for(b=0;b<zc.length;b++)(c=this.M[zc[b]])&&this.B.xa(null,zc[b],c);this.ta=null;a=Ac(a,"autoStart");null!=a&&(this.u.Gb="true"==a?!0:"false"==a?!1:!!a);G(this)};l.reset=function(){};l.save=function(){return null};l.restore=function(){return!1};
l.Qa=function(a,b){if(!b){if(a&&this.restore){Bc(this);if(!this.restore(a))return!1;Cc(this)}else this.reset();this.G?(a=this.G,a.g("Type ? for help with PDP11 Debugger commands"),a.Ha(),a.La&&(b=a.La,a.La=null,Dc(a,b))):this.g("No debugger detected")}M(this);return!0};l.Pa=function(a){return a?this.save():!0};l.Gb=function(){return this.u.Gb||!this.G&&void 0===this.M.run?(this.Ab(!0),!0):!1};l.yc=function(){return 0};
function Cc(a){void 0===a.Mb&&(a.Mb=0);void 0===a.ub&&(a.ub=-1);void 0===a.vb&&(a.vb=-1);a.u.rb=0<=a.Mb&&0<a.ub;a.u.rb&&(a.Lb=0,a.ia=a.Mb-a.fa)}function Ec(a,b){if(a.u.rb){var c=!1;a.Lb=a.Lb+a.yc()|0;a.ia-=b;0>=a.ia&&(a.ia+=a.ub,c=!0);0<=a.vb&&a.vb<=Fc(a)&&(a.ub=a.vb=-1,Cc(a),a.pa(),c=!0);c&&a.g(Fc(a)+" cycles: checksum="+t(a.Lb))}}
function Gc(a,b,c,d){if(a.M[b]){void 0===c&&(hb(a,"Value for "+b+" is invalid"),a.pa());var f=a.G&&a.G.ea||8;c=!a.u.ha||a.u.wc?8==f?r(c,d):t(c,d):"--------".substr(0,d||4);a.M[b].textContent!=c&&(a.M[b].textContent=c)}}
l.xa=function(a,b,c){var d=this;a=!1;switch(b){case "power":case "reset":this.M[b]=c;a=!0;break;case "run":this.M[b]=c;c.onclick=function(){var a;if(a=d.B)if(a=d.B,a.u.ja)a=!0;else{var b=null,c,h=$a(a.id);for(c=0;c<h.length&&(b=h[c],b===a||b.u.ready);c++);if(c==h.length)for(c=0;c<h.length&&(b=h[c],b===a||b.u.ja);c++);c==h.length&&(b=a);x("The "+b.type+" component ("+b.id+") is not "+(b.u.ready?"powered yet":"ready yet"+(b.Yb?" (waiting for notification)":""))+".");a=!1}a&&(d.u.ha?d.pa():d.Ab())};
a=!0;break;case "speed":this.M[b]=c;a=!0;break;case "setSpeed":this.M[b]=c,c.onclick=function(){Zc(d,d.ab<<1,!0)},c.textContent=this.lb.toFixed(2)+"Mhz",a=!0}return a};function $c(a,b,c){a.fa+=b;c&&(a.ea=a.b=0)}function ad(a,b){var c=1;b&&1<a.ab&&a.ca&&(c=a.ca/a.qb);a.Wb=Math.round(1E3/30);a.Ia=Math.floor(a.Da/30*c);b||(a.la=a.Ia);a.pb=0}function Fc(a){return a.fa+a.$+a.ea-a.b}function Bc(a){a.ca=0;a.Xb=0;a.fa=a.$=a.ea=a.b=0;Cc(a);Zc(a,1)}
function Zc(a,b,c){var d=!1;if(void 0!==b){.8>a.ca/a.lb?b=1:d=!0;a.ab=b;b=a.qb*a.ab;if(a.lb!=b){a.lb=b;b=a.lb.toFixed(2)+"Mhz";var f=a.M.setSpeed;f&&(f.textContent=b);a.g("target speed: "+b)}c&&a.B&&a.B.Ub()}$c(a,a.$);a.$=0;a.W=pa();a.da=0;ad(a);return d}function Nb(a,b){var c=a.S.length;a.S.push([-1,b]);return c}function Ob(a,b){var c;0<=b&&b<a.S.length&&0>a.S[b][0]&&(c=a.Da*a.ab/1E3*(1E3/60),a.S[b][0]=c)}
function bd(a,b){for(var c=a.S.length-1;0<=c;c--){var d=a.S[c];0>d[0]||b>d[0]&&(b=d[0])}return b}function cd(a,b){for(var c=a.S.length-1;0<=c;c--){var d=a.S[c];0>d[0]||(d[0]-=b,0>=d[0]&&(d[0]=-1,d[1]()))}}function dd(a){a.ea-=a.b;a.b=0}
l.nd=function(){if(this.u.ha){this.pb>=this.Da&&ad(this,!0);this.ua=0;this.Ca=pa();if(this.da){var a=this.Ca-this.da;a>this.Wb&&(this.W+=a,this.W>this.Ca&&(this.W=this.Ca))}try{do{var b=bd(this,this.u.rb?1:this.Ia);try{this.Bb(b)}catch(f){if("number"!=typeof f)throw f;}var c=this.ea-this.b;cd(this,c);this.ua+=c;this.$+=c;$c(this,0,!0);Ec(this,c);this.la-=c;if(0>=this.la){this.la+=this.Ia;15<=++this.Xb&&(this.B&&this.B.Ha(),this.Xb=0);break}}while(this.u.ha)}catch(f){this.pa();M(this);this.B&&this.B.stop(pa(),
Fc(this));hb(this,f.stack||f.message);return}if(this.u.ha){a=setTimeout;b=this.Zb;this.da=pa();c=this.Wb;this.ua&&(c=Math.round(c*this.ua/this.Ia));var c=c-(this.da-this.Ca),d=this.da-this.W;d&&(this.ca=Math.round(this.$/(10*d))/100,864E5<=d&&(this.fa=0,Zc(this)));if(0>c||this.ca<this.lb)-1E3>c&&(this.W-=c),c=0;this.pb+=this.ua;this.da+=c;a(b,c)}}};
l.Ab=function(a){if(gb(this))return!1;if(this.u.ha)return this.g(this.toString()+" busy"),!1;Zc(this);this.u.ha=!0;this.u.oc=!0;this.ta&&this.ta.start();var b=this.M.run;b&&(b.textContent="Halt");this.B&&(a&&this.B.Ub(!0),this.B.start(this.W,Fc(this)));M(this,!0);setTimeout(this.Zb,0);return!0};l.Bb=function(){return 0};
l.pa=function(a){if(this.u.ha){dd(this);$c(this,this.$);this.$=0;this.u.ha=!1;this.ta&&this.ta.stop();var b=this.M.run;b&&(b.textContent="Run");this.B&&this.B.stop(pa(),Fc(this));M(this)}this.u.complete=a};function M(a,b){a.B&&a.B.Ha(b)}
function ed(a){this.Xc=+a.model||1170;this.Tc=a.resetAddr||0;yc.call(this,a,6666667);this.Hb=0;this.decode=fd.bind(this);this.U=65536;this.V=32768;this.Y=65535;this.X=32768;this.P=15;this.i=[0,0,0,0,0,0,0,this.Tc];this.Ra=[0,0,0,0,0,0];this.Aa=[0,0,0,0];this.Ba=this.H=0;this.na=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[65535,65535,65535,65535,65535,65535,65535,65535,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];this.Tb=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.ic=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];this.C=this.f=this.A=this.j=this.La=this.D=0;this.kb=70;this.ma=-1;gd(this);this.u.complete=this.u.Nc=!1}C(ed,yc);l=ed.prototype;l.reset=function(){this.u.ha&&this.pa();gd(this);Bc(this);this.u.error=!1;this.parent.reset.call(this)};
function gd(a){a.cb=255;a.J=0;a.mc=0;a.K=0;a.bb=0;a.cc=0;a.mb=0;a.$b=0;a.za=0;a.ac=[7,7,7,7];a.F=[];a.D|=2;Pb(a)}function Pb(a){a.$b?(a.Eb=65536,a.ba=a.Rc):(a.Eb=0,a.ba=a.Qc)}l.yc=function(){return 0};l.save=function(){var a=new N(this);a.set(0,[]);a.set(1,[this.fa,this.ab]);a.set(2,Ib(this.I));return a.data()};
l.restore=function(a){var b=a[1];this.fa=b[1];Zc(this,b[3]);a:{b=this.I;a=a[2];var c;for(c=0;c<a.length-1;c+=2){var d=a[c],f=a[c+1];if(f&&f.length<b.K){for(var e=0,g=Array(b.K),h=0;h<f.length-1;)for(var k=f[h++],m=f[h++];k--;)g[e++]=m;f=g}e=b.O[d];if(!e||!e.restore(f)){x("Unable to restore memory block "+d);b=!1;break a}}b=!0}return b};
l.xa=function(a,b,c){switch(b){case "R0":case "R1":case "R2":case "R3":case "R4":case "R5":case "R6":case "R7":case "NF":case "ZF":case "VF":case "CF":case "PS":this.M[b]=c;this.Hb++;a=!0;break;default:a=this.parent.xa.call(this,a,b,c)}return a};
l.Ha=function(a){if(this.Hb&&(a||!this.u.ha||this.u.wc)){for(a=0;a<this.i.length;a++)Gc(this,"R"+a,this.i[a]);a=Qb(this);Gc(this,"PS",a);Gc(this,"NF",a&8?1:0,1);Gc(this,"ZF",a&4?1:0,1);Gc(this,"VF",a&2?1:0,1);Gc(this,"CF",a&1?1:0,1)}if(a=this.M.speed)a.textContent=this.u.ha&&this.ca?this.ca.toFixed(2)+"Mhz":"Stopped"};function hd(a){return a.U&65536?1:0}function id(a){return a.V&32768?2:0}function jd(a){return a.Y&65535?0:4}l.Oa=function(){return this.X&32768?8:0};
function kd(a){var b=ld(a,a.i[7]);a.i[7]=a.i[7]+2&65535;return b}function md(a,b){a.i[7]=b&65535}function K(a,b,c,d,f){for(var e=a.F.length;0<e--;)if(a.F[e].pd===d){0<e&&(a.F[e-1].Wa+=a.F[e].Wa);a.F.splice(e,1);break}if(0<=b){for(e=a.F.length;0<e--;){if(a.F[e].Wa>b){a.F[e].Wa-=b;break}b-=a.F[e].Wa}a.F.splice(e+1,0,{delay:b,priority:c<<5&224,vector:d,callback:f})}a.D|=2}function Qb(a){return a.P=a.P&63728|a.Oa()|jd(a)|id(a)|hd(a)}
function Rb(a,b){a.X=b<<12;a.Y=~b&4;a.V=b<<14;a.U=b<<16;if((b^a.P)&2048)for(var c=a.Ra.length;0<=--c;){var d=a.i[c];a.i[c]=a.Ra[c];a.Ra[c]=d}a.H=b>>14&3;c=a.P>>14&3;a.H!=c&&(a.Aa[c]=a.i[6],a.i[6]=a.Aa[a.H]);a.D|=2;a.P=b}function O(a,b){a.D&128||(a.X=a.Y=b,a.V=0)}function nd(a,b,c){a.D&128||(a.X=a.Y=a.U=b,a.V=c||0)}function od(a,b,c,d){a.D&128||(a.X=a.Y=a.U=b,a.V=(c^b)&(d^b))}function pd(a,b){a.D&128||(a.X=a.Y=a.U=b,a.V=a.X^a.U>>1)}function qd(a,b,c,d){a.D&128||(a.X=a.Y=a.U=b,a.V=(c^d)&(d^b))}
l.L=function(a){var b=!1;0>this.ma?this.ma=Qb(this):this.H||(a=4,b=!0);this.K&57344||(this.bb=63222,this.cc=a);this.H=0;var c=ld(this,a|65536),d=ld(this,a+2&65535|65536);Rb(this,d&-12289|this.ma>>2&12288);b&&(this.J|=4,this.i[6]=4);rd(this,this.ma);rd(this,this.i[7]);md(this,c);this.D&=-113;this.ma=-1;throw a;};function sd(a){var b=td(a),c=td(a)&-1793;a.P&49152&&(c=c&-225|a.P&63712);md(a,b);Rb(a,c);a.D&=-17}
function fc(a,b){var c=b>>13&31;31>c?a.mb&32&&(b=a.Tb[c]+(b&8190)&4194302,3932160<=b&&4186112>b&&console.log("panic(898)")):b|=4186112;return b}
function ud(a,b,c){var d,f,e,g=0;if(c&a.$b){d=b>>13&a.ac[a.H];f=a.na[a.H][d];e=(a.na[a.H][d+16]<<6)+(b&8191)&4194303;a.mb&16?3932160<=e&&4186112>e&&(e=fc(a,e&262143)):(e&=262143,253952<=e&&(e|=4186112));3932160>e&&(3915776<=e&&(a.J|=32,a.L(4,12)),e&1&&!(c&1)&&(a.J|=64,a.L(4,14)));switch(f&7){case 1:g=4096;case 2:f|=128;c&4&&(g=8192);break;case 4:g=4096;case 5:c&4&&(g=4096);case 6:f|=c&4?192:128;break;default:g=32768}32512!==(f&32520)&&(f&8?f&32512&&(b&8128)<(f>>2&8128)&&(g|=16384):(b&8128)>(f>>2&
8128)&&(g|=16384));a.na[a.H][d]=f;if(4194170!==e||a.H)a.za=a.H,a.Ba=d;g&&(g&57344&&(0<=a.ma&&(g|=128),a.K&57344||(a.K=a.K|g|a.za<<5|a.Ba<<1),a.L(168,16)),a.K&61440||!(4191360>e||4194239<e)||(a.K|=4096,a.K&512&&(a.D|=32)))}else e=b&65535,57344<=e?e|=4186112:e&1&&!(c&1)&&(a.J|=64,a.L(4,10));return e}function gc(a,b){return 4194304<=b?a.i[b-4194304]:0<=b?a.I.Ka(b):b}function ld(a,b){return gc(a,ud(a,b,2))}function td(a){var b=ld(a,a.i[6]|65536);a.i[6]=a.i[6]+2&65535;return b}
function rd(a,b){var c=a.i[6]-2&65535;a.i[6]=c;a.K&57344||(a.bb=a.bb<<8|246);!a.H&&c<=a.cb&&4<c&&(c<=a.cb-32?(a.J|=4,a.i[6]=4,a.L(4,18)):(a.J|=8,a.D|=4));c=ud(a,c|65536,4);a.I.ob(c,b&65535)}
function vd(a,b,c){var d,f,e=c&8?0:a.Eb,g=b>>3&7;b&=7;c&4?(a.j=g,a.f=b):(a.A=g,a.C=b);switch(g){case 0:return a.L(4,20),0;case 1:return 6===b&&!a.H&&c&4&&(a.i[6]<=a.cb||65534<=a.i[6])&&(a.i[6]<=a.cb-32||65534<=a.i[6]?(a.J|=4,a.i[6]=4,a.L(4,22)):(a.J|=8,a.D|=64)),a.b-=3,7===b?a.i[b]:a.i[b]|e;case 2:f=2;d=a.i[b];7!==b&&(d|=e,6>b&&c&1&&(f=1));a.b-=3;break;case 3:f=2;d=a.i[b];7!==b&&(d|=e);d=ld(a,d);d|=e;a.b-=7;break;case 4:f=-2;6>b&&c&1&&(f=-1);d=a.i[b]+f&65535;7!==b&&(d|=e);a.b-=4;break;case 5:f=-2;
d=a.i[b]-2&65535;7!==b&&(d|=e);d=ld(a,d)|e;a.b-=8;break;case 6:return d=kd(a),d=d+a.i[b]&65535|e,a.b-=6,d;case 7:return d=kd(a),d=d+a.i[b]&65535,d=ld(a,d|65536)|e,a.b-=10,d}a.i[b]=a.i[b]+f&65535;!e||a.K&57344||(a.bb=a.bb<<8|f<<3&248|b);6==b&&!a.H&&c&4&&0>=f&&(a.i[6]<=a.cb||65534<=a.i[6])&&(a.i[6]<=a.cb-32?(a.J|=4,a.i[6]=4,a.L(4,24)):(a.J|=8,a.D|=64));return d}l.Qc=function(a,b){return vd(this,a,b)};l.Rc=function(a,b){return ud(this,vd(this,a,b),b)};
function wd(a,b,c){b&56?(b=vd(a,b,2),c&65536||61440!==(a.P&61440)&&(b&=65535),a.H=a.P>>12&3,c=ld(a,b|c&65536),a.H=a.P>>14&3):(a.A=0,c=a.C=b&7,c=6!=c||(a.P>>2&12288)===(a.P&12288)?a.i[c]:a.Aa[a.P>>12&3]);return c}function xd(a,b,c,d){a.K&57344||(a.bb=22);b&56?(b=vd(a,b,4),c&65536||(b&=65535),a.H=a.P>>12&3,b=ud(a,b|c&65536,4),a.H=a.P>>14&3,a.I.ob(b,d&65535)):(a.j=0,c=a.f=b&7,6!=c||(a.P>>2&12288)===(a.P&12288)?a.i[c]=d:a.Aa[a.P>>12&3]=d)}
function P(a,b){b&56?a=gc(a,a.ba(b,2)):(a.A=0,a=a.i[a.C=b&7]);return a}function yd(a,b){b&56?(b=a.ba(b,3),a=a.I.sb(b)):(a.A=0,a=a.i[a.C=b&7]&255);return a}function Q(a,b,c,d){b&56?(b=a.ba(b,6),c=d.call(a,c,gc(a,b)),a.I.ob(b,c&65535)):(a.j=0,b=a.f=b&7,a.i[b]=d.call(a,c,a.i[b]))}function S(a,b,c,d){b&56?(b=a.La=a.ba(b,7),c=d.call(a,c,a.I.sb(b)),b&1&&a.b--,a.I.Sb(b,c&255)):(a.j=0,b=a.f=b&7,a.i[b]=a.i[b]&65280|d.call(a,c,a.i[b]))}
function zd(a,b,c){b&56?(b=a.ba(b,4),a.I.ob(b,c&65535)):(a.j=0,a.i[a.f=b&7]=c&65535);return c}function Ad(a,b,c,d){b&56?(d=a.ba(b,5),d&1&&a.b--,a.I.Sb(d,c&255)):(a.j=0,b=a.f=b&7,a.i[b]=c?d&1?c<<24>>24&65535:a.i[b]&-256|c&255:a.i[b]&-256);return c}function T(a,b,c){c&&(md(a,a.i[7]+(b<<24>>23)),a.b-=2);a.b-=3}
l.Bb=function(a){this.u.complete=!0;var b=this.u.Nc=this.G&&Bd(this.G),c=a?this.u.oc?0:1:-1;this.u.oc=!1;this.ea=this.b=a;do{if(b){if(Cd(this.G,this.i[7],c)){this.pa();break}c=1}if(this.D&&(this.D&112&&(this.D&32?this.L(168,28):this.D&64?this.L(4,30):this.D&16&&this.L(12,32),this.D&=-113),this.D&7))if(this.D&2){this.D&=-3;a=null;for(var d=this.mc&224,f=this.F.length;0<=--f;){if(0<this.F[f].Wa){this.F[f].Wa--;this.D|=2;break}if(this.F[f].tc){if(!this.F[f].tc()){this.F.splice(f,1);continue}this.F[f].tc=
null}this.F[f].Yc>d&&(d=this.F[f].Yc,a=this.F[f],this.F.splice(f,1))}d>(this.P&224)&&(this.D&4&&(this.i[7]=this.i[7]+2&65535,this.D&=-5),a?this.L(a.pd,26):this.L(160,26))}else this.D&1&&this.D++;this.K&57344||(this.bb=0,this.cc=this.i[7]);this.D=this.D&7|this.P&16;this.decode(kd(this))}while(0<this.b);return this.u.complete?this.ea-this.b:void 0===this.u.complete?0:-1};Ia(function(){for(var a=E(document,"pdp11","cpu"),b=0;b<a.length;b++){var c=a[b],d=D(c),d=new ed(d);bb(d,c)}});
function Dd(a,b){var c=b+a;od(this,c,a,b);return c&65535}function Ed(a,b){var c=b+a;od(this,c<<8,a<<8,b<<8);return c&255}function Fd(a,b){a=b<<1;pd(this,a);return a&65535}function Gd(a,b){a=b<<1;pd(this,a<<8);return a&255}function Hd(a,b){a=b&32768|b>>1|b<<16;pd(this,a);return a&65535}function Id(a,b){a=b&2048|b>>1|b<<8;pd(this,a<<8);return a&255}function Jd(a,b){a=b&~a;O(this,a);return a}function Kd(a,b){a=b&~a;O(this,a<<8);return a}function Ld(a,b){a|=b;O(this,a);return a}
function Md(a,b){a|=b;O(this,a<<8);return a}function Nd(a,b){a=~b|65536;nd(this,a);return a&65535}function Od(a,b){a=~b|256;nd(this,a<<8);return a&255}function Pd(a,b){a=b-a;this.D&128||(this.X=this.Y=a,this.V=b&(b^a));return a&65535}function Qd(a,b){a=b-a;var c=a<<8;b<<=8;this.D&128||(this.X=this.Y=c,this.V=b&(b^c));return a&255}function Rd(a,b){a=b+a;this.D&128||(this.X=this.Y=a,this.V=a&(b^a));return a&65535}
function Sd(a,b){a=b+a;var c=a<<8;this.D&128||(this.X=this.Y=c,this.V=c&(b<<8^c));return a&255}function Td(a,b){a=-b;nd(this,a,a&b&32768);return a&65535}function Ud(a,b){a=-b;nd(this,a<<8,(a&b&128)<<8);return a&255}function Vd(a,b){a=b<<1|this.U>>16&1;pd(this,a);return a&65535}function Wd(a,b){a=b<<1|this.U>>16&1;pd(this,a<<8);return a&255}function Xd(a,b){a=(this.U&65536|b)>>1|b<<16;pd(this,a);return a&65535}function Yd(a,b){a=((this.U&65536)>>8|b)>>1|b<<8;pd(this,a<<8);return a&255}
function Zd(a,b){var c=b-a;qd(this,c,a,b);return c&65535}function $d(a,b){var c=b-a;qd(this,c<<8,a<<8,b<<8);return c&255}function ae(a,b){this.D&128||(this.X=this.Y=b&65280,this.V=this.U=0);return(b<<8|b>>8)&65535}function be(a,b){a^=b;O(this,a);return a&65535}
function ce(a){var b=P(this,a);a=a>>6&7;var c=this.i[a];c&32768&&(c|=4294901760);this.U=this.V=0;b&=63;if(b&32)b=64-b,16<b&&(b=16),this.U=c<<17-b,c>>=b;else if(b)if(16<b)this.V=c,c=0;else{this.U=c<<=b;var d=c>>15&65535;d&&65535!==d&&(this.V=32768)}this.i[a]=c&65535;this.X=this.Y=c;this.b-=(this.A?6:7)+b}
function de(a){var b=P(this,a);a=a>>6&7;var c=this.i[a]<<16|this.i[a|1];this.U=this.V=0;b&=63;if(b&32){b=64-b;32<b&&(b=32);var d=c>>b-1;this.U=d<<16;d>>=1;c&2147483648&&(d|=4294967295<<32-b)}else b?(d=c<<b-1,this.U=d>>15,d<<=1,32<b&&(b=32),(c>>=32-b)&&4294967295!==(c|4294967295<<b&4294967295)&&(this.V=32768)):d=c;this.i[a]=d>>16&65535;this.i[a|1]=d&65535;this.X=d>>16;this.Y=d>>16|d;this.b-=(this.A?6:7)+b}function U(a){a&1&&(this.U=0);a&2&&(this.V=0);a&4&&(this.Y=1);a&8&&(this.X=0);this.b-=5}
function ee(a){var b=P(this,a);if(b){a=a>>6&7;var c=this.i[a]<<16|this.i[a|1];this.U=this.V=0;b&32768&&(b|=-65536);var d=~~(c/b);-32768<=d&&32767>=d?(this.i[a]=d&65535,this.i[a|1]=c-d*b&65535,this.Y=d>>16|d,this.X=d>>16):(this.V=32768,this.Y=d>>15|d,this.X=c>>16,-1===b&&65534===this.i[a]&&(this.i[a]=this.i[a|1]=1));this.b-=53}else this.Y=this.X=0,this.V=32768,this.U=65536,this.b-=7}var fe=[0,7,7,10,7,11,9,13];function ge(a){var b=this.b;md(this,vd(this,a,8));this.b=b-fe[this.A]}
var he=[0,14,14,17,14,18,16,20];function ie(a){var b=this.b,c=vd(this,a,8);a=a>>6&7;rd(this,this.i[a]);this.i[a]=this.i[7];md(this,c);this.b=b-he[this.A]}var je=[3,9,9,13,10,14,12,16,4,9,9,13,10,14,13,17],Ee=[7,13,13,17,14,18,17,21];function Fe(a){var b=P(this,a);a=a>>6&7;b&32768&&(b|=-65536);var c=this.i[a];c&32768&&(c|=-65536);b=~~(b*c);this.i[a]=b>>16&65535;this.i[a|1]=b&65535;this.D&128||(this.X=b>>16,this.Y=this.X|b,this.V=0,this.U=-32768>b||32767<b?65536:0);this.b-=23}
function Ge(){this.b-=5}function V(a){a&1&&(this.U=65536);a&2&&(this.V=32768);a&4&&(this.Y=0);a&8&&(this.X=32768);this.b-=5}function He(a){var b=(a&448)>>6;if(this.i[b]=this.i[b]-1&65535)md(this,this.i[7]-((a&63)<<1)),this.b+=1;this.b-=6}function Ie(a){Q(this,a,0,ae);this.b-=this.j?9:3+(7==this.f?2:0)}function Je(a){Q(this,a,P(this,(a&448)>>6),be);this.b-=this.j?9:3+(7==this.f?2:0)}function X(){this.L(8,6)}function fd(a){Ke[a>>12].call(this,a)}
var Ke=[function(a){Le[a>>8&15].call(this,a)},function(a){var b=P(this,a>>6),c=this.b;O(this,zd(this,a,b));this.b=c-je[(this.A?8:0)+this.j]+(7!=this.f||this.j?0:2)},function(a){var b=P(this,a>>6),c=this.A,d=this.C;a=P(this,a);qd(this,b-a,a,b);this.b-=this.A?4+(d&&6<=this.C?1:0):(c?4:3)+(7==this.C?2:0)},function(a){var b=P(this,a>>6),c=this.A,d=this.C;a=P(this,a);O(this,b&a);this.b-=this.A?4+(d&&6<=this.C?1:0):(c?4:3)+(7==this.C?2:0)},function(a){Q(this,a,P(this,a>>6),Jd);this.b-=this.j?9+(this.C&&
6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},function(a){Q(this,a,P(this,a>>6),Ld);this.b-=this.j?9+(this.C&&6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},function(a){Q(this,a,P(this,a>>6),Dd);this.b-=this.j?9+(this.C&&6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},function(a){Me[a>>8&15].call(this,a)},function(a){Ne[a>>8&15].call(this,a)},function(a){var b=yd(this,a>>6);O(this,Ad(this,a,b,1)<<8);this.b-=this.j?9+(this.C&&6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},function(a){var b=yd(this,a>>6)<<
8,c=this.A,d=this.C;a=yd(this,a)<<8;qd(this,b-a,a,b);this.b-=this.A?4+(d&&6<=this.C?1:0):(c?4:3)+(7==this.C?2:0)},function(a){var b=yd(this,a>>6),c=this.A,d=this.C;a=yd(this,a);O(this,(b&a)<<8);this.b-=this.A?4+(d&&6<=this.C?1:0):(c?4:3)+(7==this.C?2:0)},function(a){S(this,a,yd(this,a>>6),Kd);this.b-=this.j?9+(this.C&&6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},function(a){S(this,a,yd(this,a>>6),Md);this.b-=this.j?9+(this.C&&6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},function(a){Q(this,a,P(this,
a>>6),Zd);this.b-=this.j?9+(this.C&&6<=this.f?1:0):(this.A?5:3)+(7==this.f?2:0)},X],Le=[function(a){Oe[a>>4&15].call(this,a)},function(a){T(this,a,!0)},function(a){T(this,a,!jd(this))},function(a){T(this,a,jd(this))},function(a){T(this,a,!this.Oa()==!id(this))},function(a){T(this,a,!this.Oa()!=!id(this))},function(a){T(this,a,!jd(this)&&!this.Oa()==!id(this))},function(a){T(this,a,jd(this)||!this.Oa()!=!id(this))},ie,ie,function(a){Pe[a>>6&3].call(this,a)},function(a){Qe[a>>6&3].call(this,a)},function(a){Re[a>>
6&3].call(this,a)},function(a){Se[a>>6&3].call(this,a)},X,X],Pe=[function(a){nd(this,zd(this,a,0));this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,0,Nd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,1,Rd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,1,Pd);this.b-=this.j?9:3+(7==this.f?2:0)}],Qe=[function(a){Q(this,a,0,Td);this.b-=this.j?11:6},function(a){Q(this,a,hd(this)?1:0,Dd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,hd(this)?1:0,Zd);this.b-=this.j?
9:3+(7==this.f?2:0)},function(a){a=P(this,a);nd(this,a);this.b-=this.A?4:3+(7==this.C?2:0)}],Re=[function(a){Q(this,a,0,Xd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,0,Vd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,0,Hd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){Q(this,a,0,Fd);this.b-=this.j?9:3+(7==this.f?2:0)}],Se=[function(a){a=this.i[7]+((a&63)<<1)&65535;var b=ld(this,a|65536);md(this,this.i[5]);this.i[6]=a+2&65535;this.i[5]=b;this.b-=8},function(a){a=wd(this,
a,0);rd(this,a);O(this,a);this.b-=11},function(a){var b=td(this),c=this.b;xd(this,a,0,b);O(this,b);this.b=c-Ee[this.j]},function(a){O(this,zd(this,a,this.Oa?65535:0));this.b-=this.j?9:3+(7==this.f?2:0)}],Oe=[function(a){Te[a&15].call(this,a)},X,X,X,ge,ge,ge,ge,function(a){if(a&8)this.L(8,6);else{var b=td(this);a&=7;md(this,this.i[a]);this.i[a]=b;this.b-=9}},function(a){a&8?(this.P&49152||(this.P=this.P&-2017|(a&7)<<5,this.D|=1),this.b-=5):this.L(8,6)},function(a){Ue[a&15].call(this,a)},function(a){Ve[a&
15].call(this,a)},Ie,Ie,Ie,Ie],Te=[function(){this.P&49152?(this.J|=128,this.L(4,3)):dd(this);this.b-=7},function(){this.D|=4;this.i[7]=this.i[7]+-2&65535;this.b-=3},function(){sd(this);this.D|=this.P&16;this.b-=13},function(){this.L(12,1);this.b-=5},function(){this.L(16,4);this.b-=25},function(){this.P&49152||(gd(this),this.I.reset());this.b-=667},function(){sd(this);this.b-=13},X,X,X,X,X,X,X,X,X],Ue=[Ge,function(){this.U=0;this.b-=5},function(){this.V=0;this.b-=5},U,function(){this.Y=1;this.b-=
5},U,U,U,function(){this.X=0;this.b-=5},U,U,U,U,U,U,U],Ve=[Ge,function(){this.U=65536;this.b-=5},function(){this.V=32768;this.b-=5},V,function(){this.Y=0;this.b-=5},V,V,V,function(){this.X=32768;this.b-=5},V,V,V,V,V,V,V],Me=[Fe,Fe,ee,ee,ce,ce,de,de,Je,Je,X,X,X,X,He,He],Ne=[function(a){T(this,a,!this.Oa())},function(a){T(this,a,this.Oa())},function(a){T(this,a,!hd(this)&&!jd(this))},function(a){T(this,a,hd(this)||jd(this))},function(a){T(this,a,!id(this))},function(a){T(this,a,id(this))},function(a){T(this,
a,!hd(this))},function(a){T(this,a,hd(this))},function(){this.L(24,2);this.b-=25},function(){this.L(28,5);this.b-=5},function(a){We[a>>6&3].call(this,a)},function(a){Xe[a>>6&3].call(this,a)},function(a){Ye[a>>6&3].call(this,a)},function(a){Ze[a>>6&3].call(this,a)},X,X],We=[function(a){nd(this,Ad(this,a,0));this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,0,Od);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,1,Sd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,1,Qd);this.b-=
this.j?9:3+(7==this.f?2:0)}],Xe=[function(a){S(this,a,0,Ud);this.b-=this.j?11:6},function(a){S(this,a,hd(this)?1:0,Ed);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,hd(this)?1:0,$d);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){a=yd(this,a);nd(this,a<<8);this.b-=this.A?4:3+(7==this.C?2:0)}],Ye=[function(a){S(this,a,0,Yd);this.b-=this.j?9+(this.La&1):3+(7==this.f?2:0)},function(a){S(this,a,0,Wd);this.b-=this.j?9:3+(7==this.f?2:0)},function(a){S(this,a,0,Id);this.b-=this.j?9+(this.La&1):
3+(7==this.f?2:0)},function(a){S(this,a,0,Gd);this.b-=this.j?9:3+(7==this.f?2:0)}],Ze=[X,function(a){a=wd(this,a,65536);rd(this,a);O(this,a);this.b-=11},function(a){var b=td(this),c=this.b;xd(this,a,65536,b);O(this,b);this.b=c-Ee[this.j]},X];
function $e(a){y.call(this,"ROM",a,$e);this.f=null;this.C=a.addr;this.j=a.size;this.F=a.writable;this.B=a.alias;this.A=a.file;this.H=ca(this.A);if(this.A){a=this.A;var b=da(this.H);"json"!=b&&"hex"!=b&&(a=fa()+"/api/v1/dump?file="+this.A+"&format=bytes&decimal=true");var c=this;ra(a,null,!0,function(a,b,e){af(c,a,b,e)})}}C($e);$e.prototype.Ya=function(a,b,c,d){this.I=b;this.b=c;this.G=d;bf(this)};
$e.prototype.Qa=function(){if(this.Ma){if(this.G){var a=this.G,b=this.id,c=this.C,d=this.j,f=this.Ma,e=[],g;for(g in f){var h=f[g];"number"==typeof h&&(f[g]=h={o:h});var k=h.o,m=h.a;if(void 0!==k){var n=e,k=[k>>>0,g],q=oa(n,k,a.uc);0>q&&n.splice(-(q+1),0,k)}m&&(h.a=m.replace(/''/g,'"'))}a.F.push({wd:b,w:c,Uc:d,Ma:f,rc:e})}delete this.Ma}return!0};$e.prototype.Pa=function(){return!0};
function af(a,b,c,d){if(d)a.ra("Unable to load system ROM (error "+d+": "+b+")");else{Za(a.vc,b,c);var f;if("["==c.charAt(0)||"{"==c.charAt(0))try{var e,g,h=eval("("+c+")");if(e=h.bytes)a.f=e;else if(e=h.words)for(a.f=Array(2*e.length),g=f=0;f<e.length;f++)a.f[g++]=e[f]&255,a.f[g++]=e[f]>>8&255;else if(e=h.data)for(a.f=Array(4*e.length),g=f=0;f<e.length;f++)a.f[g++]=e[f]&255,a.f[g++]=e[f]>>8&255,a.f[g++]=e[f]>>16&255,a.f[g++]=e[f]>>24&255;else a.f=h;a.Ma=h.symbols;if(!a.f.length){x("Empty ROM: "+
b);return}if(1==a.f.length){x(a.f[0]);return}}catch(k){a.ra("ROM data error: "+k.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.f=Array(b.length),f=0;f<b.length;f++)a.f[f]=aa(b[f],16);bf(a)}}
function bf(a){if(!fb(a))if(!a.A)G(a);else if(a.f&&a.I){a.j||(a.j=a.f.length);if(a.f.length!=a.j)hb(a,"ROM size ("+t(a.f.length,8,!0)+") does not match specified size ("+t(a.j,8,!0)+")");else{var b;b=a.C;if(Db(a.I,b,a.j,a.F?1:nc)){var c;for(c=0;c<a.f.length;c++){var d=a.I,f=b+c;d.O[(f&d.j)>>>d.Z].Db(f&d.f,a.f[c]&255,f)}b=!0}else b=!1;if(b){b=[];"number"==typeof a.B?b.push(a.B):null!=a.B&&a.B.length&&(b=a.B);for(c=0;c<b.length;c++){for(var e=a,d=b[c],f=e.I,g=e.j,h=[],k=e.C>>>f.Z;0<g&&k<f.O.length;)h.push(f.O[k++]),
g-=f.Ea;f=e.I;e=e.j;g=0;for(d>>>=f.Z;0<e&&d<f.O.length;){k=h[g++];if(!k)break;f.O[d++]=k;e-=f.Ea}}delete a.f}}G(a)}}Ia(function(){for(var a=E(document,"pdp11","rom"),b=0;b<a.length;b++){var c=a[b],d=D(c),d=new $e(d);bb(d,c)}});function cf(a){y.call(this,"RAM",a,cf);this.B=a.addr;this.j=a.size;this.f=!1}C(cf);l=cf.prototype;l.Ya=function(a,b,c,d){this.I=b;this.b=c;this.G=d;G(this)};l.Qa=function(a,b){b||this.reset();return!0};l.Pa=function(a){return a?this.save():!0};
l.reset=function(){!this.f&&this.j&&Db(this.I,this.B,this.j,1)&&(this.f=!0);this.f||x("No RAM allocated")};l.save=function(){return null};l.restore=function(){return!0};Ia(function(){for(var a=E(document,"pdp11","ram"),b=0;b<a.length;b++){var c=a[b],d=D(c),d=new cf(d);bb(d,c)}});function df(a){y.call(this,"Keyboard",a,df,65536);G(this)}C(df);df.prototype.xa=function(){return!1};df.prototype.Ya=function(a,b,c,d){this.B=a;this.b=c;this.G=d;this.ta=null};
Ia(function(){for(var a=E(document,"pdp11","keyboard"),b=0;b<a.length;b++){var c=a[b],d=D(c),d=new df(d);bb(d,c)}});function ef(a){y.call(this,"Debugger",a,ef);this.ea=a.base||16;this.Da=!1;this.$=this.Ca=this.H=0;this.da=!1;this.A=-1;this.j=[];this.ia={}}C(ef);var ff={"||":0,"&&":1,"|":2,"^":3,"&":4,"!=":5,"==":5,">=":6,">":6,"<=":6,"<":6,">>>":7,">>":7,"<<":7,"-":8,"+":8,"%":9,"/":9,"*":9};ef.prototype.zc=function(){return-1};ef.prototype.Ac=function(){};
function gf(a,b,c,d){if(c)if(b){0>a.A&&a.j.length&&(a.A=0);if(0>a.A||b!=a.j[a.A])a.j.splice(0,0,b),a.A=0;a.A--}else a.da?b="end":b=a.j[a.A+1];a=[];if(b){b=b.toLowerCase().replace(/""/g,"'");c=0;var f=null;d=d||";";for(var e=0;e<=b.length;e++){var g=b.charAt(e);if('"'==g||"'"==g)f?g==f&&(f=null):f=g;else if(g==d&&!f||!g)a.push(na(b.substring(c,e))),c=e+1}}return a}
function hf(a,b,c){for(c=c||-1;c--&&b.length;){var d=b.pop();if(2>a.length)return!1;var f=a.pop(),e=a.pop();switch(d){case "*":d=e*f;break;case "/":if(!f)return!1;d=e/f;break;case "%":if(!f)return!1;d=e%f;break;case "+":d=e+f;break;case "-":d=e-f;break;case "<<":d=e<<f;break;case ">>":d=e>>f;break;case ">>>":d=e>>>f;break;case "<":d=e<f?1:0;break;case "<=":d=e<=f?1:0;break;case ">":d=e>f?1:0;break;case ">=":d=e>=f?1:0;break;case "==":d=e==f?1:0;break;case "!=":d=e!=f?1:0;break;case "&":d=e&f;break;
case "^":d=e^f;break;case "|":d=e|f;break;case "&&":d=e&&f?1:0;break;case "||":d=e||f?1:0;break;default:return!1}a.push(d|0)}return!0}
function jf(a,b,c){var d;if(b){b=kf(a,b);for(var f=0,e=!1,g=b,h=[],k=[],m=b.split(/(\|\||&&|\||^|&|!=|==|>=|>>>|>>|>|<=|<<|<|-|\+|%|\/|\*)/);f<m.length;){var n=m[f++],q=n.length,n=na(n);if(!n){e=!0;break}n=lf(a,n,null,!1===c);if(void 0===n){e=!0;c=!1;break}h.push(n);if(f==m.length)break;var n=m[f++],p=n.length;k.length&&ff[n]<ff[k[k.length-1]]&&hf(h,k,1);k.push(n);b=b.substr(q+p)}hf(h,k)&&1==h.length||(e=!0);e?c&&a.g("error parsing '"+g+"' at character "+(g.length-b.length)):(d=h.pop(),c&&mf(a,null,
d))}return d}function kf(a,b){for(var c,d=a.Da?"(":"{",f=a.Da?")":"}",e=new RegExp(a.Da?"\\((.*?)\\)":"\\{(.*?)\\}");(c=b.match(e))&&!(0<=c[1].indexOf(d));){var g=jf(a,c[1]);b=b.replace(d+c[1]+f,null!=g?Y(a,g):"undefined")}for(;(c=b.match(/\[(.*?)]/))&&!(0<=c[1].indexOf("["));)b=b.replace("["+c[1]+"]","unimplemented");for(;c=b.match(/\$([a-z]+)/i);){d=null;switch(c[1].toLowerCase()){case "ops":d=a.$-a.Ca}if(null==d)break;b=b.replace(c[0],d.toString())}return b}
function lf(a,b,c,d){var f;null!=b?(f=a.zc(b),0<=f?f=a.Ac(f):(f=a.ia[b],null==f&&(f=aa(b,a.ea))),null!=f||d||a.g("invalid "+(c?c:"value")+": "+b)):d||a.g("missing "+(c||"value"));return f}
function mf(a,b,c){var d,f=!1;if(void 0!==c){f=!0;d=c;var e=0,g="";if(!e||4<e)e=4;for(var h=0;h<e;h++){g&&(g=","+g);var k=d&255,m=8,n="";m?32<m&&(m=32):m=32;if(null==k||isNaN(k))for(;0<m--;)n="?"+n;else for(;0<m--;)n=(k&1?"1":"0")+n,k>>=1;g=n+g;d>>=8}d=t(c,0,!0)+" "+c+". "+r(c,0,!0)+" "+("0b"+g)}a.g((null!=b?b+": ":"")+d);return f}function nf(a,b){if(b)return mf(a,b,a.ia[b]);var c=0;for(b in a.ia)mf(a,b,a.ia[b]),c++;return 0<c}
function Y(a,b,c,d){switch(a.ea){case 8:a=r(b,3*c);break;case 10:a=b.toString();break;default:a=t(b,2*c)}d&&"0"==a.charAt(0)&&(a=a.replace(/^0+([0-9A-F]+)$/i,"$1"));return a}
function of(a){ef.call(this,a);this.Da=!0;this.S=Z();this.qb=Z();this.ca=Z();this.F=[];this.f=this.W=this.C=[];pf(this);this.ua=0;qf(this);this.Ia={};rf(this,a.messages);this.La=a.commands;var b=this;window?void 0===window.pdp11&&(window.pdp11=function(a){return Dc(b,a)}):void 0===global.pdp11&&(global.pdp11=function(a){return Dc(b,a)})}C(of,ef);
var sf={"?":"help/print","a [#]":"assemble","b [#]":"breakpoint",c:"clear output","d [#]":"dump memory","e [#]":"edit memory","g [#]":"go [to #]",h:"halt","if":"eval expression","int [#]":"request interrupt",k:"stack trace",ln:"list nearest symbol(s)",m:"messages",p:"step over",print:"print expression",r:"dump/set registers",reset:"reset machine",s:"set options","t [#]":"trace","u [#]":"unassemble",v:"print version","var":"assign variable"},tf="NONE ADC ADCB ADD ASL ASLB ASR ASRB BCC BCS BEQ BGE BGT BHI BIC BICB BIS BISB BIT BITB BLE BLOS BLT BMI BNE BPL BPT BR BVC BVS CCC CLC CLCN CLCV CLCVN CLCVZ CLCZ CLCZN CLN CLR CLRB CLV CLVN CLVZ CLVZN CLZ CLZN CMP CMPB COM COMB DEC DECB INC INCB HALT JMP JSR MARK MFPD MFPI MFPS MOV MOVB MTPD MTPI MTPS NEG NEGB NOP RESET ROL ROLB ROR RORB RTI RTS SBC SBCB SCC SEC SECN SECV SECVN SECVZ SECZ SECZN SEN SEV SEVN SEVZ SEVZN SEZ SEZN SUB SWAB SXT TST TSTB WAIT MUL DIV ASH ASHC XOR SOB EMT TRAP SPL IOT RTT MFPT".split(" "),
uf={61440:{4096:[62,4032,63],8192:[47,4032,63],12288:[18,4032,63],16384:[14,4032,63],20480:[16,4032,63],24576:[3,4032,63],36864:[63,4032,63],40960:[48,4032,63],45056:[19,4032,63],49152:[15,4032,63],53248:[17,4032,63],57344:[94,4032,63]},65024:{2048:[57,448,63],28672:[100,63,448],29184:[101,63,448],29696:[102,63,448],30208:[103,63,448],30720:[104,448,63],32256:[105,448,8192]},65280:{256:[27,4096],512:[24,4096],768:[10,4096],1024:[11,4096],1280:[22,4096],1536:[12,4096],1792:[20,4096],32768:[25,4096],
33024:[23,4096],33280:[13,4096],33536:[21,4096],33792:[28,4096],34048:[29,4096],34304:[8,4096],34560:[9,4096],34816:[106],35072:[107]},65472:{64:[56,63],192:[95,63],2560:[39,63],2624:[49,63],2688:[53,63],2752:[51,63],2816:[67,63],2880:[1,63],2944:[77,63],3008:[97,63],3072:[73,63],3136:[71,63],3200:[6,63],3264:[4,63],3328:[58,24576],3392:[60,63],3456:[65,63],3520:[96,63],35328:[40,63],35392:[50,63],35456:[54,63],35520:[52,63],35584:[68,63],35648:[2,63],35712:[78,63],35776:[98,63],35840:[74,63],35904:[72,
63],35968:[7,63],36032:[5,63],36096:[66,63],36160:[59,63],36224:[64,63],36288:[61,63]},65528:{128:[76,7],152:[108,12288]},65535:{0:[55],1:[99],2:[75],3:[26],4:[109],5:[70],6:[110],7:[111],160:[69],161:[31],162:[41],163:[33],164:[45],165:[36],166:[43],167:[35],168:[38],169:[32],170:[42],171:[34],172:[46],173:[37],174:[44],175:[30],176:[69],177:[80],178:[88],179:[82],180:[92],181:[85],182:[90],183:[84],184:[87],185:[81],186:[89],187:[83],188:[93],189:[86],190:[91],191:[79]}};l=of.prototype;
l.Ya=function(a,b,c,d){this.I=b;this.b=c;this.B=a;(a=Ac(a,"messages"))&&rf(this,a);this.Hb=uf;vf(this,function(a){a:{var b=d.I.O,c=a[0],f=a=0,k=b.length;if(c){a=d.ba(wf(d,c));if(-1===a){d.g("invalid address: "+c);break a}f=a>>>d.I.Z;k=1}d.g("blockid   physical   blockaddr   used    size    type");d.g("--------  ---------  ----------  ------  ------  ----");for(var c=-1,m=0;k--;){var n=b[f];n.type==c?m++||d.g("..."):(c=n.type,m=Gb[c],n&&d.g(t(n.id,8)+"  %"+t(f<<d.I.Z,8)+"  %%"+t(n.w,8)+"  "+t(n.Vb,
4,!0)+"  "+t(n.size,4,!0)+"  "+m),c!=mc&&(c=-1),m=0);a+=d.I.Ea;f++}}});G(this)};
l.xa=function(a,b,c){var d=this;switch(b){case "debugInput":return this.ta=this.M[b]=c,c.onkeydown=function(a){var b;if(13==a.keyCode)b=c.value,c.value="",Dc(d,b,!0);else if(27==a.keyCode)c.value=b="";else if(38==a.keyCode?(b=null,d.A<d.j.length-1&&(b=d.j[++d.A])):40==a.keyCode&&(0<d.A?b=d.j[--d.A]:(b="",d.A=-1)),null!=b){var f=b.length;c.value=b;c.setSelectionRange(f,f)}null!=b&&a.preventDefault&&a.preventDefault()},!0;case "debugEnter":return this.M[b]=c,Ca(c,function(){if(d.ta){var a=d.ta.value;
d.ta.value="";Dc(d,a,!0);return!0}return!1}),!0;case "step":return this.M[b]=c,Ca(c,function(a){var b=!1;eb(d,!0)||(db(d,!0),b=d.Bb(a?1:0),db(d,!1));return b}),!0}return!1};l.Ub=function(){this.ta&&this.ta.focus()};l.ba=function(a){a=a&&a.w;null==a&&(a=-1);return a};l.sb=function(a,b){var c=255,d=this.ba(a,!1,1);-1!==d&&(c=this.I,c=c.O[(d&c.j)>>>c.Z].Ob(d&c.f,d),b&&xf(a,b));return c};l.Ka=function(a,b){var c=65535,d=this.ba(a,!1,2);-1!==d&&(c=Hb(this.I,d),b&&xf(a,b));return c};
l.Sb=function(a,b,c){var d=this.ba(a,!0,1);if(-1!==d){var f=this.I;f.O[(d&f.j)>>>f.Z].Db(d&f.f,b&255,d);c&&xf(a,c);M(this.b,!0)}};l.ob=function(a,b,c){var d=this.ba(a,!0,2);if(-1!==d){var f=this.I,e=d&f.f,g=(d&f.j)>>>f.Z;e!=f.f?f.O[g].qc(e,b&65535,d):(f.O[g++].Db(e,b&255,d),f.O[g&f.B].Db(0,b>>8&255,d+1));c&&xf(a,c);M(this.b,!0)}};function Z(a){return{w:a,Ja:!1}}function yf(a){return[a.w,a.Ja]}function zf(a){return{w:a[0],Ja:a[1]}}
function wf(a,b,c){var d;c=(c?a.S:a.qb).w;if(void 0!==b){d=b=kf(a,b);var f;if(d.match(/^[a-z_][a-z0-9_]*$/i))for(d=d.toUpperCase(),c=0;c<a.F.length;c++){var e=a.F[c].Ma[d];if(void 0!==e){d=e.o;void 0!==d&&(f=Z(d));break}}if(d=f)return d;c=jf(a,b,void 0)}null!=c&&(d=Z(c));return d}function Af(a,b,c){c&&(c=c.match(/(['"])(.*?)\1/))&&(b.Lc=gf(a,b.Gc=c[2]))}function xf(a,b){null!=a.w&&(a.w+=b||1)}
function rf(a,b){a.G=a;a.ka=a.Mc=536870912;a.za=null;a.Ba=[];b=gf(a,b.replace("keys","key").replace("kbd","keyboard"),!1,"|");if(b.length)for(var c in H){var d;a:if(d=void 0,Array.prototype.indexOf)d=b.indexOf(c,d);else{d=d||0;0>d&&(d+=b.length);0>d&&(d=0);for(var f=b.length;d<f;d++)if(d in b&&b[d]===c)break a;d=-1}0<=d&&(a.ka|=H[c],a.g(c+" messages enabled"))}}function vf(a,b){for(var c in H)if(64==H[c]){a.Ia[c]=b;break}}
l.zc=function(a){var b=-1;a=a.toUpperCase();switch(a){case "SP":b=6;break;case "PC":b=7;break;default:"R"==a.charAt(0)&&(b=+a.charAt(1),0>b||7<b)&&(b=-1)}return b};function Bf(a){return 6>a?"R"+a:6==a?"SP":"PC"}l.Ac=function(a){var b;0<=a&&(8>a?b=this.b.i[a]:16>a?b=this.b.Ra[a-8]:20>a?b=this.b.Aa[a-16]:20==a&&(b=Qb(this.b)));return b};
l.message=function(a,b){b&&(a+=" at "+Y(this,Z(this.b.i[7]).w));this.ka&1073741824?this.Ba.push(a):this.za&&a==this.za||(this.za=a,this.ka&-2147483648&&(this.pa(),a+=" (cpu halted)"),this.g(a),this.b&&(a=this.b,dd(a),a.la=0,M(a)))};
function qf(a){var b;if(Bd(a)){if(!a.K||!a.K.length){a.K=Array(1E3);for(b=0;b<a.K.length;b++)a.K[b]=Z();a.ma=0;a.g("instruction history buffer allocated")}if(!a.la||!a.la.length)for(a.la=Array(256),b=0;b<a.la.length;b++)a.la[b]=[b,0]}else a.K&&a.K.length&&a.g("instruction history buffer freed"),a.ma=0,a.K=[],a.la=[]}l.Ab=function(a){if(!Cf(this))return!1;this.b.Ab(a);return!0};
l.Bb=function(a,b,c){if(!Cf(this))return!1;this.H=0;a||Bd(this)&&Cd(this,this.b.i[7],0);try{a=bd(this.b,a);var d=this.b.Bb(a);0<d&&(cd(this.b,a),this.H+=d,$c(this.b,d,!0),Ec(this.b,d),this.$++)}catch(f){"number"!=typeof f&&(this.H=0,hb(this.b,f.stack||f.message))}!1!==c&&M(this.b);this.Ha(b||!1);return 0<this.H};l.pa=function(a){this.b&&this.b.pa(a)};l.Ha=function(a){void 0===a&&(a=!0);this.S=Z(this.b.i[7]);a&&1!=this.fa?Df(this):Ef(this)};
function Cf(a){var b;if(b=a.b&&fb(a.b))b=a.b,b.u.ja?b=!0:(b.g(b.toString()+" not powered"),b=!1);return b&&!a.b.u.ha?!gb(a.b):!1}l.Qa=function(a,b){return!b&&(this.reset(!0),a&&this.restore&&!this.restore(a))?!1:!0};l.Pa=function(a,b){b&&this.g(a?"suspending":"shutting down");return a?this.save():!0};l.reset=function(a){qf(this);this.$=this.Ca=0;this.za=null;this.H=0;this.S=Z(this.b.i[7]);this.u.ha=!1;Ff(this);a||this.Ha()};
l.save=function(){var a=new N(this);a.set(0,yf(this.S));a.set(1,yf(this.ca));a.set(2,[this.j,this.da,this.ka]);a.set(3,this.F);return a.data()};l.restore=function(a){var b=0;void 0!==a[2]&&(this.S=zf(a[b++]),this.ca=zf(a[b++]),this.j=a[b][0],"string"==typeof this.j&&(this.j=[this.j]),this.da=a[b][1],this.ka|=a[b][2]);a[3]&&(this.F=a[3]);return!0};l.start=function(a,b){this.fa||this.g("running");this.u.ha=!0;this.Wb=a;this.Xb=b};
l.stop=function(a,b){if(this.u.ha){this.u.ha=!1;this.H=b-this.Xb;if(!this.fa){b="stopped";if(this.H){a-=this.Wb;var c=0<a?Math.round(1E3*this.H/a):0;b+=" (";Bd(this)&&(b+=this.$+" opcodes, ",this.Ca-=this.$,this.$=0);b+=this.H+" cycles, "+a+" ms, "+c+" hz)"}else F(this,-2147483648)&&(b+=" (use the 't' command to execute blocked faults)");this.g(b)}this.Ha(!0);this.Ub();Ff(this,this.b.i[7])}};function Bd(a){return 1<a.f.length||!!a.ua}
function Cd(a,b,c){var d=a.b;if(0<c&&(a.ua&&!--a.ua||vc(a,b,1,a.f)))return!0;0<=c&&a.la.length&&(a.$++,null!=Hb(a.I,b)&&(b=a.K[a.ma],b.w=d.i[7],b.Ja=!1,++a.ma==a.K.length&&(a.ma=0)));return!1}function pf(a){var b,c;a.f=["bp"];if(a.W)for(b=1;b<a.W.length;b++){c=a.W[b];var d=a.I;c=a.ba(c);wc(d.O[c>>>d.Z],!1)}a.W=["br"];if(a.C)for(b=1;b<a.C.length;b++)c=a.C[b],d=a.I,c=a.ba(c),wc(d.O[c>>>d.Z],!0);a.C=["bw"];a.pb=0}
l.ib=function(a,b,c){var d=!0;c||Gf(this,a,b,!1,!0);if(a!=this.f){var f=this.ba(b);if(-1===f)this.g("invalid address: "+Y(this,b.w)),d=!1;else{var e=this.I;e.O[f>>>e.Z].ib(f&e.f,a==this.C)}}d&&(a.push(b),c?b.Ja=!0:(Hf(this,a,a.length-1,"set"),qf(this)));return d};function Gf(a,b,c,d,f){var e=!1;c=a.ba(c);for(var g=1;g<b.length;g++){var h=b[g];if(c==a.ba(h)&&(!d||h.Ja)){e=!0;h.Ja||f||Hf(a,b,g,"cleared");b.splice(g,1);b!=a.f&&(d=a.I,wc(d.O[c>>>d.Z],b==a.C));h.Ja||qf(a);break}}return e}
function If(a,b){for(var c=1;c<b.length;c++)Hf(a,b,c);return b.length-1}function Hf(a,b,c,d){c=b[c];a.g(b[0]+" "+Y(a,c.w)+(d?" "+d:c.Gc?' "'+c.Gc+'"':""))}function Ff(a,b){if(void 0!==b)vc(a,b,1,a.f,!0),a.fa=0;else for(b=1;b<a.f.length;b++){var c=a.f[b];if(c.Ja){if(!Gf(a,a.f,c,!0))break;b=0}}}
function vc(a,b,c,d,f){var e=!1;if(!a.pb++)for(var g=1;!e&&g<d.length;g++){var h=d[g];if(!f||h.Ja)for(var k=a.ba(h),m=0;m<c;m++)if(b+m==k){var n,e=!0;h.Ja&&(Gf(a,d,h,!0),f=!0);if(n=h.Lc){for(var e=!1,q=0;q<n.length;q++)if(!Jf(a,n[q],!0)){if(n[q].indexOf("if")){e=!0;break}for(var p=q+1;p<n.length&&n[p].indexOf("else");p++)q++;if(p==n.length){e=!0;break}}a.b.u.ha||(e=!0)}if(e){f||Hf(a,d,g,"hit");break}}}a.pb--;return e}
function Kf(a,b,c,d){var f=Z(b.w),e=a.Ka(b,2),g,h;for(h in a.Hb)if(g=a.Hb[h][e&h])break;g||(g=[0]);for(var k=h="",m=tf[g[0]],n=g.length-1,q=1;q<=n;q++){var p=g[q];if(void 0!==p){var v;v=a;var w=p,p=b,z="",u=w&61440;if(4096==u)p=p.w+((e&255)<<24>>23)&65535,z=Y(v,p);else if(8192==u)p=p.w-((e&63)<<1)&65535,z=Y(v,p);else if(12288==u)z=Y(v,e&7,1);else if(24576==u)z=Y(v,e&63,1);else if(u=e&w,w&4032&&(u>>=6,w>>=6),w&63)switch(w=u&7,u&56){case 0:z=Bf(w);break;case 8:z="@"+Bf(w);break;case 16:7>w?z="("+Bf(w)+
")+":(u=v.Ka(p,2),z="#"+Y(v,u,0,!0));break;case 24:7>w?z="@("+Bf(w)+")+":(u=v.Ka(p,2),z="@#"+Y(v,u,0,!0));break;case 32:z="-("+Bf(w)+")";break;case 40:z="@-("+Bf(w)+")";break;case 48:u=v.Ka(p,2);z=Y(v,u,0,!0)+"("+Bf(w)+")";7==w&&(z=[z,Y(v,u+p.w&65535)]);break;case 56:u=v.Ka(p,2),z="@"+Y(v,u)+"("+Bf(w)+")",7==w&&(z=[z,Y(v,u+p.w&65535)])}v=z;if(!v||!v.length){h="INVALID";break}"string"!=typeof v&&(k=v[1],v=v[0]);0<h.length&&(h+=",");h+=v||"???"}}e="";g=Y(a,f.w)+":";if(-1!==f.w&&-1!==b.w){do if(e+=" "+
Y(a,a.Ka(f,2)),null==f.w)break;while(f.w!=b.w)}g+=ma(e,24);g+=ma(m,5);h&&(g+=" "+h);if(c||k)g=ma(g,60)+";"+(c||""),g=a.b.u.rb?g+("cycles="+Fc(a.b).toString()+" cs="+t(a.b.Lb)):g+(null!=d?"="+d.toString():""),k&&(g+=" @"+k);return g}function Lf(a,b){switch(b){case "N":a=a.b.Oa();break;case "Z":a=jd(a.b);break;case "V":a=id(a.b);break;case "C":a=hd(a.b);break;default:a=0}return b.charAt(0)+(a?"1":"0")+" "}
function Mf(a,b){var c="",d=a.b;8>b?(c=Bf(b),c+="="+Y(a,d.i[b])):13>b?c="A"+(b-8)+"="+Y(a,d.Ra[b-8]):16<=b&&20>b?c="S"+(b-16)+"="+Y(a,d.Aa[b-16]):20==b&&(c="PS="+Y(a,Qb(d)));c&&(c+=" ");return c}function Nf(a){var b,c="";for(b=0;6>b;b++)c+=Mf(a,b);c=c+"\n"+(Mf(a,6)+Mf(a,7)+Mf(a,20));return c+=Lf(a,"T")+Lf(a,"N")+Lf(a,"Z")+Lf(a,"V")+Lf(a,"C")}l.uc=function(a,b){return a[0]>b[0]?1:a[0]<b[0]?-1:0};
function Of(a,b,c){var d=[],f=a.ba(b)>>>0;for(b=0;b<a.F.length;b++){var e=a.F[b],g=e.w>>>0,h=e.Uc;if(f>=g&&f<g+h){f=oa(e.rc,[f-g],a.uc);0<=f?Pf(a,b,f,d):c&&(f=~f,Pf(a,b,f-1,d),Pf(a,b,f,d));break}}return d}function Pf(a,b,c,d){var f={},e=a.F[b].rc,g=0,h=null;0<=c&&c<e.length&&(g=e[c][0],h=e[c][1]);h&&(f=a.F[b].Ma[h],h="."==h.charAt(0)?null:f.l||h);d.push(h);d.push(g);d.push(f.a);d.push(f.c)}
function Qf(a,b){var c=b.match(/^\s*([A-Z_]?[A-Z0-9_]*)\s*(=?)\s*(.*)$/i);if(c){if(!c[1])return nf(a)||a.g("no variables"),!0;if(!c[2])return nf(a,c[1]);if(!c[3])return delete a.ia[c[1]],!0;b=jf(a,c[3]);return void 0!==b?(a.ia[c[1]]=b,!0):!1}a.g("invalid assignment:"+b);return!1}
function Rf(a,b,c){var d=null;if(b=wf(a,b,!0)){a.ba(b);var f=Of(a,b,!0);if(f.length){var e,g;f[0]&&(g="",(e=b.w-f[1])&&(g=" + "+t(e,4,!0)),e=f[0]+" ("+Y(a,f[1])+")"+g,c&&a.g(e),d=e);4<f.length&&f[4]&&(g="",(e=f[5]-b.w)&&(g=" - "+t(e,4,!0)),e=f[4]+" ("+Y(a,f[5])+")"+g,c&&a.g(e),d||(d=e))}else c&&a.g("no symbols")}return d}
function Df(a,b){var c;if(b&&"?"==b[1])a.g("register commands:"),a.g("\tr\tdump registers"),a.g("\trx [#]\tset flag or register x to [#]");else{var d=a.b;null==c&&(c=!0);if(b&&1<b.length){var f=b[1],e=f.indexOf("=");if(0<e)b=f.substr(e+1),f=f.substr(0,e);else if(2<b.length)b=b[2];else{a.g("missing value for "+b[1]);return}e=jf(a,b);if(void 0===e)return;b=f.toUpperCase();switch(b){case "SP":case "R6":d.i[6]=e&65535;break;case "PC":case "R7":md(d,e);a.S=Z(d.i[7]);break;case "N":d.X=e?32768:0;break;
case "Z":d.Y=e?0:1;break;case "V":d.V=e?32768:0;break;case "C":d.U=e?65536:0;break;default:if("R"==b.charAt(0)&&(b=+b.charAt(1),0<=b&&6>b)){d.i[b]=e&65535;break}a.g("unknown register: "+f);return}M(d);a.g("updated registers:")}a.g(Nf(a));c&&(a.S=Z(d.i[7]),Ef(a,Y(a,a.S.w)))}}function Sf(a,b){b=na(b);var c=b.match(/^(['"])(.*?)\1$/);c?a.g(c[2]):jf(a,b,!0)}
function Tf(a,b,c){var d="t"!=b;c=lf(a,c,null,!0)||1;var f=1==c?0:1;"tc"==b&&(f=c,c=1);Ba(c,function(){return db(a,!0)&&a.Bb(f,d,!1)},function(){M(a.b);db(a,!1)})}
function Ef(a,b,c,d){if(b=wf(a,b,!0)){void 0===d&&(d=1);var f=256;if(void 0!==c){d=wf(a,c,!0);if(!d||d.w<b.w)return;f=d.w-b.w;if(256<f){a.g("range too large");return}d=-1}c=0;for(var e;0<f&&d--;){e=eb(a,!1)||a.fa?a.H:null;var g=null!=e?"cycles":null,h=Of(a,b),k=b.w;if(h[0]&&d&&(!c&&d||0>h[0].indexOf("+"))){var m=h[0]+":";h[2]&&(m+=" "+h[2]);a.g(m)}h[3]&&(g=h[3],e=null);e=Kf(a,b,g,e);a.g(e);a.S=b;f-=b.w-k;c++}}}
function Jf(a,b,c){var d=!0;try{b.length&&"end"!=b?c||a.g(">> "+b):(a.da&&(a.g("ended assemble at "+Y(a,a.ca.w)),a.S=a.ca,a.da=!1),b="");var f=b.charAt(0);if('"'==f||"'"==f)return!0;a.za=null;if(fb(a)&&0<b.length){a.da&&(b="a "+Y(a,a.ca.w)+" "+b);var e=b.replace(/ +/g," ").split(" ");if(e&&e.length)for(var g=e[0],h=g.charAt(0),k=1;k<g.length;k++){var m=g.charAt(k);if("?"==h||"r"==h||"a">m||"z"<m){e[0]=g.substr(k);e.unshift(g.substr(0,k));break}}switch(e[0].charAt(0)){case "a":var n=wf(a,e[1],!0);
if(n)if(a.ca=n,void 0===e[2])a.g("begin assemble at "+Y(a,n.w)),a.da=!0,M(a.b);else{var q;a.g("not supported yet");q=[];if(q.length){for(var p=0;p<q.length;p++)a.Sb(n,q[p],1);a.g(Kf(a,a.ca))}}break;case "b":a:{var v=e[0],w=e[1],z=b;if("?"==w)a.g("breakpoint commands:"),a.g("\tbp [a]\tset exec breakpoint at addr [a]"),a.g("\tbr [a]\tset read breakpoint at addr [a]"),a.g("\tbw [a]\tset write breakpoint at addr [a]"),a.g("\tbc [a]\tclear breakpoint at addr [a]"),a.g("\tbl\tlist all breakpoints"),a.g("\tbn [n]\tbreak after [n] instruction(s)");
else{var u=v.charAt(1);if("l"==u){var Hc;Hc=0+If(a,a.f);Hc+=If(a,a.W);(Hc+=If(a,a.C))||a.g("no breakpoints")}else if("n"==u)a.ua=lf(a,w),a.g("break after "+a.ua+" instruction(s)");else if(void 0===w)a.g("missing breakpoint address");else{var R=Z();if("*"!=w&&(R=wf(a,w,!0),!R))break a;"c"==u?null==R.w?(pf(a),a.g("all breakpoints cleared")):Gf(a,a.f,R)||Gf(a,a.W,R)||Gf(a,a.C,R)||a.g("breakpoint missing: "+Y(a,R.w)):null!=R.w&&(Af(a,R,z),"p"==u?a.ib(a.f,R):"r"==u?a.ib(a.W,R):"w"==u?a.ib(a.C,R):a.g("unknown breakpoint command: "+
u))}}}break;case "c":a.jb&&(a.jb.value="");break;case "d":a:{var Ka,La=e[0],ga=e[1],xa=e[2],lg=e[3];if("?"==ga){var Ma="";for(Ka in H)a.Ia[Ka]&&(Ma&&(Ma+=","),Ma+=Ka);Ma+=",state,symbols";a.g("dump memory commands:");a.g("\tdb [a] [#]    dump # bytes at address a");a.g("\tdw [a] [#]    dump # words at address a");a.g("\tdd [a] [#]    dump # dwords at address a");a.g("\tdh [#] [#]    dump # instructions from history");Ma.length&&a.g("dump extension commands:\n\t"+Ma)}else if("state"==ga){var ke=Uf(a.B,
!0);"console"==xa?console.log(ke):(a.jb&&(a.jb.value=""),a.g(ke))}else if("symbols"==ga)for(var Ic=0;Ic<a.F.length;Ic++){var Jc=a.F[Ic],Na;for(Na in Jc.Ma)if("."!=Na.charAt(0)){var le=Jc.Ma[Na].o;if(void 0!==le){var me=Jc.Ma[Na].l;me&&(Na=me);a.g(Y(a,le)+" "+Na)}}}else{if("d"==La){for(Ka in H)if(e[1]==Ka){var ne=a.Ia[Ka];ne?(e.shift(),e.shift(),ne(e)):a.g("no dump registered for "+ga);break a}ga||(La=a.Zb||"db")}else a.Zb=La;if("dh"==La){var oe=ga,pe=xa,qe="",re=0,ba=a.ma,ha=a.K;if(ha.length){var W=
+oe||a.Eb,ib=+pe||10;isNaN(W)?W=ib:qe="more ";W>ha.length&&(a.g("note: only "+ha.length+" available"),W=ha.length);ba-=W;0>ba&&(null==ha[ha.length-1].w?(W=ba+W,ba=0):ba+=ha.length);var Kc=[];"call"==pe&&(ib=1E5,Kc=["CALL"]);for(void 0!==oe&&a.g(W+" instructions earlier:");0<ib&&ba!=a.ma;){var se=ha[ba++];if(null==se.w)break;var jb=Z(se.w),mg=W--,te=Kf(a,jb,"history",mg);(!Kc.length||0<=te.indexOf(Kc[0]))&&a.g(te);jb.hc&&(ba+=jb.hc,ib-=jb.hc,W-=jb.hc);ba>=ha.length&&(ba=0);a.Eb=W;re++;ib--}}re||(a.g("no "+
qe+"history available"),a.Eb=void 0)}else{var Tb=wf(a,ga);if(Tb){var Ub=0;xa&&("l"==xa.charAt(0)&&(xa=xa.substr(1)||lg),Ub=lf(a,xa)>>>0,65536<Ub&&(Ub=65536));for(var kb="",Oa="dd"==La?4:"dw"==La?2:1,Vb=Oa*Ub||128,ng=Vb+15>>4||1;ng--&&0<Vb;){var lb=0,Lc=0,mb,Mc="",ue="",ga=Y(a,Tb.w);for(mb=4==Oa?16:a.ea;0<mb&&0<Vb;mb--){var Wb=a.sb(Tb,1),lb=lb|Wb<<(Lc++<<3);Lc==Oa&&(Mc+=8==a.ea?r(lb,3*Oa):t(lb,2*Oa),Mc+=1==Oa?9==mb?"-":" ":"  ",lb=Lc=0);ue+=32<=Wb&&128>Wb?String.fromCharCode(Wb):".";Vb--}kb&&(kb+=
"\n");kb+=ga+"  "+Mc+(0==mb?" "+ue:"")}kb&&a.g(kb);a.qb=Tb}}}}break;case "e":if("else"==e[0])break;var Pa,Nc,Oc,Pc,Qc=e[0],Rc=e[1];"eb"==Qc?(Pa=1,Nc=255,Oc=a.sb,Pc=a.Sb):"e"==Qc||"ew"==Qc?(Pa=2,Nc=65535,Oc=a.Ka,Pc=a.ob):Rc=null;if(null==Rc)a.g("edit memory commands:"),a.g("\teb [a] [...]  edit bytes at address a"),a.g("\tew [a] [...]  edit words at address a");else{var Xb=wf(a,Rc);if(Xb)for(var Yb=2;Yb<e.length;Yb++){var nb=jf(a,e[Yb]);if(void 0===nb){a.g("unrecognized value: "+e[Yb]);break}nb&~Nc&&
a.g("warning: "+t(nb)+" exceeds "+Pa+"-byte value");var og=Oc.call(a,Xb);a.g("changing "+Y(a,Xb.w)+" from "+Y(a,og,Pa)+" to "+Y(a,nb,Pa));Pc.call(a,Xb,nb,Pa)}}break;case "g":a:{var ve=e[1],pg=b;if(void 0!==ve){var Sc=wf(a,ve,!0);if(!Sc)break a;Af(a,Sc,pg);a.ib(a.f,Sc,!0)}a.Ab(!0)||c||a.g("cpu busy or unavailable, run command ignored")}break;case "h":a.u.ha?(c||a.g("halting"),a.pa()):eb(a,!0)||c||a.g("already halted");break;case "i":if("if"==e[0]){var Tc;var ob=b.substr(2),ob=na(ob);jf(a,ob)?(c||a.g("true: "+
ob),Tc=!0):(c||a.g("false: "+ob),Tc=!1);Tc||(d=!1)}break;case "k":var qg=e[0];if("?"==e[1])a.g("stack trace commands:"),a.g("\tk\tshow frame addresses"),a.g("\tks\tshow symbol information");else{var Uc=0,we=Z(),pb=Z(a.b.i[6]);for(a.g("stack trace for "+Y(a,pb.w));10>Uc;){for(var ya=null,rg=256;65536>pb.w>>>0;){we.w=a.Ka(pb,2);if(null==pb.w||!rg--)break;for(var sg=a,Zb=we,xe=null,qb=Zb.w,ye=qb,Vc=1;6>=Vc&&qb;Vc++){if(2<Vc){Zb.w=qb;var $b=Kf(sg,Zb);if(0<=$b.indexOf("JSR")){var ze=$b.indexOf(" ");if(qb+
($b.indexOf(" ",ze+1)-ze-1)/2==ye){xe=$b;break}}}qb--}Zb.w=ye;if(ya=xe)break}if(!ya||null==ya)break;var Ae=null;if("ks"==qg){var Be=ya.match(/[0-9A-F]+$/);Be&&(Ae=Rf(a,Be[0]))}ya=ma(ya,50)+"  ;"+(Ae||"stack="+Y(a,pb.w));a.g(ya);Uc++}Uc||a.g("no return addresses found")}break;case "l":"ln"==e[0]&&Rf(a,e[1],!0);break;case "m":a:{var ia,ja=null,B=e[1];"?"==B&&(B=void 0);if(void 0!==B){var ua=0;if("all"==B)ua=1878917119,B=null;else if("on"==B)ja=!0,B=null;else if("off"==B)ja=!1,B=null;else{"keys"==B&&
(B="key");"kbd"==B&&(B="keyboard");for(ia in H)if(B==ia){ua=H[ia];ja=!!(a.ka&ua);break}if(!ua){a.g("unknown message category: "+B);break a}}if(ua)if("on"==e[2])a.ka|=ua,ja=!0;else if("off"==e[2]&&(a.ka&=~ua,ja=!1,1073741824==ua)){for(var Wc=0;Wc<a.Ba.length;Wc++)a.g(a.Ba[Wc]);a.Ba=[]}}var tg=0,rb="";for(ia in H)if(!B||B==ia){var ug=!!(a.ka&H[ia]);if(null===ja||ja==ug)rb&&(rb+=","),++tg%10||(rb+="\n\t"),"key"==ia&&(ia="keys"),rb+=ia}void 0===B&&a.g("message commands:\n\tm [category] [on|off]\tturn categories on/off");
a.g((null!==ja?ja?"messages on:  ":"messages off: ":"message categories:\n\t")+(rb||"none"));qf(a)}break;case "p":if("print"==e[0]){Sf(a,b.substr(5));break}var vg="pr"==e[0]?1:0;if(a.fa)a.g("step in progress");else{var Ce=Z(a.b.i[7]);a.sb(Ce);a.fa?(a.ib(a.f,Ce,!0),a.Ab()||(a.B&&a.B.Ub(),a.fa=0)):Tf(a,vg?"tr":"t")}break;case "r":if("reset"==b){a.B&&a.B.reset();break}Df(a,e);break;case "s":a:switch(e[1]){case "base":if(e[2]){var sb=+e[2];if(8==sb||10==sb||16==sb)a.ea=sb;else{a.g("invalid base: "+sb);
break}}a.g("default base: "+a.ea);break;case "cs":var tb;void 0!==e[3]&&(tb=+e[3]);switch(e[2]){case "int":a.b.ub=tb;break;case "start":a.b.Mb=tb;break;case "stop":a.b.vb=tb;break;default:a.g("unknown cs option");break a}void 0!==tb&&Cc(a.b);a.g("checksums "+(a.b.u.rb?"enabled":"disabled"));break;case "sp":void 0!==e[2]&&(Zc(a.b,+e[2])||a.g("warning: using 1x multiplier, previous target not reached"));a.g("target speed: "+(a.b.lb.toFixed(2)+"Mhz")+" ("+a.b.ab+"x)");break;case "?":a.g("debugger options:");
a.g("\tbase #\t\tset default base to #");a.g("\tcs int #\tset checksum cycle interval to #");a.g("\tcs start #\tset checksum cycle start count to #");a.g("\tcs stop #\tset checksum cycle stop count to #");a.g("\tsp #\t\tset speed multiplier to #");break;default:e[1]&&a.g("unknown option: "+e[1])}break;case "t":Tf(a,e[0],e[1]);break;case "u":Ef(a,e[1],e[2],8);break;case "v":if("var"==e[0]){Qf(a,b.substr(3))||(d=!1);break}a.g("PDP11js version 1.30.0 ("+a.b.Xc+",RELEASE"+(ub?",TYPEDARRAYS":",LONGARRAYS")+
")");a.g(window?window.navigator.userAgent:"");break;case "?":if(e[1]){Sf(a,b.substr(1));break}var Xc="commands:",Yc;for(Yc in sf)Xc+="\n"+ma(Yc,9)+sf[Yc];Bd(a)||(Xc+="\nnote: history disabled if no exec breakpoints");a.g(Xc);break;default:a.g("unknown command: "+b),d=!1}}}catch(De){a.g("debugger error: "+(De.stack||De.message)),d=!1}return d}function Dc(a,b,c){b=gf(a,b,c);for(var d in b)if(!Jf(a,b[+d]))return!1;return!0}
Ia(function(){for(var a=E(document,"pdp11","debugger"),b=0;b<a.length;b++){var c=a[b],d=D(c),d=new of(d);bb(d,c)}});
function Vf(a,b,c){y.call(this,"Computer",a,Vf,67108864);this.u.ja=!1;Wf(this,b);this.W=Ac(this,"autoPower",a);this.B=0;this.fa=a.busWidth||a.buswidth;this.f=Xf;this.K=null;this.F=this.da=!1;this.url=Ac(this,"url")||"";(Math.random()+.1).toString(36);this.j=Yf(this);if(this.b=ab("CPU",this.id)){this.G=ab("Debugger",this.id);this.I=new xb({id:this.vc+".bus",busWidth:this.fa},this.b,this.G);var d,f=$a(this.id);if((this.A=ab("Panel",this.id))&&this.A.jb)for(b=0;b<f.length;b++)d=f[b],d.ra=this.A.ra,d.g=
this.A.g,d.jb=this.A.jb;this.g("PDP11js v1.30.0\nCopyright \u00a9 2012-2016 Jeff Parsons <Jeff@pcjs.org>\nLicense: GPL version 3 or later <http://gnu.org/licenses/gpl.html>");this.g("Portions adapted from the PDP-11/70 Emulator v1.3 by Paul Nankervis <paulnank@hotmail.com>");for(b=0;b<f.length;b++)d=f[b],d.Ya&&d.Ya(this,this.I,this.b,this.G);b=null;d=a.resume;void 0!==d&&(1<d.length?b=this.H=d:this.f=parseInt(d,10));var e;if(a=Ac(this,"state")||(e=!0,a.state))b=this.$=a,e||(this.F=!0,this.f=Xf),this.f&&
(this.S=new N(this,"1.30.0"),Zf(this.S)?b=null:delete this.S);!b&&this.f&&(b=$f(this))&&(this.F=!0);if(b){var g=this;ra(b,null,!0,function(a,b,c){c?(g.H=null,g.F=!1,g.ra("Unable to load machine state from server (error "+c+(b?": "+na(b):"")+")")):(g.K=b,g.da=!0);G(g)})}else G(this);this.M.power||(this.W=!0);!c&&this.W&&ag(this,this.Nb)}else x("Unable to find CPU component")}C(Vf);var Xf=0;
function Wf(a,b){if(!b){var c;if("object"==typeof resources&&(c=resources.parms))try{b=eval("("+c+")")}catch(d){x(d.message+" ("+c+")")}}a.ea=b}function Ac(a,b,c){var d=b.toLowerCase(),d=Ta[b]||Ta[d];void 0===d&&a.ea&&(d=a.ea[b]);void 0===d&&c&&(d=c[b]);void 0===d&&"object"==typeof resources&&resources[b]&&(d=b);return d}function ag(a,b,c){for(var d=$a(a.id),f=0;f<=d.length;f++){var e=f<d.length?d[f]:a;if(!fb(e)){fb(e,function(){ag(a,b,c)});return}}b.call(a,c)}
function bg(a,b){var c=new N(a,"1.30.0","validate");if(Zf(c)&&cg(c)){var d=c.get("timestamp"),f=b?b.get("timestamp"):"unknown";d!=f&&(a.ra("Machine state may be out-of-date\n("+d+" vs. "+f+")\nCheck your browser's local storage limits"),b||c.clear())}}l=Vf.prototype;
l.Nb=function(a){void 0===a&&(a=this.f||(this.K?1:Xf));if(!this.B){this.B++;var b=!1,c=!1;this.ca=!1;var d=this.S||new N(this,"1.30.0");if(-1==a)b=!0;else if(a>Xf){if(Zf(d,this.K)){this.C=new N(this,"1.30.0","failsafe");Zf(this.C)&&(dg(this,d),a=2,eg(this.C));this.C.set("timestamp",qa());fg(this.C);var f=this.f&&!this.F;if(1==a||sa("Click OK to restore the previous PDP11js machine state, or CANCEL to reset the machine.")){if(c=cg(d)){var e=d.get("code"),g=d.get("data");e&&("ok"==e?Zf(d,g):("error"==
e&&"no machine state"!=g?(this.ra("Error: "+g),"unable to verify user"==g&&(za("user",""),this.j=null)):this.g(e+": "+g),eg(d),Zf(d)?(c=cg(d),f=!0):c=!1))}f&&bg(this,c?d:null)}else 2==a&&d.clear()}else bg(this);delete this.K;delete this.S}f=$a(this.id);for(e=0;e<f.length;e++)g=f[e],g!==this&&g!=this.b&&(c=gg(this,g,d,b,c));b=[d,a,c];-1!=a?ag(this,this.xc,b):this.xc(b)}};
function gg(a,b,c,d,f){if(!b.u.ja){b.u.ja=!0;if(b.Qa){var e=null;f&&((e=c.get(b.id))||(e=c.get(b.id.replace(/[a-z0-9]\./i,"."))));"string"===typeof e&&(e=null);!b.Qa(e,d)&&e&&(x("Unable to restore state for "+b.type),a.$&&!a.da?(c.clear(),a.f=Xf,window&&window.location.reload()):a.ca=!0,b.Qa(null),f=!1)}if(!d&&b.sc)for(a=b.sc.split("|"),c=0;c<a.length;c++)b.status(a[c])}return f}
l.xc=function(a){var b=a[0],c=0>a[1];a=a[2];this.ia=!0;this.u.ja=!0;var d=this.M.power;d&&(d.textContent="Shutdown");this.b&&(gg(this,this.b,b,c,a),this.b.Gb());this.ca&&(dg(this,b),b.clear());!c&&this.C&&(this.C.clear(),delete this.C);this.B=0};
function dg(a,b){if(sa("There may be a problem with your PDP11js machine.\n\nTo help us diagnose it, click OK to send this PDP11js machine state to http://www.pcjs.org.")){var c=a.j||"";b=b.toString();var d={app:"PDP11js",ver:"1.30.0"};d.url=a.url;d.user=c;d.type="bug";d.data=b;ra("http://www.pcjs.org/api/v1/report",d,!0)}}
function Uf(a,b,c){var d,f="none";if(a.B)return null;a.B--;var e=new N(a,"1.30.0"),g=new N(a,"1.30.0","validate"),h=qa();g.set("timestamp",h);e.set("timestamp",h);e.set("version","1.30.0");e.set("url",window?window.location.href:null);e.set("browser",window?window.navigator.userAgent:"");a.b&&a.b.Pa&&(c&&a.b.pa(),d=a.b.Pa(b,c),"object"===typeof d&&e.set(a.b.id,d),c&&(a.b.u.ja=!1,!1===d&&(f=null)));for(var h=$a(a.id),k=0;k<h.length;k++){var m=h[k];m.u.ja&&(m.Pa&&(d=m.Pa(b,c),"object"===typeof d&&e.set(m.id,
d)),c&&(m.u.ja=!1,!1===d&&(f=null)))}f&&(c?(h=d=!1,b?(a.j&&hg(a,a.j,e.toString()),fg(g)&&fg(e)||(f=null,d=h=!0)):a.f&&(d=!0,h=3==a.f),d&&e.clear(h)):f=e.toString());c&&(a.u.ja=!1,b=a.M.power)&&(b.textContent="Power");a.B=0;return f}l.reset=function(){this.I&&this.I.reset&&(cb(this,"Resetting "+this.I.type),this.I.reset());for(var a=$a(this.id),b=0;b<a.length;b++){var c=a[b];c!==this&&c!==this.I&&c.reset&&(cb(this,"Resetting "+c.type),c.reset())}};
l.start=function(a,b){for(var c=$a(this.id),d=0;d<c.length;d++){var f=c[d];"CPU"!=f.type&&f!==this&&f.start&&f.start(a,b)}};l.stop=function(a,b){for(var c=$a(this.id),d=0;d<c.length;d++){var f=c[d];"CPU"!=f.type&&f!==this&&f.stop&&f.stop(a,b)}};
l.xa=function(a,b,c){var d=this;switch(b){case "power":return this.M[b]=c,c.onclick=function(){d.B||(d.u.ja?Uf(d,!1,!0):ag(d,d.Nb))},!0;case "reset":return this.M[b]=c,c.onclick=function(){if(d.u.ja&&!d.B)if(d.f&&!d.H){var a=sa("Click OK to save changes to this PDP11js machine.\n\nWARNING: If you CANCEL, all disk changes will be discarded.");Uf(d,a,!0);!a&&d.$?window&&window.location.reload():d.Nb(Xf)}else d.reset(),d.b&&d.b.Gb()},!0;case "save":if(ea())c.parentNode.removeChild(c);else return this.M[b]=
c,c.onclick=function(){var a=Yf(d,!0);if(a){var b=!!(d.f&&!d.H||d.$),c=Uf(d,b);b?hg(d,a,c):d.ra("Resume disabled, machine state not saved")}},!0}return!1};
function Yf(a,b){var c=a.j;c||((c=wa("user"),void 0!==c)?!c&&b&&(b=null,window&&(b=window.prompt("Saving machine states on the pcjs.org server is currently unsupported.\n\nIf you're running your own server, enter your user ID below.","")),c=b)&&((c=ig(a,c))||a.ra("The user ID is invalid.")):b&&a.ra("Browser local storage is not available"));return c}
function ig(a,b){a.j=null;b=ra(fa()+"/api/v1/user?req=verify&user="+b);var c=b[1];if(!b[0]&&c)try{b=eval("("+c+")"),b.code&&"ok"==b.code&&(za("user",b.data),a.j=b.data)}catch(d){x(d.message+" ("+c+")")}return a.j}function $f(a){var b=null;a.j&&(b=fa()+"/api/v1/user?req=load&user="+a.j+"&state="+jg(a,"1.30.0"));return b}
function hg(a,b,c){if(c){var d={req:"store"};d.user=b;d.state=jg(a,"1.30.0");d.data=c;b=ra(fa()+"/api/v1/user",d);d=b[0];if(b[1]){if(d){var f=d.indexOf("\n");0<f&&(d=d.substr(0,f));d.indexOf("Error: ")||(d=d.substr(7))}d='{"code":'+b[1]+',"data":"'+d+'"}'}b=JSON.parse(d);b&&"ok"==b.code?a.ra("Machine state saved to server"):c&&(c=b&&b.data||"unable to save machine state",c="error"==b.code?"Error: "+c:"Error "+b.code+": "+c,a.ra(c),za("user",""),a.j=null)}}l.Ub=function(){};
l.Ha=function(a){this.b&&this.b.Ha(a);this.A&&this.A.Ha(a)};Ia(function(){for(var a=E(document,"pdp11-machine"),b=0;b<a.length;b++)for(var c=a[b],d=D(c),c=E(c,"pdp11","computer"),f=0;f<c.length;f++){var e=c[f],g=D(e),g=new Vf(g,d,!0);bb(g,e);g.W&&ag(g,g.Nb)}});Da.show.push(function(){for(var a=E(document,"pdp11","computer"),b=0;b<a.length;b++){var c=D(a[b]);(c=ab("Computer",c.id))&&c.ia&&!c.u.ja&&c.Nb(-1)}});
Da.exit.push(function(){for(var a=E(document,"pdp11","computer"),b=0;b<a.length;b++){var c=D(a[b]);(c=ab("Computer",c.id))&&c.u.ja&&Uf(c,!(!c.f||c.H),!0)}});function N(a,b,c){this.id=a.id;this.key=jg(a,b,c);this.G=a.G;eg(this,a.Sc)}function jg(a,b,c){a=a.id;if(b){var d=b.indexOf(".");0<d&&(a+=".v"+b.substr(0,d))}c&&(a+="."+c);return a}
N.prototype={constructor:N,set:function(a,b){try{this[this.id][a]=b}catch(c){}},get:function(a){return this[this.id][a]||null},value:function(){return this[this.id]},data:function(){return this[this.id]},toString:function(){var a=this[this.id];return"string"==typeof a?a:JSON.stringify(a)},clear:function(a){eg(this);var b=[];try{for(var c=0,d=window.localStorage.length;c<d;c++)b.push(window.localStorage.key(c))}catch(f){}for(c=0;c<b.length;c++)if((d=b[c])&&(a||d.substr(0,this.key.length)==this.key)){try{window.localStorage.removeItem(d)}catch(f){}b.splice(c,
1);c=0}}};function eg(a,b){a[a.id]={};b&&a.set("parms",b);a.b=!1}function fg(a){var b=!0;if(va()){var c=JSON.stringify(a[a.id]);za(a.key,c)||(x("Unable to store "+c.length+" bytes in browser local storage"),b=!1)}return b}function cg(a){var b=!0;try{a[a.id]=JSON.parse(a[a.id])}catch(c){x(c.message||c),b=!1}return b}function Zf(a,b){return b?(a[a.id]=b,a.b=!0):a.b?!0:va()&&(b=wa(a.key))?(a[a.id]=b,a.b=!0):!1}var kg=0;
function wg(a,b,c,d,f,e){f("Loading "+a+"...");ra(a,null,!0,function(g,h,k){k?(h||(h="unable to load "+a+" ("+k+")"),e(h,null)):xg(h,a,b,c,d,f,e)})}
function xg(a,b,c,d,f,e,g){function h(a,e){if(e)g(e,null);else{c&&(Za(c,b,a),(e=b)&&0>e.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(e=window.location.pathname+e),d?"}"==d.slice(-1)?(d=d.slice(0,-1),1<d.length&&(d+=",")):d='{state:"'+d+'",':d="{",d+='url:"'+e+'"}',"object"==typeof resources&&(e=null),a=a.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(d?" parms='"+d+"'":"")+(e?' url="'+e+'"':"")));f||(a=a.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1PDP11js$2"),
a=a.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1pdp11$2"));e=null;if("<"==a.charAt(0))try{f||(a=a.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(e=new window.ActiveXObject("Microsoft.XMLDOM"),e.async=!1,e.loadXML(a)):e=(new window.DOMParser).parseFromString(a,"text/xml")}catch(n){e=null,a=n.message}else a="unrecognized XML: "+(255<a.length?a.substr(0,255)+"...":a);g(a,e)}}a?f?yg(a,e,h):h(a,null):g("no data"+(b?" for file: "+b:""),null)}
function yg(a,b,c){var d;if(d=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(a)){var f=d[2];b("Loading "+f+"...");ra(f,null,!0,function(e,g,h){if(h||!g)c(a,"unable to resolve XML reference: "+d[0]+" ("+h+")");else{if(e=d[3])if(h=g.match(new RegExp("<"+d[1]+"[^>]*>"))){for(var k=h[0],m,n=/( [a-z]+=)(['"])(.*?)\2/g;m=n.exec(e);)k=0>k.indexOf(m[1])?k.replace(">",m[0]+">"):k.replace(new RegExp(m[1]+"(['\"])(.*?)\\1"),m[0]);h[0]!=k&&(g=g.replace(h[0],k))}else{c(a,"missing <"+d[1]+"> in "+f);return}g=g.replace(/<\?xml[^>]*>[\r\n]*/,
"");a=a.replace(d[0],g);yg(a,b,c)}})}else c(a,null)}
function zg(a,b,c,d){function f(a){if(void 0===h){var b=g&&E(g,"machine-warning");h=b&&b[0]||g}h&&(h.innerHTML=la(a))}function e(a){f("Error: "+a);k&&(--kg||Qa(!0));k=!1}var g,h,k=!0;kg++;Ya[a]={};try{if(g=document.getElementById(a)){var m;if("object"==typeof resources&&(m=resources.css)){var n=document.head||document.getElementsByTagName("head")[0],q=document.createElement("style");q.type="text/css";q.styleSheet?q.styleSheet.cssText=m:q.appendChild(document.createTextNode(m));n.appendChild(q)}c||
(c="/versions/pdp11/1.30.0/components.xsl");m=function(d,h){h?wg(c,null,null,!1,f,function(d,k){k?(Za(a,c,d),f("Processing "+b+"..."),window.ActiveXObject||"ActiveXObject"in window?(k=h.transformNode(k))?(g.outerHTML=k,--kg||Qa(!0)):e("transformNodeToObject failed"):document.implementation&&document.implementation.createDocument?(d=new XSLTProcessor,d.importStylesheet(k),(k=d.transformToFragment(h,document))?g.parentNode?(g.parentNode.replaceChild(k,g),--kg||Qa(!0)):e("invalid machine element: "+
a):e("transformToFragment failed")):e("unable to transform XML: unsupported browser")):e(d)}):e(d)};"<"!=b.charAt(0)?wg(b,a,d,!0,f,m):xg(b,null,a,d,!1,f,m)}else e("missing machine element: "+a)}catch(p){e(p.message)}return k}window.embedPDP11=function(a,b,c,d){Qa(!1);return zg(a,b,c,d)};window.enableEvents=Qa;window.sendEvent=Ra;})();
