(function(){/*
 http://pcjs.org/modules/shared/lib/diskapi.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/dumpapi.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/reportapi.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/userapi.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/keys.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/strlib.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/usrlib.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/weblib.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/messages.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/debugger.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/debugger.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/embed.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/defines.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/component.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/defines.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/panel.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/bus.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/device.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/memory.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/cpu.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/cpustate.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/cpuops.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/rom.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/ram.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/keyboard.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/serialport.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/pc11.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/disk.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/rk11.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/rl11.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/pdp11/lib/computer.js (C) Jeff Parsons 2012-2016
 http://pcjs.org/modules/shared/lib/state.js (C) Jeff Parsons 2012-2016
*/
for(var h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,ca=["Math","log2"],da=0;da<ca.length-1;da++){var ea=ca[da];ea in ba||(ba[ea]={});ba=ba[ea]}var fa=ca[ca.length-1],ga=ba[fa],ha=ga?ga:function(a){return Math.log(a)/Math.LN2};
ha!=ga&&null!=ha&&aa(ba,fa,{configurable:!0,writable:!0,value:ha});
var ia={163840:[40,1,8,,254],184320:[40,1,9,,252],327680:[40,2,8,,255],368640:[40,2,9,,253],737280:[80,2,9,,249],1228800:[80,2,15,,249],1474560:[80,2,18,,240],2949120:[80,2,36,,240],21368320:[615,4,17],2494464:[203,2,12,512],5242880:[256,2,40,256],10485760:[512,2,40,256]},ja={mc:1,Se:3,Te:26," ":32,"!":33,'"':34,"#":35,$:36,"%":37,"&":38,"'":39,"(":40,")":41,"*":42,"+":43,",":44,"-":45,".":46,"/":47,0:48,1:49,2:50,3:51,4:52,5:53,6:54,7:55,8:56,9:57,":":58,";":59,"<":60,"=":61,">":62,"?":63,"@":64,
Sb:65,Qe:66,Re:67,Ue:68,E:69,Ve:70,We:71,Xe:72,Ye:73,Ze:74,$e:75,af:76,bf:77,cf:78,df:79,ef:80,Q:81,ff:82,gf:83,hf:84,jf:85,kf:86,lf:87,mf:88,nf:89,wc:90,"[":91,"\\":92,"]":93,"^":94,_:95,"`":96,pf:97,qf:98,rf:99,d:100,e:101,sf:102,tf:103,uf:104,vf:105,yf:106,k:107,zf:108,Af:109,n:110,Bf:111,p:112,q:113,r:114,Cf:115,t:116,Df:117,Ef:118,Ff:119,x:120,y:121,z:122,"{":123,"|":124,"}":125,"~":126,nc:127};
function m(a){var b=10,c;if(a){b||(b=10);var d=a.charAt(0),e=0<a.indexOf(",");e&&(a=a.replace(/,/g,""));"#"==d?(b=8,d=null):"$"==d&&(b=16,d=null);null==d?a=a.substr(1):("0"==d&&(d=a.charAt(1),"b"==d&&e&&(b=2,d=null),"o"==d?(b=8,d=null):"x"==d&&(b=16,d=null)),null==d?a=a.substr(2):(d=a.charAt(a.length-1).toLowerCase(),"y"==d?(b=2,d=null):"."==d?(b=10,d=null):"h"==d&&(b=16,d=null),null==d&&(a=a.substr(0,a.length-1))));var f,d=a;((e=b)&&10!=e?16==e?d.match(/^[0-9a-f]+$/i):8==e?d.match(/^[0-7]+$/):2==
e&&d.match(/^[01]+$/):d.match(/^[0-9]+$/))&&!isNaN(f=parseInt(a,b))&&(c=f|0)}return c}function ka(a,b){var c="";b?11<b&&(b=11):b=a&-65536?11:6;if(null==a||isNaN(a))for(;0<b--;)c="?"+c;else for(;0<b--;)c=String.fromCharCode((a&7)+48)+c,a>>=3;return""+c}function q(a,b,c){var d="";b?8<b&&(b=8):b=a&-65536?8:4;if(null==a||isNaN(a))for(;0<b--;)d="?"+d;else for(;0<b--;){var e=a&15,e=e+(0<=e&&9>=e?48:55),d=String.fromCharCode(e)+d;a>>=4}return(c?"0x":"")+d}
function r(a,b){var c=a,d=a.lastIndexOf("/");0<=d&&(c=a.substr(d+1));d=c.indexOf("&");0<d&&(c=c.substr(0,d));b&&(d=c.lastIndexOf("."),0<d&&(c=c.substring(0,d)));return c}function la(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase());return b}function ma(a,b){return-1!==a.indexOf(b,a.length-b.length)}var na={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"};function oa(a){return a.replace(/[&<>"']/g,function(a){return na[a]})}
function pa(a){return String.prototype.trim?a.trim():a.replace(/^\s+|\s+$/g,"")}var qa={0:"NUL",1:"SOH",2:"STX",3:"ETX",4:"EOT",5:"ENQ",6:"ACK",7:"BEL",8:"BS",9:"TAB",11:"VT",12:"FF",14:"SO",15:"SI",16:"DLE",17:"XON",18:"DC2",19:"XOFF",20:"DC4",21:"NAK",22:"SYN",23:"ETB",24:"CAN",25:"EM",26:"SUB",27:"ESC",28:"FS",29:"GS",30:"RS",31:"US"},ra=Date.now||function(){return+new Date};
function sa(){function a(a){return(10>a?"0":"")+a}var b=new Date;return b.getFullYear()+"-"+a(b.getMonth()+1)+"-"+a(b.getDate())+" "+a(b.getHours())+":"+a(b.getMinutes())+":"+a(b.getSeconds())}
function t(a,b,c,d){var e=0,f=null,g=null;if("object"==typeof resources&&(f=resources[a]))return d&&d(a,f,e),[f,e];if(c&&"function"==typeof resources)return resources(a,function(b,c){d&&d(a,b,c)}),g;var k=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");c&&(k.onreadystatechange=function(){4===k.readyState&&(f=k.responseText,200==k.status||!k.status&&f.length&&"file:"==(window?window.location.protocol:"file:")||(e=k.status||-1),d&&d(a,f,e))});if(b&&"object"==
typeof b){var l="",n;for(n in b)b.hasOwnProperty(n)&&(l&&(l+="&"),l+=n+"="+encodeURIComponent(b[n]));l=l.replace(/%20/g,"+");k.open("POST",a,!!c);k.setRequestHeader("Content-type","application/x-www-form-urlencoded");k.send(l)}else k.open("GET",a,!!c),"bytes"==b&&k.overrideMimeType("text/plain; charset=x-user-defined"),k.send();c||(f=k.responseText,200!=k.status&&(e=k.status||-1),d&&d(a,f,e),g=[f,e]);return g}
function ta(a,b){var c,d={L:null,ba:null,na:null,ma:null};if("["==b.charAt(0)||"{"==b.charAt(0))try{var e,f,g;if("<"==b.substr(0,1))throw Error(b);g=0>b.indexOf("0x")&&'["'!=b.substr(0,2)?JSON.parse(b.replace(/([a-z]+):/gm,'"$1":').replace(/\/\/[^\n]*/gm,"")):eval("("+b+")");d.na=g.load;d.ma=g.exec;if(e=g.bytes)d.L=e;else if(e=g.words)for(d.L=Array(2*e.length),f=c=0;c<e.length;c++)d.L[f++]=e[c]&255,d.L[f++]=e[c]>>8&255;else if(e=g.data)for(d.L=Array(4*e.length),f=c=0;c<e.length;c++)d.L[f++]=e[c]&
255,d.L[f++]=e[c]>>8&255,d.L[f++]=e[c]>>16&255,d.L[f++]=e[c]>>24&255;else d.L=g;d.ba=g.symbols;d.L.length?1==d.L.length&&(w(d.L[0]),d=null):(w("Empty resource: "+a),d=null)}catch(k){w("Resource data error ("+a+"): "+k.message),d=null}else{e=[];b=b.replace(/\n/gm," ").replace(/ +$/,"").split(" ");for(c=0;c<b.length;c++){f=parseInt(b[c],16);if(isNaN(f)){w("Resource data error ("+a+"): invalid hex byte ("+b[c]+")");break}e.push(f&255)}c==b.length&&(d.L=e)}return d}
function ua(){return"http://"+(window?window.location.host:"www.pcjs.org")}function w(a){window&&window.alert(a)}function va(a){var b=!1;window&&(b=window.confirm(a));return b}var wa=null;function xa(){if(null==wa){var a=!1;if(window)try{window.localStorage.setItem("PCjs.localStorage","PCjs.localStorage"),a="PCjs.localStorage"==window.localStorage.getItem("PCjs.localStorage"),window.localStorage.removeItem("PCjs.localStorage")}catch(b){a=!1}wa=a}return wa}
function ya(a){var b;if(window)try{b=window.localStorage.getItem(a)}catch(c){}return b}function Ba(a,b){try{return window.localStorage.setItem(a,b),!0}catch(c){}return!1}function Ca(a){if(window){var b=window?window.navigator.userAgent:"";return"iOS"==a&&b.match(/(iPod|iPhone|iPad)/)&&b.match(/AppleWebKit/)||"MSIE"==a&&b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)?!0:!1}return!1}
function Da(a,b){var c=null;a="data:application/octet-stream;base64,"+a;b&&(c=document.createElement("a"),"string"!=typeof c.download&&(c=null));c?(c.href=a,c.download=b,document.body.appendChild(c),c.click(),document.body.removeChild(c),b="Check your Downloads folder for "+b+"."):(window.open(a),b="Check your browser for a new window/tab containing the requested data"+(b?" ("+b+")":"")+".");return b}var Ea={init:[],show:[],exit:[]},Fa=!1,Ga=!1,Ha=!0;
function Ia(a,b){if(window){var c=window[a];window[a]="function"!==typeof c?b:function(){c&&c();b()}}}function Ja(a){Ea.init.push(a)}function Ka(a){if(Ha)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){w(""+("An unexpected exception occurred:\n\n"+c.message+"\n\nPlease send this information to support@pcjs.org. Thanks."))}}function La(a){!Ha&&a?(Ha=!0,Fa&&Ma("init"),Ga&&Ma("show")):Ha=a}function Ma(a){Ea[a]&&Ka(Ea[a])}Ia("onload",function(){Fa=!0;Ka(Ea.init)});Ia("onpageshow",function(){Ga=!0;Ka(Ea.show)});
Ia(Ca("Opera")||Ca("iOS")?"onunload":"onbeforeunload",function(){Ka(Ea.exit)});function x(a,b,c,d){this.type=a;b||(b={id:"",name:""});this.id=b.id||"";this.name=b.name;this.Xb=b.comment;this.Jc=b;b=this.id.indexOf(".");0>b?this.Ca=this.id:(this.ua=this.id.substr(0,b),this.Ca=this.id.substr(b+1));this[a]=c;this.o={ready:!1,Fa:!1,Hb:!1,R:!1,error:!1};this.vb=null;this.o.error=!1;this.j={};this.H=null;this.Hc=d||0;y.push(this)}var Na=void 0,Oa={};
if(window){Na||(Na=window.location.search.substr(1));for(var Pa,Qa=/\+/g,Ra=/([^&=]+)=?([^&]*)/g;Pa=Ra.exec(Na);)Oa[decodeURIComponent(Pa[1].replace(Qa," "))]=decodeURIComponent(Pa[2].replace(Qa," "))}function Sa(a){function b(){}if(window){if(!a)throw new TypeError;if(Object.create)return Object.create(a);var c=typeof a;if("object"!==c&&"function"!==c)throw new TypeError;}b.prototype=a;return new b}
function z(a,b){b||(b=x);a.prototype=Sa(b.prototype);a.prototype.constructor=a;a.prototype.parent=b.prototype}if(window){window.PCjs||(window.PCjs={});var Ta=window.PCjs.Machines||(window.PCjs.Machines={}),y=window.PCjs.Components||(window.PCjs.Components=[])}else Ta={},y=[];function Ua(a,b,c){Ta[a]&&b&&(Ta[a][b]=c)}function A(a){var b,c=[];a&&(a=0<(b=a.indexOf("."))?a.substr(0,b+1):"");for(b=0;b<y.length;b++){var d=y[b];a&&d.id.indexOf(a)||c.push(d)}return c}
function Va(a){if(void 0!==a){var b;for(b=0;b<y.length;b++)if(y[b].id===a)return y[b]}return null}function Wa(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<y.length;d++)if(c)c==y[d]&&(c=null);else if(!(a!=y[d].type||b&&y[d].id.indexOf(b)))return y[d]}return null}function B(a){var b=null;if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(c){w(c.message+" ("+a+")")}return b}
function C(a,b){b=D(b.parentNode,"pdp11-control");for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var f=d[e];if(1===f.nodeType){var g=f.getAttribute("class");if(g)for(var k=g.split(" "),l=0;l<k.length;l++)switch(g=k[l],g){case "pdp11-binding":(g=B(f))&&g.binding&&a.aa(g.type,g.binding,f,g.value),l=k.length}}}}
function D(a,b,c){c&&(b+="-"+c+"-object");if(a.getElementsByClassName)return a.getElementsByClassName(b);var d;c=[];a=a.getElementsByTagName("*");var e=new RegExp("(^| )"+b+"( |$)");b=0;for(d=a.length;b<d;b++)e.test(a[b].className)&&c.push(a[b]);return c}
x.prototype={constructor:x,parent:null,toString:function(){return this.name?this.name:this.id||this.type},aa:function(a,b,c){switch(b){case "clear":return this.j[b]||(this.j[b]=c,c.onclick=function(a){return function(){a.j.print&&(a.j.print.value="")}}(this)),!0;case "print":return this.j[b]||(this.eb=this.j[b]=c,c.value="",this.X=function(a){return function(b,c){8192<a.value.length&&(a.value=a.value.substr(a.value.length-4096));a.value+=(void 0!==c?c+": ":"")+(b||"")+"\n";a.scrollTop=a.scrollHeight}}(c),
this.C=function(a){this.X(a,this.Ca)}),!0;default:return!1}},log:function(){},X:function(){},status:function(a){this.X(this.Ca+": "+a)},C:function(a,b,c){c=c||this.type;b||w((c?c+": ":"")+a)},ha:function(){return this.o.R=!0},ga:function(a,b){b&&(this.o.R=!1);return!0}};function Xa(a,b){a.o.Hb?(a.o.Fa=!1,a.o.Hb=!1):a.o.error?a.X(a.toString()+" error"):a.o.Fa=b}function E(a,b){a.o.error||(a.o.ready=!1!==b,a.o.ready&&(b=a.vb,a.vb=null,b&&b()))}
function Ya(a,b){b&&(a.o.ready?b():a.vb=b);return a.o.ready}function Za(a,b){a.o.error=!0;a.C(b)}Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});var $a="undefined"!==typeof ArrayBuffer;
function ab(a){x.call(this,"Panel",a,ab,512);this.ia=this.i=this.c=this.m=this.s=this.u=0;this.A=this.D=this.w=!1;this.G=bb;this.h={};this.b={START:[1,1,!0,!1,this.Qc],STEP:[1,1,!1,!1,this.Rc],ENABLE:[1,1,!1,!1,this.Mc],CONT:[1,1,!0,!1,this.Kc],DEP:[0,0,!0,!1,this.Lc],EXAM:[1,1,!0,!1,this.Nc],LOAD:[1,1,!0,!1,this.Pc],TEST:[0,0,!0,!1,this.Oc]};for(a=0;22>a;a++)this.b["S"+a]=[0,0,!1,!1,this.Sc,a]}z(ab);var bb=7;function cb(a,b){return a.b[b]&&a.b[b][1]}h=ab.prototype;h.reset=function(){this.stop()};
h.aa=function(a,b,c,d){if(this.l&&this.l.aa(a,b,c,d)||this.a&&this.a.aa(a,b,c,d))return!0;switch(b){case "R0":case "R1":case "R2":case "R3":case "R4":case "R5":case "R6":case "R7":case "NF":case "ZF":case "VF":case "CF":case "PS":return this.j[b]=c,this.u++,!0;default:return"led"==a||"rled"==a?(this.j[b]=c,this.h[b]=d?1:0,this.u++,!0):"switch"==a?(void 0===this.b[b]&&(this.b[b]=[d?1:0,d?1:0]),this.j[b]=c,a=c.parentElement||c,a=a.parentElement||a,a.onmousedown=function(a,b){return function(){db(a,
b)}}(this,b),a.onmouseup=a.onmouseout=function(a,b){return function(){eb(a,b)}}(this,b),a.ontouchstart=function(a,b){return function(c){db(a,b);c.preventDefault()}}(this,b),a.ontouchend=function(a,b){return function(){eb(a,b)}}(this,b),!0):this.parent.aa.call(this,a,b,c,d)}};h.fa=function(a,b,c,d){this.l=a;this.g=b;this.a=c;this.H=d;fb(b,this,gb);hb(b,this.reset.bind(this));ib(this);jb(this)};h.ha=function(a,b){b||(kb(),this.reset());return!0};h.ga=function(){return!0};
function lb(a,b,c){if(a=a.j[b])a.style.backgroundColor=c?"#ff0000":"#000000"}function ib(a,b){for(var c in a.h)lb(a,c,null!=b?b:a.h[c])}function mb(a,b,c){if(a=a.j[b])a.style.marginTop=c?"0px":"20px",a.style.backgroundColor=c?"#00ff00":"#228B22"}function jb(a){for(var b in a.b)mb(a,b,a.b[b][1])}function nb(a,b,c,d){a.j[b]&&(void 0===c&&(Za(a,"Value for "+b+" is invalid"),F(a.a)),c=8==(a.H&&a.H.g||8)?ka(c,d):q(c,d),a.j[b].textContent!=c&&(a.j[b].textContent=c))}
function db(a,b){var c=a.b[b];mb(a,b,c[1]=1-c[1]);c[3]=!0;c[4]&&c[4].call(a,c[1],c[5]);"STEP"!=b&&(a.A="DEP"==b,a.D="EXAM"==b)}function eb(a,b){var c=a.b[b];c[2]&&c[3]&&(mb(a,b,c[1]=c[0]),c[4]&&c[4].call(a,c[1],c[5]));c[3]=!1}h.Qc=function(a){a||this.a.o.T||(a=this.a,a.g.reset(),ob(a),cb(this,"ENABLE")&&pb(this.a))};h.Rc=function(){};h.Mc=function(a){a||F(this.a)};
h.Kc=function(a){if(!a&&!this.a.o.T)if(cb(this,"ENABLE"))pb(this.a);else{a=this.H;var b;if(b=a)a.o.Fa&&(a.o.Hb=!0),b=!a.o.Fa;if(b)Xa(a,!0),a.xb(0,null),Xa(a,!1);else try{var c=this.a.xb(1);0<c&&(qb(this.a,c),rb(this.a,c,!0),sb(this.a,c))}catch(d){"number"!=typeof d&&Za(this.a,d.stack||d.message)}this.stop();this.l&&this.l.Ba()}};h.Lc=function(a){a&&!this.a.o.T&&(this.A&&tb(this),a=ub(this,this.c),this.G==bb?this.g.Va(this.ia,a):this.a.Va(this.ia,a))};
h.Nc=function(a){a||this.a.o.T||(this.D&&tb(this),a=this.G==bb?this.g.Qa(this.ia):this.a.Qa(this.ia),ub(this,a))};h.Pc=function(a){a||this.a.o.T||vb(this,this.c)};h.Oc=function(a){if(a)this.w=!0,ib(this,!0);else if(this.w=!1,ib(this),void 0!==this.j.S0){for(a=this.c=0;22>a;a++)this.b["S"+a][1]=0&1<<a?1:0;jb(this)}};h.Sc=function(a,b){this.c=a?this.c|1<<b:this.c&~(1<<b)};
function tb(a){var b=1145>a.a.Ra?8:16,c=65472<=a.ia&&a.ia<65472+b,b=c?1:2,c=c?15:a.g.qa;cb(a,"STEP")||(b=-b);vb(a,a.ia&~c|a.ia+b&c)}function vb(a,b){a.ia=b&a.g.qa;b=a.ia;for(var c=0;22>c;c++)wb(a,"A"+c,b&1<<c)}function ub(a,b){a.i=b&65535;b=a.i;for(var c=0;16>c;c++)wb(a,"D"+c,b&1<<c);return a.i}function wb(a,b,c){a.h[b]=c;a.w||lb(a,b,c)}h.stop=function(){vb(this,this.a.f[7])};h.setData=function(a,b){b?this.m=a:this.i=a};h.Tc=function(a,b){return(b?this.m:this.c)&65535};h.Vd=function(a){this.m=a};
var xb={},gb=(xb[65400]=[null,null,ab.prototype.Tc,ab.prototype.Vd,"CNSW"],xb);function kb(){for(var a=!1,b=D(document,"pdp11","panel"),c=0;c<b.length;c++){var d=b[c],e=B(d),f=Va(e.id);f||(a=!0,f=new ab(e));C(f,d);a&&E(f)}}Ja(kb);
function yb(a,b,c){x.call(this,"Bus",a,yb,16);this.a=b;this.H=c;this.K=a.busWidth||16;this.s=0;this.u=[];this.i=null;this.D=1<<this.K;this.qa=this.D-1;this.b=G;this.c=Math.log2(this.b);this.G=this.b>>2;this.l=this.b-1;this.A=this.D/this.b|0;this.Da=[];this.h=0;this.m=!1;this.Ib=0;this.w=[];this.xc=[zb,Ab,Bb,Cb];a=new H(this);Db(a,this.H);this.g=Array(this.A);for(b=0;b<this.A;b++)this.g[b]=a;E(this)}z(yb);var G=8192,Eb=G-1;
function zb(a,b){var c=-1,d=this.controller,e=d.Da[a],f=b&65535;e?e[0]?c=e[0](f):e[2]&&(c=f&1?e[2](f&-2)>>8:e[2](f)&255):f&1&&(e=d.Da[a&-2])&&(e[2]?c=e[2](f&-2)>>8:e[0]&&(c=e[0](f)));if(0<=c)return c;I(d,b,16);return 255}
function Ab(a,b,c){var d=!1,e=this.controller,f=e.Da[a],g=c&65535;if(f)if(f[1])f[1](b,g),d=!0;else{if(f[3]){a=f[2]?f[2](g,!0):0;if(g&1)f[3](a&255|b<<8,g&-2);else f[3](a&-256|b,g);d=!0}}else g&1&&(f=e.Da[a&-2])&&(f[3]?(g&=-2,a=f[2]?f[2](g,!0):0,f[3](a&255|b<<8,g),d=!0):f[1]&&(f[1](b,g),d=!0));d||I(e,c,16)}function Bb(a,b){var c=-1,d=this.controller;a=d.Da[a];var e=b&65535;a&&(a[2]?c=a[2](e):a[0]&&(c=a[0](e)|a[0](e+1)<<8));if(0<=c)return c;I(d,b,16);return 65535}
function Cb(a,b,c){var d=!1,e=this.controller;a=e.Da[a];var f=c&65535;a&&(a[3]?(a[3](b,f),d=!0):a[1]&&(a[1](b&255,f),a[1](b>>8,f+1),d=!0));d||I(e,c,16)}function Fb(a,b){if(b!=a.s){var c;a.s&&(c=(1<<a.s)-G,Gb(a,c,G,a.u),a.s=0);b&&(a.s=b,c=1<<b,a.qa=c-1,c-=G,a.u=Hb(a,c,G),a.i?Gb(a,c,G,a.i):(Ib(a,c,G,Jb,a),a.i=Hb(a,c,G)))}}h=yb.prototype;h.reset=function(){for(var a=0;a<this.w.length;a++)this.w[a]();Fb(this,16)};h.ha=function(a,b){b||this.reset();return!0};
function Ib(a,b,c,d,e){for(var f=b,g=c,k=f>>>a.c;0<g&&k<a.g.length;){var l=a.g[k],n=k*a.b,p=a.b-(f-n);p>g&&(p=g);if(!e&&l&&l.size){if(l.type==d){if(f+g<=l.Pa)return l.yb+=l.Pa-f,l.Pa=f,!0;if(f>=l.Pa+l.yb){p=l.size-(f-n);p>g&&(p=g);l.yb=f-l.Pa+p;f=n+a.b;g-=p;k++;continue}}return Kb(1,f,g)}f=new H(a,f,p,a.b,d,e);Db(f,a.H,l);a.g[k++]=f;f=n+a.b;g-=p}return 0>=g?(d==Lb&&(a.Ib+=c),a.status((c>>10)+"Kb "+Mb[d]+" at "+ka(b)),!0):Kb(2,b,c)}
function Hb(a,b,c){var d=[];for(b>>>=a.c;0<c&&b<a.g.length;)d.push(a.g[b++]),c-=a.b;return d}function Gb(a,b,c,d){var e=0;for(b>>>=a.c;0<c&&b<a.g.length;){var f=d[e++];if(!f)break;a.g[b++]=f;c-=a.b}}function Nb(a,b){3932160<=b&&(b=Ob(a.a,b));return a.g[(b&a.qa)>>>a.c].Lb(b&a.l,b)}function Pb(a,b){3932160<=b&&(b=Ob(a.a,b));return a.g[(b&a.qa)>>>a.c].Y(b&a.l,b)}h.Qa=function(a){3932160<=a&&(a=Ob(this.a,a));var b=a&this.l,c=(a&this.qa)>>>this.c;this.m=!1;this.h++;a=this.g[c].ec(b,a);this.h--;return a};
function Qb(a,b,c){3932160<=b&&(b=Ob(a.a,b));a.g[(b&a.qa)>>>a.c].Qb(b&a.l,c&255,b)}h.jb=function(a,b){3932160<=a&&(a=Ob(this.a,a));this.m=!1;this.h++;this.g[(a&this.qa)>>>this.c].Rb(a&this.l,b&255,a);this.h--};function Rb(a,b,c){3932160<=b&&(b=Ob(a.a,b));a.g[(b&a.qa)>>>a.c].zb(b&a.l,c&65535,b)}h.Va=function(a,b){3932160<=a&&(a=Ob(this.a,a));var c=a&this.l,d=(a&this.qa)>>>this.c;this.m=!1;this.h++;this.g[d].kc(c,b&65535,a);this.h--};
function Sb(a){for(var b=0,c=[],d=0;d<a.A;d++){var e=a.g[d];if(e.za||e.Dc){c[b++]=d;var f=b++;if(e=e.save()){for(var g=0,k=0,l=[];g<e.length;){for(var n=e[g],p=g+1;p<e.length&&e[p]===n;)p++;l[k++]=p-g;l[k++]=n;g=p}l.length<e.length&&(e=l)}c[f]=e}}return c}function Tb(a,b,c,d,e,f,g,k,l){for(;b<=c;b+=2){var n=b&Eb;if(void 0!==a.Da[n])return w("I/O address already registered: "+q(b,8,!0)),!1;a.Da[n]=[d,e,f,g,l||"unknown",k||16,!1]}return!0}
function fb(a,b,c){for(var d in c){var e=+d,f=c[d];if(!(f[6]&&f[6]>a.a.Ra)){var g=f[0]?f[0].bind(b):null,k=f[1]?f[1].bind(b):null,l=f[2]?f[2].bind(b):null,n=f[3]?f[3].bind(b):null;65472<=e&&65487>=e&&(!g&&l&&(g=function(a){return function(b){return a(b)&255}.bind(b)}(l)),!k&&n&&(k=function(a){return function(b,c){return a(b,c)}.bind(b)}(n)));for(var p=f[4],u=f[5]||1,v=0;v<u;v++,e+=2)if(p&&1<u&&(p=f[4]+v),!Tb(a,e,e,g,k,l,n,f[7]||b.Hc,p||b.Ca))return!1}}return!0}function hb(a,b){a.w.push(b)}
function I(a,b,c){a.m=!0;a.h||(c&&(a.a.ja|=c),J(a.a,4,0,b))}function Ub(a){var b=a.m;a.m=!1;return b}function Kb(a,b,c){w("Memory block error ("+a+": "+q(b)+","+q(c)+")");return!1}function K(a){x.call(this,"Device",a,K,256);this.b={B:0,Pb:-1}}z(K);h=K.prototype;
h.fa=function(a,b,c,d){this.g=b;this.l=a;this.a=c;this.H=d;var e=this;this.b.Pb=Vb(c,function(){e.b.gb|=128;e.b.gb&64&&Wb(e.a,e.b.Td);e.l&&e.l.Ba(1);Xb(e.a,e.b.Pb,1E3/60)});this.b.Td=Yb(64,6,524288);fb(b,this,Zb);hb(b,this.reset.bind(this));E(this)};h.reset=function(){this.b.gb=128;Xb(this.a,this.b.Pb,1E3/60,!0)};h.$c=function(){return this.b.gb};h.be=function(a){this.b.gb=a&192};h.bd=function(){var a=this.a,b=a.Z;b&57344||(b=b&-3199|a.lb<<5|a.mb<<1);return b};
h.de=function(a){$b(this.a,a&-129|this.a.Z&128)};h.cd=function(){var a=this.a;a.Z&57344||(a.Eb=a.A>>16&65535);a=a.Eb;a&65280&&(a=(a<<8|a>>8)&65535);return a};h.dd=function(){var a=this.a;a.Z&57344||(a.Gb=a.A&65535);return a.Gb};h.ed=function(){return this.a.Ea};h.ee=function(a){var b=this.a;1170>b.Ra&&(a&=-49);b.Ea!=a&&(b.Ea=a,b.Ya=a&16?4194303:262143,ac(b))};h.Nd=function(a){a=a>>1&63;var b=this.a.kb[a>>1];return a&1?b>>16:b&65535};
h.Me=function(a,b){b=b>>1&63;var c=b>>1;this.a.kb[c]=b&1?this.a.kb[c]&65535|(a&63)<<16:this.a.kb[c]&-65536|a&65534};h.Gd=function(a){return this.a.I[1][a>>1&7]};h.Fe=function(a,b){this.a.I[1][b>>1&7]=a&65295};h.Ed=function(a){return this.a.I[1][(a>>1&7)+8]};h.De=function(a,b){this.a.I[1][(b>>1&7)+8]=a&65295};h.Fd=function(a){return this.a.ca[1][a>>1&7]};h.Ee=function(a,b){b=b>>1&7;this.a.ca[1][b]=a;this.a.I[1][b]&=65295};h.Dd=function(a){return this.a.ca[1][(a>>1&7)+8]};
h.Ce=function(a,b){b=(b>>1&7)+8;this.a.ca[1][b]=a;this.a.I[1][b]&=65295};h.Zc=function(a){return this.a.I[0][a>>1&7]};h.ae=function(a,b){this.a.I[0][b>>1&7]=a&65295};h.Xc=function(a){return this.a.I[0][(a>>1&7)+8]};h.Zd=function(a,b){this.a.I[0][(b>>1&7)+8]=a&65295};h.Yc=function(a){return this.a.ca[0][a>>1&7]};h.$d=function(a,b){b=b>>1&7;this.a.ca[0][b]=a;this.a.I[0][b]&=65295};h.Wc=function(a){return this.a.ca[0][(a>>1&7)+8]};h.Yd=function(a,b){b=(b>>1&7)+8;this.a.ca[0][b]=a;this.a.I[0][b]&=65295};
h.Md=function(a){return this.a.I[3][a>>1&7]};h.Le=function(a,b){this.a.I[3][b>>1&7]=a&65295};h.Kd=function(a){return this.a.I[3][(a>>1&7)+8]};h.Je=function(a,b){this.a.I[3][(b>>1&7)+8]=a&65295};h.Ld=function(a){return this.a.ca[3][a>>1&7]};h.Ke=function(a,b){b=b>>1&7;this.a.ca[3][b]=a;this.a.I[3][b]&=65295};h.Jd=function(a){return this.a.ca[3][(a>>1&7)+8]};h.Ie=function(a,b){b=(b>>1&7)+8;this.a.ca[3][b]=a;this.a.I[3][b]&=65295};h.Ta=function(a){a&=7;return this.a.F&2048?this.a.Ja[a]:this.a.f[a]};
h.Wa=function(a,b){b&=7;this.a.F&2048?this.a.Ja[b]=a:this.a.f[b]=a};h.kd=function(){return this.a.F&49152?this.a.ra[0]:this.a.f[6]};h.je=function(a){this.a.F&49152?this.a.ra[0]=a:this.a.f[6]=a};h.nd=function(){return this.a.f[7]};h.me=function(a){this.a.f[7]=a};h.Ua=function(a){a&=7;return this.a.F&2048?this.a.f[a]:this.a.Ja[a]};h.Xa=function(a,b){b&=7;this.a.F&2048?this.a.f[b]=a:this.a.Ja[b]=a};h.ld=function(){return 1==(this.a.F&49152)>>14?this.a.f[6]:this.a.ra[1]};
h.ke=function(a){1==(this.a.F&49152)>>14?this.a.f[6]=a:this.a.ra[1]=a};h.md=function(){return 3==(this.a.F&49152)>>14?this.a.f[6]:this.a.ra[3]};h.le=function(a){3==(this.a.F&49152)>>14?this.a.f[6]=a:this.a.ra[3]=a};h.Vc=function(a){return this.a.hc[a-65504>>1]};h.Xd=function(a,b){this.a.hc[b-65504>>1]=a};h.dc=function(a){if(65520==a){a=0;switch(Lb){case Lb:a=this.g.Ib}a=(a>>6)-1}else a=0;return a};h.jc=function(){};h.Id=function(){return 1};h.He=function(){};h.Uc=function(){return this.a.ja};
h.Wd=function(){this.a.ja=0};h.ad=function(){return this.a.gc};h.ce=function(a,b){b&1||(a&=255);this.a.gc=a};h.fd=function(a,b){return b?0:this.a.Mb};h.fe=function(a){var b=this.a;if(a&=65024){var c=a>>9;do a+=34;while(c>>=1)}b.Mb=a;b.v|=2};h.Hd=function(a,b){return b?0:this.a.ib&65280};h.Ge=function(a){this.a.ib=a|255};h.jd=function(){return bc(this.a)};h.ie=function(a){cc(this.a,a&-1793|bc(this.a)&1792);this.a.v|=128};h.ic=function(){};
var L={},Zb=(L[61568]=[null,null,K.prototype.Nd,K.prototype.Me,"UNIMAP",64,1170],L[62592]=[null,null,K.prototype.Gd,K.prototype.Fe,"SIPDR",8,1145,64],L[62608]=[null,null,K.prototype.Ed,K.prototype.De,"SDPDR",8,1145,64],L[62624]=[null,null,K.prototype.Fd,K.prototype.Ee,"SIPAR",8,1145,64],L[62640]=[null,null,K.prototype.Dd,K.prototype.Ce,"SDPAR",8,1145,64],L[62656]=[null,null,K.prototype.Zc,K.prototype.ae,"KIPDR",8,1145,64],L[62672]=[null,null,K.prototype.Xc,K.prototype.Zd,"KDPDR",8,1145,64],L[62688]=
[null,null,K.prototype.Yc,K.prototype.$d,"KIPAR",8,1145,64],L[62704]=[null,null,K.prototype.Wc,K.prototype.Yd,"KDPAR",8,1145,64],L[62798]=[null,null,K.prototype.ed,K.prototype.ee,"MMR3",1,1145,64],L[65382]=[null,null,K.prototype.$c,K.prototype.be,"LKS"],L[65402]=[null,null,K.prototype.bd,K.prototype.de,"MMR0",1,1145,64],L[65404]=[null,null,K.prototype.cd,K.prototype.ic,"MMR1",1,1145,64],L[65406]=[null,null,K.prototype.dd,K.prototype.ic,"MMR2",1,1145,64],L[65408]=[null,null,K.prototype.Md,K.prototype.Le,
"UIPDR",8,1145,64],L[65424]=[null,null,K.prototype.Kd,K.prototype.Je,"UDPDR",8,1145,64],L[65440]=[null,null,K.prototype.Ld,K.prototype.Ke,"UIPAR",8,1145,64],L[65456]=[null,null,K.prototype.Jd,K.prototype.Ie,"UDPAR",8,1145,64],L[65472]=[null,null,K.prototype.Ta,K.prototype.Wa,"R0SET0"],L[65473]=[null,null,K.prototype.Ta,K.prototype.Wa,"R1SET0"],L[65474]=[null,null,K.prototype.Ta,K.prototype.Wa,"R2SET0"],L[65475]=[null,null,K.prototype.Ta,K.prototype.Wa,"R3SET0"],L[65476]=[null,null,K.prototype.Ta,
K.prototype.Wa,"R4SET0"],L[65477]=[null,null,K.prototype.Ta,K.prototype.Wa,"R5SET0"],L[65478]=[null,null,K.prototype.kd,K.prototype.je,"R6KERNEL"],L[65479]=[null,null,K.prototype.nd,K.prototype.me,"R7KERNEL"],L[65480]=[null,null,K.prototype.Ua,K.prototype.Xa,"R0SET1",1,1145],L[65481]=[null,null,K.prototype.Ua,K.prototype.Xa,"R1SET1",1,1145],L[65482]=[null,null,K.prototype.Ua,K.prototype.Xa,"R2SET1",1,1145],L[65483]=[null,null,K.prototype.Ua,K.prototype.Xa,"R3SET1",1,1145],L[65484]=[null,null,K.prototype.Ua,
K.prototype.Xa,"R4SET1",1,1145],L[65485]=[null,null,K.prototype.Ua,K.prototype.Xa,"R5SET1",1,1145],L[65486]=[null,null,K.prototype.ld,K.prototype.ke,"R6SUPER",1,1145],L[65487]=[null,null,K.prototype.md,K.prototype.le,"R6USER",1,1145],L[65504]=[null,null,K.prototype.Vc,K.prototype.Xd,"CTRL",8,1170],L[65520]=[null,null,K.prototype.dc,K.prototype.jc,"LSIZE",1,1170],L[65522]=[null,null,K.prototype.dc,K.prototype.jc,"HSIZE",1,1170],L[65524]=[null,null,K.prototype.Id,K.prototype.He,"SYSID",1,1170],L[65526]=
[null,null,K.prototype.Uc,K.prototype.Wd,"CPUERR",1,1170],L[65528]=[null,null,K.prototype.ad,K.prototype.ce,"MB",1,1170],L[65530]=[null,null,K.prototype.fd,K.prototype.fe,"PIR"],L[65532]=[null,null,K.prototype.Hd,K.prototype.Ge,"SL"],L[65534]=[null,null,K.prototype.jd,K.prototype.ie,"PSW"],L);
Ja(function(){for(var a=D(document,"pdp11","device"),b=0;b<a.length;b++){var c,d=a[b];c=B(d);switch(c.type){case "default":c=new K(c);C(c,d);break;case "pc11":c=new dc(c);C(c,d);break;case "rl11":c=new M(c);C(c,d);break;case "rk11":c=new N(c),C(c,d)}}});var ec;if($a){var fc=new ArrayBuffer(2);(new DataView(fc)).setUint16(0,256,!0);ec=256===(new Uint16Array(fc))[0]}else ec=!1;var gc=ec;
function H(a,b,c,d,e,f){this.g=a;this.id=hc+=2;this.a=null;this.Pa=b;this.yb=c;this.size=d||0;this.type=e||ic;this.l=e==jc;this.controller=null;Db(this);this.za=this.Dc=!1;if(this.size)if(f)this.controller=f,a=[null,0],this.a=a[0],kc(this,f.xc);else if($a)this.b=new ArrayBuffer(this.size),this.c=new DataView(this.b,0,this.size),this.j=new Uint8Array(this.b,0,this.size),this.s=new Uint16Array(this.b,0,this.size>>1),this.a=new Int32Array(this.b,0,this.size>>2),kc(this,gc?lc:mc);else{a=this.a=Array(this.size>>
2);for(f=0;f<a.length;f++)a[f]=0;kc(this,nc)}else kc(this)}var ic=0,Lb=1,jc=2,Jb=4,Mb=["NONE","RAM","ROM","VID","H/W"],hc=0;
H.prototype={constructor:H,parent:null,save:function(){var a,b;if(this.controller)a=null;else if($a)for(a=Array(this.size>>2),b=0;b<a.length;b++)a[b]=this.c.getInt32(b<<2,!0);else a=this.a;return a},restore:function(a){if(this.controller)return!a;if(a&&this.size==a.length<<2){var b;if($a)for(b=0;b<a.length;b++)this.c.setInt32(b<<2,a[b],!0);else this.a=a;return this.za=!0}return!1},u:function(a,b){I(this.g,b,32);return 255},h:function(a,b,c){I(this.g,c,32)},w:function(a,b){return this.Lb(a++,b++)|
this.Lb(a,b)<<8},A:function(a,b,c){this.Qb(a++,b&255,c++);this.Qb(a,b>>8,c)},P:function(a){return this.a[a>>2]>>>((a&3)<<3)&255},la:function(a,b){a&1&&I(this.g,b,64);b=a>>2;a=(a&3)<<3;var c=this.a[b]>>a;return 24>a?c&65535:c&255|(this.a[b+1]&255)<<8},ua:function(a,b){var c=a>>2;a=(a&3)<<3;this.a[c]=this.a[c]&~(255<<a)|b<<a;this.za=!0},ya:function(a,b,c){a&1&&I(this.g,c,64);c=a>>2;a=(a&3)<<3;24>a?this.a[c]=this.a[c]&~(65535<<a)|b<<a:(this.a[c]=this.a[c]&16777215|b<<24,c++,this.a[c]=this.a[c]&-256|
b>>8);this.za=!0},G:function(a,b){return this.K(a,b)},V:function(a,b){return this.ec(a,b)},ta:function(a,b,c){this.l?this.h(a,b,c):this.Rb(a,b,c)},wa:function(a,b,c){this.l?this.h(a,b,c):this.kc(a,b,c)},D:function(a){return this.j[a]},N:function(a){return this.j[a]},U:function(a,b){a&1&&I(this.g,b,64);return this.c.getUint16(a,!0)},ka:function(a,b){a&1&&I(this.g,b,64);return this.s[a>>1]},sa:function(a,b){this.j[a]=b;this.za=!0},Ca:function(a,b){this.j[a]=b;this.za=!0},va:function(a,b,c){a&1&&I(this.g,
c,64);this.c.setUint16(a,b,!0);this.za=!0},xa:function(a,b,c){a&1&&I(this.g,c,64);this.s[a>>1]=b;this.za=!0}};function Db(a,b,c){a.H=b;a.i=a.m=0;c&&((a.i=c.i)&&oc(a,pc,!1),(a.m=c.m)&&sc(a,pc,!1))}function sc(a,b,c){c&&a.m||(a.Qb=!a.l&&b[1]||a.h,a.zb=!a.l&&b[3]||a.A);if(c||void 0===c)a.Rb=b[1]||a.h,a.kc=b[3]||a.A}function oc(a,b,c){c&&a.i||(a.Lb=b[0]||a.u,a.Y=b[2]||a.w);if(c||void 0===c)a.K=b[0]||a.u,a.ec=b[2]||a.w}function kc(a,b){b||(b=tc);oc(a,b,void 0);sc(a,b,void 0)}
var tc=[],nc=[H.prototype.P,H.prototype.ua,H.prototype.la,H.prototype.ya],pc=[H.prototype.G,H.prototype.ta,H.prototype.V,H.prototype.wa];if($a)var mc=[H.prototype.D,H.prototype.sa,H.prototype.U,H.prototype.va],lc=[H.prototype.N,H.prototype.Ca,H.prototype.ka,H.prototype.xa];
function uc(a,b){x.call(this,"CPU",a,uc,1);b=a.cycles||b;var c=a.multiplier||1;this.Bb=0;this.qb=b;this.xa=c;this.Db=Math.round(this.qb/1E4)/100;this.Ma=this.Db*this.xa;this.o.T=!1;this.o.Ob=!1;this.o.cb=a.autoStart;this.o.tb=!1;this.ob=this.Na=0;this.pb=a.csStart;this.Za=a.csInterval;this.$a=a.csStop;this.N=[];this.cc=this.Rd.bind(this);E(this)}z(uc);var vc=["power","reset"];h=uc.prototype;
h.fa=function(a,b,c,d){this.l=a;this.g=b;this.H=d;this.w=a.w;for(b=0;b<vc.length;b++)(c=this.j[vc[b]])&&this.l.aa(null,vc[b],c);a=wc(a,"autoStart");null!=a&&(this.o.cb="true"==a?!0:"false"==a?!1:!!a);E(this)};h.reset=function(){};h.save=function(){return null};h.restore=function(){return!1};h.ha=function(a,b){if(!b){if(a&&this.restore){xc(this);if(!this.restore(a))return!1;yc(this)}else this.reset();this.X("No debugger detected")}return!0};h.ga=function(a){return a?this.save():!0};
h.cb=function(){return this.o.cb||void 0===this.j.run?(pb(this),!0):!1};h.Zb=function(){return 0};function yc(a){void 0===a.pb&&(a.pb=0);void 0===a.Za&&(a.Za=-1);void 0===a.$a&&(a.$a=-1);a.o.tb=0<=a.pb&&0<a.Za;a.o.tb&&(a.ob=0,a.Na=a.pb-a.ya)}function sb(a,b){if(a.o.tb){var c=!1;a.ob=a.ob+a.Zb()|0;a.Na-=b;0>=a.Na&&(a.Na+=a.Za,c=!0);0<=a.$a&&a.$a<=zc(a)&&(a.Za=a.$a=-1,yc(a),F(a),c=!0);c&&a.X(zc(a)+" cycles: checksum="+q(a.ob))}}
h.aa=function(a,b,c){var d=this;switch(b){case "power":case "reset":return this.j[b]=c,!0;case "run":return this.j[b]=c,c.onclick=function(){var a;if(a=d.l)if(a=d.l,a.o.R)a=!0;else{var b=null,c,k=A(a.id);for(c=0;c<k.length&&(b=k[c],b===a||b.o.ready);c++);if(c==k.length)for(c=0;c<k.length&&(b=k[c],b===a||b.o.R);c++);c==k.length&&(b=a);w("The "+b.type+" component ("+b.id+") is not "+(b.o.ready?"powered yet":"ready yet"+(b.vb?" (waiting for notification)":""))+".");a=!1}a&&(d.o.T?F(d):pb(d))},!0;case "speed":return this.j[b]=
c,!0;case "setSpeed":return this.j[b]=c,c.onclick=function(){Ac(d,d.xa<<1,!0)},c.textContent=this.Ma.toFixed(2)+"Mhz",!0}return!1};h.Ba=function(a){this.l&&this.l.Ba(a)};function rb(a,b,c){a.ya+=b;c&&(a.wa=a.a=a.K=0)}function Bc(a,b){var c=1;b&&1<a.xa&&a.La&&(c=a.La/a.Db);a.$b=Math.round(1E3/30);a.rb=Math.floor(a.qb/30*c);b||(a.ab=a.rb);a.Ab=0}function zc(a){return a.ya+a.ta+a.wa-a.a}function xc(a){a.La=0;a.ac=0;a.ya=a.ta=a.wa=a.a=a.K=0;yc(a);Ac(a,1)}
function Ac(a,b,c){if(void 0!==b){.8>a.La/a.Ma&&(b=1);a.xa=b;b=a.Db*a.xa;if(a.Ma!=b){a.Ma=b;b=a.Ma.toFixed(2)+"Mhz";var d=a.j.setSpeed;d&&(d.textContent=b);a.X("target speed: "+b)}c&&a.l&&Cc(a.l)}rb(a,a.ta);a.ta=0;a.la=ra();a.va=0;Bc(a)}function Vb(a,b){var c=a.N.length;a.N.push([-1,b]);return c}function Xb(a,b,c,d){0<=b&&b<a.N.length&&(d||0>a.N[b][0])&&(c=a.qb*a.xa/1E3*c|0,a.o.T&&(c+=Dc(a)),a.N[b][0]=c)}
function qb(a,b){for(var c=a.N.length-1;0<=c;c--){var d=a.N[c];0>d[0]||(d[0]-=b,0>=d[0]&&(d[0]=-1,d[1]()))}}function Dc(a,b){var c=a.wa-=a.a;a.a=a.K=0;b&&(a.wa=0);return c}
h.Rd=function(){if(this.o.T){this.Ab>=this.qb&&Bc(this,!0);this.bb=0;this.nb=ra();if(this.va){var a=this.nb-this.va;a>this.$b&&(this.la+=a,this.la>this.nb&&(this.la=this.nb))}try{do{for(var b,c=this.o.tb?1:this.rb,d=this.N.length-1;0<=d;d--){var e=this.N[d];0>e[0]||c>e[0]&&(c=e[0])}b=c;try{this.xb(b)}catch(f){if("number"!=typeof f)throw f;}b=Dc(this,!0);this.bb+=b;this.ta+=b;sb(this,b);qb(this,b);this.ab-=b;if(0>=this.ab){this.ab+=this.rb;15<=++this.ac&&(this.Ba(),this.ac=0);break}}while(this.o.T)}catch(f){F(this);
this.l&&this.l.stop(ra(),zc(this));Za(this,f.stack||f.message);return}if(this.o.T){a=setTimeout;b=this.cc;this.va=ra();c=this.$b;this.bb&&(c=Math.round(c*this.bb/this.rb));c-=this.va-this.nb;if(d=this.va-this.la)this.La=Math.round(this.ta/(10*d))/100,864E5<=d&&(this.ya=0,Ac(this));if(0>c||this.La<this.Ma)-1E3>c&&(this.la-=c),c=0;this.Ab+=this.bb;this.va+=c;a(b,c)}}};
function pb(a){var b;a.o.error?(a.X(a.toString()+" error"),b=!0):b=!1;if(!b)if(a.o.T)a.X(a.toString()+" busy");else{Ac(a);a.o.T=!0;a.o.Ob=!0;if(b=a.j.run)b.textContent="Halt";a.l&&a.l.start(a.la,zc(a));setTimeout(a.cc,0)}}h.xb=function(){return 0};function F(a){var b=!1;if(a.o.T){Dc(a);rb(a,a.ta);a.ta=0;a.o.T=!1;if(b=a.j.run)b.textContent="Run";a.l&&a.l.stop(ra(),zc(a));b=!0}a.o.complete=void 0;return b}
function Ec(a){this.Ra=+a.model||1170;this.Wb=a.addrReset||0;uc.call(this,a,6666667);this.sb=0;this.Yb=255;1120==this.Ra?(this.decode=Fc.bind(this),this.Ka=this.Bc,this.sb=8,this.Yb=-1):(this.decode=Gc.bind(this),this.Ka=this.Cc);Hc(this);this.sa=0;this.U=null;this.o.complete=!1}z(Ec,uc);h=Ec.prototype;h.reset=function(){this.status("model "+this.Ra);this.o.T&&F(this);Hc(this);xc(this);this.o.error=!1;this.parent.reset.call(this)};
function Hc(a){a.m=65536;a.h=32768;a.i=65535;a.s=32768;a.F=15;a.f=[0,0,0,0,0,0,0,a.Wb,-1,-2,-3,-4,-5,-6,-7,-8];a.Ja=[0,0,0,0,0,0];a.ra=[0,0,0,0];a.u=0;a.mb=0;a.Ic=[4,2,0,1];a.I=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.ca=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0]];a.kb=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];a.hc=[0,0,0,0,0,0,0,0];a.gc=0;a.v=0;a.D=a.G=0;a.c=a.b=a.Cb=0;a.Oa=-1;ob(a)}function ob(a){a.Z=0;a.Eb=0;a.Gb=0;a.Ea=0;a.ja=0;a.Mb=0;a.ib=255;a.ka=0;a.lb=0;a.Ya=262143;a.fb=0;a.A=0;a.U=null;a.g&&ac(a)}function ac(a){a.ka?(a.V=65536,a.Ub=a.Ea&16?4186112:253952,a.P=a.Fc,a.Y=a.Od,a.zb=a.Ne,Fb(a.g,a.Ea&16?22:18)):(a.V=0,a.Ub=57344,a.P=a.Ec,a.Y=a.fc,a.zb=a.lc,Fb(a.g,16))}
function $b(a,b){b&=-3073;if(a.Z!=b){b&57344&&!(a.Z&57344)&&(a.Eb=a.A>>16&65535,a.Gb=a.A&65535);a.Z=b;a.lb=b>>5&3;a.mb=b>>1&15;var c=0;b&257&&(c=4,b&1&&(c|=2));a.ka!=c&&(a.ka=c,ac(a))}}h.Zb=function(){return 0};h.save=function(){var a=new O(this);a.set(0,[]);a.set(1,[this.ya,this.xa]);a.set(2,Sb(this.g));return a.data()};
h.restore=function(a){var b=a[1];this.ya=b[1];Ac(this,b[3]);a:{b=this.g;a=a[2];var c;for(c=0;c<a.length-1;c+=2){var d=a[c],e=a[c+1];if(e&&e.length<b.G){for(var f=0,g=Array(b.G),k=0;k<e.length-1;)for(var l=e[k++],n=e[k++];l--;)g[f++]=n;e=g}f=b.g[d];if(!f||!f.restore(e)){w("Unable to restore memory block "+d);b=!1;break a}}b=!0}return b};function P(a){return a.m&65536?1:0}function Ic(a){return a.s&32768?8:0}function Jc(a){var b=a.f[7];a.A=b;var c=a.Y(b);a.f[7]=b+2&65535;return c}
function Kc(a,b){var c=a.f[7];a.f[7]=c+b&65535;return c}function Q(a,b){a.f[7]=b&65535}function Yb(a,b,c){return{Ud:a,Sa:b,message:c||0,next:null}}function Lc(a,b){var c=a.U;if(c==b)a.U=b.next;else for(;c;){a=c.next;if(a==b){c.next=a.next;break}c=a}}function Wb(a,b){if(b!=a.U){var c=a.U;if(!c||c.Sa<=b.Sa)b.next=c,a.U=b;else{do{var d=c.next;if(!d||d.Sa<=b.Sa){b.next=d;c.next=b;break}c=d}while(c)}}a.v|=1}
function Mc(a){return a.v&64?(J(a,168,64,-5),!0):a.v&32?(J(a,4,32,-4),!0):a.v&16?(J(a,12,16,-6),!0):!1}function bc(a){return a.F=a.F&63728|Ic(a)|(a.i&65535?0:4)|(a.h&32768?2:0)|P(a)}function cc(a,b){a.s=b<<12;a.i=~b&4;a.h=b<<14;a.m=b<<16;if((b^a.F)&2048)for(var c=a.Ja.length;0<=--c;){var d=a.f[c];a.f[c]=a.Ja[c];a.Ja[c]=d}a.u=b>>14&3;c=a.F>>14&3;a.u!=c&&(a.ra[c]=a.f[6],a.f[6]=a.ra[a.u]);a.F=b;a.v|=2}function R(a,b){a.v&128||(a.s=a.i=b,a.h=0)}function Nc(a,b,c){a.v&128||(a.s=a.i=a.m=b,a.h=c||0)}
function Oc(a,b,c,d){a.v&128||(a.s=a.i=a.m=b,a.h=(c^b)&(d^b))}function Pc(a,b){a.v&128||(a.s=a.i=a.m=b,a.h=a.s^a.m>>1)}function Qc(a,b,c,d){a.v&128||(a.s=a.i=a.m=b,a.h=(c^d)&(d^b))}function J(a,b,c,d){if(!a.sa){0>a.Oa?a.Oa=bc(a):a.u||(d=-3);var e=!1;-3==d&&(b=4,a.ja|=4,a.f[6]=4,e=!0);a.A=b|4143316992;a.u=0;var f=a.Y(b|a.V),g=a.Y(b+2&65535|a.V);cc(a,g&-12289|a.Oa>>2&12288);Rc(a,a.Oa,e);Rc(a,a.f[7],e);Q(a,f);a.v&=~(c|18);a.v|=9;a.Oa=-1;if(-3<=d)throw b;}}
function Sc(a){var b=Tc(a),c=Tc(a)&-1793;a.F&49152&&(c=c&-225|a.F&63712);Q(a,b);cc(a,c);a.v&=-17}function Ob(a,b){var c=b>>13&31;31>c&&(b=a.Ea&32?a.kb[c]+(b&8190)&4194302:b&-3932161);return b}
function Uc(a,b,c){var d,e,f;if(!(c&a.ka))return f=b&65535,57344<=f&&(f|=a.Ub),f;d=b>>13;a.Ea&a.Ic[a.u]||(d&=7);e=a.I[a.u][d];f=(a.ca[a.u][d]<<6)+(b&8191)&a.Ya;if(a.sa)return f;f&1&&!(c&1)&&(a.ja|=64,J(a,4,0,f));var g=0;switch(e&7){case 1:g=4096;case 2:e|=128;c&4&&(g=8192);break;case 4:g=4096;case 5:c&4&&(g=4096);case 6:e|=c&4?192:128;break;default:g=32768}32512!=(e&32520)&&(e&8?e&32512&&(b&8128)<(e>>2&8128)&&(g|=16384):(b&8128)>(e>>2&8128)&&(g|=16384));a.I[a.u][d]=e;if(f!=(4194170&a.Ya)||a.u)a.lb=
a.u,a.mb=d;g&&(g&57344&&(0<=a.Oa&&(g|=128),a.Z&57344||(g|=a.Z&4096|a.lb<<5|a.mb<<1,$b(a,a.Z&-61695|g&61694)),J(a,168,64,-1)),a.Z&61440||!(f<(4191360&a.Ya)||f>(4194239&a.Ya))||(a.Z|=4096,a.Z&512&&(a.v|=64)));return f}function Tc(a){var b=a.Y(a.f[6]|a.V);a.f[6]=a.f[6]+2&65535;return b}function Rc(a,b,c){var d=a.f[6]-2&65535;a.f[6]=d;a.A=a.A&65535|(a.A&-65536)<<8|16121856;c||a.Ka(4,-2,d);a.zb(d,b)}
function Vc(a,b,c,d){var e,f,g=d&8?0:a.V;switch(b){case 0:return J(a,4,0,-2),0;case 1:return 6==c&&a.Ka(d,0,a.f[6]),a.a-=3,7==c?a.f[c]:a.f[c]|g;case 2:f=2;e=a.f[c];6==c&&a.Ka(d,f,e);7!=c&&(e|=g,6>c&&d&1&&(f=1));a.a-=3;break;case 3:f=2;e=a.f[c];7!=c&&(e|=g);e=a.Y(e);e|=g;a.a-=7;break;case 4:f=-2;6>c&&d&1&&(f=-1);e=a.f[c]+f&65535;6==c&&a.Ka(d,f,e);7!=c&&(e|=g);a.a-=4;break;case 5:f=-2;e=a.f[c]-2&65535;7!=c&&(e|=g);e=a.Y(e)|g;a.a-=8;break;case 6:return e=a.Y(Kc(a,2)),e=e+a.f[c]&65535,6==c&&a.Ka(d,0,
e),a.a-=6,e|g;case 7:return e=a.Y(Kc(a,2)),e=e+a.f[c]&65535,e=a.Y(e|a.V),a.a-=10,e|g}a.f[c]=a.f[c]+f&65535;a.A=a.A&65535|(a.A&-65536)<<8|(f<<3&248|c)<<16;return e}h.Bc=function(a,b,c){!this.u&&0>=b&&c<=this.ib&&(this.v|=32)};h.Cc=function(a,b,c){this.u||(65534<=c&&(c|=-65536),a&4&&c<=this.ib&&(c<=this.ib-32?J(this,4,0,-3):(this.ja|=8,this.v|=32)))};h.Qa=function(a){if(!this.ka)return this.g.Qa(a);this.sa++;a=this.fc(Uc(this,a,2));this.sa--;return a};
h.jb=function(a,b){this.ka?(this.sa++,a=Uc(this,a,5),a&1&&this.a--,Qb(this.g,a,b),this.sa--):this.g.jb(a,b)};h.Va=function(a,b){this.ka?(this.sa++,this.lc(Uc(this,a,4),b),this.sa--):this.g.Va(a,b)};h.Ec=function(a,b,c){return Vc(this,a,b,c)};h.Fc=function(a,b,c){return Uc(this,Vc(this,a,b,c),c)};h.fc=function(a){return Pb(this.g,this.fb=a)};h.Od=function(a){return Pb(this.g,this.fb=Uc(this,a,2))};h.lc=function(a,b){Rb(this.g,this.fb=a,b&65535)};h.Ne=function(a,b){Rb(this.g,this.fb=Uc(this,a,4),b)};
function Wc(a,b,c){var d=a.b=b&7;(b=a.c=(b&56)>>3)?(d=Vc(a,b,d,2),c&65536||61440!==(a.F&61440)&&(d&=65535),a.u=a.F>>12&3,c=a.Y(d|c&a.V),a.u=a.F>>14&3):c=6!=d||(a.F>>2&12288)===(a.F&12288)?a.f[d]:a.ra[a.F>>12&3];return c}function Xc(a,b,c,d){a.A=a.A&65535|1441792;var e=a.b=b&7;(b=a.c=(b&56)>>3)?(e=Vc(a,b,e,4),c&65536||(e&=65535),a.u=a.F>>12&3,e=Uc(a,e|c&65536,4),a.u=a.F>>14&3,Rb(a.g,e,d)):6!=e||(a.F>>2&12288)===(a.F&12288)?a.f[e]=d:a.ra[a.F>>12&3]=d}
function Yc(a,b){b>>=6;var c=a.G=b&7;(b=a.D=(b&56)>>3)?(c=a.P(b,c,3),a=Nb(a.g,c)):a=a.f[c+a.sb]&a.Yb;return a}function Zc(a,b){b>>=6;var c=a.G=b&7;return(b=a.D=(b&56)>>3)?Pb(a.g,a.P(b,c,2)):a.f[c+a.sb]}function $c(a,b){var c=a.b=b&7;b=a.c=(b&56)>>3;return Vc(a,b,c,8)}function ad(a,b){var c=a.b=b&7;(b=a.c=(b&56)>>3)?(c=a.P(b,c,3),a=Nb(a.g,c)):a=a.f[c]&255;return a}function bd(a,b){var c=a.b=b&7;return(b=a.c=(b&56)>>3)?Pb(a.g,a.P(b,c,2)):a.f[c]}
function S(a,b,c,d){var e=a.b=b&7;(b=a.c=(b&56)>>3)?(e=a.Cb=a.P(b,e,7),c=0>c?a.f[-c-1]&255:c,c=d.call(a,c,Nb(a.g,e)),e&1&&a.a--,Qb(a.g,e,c)):(b=a.f[e],c=0>c?a.f[-c-1]&255:c,a.f[e]=b&65280|d.call(a,c,b&255))}function T(a,b,c,d){var e=a.b=b&7;(b=a.c=(b&56)>>3)?(e=a.P(b,e,6),Rb(a.g,e,d.call(a,0>c?a.f[-c-1]:c,Pb(a.g,e)))):a.f[e]=d.call(a,0>c?a.f[-c-1]:c,a.f[e])}
function cd(a,b,c,d){var e=a.b=b&7;(b=a.c=(b&56)>>3)?(d=a.P(b,e,5),e=c=0>c?a.f[-c-1]&255:c,d&1&&a.a--,Qb(a.g,d,e)):c?(c=0>c?a.f[-c-1]&255:c,a.f[e]=a.f[e]&~d|c<<24>>24&d):a.f[e]&=~d;return c}function dd(a,b,c){var d=a.b=b&7;(b=a.c=(b&56)>>3)?(d=a.P(b,d,4),Rb(a.g,d,c=0>c?a.f[-c-1]:c)):a.f[d]=c=0>c?a.f[-c-1]:c;return c}function V(a,b,c){c&&(Q(a,a.f[7]+(b<<24>>23)),a.a-=2);a.a-=3}
h.xb=function(a){this.o.complete=!0;var b=a?this.o.Ob?0:1:-1;this.o.Ob=!1;this.wa=this.a=a;do{if(this.v){if(a=this.v&7){a=!1;if(this.v&2){this.v&=-3;var c=160,d=(this.Mb&224)>>5,e=this.U&&this.U.Sa>d?this.U:null;e&&(c=e.Ud,d=e.Sa);d>(this.F&224)>>5?(this.v&4&&(Kc(this,2),this.v&=-5),J(this,c,0,-9),d=!0):d=!1;d&&(e&&Lc(this,e),a=!0)}else this.v&1&&this.v++;a=a&&0>b}if(a)break;if(this.v&112&&Mc(this)&&0>b)break}this.v=this.v&7|this.F&16;this.decode(Jc(this))}while(0<this.a);return this.o.complete?this.wa-
this.a:void 0===this.o.complete?0:-1};Ja(function(){for(var a=D(document,"pdp11","cpu"),b=0;b<a.length;b++){var c=a[b],d=B(c),d=new Ec(d);C(d,c)}});function ed(a,b){var c=b+a;Oc(this,c,a,b);return c&65535}function fd(a,b){var c=b+a;Oc(this,c<<8,a<<8,b<<8);return c&255}function gd(a,b){a=b<<1;Pc(this,a);return a&65535}function hd(a,b){a=b<<1;Pc(this,a<<8);return a&255}function id(a,b){a=b&32768|b>>1|b<<16;Pc(this,a);return a&65535}function jd(a,b){a=b&128|b>>1|b<<8;Pc(this,a<<8);return a&255}
function kd(a,b){a=b&~a;R(this,a);return a}function ld(a,b){a=b&~a;R(this,a<<8);return a}function md(a,b){a|=b;R(this,a);return a}function nd(a,b){a|=b;R(this,a<<8);return a}function od(a,b){a=~b|65536;Nc(this,a);return a&65535}function pd(a,b){a=~b|256;Nc(this,a<<8);return a&255}function qd(a,b){a=b-a;this.v&128||(this.s=this.i=a,this.h=b&(b^a));return a&65535}function rd(a,b){a=b-a;var c=a<<8;b<<=8;this.v&128||(this.s=this.i=c,this.h=b&(b^c));return a&255}
function sd(a,b){a=b+a;this.v&128||(this.s=this.i=a,this.h=a&(b^a));return a&65535}function td(a,b){a=b+a;var c=a<<8;this.v&128||(this.s=this.i=c,this.h=c&(b<<8^c));return a&255}function ud(a,b){a=-b;Nc(this,a,a&b&32768);return a&65535}function vd(a,b){a=-b;Nc(this,a<<8,(a&b&128)<<8);return a&255}function wd(a,b){a=b<<1|this.m>>16&1;Pc(this,a);return a&65535}function xd(a,b){a=b<<1|this.m>>16&1;Pc(this,a<<8);return a&255}function yd(a,b){a=(this.m&65536|b)>>1|b<<16;Pc(this,a);return a&65535}
function zd(a,b){a=((this.m&65536)>>8|b)>>1|b<<8;Pc(this,a<<8);return a&255}function Ad(a,b){var c=b-a;Qc(this,c,a,b);return c&65535}function Bd(a,b){var c=b-a;Qc(this,c<<8,a<<8,b<<8);return c&255}function Cd(a,b){this.v&128||(this.s=this.i=b&65280,this.h=this.m=0);return(b<<8|b>>8)&65535}function Dd(a,b){a^=b;R(this,a);return a&65535}function Ed(a){T(this,a,Zc(this,a),ed);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}
function Fd(a){var b=bd(this,a);a=a>>6&7;var c=this.f[a];c&32768&&(c|=4294901760);this.m=this.h=0;b&=63;if(b&32)b=64-b,16<b&&(b=16),this.m=c<<17-b,c>>=b;else if(b)if(16<b)this.h=c,c=0;else{this.m=c<<=b;var d=c>>15&65535;d&&65535!==d&&(this.h=32768)}this.f[a]=c&65535;this.s=this.i=c;this.a-=(this.c?6:7)+b}
function Gd(a){var b=bd(this,a);a=a>>6&7;var c=this.f[a]<<16|this.f[a|1];this.m=this.h=0;b&=63;if(b&32){b=64-b;32<b&&(b=32);var d=c>>b-1;this.m=d<<16;d>>=1;c&2147483648&&(d|=4294967295<<32-b)}else b?(d=c<<b-1,this.m=d>>15,d<<=1,32<b&&(b=32),(c>>=32-b)&&4294967295!==(c|4294967295<<b&4294967295)&&(this.h=32768)):d=c;this.f[a]=d>>16&65535;this.f[a|1]=d&65535;this.s=d>>16;this.i=d>>16|d;this.a-=(this.c?6:7)+b}function Hd(a){V(this,a,!P(this))}function Id(a){V(this,a,P(this))}
function Jd(a){T(this,a,Zc(this,a),kd);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}function Kd(a){S(this,a,Yc(this,a),ld);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}function Ld(a){T(this,a,Zc(this,a),md);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}function Md(a){S(this,a,Yc(this,a),nd);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}
function Nd(a){var b=Zc(this,a);a=bd(this,a);R(this,(0>b?this.f[-b-1]:b)&a);this.a-=this.c?4+(this.G&&6<=this.b?1:0):(this.D?4:3)+(7==this.b?2:0)}function Od(a){var b=Yc(this,a);a=ad(this,a);R(this,((0>b?this.f[-b-1]&255:b)&a)<<8);this.a-=this.c?4+(this.G&&6<=this.b?1:0):(this.D?4:3)+(7==this.b?2:0)}function Pd(a){V(this,a,this.i&65535?0:4)}function Qd(a){V(this,a,!Ic(this)==!(this.h&32768))}function Rd(a){V(this,a,!!(this.i&65535)&&!Ic(this)==!(this.h&32768))}
function Sd(a){V(this,a,!P(this)&&!!(this.i&65535))}function Td(a){V(this,a,(this.i&65535?0:4)||!Ic(this)!=!(this.h&32768))}function Ud(a){V(this,a,P(this)||(this.i&65535?0:4))}function Vd(a){V(this,a,!Ic(this)!=!(this.h&32768))}function Wd(a){V(this,a,Ic(this))}function Xd(a){V(this,a,!!(this.i&65535))}function Yd(a){V(this,a,!Ic(this))}function Zd(){J(this,12,0,-8);this.a-=5}function $d(a){V(this,a,!0)}function ae(a){V(this,a,!(this.h&32768))}function be(a){V(this,a,this.h&32768?2:0)}
function W(a){a&1&&(this.m=0);a&2&&(this.h=0);a&4&&(this.i=1);a&8&&(this.s=0);this.a-=5}function ce(a){var b=Zc(this,a);a=bd(this,a);var c=(b=0>b?this.f[-b-1]:b)-a;Qc(this,c,a,b);this.a-=this.c?4+(this.G&&6<=this.b?1:0):(this.D?4:3)+(7==this.b?2:0)}function de(a){var b=Yc(this,a);a=ad(this,a);var c=(b=(0>b?this.f[-b-1]&255:b)<<8)-(a<<=8);Qc(this,c,a,b);this.a-=this.c?4+(this.G&&6<=this.b?1:0):(this.D?4:3)+(7==this.b?2:0)}
function ee(a){var b=bd(this,a);if(b){a=a>>6&7;var c=this.f[a]<<16|this.f[a|1];this.m=this.h=0;b&32768&&(b|=-65536);var d=~~(c/b);-32768<=d&&32767>=d?(this.f[a]=d&65535,this.f[a|1]=c-d*b&65535,this.i=d>>16|d,this.s=d>>16):(this.h=32768,this.i=d>>15|d,this.s=c>>16,-1===b&&65534===this.f[a]&&(this.f[a]=this.f[a|1]=1));this.a-=53}else this.i=this.s=0,this.h=32768,this.m=65536,this.a-=7}function fe(){J(this,24,0,-8);this.a-=25}
function ge(){this.F&49152?(this.ja|=128,J(this,4,0,-7)):(this.w&&1120==this.Ra&&this.w.setData(this.f[0],!0),this.H?this.H.b():F(this));this.a-=7}function he(){J(this,16,0,-8);this.a-=25}var ie=[0,7,7,10,7,11,9,13];function je(a){this.K=this.a;Q(this,$c(this,a));this.a=this.K-ie[this.c]}var ke=[0,14,14,17,14,18,16,20];function le(a){this.K=this.a;var b=$c(this,a);a=a>>6&7;Rc(this,this.f[a]);this.f[a]=this.f[7];Q(this,b);this.a=this.K-ke[this.c]}var me=[3,9,9,13,10,14,12,16,4,9,9,13,10,14,13,17];
function ne(a){var b=Zc(this,a);this.K=this.a;R(this,dd(this,a,b));this.a=this.K-me[(this.D?8:0)+this.c]+(7!=this.b||this.c?0:2)}function oe(a){var b=Yc(this,a);R(this,cd(this,a,b,65535)<<8);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}var pe=[7,13,13,17,14,18,17,21];
function qe(a){var b=bd(this,a);a=a>>6&7;b&32768&&(b|=-65536);var c=this.f[a];c&32768&&(c|=-65536);b=~~(b*c);this.f[a]=b>>16&65535;this.f[a|1]=b&65535;this.v&128||(this.s=b>>16,this.i=this.s|b,this.h=0,this.m=-32768>b||32767<b?65536:0);this.a-=23}function re(){this.a-=5}function se(){this.F&49152||(this.g.reset(),ob(this),this.w&&this.w.setData(this.f[0],!0));this.a-=667}function te(a){if(a&8)J(this,8,0,-8);else{var b=Tc(this);a&=7;7==a?Q(this,b):(Q(this,this.f[a]),this.f[a]=b);this.a-=9}}
function ue(){Sc(this);this.a-=13}function X(a){a&1&&(this.m=65536);a&2&&(this.h=32768);a&4&&(this.i=0);a&8&&(this.s=32768);this.a-=5}function ve(a){var b=(a&448)>>6;if(this.f[b]=this.f[b]-1&65535)Q(this,this.f[7]-((a&63)<<1)),this.a+=1;this.a-=6}function we(a){T(this,a,Zc(this,a),Ad);this.a-=this.c?9+(this.G&&6<=this.b?1:0):(this.D?5:3)+(7==this.b?2:0)}function xe(a){T(this,a,0,Cd);this.a-=this.c?9:3+(7==this.b?2:0)}function ye(){J(this,28,0,-8);this.a-=5}
function ze(){this.w&&(this.w.ia=this.f[7],this.w.setData(this.f[0],!0));this.v|=4;Kc(this,-2);this.a-=3}function Ae(a){T(this,a,this.f[(a>>6&7)+this.sb],Dd);this.a-=this.c?9:3+(7==this.b?2:0)}function Y(){J(this,8,0,-8)}function Fc(a){Be[a>>12].call(this,a)}function Ce(a){De[a>>6&3].call(this,a)}function Ee(a){Fe[a>>6&3].call(this,a)}function Ge(a){He[a>>6&3].call(this,a)}function Ie(a){Je[a&15].call(this,a)}function Ke(a){Le[a&15].call(this,a)}function Me(a){Ne[a>>6&3].call(this,a)}
function Oe(a){Pe[a>>6&3].call(this,a)}function Qe(a){Re[a>>6&3].call(this,a)}
var Be=[function(a){Se[a>>8&15].call(this,a)},ne,ce,Nd,Jd,Ld,Ed,Y,function(a){Te[a>>8&15].call(this,a)},oe,de,Od,Kd,Md,we,Y],Se=[function(a){Ue[a>>4&15].call(this,a)},$d,Xd,Pd,Qd,Vd,Rd,Td,le,le,Ce,Ee,Ge,Y,Y,Y],De=[function(a){Nc(this,dd(this,a,0));this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,0,od);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,1,sd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,1,qd);this.a-=this.c?9:3+(7==this.b?2:0)}],Fe=[function(a){T(this,a,0,
ud);this.a-=this.c?11:6},function(a){T(this,a,P(this)?1:0,ed);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,P(this)?1:0,Ad);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){a=bd(this,a);Nc(this,a);this.a-=this.c?4:3+(7==this.b?2:0)}],He=[function(a){T(this,a,0,yd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,0,wd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,0,id);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){T(this,a,0,gd);this.a-=this.c?9:3+(7==this.b?2:0)}],
Ue=[function(a){Ve[a&15].call(this,a)},Y,Y,Y,je,je,je,je,te,Y,Ie,Ke,xe,xe,xe,xe],Ve=[ge,ze,ue,Zd,he,se,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y],Je=[re,function(){this.m=0;this.a-=5},function(){this.h=0;this.a-=5},W,function(){this.i=1;this.a-=5},W,W,W,function(){this.s=0;this.a-=5},W,W,W,W,W,W,W],Le=[re,function(){this.m=65536;this.a-=5},function(){this.h=32768;this.a-=5},X,function(){this.i=0;this.a-=5},X,X,X,function(){this.s=32768;this.a-=5},X,X,X,X,X,X,X],Te=[Yd,Wd,Sd,Ud,ae,be,Hd,Id,fe,ye,Me,Oe,Qe,Y,Y,Y],Ne=[function(a){Nc(this,
cd(this,a,0,255));this.a-=this.c?9:3+(7==this.b?2:0)},function(a){S(this,a,0,pd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){S(this,a,1,td);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){S(this,a,1,rd);this.a-=this.c?9:3+(7==this.b?2:0)}],Pe=[function(a){S(this,a,0,vd);this.a-=this.c?11:6},function(a){S(this,a,P(this)?1:0,fd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){S(this,a,P(this)?1:0,Bd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){a=ad(this,a);Nc(this,a<<8);this.a-=this.c?4:3+(7==
this.b?2:0)}],Re=[function(a){S(this,a,0,zd);this.a-=this.c?9+(this.Cb&1):3+(7==this.b?2:0)},function(a){S(this,a,0,xd);this.a-=this.c?9:3+(7==this.b?2:0)},function(a){S(this,a,0,jd);this.a-=this.c?9+(this.Cb&1):3+(7==this.b?2:0)},function(a){S(this,a,0,hd);this.a-=this.c?9:3+(7==this.b?2:0)}];function Gc(a){We[a>>12].call(this,a)}
var We=[function(a){Xe[a>>8&15].call(this,a)},ne,ce,Nd,Jd,Ld,Ed,function(a){Ye[a>>8&15].call(this,a)},function(a){Ze[a>>8&15].call(this,a)},oe,de,Od,Kd,Md,we,Y],Xe=[function(a){$e[a>>4&15].call(this,a)},$d,Xd,Pd,Qd,Vd,Rd,Td,le,le,Ce,Ee,Ge,function(a){af[a>>6&3].call(this,a)},Y,Y],af=[function(a){a=this.f[7]+((a&63)<<1)&65535;var b=this.Y(a|this.V);Q(this,this.f[5]);this.f[6]=a+2&65535;this.f[5]=b;this.a-=8},function(a){a=Wc(this,a,0);Rc(this,a);R(this,a);this.a-=11},function(a){var b=Tc(this);this.K=
this.a;Xc(this,a,0,b);R(this,b);this.a=this.K-pe[this.c]},function(a){R(this,dd(this,a,Ic(this)?65535:0));this.a-=this.c?9:3+(7==this.b?2:0)}],$e=[function(a){bf[a&15].call(this,a)},Y,Y,Y,je,je,je,je,te,function(a){a&8?(this.F&49152||(this.F=this.F&-2017|(a&7)<<5,this.v|=1),this.a-=5):J(this,8,0,-8)},Ie,Ke,xe,xe,xe,xe],bf=[ge,ze,function(){Sc(this);this.v|=this.F&16;this.a-=13},Zd,he,se,ue,function(){J(this,8,0,-8)},Y,Y,Y,Y,Y,Y,Y,Y],Ye=[qe,qe,ee,ee,Fd,Fd,Gd,Gd,Ae,Ae,Y,Y,Y,Y,ve,ve],Ze=[Yd,Wd,Sd,Ud,
ae,be,Hd,Id,fe,ye,Me,Oe,Qe,function(a){cf[a>>6&3].call(this,a)},Y,Y],cf=[Y,function(a){a=Wc(this,a,65536);Rc(this,a);R(this,a);this.a-=11},function(a){var b=Tc(this);this.K=this.a;Xc(this,a,65536,b);R(this,b);this.a=this.K-pe[this.c]},Y];
function df(a){x.call(this,"ROM",a,df,128);this.ba=this.c=null;this.i=a.addr;this.b=a.size;this.m=!1;this.h=a.alias;this.l=a.file;this.s=r(this.l);if(this.l){a=this.l;var b=la(this.s);"json"!=b&&"hex"!=b&&(a=ua()+"/api/v1/dump?file="+this.l+"&format=bytes&decimal=true");var c=this;t(a,null,!0,function(a,b,f){f?(c.C("Unable to load ROM resource (error "+f+": "+a+")"),c.l=null):(Ua(c.ua,a,b),(a=ta(a,b))?(c.c=a.L,c.ba=a.ba):c.l=null);ef(c)})}}z(df);h=df.prototype;
h.fa=function(a,b,c,d){this.g=b;this.a=c;this.H=d;ef(this)};h.ha=function(){this.ba&&(this.H&&this.H.a(this.id,this.i,this.b,this.ba),delete this.ba);return!0};h.ga=function(){return!0};
function ef(a){if(!Ya(a)){if(a.l){if(!a.c||!a.g)return;a.b||(a.b=a.c.length);if(a.c.length!=a.b)Za(a,"ROM size ("+q(a.c.length,8,!0)+") does not match specified size ("+q(a.b,8,!0)+")");else{var b;a:{b=a.i;a.status(a.b+"-byte ROM at "+ka(b));if(57344<=b&&b<57344+G){var c={};b=(c[b]=[df.prototype.Cd,df.prototype.Be,null,null,null,a.b>>1],c);if(fb(a.g,a,b)){b=a.m=!0;break a}}else if(Ib(a.g,b,a.b,jc)){for(c=0;c<a.c.length;c++)a.g.jb(b+c,a.c[c]);b=!0;break a}b=!1}if(b){b=[];"number"==typeof a.h?b.push(a.h):
null!=a.h&&a.h.length&&(b=a.h);for(c=0;c<b.length;c++){var d=a,e=b[c],f=Hb(d.g,d.i,d.b);Gb(d.g,e,d.b,f)}a.m||delete a.c}}}E(a)}}h.Cd=function(a){return this.c[a-this.i]};h.Be=function(){};Ja(function(){for(var a=D(document,"pdp11","rom"),b=0;b<a.length;b++){var c=a[b],d=B(c),d=new df(d);C(d,c)}});
function ff(a){x.call(this,"RAM",a,ff);this.ba=this.c=null;this.l=a.addr;this.i=a.size;this.na=a.load;this.ma=a.exec;this.h=!1;this.b=a.file;this.m=r(this.b);if(this.b){a=this.b;var b=la(this.m);"json"!=b&&"hex"!=b&&(a=ua()+"/api/v1/dump?file="+this.b+"&format=bytes&decimal=true");var c=this;t(a,null,!0,function(a,b,f){f?(c.C("Unable to load RAM resource (error "+f+": "+a+")"),c.b=null):(Ua(c.ua,a,b),(a=ta(a,b))?(c.c=a.L,c.ba=a.ba,null==c.na&&(c.na=a.na),null==c.ma&&(c.ma=a.ma)):c.b=null);gf(c)})}}
z(ff);ff.prototype.fa=function(a,b,c,d){this.g=b;this.a=c;this.H=d;gf(this)};ff.prototype.ha=function(){this.ba&&(this.H&&this.H.a(this.id,this.l,this.i,this.ba),delete this.ba);return!0};ff.prototype.ga=function(){return!0};function gf(a){if(a.g&&(!a.h&&a.i&&Ib(a.g,a.l,a.i,Lb)&&(a.h=!0),!Ya(a))){if(!a.h)w("No RAM allocated");else if(a.b){if(!a.c||!a.g)return;hf(a,a.c,a.na,a.ma,a.l)}E(a)}}
ff.prototype.reset=function(){if(this.h){for(var a=this.g,b=this.l,c=this.i,d=b&a.l,b=b>>>a.c;0<c&&b<a.g.length;){var e=a.g[b];if(e.controller&&a.i&&a.i.length==a.u.length){var f=a.i.indexOf(e);0<=f&&(e=a.u[f])}if(e){var f=c,g=0,k,d=d||0,g=g&255;void 0===f&&(f=e.size);if($a&&e.j)for(k=d;f--&&k<e.j.length;k++)e.j[k]=g;else for(k=d;f--&&k<e.size;k++)e.Rb(d,g,e.Pa+d)}c-=a.b;b++;d=0}this.c&&hf(this,this.c,this.na,this.ma,this.l,!0)}};
function hf(a,b,c,d,e,f){var g=!1;if(null==c)for(var k=0;k<b.length-1;){var l=b[k]&255|(b[k+1]&255)<<8;if(l)if(l&255){if(1!=l)break;if(k+6>=b.length)break;for(var k=k+2,n=b[k++]&255|(b[k++]&255)<<8,p=b[k++]&255|(b[k++]&255)<<8,l=l+((n&255)+(n>>8)+(p&255)+(p>>8)),u=k,v=n-=6;0<n&&k<b.length;)l+=b[k++]&255,n--;if(n||k>=b.length)break;l+=b[k++]&255;if(l&255)break;if(v)for(;v--;)a.a.jb(p++,b[u++]&255);else p&1?F(a.a):null==d&&(d=p);g=!0}else k++;else k+=2}if(!g&&(null==c&&(c=e),null!=c)){for(g=0;g<b.length;g++)a.a.jb(c+
g,b[g]);g=!0}g&&null!=d&&(a=a.a,a.Wb=d,a.g.reset(),ob(a),Q(a,d),cc(a,0),!f&&a.H&&(F(a)||a.H.c()));return g}Ja(function(){for(var a=D(document,"pdp11","ram"),b=0;b<a.length;b++){var c=a[b],d=B(c),d=new ff(d);C(d,c)}});function jf(a){x.call(this,"Keyboard",a,jf,1024);E(this)}z(jf);jf.prototype.aa=function(){return!1};jf.prototype.fa=function(a,b,c,d){this.l=a;this.a=c;this.H=d};Ja(function(){for(var a=D(document,"pdp11","keyboard"),b=0;b<a.length;b++){var c=a[b],d=B(c),d=new jf(d);C(d,c)}});
function Z(a){this.G=a.baudReceive||9600;this.V=a.baudTransmit||9600;this.U=a.upperCase;this.h=this.m=null;this.N=a.tabSize;this.K=a.charBOL;this.s=0;x.call(this,"SerialPort",a,Z,262144);var b=a.binding;if("console"==b)this.m="";else{var c;a=kf;b&&(void 0===c&&(c="Panel"),(c=Wa(c,this.id))&&(b=c.j[b])&&this.aa(null,a,b))}this.u=this.A=null;this.exports={connect:this.bc,receiveData:this.wb}}z(Z);var kf="buffer";h=Z.prototype;
h.aa=function(a,b,c){var d=this;switch(b){case kf:return this.j[b]=this.h=c,c.onkeydown=function(a){a=a||window.event;var b=!1,c=a.keyCode;8==c?(b=!0,c=ja.nc):a.ctrlKey&&c>=ja.Sb&&c<=ja.wc&&(b=!0,c-=ja.Sb-ja.mc);b&&(a.preventDefault&&a.preventDefault(),d.wb(c));return!0},c.onkeypress=function(a){a=a||window.event;d.wb(a.which||a.keyCode);a.preventDefault&&a.preventDefault();return!0},c.onpaste=function(a){a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();(a=a.clipboardData||
window.clipboardData)&&d.wb(a.getData("Text"))},c.removeAttribute("readonly"),!0}return!1};h.fa=function(a,b,c,d){this.l=a;this.g=b;this.a=c;this.H=d;var e=this;this.la=Yb(48,4,262144);this.P=Vb(this.a,function(){e.b&128||!e.i.length||(e.w=e.i.shift()&255,e.U&&97<=e.w&&122>e.w&&(e.w-=32),e.b|=128,e.b&64&&Wb(e.a,e.la))});this.D=Yb(52,4,262144);this.ka=Vb(this.a,function(){e.c|=128;e.c&64&&Wb(e.a,e.D)});fb(b,this,lf);hb(b,this.reset.bind(this));E(this)};
h.bc=function(){if(!this.u){var a=wc(this.l,"connection");if(a){var b=a.split("->");if(2==b.length){var c=pa(b[0]);if(c!=this.Ca)return;b=pa(b[1]);if(this.u=Va(b)){var d=this.u.exports;if(d){var e=d.connect;e&&e.call(this.u);if(this.A=d.receiveData){this.status(this.ua+"."+c+" connected to "+b);return}}}}this.status("Unable to establish connection: "+a)}}};h.ha=function(a,b){if(!b)if(this.bc(),!a||!this.restore)this.reset();else if(!this.restore(a))return!1;return!0};
h.ga=function(a){return a?this.save():!0};h.reset=function(){mf(this)};h.save=function(){var a=new O(this);a.set(0,[]);return a.data()};h.restore=function(){return mf(this)};function mf(a){a.w=0;a.b=0;a.c=128;a.i=[];return!0}h.wb=function(a){if("number"==typeof a)this.i.push(a);else if("string"==typeof a)for(var b=0,c,d=0;d<a.length;d++){c=b;b=a.charCodeAt(d);if(10==b){if(13==c)continue;b=13}this.i.push(b)}else this.i=this.i.concat(a);Xb(this.a,this.P,1E3/Math.round(this.G/10));return!0};
h.pd=function(){return this.b&65534};h.oe=function(a){this.b=this.b&-112|a&111};h.od=function(){this.b&=-129;0<this.i.length&&Xb(this.a,this.P,1E3/Math.round(this.G/10));return this.w};h.ne=function(){};h.Qd=function(){return this.c};h.Pe=function(a){this.c&128&&(a&64?Wb(this.a,this.D):Lc(this.a,this.D));this.c=this.c&-70|a&69};h.Pd=function(){return 0};
h.Oe=function(a){a&=255;this.A&&this.A.call(this.u,a);a&=127;if(this.h)if(13==a)this.s=0;else if(8==a)this.h.value=this.h.value.slice(0,-1),0<this.s&&this.s--;else{if(a){var b;b=(b=qa[a])?"<"+b+">":String.fromCharCode(a);var c=b.length;32>a&&1==c&&(c=0);9==a&&(a=this.N||8,c=a-this.s%a,this.N&&(b="                                        ".slice(0,c)));this.K&&!this.s&&c&&(b=String.fromCharCode(this.K)+b);this.h.value+=b;this.h.scrollTop=this.h.scrollHeight;this.s+=c}}else if(null!=this.m){if(10==a||
1024<=this.m.length)this.X(this.m),this.m="";10!=a&&(this.m+=String.fromCharCode(a))}this.c&=-129;Xb(this.a,this.ka,1E3/Math.round(this.V/10))};var nf={},lf=(nf[65392]=[null,null,Z.prototype.pd,Z.prototype.oe,"RCSR"],nf[65394]=[null,null,Z.prototype.od,Z.prototype.ne,"RBUF"],nf[65396]=[null,null,Z.prototype.Qd,Z.prototype.Pe,"XCSR"],nf[65398]=[null,null,Z.prototype.Pd,Z.prototype.Oe,"XBUF"],nf);
Ja(function(){for(var a=D(document,"pdp11","serial"),b=0;b<a.length;b++){var c=a[b],d=B(c),d=new Z(d);C(d,c)}});function dc(a){x.call(this,"PC11",a,dc);this.c=a.autoMount||null;this.m=0;this.U=a.baudReceive||3600;this.w=this.A=this.b=0;this.u=[];this.s=of;this.h=pf;this.D=this.i="";this.L=this.na=this.ma=null;this.K=-1;this.G=!Ca("Mobi")&&window&&"FileReader"in window}z(dc);var of="",pf=0;h=dc.prototype;
h.aa=function(a,b,c){var d=this,e=pf;switch(b){case "listTapes":return this.j[b]=c,c.onchange=function(){var a=d.j.descTape,b=c.options[c.selectedIndex];if(a&&b){var e={};if(b=b.getAttribute("data-value"))try{e=eval("("+b+")")}catch(l){w("PC11 option error: "+l.message)}b=e.desc;void 0===b&&(b="");e=e.href;void 0!==e&&(b='<a href="'+e+'" target="_blank">'+b+"</a>");a.innerHTML=b}},!0;case "descTape":return this.j[b]=c,!0;case "loadTape":e=2;case "attachTape":return e||(e=1),this.j[b]=c,c.onclick=
function(){var a=d.j.listTapes;a&&qf(d,a.options[a.selectedIndex].text,a.value,e)},!0;case "mountTape":if(!this.G){c.parentNode.removeChild(c);break}this.j[b]=c;c.addEventListener("change",function(){var a=c.children[0];a.children[1].disabled=!a.children[0].files.length});c.onsubmit=function(a){if(a=a.currentTarget[1].files[0]){var b=a.name;qf(d,r(b,!0),b,1,a)}return!1};return!0;case "readProgress":return this.j[b]=c,!0}return!1};
h.fa=function(a,b,c,d){this.l=a;this.g=b;this.a=c;this.H=d;this.N=rf(a);var e=this;if((this.c=wc(this.l,"autoMount")||this.c)&&"string"==typeof this.c)try{this.c=eval("("+this.c+")")}catch(f){w("PC11 auto-mount error: "+f.message+" ("+this.c+")"),this.c=null}this.P=Yb(56,4,4096);this.V=Vb(this.a,function(){1==(e.b&32769)&&!(e.b&128)&&e.w<e.u.length&&(e.A=e.u[e.w++]&255,sf(e,e.w/e.u.length*100),e.b|=128,e.b&=-2049,e.b&64&&Wb(e.a,e.P))});fb(b,this,tf);hb(b,this.reset.bind(this));uf(this,"None",of,!0);
this.G&&uf(this,"Local Tape","?");uf(this,"Remote Tape","??");vf(this)||E(this)};h.ha=function(a,b){if(!b)if(!a||!this.restore)this.reset();else if(!this.restore(a))return!1;return!0};h.ga=function(a){return a?this.save():!0};h.reset=function(){this.b&=-2241;this.A=0};
function vf(a){a.m=0;if(a.c){var b=a.c.path||"",c;if(!(c=a.c.name))a:{if((c=a.j.listTapes)&&c.options)for(var d=0;d<c.options.length;d++){var e=c.options[d];if(e.value==b){c=e.text;break a}}c=r(b,!0)}b&&c?wf(a,c,b,1,!0):xf(a)}return!!a.m}
function qf(a,b,c,d,e){if(c)if("?"==c)a.C('Use "Choose File" and "Mount" to select and load a local tape.');else{if("??"==c){c=window.prompt("Enter the URL of a remote tape image.","")||"";if(!c)return;b=r(c);a.status("Attempting to load "+c+' as "'+b+'"');a.s="??"}else a.s=c;wf(a,b,c,d,!1,e)}else yf(a,!1)}function wf(a,b,c,d,e,f){var g=-1;if(a.i.toLowerCase()!=c.toLowerCase()||a.h!=d)g++,yf(a,!0),a.o.Fa?a.C("PC11 busy"):(e&&a.m++,zf(a,b,c,d,f)?g++:a.o.Fa=!0);g&&Af(a,a.D,a.i,a.h,a.L,a.na,a.ma)}
function zf(a,b,c,d,e){var f=c;if(e){var g=new FileReader;g.onload=function(){var e=g.result;e&&(e=new Uint8Array(e,0,e.byteLength),Af(a,b,c,d,e),a.s="?");xf(a)};g.readAsArrayBuffer(e);return!0}0>c.indexOf("/api/v1/dump")&&(e=la(c),f="json"==e||"gz"==e?encodeURI(c):ua()+"/api/v1/dump?path="+encodeURIComponent(c)+"&format=json");return!!t(f,null,!0,function(e,f,g){var k=0>g&&a.l&&!a.l.o.R;g?a.C('Unable to load tape "'+b+'" (error '+g+": "+e+")",k):(Ua(a.ua,e,f),(e=ta(e,f))&&Af(a,b,c,d,e.L,e.na,e.ma));
a.o.Fa=!1;a.m&&(a.m--,a.m||E(a));xf(a)})}function uf(a,b,c,d){if((a=a.j.listTapes)&&a.options){for(var e=0;e<a.options.length;e++)if(a.options[e].value==c)return;e=document.createElement("option");e.text=b;e.value=c;d&&a.childNodes[0]?a.insertBefore(e,a.childNodes[0]):a.appendChild(e)}}function xf(a){var b=a.j.listTapes;if(b&&b.options){a=a.s||a.i;for(var c=0;c<b.options.length;c++)if(b.options[c].value==a){b.selectedIndex!=c&&(b.selectedIndex=c);break}c==b.options.length&&(b.selectedIndex=0)}}
function sf(a,b){b|=0;if(b!==a.K){var c=a.j.readProgress;c&&(c=(c=D(c,"pcjs-progress-bar"))&&c[0])&&c.style&&(c.style.width=b+"%");a.K=b}}function Af(a,b,c,d,e,f,g){a.D=b;a.i=c;a.h=d;a.L=e;a.na=f;a.ma=g;2==d?a.N&&hf(a.N,e,f,g)?a.status("tape loaded: "+b):(a.D="",a.i="",a.s=of,a.h=pf,a.C("No load address available for tape: "+b)):(a.w=0,a.u=e,a.status("tape attached: "+b),sf(a,0))}
function yf(a,b){if(a.i||!1===b)a.D="",a.i="",b||(a.h&&a.status(1==a.h?"tape detached":"tape unloaded"),a.s=of,a.h=pf,xf(a))}h.save=function(){return(new O(this)).data()};h.restore=function(){return!0};h.hd=function(){return this.b&65534};h.he=function(a){a&1&&(this.b&32768?(a&=-2,this.b&64&&Wb(this.a,this.P)):(this.b&=-129,this.b|=2048,this.A=0,Xb(this.a,this.V,1E3/Math.round(this.U/10))));this.b=this.b&-66|a&65};h.gd=function(){this.b&=-129;this.b|=2048;return this.A};h.ge=function(){};
var Bf={},tf=(Bf[65384]=[null,null,dc.prototype.hd,dc.prototype.he,"PRS"],Bf[65386]=[null,null,dc.prototype.gd,dc.prototype.ge,"PRB"],Bf);function Cf(a,b,c){x.call(this,"Disk",{id:a.ua+".disk"+q(++Df,4)},Cf,8192);this.controller=a;this.l=a.l;this.H=a.H;this.h=b;this.oa=b.name;this.ub=b.ub;Ef(this,c,b.O,b.S,b.M,b.W);E(this)}var Df=0;z(Cf);h=Cf.prototype;h.fa=function(a,b,c,d){this.H=d};
function Ef(a,b,c,d,e,f){a.mode=b;a.O=c;a.S=d;a.M=e;a.W=f;a.a=[];if("preload"!=a.mode){b=Array(a.O);for(c=0;c<b.length;c++){d=Array(a.S);for(e=0;e<d.length;e++){f=Array(a.M);for(var g=1;g<=f.length;g++)f[g-1]=Ff(null,c,e,g,a.W,0);d[e]=f}b[c]=d}a.a=b}a.b=null}
function Gf(a,b,c,d,e){var f=c;if(a.g)return!0;a.oa=b;a.da=c;a.Nb=r(c);a.g=e;a.i=a.controller;if(d){var g=new FileReader;g.onload=function(){var b=g.result,c,d=b?b.byteLength:0,e=ia[d];if(e){a.O=e[0];a.S=e[1];a.M=e[2];a.W=e[3]||512;c=a.W>>2;var f=e=0,b=new DataView(b,0,d);a.a=Array(a.O);for(d=0;d<a.a.length;d++)for(var v=a.a[d]=Array(a.S),U=0;U<v.length;U++)for(var za=v[U]=Array(a.M),Aa=0;Aa<za.length;Aa++){for(var qc=Ff(null,d,U,Aa+1,a.W,0),rg=qc.data,rc=0;rc<c;rc++,f+=4)var sg=rg[rc]=b.getInt32(f,
!0),e=e+sg&-1;qc.ea=c;za[Aa]=qc}a.b=e;c=a}else a.C("Unrecognized disk format ("+d+" bytes)");a.g&&(a.g.call(a.controller,a.h,c,a.oa,a.da),a.g=null)};g.readAsArrayBuffer(d);return!0}0>c.indexOf("/api/v1/dump")&&(b=la(c),"json"==b||"gz"==b?f=encodeURI(c):(d="path",e="&mbhd=10",!c.indexOf("http:")||!c.indexOf("ftp:")||0<="dsk ima img 360 720 12 144".split(" ").indexOf(b)?(d="disk",e="&mbhd=0"):ma(c,"/")&&(d="dir"),f=ua()+"/api/v1/dump?"+d+"="+encodeURIComponent(c)+(a.ub?"":e)+"&format=json"));return!!t(f,
null,!0,function(b,c,d){Hf(a,b,c,d)})}
function Hf(a,b,c,d){var e=null;a.c=!1;var f=0>d&&a.l&&!a.l.o.R;if(d)a.controller.C('Unable to load disk "'+a.oa+'" (error '+d+": "+b+")",f);else{Ua(a.controller.ua,b,c);try{if(0<r(a.Nb,!0).toLowerCase().indexOf("-readonly"))a.c=!0;else{var g=c.indexOf("\n");0<g&&1024>g&&0<c.substring(0,g).indexOf("write-protected")&&(a.c=!0)}var k;"<"==c.substr(0,1)?k=["Missing disk image: "+a.oa]:k=0>c.indexOf("0x")&&'["'!=c.substr(0,2)?JSON.parse(c.replace(/([a-z]+):/gm,'"$1":').replace(/\/\/[^\n]*/gm,"")):eval("("+
c+")");if(k.length)if(1==k.length)w(k[0]);else{a.O=k.length;a.S=k[0].length;a.M=k[0][0].length;var l=k[0][0][0];a.W=l&&l.length||512;for(d=c=0;d<a.O;d++)for(f=0;f<a.S;f++)for(g=0;g<a.M;g++)if(l=k[d][f][g]){var n=l.length;void 0===n&&(n=l.length=512);var n=n>>2,p=l.pattern;void 0===p&&(p=l.pattern=0);var u=l.data;if(void 0===u){var v=l.bytes;if(void 0!==v&&v.length){for(var U=n<<2,za=v.length;za<U;za++)v[za]=p;If(l,v)}else u=[],p=l.pattern=p|p<<8|p<<16|p<<24,l.data=u;delete l.bytes}Ff(l,d,f);for(U=
0;U<u.length;U++)c=c+u[U]&-1}a.a=k;a.b=c;e=a}else w("Empty disk image: "+a.oa)}catch(Aa){w("Disk image error ("+b+"): "+Aa.message)}}a.g&&(a.g.call(a.i,a.h,e,a.oa,a.da),a.g=null)}function Ff(a,b,c,d,e,f){a||(a={sector:d,length:e,data:[],pattern:f});a.wf=b;a.xf=c;a.pa=a.ea=0;a.za=!1;return a}function Jf(a){return a.a.length?[a.a.length,a.a[0].length,a.a[0][0].length,a.a[0][0][0].length]:[0,0,0,0]}
h.seek=function(a,b,c,d,e){d=null;var f=this.h,g=this.a[a];if(g){var k=g[b];if(!k&&f.zc&&b<f.S)for(k=g[b]=Array(f.Tb),g=0;g<k.length;g++)k[g]=Ff(null,a,b,g+1,f.Kb,0);if(k){for(g=0;g<k.length;g++)if(k[g]&&k[g].sector==c){d=k[g];break}!d&&f.zc&&9==f.Fb&&(d=k[g]=Ff(null,a,b,f.Fb,f.Kb,0))}}e&&e(d,!1);return d};function If(a,b){for(var c=0,d=a.length>>2,e=Array(d),f=0;f<d;f++)e[f]=b[c]|b[c+1]<<8|b[c+2]<<16|b[c+3]<<24,c+=4;a.data=e}
h.read=function(a,b){var c=-1;if(a&&b<a.length)var c=a.data,d=b>>2,c=(d<c.length?c[d]:a.pattern)>>((b&3)<<3)&255;return c};h.write=function(a,b,c){if(this.c)return!1;if(b<a.length){if(c!=this.read(a,b,!0)){var d=a.data,e=a.pattern,f=b>>2;b=(b&3)<<3;for(var g=d.length;g<=f;g++)d[g]=e;a.ea?f<a.pa?(a.ea+=a.pa-f,a.pa=f):f>=a.pa+a.ea&&(a.ea+=f-(a.pa+a.ea)+1):(a.pa=f,a.ea=1);d[f]=d[f]&~(255<<b)|c<<b}return!0}return null};
function Kf(a,b){var c=a.S*a.M,d=b/c|0;return d<a.O?(b%=c,a.seek(d,b/a.M|0,b%a.M+1)):null}function Lf(a,b,c){for(var d=1,e=0,f=0;d--;){var g=a.read(b,c++);if(0>g)break;e|=g<<f;f+=8}return e}function Mf(a){for(var b="",c=0,d;d=Kf(a,c++);)for(var e=0,f=d.length;e<f;e++)b+=String.fromCharCode(Lf(a,d,e));return btoa(b)}
h.save=function(){var a=0,b=[];b[a++]=[this.da,this.b,this.O,this.S,this.M,this.W];if(!this.c)for(var c=this.a,d=0;d<c.length;d++)for(var e=0;e<c[d].length;e++)for(var f=0;f<c[d][e].length;f++){var g=c[d][e][f];if(g&&g.ea){for(var k=[],l=0,n=g.pa,p=g.pa+g.ea;n<p;)k[l++]=g.data[n++];b[a++]=[d,e,f,g.pa,k]}}return b};
h.restore=function(a){var b=0,c="unsupported restore format";if(a&&0<a.length){var d=0,e=a[d++];e&&2<=e.length&&(!this.a.length&&6<=e.length?Ef(this,"local",e[2],e[3],e[4],e[5]):null!=e[1]&&null!=this.b&&e[1]!=this.b&&(c="original checksum ("+e[1]+") differs from current checksum ("+this.b+")",b=-2));for(this.a.length||(b=-1);d<a.length&&0<=b;){var f=0,g=a[d++],k=g[f++],l=g[f++],n=g[f++];if(k>=this.a.length||l>=this.a[k].length||n>=this.a[k][l].length){c="sector (CHS="+k+":"+l+":"+n+") out of range ("+
b+" changes applied)";b=-1;break}if(this.c){c="unable to modify write-protected disk";b=-1;break}e=g[f++];f=g[f++];g=e+f.length;if(k=this.a[k][l][n]){for(l=k.data.length;l<e;)k.data[l++]=k.pattern;l=0;k.pa=e;for(k.ea=f.length;e<g;)k.data[e++]=f[l++];b++}}}0>b&&-2!=b&&this.controller.C("Unable to restore disk '"+this.oa+": "+c);return b};
h.toJSON=function(){var a;a=0;for(var b;b=Kf(this,a++);)Nf(b);a=JSON.stringify(this.a,function(a,b){if("file"!=a)return b});a=a.replace(/,"length":512/gm,"").replace(/,"pattern":0/gm,"");a=a.replace(/"(sector|length|data|pattern)":/gm,"$1:");a=a.replace(/,"[^"]*":([0-9]+|true|false)/gm,"");a=a.replace(/(sector|length|data|pattern):/gm,'"$1":');return a=a.replace(/([\]}]),/gm,"$1,\n")};
function Nf(a){var b=a.data,c=b.length;if(c<<2==a.length){for(var d=c-1,e=b[d],f=0;d--&&b[d]===e;)f++;f++&&(b.length=c-f,a.pattern=e)}}function N(a){x.call(this,"RK11",a,N,65536);this.u=a.autoMount||{};this.m=0;this.c=Array(8);this.w=!Ca("Mobi")&&window&&"FileReader"in window}z(N);h=N.prototype;
h.aa=function(a,b,c){var d=this;switch(b){case "listDisks":return this.j[b]=c,c.onchange=function(){var a=d.j.descDisk,b=c.options[c.selectedIndex];if(a&&b){var g={};if(b=b.getAttribute("data-value"))try{g=eval("("+b+")")}catch(k){w("RK11 option error: "+k.message)}b=g.desc;void 0===b&&(b="");g=g.href;void 0!==g&&(b='<a href="'+g+'" target="_blank">'+b+"</a>");a.innerHTML=b}},!0;case "descDisk":case "listDrives":return this.j[b]=c,c.onchange=function(){var a=m(c.value);null!=a&&Of(d,a)},!0;case "loadDrive":return this.j[b]=
c,c.onclick=function(){var a=d.j.listDisks;a&&Pf(d,a.options[a.selectedIndex].text,a.value)},!0;case "saveDrive":if(!this.w){c.parentNode.removeChild(c);break}this.j[b]=c;c.onclick=function(){var a=d.j.listDrives;a&&a.options&&d.c&&((a=d.c[m(a.value)||0])?(a=a.J)?(a=Da(Mf(a),a.Nb.replace(".json",".img")),w(a)):d.C("No disk loaded in drive."):d.C("No disk drive selected."))};return!0;case "mountDrive":if(this.w)return this.j[b]=c,c.addEventListener("change",function(){var a=c.children[0];a.children[1].disabled=
!a.children[0].files.length}),c.onsubmit=function(a){if(a=a.currentTarget[1].files[0]){var b=a.name;Pf(d,r(b,!0),b,a)}return!1},!0;c.parentNode.removeChild(c)}return!1};
h.fa=function(a,b,c,d){this.l=a;this.g=b;this.a=c;this.H=d;if((a=wc(this.l,"autoMount"))&&"string"==typeof a)try{a=eval("("+a+")")}catch(f){w(this.type+" auto-mount error: "+f.message+" ("+a+")"),a=null}if(a)for(var e in a)e.substr(0,2)==this.type.substr(0,2)&&(this.u[e]=a[e]);Qf(this);this.D=Yb(144,5,65536);fb(b,this,Rf);hb(b,this.reset.bind(this));Sf(this,"None","",!0);this.w&&Sf(this,"Local Disk","?");Sf(this,"Remote Disk","??");Tf(this)||E(this)};
h.ha=function(a,b){if(!b){if(!a||!this.restore){if(this.reset(),this.l.Jb){for(a=0;a<this.c.length;a++)Uf(this,a,!0);Tf(this,!0)}}else if(!this.restore(a))return!1;if(a=this.j.listDrives){for(;a.firstChild;)a.removeChild(a.firstChild);a.value="";for(b=0;8>b;b++){var c=document.createElement("option");c.value=b;c.text="RK"+b;a.appendChild(c)}a.value="0";Of(this,0)}}return!0};h.ga=function(a){return a?this.save():!0};h.reset=function(){Qf(this)};h.save=function(){return(new O(this)).data()};
h.restore=function(a){return Qf(this,a[0])};function Tf(a,b){b||(a.m=0);for(var c in a.u){var d=a.u[c],e=d.path||"",f;if(!(f=d.name))a:{if((f=a.j.listDisks)&&f.options)for(var g=0;g<f.options.length;g++){var k=f.options[g];if(k.value==e){f=k.text;break a}}f=r(e,!0)}if(e&&f&&(g=-1,c&&(g=c.charCodeAt(c.length-1)-48,0>g||9<g)&&(g=-1),0<=g&&g<a.c.length)){!Vf(a,g,f,e,!0)&&b&&E(a,!1);continue}a.C("Incorrect auto-mount settings for drive "+c+" ("+JSON.stringify(d)+")")}return!!a.m}
function Pf(a,b,c,d){var e=a.j.listDrives,e=e&&m(e.value);if(void 0===e||0>e||e>=a.c.length)a.C("Unable to load the selected drive");else if(c)if("?"==c)a.C('Use "Choose File" and "Mount" to select and load a local disk.');else{if("??"==c){c=window.prompt("Enter the URL of a remote disk image.","")||"";if(!c)return;b=r(c);a.status("Attempting to load "+c+' as "'+b+'"')}Vf(a,e,b,c,!1,d)}else Uf(a,e)}
function Vf(a,b,c,d,e,f){var g=-1,k=a.c[b];k.da.toLowerCase()!=d.toLowerCase()&&(g++,Uf(a,b,!0),k.Ha?a.C("RK11 busy"):(k.Ha=!0,e&&(k.Ga=!0,a.m++),k.Aa=!!f,Gf(new Cf(a,k,"preload"),c,d,f,a.pc)&&g++));return g}
h.pc=function(a,b,c,d,e){var f;a.Ha=!1;b&&(f=Jf(b),b&&f[0]>a.O||f[1]>a.S)&&(this.C('Disk "'+c+'" too large for drive '+("RK"+a.Ia)),b=null);b?(a.J=b,a.oa=c,a.da=d,this.C('Mounted disk "'+c+'" in drive '+("RK"+a.Ia),a.Ga||e),this.l&&Cc(this.l)):a.Aa=!1;a.Ga&&(a.Ga=!1,--this.m||E(this));Of(this,a.Ia)};
function Sf(a,b,c,d){if((a=a.j.listDisks)&&a.options){for(var e=0;e<a.options.length;e++)if(a.options[e].value==c)return;e=document.createElement("option");e.text=b;e.value=c;d&&a.childNodes[0]?a.insertBefore(e,a.childNodes[0]):a.appendChild(e)}}
function Of(a,b){if(0<=b&&b<a.c.length){var c=a.c[b],d=a.j.listDisks;a=a.j.listDrives;if(d&&a&&d.options&&a.options&&(a=m(a.value),c=c.Aa?"?":c.da,!isNaN(a)&&a==b)){for(b=0;b<d.options.length;b++)if(d.options[b].value==c){d.selectedIndex!=b&&(d.selectedIndex=b);break}b==d.options.length&&(d.selectedIndex=0)}}}function Uf(a,b,c){var d=a.c[b];if(d.J||!1===c)d.oa="",d.da="",d.J=null,d.Aa=!1,c||(a.C("Drive RK"+b+" unloaded",c),Of(a,b))}
function Qf(a,b){var c=0;b||(b=[]);a.A=b[c++]||2496;a.i=b[c++]||0;a.B=b[c++]||128;a.s=b[c++]||0;a.h=b[c++]||0;a.b=b[c++]||0;a.G=b[c]||0;for(b=0;b<a.c.length;b++){var d=a.c[b];void 0===d&&(d=a.c[b]={});c=a;d.Ia=b;d.Ha=d.Aa=!1;d.name=c.Ca;d.O=203;d.S=2;d.M=12;d.W=512;d.ub=!0;d.Ac=0;d.yc=0;d.Fb=1;d.Tb=d.M;d.Kb=d.W;d.Gc=0;d.Sd=null;d.J||(d.da="");d.status=2496}return!0}h.oc=function(a,b,c,d,e,f){this.h=f&65535;this.B=this.B&-49|f>>12&48;this.s=65536-e&65535;a&&(this.i=this.i|a|32768,this.B|=49152);return!0};
h.qc=function(a,b,c,d,e,f,g){var k=0,l=a.J,n=null,p;l||(k=128,e=0);for(;e--;){if(!n){n=a.J.seek(b,c,d+1);if(!n){k=4096;break}p=0}var u,v;if(0>(u=a.J.read(n,p++))||0>(v=a.J.read(n,p++))){k=32;break}this.g.Va(f,u|v<<8);if(Ub(this.g)){k=1024;break}f+=2;if(p>=l.W&&(n=null,++d>=l.M&&(d=0,++c>=l.S&&(c=0,++b>=l.O)))){k=64;break}}return g(k,b,c,d,e,f)};
h.rc=function(a,b,c,d,e,f,g){var k=0,l=a.J,n=null,p;l||(k=128,e=0);for(;e--;){var u=this.g.Qa(f);if(Ub(this.g)){k=1024;break}f+=2;if(!n){n=a.J.seek(b,c,d+1,!0);if(!n){k=4096;break}p=0}if(!a.J.write(n,p++,u&255)||!a.J.write(n,p++,u>>8)){k=32;break}if(p>=l.W&&(n=null,++d>=l.M&&(d=0,++c>=l.S&&(c=0,++b>=l.O)))){k=64;break}}return g(k,b,c,d,e,f)};h.ud=function(){return this.A};h.te=function(){};h.vd=function(){return this.i};h.ue=function(){};h.rd=function(){return this.B&61438};
h.qe=function(a){this.B=this.B&-3968|a&3967;if(this.B&1){var b,c=!0;a=(this.b&57344)>>13;var d=this.c[a],e,f,g,k;this.B&=-129;switch(this.B&14){case 0:this.A=d.status;this.i=0;this.B=128;this.b=0;break;case 4:b=this.qc;case 2:b||(b=this.rc),e=(this.b&8160)>>5,f=(this.b&16)>>4,g=this.b&15,e>=d.O?(this.i|=32832,this.B|=49152):g>=d.M?(this.i|=32800,this.B|=49152):(k=(this.B&48)<<12|this.h,c=65536-this.s&65535,c=b.call(this,d,e,f,g,c,k,this.oc.bind(this)))}this.A=d.status|a<<13|this.b%9&15;c&&(this.B&=
-2,this.B|=128,this.B&64&&Wb(this.a,this.D))}};h.wd=function(){return this.s};h.ve=function(a){this.s=a};h.qd=function(){return this.h};h.pe=function(a){this.h=a};h.sd=function(){return this.b};h.re=function(a){this.b=a};h.td=function(){return this.G};h.se=function(a){this.G=a};
var Wf={},Rf=(Wf[65280]=[null,null,N.prototype.ud,N.prototype.te,"RKDS"],Wf[65282]=[null,null,N.prototype.vd,N.prototype.ue,"RKER"],Wf[65284]=[null,null,N.prototype.rd,N.prototype.qe,"RKCS"],Wf[65286]=[null,null,N.prototype.wd,N.prototype.ve,"RKWC"],Wf[65288]=[null,null,N.prototype.qd,N.prototype.pe,"RKBA"],Wf[65290]=[null,null,N.prototype.sd,N.prototype.re,"RKDA"],Wf[65294]=[null,null,N.prototype.td,N.prototype.se,"RKDB"],Wf);
function M(a){x.call(this,"RL11",a,M,131072);this.w=a.autoMount||{};this.s=0;this.c=Array(4);this.A=!Ca("Mobi")&&window&&"FileReader"in window}z(M);h=M.prototype;
h.aa=function(a,b,c){var d=this;switch(b){case "listDisks":return this.j[b]=c,c.onchange=function(){var a=d.j.descDisk,b=c.options[c.selectedIndex];if(a&&b){var g={};if(b=b.getAttribute("data-value"))try{g=eval("("+b+")")}catch(k){w("RL11 option error: "+k.message)}b=g.desc;void 0===b&&(b="");g=g.href;void 0!==g&&(b='<a href="'+g+'" target="_blank">'+b+"</a>");a.innerHTML=b}},!0;case "descDisk":case "listDrives":return this.j[b]=c,c.onchange=function(){var a=m(c.value);null!=a&&Xf(d,a)},!0;case "loadDrive":return this.j[b]=
c,c.onclick=function(){var a=d.j.listDisks;a&&Yf(d,a.options[a.selectedIndex].text,a.value)},!0;case "saveDrive":if(!this.A){c.parentNode.removeChild(c);break}this.j[b]=c;c.onclick=function(){var a=d.j.listDrives;a&&a.options&&d.c&&((a=d.c[m(a.value)||0])?(a=a.J)?(a=Da(Mf(a),a.Nb.replace(".json",".img")),w(a)):d.C("No disk loaded in drive."):d.C("No disk drive selected."))};return!0;case "mountDrive":if(this.A)return this.j[b]=c,c.addEventListener("change",function(){var a=c.children[0];a.children[1].disabled=
!a.children[0].files.length}),c.onsubmit=function(a){if(a=a.currentTarget[1].files[0]){var b=a.name;Yf(d,r(b,!0),b,a)}return!1},!0;c.parentNode.removeChild(c)}return!1};
h.fa=function(a,b,c,d){this.l=a;this.g=b;this.a=c;this.H=d;if((a=wc(this.l,"autoMount"))&&"string"==typeof a)try{a=eval("("+a+")")}catch(f){w(this.type+" auto-mount error: "+f.message+" ("+a+")"),a=null}if(a)for(var e in a)e.substr(0,2)==this.type.substr(0,2)&&(this.w[e]=a[e]);Zf(this);this.D=Yb(112,5,131072);fb(b,this,$f);hb(b,this.reset.bind(this));ag(this,"None","",!0);this.A&&ag(this,"Local Disk","?");ag(this,"Remote Disk","??");bg(this)||E(this)};
h.ha=function(a,b){if(!b){if(!a||!this.restore){if(this.reset(),this.l.Jb){for(a=0;a<this.c.length;a++)cg(this,a,!0);bg(this,!0)}}else if(!this.restore(a))return!1;if(a=this.j.listDrives){for(;a.firstChild;)a.removeChild(a.firstChild);a.value="";for(b=0;4>b;b++){var c=document.createElement("option");c.value=b;c.text="RL"+b;a.appendChild(c)}a.value="0";Xf(this,0)}}return!0};h.ga=function(a){return a?this.save():!0};h.reset=function(){Zf(this)};h.save=function(){return(new O(this)).data()};
h.restore=function(a){return Zf(this,a[0])};function bg(a,b){b||(a.s=0);for(var c in a.w){var d=a.w[c],e=d.path||"",f;if(!(f=d.name))a:{if((f=a.j.listDisks)&&f.options)for(var g=0;g<f.options.length;g++){var k=f.options[g];if(k.value==e){f=k.text;break a}}f=r(e,!0)}if(e&&f&&(g=-1,c&&(g=c.charCodeAt(c.length-1)-48,0>g||9<g)&&(g=-1),0<=g&&g<a.c.length)){!dg(a,g,f,e,!0)&&b&&E(a,!1);continue}a.C("Incorrect auto-mount settings for drive "+c+" ("+JSON.stringify(d)+")")}return!!a.s}
function Yf(a,b,c,d){var e=a.j.listDrives,e=e&&m(e.value);if(void 0===e||0>e||e>=a.c.length)a.C("Unable to load the selected drive");else if(c)if("?"==c)a.C('Use "Choose File" and "Mount" to select and load a local disk.');else{if("??"==c){c=window.prompt("Enter the URL of a remote disk image.","")||"";if(!c)return;b=r(c);a.status("Attempting to load "+c+' as "'+b+'"')}dg(a,e,b,c,!1,d)}else cg(a,e)}
function dg(a,b,c,d,e,f){var g=-1,k=a.c[b];k.da.toLowerCase()!=d.toLowerCase()&&(g++,cg(a,b,!0),k.Ha?a.C("RL11 busy"):(k.Ha=!0,e&&(k.Ga=!0,a.s++),k.Aa=!!f,Gf(new Cf(a,k,"preload"),c,d,f,a.tc)&&g++));return g}
h.tc=function(a,b,c,d,e){var f;a.Ha=!1;b&&(f=Jf(b),b&&f[0]>a.O||f[1]>a.S)&&(this.C('Disk "'+c+'" too large for drive '+("RL"+a.Ia)),b=null);b?(a.J=b,a.oa=c,a.da=d,this.C('Mounted disk "'+c+'" in drive '+("RL"+a.Ia),a.Ga||e),this.l&&Cc(this.l)):a.Aa=!1;a.Ga&&(a.Ga=!1,--this.s||E(this));Xf(this,a.Ia)};
function ag(a,b,c,d){if((a=a.j.listDisks)&&a.options){for(var e=0;e<a.options.length;e++)if(a.options[e].value==c)return;e=document.createElement("option");e.text=b;e.value=c;d&&a.childNodes[0]?a.insertBefore(e,a.childNodes[0]):a.appendChild(e)}}
function Xf(a,b){if(0<=b&&b<a.c.length){var c=a.c[b],d=a.j.listDisks;a=a.j.listDrives;if(d&&a&&d.options&&a.options&&(a=m(a.value),c=c.Aa?"?":c.da,!isNaN(a)&&a==b)){for(b=0;b<d.options.length;b++)if(d.options[b].value==c){d.selectedIndex!=b&&(d.selectedIndex=b);break}b==d.options.length&&(d.selectedIndex=0)}}}function cg(a,b,c){var d=a.c[b];if(d.J||!1===c)d.oa="",d.da="",d.J=null,d.Aa=!1,c||(a.C("Drive RL"+b+" unloaded",c),Xf(a,b))}
function Zf(a,b){var c=0;b||(b=[]);a.B=b[c++]||0;a.h=b[c++]||0;a.b=b[c++]||0;a.i=b[c++]||0;a.m=b[c++]||0;a.u=b[c]||0;for(b=0;b<a.c.length;b++){var d=a.c[b];void 0===d&&(d=a.c[b]={});c=a;d.Ia=b;d.Ha=d.Aa=!1;d.name=c.Ca;d.O=512;d.S=2;d.M=40;d.W=256;d.ub=!0;d.Ac=0;d.yc=0;d.Fb=1;d.Tb=d.M;d.Kb=d.W;d.Gc=0;d.Sd=null;d.J||(d.da="");d.status=29|(512==d.O?128:0)}return!0}
h.sc=function(a,b,c,d,e,f){this.h=f&65535;this.B=this.B&-49|f>>12&48;this.u=f>>16&63;this.i=this.b=b<<7|(c?64:0)|d&63;this.m=65536-e&65535;a&&(this.B=this.B|a|32768);return!0};
h.uc=function(a,b,c,d,e,f,g){var k=0,l=a.J,n=null,p;l||(k=5120,e=0);for(;e--;){if(!n){n=a.J.seek(b,c,d+1);if(!n){k=5120;break}p=0}var u,v;if(0>(u=a.J.read(n,p++))||0>(v=a.J.read(n,p++))){k=5120;break}this.g.Va(f,u|v<<8);if(Ub(this.g)){k=8192;break}f+=2;if(p>=l.W&&(n=null,++d>=l.M&&(d=0,++c>=l.S&&(c=0,++b>=l.O)))){k=5120;break}}return g(k,b,c,d,e,f)};
h.vc=function(a,b,c,d,e,f,g){var k=0,l=a.J,n=null,p;l||(k=5120,e=0);for(;e--;){var u=this.g.Qa(f);if(Ub(this.g)){k=8192;break}f+=2;if(!n){n=a.J.seek(b,c,d+1,!0);if(!n){k=5120;break}p=0}if(!a.J.write(n,p++,u&255)||!a.J.write(n,p++,u>>8)){k=5120;break}if(p>=l.W&&(n=null,++d>=l.M&&(d=0,++c>=l.S&&(c=0,++b>=l.O)))){k=5120;break}}return g(k,b,c,d,e,f)};h.zd=function(){return this.B&65535};
h.ye=function(a){this.B=this.B&-1023|a&1022;this.G=this.G&-4|(a&48)>>4;if(!(this.B&128)){var b;a=!0;var c=this.c[(this.B&768)>>8],d,e,f,g;this.B&=-2;switch(this.B&14){case 4:this.b&8&&(this.B&=63);this.m=c.status|this.i&64;break;case 6:1==(this.b&3)&&(b=this.b&65408,c=(this.b&16)<<2,this.i=this.b&4?this.i+b:this.i-b,this.b=this.i=this.i&65408|c);break;case 8:this.m=this.i;break;case 12:b=this.uc;case 10:b||(b=this.vc),d=this.b>>7,e=this.b&64?1:0,f=this.b&63,d>=c.O||f>=c.M?this.B|=37888:(g=(this.u&
63)<<16|this.h,a=65536-this.m&65535,a=b.call(this,c,d,e,f,a,g,this.sc.bind(this)))}a&&(this.B|=129,this.B&64&&Wb(this.a,this.D))}};h.xd=function(){return this.h};h.we=function(a){this.h=a&65534};h.Ad=function(){return this.b};h.ze=function(a){this.b=a};h.Bd=function(){return this.m};h.Ae=function(a){this.m=a};h.yd=function(){return this.u};h.xe=function(a){this.u=a&63};
var eg={},$f=(eg[63744]=[null,null,M.prototype.zd,M.prototype.ye,"RLCS"],eg[63746]=[null,null,M.prototype.xd,M.prototype.we,"RLBA"],eg[63748]=[null,null,M.prototype.Ad,M.prototype.ze,"RLDA"],eg[63750]=[null,null,M.prototype.Bd,M.prototype.Ae,"RLMP"],eg[63752]=[null,null,M.prototype.yd,M.prototype.xe,"RLBE"],eg);
function fg(a,b,c){x.call(this,"Computer",a,fg,33554432);this.o.R=!1;gg(this,b);this.A=wc(this,"autoPower",a);this.l=0;this.P=a.busWidth||a.buswidth;this.b=hg;this.s=null;this.i=this.K=!1;this.U=wc(this,"url")||"";(Math.random()+.1).toString(36);this.c=ig(this);if(this.a=Wa("CPU",this.id)){this.H=Wa("Debugger",this.id);this.g=new yb({id:this.ua+".bus",busWidth:this.P},this.a,this.H);var d,e=A(this.id);if((this.w=Wa("Panel",this.id))&&this.w.eb)for(b=0;b<e.length;b++)d=e[b],d.C=this.w.C,d.X=this.w.X,
d.eb=this.w.eb;this.X("PDPjs v1.30.4\nCopyright \u00a9 2012-2016 Jeff Parsons <Jeff@pcjs.org>\nLicense: GPL version 3 or later <http://gnu.org/licenses/gpl.html>");this.X("Portions adapted from the PDP-11/70 Emulator v1.4 by Paul Nankervis <paulnank@hotmail.com>");for(b=0;b<e.length;b++)d=e[b],d.fa&&d.fa(this,this.g,this.a,this.H);b=null;d=a.resume;void 0!==d&&(1<d.length?b=this.m=d:this.b=parseInt(d,10));var f;if(a=wc(this,"state")||(f=!0,a.state))b=this.D=a,f||(this.i=!0,this.b=hg),this.b&&(this.u=
new O(this,"1.30.4"),jg(this.u)?b=null:delete this.u);!b&&this.b&&(b=kg(this))&&(this.i=!0);if(b){var g=this;t(b,null,!0,function(a,b,c){c?(g.m=null,g.i=!1,g.C("Unable to load machine state from server (error "+c+(b?": "+pa(b):"")+")")):(g.s=b,g.K=!0);E(g)})}else E(this);this.j.power||(this.A=!0);!c&&this.A&&lg(this,this.hb)}else w("Unable to find CPU component")}z(fg);var hg=0;
function gg(a,b){if(!b){var c;if("object"==typeof resources&&(c=resources.parms))try{b=eval("("+c+")")}catch(d){w(d.message+" ("+c+")")}}a.N=b}function wc(a,b,c){var d=b.toLowerCase(),d=Oa[b]||Oa[d];void 0===d&&a.N&&(d=a.N[b]);void 0===d&&c&&(d=c[b]);void 0===d&&"object"==typeof resources&&resources[b]&&(d=b);return d}function lg(a,b,c){for(var d=A(a.id),e=0;e<=d.length;e++){var f=e<d.length?d[e]:a;if(!Ya(f)){Ya(f,function(){lg(a,b,c)});return}}b.call(a,c)}
function mg(a,b){var c=new O(a,"1.30.4","validate");if(jg(c)&&ng(c)){var d=c.get("timestamp"),e=b?b.get("timestamp"):"unknown";d!=e&&(a.C("Machine state may be out-of-date\n("+d+" vs. "+e+")\nCheck your browser's local storage limits"),b||c.clear())}}h=fg.prototype;
h.hb=function(a){void 0===a&&(a=this.b||(this.s?1:hg));if(!this.l){this.l++;var b=!1,c=!1;this.G=!1;var d=this.u||new O(this,"1.30.4");if(-1==a)b=!0;else if(a>hg){if(jg(d,this.s)){this.h=new O(this,"1.30.4","failsafe");jg(this.h)&&(og(this,d),a=2,pg(this.h));this.h.set("timestamp",sa());qg(this.h);var e=this.b&&!this.i;if(1==a||va("Click OK to restore the previous PDPjs machine state, or CANCEL to reset the machine.")){if(c=ng(d)){var f=d.get("code"),g=d.get("data");f&&("ok"==f?jg(d,g):("error"==
f&&"no machine state"!=g?(this.C("Error: "+g),"unable to verify user"==g&&(Ba("user",""),this.c=null)):this.X(f+": "+g),pg(d),jg(d)?(c=ng(d),e=!0):c=!1))}e&&mg(this,c?d:null)}else 2==a&&d.clear()}else mg(this);delete this.s;delete this.u}e=A(this.id);for(f=0;f<e.length;f++)g=e[f],g!==this&&g!=this.a&&(c=tg(this,g,d,b,c));b=[d,a,c];-1!=a?lg(this,this.Vb,b):this.Vb(b)}};
function tg(a,b,c,d,e){if(!b.o.R){b.o.R=!0;if(b.ha){var f=null;e&&((f=c.get(b.id))||(f=c.get(b.id.replace(/[a-z0-9]\./i,"."))));"string"===typeof f&&(f=null);!b.ha(f,d)&&f&&(w("Unable to restore state for "+b.type),a.D&&!a.K?(c.clear(),a.b=hg,window&&window.location.reload()):a.G=!0,b.ha(null),e=!1)}if(!d&&b.Xb)for(a=b.Xb.split("|"),c=0;c<a.length;c++)b.status(a[c])}return e}
h.Vb=function(a){var b=a[0],c=0>a[1];a=a[2];this.V=!0;this.o.R=!0;var d=this.j.power;d&&(d.textContent="Shutdown");this.a&&(tg(this,this.a,b,c,a),this.Ba(),this.a.cb());this.G&&(og(this,b),b.clear());!c&&this.h&&(this.h.clear(),delete this.h);this.l=0};
function og(a,b){if(va("There may be a problem with your PDPjs machine.\n\nTo help us diagnose it, click OK to send this PDPjs machine state to http://www.pcjs.org.")){var c=a.c||"";b=b.toString();var d={app:"PDPjs",ver:"1.30.4"};d.url=a.U;d.user=c;d.type="bug";d.data=b;t("http://www.pcjs.org/api/v1/report",d,!0)}}
function ug(a,b,c){var d,e="none";if(a.l)return null;a.l--;var f=new O(a,"1.30.4"),g=new O(a,"1.30.4","validate"),k=sa();g.set("timestamp",k);f.set("timestamp",k);f.set("version","1.30.4");f.set("url",window?window.location.href:null);f.set("browser",window?window.navigator.userAgent:"");a.a&&a.a.ga&&(c&&F(a.a),d=a.a.ga(b,c),"object"===typeof d&&f.set(a.a.id,d),c&&(a.a.o.R=!1,!1===d&&(e=null)));for(var k=A(a.id),l=0;l<k.length;l++){var n=k[l];n.o.R&&(n.ga&&(d=n.ga(b,c),"object"===typeof d&&f.set(n.id,
d)),c&&(n.o.R=!1,!1===d&&(e=null)))}e&&(c?(k=d=!1,b?(a.c&&vg(a,a.c,f.toString()),qg(g)&&qg(f)||(e=null,d=k=!0)):a.b&&(d=!0,k=3==a.b),d&&f.clear(k)):e=f.toString());c&&(a.o.R=!1,b=a.j.power)&&(b.textContent="Power");a.l=0;return e}h.reset=function(){this.g&&this.g.reset&&this.g.reset();this.a&&this.a.reset&&this.a.reset();for(var a=A(this.id),b=0;b<a.length;b++){var c=a[b];c!==this&&c!==this.g&&c!==this.a&&c.reset&&c.reset()}this.Ba(-1)};
h.start=function(a,b){for(var c=A(this.id),d=0;d<c.length;d++){var e=c[d];"CPU"!=e.type&&e!==this&&e.start&&e.start(a,b)}this.Ba(-1)};h.stop=function(a,b){for(var c=A(this.id),d=0;d<c.length;d++){var e=c[d];"CPU"!=e.type&&e!==this&&e.stop&&e.stop(a,b)}this.Ba(-1)};
h.Ba=function(a){if(this.a){var b=this.a,c=a||0,d=b.j.speed;d&&(0>=c||30<=(b.Bb+=c))&&(d.textContent=b.o.T?b.La.toFixed(2)+"Mhz":"Stopped",b.Bb=0)}if(this.w&&(b=this.w,a=a||0,b.u)){c=b.a.o.T;d=!!(b.a.v&4);if(0>=a||60<=(b.s+=a)){for(var e=0;e<b.a.f.length;e++)nb(b,"R"+e,b.a.f[e]);e=bc(b.a);nb(b,"PS",e);nb(b,"NF",e&8?1:0,1);nb(b,"ZF",e&4?1:0,1);nb(b,"VF",e&2?1:0,1);nb(b,"CF",e&1?1:0,1);b.s=0}vb(b,0<a&&c&&!d?b.a.fb:b.ia);ub(b,b.m);a=b.a;a=a.ka?a.Ea&16?1:2:4;wb(b,"B22",a&1);wb(b,"B18",a&2);wb(b,"B16",
a&4)}};
h.aa=function(a,b,c){var d=this;switch(b){case "power":return this.j[b]=c,c.onclick=function(){d.l||(d.o.R?ug(d,!1,!0):lg(d,d.hb))},!0;case "reset":return this.j[b]=c,c.onclick=function(){if(d.o.R&&!d.l)if(d.b&&!d.m){var a=va("Click OK to save changes to this PDPjs machine.\n\nWARNING: If you CANCEL, all disk changes will be discarded.");ug(d,a,!0);!a&&d.D?window&&window.location.reload():(a||(d.Jb=!0),d.hb(hg),d.Jb=!1)}else d.reset(),d.a&&d.a.cb()},!0;case "save":if(ma(ua(),"pcjs.org"))c.parentNode.removeChild(c);else return this.j[b]=
c,c.onclick=function(){var a=ig(d,!0);if(a){var b=!!(d.b&&!d.m||d.D),c=ug(d,b);b?vg(d,a,c):d.C("Resume disabled, machine state not saved")}},!0}return!1};
function ig(a,b){var c=a.c;c||((c=ya("user"),void 0!==c)?!c&&b&&(b=null,window&&(b=window.prompt("Saving machine states on the pcjs.org server is currently unsupported.\n\nIf you're running your own server, enter your user ID below.","")),c=b)&&((c=wg(a,c))||a.C("The user ID is invalid.")):b&&a.C("Browser local storage is not available"));return c}
function wg(a,b){a.c=null;b=t(ua()+"/api/v1/user?req=verify&user="+b);var c=b[1];if(!b[0]&&c)try{b=eval("("+c+")"),b.code&&"ok"==b.code&&(Ba("user",b.data),a.c=b.data)}catch(d){w(d.message+" ("+c+")")}return a.c}function kg(a){var b=null;a.c&&(b=ua()+"/api/v1/user?req=load&user="+a.c+"&state="+xg(a,"1.30.4"));return b}
function vg(a,b,c){if(c){var d={req:"store"};d.user=b;d.state=xg(a,"1.30.4");d.data=c;b=t(ua()+"/api/v1/user",d);d=b[0];if(b[1]){if(d){var e=d.indexOf("\n");0<e&&(d=d.substr(0,e));d.indexOf("Error: ")||(d=d.substr(7))}d='{"code":'+b[1]+',"data":"'+d+'"}'}b=JSON.parse(d);b&&"ok"==b.code?a.C("Machine state saved to server"):c&&(c=b&&b.data||"unable to save machine state",c="error"==b.code?"Error: "+c:"Error "+b.code+": "+c,a.C(c),Ba("user",""),a.c=null)}}
function rf(a){var b;a=A(a.id);for(var c=0;c<a.length;c++){var d=a[c];if(b)b==d&&(b=null);else if("RAM"==d.type)return d}return null}function Cc(a){if(a.eb){var b=0,c=0;window&&(b=window.scrollX,c=window.scrollY);a.eb.focus();window&&window.scrollTo(b,c)}}Ja(function(){for(var a=D(document,"pdp11-machine"),b=0;b<a.length;b++)for(var c=a[b],d=B(c),c=D(c,"pdp11","computer"),e=0;e<c.length;e++){var f=c[e],g=B(f),g=new fg(g,d,!0);C(g,f);g.A&&lg(g,g.hb)}});
Ea.show.push(function(){for(var a=D(document,"pdp11","computer"),b=0;b<a.length;b++){var c=B(a[b]);(c=Wa("Computer",c.id))&&c.V&&!c.o.R&&c.hb(-1)}});Ea.exit.push(function(){for(var a=D(document,"pdp11","computer"),b=0;b<a.length;b++){var c=B(a[b]);(c=Wa("Computer",c.id))&&c.o.R&&ug(c,!(!c.b||c.m),!0)}});function O(a,b,c){this.id=a.id;this.key=xg(a,b,c);this.H=a.H;pg(this,a.Jc)}function xg(a,b,c){a=a.id;if(b){var d=b.indexOf(".");0<d&&(a+=".v"+b.substr(0,d))}c&&(a+="."+c);return a}
O.prototype={constructor:O,set:function(a,b){try{this[this.id][a]=b}catch(c){}},get:function(a){return this[this.id][a]||null},value:function(){return this[this.id]},data:function(){return this[this.id]},toString:function(){var a=this[this.id];return"string"==typeof a?a:JSON.stringify(a)},clear:function(a){pg(this);var b=[];try{for(var c=0,d=window.localStorage.length;c<d;c++)b.push(window.localStorage.key(c))}catch(e){}for(c=0;c<b.length;c++)if((d=b[c])&&(a||d.substr(0,this.key.length)==this.key)){try{window.localStorage.removeItem(d)}catch(e){}b.splice(c,
1);c=0}}};function pg(a,b){a[a.id]={};b&&a.set("parms",b);a.a=!1}function qg(a){var b=!0;if(xa()){var c=JSON.stringify(a[a.id]);Ba(a.key,c)||(w("Unable to store "+c.length+" bytes in browser local storage"),b=!1)}return b}function ng(a){var b=!0;try{a[a.id]=JSON.parse(a[a.id])}catch(c){w(c.message||c),b=!1}return b}function jg(a,b){return b?(a[a.id]=b,a.a=!0):a.a?!0:xa()&&(b=ya(a.key))?(a[a.id]=b,a.a=!0):!1}var yg=0;
function zg(a,b,c,d,e,f){e("Loading "+a+"...");t(a,null,!0,function(g,k,l){l?(k||(k="unable to load "+a+" ("+l+")"),f(k,null)):Ag(k,a,b,c,d,e,f)})}
function Ag(a,b,c,d,e,f,g){function k(a,f){if(f)g(f,null);else{c&&(Ua(c,b,a),(f=b)&&0>f.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(f=window.location.pathname+f),d?"}"==d.slice(-1)?(d=d.slice(0,-1),1<d.length&&(d+=",")):d='{state:"'+d+'",':d="{",d+='url:"'+f+'"}',"object"==typeof resources&&(f=null),a=a.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(d?" parms='"+d+"'":"")+(f?' url="'+f+'"':"")));e||(a=a.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1PDPjs$2"),
a=a.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1pdp11$2"));f=null;if("<"==a.charAt(0))try{e||(a=a.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(f=new window.ActiveXObject("Microsoft.XMLDOM"),f.async=!1,f.loadXML(a)):f=(new window.DOMParser).parseFromString(a,"text/xml")}catch(p){f=null,a=p.message}else a="unrecognized XML: "+(255<a.length?a.substr(0,255)+"...":a);g(a,f)}}a?e?Bg(a,f,k):k(a,null):g("no data"+(b?" for file: "+b:""),null)}
function Bg(a,b,c){var d;if(d=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(a)){var e=d[2];b("Loading "+e+"...");t(e,null,!0,function(f,g,k){if(k||!g)c(a,"unable to resolve XML reference: "+d[0]+" ("+k+")");else{if(f=d[3])if(k=g.match(new RegExp("<"+d[1]+"[^>]*>"))){for(var l=k[0],n,p=/( [a-z]+=)(['"])(.*?)\2/g;n=p.exec(f);)l=0>l.indexOf(n[1])?l.replace(">",n[0]+">"):l.replace(new RegExp(n[1]+"(['\"])(.*?)\\1"),n[0]);k[0]!=l&&(g=g.replace(k[0],l))}else{c(a,"missing <"+d[1]+"> in "+e);return}g=g.replace(/<\?xml[^>]*>[\r\n]*/,
"");a=a.replace(d[0],g);Bg(a,b,c)}})}else c(a,null)}
function Cg(a,b,c,d){function e(a){if(void 0===k){var b=g&&D(g,"machine-warning");k=b&&b[0]||g}k&&(k.innerHTML=oa(a))}function f(a){e("Error: "+a);l&&(--yg||La(!0));l=!1}var g,k,l=!0;yg++;Ta[a]={};try{if(g=document.getElementById(a)){var n;if("object"==typeof resources&&(n=resources.css)){var p=document.head||document.getElementsByTagName("head")[0],u=document.createElement("style");u.type="text/css";u.styleSheet?u.styleSheet.cssText=n:u.appendChild(document.createTextNode(n));p.appendChild(u)}c||
(c="/versions/pdpjs/1.30.4/components.xsl");n=function(d,k){k?zg(c,null,null,!1,e,function(d,l){l?(Ua(a,c,d),e("Processing "+b+"..."),window.ActiveXObject||"ActiveXObject"in window?(l=k.transformNode(l))?(g.outerHTML=l,--yg||La(!0)):f("transformNodeToObject failed"):document.implementation&&document.implementation.createDocument?(d=new XSLTProcessor,d.importStylesheet(l),(l=d.transformToFragment(k,document))?g.parentNode?(g.parentNode.replaceChild(l,g),--yg||La(!0)):f("invalid machine element: "+
a):f("transformToFragment failed")):f("unable to transform XML: unsupported browser")):f(d)}):f(d)};"<"!=b.charAt(0)?zg(b,a,d,!0,e,n):Ag(b,null,a,d,!1,e,n)}else f("missing machine element: "+a)}catch(v){f(v.message)}return l}window.embedPDP11=function(a,b,c,d){La(!1);return Cg(a,b,c,d)};window.enableEvents=La;window.sendEvent=Ma;})();//# sourceMappingURL=/tmp/pdpjs/1.30.4/pdp11.map
